### ISSUE TITLE
Missing landowners/sites

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#100]
For project 1: There's only 1 site listed despite every deployment being associated with a site on the deployments page: https://motus.org/data/project/sites?projectID=1

it almost looks like the table just won't load properly, the page shows the first record for ID 1174, site Anderson, but the table goes blank at lat/lon, I tried reloading the page and then nothing came up.  I tried this on a mac and a PC, chrome, safari, firefox, explorer.

Also, didn't landowners used to show up on receiver deployment pages?  Is there a reason this was removed?

**Comment by StuMackenzie** [comment]
If we’re talking about the same thing, I think landowner contacts was removed from ‘public’ views for privacy concerns. Some landowners may wish to be recognized at the station level however.

**Comment by zcrysler** [comment]
but only logged in users can see their receiver deployment pages, which used to include a dropdown menu for site and landowner.  So that when you create a new deployment you can link it to an existing landowner.  There doesn't seem to be a way from the landowner page to link to a deployment, so from what I'm seeing now, I can't add a landowner to any existing or new deployments

**Comment by pmorrill** [comment]
Zoe: this is due to a bug that was triggered by a landowner you have in project 1. Name was tester (first) and blank lastname. I added a surname (Test) and it restored the sites page.

I will reproduce in sandbox and put in a fix so that this does not happen when a surname is missing.
