### ISSUE TITLE
New Lotek Tag Model

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#1002]
Hey J-Dawg, 

Lotek has asked me to create a new tag model for them. As part of that they also sent me some addition lifespan details on all the NTQB2 tags. 

As such I re-ran all of them through the tag lifespan model and got updated D and rt values. They have changed very little, but I figured I would update the values in the DB anyway. 

I've updated lk_tag_models in sandbox and live. Can you do the same for tagfinder? The new tags is NTQB2-9-2

![image](https://user-images.githubusercontent.com/22172758/129787180-bf2436ba-5e40-4318-aea1-6bd9fa61c4ce.png)

**Comment by cjardine-bsc** [comment]
use Model "NTQB2-9-2-M" please

**Comment by Hussell** [comment]
I'm mapping both "NTQB2-9-2" and "NTQB2-9-2-M" to the same (new) battery "2-9-2", which is how the -M suffixes are handled over there.

For the batteries, I need the burst interval, duty cycle, lifespan triples from which you calculated the table above. Here's what I already have:
Battery|Burst Interval|Duty Cycle|Lifespan
-|-|-|-
2-1| 3|1| 19
2-1| 7|1| 39
2-1|13|1| 63
2-1|29|1|103
2-2| 3|1| 29
2-2| 7|1| 60
2-2|13|1| 97
2-2|29|1|159
2-3-2| 3|1| 67
2-3-2| 7|1|140
2-3-2|13|1|224
2-3-2|29|1|367
2-4-2| 3|1|134
2-4-2| 7|1|280
2-4-2|13|1|449
2-4-2|29|1|735
2-5-1| 3|1|53
2-5-1| 7|1|111
2-5-1|13|1|178
2-5-1|29|1|291
2-6-1| 3|1| 190
2-6-1| 7|1| 397
2-6-1|13|1| 636
2-6-1|29|1|1042
2-6-2| 3|1| 359
2-6-2| 7|1| 749
2-6-2|13|1|1203
2-6-2|29|1|1969

**Comment by Hussell** [comment]
OK, this is done.
