### ISSUE TITLE
Accommodating SRX 1200 detection data format

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1004]
Project 391 is trying to upload a .DTA file from a Lotek 1200 (which isn't in the DB, though its serial format appears to fall under the existing regex).

When the data file is uploaded the message says that no receiver serial is found in the data file. The file does appear to be formatted a bit differently than other SRX .DTA files, but I haven't actually seen all that many. 

> File uploaded: 19829_2021-08-17T13-34-19.404_Lotek-D0020158.dta
> 
> There is a delay between the time this job finishes and the time when the newly processed data appears on the website and is available through the R package, which varies depending on how much data has been processed recently. Typical delays are ~20 minutes, but can be several hours (or more) if a lot of other processing is going on. Also, please note that detections on the website are filtered, so you may not be able to see every detection there. Unfiltered data is available through the Motus R package. (See https://motus.org/MotusRBook/)
> Error: Error in lockSymbol(serno): invalid symbol NA
> 
> Error: Error in lockSymbol(serno): invalid symbol NA
> 
> 
> NA: no deployments are known in this project for this receiver. Please enter a deployment for this receiver at https://motus.org/data/project/recvs?projectID=391.

       
> Sub Jobs:
> Job ID 	Type 	Created 	Status 	Parameters
> 8235284 	uploadFile 	2021-08-17 13:34:20.440Z 	Okay 	filename = Lotek-D0020158.dta; uploadID = 79517; replyTo = jsayers@birdscanada.org
> 8235285 	sanityCheck 	2021-08-17 13:34:22.642Z 	Okay 	dir = /sgm/queue/2//08235284
> 8235286 	queueArchives 	2021-08-17 13:34:22.667Z 	Okay 	dir = /sgm/queue/2//08235284
> 8235287 	newFiles 	2021-08-17 13:34:22.691Z 	Okay 	
> 8235288 	uploadProcessed 	2021-08-17 13:34:22.753Z 	Okay 	
> 8235289 	LtFiles 	2021-08-17 13:34:22.908Z 	Okay 	
> 8235290 	LtFindtags 	2021-08-17 13:34:23.319Z 	Error 	serno = null; tsStart = Inf
> 8235291 	exportData 	2021-08-17 13:34:23.347Z 	Error 	serno = null
> 8235292 	plotData 	2021-08-17 13:34:23.369Z 	Okay 	serno = null; ts = Inf,-Inf
> 
>         Logs by subjob:
> Log for 8235284
> 
> Job 8235284 with 1 pending subjobs entered processing queue #2
> Warning: file 19829_2021-08-17T13-34-19.404_Lotek-D0020158.dta contains no serial number.
> Its Site Code is  NA  which might be its serial number
> but I can't find a deployment name for that receiver
> which matches ` 198 `,
> so I will not process this file
> 
> Log for 8235290
> 
> Running tag finder on receiver NA
> Error: Error in lockSymbol(serno): invalid symbol NA
> 
> 
> Log for 8235291
> 
> Error: Error in lockSymbol(serno): invalid symbol NA
> 

      

 https://sgdata.motus.org/status?jobID=8235284

**Comment by denislepage** [comment]
The issue appears to be with the file name, not its content.  The handleNewFiles.R script in motusServer would suggest that the DTA extension is case-sensitive and should be uppercase. The fact that the receiver is not even listed in the /sgm/file_repo folder suggests that tag finder doesn't even attempt to open the file and doesn't know what to do with it. All the archives I am looking at use uppercase DTA, not dta, so I don't know if this is a new thing that Lotek did, or the user renamed it. 

It this is the source, then we should change the code to make this case-insensitive on the extention, at the very least.

A quick test would be to reupload the file after renaming it from .dta to .DTA. If the file is zipped, that small change I think will be enough to give it a new signature during the upload.

**Comment by jsayers-bsc** [comment]
changing the extension didn't seem to do anything. Same error message as before.

**Comment by Hussell** [comment]
It seems to be a significantly different file format. I've looked through the code for handling Lotek files, and I don't see anything which matches what's in the files. Even the line which states the serial number of the receiver uses a different label, which is why we're getting an error message "file <X> contains no serial number."

Are there any options on the receiver end to produce output in an older, compatible file format? If not, I'm going to have to write some R code to parse this new format, without knowing what the format is.

**Comment by denislepage** [comment]
Is this the first time we’ve dealt with this receiver model? We may need to check with Lotek whether their output format has changed, and try to get some clarity on the changes they have implemented.  The alternative is that the output format is optionally controlled by the user, but I’m not familiar with that interface.

A bigger concern would be if they made a firmware change that could be applied to earlier models as well.

**Comment by Hussell** [comment]
It's the first time I've heard of it. The serial number seems to be from a new series too: Lotek-D0020158 (7 digits instead of 6, and so far the largest number has been Lotek-D001082).

**Comment by denislepage** [comment]
I missed that details (7 vs. 6 digits). That would explain the initial error message saying that the receiver serial number can’t be extracted from the file name.

As a minimum, we’ll need to adjust the motusServer code to include that pattern. But there may be more issues to resolve if the content formatting has significantly changed.

We’ll also need to add the receiver type in our database, with the appropriate regex pattern, and we should ask Lotek what that pattern is.

The closest pattern we have now is the SRX DL: ^(Lotek-8\d{3})|(Lotek-D\d{6})$

This would work with the above serial:  ^Lotek-D\d{6,7}$

**Comment by jsayers-bsc** [comment]
Lotek has indicated they will offer an option for SRX1200 users to export in the same DTA format as the SRX800.

**Comment by denislepage** [comment]
Thumbs-up!

**Comment by jsayers-bsc** [comment]
The two files have been processed, though each had a different error. 

Job 10218883:

> Error: Error in rawToChar(.): embedded nul in string: 'SRX1200 Data formatted as SRX800 Legacy DTA\r\nSRX1200 / 1200D Information:\r\nEnvironment History:\r\nchanged: 07/22/21  23:58:16\r\n\r\nMaster Firmware: V1.2.1480.7\r\nSlave Firmware:  V1.0.998.1\r\nReceiver S/N:    D0020107\r\n\r\nActive Configuration: 1\r\nSite Code: 0000\r\nCode Set: Lotek3\r\n\r\nANTENNA GROUP:\r\nAntenna      Gain\r\n  A0          86\r\n  A0          86\r\n  A0          86\r\n  A0          86\r\n\r\nMaster Antenna: A1+A2+A3+A4\r\nMaster Antenna Gain = 50\r\n\r\n# Antennas = 4\r\n\r\nSCAN SETTINGS:\r\nScan Time = 0:15.0\r\nTotal Scan Time = 0:0:0\r\nMaster Priority Scan: disabled\r\nScan Priority: Frequency\r\nAGC OFF\r\nTOA Disabled\r\nGPS Clock ON\r\n2D Positions Stored\r\nAntenna - AS4\r\n\r\nActive scan table:\r\nCHANNEL  FREQUENCY   STATUS     TYPE         \r\n   1      166.380    Enabled    ID Tag       \r\n\r\nNoise Blank Level: 10\r\nSignal Deviation Filter: DISABLED\r\nPulse Width Filter: ENABLED\r\nMinimum Pulse Width: 2.0 ms\r

Glancing at that it appears that the new format is not identical to the 800 format. At least, there is a different first line, though maybe that's not important. 

Job 10218792:

> Error: Error in moveFilesUniquely(rv$fullname[iMove], file.path(MOTUS_PATH$FILE_REPO, : In moveFilesUniquely, failed to successfully move: /sgm/queue/3//10218792/10239433/24532_2021-10-28T15-38-32.860_SRX1200_800_NAV_D0020158_7-26-2021.DTA

That may be due to some issue other than formatting?

**Comment by Hussell** [comment]
Yes, the second error is something I've seen before and know how to deal with, but haven't yet managed to fully diagnose and fix. It only happens to (some) new Lotek receivers, and the proximate cause is that the new directory in /sgm/file_repo doesn't get created, and then this error happens when it tries to move the newly uploaded files to there anyway.

So, the second one worked after I created the directory and reran, but the first one didn't. There are indeed NULL characters in the first file, which should never be present. They're on line 66, which begins "Site Code: 1", then there are 3 NULL characters, then the regular newline and the rest of the file. That might be a genuine bug on the other end?

**Comment by j-sayers** [comment]
Everything seems to be working here. Lotek fixed the NULL issue and uploads have been tested by a few projects.
