### ISSUE TITLE
Batch of likely false positives

### ISSUE THREAD

**Issue by adamdsmith** [MotusDev/Motus-TO-DO#1013]
Just noticed a batch of bad "detections" at a receiver on 22 Sep 2021: https://motus.org/data/receiverDeploymentDetections?id=5938

I've not inspected closely but it looks likely a bunch of radio noise through some false positives. Shouldn't be aliasing.

If there's a more preferred approach to reporting these types of events, please let me know.

**Comment by leberrigan** [comment]
Thanks Adam. I agree this looks like a noise event. We've been picking away at these as they come up so it's helpful to hear about them, but it can also clutter our Git issues. If you find anything else, maybe keep posting in this thread to keep things organised. Alternately, you can post findings in our Slack channel: https://motuswts.slack.com/archives/C01LHLS17PW

![image](https://user-images.githubusercontent.com/35931796/135864163-d3c3af05-14fc-494c-89db-5d9d2c16b574.png)

**Comment by jsayers-bsc** [comment]
@adamdsmith Thanks for the heads-up; we've filtered those out of public view. As a reminder, these detections will all show up still in the R package, but will have `motusFilter == 1`. For reference, a bit of discussion about flagging in this way in #749 and #853
