### ISSUE TITLE
Rogue CTT projects

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#1020]
Background:

Non-Motus CTT sensorstations and tags are still being pushing to Motus. Tag data is inconsequential if it isn't assigned to a project.

Receiver data matters because it often contains detections of registered tags.

**ACTION** - need to figure out if and how we provide these data to users.

@leberrigan do you mind looking at which device ID's he has detections from that aren't registered. Project 310. We can then followup with CTT with a good example, or even get that device registered.

Copy and paste of first correspondence with users that noticed for reference

Hi Jeff,

responding privately for the moment. 

These detections are valid, but they come from devices that, for one reason or another, haven't been registered with Motus.

The information we have on those is limited to what you see in the data. GPS location, timestamp and tag ID.

We are looking into how potentially create partial metadata records for these receivers based on the data we have, and see if we can encourage at least some of those projects to provide a bit extra details.

We're not quite ready to share this more broadly, just because we haven't settled yet on the approach we'll use, and CTT also needs a bit of time to think about how they will be able to tackle the data flow on their end.

But, there's no reason to think that these are any less valid detections.

Cheers
Denis

Denis Lepage dlepage@bsc-eoc.org
Senior Director, Data Science and Technology Birds Canada

-----Original Message-----
From: Jeffrey Buler [mailto:jbuler@udel.edu]
Sent: 7-Oct-21 12:31
To: Motus Wildlife Tracking System
Subject: Detections with no reciever information

------=3D_Part_1308_1893019347.1633624249236
Content-Type: multipart/alternative;=20
	boundary=3D"----=3D_Part_1309_1833435696.1633624249236"

------=3D_Part_1309_1833435696.1633624249236
Content-Type: text/plain; charset=3DUTF-8
Content-Transfer-Encoding: 7bit

Hi all,

I have downloaded thousands of detections of my deployed tags at 434 MHz=20 that are from receivers that only have a deviceID (i.e., no recvDeployID or=
=20
other associated receiver information). Many of these seem like legitimate=
=20
detections with long runs. Are these detections from receivers that are not=
=20
in formal deployments or not registered to Motus? Or are they faux=20 detections? Does anyone know of a way to track down information about the=
=20
reciever from just the deviceID? Or is this data that is simply not usable?

Thanks much,
Jeff Buler
University of Delaware

------=3D_Part_1309_1833435696.1633624249236
Content-Type: text/html; charset=3Dutf-8
Content-Transfer-Encoding: 7bit

Hi all,<div><br></div><div>I have downloaded thousands of detections of my = deployed tags at 434 MHz that are from receivers that only have a deviceID = (i.e., no recvDeployID or other associated receiver information). Many of t= hese seem like legitimate detections with long runs. Are these detections f= rom receivers that are not in formal deployments or not registered to Motus= ? Or are they faux detections? Does anyone know of a way to track down info= rmation about the reciever from just the deviceID? Or is this data that is = simply not usable?</div><div><br></div><div>Thanks much,</div><div>Jeff Bul= er</div><div>University of Delaware</div>
------=3D_Part_1309_1833435696.1633624249236--

------=3D_Part_1308_1893019347.1633624249236--

**Comment by leberrigan** [comment]
Moving this to discussion since we need to sort out a way to deal with these before we make make an issue.
