### ISSUE TITLE
Overlapping deployments on same receiver

### ISSUE THREAD

**Issue by ajmacdonald3** [MotusDev/Motus-TO-DO#1023]
Receiver CTT-72A787D1C983 (Device ID 1915) has two concurrent deployments: [deployID 7702](https://motus.org/data/receiverDeployment?id=7702) and [deployID  8204](https://motus.org/data/receiverDeployment?id=8204). From what I can figure out, 7702 is a test deployment that was never terminated. Then the deployment at Rocky Point Bird Observatory was started. Since the test deployment was ongoing, all the [NSWO detections](https://motus.org/data/receiverDeploymentDetections?id=7702) that should be under the Rocky Point deployment ended up on the test deployment. Can we terminate the test deployment and move all the BC NSWO MOTUS (project 434) tag detections over to the 8204 Rocky Point deployment?

**Comment by denislepage** [comment]
The detections will be relinked offline once you update the metadata. There will be a bit of a lag, depending on what else is happening in the queue, but in theory, all is needed is to update the metadata and the rest is automated. Might not be a bad idea to confirm after the proc completed.

Are you able to make this change yourself Amie?

**Comment by ajmacdonald3** [comment]
Yes, will do. Didn't realize it was that simple, thanks!
