### ISSUE TITLE
Repeated timing out in R

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#1025]
For the last day or two I have been unable to download any data via the R package. I just keep getting the "server timed out" error. I've also heard from several collaborators that they have can't download their data either.

**Comment by jsayers-bsc** [comment]
Same thing since yesterday afternoon

**Comment by ajmacdonald3** [comment]
I've been having this problem for the last couple days. I haven't been able to download any data through the R package.
