### ISSUE TITLE
Station status and workflow

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1026]
In light of our conversation last week and what has continued into the email thread, I have outlined our conclusions here so we can clearly define which changes need to be implemented.

# For Paul

## Notes
- We decided to eliminate user controls to edit the station status directly and instead interpret the status based on two fields: `anticipated_date` and `station_status`.
- Paul will no longer set `station_status` using this form, but will instead read `station_status` to set the behaviour.
- `station_status` can only be: **0** (no deployments, or 'pending'); **1** ('active'); or **2** ('terminated').

## Creating or modifying a station
 - [ ] Default `station_status` is `pending` (i.e., no deployments)
 - [x] Remove station status dropdown
 - [x] Add text fragment for `anticipated_date_instructions`, to be included after header or as an info bubble
    - E.g.:  ![image](https://user-images.githubusercontent.com/35931796/138341407-cc54063a-0257-4a33-a294-a82c5c01293c.png)
    > If you know when this station will be deployed, enter the date here. This can be in the past if the station has already been deployed, or in the future if you anticipate deploying the station another time. It's okay if the future date isn't precise. If you don't have plans to deploy here, leave this field blank to indicate this location is available. 

 - [x] If `station_status == "active"`:  hide `anticipated_date` field
 - [ ] On form submit: 
     - If `station_status == "pending" || station_status == "terminated"`: 
        - If `anticipated_date` is in the past or present: 
          - Send user to create a new deployment
        - If `anticipated_date` is in the future or blank: 
          - Alert: _"Don't forget to create a new deployment if you deploy this station!"_

## Terminating a deployment
- [ ] Replace 'Terminate' button with two buttons and question: 
  - Question: _"Will this station be redeployed"_
  - Answers: 
    1. **YES**
       - Show similar controls to above:
         - Header: _"Prospective start date:"_
         - Input: `anticipated_date` field
          - On form submission:
            - If `anticipated_date` is in the past or present: 
              - Send user to create a new deployment
            - If `anticipated_date` is in the future or blank: 
              - Alert: _"Don't forget to create a new deployment if you deploy this station!"_
    3. **NO**
       - `anticipated_date` is set to `NULL`
       
![image](https://user-images.githubusercontent.com/35931796/138335023-74785656-9957-4e92-9e2f-a7f992d70378.png)

# Details for everyone else
## Notes:
 - We have decided to eliminate the 'deprecated' flag entirely.
### If NO deployments exist (e.g.: creating a new station)
  1. **`anticipated_date`**
    - Equal to the user-entered value in station properties (can be blank)
  2. **Status**
    - If `anticipated_date` is in the past or present, the station is treated as 'pending' since no deployments exist
    - If `anticipated_date` is in the future or blank, the station is treated as 'prospective'
  3. **On form submission**
    - If `anticipated_date` is in the past or present, send user to create a new deployment
    - If `anticipated_date` is in future or blank, the user is advised to create a new deployment once the station has been deployed (alert message is probably fine)

### If ANY deployments exist
  1. **`anticipated_date`**
    - Cannot be modified if `station_status` is `active`.
  2. **Status**
    - Station status is equal to the status of the latest deployment UNLESS inactive.
    - Inactive stations without an anticipated start date are treated as 'available'.
    - Station can be 'deprecated' to retire it from the list of possible stations, but all deployments must first be terminated.
      - Can be undone.
 
## Terminating a station deployment 
  - Ask the user: "Will this station be deployed again in the future?"
    - **YES**
      - "When will the station be deployed again?"
      - Include similar fields and behaviour to when creating a new station above:
         1. **`anticipated_date`**
            - Equal to the user-entered value in station properties (can be blank)
         2. **Status**
            - If `anticipated_date` is in the past or present, the station is treated as 'pending' since no deployments exist
            - If `anticipated_date` is in the future, the station is treated as 'prospective'
            - If `anticipated_date` is in the blank, the station is treated as 'available'
         3. **On form submission**
            - If `anticipated_date` is in the past or present, send user to create a new deployment
            - If `anticipated_date` is in the future or blank, the user is advised to create a new deployment once the station has been deployed (alert message is probably fine)
    - **NO**
      - No more actions

**Comment by pmorrill** [comment]
@leberrigan : I made a change late yesterday, so that if you are changing the properties of a station, the following rules apply:

  * If you use 'Save' - no changes to behaviour
  * If you use 'Save and exit' you **may** be directed to the receiver selection page to set up a new deployment
  
Whether you land on the recv selection page depends on:

  - the 'prospective_start_date' must be non-null and be in the past or the present day
  - there must be no prior deployments on the station

That 2nd conditional means that a station does not have to be strictly speaking 'new' for this behaviour to kick in. This takes care of a situation where you create a new station, but use the 'Save' option, then the 'Save and Exit' option. By the time you use 'Save and Exit' the station is no longer technically 'new' (you created the Station when you hit 'Save'). Alternatively, you could come back to an existing station and set the prospective start date, and though the station is not 'new', you probably still want the user directed to the recv selection page if the above two conditions are met.

Try this out, and then consider the changes needed to the instruction esp. surrounding the 'prospective_start_date' field.

**Comment by leberrigan** [comment]
@pmorrill : This looks great. I'll think about the wording there, but that's what we want to happen.
