### ISSUE TITLE
Access level insufficient message when viewing tag timeline

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1030]
Someone from Project 231 reported being unable to view the detection timeline for a particular tag.

Lucas and I can view it fine from our own accounts, but when we assume his, or even the project PI account, this particular timeline cannot be viewed to the "insufficient access level".

https://motus.org/data/tag/deployment/detections/timeline?year=2019&id=20210

![image](https://user-images.githubusercontent.com/55001144/138740634-17c75f3a-80a0-46a0-ba8d-2588981c466e.png)

The table and map both show fine. ~~I clicked through on a few and this was the only tag deployment I saw with this issue.~~

**Comment by Hussell** [comment]
The fix for this is in the live branch now, it's only waiting for deployment.
