### ISSUE TITLE
Duplicate detections - Cordova. Project 199 and 336

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#1032]
Related specifically to deployment - https://motus.org/data/receiverDeployment?id=7659

"it appears for every tag detected it is outputting two duplicate detections: one for "Pacific Shorebirds" and one for "CWS-PacificStations" (as per the "recvProjName" field). It looks like 26 tags have been affected."

[dupsCordova.csv](https://github.com/MotusDev/Motus-TO-DO/files/7421214/dupsCordova.csv)

**Comment by leberrigan** [comment]
@ajmacdonald3 do you know if this has been resolved?

**Comment by ajmacdonald3** [comment]
I think so, I resolved a duplicate tag registration issue for them. I'll double check.
