### ISSUE TITLE
Missing data from deployed tag 36845 at station 7251

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#1033]
Tag - https://motus.org/data/tagDeployment?id=36845

Was deployed at station https://motus.org/data/receiverDeployment?id=7251, but there are no detection appearing of it there?

I changed the deployment to one day prior in case the metadata was cutting the detections short.

@Hussell can you take a look, rerun, and see what you think?

**Comment by Hussell** [comment]
I finally had a chance to rerun this. No change. Looking at the track for the tag (https://motus.org/data/track?tagDeploymentId=36845) it looks like the bird was on migration. I'm not sure why it was never detected at the tagging site, possibly it was foraging at ground-level until it reached the tip of the point? The receiver looks like it's operating normally, with detections of tags both before and after Oct. 4th when the bird was tagged.

**Comment by StuMackenzie** [comment]
hmmm....
