### ISSUE TITLE
Unresolved Beta10 issues

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1034]
Peeling off the unresolved comments from this beastly thread (#994) ...

### **Changes** 

- [ ] Start with #1026 

- [x] Links to station and landowner management pages should work without project ID.
   - In the header menu dropdown, this link doesn't work: https://beta.motus.org/data/project/stations
   - If you provide a station ID but no project ID, it also doesn't work: https://beta.motus.org/data/project/stations?setStationId=7005
![image](https://user-images.githubusercontent.com/35931796/139481271-612d6567-3273-4bac-a6e5-27855364e53c.png)

 - [x] Copy the map button from the receiver management page to the station management page. Place it next to 'Manage your receivers' button on stations page. 
 
![image](https://user-images.githubusercontent.com/35931796/139482444-9b17a16b-8c15-45b5-8340-9bcafafe25d4.png)

- [x] Station map should default to 'active' instead of 'all'.

- [x] Order of longitude and latitude on both the station overview and station properties should be swapped (latitude first, then longitude). By convention it's latitude then longitude. Also add labels (latitude/longitude) to station overview location: 
![image](https://user-images.githubusercontent.com/35931796/139483384-49b0734c-34f6-4bb5-9f39-234461f2bdb5.png)
![image](https://user-images.githubusercontent.com/35931796/139483443-803107b5-64e0-4ce9-87db-d948dc2e499e.png)

- [x] When creating a new deployment the only button at the bottom is "Cancel". It should only say "Cancel" when in edit mode, otherwise it should say "Close".

- [x] Maybe need a No_active_deployments_msg text fragment that is unique for tags? 
For now I just changed the fragment to "No active deployments for this station or tag", but that's probably not ideal
    - Use 'No_active_tag_deployments_msg' instead on this page: https://beta.motus.org/data/project/tags?projectID=109
![image](https://user-images.githubusercontent.com/35931796/139484683-64c882ae-7046-40d4-b867-ed59d6e39bbb.png)

- [x] Remove 'Add deployments' button for tags that already have an active deployment.

- [x] Table in tag summary panel  should have deployment dates formatted the same as the main table: i.e., the calculated end dates should be greyed out, etc.

- [x] Display deprecated status on tag overview. Currently it's only visible by clicking "modify tag". E.g.: 
![image](https://user-images.githubusercontent.com/35931796/139486500-91bbe410-dea0-41ad-82d2-9b4155d0031d.png)

- [x] Don't show Most Recent Config details for Test stations. e.g. https://beta.motus.org/data/project/stations?projectID=1&setStation=5377

![image](https://user-images.githubusercontent.com/55001144/141357103-d8323189-316f-4afd-89ec-c0ddc53133c1.png)

- [ ] Add link to tag deployment detection summary (e.g. https://motus.org/data/tagDeploymentDetections?id=22528) in the Manage Tags tag overview section page (the right hand side). "Atatchment type" isn't the most useful here so maybe the link could take the place. Or add it as a second line to, say, the deployment range field.

### **Bugs**
- [ ] Terminating a station deployment with a date that's **_before_** the start date, it produces the below developer error. Can we change the behaviour to produce a user and reject the form submit?
![image](https://user-images.githubusercontent.com/35931796/145456632-da1cdbb6-f15a-40d2-a3dd-994c646af3de.png)

- [ ] [When adding a new deployment to a station with no previous deployments, you can't set the deployment configuration because 'an existing deployment overlaps with this one'](https://github.com/MotusDev/Motus-TO-DO/issues/1034#issuecomment-979444208)
- [ ] [Stations with no deployments have two 'Create new deployment' buttons with the top one producing a dialogue with blank buttons.](https://github.com/MotusDev/Motus-TO-DO/issues/1034#issuecomment-979430244)

- [x] Adding a new landowner fails.

- [x] On station deployment page: Add hidden latitude and longitude fields back in with the names 'latitude' and 'longitude' respectively. (this is to fix 'view antenna map' button).

- [x] When trying clicking on 'terminate this deployment' while viewing a station that has a single quotation mark in it ('), nothing happens and a js error is thrown: 

- [x] Different dates on Station map (when hovering over a station) and on overview (looks like the map is reporting local timezone?)

**Comment by pmorrill** [comment]
`Remove 'Add deployments' button for tags that already have an active deployment.`

Can you give me a specific example where this button is still visible despite an active deployment? The deployment is considered active if a) it has a null termination date, **and** b) it is still within it's expected lifespan (dtEndCalc field)

**Comment by pmorrill** [comment]
`Display deprecated status on tag overview. Currently it's only visible by clicking "modify tag". E.g.:`

Hmm.... in your screen shot there is a large 'Deprecated' text beside the tag id.....

**Comment by leberrigan** [comment]
![image](https://user-images.githubusercontent.com/35931796/143491302-872d8e2b-08c0-48a9-a99c-bb05d3e2e3ff.png)
![image](https://user-images.githubusercontent.com/35931796/143491524-9bcb166e-62a8-4604-b83f-ff26e31a9f35.png)

**Comment by pmorrill** [comment]
I noticed that this AM and put a fix in already.

**Comment by leberrigan** [comment]
When creating a new deployment for a station with no previous deployments, saving the deployment configurations because "An existing deployment of this tag or receiver overlaps the dates that you are using.":
![image](https://user-images.githubusercontent.com/35931796/143493004-44a01468-a9e1-4a16-94c9-85303dac3b1d.png)

**Comment by pmorrill** [comment]
I can't reproduce this issue in my system. The validation test looks to see if the recv is currently deployed within any project (meaning a receiver cannot be active in 2 projects at once: this may need changing).

I have made an adjustment to simplify the test query, to use ''vwBase_receivers_deployments''

**Comment by leberrigan** [comment]
@pmorrill Added to checklist above: 
Terminating a station deployment with a date that's **_before_** the start date, it produces the below developer error. Can we change the behaviour to produce a user and reject the form submit?
![image](https://user-images.githubusercontent.com/35931796/145456632-da1cdbb6-f15a-40d2-a3dd-994c646af3de.png)

**Comment by pmorrill** [comment]
I have just improved validation of the end date when terminating, so this error will be handled properly.

**Comment by StuMackenzie** [comment]
FYI. Updates are live on the site, but we haven't posted to the Motus Group yet.
