### ISSUE TITLE
Unable to browse sgjobs

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1035]
I can't seem to access SG jobs via `https://sgdata.motus.org/status` any longer. I'm not sure what is going on, but it seems like there's a difference in behaviour between browsers (Firefox 93.0 vs. Chrome 95.0.4638.69). 

---
This has been an ongoing issue for a few months now, although I have been able to access sgjobs half the time but only via Chrome. The past few weeks, however, Chrome hasn't worked either. 

Just to to make sure it's not a caching issue, I disabled caching and reloaded the page in both browsers and got the same error. 

---
Sometimes (rarely) I get this error: 
Most of the time I get this error: 

# Rarely I get this error
```
502 Proxy Error

Proxy Error
The proxy server received an invalid
response from an upstream server.
The proxy server could not handle the request POST /status2/get_receiver_info.
Reason: Error reading from remote server

Apache/2.4.10 (Debian) Server at sgdata.motus.org Port 443


        
        The api entry called was:
        
          get_receiver_info
        
        with these parameters:
        
{
   "serno": "CTT-867459049273626",
   "authToken": "(omitted)"
}
        
        and this browser state:
        
{
   "authToken": "(omitted)",
   "selector": {},
   "sortBy": "mtime",
   "sortDesc": true,
   "errorOnly": false,
   "excludeSync": false,
   "lastKey": [],
   "forwardFromKey": true,
   "debug": false,
   "progress_timeout": null
}
      
```

# Usually I get this error

```

503 Service Unavailable

Service Unavailable
The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.

Apache/2.4.10 (Debian) Server at sgdata.motus.org Port 443


        
        The api entry called was:
        
          list_jobs
        
        with these parameters:
        
{
   "options": {
      "includeUnknownProjects": true,
      "full": true,
      "errorOnly": false,
      "excludeSync": false
   },
   "order": {
      "sortBy": "mtime",
      "sortDesc": true,
      "lastKey": [],
      "forwardFromKey": true
   },
   "authToken": "(omitted)"
}
        
        and this browser state:
        
{
   "authToken": "(omitted)",
   "selector": {},
   "sortBy": "mtime",
   "sortDesc": true,
   "errorOnly": false,
   "excludeSync": false,
   "lastKey": [],
   "forwardFromKey": true,
   "debug": false,
   "progress_timeout": null
}
```

**Comment by jsayers-bsc** [comment]
Same issue as #1019? After a brief period of success I'm also unable to access the logs on either Firefox of Vivaldi (Chromium), and as previously and also mentioned by Lucas above, the errors are different depending on the browser. 

Firefox error:

> 
> Proxy Error
> 
> The proxy server received an invalid response from an upstream server.
> The proxy server could not handle the request POST /status2/list_jobs.
> 
> Reason: Error reading from remote server

Vivaldi Error:

> Service Unavailable
> The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by Hussell** [comment]
Reopening #1019 because I'm now reasonably sure these are the same thing.
