### ISSUE TITLE
Can't update metadata-history repository

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#1041]
Github no longer permits the use of DSA keys, which is preventing the metadata-history repository from being updated. This breaks tag registration.

https://github.blog/2021-09-01-improving-git-protocol-security-github/

I'm not familiar with the steps needed to set up a new, different type of SSH key, but I don't think anyone else is either.

**Comment by Hussell** [comment]
GitHub says this is a brownout, and DSA keys will continue to function until March 15th 2022, so we don't have to panic as much as I thought.

**Comment by Hussell** [comment]
Looks like I need access to the MotusWTS GitHub account to update the key.
https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

**Comment by Hussell** [comment]
Denis was correct that MotusWTS is an organization, not a user, and therefore can't have an ssh key assigned. I ended up assigning it to my account after all.

The repository has been moved from https://github.com/jbrzusto/motus-metadata-history to https://github.com/MotusWTS/motus-metadata-history and the automated updates happened normally over the weekend, so it looks like this is done.

**Comment by denislepage** [comment]
Excellent. With almost 4 months to spare before the deadline.
