### ISSUE TITLE
Project Permissions Tooltips broken. 

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#1042]
![image](https://user-images.githubusercontent.com/22172758/140414320-66a00d2c-d314-4b99-b887-41ac5be509c1.png)

The tooltips do nothing on this page: https://motus.org/data/project/edit?id=137 

@Hussell can you look in Paul's absence?

**Comment by Hussell** [comment]
They maybe shouldn't be part of the label, because that makes clicking on one select the option, but hovering over it does produce a tooltip for me.

What browser and OS are you using to view these?

**Comment by Hussell** [comment]
No, wait, the tooltip is on the whole label. The ? glyph is purely cosmetic.

**Comment by cjardine-bsc** [comment]
Oh I'm a Luddite and tried to get it to opening by clicking on the glyph. 

But if I cant figure it out....will all our users?

**Comment by Hussell** [comment]
Honestly, hovering is more of an old-person thing now, because touch-based UI on mobile devices means there's no way to hover a cursor. So, yeah, I should probably make clicking on this bring up a tooltip. It's just annoyingly complicated compared to a regular hover-tooltip...

**Comment by leberrigan** [comment]
This is not even javascript - looks like Paul is using the 'title' tag of the `label` element which is why it takes a second for it to appear. The 

This differs from the tooltips on the management pages which use the title tag of the `img` element and javascript events.

**Comment by Hussell** [comment]
The javascript events on the management pages are from jQuery UI. Adding all of jQuery and jQuery UI to the edit project page just to get a different style of tooltip feels dirty. 374 kB and three extra requests just for that?

**Comment by Hussell** [comment]
The "edit project" page is used very infrequently: when you create a project, and when (if) you ever need to change the settings. As such, I think tooltips are not necessary on this page. There's plenty of space to have fully visible text, and users are likely going to need to re-learn everything every time they visit this page. See https://sandbox.motus.org/data/project/edit?id=137 for a version without tooltips. If you have no objections to that, I'll put it into beta10.

**Comment by cjardine-bsc** [comment]
Hmmmm I'm being picky but I don't really like that. We already arguably have too much text in this section.  Keeping the tooltips is probably cleaner.

**Comment by Hussell** [comment]
lk_securable_bins has some differences between beta/live and sandbox. Could you synchronize them, please? I believe the beta/live versions are the correct ones.

**Comment by cjardine-bsc** [comment]
I can update the content in sandbox (the table definitions are the same) but I don't think that addresses the issue.

**Comment by Hussell** [comment]
Thanks. And you're correct, that was a separate thing.

**Comment by leberrigan** [comment]
At this point I don't think we need to be spending time on this any longer - it's functional we're going to redesign the whole interface soon enough.
