### ISSUE TITLE
vwData_stations

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#1045]
vwData_stations on sandbox should be much more similar to vwData_receivers_deployments than it is right now:
 - rounding of latitude and longitude depending on is_private_sensor
 - accessLevel restricted to administrators when it's a prospective station

When that's done, it would also be handy to have a copy of vwData_stations in the beta/live database.

See https://sandbox.motus.org/data/projectStations?id=1 for a very bare bones prototype table of stations with links to station details pages.

**Comment by cjardine-bsc** [comment]
Why would you like to restrict perspective stations to admins? What are you defining as a perspective station? We have Active, terminated or pending.

**Comment by Hussell** [comment]
Copying how we handle receiver deployments. Pending deployments are not visible to the public, nor are test deployments. So, stations with status = 0 or the test bit set = 1 probably shouldn't be visible to the public either. Project members are still able to see everything, of course.

**Comment by cjardine-bsc** [comment]
hrrm we might want to re-think that for stations. 

If we eventually are considering doing a station planning map, we will want pending sites on that map to be publicly viewable. So I don't think we should use the securable option to filter those. Are you able to filter on status?

**Comment by cjardine-bsc** [comment]
Actually, looking at the page, I can see value in having pending stations displayed there, without much downside. Perhaps we should leave them in. 

Lets leave them for now, and follow up about this on Thursday (though that may be focused on beta 10)
