### ISSUE TITLE
stop import of sandbox data?

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#1047]
Spinning off from thread #1031

In order to streamline some of our operations, we should consider whether to continue maintaining identical processes in both sandbox and live databases.

I say this with some reluctance, but how important is it to keep a copy of the entire set of sg data, really? We could potentially archive those outside of the database, but are they really important? Remember that this is the only complete set that includes all data from deprecated batches.

I know we have discussed this a few times, but the value of sandbox det tables is also somewhat limited. It mostly allow us to develop and test and optimize queries that take into account realistic data volumes. We could in theory stop importing new data, and have plenty already in the table to work from and those tests would probably still be realistic. 

So, my suggestions:
-	stop the import into sg data and delete those tables from the data. We should discuss whether archiving those records would be necessary, but they can be recreated from reprocessing, worse case.
-	stop the import of new data into det tables in sandbox, or at the very least, skip importing the hits and import the rest. For now, keep those tables unchanged.
-	if we want to maintain a full archive of all data, I can modify my import script so it creates a repository of the data (e.g. tar files), but those would be relatively difficult to access and query, and would need to be organized in a meaningful way (e.g. by receiver, and using the batchID)

For DET, the process is a bit different, but the question is similar: do we need a copy of detections in sandbox. Like for SG data, we could stop importing the hits only, or all data into sandbox.

**Comment by denislepage** [comment]
One more thought. Keeping the import going in sandbox, but leaving out the hits data has 1 downside in that it will mean that earlier deprecated records will potentially continue to be deleted, unless we stopped that process from happening in sandbox.

**Comment by leberrigan** [comment]
@denislepage I'm closing this since it seems to be related to a resolved issue. Feel free to reopen.
