### ISSUE TITLE
Receiver deployment edit page does not show current frequencies

### ISSUE THREAD

**Issue by tve** [MotusDev/Motus-TO-DO#1050]
Minor issue:
When editing a receiver deployment (e.g. https://motus.org/data/receiver/deployment/edit?projectID=460&id=8308) the "Receiver frequency" drop-down is unselected, even if the frequency was previously saved. This is annoying because one has to reselect from the drop-down even when changing something unrelated. It can also cause mistakes if the user doesn't remember the freq correctly.

**Comment by leberrigan** [comment]
We have changed to a new interface since this was posted.
