### ISSUE TITLE
logo change on Motus R Book

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#1053]
Not sure who can do this most efficiently.

![BirdsCan_SQ_2col](https://user-images.githubusercontent.com/21124211/143308811-094b5a0b-f857-4939-bda4-533b96af63e1.png)
![BirdsCan_SQ_2col](https://user-images.githubusercontent.com/21124211/143308820-97ebce80-be70-4f29-808b-849cef09318c.jpg)

Por favor

**Comment by steffilazerte** [comment]
Yup, I can do this, urgent for the current version? Or can I add it to the developmental version?

**Comment by StuMackenzie** [comment]
Dev is fine, thanks! I just stumble upon things.

____________________

**Comment by steffilazerte** [comment]
I've added the logos to the README.

Note that the Motus R book will soon (hopefully) be replaced with the new package docs (currently located here https://motusWTS.github.io/motus), which uses the README as the landing page. So we should be go from now.

**Comment by denislepage** [comment]
I like the new book look. I'd be keen to get this pushed out.

I guess we'll need to deprecate the old book repos.

Do we have a way yet to switch language to French? Not sure how much new content will need translation.

**Comment by StuMackenzie** [comment]
Me too, we’re gonna want to change some of the content here which is outdated. I also wonder to what extent and how to maintain authorship and ‘development’ credits.

____________________

**Comment by steffilazerte** [comment]
I should have been more clear: That site has just the original content but in the new format (originally so people could see how it would look), the development site (https://MotusWTS.github.io/motus/dev), has *most* of the new/modified content, but the organization will change a bit, the understanding Motus data will change and there will be another article on signal strength added (that's all in the works, aiming for next week sometime). When that's all done, I'll set up a series of issues and assign people to review the different sections so we can get it out there!
