### ISSUE TITLE
Station Status Map viewable for all projects.

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#1055]
A map of station 'status', date since last download is available to individual projects, but individuals can't view projects that they're not a part of. It would be ideal if there was a single place where anyone could view the status of individual stations. e.g. https://motus.org/data/project/receivers/map?id=1 My preference would be to make this available from the main receiver map (link, box or something) at least until we've rolled out new Explore Data Tools and started to develop new Management tools.

No one knows the map tools exists, partly because it's hidden, partly because we haven't advertised, partly because no one looks. 

Maybe related to https://github.com/MotusDev/Motus-TO-DO/issues/642, but I don't want to confound the issue either.

**Comment by jsayers-bsc** [comment]
Can this styling be available as a toggle on the main receiver map (https://motus.org/data/receiversMap?lang=en)?

**Comment by leberrigan** [comment]
This is coming soon with the explore dashboard
