### ISSUE TITLE
Docs: Review "Complete walk-through"

### ISSUE THREAD

**Issue by steffilazerte** [MotusDev/Motus-TO-DO#1059]
Review the transformation of the original Motus Book to pkgdown articles

**Requirements**
- Review formating (cf. #918)
- Review simplification (i.e. filtering and GPS sections were simplified to move that information other issues: #981 and #1060
- Review clarification of `tagme(..., forceMeta = TRUE)` vs. `metadata()` (cf. #867) in Chp 3 (**Need to be more explicit?**)
- General editorial review

**Resources**
- [Compiled HTML Articles](https://motuswts.github.io/motus/articles/index.html)
- [Rmd files on book-overhaul branch](https://github.com/MotusWTS/motus/tree/book-overhaul/vignettes/articles) (`01-XXX.Rmd`, `02-XXX.Rmd`, etc.)

**How to review:**
- Make git changes directly to "[book-overhaul](https://github.com/MotusWTS/motus/tree/book-overhaul)" branch
- "Review changes" on the [pull request](https://github.com/MotusWTS/motus/pull/12/files) (See [GitHub docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request)). You can make suggestions directly there. 
- Send me a modified Rmd file and I'll incorporate your changes

**Comment by ajmacdonald3** [comment]
Assigning myself to this review.

**Comment by ajmacdonald3** [comment]
https://github.com/MotusWTS/motus/pull/15
