### ISSUE TITLE
inconsistent usage of `receiver ID` on pages for entering receiver metadata

### ISSUE THREAD

**Issue by jbrzusto** [MotusDev/Motus-TO-DO#106]
e.g. in this collage 
![collage](http://public.sensorgnome.org/motus//images_for_github/inconsistent_naming_of_receiver_identification_fields.png)

of two screenshots from these pages:

https://motus.org/data/receiver/deployment/edit?projectID=31&id=4109
https://motus.org/data/receivers/edit?projectID=31&id=2161

the term `receiver ID` is not used consistently.

For most users, the natural identifier of a receiver is the `serial number` or `serno`, which looks like `Lotek-345` or `SG-1234BBBK5678`.  For one thing, it's physically printed on the receiver.  So it would seem to follow that this should be the most prominent identifier for a receiver or its deployment when editing these.  However, it's only visible on one of these pages, and not prominently.

The `deviceID` is an arbitrary motus-generated number, but at least it is useful to users
in that it's present in the batches and recvDeps tables of the .motus sqlite databases they 
build with the R motusClient package.

But `receiver ID` (e.g. 2161 in the example above) is neither physically associated with the receiver,
nor used to link to anything in data tables that users can see.  Is there any reason to display it?
It's just a source of potential confusion in e.g. problem reports.

**Comment by pmorrill** [comment]
I have updated the tools interface in our next release branch to follow these recommendations.
