### ISSUE TITLE
Add "country" field to user-accessed profile page

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1063]
There are two User Profile pages on the Motus site, which display somewhat different information (and have a couple issues on the web end)

This is the one I'm used to using (and which allows user access levels to be set): https://motus.org/data/admin/user_id?id=19829

And this is the one collaborators would be using: https://motus.org/data/user/edit

The user-accessed profile page lacks some important information present on 

- There is no option to set country in the User side
- There is only 1 line available for address (instead of 2). Additionally, if both street fields are populated in the database but the user updates it from their end, with only 1 address line, the second field in the database will be overwritten with NULL
- No option to select salutation on User end.
  - On the Admin end, the salutation dropdown doesn't change appropriately with the selection. If I select "None", "Dr" will instead be displayed. If I select "Mr", "Ms" will instead be displayed. The value in `user_id` is correct so it's just the display

Can we add a Country option, and a second Address line to the User end to make these two the same?

**Comment by Hussell** [comment]
The second address line, salutation, and country aren't used anywhere in Motus. They're part of the database record because those fields are defined in org.bsc.User, which org.bsc.motus.MotusUser inherits from. They show up on the admin user page because it was created before all the unnecessary fields were stripped from the main Motus user page. I can remove the unused fields from the admin page when I find some time, if you like?

**Comment by jsayers-bsc** [comment]
I think adding the fields to the user end may be better if possible.

Salutation probably isn't necessary but Country in particular is very useful (determining what currency to bill people in, for instance). A second address line is helpful as well, but not essential.

So if anything add Country to the user end if (and when) you can.

**Comment by leberrigan** [comment]
Closing in deference to #1172
