### ISSUE TITLE
Add dongle to sensor deployment interface

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#107]
Need to add new field "dongle" to the sensor deployment UI. Dropdown pulled from lk_dongle.

**Comment by StuMackenzie** [comment]
It should be labelled as something different than dongles on the public interface. I'll try and figure out an appropriate word. Technically they are all 'radio receivers'

**Comment by StuMackenzie** [comment]
Bah - Dongle is probably fine for now...
Labels:
Funcube Pro+
RTL-SDR
XCVR (this may change)

**Comment by denislepage** [comment]
Can we make this dongle_type, to be consistent with other lookups?

**Comment by cjardine-bsc** [comment]
sure.

**Comment by pmorrill** [comment]
Has this field (dongle_type) been added to tags_deployments, in sandbox? I'm not seeing it. That is where it belongs, right? As part of the deployment record rather than the tag record?

**Comment by StuMackenzie** [comment]
deployment record, yes, but receiver deployment not tags. It could theoretically change between different receiver deployments.

**Comment by pmorrill** [comment]
Yes - my bad! I realized that the dongle is not on the bird! I knew that, really.

**Comment by pmorrill** [comment]
This support is now in beta5 and master branches for testing

**Comment by pmorrill** [comment]
Stu: should the dongle field be mandatory?

**Comment by StuMackenzie** [comment]
Yes. Thanks, but only for sensorgnomes. I'm not sure how difficult that makes it. If this wasn't done already, we can assume that all sensorgnome deployments are FunCubes unless already labelled otherwise and we can go back and edit the ones that aren't.

**Comment by pmorrill** [comment]
To confirm: dongle type has no meaning at all except for sensorgnome? That means that for Lotek and others we don't need to present this field at all, right? But for SG, the fields is presented and mandatory.

**Comment by StuMackenzie** [comment]
Yes, currently Sensorgnomes are the only device with a dongle.

**Comment by pmorrill** [comment]
OK - beta5 and master branches updated to reflect this. The field will be disabled when deploying non-SG receivers; it will be mandatory for SG receivers.
