### ISSUE TITLE
Error when downloading data via R Sandbox

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1074]
This problem only exists for the `sandbox` version of the Motus R package.

When running tagme to create a new database or to update an existing one, I get the following error:
```
> motus.sql <- tagme(recvID, new = T, update = T, forceMeta = T, dir = data.dir)
Error in dplyr::filter(sql_tables, .data$table == name) : 
  lazy-load database 'C:/Users/Lucas Berrigan/Documents/R/win-library/4.0/motus/R/sysdata.rdb' is corrupt
In addition: Warning messages:
1: In dplyr::filter(sql_tables, .data$table == name) :
  restarting interrupted promise evaluation
2: In dplyr::filter(sql_tables, .data$table == name) :
  internal error -3 in R_decompress1
```

**Comment by steffilazerte** [comment]
Hi @cjardine-bsc, I don't think this is related, but yes that has been done (we chatted about it in this issue #1016, but I forgot to let you know that it was done, sorry!). Might be easier in future to open specific issues for these things so I remember to actually close and comment on them.

@leberrigan I'm not sure what's up but I've recreated the internal data (sysdata.rda) and pushed the new stuff. You'll have to reinstall from sandbox, and restart R to be sure. Let me know how it goes!

**Comment by cjardine-bsc** [comment]
Great! 

I've created those two fields in the view in Live. So @leberrigan you should be able to test the live branch and see that they appear.

Users will likely start to see those in R now that I've made that change. So if we don't end up launching tomorrow I should revert that.

**Comment by leberrigan** [comment]
I can confirm it works in both sandbox and live! I also see the new variables (`stationID` and `stationName` in `recvDeps`; `numGPSfix` in `activity`). I had to use `forceMeta=T` for station metadata to populate.
