### ISSUE TITLE
Need direct link to Station from receiver deployment page

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#1075]
Can we add a direct link to the appropriate station from the receiver deployment page? People are going to be landing on these pages now as they always have and it will look quite different. 

A direct way to get back to the station overview for that station will be very helpful both now and for navigation going forward.

e.g. somewhere on this [page ](https://motus.org/data/station/deployment/edit?projectID=1&id=7316)(screenshot below) either make the Station name clickable or provide a link beside it. In this case the link would be https://motus.org/data/project/stations?setStation=6279

![image](https://user-images.githubusercontent.com/55001144/146198843-29fa8ad8-0e36-46a4-967c-f213b41523e8.png)

Note: The breadcrumbs usually, but not always work, and they don't actually contain the station ID in the link so they can't be shared. Plus many people (like me) if ever use them for navigation.

**Comment by jsayers-bsc** [comment]
Apparently the direct link with `setStation=` as above doesn't always work without providing the project. The project number is superfluous as station id's are unique regardless of projects

**Comment by Hussell** [comment]
That link doesn't work either. I think you're being redirected to the previous page you visited. The link that works has `setStationId=`, and doesn't require a project ID.

**Comment by jsayers-bsc** [comment]
> That link doesn't work either. I think you're being redirected to the previous page you visited. The link that works has `setStationId=`, and doesn't require a project ID.

Ah, that station must have been saved with the browser state when I tried it. Yes the other works as desired.

**Comment by Hussell** [comment]
https://beta.motus.org/data/station/deployment/edit?projectID=1&id=8356
