### ISSUE TITLE
Beta10 Bugs and Fixes: post-release

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1076]
### Cannot add new landowner
When adding a new landowner, the 'preferred language' field is required, but there are no options to select so the form cannot be submitted.

![image](https://user-images.githubusercontent.com/35931796/146232706-75fc740f-3d8e-453d-9cdc-c8f0a57bb9fe.png)

We can probably just make this field not required to fix the problem for now. 
Edit this file:
`motus\web\WEB-INF\data\landowner\edit.jsp`
Replace **line 61** with:
`<select name="lang" id="lang">`

- [x] Fixed

**Comment by leberrigan** [comment]
Header menu cannot be edited on `/data` pages; at least, I can't figure out how to edit it through Wordpress. We need it to resemble the ones on other pages. Manage links have changed to the following:

French
```
    <li><a href='/data/project/edit?lang=fr'>Gérer projet</a>
    <li><a href='/data/project/users?lang=fr'>Gérer les collaborateurs</a>
    <li><a href='/data/issues?lang=fr'>Problèmes de données</a>
    <li><a href='/data/project/tags?lang=fr'>Gérer vos émetteurs</a>
    <li><a href='/data/project/landowners?lang=fr'>Gérer les propriétaires fonciers</a>
    <li><a href='/data/project/recvs?lang=fr'>Gérer vos stations</a>
    <li><a href='/data/project/sgJobs?lang=fr'>Soumettre des données de détection</a>
```

English
```
    <li><a href='/data/project/edit'>Manage Project</a>
    <li><a href='/data/project/users'>Manage Collaborators</a>
    <li><a href='/data/issues'>Data Issues</a>
    <li><a href='/data/project/tags'>Manage Tags</a>
    <li><a href='/data/project/landowners'>Manage Landowners</a>
    <li><a href='/data/project/stations'>Manage Stations</a>
    <li><a href='/data/project/sgJobs'>Upload Detection Files</a>
```

**Comment by Hussell** [comment]
I've put a full fix for the landowner thing on sandbox and beta. The code to populate those lists was just missing.

I don't have permissions to update the headers and footers on the live WordPress site. @cjardine-bsc  or @denislepage will have to copy them over from the beta WordPress site.

**Comment by leberrigan** [comment]
### Links between Stations and Landowners are broken
It appears that none of the stations have landowners associated with them any more. I haven't looked into why yet.

**Comment by cjardine-bsc** [comment]
My bad. I forgot a step past Catherine should have written down. 

They should be back.

**Comment by leberrigan** [comment]
Links to Deployment Details return an Error:
Clicking on 'Deployment Details' or deploy ID link (in Deployment History table) doesn't work. See this error:
https://motus.org/data/station/deployment/edit?projectID=2&id=5192

**Comment by cjardine-bsc** [comment]
That page is tossing a Null Pointer Exception. @Hussell I'm running into a meeting but sending you the trace.

**Comment by Hussell** [comment]
Paul checked in a fix last night. I've added it to the live branch, but it still needs to be deployed.

**Comment by leberrigan** [comment]
@pmorrill  When adding a new receiver, the text fragment is 'missing', but I can't add a new one because another with the same name already exists, just in uppercase:
https://sandbox.motus.org/data/project/receivers?projectID=2
![image](https://user-images.githubusercontent.com/35931796/146431834-4d38d4e0-1c6b-4da7-b000-28857f01b840.png)

**Comment by cjardine-bsc** [comment]
> I've put a full fix for the landowner thing on sandbox and beta. The code to populate those lists was just missing. The fix has been checked into the live branch, but I don't have permissions to deploy.
> 
> I don't have permissions to update the headers and footers on the live WordPress site. @cjardine-bsc or @denislepage will have to copy them over from the beta WordPress site.

Header and footer updated.

**Comment by Hussell** [comment]
I've only just now edited the sandbox and beta WordPress headers so that the menus match what Lucas posted above. Some other differences between the beta and live header remain, e.g. the standardized logo. @cjardine-bsc

**Comment by cjardine-bsc** [comment]
I did another update.

**Comment by Hussell** [comment]
I'm seeing the updated menu but old logo on the English pages, and the old menu but the updated logo on the French pages. Weird.

**Comment by cjardine-bsc** [comment]
kk. You're not seeing the same on beta? I'm doing a copy and past of the header, footer and stripped header template.

**Comment by leberrigan** [comment]
### All stations are duplicated
Every station has a copy with no associated deployments. This copy always has a higher station ID than the original.
![image](https://user-images.githubusercontent.com/35931796/146561410-e6c5b511-55f7-4a93-83f0-51e5d9317031.png)

**Comment by leberrigan** [comment]
@Hussell 
### Broken links on receiver timeline page
![image](https://user-images.githubusercontent.com/35931796/146561705-7d451eaf-8f3d-4636-a6b3-1f521cd003b1.png)

**Comment by Hussell** [comment]
>kk. You're not seeing the same on beta? I'm doing a copy and past of the header, footer and stripped header template.

I've double-checked everything. I did find and fix a problem in the French menus in the stripped headers, but I found nothing to explain the English logo. Try recopying both the header and the stripped header?

**Comment by Hussell** [comment]
The English logo is fixed. (?) Only the French menu in the stripped header needs to be updated now, I think.

**Comment by cjardine-bsc** [comment]
> @cjardine-bsc
> ### All stations are duplicated
> 
> Every station has a copy with no associated deployments. This copy always has a higher station ID than the original. ![image](https://user-images.githubusercontent.com/35931796/146561410-e6c5b511-55f7-4a93-83f0-51e5d9317031.png)
> ### Deployment associated with wrong station
> 
> These stations are not duplicated. Instead, one station has two active deployments and the other has none. Deployment 7592 should be associated with station 7795. Likely related to the bug above. Perhaps they had the same 'site' selected, but different deployment names? https://motus.org/data/project/stations?setStationId=7497

Looks like I forgot to wipe out my first run. I've done a wipe and replace, I think that's resolved it.

**Comment by cjardine-bsc** [comment]
> > kk. You're not seeing the same on beta? I'm doing a copy and past of the header, footer and stripped header template.
> 
> I've double-checked everything. I did find and fix a problem in the French menus in the stripped header, but I found nothing to explain the English logo. Try recopying both the header and the stripped header?

recopied.

**Comment by tve** [comment]
Why am I seeing jobs for project 661 (see lower part), when I'm viewing project 460 (see top)?
![Screenshot from 2021-12-19 20-48-59](https://user-images.githubusercontent.com/39480/146713491-2ddd231d-1251-4bc7-84cd-82c54edb1149.png)

**Comment by Hussell** [comment]
That's 661 jobs belonging to project 460.

**Comment by leberrigan** [comment]
Remove `required` attribute for field **Last name** in edit/modify landowners modal:
![image](https://user-images.githubusercontent.com/35931796/148419686-feb35d09-93e5-45f3-be42-e8bcb9953494.png)

**Comment by leberrigan** [comment]
Adding a new landowner logs you out of your Motus session:
![image](https://user-images.githubusercontent.com/35931796/152998467-30856757-0d3e-4e63-ab18-8a9720aec4a7.png)

Modifying a landowner does not.

**Comment by leberrigan** [comment]
this issue has become too large - we'll split them up from now on
