### ISSUE TITLE
Cannot edit Lat/Lon fields for Stations

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1078]
The Lat Lon fields for stations cannot be modified either directly by typing in the field or by copying and pasting in.

The only way to change a location is by sliding the marker on the map.

**Comment by Hussell** [comment]
Fixed on sandbox and beta, has to be deployed to live.

**Comment by denislepage** [comment]
Just deployed to live now, if someone can test and close the issue. @j-sayers
