### ISSUE TITLE
Redirect error when registering a new user

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#108]
1) I just tried to sign up with a new account. If you try to reach any pages, you are redirected to https://motus.org/data with the error: The page isn’t redirecting properly.

2) I thought there was an email sent out upon registration, but I did not receive one. We're starting to get fake registrations, so having a process for people to confirm their email address might be useful. We could set the real_user flag = 'Y' for instance when they confirm, and not let them use that account until they do. Unconfirmed registration attempts could be deleted after 24 or 48 h.

**Comment by Hussell** [comment]
1. appears to be a bug in the data management pages triggered by any user who is not registered with any projects.

**Comment by Hussell** [comment]
2. New user emails are going to motus@birdscanada.org

**Comment by denislepage** [comment]
But is the user also receiving one to confirm their registration?

**Comment by pmorrill** [comment]
1. I have added a handler for this case, and a new text fragment to help non-linked users
