### ISSUE TITLE
Receiver deployments instead of Stations currently displayed in Landowner overview

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1081]
In Landowner overview, receiver deployments are displayed instead of Stations. Should probably just be stations.

![image](https://user-images.githubusercontent.com/55001144/146431799-41478f0b-b2b8-4dba-8fad-374b9174afdd.png)

**Comment by leberrigan** [comment]
It is showing stations - just sometimes there are duplicates if they are split between projects of there are slight variations in name.
