### ISSUE TITLE
Some stations not showing on map for Project 113

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1090]
I noticed something odd in[ Project 113 today when viewing their stations.](https://motus.org/data/project/stations?projectID=113)

None of their show up on the map when viewing the "Active" or "All" tabs. The table will be displayed. However if from the Table tab you click on the Map tap, nothing will be displayed on either tab.

The "Inactive" tab works as expected.

I haven't noticed this in any other project before.

**Comment by Hussell** [comment]
Some fields in the database are derived from user input, which can be arbitrary. On this page, the station names and landowner names weren't being encoded into HTML properly, just inserted directly into the page, so when one of the station names had an unexpected character in it, it crashed the page. (Technically, the sub-pages which were supposed to display the map and the table crashed.)

Fixed on sandbox and beta, has to be deployed to live.
