### ISSUE TITLE
Motus Website Template

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1091]
## Overview
Start with new NatureCounts template and adapt for Motus (Streamlining for similar look). From there, we're not sure how many distinct templates will be needed, but likely 3 or 4:
- Home: as discussed on Thursday and below.
- About and internal resources pages: simple content pages.
- Explore: just a header, the content will be dynamic and we'll have to decide on the look later.
- Manage: lower priority, but we will likely use something very similar to about pages.

## Header
  - Main menu will no longer be a drop down and will instead have just 4 options: "About", "Resources", "Explore", and "Manage"
  - Login/language options will be similar to what currently exists and will be present on each page.
    - We anticipate to have 3 languages (EN, FR, ES) and perhaps eventually more.
  - Motus Logo and Birds Canada logo can have similar prominence and placement to current NatureCounts site.

## Footer
  - Content can be similar to what is currently present on Motus.
  - Add Birds Canada logo here as well, similar to NatureCounts.
  - We're flexible with how it will look.

#### Home Page
 - Start with this page and we'll review before working on other pages.
 - Keep an image carousel somewhat like NatureCounts, but feel free to upgrade images and add videos. You can find images on shared Google Drive (link has already been provided to Jarrad).
 - Features below carousel: 
   - "What is Motus?" intro text found on current home page.
   - Image of map with link to Explore Data.
   - "Recent updates" link and/or list.
   - List of sponsors.
 - Embellish with statistics from "Motus by the numbers", or place in about.

#### About
 - This will contain much of the same content as what currently exists in the section, albeit pared down a fair bit. 
 - These pages can be generally flashier than "Resources" and "Manage" since it's going to be the first impression for a lot of visitors.
 - Currently, the landing page has a lot of content which is hidden below the video which could be presented in a much nicer way. 
 -  Embellish with statistics from "Motus by the numbers", if not on home page.
 - We haven't decided on what pages we'll be keeping here, but you can start with:
   - ["About" Landing page](https://motus.org/about/)
   - [Get Involved](https://motus.org/get-involved/)
     - We may instead want to include this page on the 'about' landing page, but I'm worried it will be over crowded.
   - [About Automated Radio Telemetry](https://motus.org/telemetry/)
     - Potentially will be moved to Motus Docs.
   - [Frequently Asked Questions](https://motus.org/faq/)
     - Potentially will be moved to Motus Docs
   - [Partners and Supporters](https://motus.org/data/partners)
   - [Committee and Staff](https://motus.org/committee-and-staff/)
   - [Motus by the Numbers](https://motus.org/data/numbers)
     - This may be better suited as an embellishment on another page, like the home or about landing page.

#### Resources
  - Template should be similar to about pages, but I don't think there will be as much content to include on the landing page besides the links below (list may be incomplete):
    - [Motus Docs (external link)](https://docs.motus.org/motus-docs/)
    - [Regional Coordination Groups](https://motus.org/collaboratives/)
      - Everything under "Webinars and Meetings" can be moved to the page below.
    - [Seminars, Meetings, and other Videos](https://motus.org/video/#espanol)
      - Page is incomplete, but will eventually include videos found under "[Webinars and Meetings](https://motus.org/collaboratives/#webinarsAndMeetings)"
    - [Motus Google Group (external link)](https://groups.google.com/g/motus-wts)
    - [Data Analysis Guide: Motus R Book (external link)](https://motus.org/MotusRBook/)
    - [Publications](https://motus.org/data/publications)
    - [Policies and Fees](https://motus.org/policy/)
    - [Media](https://motus.org/info-graphics/)
      - Should have a media statement and quotes along with sharable images.

#### Explore
- This will have a light header similar to the other pages, but could be smaller. 
- Content will likely change a fair bit from where it currently stands, but current demo is here: https://leberrigan.github.io/motusDashboard/explore.html#e=main&d=stations

#### Manage
- Tables, data summaries, etc., all need a new, streamlined look consistent with other pages, cleaner colour schemes/organization

**Comment by StuMackenzie** [comment]
I went through and added a few comments to the primary text. Once we've had a go we should open it up to the whole team.

**Comment by StuMackenzie** [comment]
Tried adding these to the original, but it wouldn't let me for whatever reason:

## Header
  - eventual language support for English, French, Spanish

## Footer
  - wonder if Birds Canada logo should live in the footer? - similar to Nature Counts

## Page content

#### Home Page
 -  Keep an image carousel somewhat like NatureCounts, but will upgrade images. You can find images on shared Google Drive (link has already been provided to Jarrad). ***Motus team will have to secure and find the best images.***
 - Feature - high quality images, map/video/graphic content, brief 'what is' text, little else. Maybe a 'Recent Updates' link.
 - Embellished Motus by the Numbers on the Home Page providing summary statistics, or 'about'
  
#### About
 - 
 - We haven't decided on what pages we'll be keeping here, but you can start with:
   - ["About" Landing page](https://motus.org/about/) - will likely include everything within [Get Involved](https://motus.org/get-involved/)
   - [About Automated Radio Telemetry](https://motus.org/telemetry/) _*Potential Guides content*_
   - [Frequently Asked Questions](https://motus.org/faq/) _*Potential Guides content*_
   - [Partners and Supporters](https://motus.org/data/partners)
   - [Committee and Staff](https://motus.org/committee-and-staff/)
   - [Motus by the Numbers](https://motus.org/data/numbers) - or include on Home Page
     - This may be better suited as an embellishment on another, like the home page or about landing page.

#### Resources
  - This will be a landing page with links to the following pages (may be incomplete)
   
   - [Media} (Infographics and photos)(https://motus.org/info-graphics/) - should have a media statement and quotes along with sharable images.

#### Explore
- This will have a light header similar to the other pages, but could be smaller. 
- Content will likely change a fair bit from where it currently stands, but current demo is here: https://leberrigan.github.io/motusDashboard/explore.html#e=main&d=stations

#### Manage

- Tables, data summaries, etc., all need a new, streamlined look consistent with other pages, cleaner colour schemes/organization
-

**Comment by denislepage** [comment]
A few quick notes. It's not obvious from the above if we will be asking him to work on just the home page first, or other pages. I'd suggest the former.

The main pages make sense for us to discuss as they impact the navigation items of course. The list above looks about right at first blush: About, Resources, Explore and Manage would be the main options, no matter if you are logged in or not (my preference), or we could have a different path to get to manage. Given the key reason for the site, I think manage should be in the navigation at all times.

Language: we should likely anticipate the need to support more than 2 or 3, eventually. Perhaps we can have an option to showing them all when there 2-3 max, and worry later about what happens when we expand, which could be far away.

Photos: it may not matter what he uses for now. If we have one or two high res image that we can share now, it may be worth sending him, even if they are not used later. The flight tunnel shots are very cool if we have some we can use for this.

Logo: I'd use the same approach and placement as NC, generally.

**Comment by leberrigan** [comment]
I have updated the first post to reflect your comments. Does that look okay?

**Comment by StuMackenzie** [comment]
Looks good. Thanks.

**Comment by j-sayers** [comment]
I made a list of general comments related to functionality across the site here: #1108

**Comment by leberrigan** [comment]
Closed since we've already communicated these ideas to Jarrad. Next step is #1126
