### ISSUE TITLE
We need a sample project that includes receivers as well as tags

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1092]
The sample project in the R book / package docs only includes tags. So all the receiver-specific examples won't work.

Is there a sample project we could use that includes both tags and receivers so that people working through the docs can try all the examples?

This may be a real existing project, or some sort of construct we make up where we copy tags and receivers from an appropriate project into the "sample" project.

However we do it, we should offer new users a method of working through all, not just some, of the examples.

**Comment by cjardine-bsc** [comment]
Note that this isn't a super simple change. It requires building new DB tables and expanding the API to support a receiver call. Its quite doable, but when we set it up we decided that effort was not worth the ability for the user to test a single tagme call. The goal is to get them some standard data to work with for data manipulation, less so to show them how the tagme call works. 

What receiver specific examples are you referencing? Can we just subset the sample data to provide them with data from a single receiver to work with?

**Comment by denislepage** [comment]
Perhaps this is what you are saying, but we could provide sample .motus files available for download that we compiled ourselves, rather than modifying the API to support this for specific use cases.

One example, as we have now, to demonstrate tagme is fine, and I don’t think we should plan for more, but there is potentially no limit to sample data we can provide as downloadable files for the walkthrough examples.

**Comment by j-sayers** [comment]
I suppose I had assumed that everything with a motus account had access to Project 176 and could therefore just download data from that project any other. But it sounds like it's actually a different process for the sample project?

It's not a huge deal just that are a handful of examples in the erstwhile R book that refer to downloading data for receivers etc, followed by something like "expect this won't work because the sample project does not contain receivers".  One example:

```
3.5.4 Downloading multiple receivers at the same time

If you have a large number of receivers in your project, and wish to get receiver specific data for each one, rather than downloading them one by one as above, we can download them with a simple loop. 

Note that since the sample project doesn’t have any receivers associated with it, this script will not result in a download but you can try it with your own project if you have receivers.

> # specify the project whose rece
```ivers you wish to download:
> proj.num <- 176
> 
> # get a copy of the metadata only
> sql.motus <- tagme(proj.num, new = TRUE, update = FALSE, dir = "./data/")
> metadata(sql.motus, proj.num)
> tbl.recvDeps <- tbl(sql.motus, "recvDeps")
> 
> df.serno <- tbl.recvDeps %>% 
>   filter(projectID == proj.num) %>% 
>   select(serno) %>% 
>   distinct() %>% 
>   collect() %>% as.data.frame()
> 
> # loop through each receiver (may take a while!)
> for (row in 1:nrow(df.serno)) {
>   tagme(df.serno[row, "serno"], dir = "./data/", new = TRUE, update = TRUE)
> }
> 
> # Note you can remove the dir argument if you want to save it to your working
> # directory, just make sure that you use the same directory in both calls

```

It would be nice if all of the examples could be worked through in practice. That said, downloading by tag is definitely more important.
