### ISSUE TITLE
Cannot upload data - SensorGnome service authentication error

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1099]
I noticed this last night. I am unable to upload data or access job logs for any project and any user. Restricted to the following page (other management pages work fine): https://motus.org/data/project/sgJobs

![image](https://user-images.githubusercontent.com/35931796/152644594-20971a77-47a2-424a-8b42-595041a41c3d.png)

**Comment by denislepage** [comment]
OK, pushed to live.

**Comment by denislepage** [comment]
@leberrigan once you confirm that this resolved the issue, you can close

**Comment by leberrigan** [comment]
Looks good, thanks!
