### ISSUE TITLE
Networked receivers haven't synced data in several days

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1100]
Networked SG in Ontario appear to be checking at sg.org but none have synced data since around the 3rd of 4th. 

Example [Auzins ](https://motus.org/data/project/stations?setStationId=11207)which has no data since the 4th but still regularly sending data according to [sg.org/status ](https://sensorgnome.org/status/)

**Comment by j-sayers** [comment]
Looks like they are back up to date again

**Comment by denislepage** [comment]
Potentially due to the catching up of CTT files last week,  as they pushed the dual mode data. That would have likely stalled the transfer from sgdata

I will look into what was imported.
