### ISSUE TITLE
Stations with type 'buoy' not showing up on receivers map

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1104]
It seems like the issue is stemming from 'isMobile' flag being blank rather than FALSE.

Example receiver: https://motus.org/data/receiverMap?receiverDeploymentId=8390

**Comment by denislepage** [comment]
There were 2 issues, now fixed. The type was misspelled, with extra space characters (and/or some other non alpha chars). There was also no integrity between the deployment and the fixture type table to prevent invalid types from being saved. This also affected 2 depl for Turbine.
