### ISSUE TITLE
Search bar in Manage Tags to return matches of tagDeployID in addition to tagID

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1105]
The search bar in Manage Tags only matches tagID.

It would seem useful to allow searching for tagDeployID as well.

**Comment by leberrigan** [comment]
If we are to do this we need to fix the column header labelled 'ID' which is confusing when searching for two different IDs types at once. I'm going to make a new Git about this because the text fragment key is shared between multiple different tables/ID types so I can't change it yet.

**Comment by j-sayers** [comment]
Agreed, and that would add some much needed clarity between the two ID's as well

**Comment by leberrigan** [comment]
Closing this and placing it in Future Developments project
