### ISSUE TITLE
Robots.txt being ignored by Microsoft

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#1109]
I saw the same thing with NatureCounts. Bing crawlers are reaching pages that they should not based on robots.txt directives. In some instances, this creates errors, so I'd really like to try to prevent crawling most of our data related pages, except for a few things.

https://motus.org/robots.txt

There are noindex directives that we could potentially add to the banner, but that works differently.

Bing has a webmaster tool that looks useful, but I can't signup for some reason (other than Microsoft seems to hate me)

**Comment by denislepage** [comment]
I've made a few changes to the robots file. I'll need to check later on in the web logs if this has had an impact.,

**Comment by Hussell** [comment]
I noticed robots.txt was not being deployed to sandbox and beta, and fixed it.

**Comment by denislepage** [comment]
I think those 2 should block all agents and pages.

We don't want them crawling around.

**Comment by Hussell** [comment]
Done. robots.txt is now one of the server-specific configuration files, and the versions in the beta and master branches disallow everything for all agents.

**Comment by denislepage** [comment]
We can close for now. We'll reopen if we need.
