### ISSUE TITLE
Motus Dashboard API

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1110]
The following tables and columns are what I require for the dashboard integration. I tried to be clear about what I'm looking for and there's also a bit of flexibility in some instances that I've indicated.

This includes everything except for det_tagHitsTracks – that can be found in #1087.

Only show stuff where data is open.

---

### Stations
- API returns the **entire table**.

stationID | projectID | stationName | latitude | longitude | status
-- | -- | -- | -- | -- | --

### Station deployments
- API returns the **entire table**.

stationDeployID | stationID | receiverID | tsStart | tsEnd | type | status | region | photo | group | notes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

### Station tags
- API returns the **entire table**.
- `tagDeploymentIDs`: a vectorised list of tag deployments detected at the station
- `speciesIDs`: a vectorised list of species detected at the station

deploymentID | tagDeploymentIDs | speciesIDs
-- | -- | --

### Receivers
- API returns the **entire table**.

receiverID | serialNumber
-- | --

### Hourly GPS fixes
- API returns a **single receiver** at a time.
- Summarise GPS fixes per hour per receiver. Hourly count of fixes to be in new column named `fixes`. Rows where `fixes == 0` are omitted.

receiverID | hourBin | fixes
-- | -- | --

### Antenna deployments
- API returns the **entire table**.

stationDeployID | port | frequency | type | bearing | height | angle
-- | -- | -- | -- | -- | -- | --

### Antenna pulses
- API returns a **single receiver deployment** at a time, unless there is a more efficient solution. I will actually be displaying antenna pulses from a single station at a time which frequently encompasses multiple receivers.
- Summarise antenna pulses per hour per antenna. Hourly count of fixes to be in new column named `fixes`. Rows where `fixes == 0` are omitted.

stationDeployID | port | hourBin | pulseCount
-- | -- | -- | --

### Tags
- API returns the **entire table**.

tagID | frequency | model | burstInterval | mfgID
-- | -- | -- | -- | --

### Tag deployments
- API returns the **entire table**.
- `region` is country-province pair, like `CA-NS`.
- Group is for 'offshore wind portal', etc.

tagDeployID | tagID | speciesID | projectID | tsStart | tsEnd | region | group | markerNumber | markerType
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

### Species
- API returns the **entire table**, but only species which actually have tag deployments.
- Group is for bats/insects/shorebirds/waterbirds/etc.

speciesID | scientific | english | french | spanish | code | sort | photo | group
-- | -- | -- | -- | -- | -- | -- | -- | --

### Projects
- API returns the **entire table**.

projectID | name | shortName | shortDescription | description | group | primaryUser
-- | -- | -- | -- | -- | -- | --

### Regions
- API returns the **entire table**.
- `type` column defines whether the region is a country, prov/state, county, KBA, etc.

regionID | type | name
-- | -- | --

### Region polygons
- API returns all polygons of a **single type**.

regionID | type | coordinates
-- | -- | --

**Comment by cjardine-bsc** [comment]
For stations and station deployments do you want me to include or exclude test stations?

**Comment by cjardine-bsc** [comment]
@denislepage  There are a few questions to resolve above, but if you're keen to start creating entry points for Lucas the views are in your inbox.

**Comment by leberrigan** [comment]
> For stations and station deployments do you want me to include or exclude test stations?
Exclude please.

> How would you like to manage mobile deployments?
I don't have a good way to deal with them yet. Can we exclude them for now?

> Note I'm removing all filtered runs from these summaries.
Sounds good to me
 
> What is your definition of receiverID? In the database receiverID means the serial number of the receiver. But given your request below it looks like you're using it to mean either the device_id (unique for each serial number) or sensor_id (unique for each serial number/project).
I believe we settled on `sensor_id` last call.

> For Antenna deployments is "type" the antenna type or the dongle type?
Antenna type

> Hrrrmmm Antenna pulses is a nice wormy can and mixed in with hourly GPS fixes. I have it all associated with the sensor device ID, but there is no efficient way to do a join to get the deployment/sensor ids for each hour bin. We have managed this with taghits and GPS by keeping a static table that we update every time someone updates their metadata. It sounds like you'll need that for pulse counts too. Just to be sure, for antenna pulses are you looking for all pulse counts or just the ones that resolve to hits?
All pulse counts please. 

> You don't have projectId in the tags or tags deployment calls. Are you sure you don't need that?
Uhh woops... I do need those! Table has been updated

> Are you sure you want to call deployments for both tags and sensors "deploymentID" our convention has been to call them "tagDeployID" and sensorDeployID" to avoid confusion.
Sure, but let's use `tagDeployID` and `stationDeployID`.
 
> Would you like me to include or exclude test tag deployments?
Yes, please.

> Species code is a bit tricky, as there are different languages and authorities. For now I'm handing you the 6 character ebird species code.
That's fine. It will allow me to link to websites with species info by modifying the URL.

> We don't track Spanish common species names at the moment. The standard has been to use scientific names for Spanish.
Makes sense. Spanish names seem to have a lot more variation in them from my limited experience.

> What information are you looking for in the species group column. There are a couple options depending on the level i.e. Birds/Bats/Insect vs Shorebirds/Waterbirds/Raptors etc.
I wasn't sure what to do here. Right now it's a code for birds/bats/insects and that's handy, but I also really like the idea of including shorebirds/waterbirds/raptors. Can we do both? Just keep bats and insects and then split up birds into those large groups?

> Is shortName for projects the project_code?
Yup

**Comment by cjardine-bsc** [comment]
Can I change receiverID to sensorID then? It might save confusion in the long run. 

Can I merge the pulse counts and gps fix into one view? They both presumably need sensorDeployID? 

RE: 

    Would you like me to include or exclude test tag deployments?

Yes, please.

......sooooo.....exclude?

**Comment by leberrigan** [comment]
> Can I change receiverID to sensorID then? It might save confusion in the long run.

Yes!

> Can I merge the pulse counts and gps fix into one view? They both presumably need sensorDeployID?

Yes!

> ......sooooo.....exclude?

Yes!

**Comment by denislepage** [comment]
Progress:

Documentation: https://github.com/MotusDev/dashboard-api

Three formats available:

JSON Objects => https://sandbox.motus.org/data/dashboard/gps?deviceId=101&page=1

JSON Arrays => https://sandbox.motus.org/data/dashboard/gps?deviceId=101&page=1&fmt=jsonArrays

CSV => https://sandbox.motus.org/data/dashboard/gps?deviceId=101&page=1&fmt=csv

I made the longer results paginated, so you will have to loop through until there are no more results (if nrec < 10000, that should be the last page, or you can rely on the /count/xxxxx entry points to know how many pages are available before you start. For now, the gps call is the only one that is filterable (by deviceId).
 
List of API entry points (no pagination):

https://sandbox.motus.org/data/dashboard/antennaDeployments
https://sandbox.motus.org/data/dashboard/species
https://sandbox.motus.org/data/dashboard/projects
https://sandbox.motus.org/data/dashboard/receivers
https://sandbox.motus.org/data/dashboard/species
https://sandbox.motus.org/data/dashboard/stations
https://sandbox.motus.org/data/dashboard/stationDeployments

Paginaged calls:

https://sandbox.motus.org/data/dashboard/gps?deviceId=101&page=1
https://sandbox.motus.org/data/dashboard/stationTags?page=1
https://sandbox.motus.org/data/dashboard/tagDeployments?page=1
https://sandbox.motus.org/data/dashboard/tags?page=1

Counting records and pages (parameters for those are the same as those for the call you want a count):

https://sandbox.motus.org/data/dashboard/count/antennaDeployments
https://sandbox.motus.org/data/dashboard/count/gps?deviceId=101
https://sandbox.motus.org/data/dashboard/count/species
https://sandbox.motus.org/data/dashboard/count/stationTags
https://sandbox.motus.org/data/dashboard/count/projects
https://sandbox.motus.org/data/dashboard/count/receivers
https://sandbox.motus.org/data/dashboard/count/species
https://sandbox.motus.org/data/dashboard/count/stations
https://sandbox.motus.org/data/dashboard/count/stationDeployments
https://sandbox.motus.org/data/dashboard/count/tagDeployments
https://sandbox.motus.org/data/dashboard/count/tags

@cjardine-bsc  the station tables only return a small number of results in sandbox. Needs a sync perhaps?

**Comment by denislepage** [comment]
Also, there are currently no restrictions on access on any of the calls. It may not be unreasonable to put the dashboard behind a login, but I'm not sure. The way it is set up now, it'd be easier to add restrictions, or customize what people can see based on their permissions.

**Comment by leberrigan** [comment]
Thanks Denis. I'm going to close this since the API has been created as requested. Any changes should be posted in a new Git.

**Comment by cjardine-bsc** [comment]
Nope. I have some tasks here still for the activity. Sorry!

**Comment by leberrigan** [comment]
Okay, sure! Can you also make these changes to the tag deployments table? 

### Tag deployments
- Add variables `deployLatitude`, `deployLongitude`. `photo`, `status
  - Photo: same as with station deployments; leave it blank for now and we'll populate later
tagDeployID | tagID | speciesID | projectID | tsStart | tsEnd | region | group | deployLatitude | deployLongitude | photo | status
-- | -- | -- | -- | -- | -- | -- | --

**Comment by leberrigan** [comment]
One more ask - I would like a list of tags that are 'local' to each station. That is, I want to know which tags were deployed within 10 km of each station. It doesn't have to be 10 km, that's just the threshold I've chosen; let's keep it at that for now. I'm guessing it would be easiest to make a new table called `stationLocalTags`.

### Station Local Tags
stationDeployID | tagDeployID
-- | --

**Comment by leberrigan** [comment]
@cjardine-bsc  I have one more request!
I need a table of the 'most recent data' for each station - that's so I can quickly display that information while hovering over a station with the cursor, rather than downloading the entire activity table for that station.

Denis suggested you use the batches table to figure out the most recent data.

### Station Recent Data
stationID | ts
-- | --

**Comment by cjardine-bsc** [comment]
RE: @cjardine-bsc the station tables only return a small number of results in sandbox. Needs a sync perhaps?

Sunk.

**Comment by cjardine-bsc** [comment]
> Okay, sure! Can you also make these changes to the tag deployments table?
> ### Tag deployments
> 
>     * Add variables `deployLatitude`, `deployLongitude`. `photo`, `status
>       
>       * Photo: same as with station deployments; leave it blank for now and we'll populate later
>         tagDeployID | tagID | speciesID | projectID | tsStart | tsEnd | region | group | deployLatitude | deployLongitude | photo | status
>         -- | -- | -- | -- | -- | -- | -- | --

Added to vwDashboard_tags_deployments in the database.

**Comment by cjardine-bsc** [comment]
> One more ask - I would like a list of tags that are 'local' to each station. That is, I want to know which tags were deployed within 10 km of each station. It doesn't have to be 10 km, that's just the threshold I've chosen; let's keep it at that for now. I'm guessing it would be easiest to make a new table called `stationLocalTags`.
> ### Station Local Tags
> stationDeployID 	tagDeployID

AH! Found it! I knew we had done this already. 

https://github.com/MotusDev/Motus-TO-DO/issues/917

Do you actually want the station deployment ID or just the stationID? I'm assuming the stationID. 

New view:

 vwDashboard_tags_local 

[tagDeployID]
,[stationID]


@denislepage we'll need to add this entrypoint.

**Comment by cjardine-bsc** [comment]
> @cjardine-bsc I have one more request! I need a table of the 'most recent data' for each station - that's so I can quickly display that information while hovering over a station with the cursor, rather than downloading the entire activity table for that station.
> 
> Denis suggested you use the batches table to figure out the most recent data.
> ### Station Recent Data
> stationID 	ts

Okie! So the tricky part of this one, that we didn't discuss on the call, is the fact that device's can move between stations. So its going to be a smidge more complex. Its easy enough for stations with active deployments (since then deviceIDs will be unique, with only one device active at each station).  

For terminated deployments, can I give you the deployment end date, or do you want the last data that came in for the deviceID used by that deployment. I'm trying to find ways to make the query speedy.

**Comment by leberrigan** [comment]
> Do you actually want the station deployment ID or just the stationID? I'm assuming the stationID.

Sure, that works for me!

> Okie! So the tricky part of this one, that we didn't discuss on the call, is the fact that devices can move between stations. So its going to be a smidge more complex. Its easy enough for stations with active deployments (since then deviceIDs will be unique, with only one device active at each station).
> 
> For terminated deployments, can I give you the deployment end date, or do you want the last data that came in for the deviceID used by that deployment. I'm trying to find ways to make the query speed
That should be fine. That is, if the most recent data is from beyond the deployment end date, just cut it off there.

**Comment by leberrigan** [comment]
I also have these changes:


### Tag deployments
- add marker type and marker number

tagDeployID | tagID | speciesID | projectID | tsStart | tsEnd | region | group | markerNumber | markerType
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- 


### Station deployments
- add notes

stationDeployID | stationID | receiverID | tsStart | tsEnd | type | status | region | photo | group | notes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --


### Antenna deployments
- add height and angle

stationDeployID | port | frequency | type | bearing | height | angle
-- | -- | -- | -- | -- | -- | --

**Comment by cjardine-bsc** [comment]
> > Do you actually want the station deployment ID or just the stationID? I'm assuming the stationID.
> 
> Sure, that works for me!
> 
> > Okie! So the tricky part of this one, that we didn't discuss on the call, is the fact that devices can move between stations. So its going to be a smidge more complex. Its easy enough for stations with active deployments (since then deviceIDs will be unique, with only one device active at each station).
> > For terminated deployments, can I give you the deployment end date, or do you want the last data that came in for the deviceID used by that deployment. I'm trying to find ways to make the query speed
> 
> That should be fine. That is, if the most recent data is from beyond the deployment end date, just cut it off there.

Okay, view works, but currently takes 8 seconds to run. vwDashboard_station_recent_data 

I'd like to try and trim that 8seconds down. But for now we can get the entry point up so we're not slowing your progress.

**Comment by cjardine-bsc** [comment]
> I also have these changes:
> ### Tag deployments
> 
>     * add `markerNumber` and `markerType`
> 
Added
> 
> tagDeployID 	tagID 	speciesID 	projectID 	tsStart 	tsEnd 	region 	group 	markerNumber 	markerType
> ### Station deployments
> 
>     * add `notes`
> 
> 
> stationDeployID 	stationID 	receiverID 	tsStart 	tsEnd 	type 	status 	region 	photo 	group 	notes

called it comments 

> ### Antenna deployments
> 
>     * add `height` and `angle`
> 
Is angle the elevation_angle? If so, added! 

Okay, I think that's it. I suspect Denis set up the entry points to grab all fields from the table, in which case we should be good! Let me know if not. 
> 
> stationDeployID 	port 	frequency 	type 	bearing 	height 	angle

**Comment by denislepage** [comment]
Yes, most of the API entry points will simply return all columns in the proc or view, so adding new columns should immediately be reflected in the API. 

There are some exceptions, but most of them involve removing specific fields that we do not want returned in the API.

**Comment by leberrigan** [comment]
@cjardine-bsc Can you make the following edits to [dbo].[vwDashboard_tags]?
- Add column `lifespan`.
- Rename column `ProjectID` to `projectID`.

**Comment by cjardine-bsc** [comment]
okay, should be done!

**Comment by leberrigan** [comment]
@denislepage I'm not seeing any of the following new variables that Catherine just added. Is it something you need to change on your end?

> 



> > I also have these changes:
> > ### Tag deployments
> > ```
> > * add `markerNumber` and `markerType`
> > ```
> 
> Added
> 
> > tagDeployID 	tagID 	speciesID 	projectID 	tsStart 	tsEnd 	region 	group 	markerNumber 	markerType
> > ### Station deployments
> > ```
> > * add `notes`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > stationDeployID 	stationID 	receiverID 	tsStart 	tsEnd 	type 	status 	region 	photo 	group 	notes
> 
> called it comments
> 
> > ### Antenna deployments
> > ```
> > * add `height` and `angle`
> > ```
> 
> Is angle the elevation_angle? If so, added!
> 
> Okay, I think that's it. I suspect Denis set up the entry points to grab all fields from the table, in which case we should be good! Let me know if not.
> 
> > stationDeployID 	port 	frequency 	type 	bearing 	height 	angle

**Comment by leberrigan** [comment]
@cjardine-bsc This is still returning an empty array: https://beta.motus.org/data/dashboard/tags/local

**Comment by leberrigan** [comment]
@denislepage I'm not getting any response when trying to load from: 
 - `/gps` https://beta.motus.org/data/dashboard/gps?stationId=11632&page=1
 - `/antPulse` https://beta.motus.org/data/dashboard/antPulse?stationId=11632&page=1

**Comment by denislepage** [comment]
I saw some database errors related to missing views today.

Catherine can let me know if I need to fix the API.

**Comment by cjardine-bsc** [comment]
I'm on it. Stand by.

**Comment by cjardine-bsc** [comment]
Sorry, meetings. 

Tags local proc run on live

**Comment by leberrigan** [comment]
Yup yup - looks good now

**Comment by leberrigan** [comment]
@cjardine-bsc It looks like I'm only getting antenna pulses for a subset of the hour bins - are you only sending me hours where tag detections occur? Perhaps you've pared things down because it's a lot of data to send -- if that's the case, I'm fine with you sending me a daily sum of pulses per antenna.
![image](https://user-images.githubusercontent.com/35931796/173876559-dd7b56f2-2ab9-478b-9157-e13421eafb61.png)

https://beta.motus.org/dashboard-beta/#e=stations&d=stations&selections=11037

**Comment by cjardine-bsc** [comment]
This is what I mentioned last week. The new activity proc isn't in live yet. Stand by!

**Comment by cjardine-bsc** [comment]
Running on live now.

**Comment by leberrigan** [comment]
@cjardine-bsc  Can you make the following changes?

### Tag deployments
- add `bandNumber`, `age`, `sex`, and `notes`

tagDeployID | tagID | speciesID | projectID | tsStart | tsEnd | region | group | markerNumber | markerType | bandNumber | age | sex | notes
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by cjardine-bsc** [comment]
Done. Notes is called Comments for consistency.
