### ISSUE TITLE
We need better enforcement of Lotek receiver type during registration

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1113]
I was just looking to see how many detections exist from SRX 1200 receivers.

Though there are at least a few SRX 1200 out there that have uploaded data, none of those receivers were registered at LotekSRX1200.

~~Is defining the correct SRX model necessary for tagfinder? There are actually 8 different variations of Lotek receivers offered during registration.~~\

Unlike previous SRX models, which offered users the option to download data in either UTC or their local time zone, and necessitated the "UTC offset" workaround, SRX 1200 **always** export detection data in UTC. 

Knowing whether a particular Lotek receiver is now fairly important since UTC should never be set (and  ideally [shouldn't even be presented](#1115) as an option).

Though SRX 1200 is one of the 8 Lotek receiver options presented during registration, so is the undifferentiated "Lotek". In the recent cases anyway it seems this is was selected, which is why there were no SRX 1200 receivers registered.

Given the chance of detection times being off by several hours, we probably have to do more now to enforce proper registration of these receivers. Seems there are at least a couple options.

- Action required by users during registration to specifically confirm whether the receiver is an SRX 1200
- Identify SRX 1200 pattern with regex if there is actually a distinctive pattern used by Lotek (I'm note sure)
- Identify model in DTA files. The receiver type is stored there, but it may not be practical to use that.

**Comment by j-sayers** [comment]
...Maybe not for tagfinder but for metadata it is important as SRX1200 **always** export detection data in UTC.

**Comment by leberrigan** [comment]
Moving this to a discussion until we can identify what actions we want to take. We're still at the decision stage.
