### ISSUE TITLE
motus credentials not accepted on sandbox

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1118]
I'm trying to log in on Sandbox but my credentials are not being accepted.

No issue on Live or Beta. I've tried deleting cache and cookies but no change.

It's been a few weeks since I've logged on to sandbox so I'm not sure when this started.

**Comment by leberrigan** [comment]
Did you change your password in the past? I noticed mine had reverted to the old one

**Comment by j-sayers** [comment]
> Did you change your password in the past? I noticed mine had reverted to the old one

That's it. Turns out the Live/Beta and Sandbox passwords are independent of each other.
