### ISSUE TITLE
Review Changes to Motus pages on Sandbox: main menu, "Home", "About", "Resources", and "Get Involved"

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1125]
### Changes made
- Menu simplified to 4 options: "About", "Resources", "Explore Motus", and "Manage"
- Home page has been adjusted to fix a few cosmetic bugs and change the colour-scheme a tad bit.
- About hasn't changed much from current website, except two paragraphs of intro text have been moved to the top. "Get involved" has been added to the link table here.
- Resources has changed in terms of the way it displays links. There are now two sections: "Quick Reference" and "General Resources", with the former coming up first. The former includes:
- Get involved
- Tag deployment
- Station deployment
- 	General resources includes everything else that won't be in 'about'.
- Explore Motus now links directly to the Dashboard Demo

---

### What to review
- Did I bury something important?
- I'm open to suggestions for further simplification.
- Is 4 menu options and no dropdown sufficient?

**Comment by eageldart** [comment]
"about automated telemetry", "motus updates"  links lead to a page with the message:  "We are sorry. The page or resource that you are looking for cannot be found at this address. Please use our navigation menu to locate what you are looking for or return to the homepage"

**Comment by leberrigan** [comment]
Sorry - I forgot to mention that some links may not work. This is because the demo is on Sandbox and not all pages have been populated. Those which have broken links do not need to be reviewed.
