### ISSUE TITLE
Bulk tag deployment import proc fails silently

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1128]
### Problem
When uploading tag deployments using the bulk uploader tool, the import fails silently if there are test tags which have start dates equal to end dates. 

---
### Solution
Ideally, we should prevent this proc from failing silently so we can identify any other validation steps that may have been missed.

---
### Background
Issue first raised in #1107. Issue relating to this specific validation step is here #1127.

From Denis:

> I don't have an immediate solution to propose, but we should ideally prevent this proc from failing silently, so I least we can catch any other conditions we missed during validation.

Full post below:

> 
> Here's the error that I am getting when trying to run the import (which is failing silently):
> 
> "Start date is greater than or equal to the end date"
> 
> This currently applies to 2 tags, both of which are flagged as test tags. Although there is a validation in place for this condition, it is being ignored because these 2 are test tags.
> 
> This is the problematic section (last condition where test != 1).
> 
> ```
> SELECT a.rowNum,'Start/End Dates' as field_name,tsStart,tsEnd,
> dbo.ts2datetime(tsStart) as startDT,dbo.ts2datetime(tsEnd) as endDT, tagDeployID,tagID, confirm_dt_start 
> INTO #temp_ts
> FROM api_tag_deployments a 
>                 LEFT JOIN #temp_error b ON a.apiBatchID=b.apiBatchID AND a.rowNum=b.rowNum AND b.field_name like 'utc%'
> WHERE b.error_code IS NULL and a.apiBatchID = @apiBatchID AND test != 1 
> ```
> 
> The reason it is failing silently, which is a separate issue, is because the proc currently catches the error and rollbacks to update/insert, but doesn't return an error to the calling method, which leaves the values in their original state (0 updated, 0 inserted). 
> 
> I tried to add a RAISERROR statement in the catch block, but it's being handled silently somewhere else in Java, it seems. 
> 
> Anyway.
> 
> 1. Immediate fix is to set the end date later than the start date/time in the file, even just by 1 minute. I just tried the project 78 file with success after setting utcMinuteEnd = 1
> 
> 2. Second fix would be to either add this condition to generate an api_error record in the validation, or allow tags to have the same start and end date in the deployment table.
> 
> 3. I don't have an immediate solution to propose, but we should ideally prevent this proc from failing silently, so I least we can catch any other conditions we missed during validation.
> 
> _Originally posted by @denislepage in https://github.com/MotusDev/Motus-TO-DO/issues/1107#issuecomment-1043580499_

**Comment by cjardine-bsc** [comment]
I removed the provision that restricted the date checks to only focus on non-test deployments. This will mean that test deploys will need to be clean. But that's good to enforce anyway.
