### ISSUE TITLE
Antenna port dropdown not populated, and cannot delete antenna without a port selected

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1132]
Project 467 is trying to update their station metadata for a [SensorStation](https://motus.org/data/station/deployment/edit?projectID=467&id=8316&edit=1). 

These ended up somehow being saved without the antenna port set. Now that they are saved the dropdown remains unpopulated so they can not be corrected.

The page cannot be saved either so these antennas can neither be deleted, nor new ones with the correct port added in the interim.

Usually when I select "CTT Integrated" from the list of new antennas it's automatically populating the correct "L-" ports as it should. But occasionally I also get a situation where "CTT Integrated" is selected but there is nothing in the dropdown. I can't reliably replicate that though.

![image](https://user-images.githubusercontent.com/55001144/158197760-d3beb932-509d-4539-ba06-dd3a3d4cce90.png)

**Comment by cjardine-bsc** [comment]
What deployment? I'll remove the empty antennas in the back end while we wait for a website fix of the root of the problem (might be a while).

**Comment by j-sayers** [comment]
> Project 467 is trying to update their station metadata for a [SensorStation](https://motus.org/data/station/deployment/edit?projectID=467&id=8316&edit=1).

[8316](https://motus.org/data/station/deployment/edit?projectID=467&id=8316&edit=1)

Thanks that will help for now.

**Comment by cjardine-bsc** [comment]
Huh. Actually. It might be a display issue. Here are the values in the DB. Are they correct? 

![image](https://user-images.githubusercontent.com/22172758/158247635-0409f6ea-7ad7-4f28-9f3f-a2eefc5f4db0.png)

**Comment by denislepage** [comment]
I have been getting a related error: NullPointerException in class RecvDeploymentBean (line 601). The weird thing is the that line # is "frequency == null". There's a chance that the mixture of primitive double and wrapper Double is trying to force a Null object to a primitive, but I didn't yet manage to replicate that. In any case, I made the following change on the live site, if someone could test whether this has changed anything.

Old
```
	Double newFrequency = cttIntegratedPort
#		? 434.00
		: (frequency == null
			? p.getDoubleObject("frequency_new_" + i,null) 
			: frequency);
```
New:
```
	Double newFrequency = cttIntegratedPort
#		? Double.valueOf(434.00d)
		: (frequency == null
			? p.getDoubleObject("frequency_new_" + i,null) 
			: frequency);

```
I think this confirm the issue. If p.getDoubleObject returns null, it tries to unbox the Null value to match the primitive 434, and throws a null pointer:

This fails:
```
	Double newFrequency = false
			? 434.00
			: (frequency == null
				? null 
				: frequency);
```

This works:
```
	Double newFrequency = false
			? Double.valueOf(434.00d)
			: (frequency == null
				? null 
				: frequency);
```

**Comment by denislepage** [comment]
Fixed. 

It was a database issue. A small number of dongle types where saved as 'CTT Integrated', rather than 'Integrated (CTT SensorStation)'. Presumably something we changed along the way.

There was integrity validation, but both types were in lk_dongle_type, one without values in lk_device_dongles.

I have changed 140 antenna records associated with "CTT Integrated" to "Integrated (CTT SensorStation)" and removed the first from lk_dongle_type.

The select list could not find the necessary property for that dongle type, and was thus empty.

**Comment by j-sayers** [comment]
Perhaps something similar...?

I'm Trying to remove RTL-SDR from a SensorStation deployment but the dropdown is empty and preventing me from saving (including adding the new replaced dongles).

Deployment https://motus.org/data/station/deployment/edit?projectID=1&id=8559

![image](https://user-images.githubusercontent.com/55001144/164306096-f9db0a77-530d-475f-afc2-312ff33ca2b6.png)

**Comment by denislepage** [comment]
Should be fixed now. We had two different entry for the RTL dongle type, with inconsistencies regarding which was used in different places in the database.

Everything is now under “RTL-SDR v3”. The description for RTL-SDR alone also specified version 3, so I assumed they were both referring to the same dongle. If not, we’ll need to undo some changes I made.
