### ISSUE TITLE
Old URL Parameter 'setStationId' causes Station API to fail

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#1133]
I have seen this error several time today.

This is potentially the result of my pushing of the live branch yesterday. I don't expect this new error is the result of my change, but something else is throwing the error. The Illegal state error is most likely a secondary bug to another underlying issue. Can someone try to find out how to replicate this problem and post it here, or perhaps contact the user if needed? I haven't checked whether the user was always the same or not yet.

![image](https://user-images.githubusercontent.com/21110542/158448682-690ce3d4-e736-418b-83ac-a6b8d2f1607f.png)

•	https://motus.org/data/station/deployment/edit?projectID=441&id=8478
```
Parameters:

projectID:
•	441
setStationId:
•	12488


Request attributes:
javax.servlet.error.exception:
java.lang.IllegalStateException: Cannot call sendRedirect() after the response has been committed
javax.servlet.error.exception_type:
class java.lang.IllegalStateException
javax.servlet.error.message:
Cannot call sendRedirect() after the response has been committed
javax.servlet.error.request_uri:
/data/project/stations
javax.servlet.error.servlet_name:
ManageStationsServlet
javax.servlet.error.status_code:
500
javax.servlet.forward.context_path:
javax.servlet.forward.query_string:
projectID=441&setStationId=12488
javax.servlet.forward.request_uri:
/data/project/stations
javax.servlet.forward.servlet_path:
/data/project/stations

activeUserInfo: User ID: 24398


```

**Comment by j-sayers** [comment]
I'll get a hold of them.

**Comment by j-sayers** [comment]
Just had a very similar error/issue when trying to view a [deployment page for a station](https://motus.org/data/project/stations?projectID=1&setStationId=9830) in Project 1


![image](https://user-images.githubusercontent.com/55001144/158605236-f24e61a5-8b54-4d87-81f5-f09a3c6c058c.png)

**Comment by leberrigan** [comment]
It's a URL parameter problem. Clicking on the link on the station deployment page produces this error because it's using the old parameter that Paul had made for Station ID ("setStationID") when it should be `stationID`.

**Comment by denislepage** [comment]
I suspect these were introduced with the push I made earlier this week, and ideally, everything that goes in the live branch should have been tested in beta. If we can resolve this issue quickly, would reverting the most recent commits temporarily get rid of the error? I don't understand otherwise why the error did not manifest until this week.

@Hussell  can you confirm whether any new changes could be causing this that we can revert (ideally today), or can you try to investigate how to address this bug as a priority?

**Comment by denislepage** [comment]
The reported error (IllegalState) was relatively simple There were 2 consecutive redirects in ManageStationsServlet. You can't redirect twice, so I commented out the second one. There were some changes made on 25 Feb that left that second line behind inadvertently. 

```
ctx.redirectRaw("?" + Parameters.buildQueryString(parameterMap));
ctx.redirectRaw("/data/project/stations?projectID=" + ProjectBean.getProjectIdFromStation(ctx.getProjInfo(),stationId));

```
I have also changed the setStationId parameter in a few places, which may or may not have been causing this issue This is currently deployed in live. If that works, we can propagate the fixes to beta and sandbox (and jakarta, which we need to start tracking for changes as well, but I'll bring this up tomorrow).

Can people try to replicate this again? The link in #1134 is now working as expected, I believe.

**Comment by denislepage** [comment]
I'm going to close this one in deference to #1134  That one now only needs testing, hopefully.
