### ISSUE TITLE
Issue with an estimated tag deployment end date

### ISSUE THREAD

**Issue by eageldart** [MotusDev/Motus-TO-DO#1136]
Tag ID 10348, deployment ID 26888, from project 20 (https://motus.org/data/project/tags?projectID=20) has an estimated end date that is before the deployment start date (see screenshots below). This is the only case that I have seen this issue, but I will post here if I find more.

**Comment by eageldart** [comment]
![image 2](https://user-images.githubusercontent.com/94930170/158836441-92884b25-71e4-4ad5-96b4-385a2583a1c2.png)
![image 1](https://user-images.githubusercontent.com/94930170/158836466-afac6348-105d-4600-b46f-a4c9d27afb3b.png)

**Comment by cjardine-bsc** [comment]
Well....Its actually _kinda_ right. 

The end date is 55 days after the start date of the initial deploy (2014-05-20 to 2014-07-15). 

The problem is that first deployment (5073) its end date is way out of wack. Something is off with the metadata here. Or they deployed a long-dead tag on a bird.

**Comment by leberrigan** [comment]
It's likely that they changed something before we put a block in place to prevent this. 

@eageldart Can you find other examples like this and list them here, or just give us a tally if there are lots?
