### ISSUE TITLE
Motus procs queue changes

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#1137]
In the process of moving our code to JDK17, I have made numerous changes to the code. 

I have rewritten large parts of the procs queue that handle automated tasks. Most of the tasks are largely unchanged, but the process of handling the tasks and dealing with possible concurrency issues has changed.

The currently deployed sandbox (based on the jakarta branch) is the one handling the sandbox procs queue.

I have been monitoring the procs queue in sandbox for a few days now. I resolved some of the initial errors, but I am still trying to figure out some apparent concurrency issues in ReadCTTFiles where it's trying to parse files with temporary extensions (.done, .part) before it seems to have finished downloading them.

We should keep an eye on the queue for a little while (1-2 weeks) before closing this issue, unless new problems crop up.

**Comment by cjardine-bsc** [comment]
1-2 weeks.....errr....1-2 years.... 

Closing.
