### ISSUE TITLE
New beta 11 branch - uploads need testing

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#1138]
In the various changes I made to the upcoming beta11 branch (now jakarta,) one that should require testing are the upload functionalities. Those are ready to test on the sandbox site right now.

**Comment by j-sayers** [comment]
Two more uploads of new data went fine.

**Comment by leberrigan** [comment]
I'm no longer able to see the [Station Management](https://sandbox.motus.org/data/project/stations) page on Sandbox:
![image](https://user-images.githubusercontent.com/35931796/159953737-8b21b1ba-af0f-4890-bfac-ba2034f342f7.png)

**Comment by denislepage** [comment]
That’s good. I changed the class for the upload itself in sandbox, so that should be a good sign. This would likely also affect the upload of the deployment csv file, so that’s another place we can test.
