### ISSUE TITLE
can't get deviceID because API not returning records for some "registered" receivers

### ISSUE THREAD

**Issue by jbrzusto** [MotusDev/Motus-TO-DO#114]
According to  `api/receiver/register`, the following receivers are already "registered"
(scare quotes because these registrations did not happen via an API call from the data server):

deviceID|serno
---|---
 .|Lotek-6157
 .|Lotek-6295
 .|Lotek-6297
 .|Lotek-6298
 .|Lotek-6299
 .|Lotek-6306
 .|Lotek-6463
 .|Lotek-6531
 .|Lotek-8116
 .|Lotek-8189
 .|Lotek-D000426
 .|SG-0613BB000593
 .|SG-1814BBBK0000
 .|SG-3615BBBK0B93
 .|SG-4815BBBK1147

but they don't show up in either of these APIs:

 - /api/receivers
 - /api/receivers/sensordeployments

so I can't get the deviceID from anywhere.

**Comment by cjardine-bsc** [comment]
They do have device IDs

id	receiverID
487	Lotek-6157
490	Lotek-6295
492	Lotek-6297
505	Lotek-6463
508	Lotek-6531
706	SG-0613BB000593
764	Lotek-6298
765	Lotek-6299
766	Lotek-6306
770	Lotek-8116
771	Lotek-8189
772	Lotek-D000426
912	SG-3615BBBK0B93

Paul will need to investigate why they are not showing up in either API.

**Comment by denislepage** [comment]
They all have secret hash keys, so they must have been registered through the API. Two of them (those 2 not in Catherine's list) were added today. I don't think we ever added anything manually, or even changed existing records in this table, but we definitely have been fixing the user-entered values under their projects (sensorID).

I expect the reason they are not showing up on the API is that they are not registered under any project, but I thought this had been addressed a long time ago. We need to support an option where receivers that only have a deviceID, and not linked to any projects, can be visible through the API. The 2 options are either to add a new entry point which sole purpose is to supply the list of deviceID's, or change the join type in the existing list, so those receivers are included.

The deviceID's were probably provided at the time of registration, but that doesn't help if you don't have a trace of them.

**Comment by jbrzusto** [comment]
Sorry, my bad on "not registered".
I was going by a lack of a deviceID on my side when I said they hadn't been registered, but as you 
point out, they *were* registered via the API.  However the registration call did not return a deviceID, and the
receiver did not show up in any of the other API calls, so no device ID was obtained.

Once Paul's changes have made it to the production server from the beta (where they now work),
I'm going to close this because:
 - I have deviceIDs for all receivers
 - the receiver/register API on beta now works and returns a deviceID

So going forward, I should always be able to the the deviceID.

Also, I confirmed again with a test registration, so please delete the bogus receiver with deviceID 950 (SG-FFFFRPI3FFFF, again).  

Thanks!

**Comment by denislepage** [comment]
I have no posted the changes to the production site, if you want to confirm. The deviceID 950 has also been deleted.

**Comment by jbrzusto** [comment]
Thanks! (and there's another device 950 to delete now)
