### ISSUE TITLE
Active receiver tally not updating when deployment ended 

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#118]
See "active" tab for https://motus.org/data/project/recvs?projectID=145

**Comment by Hussell** [comment]
Page appears correct to me when I first viewed it, so this is very likely another caching bug.

**Comment by StuMackenzie** [comment]
Seems fine now when I've logged in with another user.

**Comment by pmorrill** [comment]
This is similar to #90 (though that issues is with the tag deployment lists). In this case, my testing shows that the deployment records are being removed from the active tab, but that the tab text itself - which includes a count of the deployments in that category - is NOT being updated.

Stu: is that situation that you saw as well?

**Comment by StuMackenzie** [comment]
That is the case. The list is updated and fine, but the COUNT isn't. sorry for not being more explicit.

**Comment by pmorrill** [comment]
This should be fixed on the next deployment to sandbox or beta
