### ISSUE TITLE
Dashboard API has only 11 stations

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1185]
I'm assuming this because it's pulling data from `sandbox`? I'm going to need the full list of stations to properly test this.

https://sandbox.motus.org/data/dashboard/count/stations
https://sandbox.motus.org/data/dashboard/stations

**Comment by cjardine-bsc** [comment]
Hmm. There are oddles in the DB in sandbox (2613 = 1 metric oodle). 

Ah-ha. Found it. Enjoy your oodles.

**Comment by cjardine-bsc** [comment]
Remember that data will be sloppy. I didn't do my deep clean of the pre-station metadata in Sandbox, so there will be a bunch of duplicates etc.
