### ISSUE TITLE
Dashboard API - GPS hits should require sensorID, not deviceID

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1190]
I currently cannot link GPS hits with stations because the GPS hits api requires you to enter the `deviceID` of the receiver which I do not have access to.

Can this be changed to `sensorID` or just the serial number of the receiver? I can use either of those.

**Comment by cjardine-bsc** [comment]
I had previously asked about combining the GPS call and the antenna activity call. But I think we decided on a call eons ago that we would be better to keep them separate (as per your original request). 

<html><body>
<h3 dir="auto">ourly GPS fixes</h3>
<ul dir="auto">
<li>API returns a <strong>single receiver</strong> at a time.</li>
<li>Summarise GPS fixes per hour per receiver. Hourly count of fixes to be in new column named <code class="notranslate">fixes</code>. Rows where <code class="notranslate">fixes == 0</code> are omitted.</li>
</ul>


receiverID | hourBin | fixes
-- | -- | --



</body>
</html>


For this one, I'd like to just use the det_gps table. For almost all receivers, the GPS only records a fix once per hour. Are we anticipating future cases where the sum of the gps hits for a given hour will be more than one? Right now there are only 2k times where an hourbin has more than one GPS hit. And these are almost all cases of two hits. It would be more efficient to just return a list of the hourbins where the station had hits, and not worry about the count of hits. What do you think?  

You mention wanting sensorID wouldn't you rather have stationID? Same effort for either. 

Do you want the actual ts where the gps hit occurred or do you want me to resolve those to hourbins? 



<html><body>
<h3 dir="auto">Antenna pulses</h3>
<ul dir="auto">
<li>API returns a <strong>single receiver deployment</strong> at a time,
 unless there is a more efficient solution. I will actually be 
displaying antenna pulses from a single station at a time which 
frequently encompasses multiple receivers.</li>
<li>Summarise antenna pulses per hour per antenna. Hourly count of fixes to be in new column named <code class="notranslate">fixes</code>. Rows where <code class="notranslate">fixes == 0</code> are omitted.</li>
</ul>


stationDeployID | port | hourBin | pulseCount
-- | -- | -- | --



</body>
</html>

I've set something up that returns fairly quickly when you feed it the stationID (vwDashboard_ant_pulse). I'm surprised how fast it is going. Will need some testing, maybe with old cut..... start with the final boss. 

Do you need the data null filled? i.e. have hourbins that are within the deployments but have 0 pulse counts? or should I remove those? 

Okay, I think that's the last DB task for the dashboards. Once you take a look and answer my few last questions I'll get things tidy and send Denis the list of changes/additions needed for the api entry points. If I missed anything let me know!

**Comment by leberrigan** [comment]
Sorry - I didn't see this until now..
# Hourly GPS fixes
> For this one, I'd like to just use the det_gps table. For almost all receivers, the GPS only records a fix once per hour. Are we anticipating future cases where the sum of the gps hits for a given hour will be more than one? Right now there are only 2k times where an hourbin has more than one GPS hit. And these are almost all cases of two hits. It would be more efficient to just return a list of the hourbins where the station had hits, and not worry about the count of hits. What do you think?
- Works for me!
> You mention wanting sensorID wouldn't you rather have stationID? Same effort for either.
- Yeah, sure!
> Do you want the actual ts where the gps hit occurred or do you want me to resolve those to hourbins?
- I'd rather get the TS since I need it to convert it into a javascript time object.

# Antenna pulses
> Do you need the data null filled? i.e. have hourbins that are within the deployments but have 0 pulse counts? or should I remove those?
- No, I'd rather omit hour bins with 0 pulses

**Comment by denislepage** [comment]
I deployed the new entry point: /data/dashboard/count/antPulses

Reading for testing.

**Comment by leberrigan** [comment]
Doesn't appear to be working?
https://sandbox.motus.org/data/dashboard/count/antPulses?stationId=462&page=2

**Comment by denislepage** [comment]
I may have missed an API term in the url or something like that. Compare with the other calls

**Comment by denislepage** [comment]
Oh. The ant build needed to deploy to sandbox2 for the new Tomcat server. :-)

It's working now: https://sandbox.motus.org/data/dashboard/antPulse?stationId=452&page=1

**Comment by leberrigan** [comment]
Looks good. I see an additional variable 'row' which seems to be just the row number and can be omitted.

**Comment by denislepage** [comment]
Done. I also added the antenna number as part of the sorting, which was missing. Pagination should always be done on a unique set of key values. May be ok to close this one?

**Comment by leberrigan** [comment]
yup - that's all I need. Thanks!

**Comment by denislepage** [comment]
I thought I had taken that out,, but i will. That's an artefact of sorting/paging.
