### ISSUE TITLE
SensorGnome link under Troubleshooting Guide directs to wrong page

### ISSUE THREAD

**Issue by eageldart** [MotusDev/Motus-TO-DO#1191]
I am trying to access the SensorGnome Guide from the Troubleshooting Guide (https://motus.org/troubleshooting-guide/) under Resources (screenshot below) 
 
![1](https://user-images.githubusercontent.com/94930170/165806027-d14c1e7e-afcc-4c31-9e88-5ee40c4f4d09.png)

The SensorGnome Guide link brings you to https://motus.org/data/project/sgJobs (screenshot below) 

![2](https://user-images.githubusercontent.com/94930170/165806037-bdcb3186-c35e-420f-be70-7448efdfde81.png)

I believe it is supposed to bring you to the following link:  
https://docs.motus.org/sensorgnome

**Comment by Hussell** [comment]
@leberrigan I *think* this is yours? Let me know if this is someone else's creation.

**Comment by leberrigan** [comment]
I can remove this - don't think it's useful
