### ISSUE TITLE
Can we close access to manual tag registration?

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#1193]
Just had a case where users registered a set of tags that had already been registered by lotek. 

It may be time to shut down the ability for users to upload their own tag recordings?

**Comment by denislepage** [comment]
That'd be handled by motusServer. Not sure yet of what changes would need to happen to disable this feature alone. At the very least, we should update the page to say that manual tag registration is no longer supported, or we could change API to simply ignore those calls from sgdata.

**Comment by j-sayers** [comment]
People are still registering tags though. Last week for instance, someone had tags purchased earlier in 2021 that hadn't been registered yet. Aren't they just getting "tag already exists" errors when trying to register?

**Comment by cjardine-bsc** [comment]
No. They only get that error when they register the same tag twice within the same date_bin. 

I can make it so their registrations fail in the back end, but I'm not sure what that will do to the results the user sees.  I'd need to check with Jeremy. 

Either way. Lets put a big warning on that page that says tags purchased after Feb 2022 should NOT be registered. With a link to their tag page so they can review their registered tags.

**Comment by j-sayers** [comment]
Yeah only getting that error within the same date_bin does leave the door open for potential (very serious) issues since they could be just a day apart and be in two different date_bins. 

A big warning will help for now!

**Comment by cjardine-bsc** [comment]
I’m making a change to prAPIImportTagsTransfer if a user registers a tag that already exists in the tagsActive view they are now going to get an error. This will prevent problems of potential duplicate registrations lfrom going unnoticed until we get through this two-registration-methods-at-the-same-time phase.

**Comment by denislepage** [comment]
As per Josh's point, we may want to also curtail registration for at least the previous dateBin value (or perhaps 2). I imagine there will be cases though where the same tag properties are used in 2 consecutive seasons (e.g. spring and fall)? Can we find out how often this happens (e.g. 2 distinct tag IDs with the same properties, but slightly different date bins?)

**Comment by cjardine-bsc** [comment]
The change I made will do that and more. If it's on the vwTagsActive list the registration will fail. :-)

**Comment by denislepage** [comment]
I see now. Makes sense.
