### ISSUE TITLE
Test tag no longer showing up on Motus website despite being detected

### ISSUE THREAD

**Issue by ajmacdonald3** [MotusDev/Motus-TO-DO#1199]
I’m trying to solve a small mystery that I think may have happened with the beta 10 launch. I have a CTT lifetag test tag that was registered to project 322 (Test Tags). I noticed it wasn’t showing up on motus when I set up the last [station at UNBC](https://motus.org/data/receiverDeploymentDetections?id=8649) despite seeing it on the web interface. The Lotek test tag does show up. I did some digging and it is now in project 23 (Motus), though I did not move it there. It still has an active deployment though, so I would have thought it would still show up as a detected tag. [TagID  = 36605](https://motus.org/data/tag?id=36605), DeploymentID = 27191, mfgID = 61330766. Should I just terminate the deployment, move it back to 322 and start a new test deployment?

**Comment by leberrigan** [comment]
Is it possible the missing tag data is from May 18-21? See #1201

**Comment by ajmacdonald3** [comment]
Yes, we set up that station on May 18, so maybe it is related to the CTT data gap.

**Comment by ajmacdonald3** [comment]
The test tag reappeared after the CTT data gap was resolved.
