### ISSUE TITLE
Let receiver deployments be marked as test deployments

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#120]
Are we allowing users to mark sensor deployments as test? Is there such thing as a test deployment (if it's on and detecting tags then that's ligit right?) 

There are 4 sensor deployments in the DB marked as test.

**Comment by denislepage** [comment]
Test was meant for receivers turned on in a lab, where they are testing tags.

That’s a bit of an overlap with the concept of test tag deployments. You could possibly achieve the same by setting these tags deployments as tests in at least some circumstances, but in some cases, it may be simpler to do it from the receiver side? It’d just be a simple way for having someone identifying periods for which there are detections that they are not considering valid for any reason. I’m not 100% sure of that those reasons would be, however. If it doesn’t hurt to have the status there, I’d be inclined to keep it for now.

**Comment by cjardine-bsc** [comment]
But what if a real tagged bird flies past the lab window?!?! :D (tehehe...)

Paul, Can you add a field for test on the sensor deployment page? Thanks!

**Comment by pmorrill** [comment]
Done: checked into master and beta5 branch. The interface will change some when I implement the alterations to site definition rules as discussed last week.
