### ISSUE TITLE
Network-wide missing data from CTT radios on SensorStation receivers: May 18-21

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1201]
Large gaps in data are missing from May 18-21 over the exact same time periods for all CTT SensorStations across the network.
![image](https://user-images.githubusercontent.com/35931796/170089609-56177bf7-715c-4d1a-8da6-215d39a2e653.png)

Bob is looking into it on their end - it's not yet clear where the problem is occurring. 

Lotek data appears to be flowing normally - station in Montana that was detection both CTT and Lotek tags continued to detect Lotek tags over the time period when CTT tags are not being detected.

Lotek antenna pulses and GPS hits are also being recorded correctly.

Pennsylvania (CTT tags only): https://motus.org/data/receiver/deployment/detections/timeline?year=2022&id=6131
Montana (Lotek and CTT tags): https://motus.org/data/receiver/deployment/detections/timeline?year=2022&id=6156

**Comment by Hussell** [comment]
Must be us. I'm seeing activity and detections on the receiver deployment plots:
https://motus.org/data/receiver/deployment/plot?id=6131
https://motus.org/data/receiver/deployment/plot?id=6156

So the data must have been processed on sgdata and successfully transferred to the main database. It's likely the summarisation process have been failing.

**Comment by cjardine-bsc** [comment]
Hmm, no I think something wonky is happening upstream. There is a pretty clear gap on the plot Jeremy shared: 

![image](https://user-images.githubusercontent.com/22172758/170111798-c5813253-944b-4393-a6d0-dee9982e7f6a.png)


And in the DB, I'm seeing some gaps for those receivers in terms of batches. Data was coming in every hour or so before the 18th, and since then we've only received 3 batches. 

![image](https://user-images.githubusercontent.com/22172758/170112324-dd5fde8c-f157-4b39-9da0-3293f740c890.png)


So whatever has gone wrong is happening before the data is written to the DB.

**Comment by denislepage** [comment]
There was some disk failure happening last week. Kwic changed a disk on Thursday and the array should now be rebuilt.

However, this is more likely related to the new tomcat instance I installed around that date.

I can see a large number of unprocessed data in the beta folder, all dated 18 May or later.

The proc appears to be running, but it seems to be ignoring the data files, so it may be looking in the wrong place.

**Comment by ajmacdonald3** [comment]
Not sure if this is related, but sensorstations connected to cell have not sent data to motus since May 22 and they usually send it daily (checked all of mine and a number of others). They have sent data to CTT.

**Comment by Hussell** [comment]
Two different things, I think. An issue on our end from 05-18 to 05-21, and an ongoing issue at CTT beginning 05-22.

**Comment by denislepage** [comment]
It'll take perhaps a day or two to clear the backup, so let's revisit again once that is done. I'm not entirely clear either. I see data stored in 2 different formats in the queue. One format contains files for 18-21 May, and the other contains ONLY files for 22 May. 

The sandbox queue also has a number of unprocessed files, but only for a brief period on 22 May (13-14h), which seems odd.

**Comment by denislepage** [comment]
As far as I can tell, it's processed about 10% of the backlog, so it may be done by tomorrow night, depending on the size of the individual batches.

**Comment by denislepage** [comment]
All done. As I thought, a small number of files didn't get processed in sandbox, and went straight to the main database. I don't think we need to worry about those, but for safekeeping, I am attaching the list of batch ID's (the second number is the batch UID, which is meant to match batches between sandbox and live).

I am going to close this, but someone should confirm that the data gaps have been resolved. @leberrigan are you also going to let Bob know, or perhaps we need to resolve and see if anything else is happening on their end.

batch-6083316-7125889934228000
batch-6083359-7129503616966000
batch-6084371-7151244481614400
batch-6084373-7151244603369200
batch-6084375-7151244785974700
batch-6084376-7151244895313600
batch-6084377-7151244946513300
batch-6084378-7151245019320300
batch-6084380-7151245125571600
batch-6084384-7151245469176300
batch-6084386-7151245588188400
batch-6084388-7151245697238100
batch-6084390-7151245864274500
batch-6084398-7151246373779100
batch-6084402-7151246573298300
batch-6084404-7151246863891900
batch-6084410-7151247232160600
batch-6084413-7151247443394900
batch-6084414-7151247489252000
batch-6084417-7151248123320500
batch-6084418-7151248576156900
batch-6084422-7151249030837700
batch-6084424-7151249144957700
batch-6084425-7151249199657500
batch-6084426-7151249248543400
batch-6084429-7151249391379700
batch-6084431-7151249500214500
batch-6084435-7151249937711900
batch-6084436-7151250032458900
batch-6084443-7151250416572500
batch-6084444-7151250489732000
batch-6084445-7151250640931400
batch-6084447-7151250734489000
batch-6084452-7151250988281700
batch-6084453-7151251094683200
batch-6084457-7151251408964100
batch-6084458-7151251507966400
batch-6084552-7158497207571200
batch-6096535-7212655493637400
batch-6099283-7281476286965400
batch-6099800-7298741418604600
batch-6101126-7352919762978200
batch-6101127-7352924860196500
batch-6101134-7352946009902700
batch-6101135-7352947815755600
batch-6101150-7353008564924100
batch-6101151-7353011711046800
batch-6101152-7353017194773500
batch-6101153-7353020092545400
batch-6101156-7353028965774300
batch-6101157-7353032453266600
batch-6101176-7353121313903400
batch-6101177-7353122200225300
batch-6101178-7353127329155800
batch-6101179-7353127816727200
batch-6101180-7353128994202500
batch-6101181-7353130108812200
batch-6101184-7353138404502900
batch-6101185-7353139356722100
batch-6101193-7353219519402600
batch-6101194-7353222977775300
batch-6101199-7353246157061100
batch-6101200-7353247514805000
batch-6101201-7353254920276800
batch-6101202-7353256037611700
batch-6101209-7353356634384900
batch-6101210-7353375628586400
batch-6101213-7353440500076900
batch-6101214-7353483194594300
batch-6101216-7353589893232800
batch-6101217-7353603200853400
batch-6101218-7353608643884100
batch-6101219-7353622607034200
batch-6101220-7353638374082300
batch-6101222-7353683065917400
batch-6101224-7353703689240600
batch-6101225-7353707444580600
batch-6101226-7353719179143200
batch-6101227-7353723362341200
batch-6101229-7353749774445700
batch-6101230-7353752054861100
batch-6101233-7353869951953900
batch-6101235-7353930715592700
batch-6101237-7353957246225500
batch-6101238-7353957397085300
batch-6101277-7353452214375100
batch-6101278-7353468833432300
batch-6101280-7353585148576200
batch-6101281-7353620059049700
batch-6101282-7353635577933400
batch-6101283-7353676832070300
batch-6101284-7353677899940700
batch-6101286-7353679874608100
batch-6101288-7353715891774900
batch-6101289-7353721907187200
batch-6101295-7353862430164100
batch-6101297-7353890636746300
batch-6101298-7353892342128100
batch-6101301-7353922035931600
batch-6101317-7354010498680900
batch-6101318-7354011184054100
batch-6101325-7354024688680200
batch-6101326-7354024979714400
batch-6101330-7354059199005800
batch-6101331-7354060623771500
batch-6101342-7354155538500400
batch-6101343-7354160921027700
batch-6101348-7354200467299400
batch-6101349-7354203164429100
batch-6101354-7354256354779700
batch-6101355-7354258813345500
batch-6101356-7354285620238800
batch-6101357-7354286367765600
batch-6101364-7354346600274700
batch-6101365-7354349704064200
batch-6101368-7354371941486200
batch-6101369-7354372380185100
batch-6101370-7354373202990500
batch-6101371-7354375541661100
batch-6101372-7354388116786900
batch-6101373-7354388368317300
batch-6101378-7354424403255000
batch-6101379-7354431292212500
batch-6101382-7354454698409100
batch-6101383-7354462392688700
batch-6101390-7354519063948800
batch-6101391-7354522207653900
batch-6101392-7354555420201400
batch-6101393-7354557510418200
batch-6101406-7354590569694300
batch-6101407-7354591179887300
batch-6101408-7354597599825600
batch-6101409-7354598619396100
batch-6101410-7354612135575200
batch-6101411-7354613076007700
batch-6101414-7354628401688300
batch-6101415-7354628836540800
batch-6101424-7354686013876300
batch-6101425-7354687512784700
batch-6101426-7354690619495900
batch-6101427-7354691544614000
batch-6101436-7354744857769000
batch-6101437-7354745076583500
batch-6101442-7354748488409100
batch-6101443-7354755450639400
batch-6101444-7354756645505800
batch-6101445-7354756841266800
batch-6101448-7354766164686700
batch-6101449-7354769700557300
batch-6101456-7354824519664400
batch-6101457-7354825841140800
batch-6101462-7354862485001500
batch-6101463-7354865265572100
batch-6101464-7354869275654800
batch-6101465-7354873116266300
batch-6101468-7354897173850000
batch-6101469-7354900603727400
batch-6101470-7354907783360400
batch-6101471-7354914396772000
batch-6101476-7354943968617300
batch-6101489-7354996270274900
batch-6101490-7355000930623300
batch-6101501-7355362388987900
batch-6101502-7355363933794300
batch-6101505-7355378541540000
batch-6101506-7355379372001600
batch-6101507-7355382454162700
batch-6101508-7355382793787700
batch-6101509-7355383387961500
batch-6101510-7355383566004400
batch-6101513-7355396406285400
batch-6101514-7355398083500400
batch-6101517-7355408703042800
batch-6101519-7355409372086200
batch-6101520-7355409475418300
batch-6101521-7355418389953900
batch-6101522-7355425149780000
batch-6101523-7355432382583200
batch-6101524-7355432675247000
batch-6101525-7355440947815700
batch-6101526-7355441098585700
batch-6101527-7355441978994500
batch-6101528-7355446009613700
batch-6101531-7355465442638800
batch-6101532-7355467340917500
batch-6101534-7355485563014200
batch-6101535-7355576762684300
batch-6101536-7355589555710800
batch-6101540-7355689413026400
batch-6101541-7355689928182500
batch-6101542-7355712371784500
batch-6101543-7355712729722800
batch-6101544-7355718921362900
batch-6101552-7355751163432400
batch-6101557-7355766234293600
batch-6101558-7355766485237900
batch-6101559-7355771339742200
batch-6102100-7355714413250100
batch-6102102-7355750841929700
batch-6102107-7355770566123000
batch-6102112-7355848002057400
batch-6102113-7355848909006700
batch-6102114-7355849592486800
batch-6102115-7355849841192300
batch-6102119-7355867655060700
batch-6102120-7355867911599500
batch-6102125-7355886404710700
batch-6102136-7355929056660000
batch-6102137-7355930608251800
batch-6102138-7355933894238100
batch-6102139-7355934091435200
batch-6102146-7355948577603400
batch-6102147-7355949414697000
batch-6102148-7355951988583000
batch-6102149-7355952186320500
batch-6102150-7355954117081500
batch-6102151-7355954374834400
batch-6102158-7355966666008800
batch-6102159-7355969211750600
batch-6102164-7355989008041100
batch-6102165-7355989204384000
batch-6102166-7355989876346300
batch-6102167-7355991372054600
batch-6102168-7355994530041600
batch-6102169-7355996696213000
batch-6102172-7356010632198500
batch-6102173-7356011296564000
batch-6102176-7356021485703600
batch-6102177-7356024344881200
batch-6102178-7356024853061200
batch-6102179-7356025034285600
batch-6102180-7356028715037500
batch-6102181-7356028909820000
batch-6102182-7356046538580500
batch-6102183-7356046851248300
batch-6102194-7356071930422600
batch-6102195-7356073015892000
batch-6102206-7356115394845200
batch-6102207-7356116366429800
batch-6102226-7356169710290300
batch-6102227-7356172252707200
batch-6102232-7356182326959700
batch-6102233-7356183458615400
batch-6102246-7356225259461500
batch-6102247-7356226517676700
batch-6102254-7356287478285600
batch-6102255-7356288483231300
batch-6102264-7356333868093500
batch-6102265-7356336631083800
batch-6102270-7356350854099400
batch-6102271-7356351052216500
batch-6102278-7356369990679600
batch-6102279-7356370539684000
batch-6102288-7356407581557600
batch-6102289-7356408459332900
batch-6102292-7356414396336900
batch-6102293-7356416426098700
batch-6102296-7356425998601200
batch-6102297-7356426195881700
batch-6102314-7356492965260600
batch-6102315-7356494186806200
batch-6102316-7356514798130200
batch-6102317-7356516315933000
batch-6102318-7356520500770700
batch-6102319-7356522229636600
batch-6102340-7356560967898000
batch-6102341-7356561200269500
batch-6102344-7356563198144400
batch-6102345-7356564422146900
batch-6102350-7356595982423900
batch-6102351-7356597242251700
batch-6102352-7356598214566000
batch-6102353-7356602444736300
batch-6102356-7356647672518600
batch-6102357-7356651667312800
batch-6102358-7356653093604300
batch-6102359-7356667694731800
batch-6102360-7356671052564700
batch-6102363-7356681256008000
batch-6102364-7356682259556500
batch-6102379-7356763157021500
batch-6102380-7356765043772600
batch-6102383-7356777355394900
batch-6102384-7356779587588200
batch-6102385-7356780155137000
batch-6102386-7356780352006400
batch-6102389-7356784543044800
batch-6102390-7356784743249700
batch-6102391-7356786407200300
batch-6102392-7356789167586300
batch-6102395-7356802246211200
batch-6102396-7356807047045400
batch-6102397-7356816719843700
batch-6102398-7356824507192600
batch-6102399-7356829849890600
batch-6102400-7356831949698300
batch-6102403-7356855622447100
batch-6102404-7356855997648500
batch-6102409-7356901675684800
batch-6102410-7356903945267600
batch-6102413-7356922663448400
batch-6102414-7356929445636500
batch-6102419-7356983392655500
batch-6102420-7356994575815500
batch-6102441-7357099736174400
batch-6102442-7357100084335200
batch-6102443-7357103627301600
batch-6102444-7357107100826100

**Comment by denislepage** [comment]
All done. As I thought, a small number of files didn't get processed in sandbox, and went straight to the main database. I don't think we need to worry about those, but for safekeeping, I am attaching the list of batch ID's (the second number is the batch UID, which is meant to match batches between sandbox and live).

I am going to close this, but someone should confirm that the data gaps have been resolved. @leberrigan are you also going to let Bob know, or perhaps we need to resolve and see if anything else is happening on their end.

batch-6083316-7125889934228000
batch-6083359-7129503616966000
batch-6084371-7151244481614400
batch-6084373-7151244603369200
batch-6084375-7151244785974700
batch-6084376-7151244895313600
batch-6084377-7151244946513300
batch-6084378-7151245019320300
batch-6084380-7151245125571600
batch-6084384-7151245469176300
batch-6084386-7151245588188400
batch-6084388-7151245697238100
batch-6084390-7151245864274500
batch-6084398-7151246373779100
batch-6084402-7151246573298300
batch-6084404-7151246863891900
batch-6084410-7151247232160600
batch-6084413-7151247443394900
batch-6084414-7151247489252000
batch-6084417-7151248123320500
batch-6084418-7151248576156900
batch-6084422-7151249030837700
batch-6084424-7151249144957700
batch-6084425-7151249199657500
batch-6084426-7151249248543400
batch-6084429-7151249391379700
batch-6084431-7151249500214500
batch-6084435-7151249937711900
batch-6084436-7151250032458900
batch-6084443-7151250416572500
batch-6084444-7151250489732000
batch-6084445-7151250640931400
batch-6084447-7151250734489000
batch-6084452-7151250988281700
batch-6084453-7151251094683200
batch-6084457-7151251408964100
batch-6084458-7151251507966400
batch-6084552-7158497207571200
batch-6096535-7212655493637400
batch-6099283-7281476286965400
batch-6099800-7298741418604600
batch-6101126-7352919762978200
batch-6101127-7352924860196500
batch-6101134-7352946009902700
batch-6101135-7352947815755600
batch-6101150-7353008564924100
batch-6101151-7353011711046800
batch-6101152-7353017194773500
batch-6101153-7353020092545400
batch-6101156-7353028965774300
batch-6101157-7353032453266600
batch-6101176-7353121313903400
batch-6101177-7353122200225300
batch-6101178-7353127329155800
batch-6101179-7353127816727200
batch-6101180-7353128994202500
batch-6101181-7353130108812200
batch-6101184-7353138404502900
batch-6101185-7353139356722100
batch-6101193-7353219519402600
batch-6101194-7353222977775300
batch-6101199-7353246157061100
batch-6101200-7353247514805000
batch-6101201-7353254920276800
batch-6101202-7353256037611700
batch-6101209-7353356634384900
batch-6101210-7353375628586400
batch-6101213-7353440500076900
batch-6101214-7353483194594300
batch-6101216-7353589893232800
batch-6101217-7353603200853400
batch-6101218-7353608643884100
batch-6101219-7353622607034200
batch-6101220-7353638374082300
batch-6101222-7353683065917400
batch-6101224-7353703689240600
batch-6101225-7353707444580600
batch-6101226-7353719179143200
batch-6101227-7353723362341200
batch-6101229-7353749774445700
batch-6101230-7353752054861100
batch-6101233-7353869951953900
batch-6101235-7353930715592700
batch-6101237-7353957246225500
batch-6101238-7353957397085300
batch-6101277-7353452214375100
batch-6101278-7353468833432300
batch-6101280-7353585148576200
batch-6101281-7353620059049700
batch-6101282-7353635577933400
batch-6101283-7353676832070300
batch-6101284-7353677899940700
batch-6101286-7353679874608100
batch-6101288-7353715891774900
batch-6101289-7353721907187200
batch-6101295-7353862430164100
batch-6101297-7353890636746300
batch-6101298-7353892342128100
batch-6101301-7353922035931600
batch-6101317-7354010498680900
batch-6101318-7354011184054100
batch-6101325-7354024688680200
batch-6101326-7354024979714400
batch-6101330-7354059199005800
batch-6101331-7354060623771500
batch-6101342-7354155538500400
batch-6101343-7354160921027700
batch-6101348-7354200467299400
batch-6101349-7354203164429100
batch-6101354-7354256354779700
batch-6101355-7354258813345500
batch-6101356-7354285620238800
batch-6101357-7354286367765600
batch-6101364-7354346600274700
batch-6101365-7354349704064200
batch-6101368-7354371941486200
batch-6101369-7354372380185100
batch-6101370-7354373202990500
batch-6101371-7354375541661100
batch-6101372-7354388116786900
batch-6101373-7354388368317300
batch-6101378-7354424403255000
batch-6101379-7354431292212500
batch-6101382-7354454698409100
batch-6101383-7354462392688700
batch-6101390-7354519063948800
batch-6101391-7354522207653900
batch-6101392-7354555420201400
batch-6101393-7354557510418200
batch-6101406-7354590569694300
batch-6101407-7354591179887300
batch-6101408-7354597599825600
batch-6101409-7354598619396100
batch-6101410-7354612135575200
batch-6101411-7354613076007700
batch-6101414-7354628401688300
batch-6101415-7354628836540800
batch-6101424-7354686013876300
batch-6101425-7354687512784700
batch-6101426-7354690619495900
batch-6101427-7354691544614000
batch-6101436-7354744857769000
batch-6101437-7354745076583500
batch-6101442-7354748488409100
batch-6101443-7354755450639400
batch-6101444-7354756645505800
batch-6101445-7354756841266800
batch-6101448-7354766164686700
batch-6101449-7354769700557300
batch-6101456-7354824519664400
batch-6101457-7354825841140800
batch-6101462-7354862485001500
batch-6101463-7354865265572100
batch-6101464-7354869275654800
batch-6101465-7354873116266300
batch-6101468-7354897173850000
batch-6101469-7354900603727400
batch-6101470-7354907783360400
batch-6101471-7354914396772000
batch-6101476-7354943968617300
batch-6101489-7354996270274900
batch-6101490-7355000930623300
batch-6101501-7355362388987900
batch-6101502-7355363933794300
batch-6101505-7355378541540000
batch-6101506-7355379372001600
batch-6101507-7355382454162700
batch-6101508-7355382793787700
batch-6101509-7355383387961500
batch-6101510-7355383566004400
batch-6101513-7355396406285400
batch-6101514-7355398083500400
batch-6101517-7355408703042800
batch-6101519-7355409372086200
batch-6101520-7355409475418300
batch-6101521-7355418389953900
batch-6101522-7355425149780000
batch-6101523-7355432382583200
batch-6101524-7355432675247000
batch-6101525-7355440947815700
batch-6101526-7355441098585700
batch-6101527-7355441978994500
batch-6101528-7355446009613700
batch-6101531-7355465442638800
batch-6101532-7355467340917500
batch-6101534-7355485563014200
batch-6101535-7355576762684300
batch-6101536-7355589555710800
batch-6101540-7355689413026400
batch-6101541-7355689928182500
batch-6101542-7355712371784500
batch-6101543-7355712729722800
batch-6101544-7355718921362900
batch-6101552-7355751163432400
batch-6101557-7355766234293600
batch-6101558-7355766485237900
batch-6101559-7355771339742200
batch-6102100-7355714413250100
batch-6102102-7355750841929700
batch-6102107-7355770566123000
batch-6102112-7355848002057400
batch-6102113-7355848909006700
batch-6102114-7355849592486800
batch-6102115-7355849841192300
batch-6102119-7355867655060700
batch-6102120-7355867911599500
batch-6102125-7355886404710700
batch-6102136-7355929056660000
batch-6102137-7355930608251800
batch-6102138-7355933894238100
batch-6102139-7355934091435200
batch-6102146-7355948577603400
batch-6102147-7355949414697000
batch-6102148-7355951988583000
batch-6102149-7355952186320500
batch-6102150-7355954117081500
batch-6102151-7355954374834400
batch-6102158-7355966666008800
batch-6102159-7355969211750600
batch-6102164-7355989008041100
batch-6102165-7355989204384000
batch-6102166-7355989876346300
batch-6102167-7355991372054600
batch-6102168-7355994530041600
batch-6102169-7355996696213000
batch-6102172-7356010632198500
batch-6102173-7356011296564000
batch-6102176-7356021485703600
batch-6102177-7356024344881200
batch-6102178-7356024853061200
batch-6102179-7356025034285600
batch-6102180-7356028715037500
batch-6102181-7356028909820000
batch-6102182-7356046538580500
batch-6102183-7356046851248300
batch-6102194-7356071930422600
batch-6102195-7356073015892000
batch-6102206-7356115394845200
batch-6102207-7356116366429800
batch-6102226-7356169710290300
batch-6102227-7356172252707200
batch-6102232-7356182326959700
batch-6102233-7356183458615400
batch-6102246-7356225259461500
batch-6102247-7356226517676700
batch-6102254-7356287478285600
batch-6102255-7356288483231300
batch-6102264-7356333868093500
batch-6102265-7356336631083800
batch-6102270-7356350854099400
batch-6102271-7356351052216500
batch-6102278-7356369990679600
batch-6102279-7356370539684000
batch-6102288-7356407581557600
batch-6102289-7356408459332900
batch-6102292-7356414396336900
batch-6102293-7356416426098700
batch-6102296-7356425998601200
batch-6102297-7356426195881700
batch-6102314-7356492965260600
batch-6102315-7356494186806200
batch-6102316-7356514798130200
batch-6102317-7356516315933000
batch-6102318-7356520500770700
batch-6102319-7356522229636600
batch-6102340-7356560967898000
batch-6102341-7356561200269500
batch-6102344-7356563198144400
batch-6102345-7356564422146900
batch-6102350-7356595982423900
batch-6102351-7356597242251700
batch-6102352-7356598214566000
batch-6102353-7356602444736300
batch-6102356-7356647672518600
batch-6102357-7356651667312800
batch-6102358-7356653093604300
batch-6102359-7356667694731800
batch-6102360-7356671052564700
batch-6102363-7356681256008000
batch-6102364-7356682259556500
batch-6102379-7356763157021500
batch-6102380-7356765043772600
batch-6102383-7356777355394900
batch-6102384-7356779587588200
batch-6102385-7356780155137000
batch-6102386-7356780352006400
batch-6102389-7356784543044800
batch-6102390-7356784743249700
batch-6102391-7356786407200300
batch-6102392-7356789167586300
batch-6102395-7356802246211200
batch-6102396-7356807047045400
batch-6102397-7356816719843700
batch-6102398-7356824507192600
batch-6102399-7356829849890600
batch-6102400-7356831949698300
batch-6102403-7356855622447100
batch-6102404-7356855997648500
batch-6102409-7356901675684800
batch-6102410-7356903945267600
batch-6102413-7356922663448400
batch-6102414-7356929445636500
batch-6102419-7356983392655500
batch-6102420-7356994575815500
batch-6102441-7357099736174400
batch-6102442-7357100084335200
batch-6102443-7357103627301600
batch-6102444-7357107100826100
