### ISSUE TITLE
sgdata unreachable 

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1206]
Just noticed now that sgdata.motus.org is unreachable and attempts to reach https://motus.org/data/project/sgJobs generates an error (Trying to access https://sgdata.motus.org/status2/authenticate_user got response: HTTP/1.1 502 Proxy Error).

~~Perhaps relatedly, or perhaps not, there is no new data from networked SG's or SS since yesterday.~~

**Comment by denislepage** [comment]
The processes are running, but there is a bit of backlog. We are talking to CTT very shortly, so I can ask, but there seems to be a big push of data right now from their end. If this is the new normal volume, we may be starting to get closer to a point soon where data comes in faster than we can process them.

I can log into in sgdata, and apache seems to be running ok. I've asked  @Hussell to investigate. @joeybernard  can hopefully find the root of this problem, now that we (almost?) have a sandbox to play in.

**Comment by Hussell** [comment]
Restarted.
