### ISSUE TITLE
Changes to Project Management Page

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1207]
As discussed on June 9 call:
- Add dropdown for fee contact (users registered to project)
- Add dropdown for project group (one of [motus].[dbo].[lk_group])

### Groups
Department of Interior (USFWS, USGS, BOEM) - CRADA 
Environment and Climate Change Canada
Atlantic Offshore Wind
Birds Canada

### Fees 
Institution of the Principal Investigator
Department of Interior (USFWS, USGS, BOEM) - CRADA 
Environment and Climate Change Canada
Birds Canada

**Comment by denislepage** [comment]
@cjardine-bsc , is the new field for `fee_user_id `what it's gonna be called?

I can add it to the database, so I can start adding some of the Java support for it now. You have 2 minutes to respond until such a field exists… ;-)

**Comment by cjardine-bsc** [comment]
its already in sandbox. Projects, bt_projects and trigger. With FK to user_id

**Comment by denislepage** [comment]
![image](https://user-images.githubusercontent.com/21110542/172925160-151faaad-4a7f-4daf-9694-d474966844ad.png)

**Comment by cjardine-bsc** [comment]
Go forth and debt collect.

**Comment by cjardine-bsc** [comment]
@StuMackenzie should I populate the fee_user_id to be the primary contact where the user has selected project lead as the fee type?

**Comment by denislepage** [comment]
Done.

![image](https://user-images.githubusercontent.com/21110542/172932180-ee00df55-bad0-4d52-b1ff-be1b20637bfb.png)

Things that are still needed:

- copy all values from lead_user_id to fee_user_id as the default. @cjardine-bsc 
- copy all fee_id values to group_id as the default  @cjardine-bsc 
- Provided new and/or amended text fragments: Fee_contact and Fees_will_be_covered_by. (@StuMackenzie or @leberrigan )
- Confirm that the ordering of the 4 box is what we want (@StuMackenzie or @leberrigan )
- Test the functionality (@leberrigan )

**Comment by leberrigan** [comment]
Thanks! That was quick...

@cjardine-bsc 
- I have updated the text fragments in sandbox - can you push it to live?
- Can you change in `Fees_will_be_covered_by` the value 'Institution of the Principal Investigator' to: 
  - EN: The project fee contact
  - FR: Le contact des frais de projet
  - ES: El contacto de la tarifa del proyecto

@denislepage
- Ordering looks great.
- Can you add a row to the select menu under `fee_contact` which is 'select one' or whatever? Right now it just picks the top option and if someone presses 'save' without being careful the fee contact will be incorrect.

**Comment by leberrigan** [comment]
> @StuMackenzie should I populate the fee_user_id to be the primary contact where the user has selected project lead as the fee type?

Yes! We'll need a default and if it's wrong that will change fairly quickly.

**Comment by cjardine-bsc** [comment]
copy all values from lead_user_id to fee_user_id as the default. @cjardine-bsc

Done

copy all fee_id values to group_id as the default @cjardine-bsc

done 

 have updated the text fragments in sandbox - can you push it to live?
 
Done

Can you change in Fees_will_be_covered_by the value 'Institution of the Principal Investigator' to:

    EN: The project fee contact
    FR: Le contact des frais de projet
    ES: El contacto de la tarifa del proyecto

Done

**Comment by denislepage** [comment]
For new projects (which is another we just test), main and fee contacts will be set by default to the logged in user. Now that the values are prepopulated for both fields, I don't think we need a blank option.

Other than testing a new project, I am not sure if anything else is needed? On new projects, we perhaps will need to add the new fields also? At the moment, it asks for none of them, but it should default the contact to the current user who creates the project, and to unaffiliated group and own project for fees.

**Comment by leberrigan** [comment]
That sounds fine with me. We should probably update the page for new projects since that will be part of the workflow in our guidance document. Also, it's missing all the instructions that the 'edit project' page has.

**Comment by j-sayers** [comment]
That all looks great!

@denislepage while you're in there are you able to add the **country** and **address2** fields to the user profile page (they exist in the admin profile page, but not the one accessible directly by users; #1063)

**Comment by denislepage** [comment]
Done. The field group_id in the project table was called "group_Id", with an uppercase I. SQL isn't fussy about case for field names, but Java was in this case. Seems to work now.

**Comment by leberrigan** [comment]
Thanks and welcome back ;)

**Comment by cjardine-bsc** [comment]
Done

**Comment by denislepage** [comment]
Are we ready to switch live to the new branch then? I’ll need to set up the new Tomcat server

@Hussell, can you merge the beta11 branch into live? Since live is likely based on beta10, you’ll need to undo the usual xml config changes.

**Comment by leberrigan** [comment]
Yes let's switch to live.

**Comment by leberrigan** [comment]
Also, we need to add these options when creating a new project. Right now we only have: 
![image](https://user-images.githubusercontent.com/35931796/182606755-29f8773e-10ff-4e69-a418-5c4893e0659f.png)
