### ISSUE TITLE
Link to a single site

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#121]
The issues page needs a way to link to and edit a single site so issues with a specific site can be addressed. E.g. the site is missing a name, its latitude and longitude are invalid, etc. Currently we link to a page that shows every site in a (sometimes very long) table, forcing the user to search for the specific site referred to, which usually means going back to the issues page to look up the name of the site then forward to search for the name in the table.

This could be as simple as providing an anchor for each row of the table, or as complicated as providing a fully independent page to edit a single site.

**Comment by pmorrill** [comment]
I've taken the simplest approach, to get something in place for you in beta5. But the site ad landowner pages need work - they were put together quickly when we changed the model for sites / landowner linkage to deployments.

I am going to open a new issue (enhancement) describing the next steps to sort it - which will be destined for beta6.

In the meantime, use eg:

/data/project/sites?projectID=9#site-325

where the numeral is the site ID.
