### ISSUE TITLE
Loading GPS hits and antenna pulses is too slow

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1210]
The main reason why it takes too long is server latency: it takes about 1.5 s to get a response for each GPS hit request and 10-15 seconds for each antenna pulses request. Since each request only includes 10k rows, I usually have to do multiple requests to get the full table. It takes only 5 ms between requests to send a new request, so it's definitely not my code slowing things down.

At this rate, it takes over a minute on average to load the pulses for each station which is really not great for a web app. We should aim for a response time of <500ms.

That said, I would be fine if we changed it so we only received a **daily** summary of gps hits and ant pulses - that would make it much faster to load and the plots I'm displaying are already summarised this way.

Below is my browser network console showing latency for each request.
![image](https://user-images.githubusercontent.com/35931796/174575716-0f68d994-8134-4711-911f-43a2eba178bf.png)

**Comment by leberrigan** [comment]
Works MUCH better than before, but I still think it would be good to have a daily _option_ for faster downloading and fewer individual requests to the server. 

There are 4 stations in particular that I've found so far that each have over 200,000 gps hits or antenna pulses (over 20 requests) and take a considerable time to load their activity timelines: 12203, 11953, 11207, 11578 

In another case, I want to make a report for the Motus Ontario Array, it takes several minutes to load yet I'm only looking at the daily summary.

**Comment by denislepage** [comment]
Define daily? ☺ I used a dayBin approach, which is based on UTC days (ts / 86400 sec, or hourBin / 24 hours). The new field is called dayBin. To convert dayBin to UTC date in Javascript:

```
var d = new Date(0);
d.setUTCSeconds(dayBin * 86400);
```

I created new entry points in sandbox for:

/gpsDaily
/antPulseDaily
/count/gpsDaily
/count/antPulse (was somehow missing)
/count/antPulseDaily

This should reduce by about 24 fold the number of records returned.

I saw some pulse records have pulseCount = null, but I left them in the results.

I haven’t tried the API, but it is deployed on sandbox.

It would be good to update the documentation for these entry points. Have you already started something?

**Comment by leberrigan** [comment]
Looks good - can you deploy to beta, too? I've been working on that for the most part.

I haven't updated documentation but can do so tomorrow.

**Comment by denislepage** [comment]
I merged the dashboard API servlet into beta11 and redeployed to beta. I also made the changes to the database.

@leberrigan can you give it a try on beta?

I am not 100% certain that indexing is the same, so the response time could be impacted.

**Comment by cjardine-bsc** [comment]
I'll check the indexing. I made the good indices on live, so it may even be faster there

**Comment by denislepage** [comment]
I added one in sandbox, but then realized that a similar one existed in live, which I left alone, and I didn’t look further.

**Comment by cjardine-bsc** [comment]
All done :-)

**Comment by leberrigan** [comment]
Works great on sandbox and beta. We're now at the 400-500ms mark per request which is what I was aiming for. Thanks!
