### ISSUE TITLE
sgdata appears down

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1212]
Haven't been able to reach sgadata, or data via the R package this morning

Maybe a restart is needed?  @cjardine-bsc @Hussell @denislepage

**Comment by denislepage** [comment]
Database lock. Got it unstuck.

**Comment by leberrigan** [comment]
Still isn't working

**Comment by cjardine-bsc** [comment]
website is back up and r package, but I'm seeing a few user authentication errors come through for sgdata

**Comment by denislepage** [comment]
@joeybernard has been looking into the sgdata server issues. If the R package problems persist, you can reopen.

**Comment by j-sayers** [comment]
This is affecting the website more generally actually.... @denislepage @Hussell @cjardine-bsc Is there a quick fix possible?

**Comment by denislepage** [comment]
We’ve been seeing several slow-downs in the past few weeks. I could be wrong, but this seems to have started with the recent changes that Catherine made to the summary procs.

It is a bit hard to nail down after the fact, and I am not seeing any red flags associated with procs in the past while, including around the time when you were failing to connect.

When that happens again, you can let me know asap, and I can examine a bit what else is happening at the same time.
