### ISSUE TITLE
Influx of false positive CTT detections

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1215]
We've had a few people (incl. Amie) report a recent influx in false positives found in CTT data – there are a few comments about it on the Slack channel: https://motuswts.slack.com/archives/C01JJ4PKQCU/p1656170054360229

This is unusual because we don’t normally see such false positives in the public data, but it’s almost as if the way CTT data has been filtered has changed – that’s just speculation. In any case, it’s resulting in birds turning up in odd locations in the public data just like with Lotek tags.

David La Puma’s comment was to say that folks need to confirm that ‘validated = 1’ in the data – I’m assuming that’s something we already do? It looks like it’s a column that we import with the CTT detections.

**Comment by ajmacdonald3** [comment]
Here are the recent false positives I've noticed on stations in northern BC. The stations running there for the last year have all been quiet (one false positive CTT TRES tag), but in the last week or so there have been quite a few false positives in the public outputs that would be good to remove.

| tagDeployID | recvDeployID |
|---------------|----------------|
| 39140           | 7971              |
| 32850           | 8711              |
| 31975           | 8711              |
| 26421           | 7913              |
| 34258           | 8721              |
| 39154           | 8698              |

**Comment by cjardine-bsc** [comment]
Thanks. That's helpful. Those are all run_len = 1, which means they should be filtered out, but they are not in the runs_filtered table. 

I think I know what happened. I overwrote a change that was only in live and never made it's way back to sandbox when I made some changes recently for Lucas. I've re-added the filter. 

I made the change two weeks ago. Running the CTT batches that came in between then and now through the proc should clean that up. That will take me a little bit. Stand by.

**Comment by cjardine-bsc** [comment]
@denislepage FYI I'm pausing imports for a moment to do this.

**Comment by denislepage** [comment]
Cool. I suggest pushing forward the last date run into the future, rather than disabling the entry.

**Comment by cjardine-bsc** [comment]
Thats what I did :-)

**Comment by cjardine-bsc** [comment]
Better?

**Comment by leberrigan** [comment]
Looks good to me - I'll reopen if I hear otherwise from collaborators
