### ISSUE TITLE
tag database for 2022 tags not available 

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1217]
Project 113 is trying to download their tag database but there is no product for 2022, despite them having registered 80 tags in 2022.

https://sgdata.motus.org/download/113/
https://motus.org/data/project/tagdb?projectID=113
`select * from tags where project_id = 113 and left(date_bin, 4) = '2022'
`

**Comment by eageldart** [comment]
Project 252 is having this same issue.

**Comment by denislepage** [comment]
closing in deference to #901
