### ISSUE TITLE
Tag for completely different project displayed on tag page

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1222]
I'm looking into the tags for Project 160 and on the right hand side is a tag from a completely different project (307) which I was looking into previously.

I have already viewed multiple tags for Project 160, but when I navigated back the previous tag for the project appeared.

This appears to be related to filtering for this tag ID previously in Project 307. Evidently something remained cached even though I navigated to and and within a new project (and cleared the filter itself, which was still present after I switched projects).

![image](https://user-images.githubusercontent.com/55001144/177810640-d4946d41-c203-4ce3-b49f-6ff0d953a058.png)

**Comment by cjardine-bsc** [comment]
@j-sayers Can you reproduce this? Getting a sense of the step by step path that led here will be important to try and plug the leak.

**Comment by j-sayers** [comment]
Unfortunately this is not easily reproducible. It is one of a couple similar errors that arose after the change to the new Manage page format. Something similar happens with stations and projects, but not consistently to see a pattern. With this entire section possibly seeing some updates soon maybe we should park it for now.
