### ISSUE TITLE
Cannot register SensorStation V3

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1223]
It appears that trying to register a SensorStation fails on live, but not on Sandbox. In particular, we've only heard reports of it failing with serial numbers that have a leading 'V'. The regex string appears to be accurate on live and it's identical to sandbox, so it must be something else going on.

I tried registering "CTT-V30B0154DD1F" on live and got the error: 
![image](https://user-images.githubusercontent.com/35931796/178035044-2ca4442a-395c-42b4-8eee-d53ba10f4e7f.png)
I then tried registering the same serno on Sandbox and it worked:
https://sandbox.motus.org/data/project/receivers?projectID=0

This is labeled as priority since collaborators are unable to register their station deployments until this issue gets fixed.

**Comment by denislepage** [comment]
Have you tried refreshing the cache from the admin tools?

**Comment by leberrigan** [comment]
That was it
