### ISSUE TITLE
Flagged detections not filtered from public site

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1224]
We have the concept of manually flagging runs that are thought to be suspect (aliasing, noise event) by setting motusFilter to 0. This in turn is supposed to filter out the detections on the public site while leaving them in the R data along with that value.

We haven't been using this all that much though until recently, and it's become clear it's not working expected. One station that had many of its tags flagged a few months ago is this one: https://motus.org/data/receiverDeployment?id=7742. All the flagged tags are still there. 

In the last week or so I've entered several other batches of false detections into det_manual_runs_filter and after each set it turns out some pairs were already in the table despite being visible on the site.

Catherine can provide more context when she's back. This was noticed just prior to her leaving on vacation.

What I didn't think about checking until now (too late for the moment) is whether any of the false detections that have been reported but that weren't already in det_manual_runs_filter did nonetheless have motusFilter already set to 0 due to being a short run in a noisy period.

**Comment by cjardine-bsc** [comment]
Most of those (249.5k) are CTT tags. Those only get filtered out if they have run length of 1. so that's expected. 

As for CTT-C295760116D9 there is a discrepancy between the hourbin calculation from pulse counts and the one I was getting from the tsBegin of the run. I made a change that should prevent that issue from blocking the filter for short runs. I also am now re-running all the batches with lotek tags and short runs (from taghits_daily) through the updated proc to clean up any stragglers,

**Comment by j-sayers** [comment]
Interestingly there are more false detections now at this one https://motus.org/data/receiverDeployment?id=7742 -- 66 in the daily table, as opposed to 57 as it's been for the last few months. I don't know what ones are new but I'm assuming they are false as the PI flagged all detections previously as false, and there hasn't new data uploaded or any receiver rerun for the past few weeks

**Comment by cjardine-bsc** [comment]
That's a different receiver though right? I'm assuming the problem with that one is the manual flagging, which is a different issue I haven't had a chance to look at yet.

**Comment by denislepage** [comment]
At the moment, we are not relying on the CRC check for newer tags.

It's something we could consider adding, but we'd need to be able to separate tags for which this is available vs. not.

We could for instance tally a number of hits that have been validated and use this as a filter.

**Comment by j-sayers** [comment]
> That's a different receiver though right? I'm assuming the problem with that one is the manual flagging, which is a different issue I haven't had a chance to look at yet.

There were two categories I noticed where flagged false positives were being displayed where they shouldn't
- runs where the automated process should have set motusFilter to 0 and filter them out, but which were not already in manual_runs_filter
- tag/receiver pairs which I tried to add to manual_runs_filter after seeing them on the website, only to find they were already there. The station mentioned above was one of those.

These were all Nanotags. I really haven't been noticing much of this lately with CTT tags myself.

**Comment by cjardine-bsc** [comment]
okay. CRC isn't relevant to what Josh is talking about. Cool. 

For Josh:


    runs where the automated process should have set motusFilter to 0 and filter them out, but which were not already in manual_runs_filter
    
    Due to run length right? This should be addressed. 
    
    tag/receiver pairs which I tried to add to manual_runs_filter after seeing them on the website, only to find they were already there. The station mentioned above was one of those.

Yes, I'll get to investigating this one soon, I've only been back for a day :-)

**Comment by j-sayers** [comment]
> runs where the automated process should have set motusFilter to 0 and filter them out, but which were not already in manual_runs_filter
> 
> Due to run length right? This should be addressed. 

Yes these were records from tag_hits_daily with n_hits < 4 (not run length specifically, but pretty close). And in the runs table they did already have motusFilter set to 0 (some were NULL). 

> 
> tag/receiver pairs which I tried to add to manual_runs_filter after seeing them on the website, only to find they were already there. The station mentioned above was one of those.
> ```
> 
> Yes, I'll get to investigating this one soon, I've only been back for a day :-)

Welcome back!

**Comment by denislepage** [comment]
It’s only relevant if we’re seeing too many false detections with runs of 2 for CTT tags, which I thought perhaps this is what he was reporting.

It’d less likely to get 2 consecutive hits of the same tag ID if they are false (that in itself is a kind of redundant check), but there may be certain patterns that are more likely to generate false hits with older tags. If using run > 1 is sufficient for CTT, we don’t need to dig deeper on my suggestions for now.
