### ISSUE TITLE
Station missing detections - also has many false positives with same BI

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1225]
First off, I think data from this station since the beginning of June should be reprocessed. Details are below:

Beaubassin station is located adjacent to two tag deployment sites for American Robins, Bank Swallows, and Nelson's Sparrows. 

However, [the deployment plot](https://motus.org/data/receiver/deployment/plot/SG%2D4001BBBK1560-2022%20MotusATL%2C%20Beaubassin.png?id=8699&n=100&firstTag=0) shows only one bank swallow, our test tag, and MANY false positives.

Two adjacent (within 2km) omni stations ([Fort Beausejour](https://motus.org/data/receiver/deployment/plot/SG%2D1614BBBK1910-2022%20Fensore%5FUNB%2C%20Fort%20Beausejour.png?id=8667&n=100&firstTag=0) and [Beaubassin Northeast Wetland](https://motus.org/data/receiver/deployment/plot/SG%2DFEEFRPI33E91-2022%20Fensore%5FUNB%2C%20Beaubassin%20Northeast%20Wetland.png?id=8659&n=100&firstTag=0)) have picked up Bank Swallows and American Robins - manual tracking has picked up NESP tags. 

Last year this station picked up lots of BANS from the same tagging site.

Metadata for these tags were entered as tags were deployed - some a week or two before more recent data has been uploaded.

Curiously, the false detections all have the same burst rate which match the Nelson's Sparrow tags, but the don't share Lotek IDs. I suspect this is a metadata problem, but I don't really understand how since they had their deployment dates entered already.

**Comment by leberrigan** [comment]
The deployment plot hasn't changed since reprocessing - any thoughts?

**Comment by leberrigan** [comment]
It's been a couple weeks without any changes - @Hussell are you able to take a closer look? Is there some information I could provide that would help?

**Comment by Hussell** [comment]
I hit several dead ends while investigating this, so I started over from the beginning just now. It turns out I did not, in fact, rerun the most recent data earlier, but data from 2021. Rerunning 2022 now...

**Comment by Hussell** [comment]
That did it. My apologies for the dumb mistake which led to the delay.

**Comment by leberrigan** [comment]
No worries!  Thanks
