### ISSUE TITLE
Station Deployment 8809 Missing Data

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1227]
Manual upload of CTT SensorStation data has resulted in 0 detections when there are definitely real tag detections at this site. Specifically, tag `motusTagID 57951` was detected there on `2022-06-08`, but nothing appears in our data.

I suspect this is an issue with manual uploads of CTT data - the SG data from the same station was processed without a hitch.

**Comment by denislepage** [comment]
I would need the station serial number.

**Comment by leberrigan** [comment]
Ugh, sorry: CTT-DEB0AE9543E6

**Comment by denislepage** [comment]
The data now seems to be in the database following CTT's recent connection of the manual upload pipeline at their end (processed on our end around 15-16 Nov. with a bunch of other data). About 3900 hits on that day for the tag 57951.

batchID: 8397335
runID's: 427442467 (L2) 427442464 (L1) 427442465 (L4) 427442466 (L5) 427442468 (L3)

I might be good to spot check a few more and once we feel that we seem to have most of the data, we should start first reaching out to impacted users who have been asking for this, and then once they confirm positively, announcing to everyone.
