### ISSUE TITLE
Project 380 Missing data (please reprocess)

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1238]
**[This tag test deployment](https://motus.org/data/tag/deployment/edit?projectID=408&id=41351)** was used at the following stations where it should have detections:

Serno | DeployID | Station Name
 -- | -- | -- 
SG-4812BB000230 | 8775 | La Coupe
SG-1012BB012090 | 8684 | Amherst Point Migratory Bird Sanctuary
SG-4812BB000025 | 8737 | Missaguash

**Comment by Hussell** [comment]
Done, finally. Test tag detected on all three receivers.
