### ISSUE TITLE
field maintenance required for SG-5113BBBK2799 (Port Maitland)

### ISSUE THREAD

**Issue by jbrzusto** [MotusDev/Motus-TO-DO#124]
On the next visit:
- download data 
- reimage the SG 
- reboot and apply the software update from [here](http://public.sensorgnome.org/motus/update_for_SG-5113BBBK2799_set_bootcount_to_3000.tar.bz2) which will set the bootcount to 3000

Before submitting data for reprocessing, files with "000NaN' boot counts will need to be renamed.  Assuming you have these files in a folder called "SG-5113BBBK2799" whose contents are one folder per day, here is an R script to do this:
```R
x = dir("SG-5113BBBK2799", recursive=TRUE, full.names=TRUE)
### get max existing real boot count + 1
mbn = max(as.integer(substring(basename(x), 21, 26)), na.rm=TRUE) + 1
### work only with files having bad boot counts
x = grep("-000NaN-", x, val=TRUE)
### look for any new reboots (marked by having the '.txt' version of a file, not just the '.txt.gz' version)
### note that '.txt' comes before '.txt.gz', and we only want to increase boot counts of files
### *after* both of these, hence the `FALSE, FALSE` and head(..., -2)`
rb = cumsum(c(FALSE, FALSE, head(grepl("-000NaN-.*\\.txt$", x), -2)))
### replace all bogus boot counts with new number, taking into account reboots
bn = basename(x)
substring(bn, 21, 26) = sprintf("%06d", mbn + rb)
new = file.path(dirname(x), bn)
### rename files
file.rename(x, new)
```

Note: in initially correcting this, I messed up boot counts, but when data get replayed to the new
server, that will be fixed.

**Comment by StuMackenzie** [comment]
Thanks, we'll try and do this on the next visit, but probably won't be until spring. It's not an easy site to get to. A note has also been logged in the Motus database - https://motus.org/data/receiver/deployment/edit?projectID=1&id=3956
