### ISSUE TITLE
We are not receiving ctt data for any Version 3 SensorStations

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1241]
We were contacted recently by a couple projects who don't have a single detection of the LifeTags they are deploying next to some of their stations, even though the stations are up to date on the website and the tags are detected on other stations.

Turns out we don't have a single ctt batch present in the database for any of 30 Version 3 SensorStations that have so far sent data. Data transfers are working fine otherwise (we have up to date sg batches for many of them). And we have up to date ctt batches for older SS.

According to CTT the data processing is up to date in the bucket for these files on their end, and they've been able to confirm detections for some of the "missing" tags.

It's possible there has been a change in the file name format that is preventing our import process from recognizing them. We've already updated the regex for the change in serial number format, though maybe the import process is checking against something else. Or maybe it's something else entirely. 

FWIW here's one of the data file names CTT-V30B0154CD0C-raw-data.2022-08-15_095039.csv.gz (there are separately files for GPS and logs, which we apparently aren't receiving either).

**Comment by denislepage** [comment]
The backlog is now processing. It could take a day or two to get back on track, and this will also delay other scheduled threads.

**Comment by denislepage** [comment]
Not sure when, but it looks like the import of the backlogged V3 data completed at some point this weekend. Looks like we’re entirely caught up now on all pending data imports, in both databases.

@cjardine-bsc , I suspect you did not deprecate the CTT station in sandbox. That would explain why sandbox has about half a billion more records than live (10.25 vs. 9.8 billion).

I'm going to close.

**Comment by cjardine-bsc** [comment]
correct, I only deprecated the CTT receiver from live. Just in case :-)
