### ISSUE TITLE
No receiver deployment found for IDs in Data Issues

### ISSUE THREAD

**Issue by eageldart** [MotusDev/Motus-TO-DO#1243]
When I click 'View | Edit' for any of the "Station Location or Selected Receiver Incorrect" errors or "GPS Fixes Far from Station Location" warnings in Project 2, I get the error "No receiver deployment found for ID = ####" (picture example attached). 

![image](https://user-images.githubusercontent.com/94930170/186200955-7d3b7707-ebf9-4456-bd0e-5b4cff73a084.png)

I also cant find these recvDeployIDs in my receiver-deployments table for this project

https://motus.org/data/issues?id=2

**Comment by cjardine-bsc** [comment]
ah, its giving you the station_id, not the deployment_id. I shall switch them. 

Try now (you'll have to re-run the validations).

**Comment by eageldart** [comment]
Its behaving properly now. Thank you! Closing this issue.

**Comment by eageldart** [comment]
I have reopened this issue as it is occurring still for all projects aside from just Project 2.

**Comment by cjardine-bsc** [comment]
Even after you re-run the validations for those projects? 

Re-running the validations on the issue page only does the current project. I just re-ran all projects, let me know if it still seems to be an issue.

**Comment by eageldart** [comment]
Oups! I'm silly. All is good. Closing again.

**Comment by cjardine-bsc** [comment]
No worries. I'm silly too, I should have re-run all the projects after fixing yesterday
