### ISSUE TITLE
Move tags to another project

### ISSUE THREAD

**Issue by adamdsmith** [MotusDev/Motus-TO-DO#1251]
Hey @cjardine-bsc, Stu suggested I submit a tag transfer request via Github and tag you.

I'm requesting the following 15 tags be moved from Project 358 (Black Rail) to Project 537 (Coweeta LTER) belonging to Richard Chandler ([carellinacanadensis@gmail.com](mailto:carellinacanadensis@gmail.com)). This represents all the undeployed tags from Project 358.

Thanks!

| MotusTagID | MfgID |
| ------------- | ------- |
|59719 | 1E523307|
|59720 | 614C7819|
|59721 | 4B07522D| 
|59722 | 194B4C33|
|59723 | 662A7852|
|59725 | 19523466|
|59731 | 2A2D0766| 
|59733 | 4C1E2D61|
|59734 | 1E66784C|
|60178 | 52782A19|
|60179 | 2D4B2A66| 
|60181 | 191E6166|
|60182 | 334C4C19|
|60194 | 5534074B|
|60200 | 334C0755|

**Comment by cjardine-bsc** [comment]
Done
