### ISSUE TITLE
Exclude some Tag Models from receiving a 'Tag Never Deployed' Critical Error

### ISSUE THREAD

**Issue by eageldart** [MotusDev/Motus-TO-DO#1253]
I am thinking that since some of our tags models (Lotek Nanotag Solar, CTT LifeTags and HybridTags) have unlimited lifespans, they should not trigger a 'Tag Never Deployed' Critical Error in the Notification Center. 

Here is an example where CTT LifeTags trigger such an error: https://motus.org/data/issues?id=59#v_tag_not_deployed_released 

This gives off the impression that these tags have been deprecated by us so that the tag properties can be made available to others, whereas this is not the case, correct? Also, we won't want these tags to trigger a Critical Error or Error when we implement the Metadata Strongarm since they may unnecessarily block users from accessing their data. 

Instead, a Warning or Note similar to 'Tag Not Deployed' might be more appropriate for these tags. 

What do we think?

**Comment by cjardine-bsc** [comment]
Good call! We didn't have lifetags back when this script was built, I've removed any tags that have battery type of SOLAR from that error. I tested project_id 59 and it looks good. 

we should confirm that they tags still show in the "tag not deployed" list

**Comment by eageldart** [comment]
I checked to make sure these tags were still showing in the "tag not deployed" list and I do not believe they are:

Here are a couple examples:

Project 292: LifeTag 61525207 is from datebin 2019-3 but is not in the 'Tag Not Deployed' Warning list. 

Project 59: LifeTag 34333478 is from datebin 2020-2 but is not in either the 'Tag Not Deployed' Warning list.

**Comment by cjardine-bsc** [comment]
yup, that checks out. I made some changes, should be good now.
