### ISSUE TITLE
Rerun 3 receivers - project 78

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1257]
Please reprocess these receivers, thanks!
serno | deploymentID
 -- | -- 
[SG-2712BB000055](https://motus.org/data/project/receivers?projectID=78&setRecvId=1429) | 11083
[SG-14A9RPI3C3AC](https://motus.org/data/project/receivers?projectID=78&setRecvId=3221) | 12159
[SG-3927RPI3E7AE](https://motus.org/data/project/receivers?projectID=78&setRecvId=3794) | 11561

**Reason**
Students are seeking their data asap for analysis, but we're getting loads of false positives on these stations rather than the real detections. Similar situation to Beaubassin earlier this year.

**Comment by Hussell** [comment]
The deployment IDs don't match. I'm assuming the receiver serial numbers are correct?

**Comment by Hussell** [comment]
Done. Lots and lots of new detections.
