### ISSUE TITLE
Add an instruction button to the manage receivers page

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#126]
Add a button to this page: https://motus.org/data/project/recvs?projectID=1

Beside "register new receiver" that says "Instructions" This should link here: https://motus.org/data/download/ReceiverMetadataInstructions.pdf

Zoe will also probably add a link to the text fragment for this page: https://motus.org/data/receiver/deployment/edit?projectID=1&id=681

**Comment by pmorrill** [comment]
The button is in place: beta5 and sandbox on next deployment.
