### ISSUE TITLE
No receivers shown in project summary 

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1261]
Project 463 has about [20 receivers,](https://motus.org/data/project/receivers?projectID=463) but there are no receivers showing up in the [project overview.]((https://motus.org/data/project?id=463))

![image](https://user-images.githubusercontent.com/55001144/193626182-f92a0dcf-f42f-41fe-b585-b4d1eaa4308c.png)

![image](https://user-images.githubusercontent.com/55001144/193626591-3f152bcf-a926-4fe9-b76f-b0aa1f43bf18.png)

![image](https://user-images.githubusercontent.com/55001144/193626445-22589b27-8023-485e-abff-b671c22f8ede.png)

I don't think I've seen this before. Usually the receivers summary leads to something like this page (https://motus.org/data/projectActiveReceiverDeployments?id=458) where you can sort receivers and receiver deployments based on the number of detections.

**Comment by cjardine-bsc** [comment]
Looking at the summary for other projects it says "active" receiver deployments. Project 463 has all its deployments terminated. I suspect this is a "feature" not a bug, and the projects pagewas designed only to show actively deployed recievers: 

i.e.: https://motus.org/data/projectActiveReceiverDeployments?id=463

**Comment by j-sayers** [comment]
Yes it does link to Active deployments doesn't it.

I never realized that the Receivers list in the Explore Projects page only listed _active_ receivers. 

I guess this is the first time I've tried to view the receivers for a project that did have at least _some_ active deployments!
