### ISSUE TITLE
Trigger a Tag Missing Band Number notification

### ISSUE THREAD

**Issue by eageldart** [MotusDev/Motus-TO-DO#1262]
Since Band Number is a **required** tag metadata field, I thought we might want to add '**Tag Missing Band Number**' or '**Invalid Band Number**' as an Error in the Notification Center. This should help collaborators when we enforce the Metadata strongarm.

However, this is only an issue for animals that get banded, so we might first have to address issue 1122:
https://github.com/MotusDev/Motus-TO-DO/issues/1122

**Comment by cjardine-bsc** [comment]
Sent you an email to get the instructions and details. I can add this error once we have that. 

For my reference: 

SELECT *
  FROM [motus].[dbo].[tags_deployments]
  where ISNULL(bird_band, 1) = 1 and band_number is null and dt_start is not null

**Comment by eageldart** [comment]
Catherine, I sent you back an updated instructions sheet.

**Comment by cjardine-bsc** [comment]
Okay, I made all the changes needed to the sandbox database to support that error. Its now ready once we implement #1122. 

Assigning @Hussell for now in lieu of a java programmer.

**Comment by eageldart** [comment]
I see that this Error notification is now live. Woohoo!

One recommendation to reduce overwhelm for users: Do not trigger this error for test tag deployments. 


![Tag Missing Band Number](https://user-images.githubusercontent.com/94930170/208465973-6256dad7-5feb-48ce-a948-b61bd301b43d.png)

**Comment by cjardine-bsc** [comment]
No problem, I made that change. I also changed it so that it will only trigger if there is a species populated.
