### ISSUE TITLE
Old data link to remove

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#127]
I think links to this type of .csv data can be removed: https://motus.org/data/project/detections?projectID=113&file=taghits_113_2016_1.csv?

Some users are apparently still accessing it this way, but I don't think there's a reason to keep it available as we move to .motus data through R

**Comment by Hussell** [comment]
Not everyone knows R, and many have a great deal of expertise in other software (SAS, SPSS, MATLAB, Excel, etc). We should continue to provide plain text files for anyone to examine their own data in bulk through whatever software they're familiar with. I see no reason _not_ to.

**Comment by zcrysler** [comment]
I agree that it's important to have it available as a .csv, and one of the first instructions we give in the RBook is how to convert the .motus files to .csv.  But are these files still being updated?  I can't see where to access them from the website without this direct link that a user sent me, the only detection data available for download from the download page is the .motus file.

I also thought that we were eventually removing the ability to download the .motus files directly from the website once we had everything working from R - maybe I misunderstood that.

**Comment by jbrzusto** [comment]
This is going to be an obsolete format, at least for distribution, 
because it just isn't up to the job without significantly more thought.
As just one issue, how will the .csv file distribution deal with replacement batches,
when a batch of raw receiver data has to be re-run due to bugs or previously missing files
having been obtained?

I think it would be an unnecessary burden for motus to manage different versions
of .csv files and quite possibly a bigger headache than just coaching users to work
with .motus files directly.  Users are always free to follow Zoe and Tara's
instructions for generating .csv files from .motus files, but then
at least it's clearly their responsibility to deal with managing versions.

**Comment by denislepage** [comment]
We plan to remove the static file approach as soon as we have the full R package process running properly. I think we are nearly there. 

I don't think the link to the CSV file is available anywhere from the web site, but we still offer (for now), the link to the static sqlite files. The link above should probably redirect to the project download page where the can find the sqlite file.

It is unclear whether we should support any format for detection data beyond what the R package will provide. Not everyone will want to use R for their analysis/needs, but that may be the only way by which they will be able to get their data for the foreseeable future.

When we tried to make the entire project data available as a single CSV streaming from the database, we ran into memory buffer issues that we never resolved.

I think that providing instructions for people on how to create a CSV file from the sqlite file will be sufficient for now.

**Comment by denislepage** [comment]
Task for Jeremy (or Paul): 

Redirect links to this page 
https://motus.org/data/project/detections?projectID=113

to:
https://motus.org/data?projectID=113

I have already removed the static csv files, so the downloads will no longer work.

**Comment by pmorrill** [comment]
I have removed the jsp template and set a redirect in the old servlet, as described. Move the redirect to the setup filter (if you have a mechanism in place to handle that), then we can remove the servlet as well.

**Comment by Hussell** [comment]
I searched for links to this page and found 3:
- https://beta.motus.org/data (Download Detection Data, https://beta.motus.org/data/project/detections?fmt=sqlite&projectID=10)
- https://beta.motus.org/data/downloads?projectID=10 (Tag Detections, link only present when logged in and authorized to view detections, https://beta.motus.org/data/project/detections?fmt=sqlite&projectID=10)
- https://beta.motus.org/data/project/tags?projectID=10 ("Download Detection Data" button, https://beta.motus.org/data/project/detections?projectID=10)

Only the third link is obsolete. So, I've:
- restored the DetectionsDataServlet from backup
- deleted the code related to the CSV downloads page without touching the SQLite file download code
- replaced the CSV downloads page with a redirect to /data?projectID=X (which wasn't working correctly anyway; Paul, you should test things before checking them in, and beware the low precedence of the ?: operator)
- changed the obsolete link to download the SQLite file instead

I think that takes care of this.

**Comment by pmorrill** [comment]
Yes - my misunderstanding of the servlet here. Mistakes will be made. But no need to be patronizing: if you really feel that I don't test things before I check them in, then you should just go to Denis and discuss replacing me on the project. I'm fine with that and tired of splitting my time between my own projects and Motus, anyway.
