### ISSUE TITLE
antenna numbering is confusing

### ISSUE THREAD

**Issue by tve** [MotusDev/Motus-TO-DO#1277]
Station "SBA san marcos pass" has radios on ports 5, 6, 7 and the antennas are labeled 1, 2, 3 in the receiver deployment info:
![image](https://user-images.githubusercontent.com/39480/195888765-aaae06d6-4186-468b-b790-b7847e8bcc1b.png)
But in the deployment timeline the antennas are labeled 3, 4, 5:
![image](https://user-images.githubusercontent.com/39480/195888910-cf38210f-054a-4c4b-9224-be6fa5c82037.png)
And in the API (/api/receivers/sensordeployments) there are no antenna numbers, only ports:
```
{"port":"5","antennaType":"yagi-9-maple","bearing":345.09924,"heightMeters":5.5,"cableLengthMeters":7.5,"cableType":"LMR400","polarization2":90.0}
```
If antennas have a numbering, it would be good to show that in the form:
![image](https://user-images.githubusercontent.com/39480/195892613-5a512051-1174-466a-b755-da97e501e10b.png)

**Comment by Hussell** [comment]
The headings on the receiver deployment page are just numbered from 1 to n, where n is the number of antennas. That could be changed, though it would have to deal with missing port numbers, odd port "numbers", etc.

The metadata for the receiver has the antennas as being in ports 5, 6, and 7, but looking in the files the receiver is mostly reporting hits from port 5 but occasionally port 3 (and presumably port 4, though I didn't find an example). So the metadata might not match physical reality in this case.

**Comment by Hussell** [comment]
https://beta.motus.org/data/receiverDeployment?id=9094

**Comment by tve** [comment]
Nice change!

> The metadata for the receiver has the antennas as being in ports 5, 6, and 7, but looking in the files, the receiver is mostly reporting hits from port 5 but occasionally port 3 (and presumably port 4, though I didn't find an example). So the metadata might not match physical reality in this case.

Whoops! I'm glad you caught this. I went back and looked. File sg_wcc-7F5ERPI46977-028-2022-10-13T20-43-13.8280Z-ctt.txt.gz is a good example as it has (test tag) detections from both of the CTT radios:
```
...
T6,1665697286.864,78664C33,-67
T7,1665697286.914,78664C33,-80
T7,1665697291.952,78664C33,-80
T6,1665697292.083,78664C33,-67
T6,1665697297.118,78664C33,-67
...
```
This file was processed in job 20624695 on 2022-10-13 20:43:21. The "T6" and "T7" match the antenna definitions in the deployment. But it produced some of the "activity" on "antenna 3" and "antenna 4" in the plot in the very first post here. Also odd is that this file clearly shows concurrent detections of the same tag (which is expected) but the plot in the first post doesn't have any detection overlap between antennas 3 & 4. Something is wrong either in that plot or in the processing before the plot gets generated...

**Comment by Hussell** [comment]
Files ending in -ctt.txt.gz are sent to CTT for processing. [The plot above](https://motus.org/data/receiver/deployment/plot?id=9094) summarizes results from the Motus tag finder and thus doesn't show anything from that file. The files lacking "ctt.", contain the data summarized on that plot.

**Comment by tve** [comment]
OK... Would be nice for Motus to treat the CTT tags on equal footing...

But that plot is still very strange. It continues to show activity on Antenna 3. The data uploaded has "P5" and "T6" lines, i.e., lotek pulses on port 5 and CTT tags on port 6. Nothing else. What is the activity on antenna 3 then?

**Comment by Hussell** [comment]
As I mentioned above, I did find some "p3" lines during a quick search, though they're quite sparse. So the plot really is showing what's in the files. Presumably there's a "p4" line somewhere too, though I haven't found it.

These plots are specifically summaries of the results of uploads to the Motus tag-finder. They're linked in the emails people get in response to manual uploads. That's why they don't have CTT tags in them. There are similar plots elsewhere which show all tags, though nothing with this exact design.

**Comment by tve** [comment]
I took a look at the files, I have a second funcube on port 3 that is not connected (awaiting antenna mount) and evidently produces a couple of pulse detections per day from noise. So that explains antenna 3. I'm not seeing any 'p4' in the files but those detections happened the day I deployed the SG, so it's possible they happened before everything was properly configured and I may have reflashed the image. Thanks for checking!

**Comment by tve** [comment]
> There are similar plots elsewhere which show all tags, though nothing with this exact design.

Would you mind pointing one out to me? Or am I not seeing any CTT tag detections anywhere because CTT is not sending anything to Motus lately?

**Comment by Hussell** [comment]
The latter.

**Comment by cjardine-bsc** [comment]
@Hussell and @tve Are we okay to close this one?
