### ISSUE TITLE
Wrong StationId returned from dashboard/antPulseDaily and dashboard/gpsDaily

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1279]
For example, when I request data for station 12750, I get returned stationId=11312!
https://motus.b-cdn.net/data/dashboard/count/gpsDaily.json?stationId=12750
https://motus.b-cdn.net/data/dashboard/count/antPulseDaily.json?stationId=12750

**Comment by denislepage** [comment]
This is an issue with the CDN caching, which as I noted earlier, seems to ignore the parameters.

Those ones are returning the expected data.

https://motus.org/data/dashboard/count/gpsDaily.json?stationId=12750
https://motus.org/data/dashboard/count/antPulseDaily.json?stationId=12750

Seems odd that Bunny is not using URL parameters for caching.

**Comment by denislepage** [comment]
Ah, I found a setting in Bunny that enables something called Vary Cache, which relies on the parameters. There are more options with Vary Cache (e.g. caching mobile and desktop separately), but this should do it.

**Comment by leberrigan** [comment]
Yup - looks good, thanks!
