### ISSUE TITLE
Missing statprov_code in dbo.tags_deployments

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1280]
All entries in `dbo.tags_deployments` have `statprov_code` set to null. Were we waiting to populate this for some reason?

I would like these data to populate region summaries in the dashboard. Currently, only stations have region codes.

**Comment by cjardine-bsc** [comment]
Don't think there was any reason. Just never did it. 

Added to trigger live and sandbox and populated in live.
