### ISSUE TITLE
Allow landowners to 'opt out' of their names being listed on our Motus Partners and Collaborators Page

### ISSUE THREAD

**Issue by eageldart** [MotusDev/Motus-TO-DO#1286]
Create an 'opt out' checkbox for Landowner names to show up on out Motus Partners and Collaborators page https://motus.org/data/partners 

This checkbox would be used when the user uses the 'Modify this landowner' tool on the Manage Landowner page https://motus.org/data/project/landowners?

**Comment by denislepage** [comment]
OK, done. Ready to test in beta. I confirmed that the name is being removed from the partners page. Keep in mind that the same name may appear under multiple projects, so hiding in one project may not be enough. Myles Falconer is listed under project 0 and 1 for instance. Those are distinct entries, so the checkbox must be applied in both places.

![image](https://user-images.githubusercontent.com/21110542/198477429-b7c09581-0e07-4988-a0dc-e5caa0187587.png)

I realized after I implemented this that Catherine had already set a field called "acknowledge" in the projects_landowners table, which was never implemented. I rather used a field already in user_id called "ghost_user". I'm inclined to remove the acknowledge field from the other table, but that can wait until @cjardine-bsc  is back.

**Comment by eageldart** [comment]
It worked for me as well! 

The only thing is that the Text Fragment reads " Text fragment not found in database: (EN) Hide_landowner" instead of what you have written in your last post "Hide the name of this landowner..."

**Comment by cjardine-bsc** [comment]
Thanks Erica, you'll just need to add that fragment to sandbox. Do you know how? Lucas or Josh can probably give you a quick walk through.

**Comment by eageldart** [comment]
I just checked and someone has added the fragment already. The checkbox is now live. Closing issue
