### ISSUE TITLE
Remove 'Missing Landowner Information' Warning on Notification Center

### ISSUE THREAD

**Issue by eageldart** [MotusDev/Motus-TO-DO#1287]
In todays meeting, the consensus was to remove the Warning 'missing landowner information' from the Data issues Notification center e.g. https://motus.org/data/issues?id=0#v_no_landowner

This came up because several landowners do not want their name to be public on our website. To fix this, we plan to address issue #1286 so that they can 'opt out' of having their name shared to the public. 

But ultimately, landowner information is only important to people involved in each project right now (for record keeping) so does not necessitate a Warning. In the future if we implement Outreach to Landowners, we might want to bring this back.

**Comment by denislepage** [comment]
Done. Commented out the rule, and remove existing warnings from both databases.

**Comment by eageldart** [comment]
I am not sure if this needs to be done seperately from what youve done, but 'Missing Landowner Information' is still listed in the Receiver Issue Type table

See https://motus.org/data/issues?id=234 

I have refreshed and rerun data validation

**Comment by denislepage** [comment]
The link you shared shows a count of 0 for that error. It took me a few minutes to realize that this is what was happening. I'm wondering if we should simply exclude errors that have a count of zero, or perhaps make them more obvious that they are not applicable.

Is there a value in showing the things we are testing for if they are not applicable to the project?

**Comment by cjardine-bsc** [comment]
This whole page needs a reconsideration from a function standpoint. I'm going to close this one for now because everything is working but this is a good question to consider as the team thinks about the ideal format for this page.
