### ISSUE TITLE
sample data runs_for_tag_project

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#129]
When I used (by accident) the motus.sample user for requesting data for project 15, I received a server error:

https://sandbox.motus.org/api/sgdata/custom/runs_for_tag_project
json={authToken=xxx, runID=0, batchID=68902, projectID=15}

SQL = SELECT top (10000) * FROM Sample_R_Runs_for_receiver WHERE runID > ? AND batchID = ?  ORDER BY runID
Description = API Context prepared statement (Made it to result set wrapper)
Stack trace:
com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'Sample_R_Runs_for_receiver'.

IThe authToken is the one expected for the motus.sample user authentication.  Weird because I am trying to access runs_for_tag_project, not runs_for_receivers. It think the issue is simply the table name being queried? 

This is also not working:
https://sandbox.motus.org/api/sgdata/custom/batches_for_tag_project
{authToken=xxxx, batchID=0, projectID=15}

The latter is slightly more problematic, as people are not likely to make the same mistake of not resetting their authentication after accessing the sample data.  This should ideally not throw a database error and preferably return an authentication error, similar to when you try to load a project for which you don't have permission. When I call tagme(160) with the sample credentials, I currently get a server error as the response.

**Comment by pmorrill** [comment]
Interesting. I thought that I'd cleared this sort of error (using the sample account on non-sample project ids.) I'll take a look.,

**Comment by pmorrill** [comment]
I am just about to check in a slight over-haul of how the required parameters are checked, to 
catch errors and return 'access denied' instead of generic server errors.



> 
> When I used (by accident) the motus.sample user for requesting data for project 15, I received a 
> server error:
> https://sandbox.motus.org/api/sgdata/custom/runs_for_tag_project
> json={authToken=xxx, runID=0, batchID=68902, projectID=15}
> SQL = SELECT top (10000) * FROM Sample_R_Runs_for_receiver WHERE runID > ? AND 
> batchID = ? ORDER BY runID
> Description = API Context prepared statement (Made it to result set wrapper)
> Stack trace:
> com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 
> 'Sample_R_Runs_for_receiver'.
> IThe authToken is the one expected for the motus.sample user authentication. Weird because I 
> am trying to access runs_for_tag_project, not runs_for_receivers. It think the issue is simply the 
> table name being queried?
> This is also not working:
> https://sandbox.motus.org/api/sgdata/custom/batches_for_tag_project
> {authToken=xxxx, batchID=0, projectID=15}
> The latter is slightly more problematic, as people are not likely to make the same mistake of not 
> resetting their authentication after accessing the sample data. This should ideally not throw a 
> database error and preferably return an authentication error, similar to when you try to load a 
> project for which you don't have permission. When I call tagme(160) with the sample credentials, 
> I currently get a server error as the response.
> -
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or mute the thread.

---
Paul Morrill
paul@ravenforge.ca
(613) 273-7375
