### ISSUE TITLE
CTT Hybrid Tag Lifespan

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#1297]
Need to confirm that CTT Hybrid Tag lifespans are being treated the same as life tags. Unlimited or loooong life.

From a collaborator:

Interesting Motus question from Laura Cook:
"When I look at tag registration or deployment on the Motus site there is Tag Lifespan information. Part of that is Buffered Expiration date and Buffered Life Span Remaining. I am concerned about this because for one of the new Hybrid LIfeTags that I just deployed it says expiration date is 14Dec2023 and that "This is the date when Motus will stop searching for this tag". For our old LifeTags, it seems the expiration date isn't until 2025. Is there a way to expand these expiration dates? Fidelity is an important component to our study and why I love the LifeTags."

**Comment by denislepage** [comment]
I changed the function so it uses 5 years by default for hybrid tags (same as lifetags). That doesn’t solve the issue with powertags, but I don’t think we have the information we need yet. Worst case, we can also set a default lifespan for powertags based on the same period for now.

Unlike lotek tags, there is little consequence to extend the lifespan of a CTT tags, as we are currently not filtering anything (yet anyway) based on deployment dates or lifespan.

**Comment by cjardine-bsc** [comment]
The function shouldn't need to change I don't think. If you update the battery_model field in lk_tags_modles to SOLAR they should be treated the same way as life tags (default 4 years I believe). 

Both approaches solve the issue, but for consistency I think I'll change the battery type unless there are any objections.

**Comment by cjardine-bsc** [comment]
Ah, I dug further and the function in live did indeed need to change, but I've altered it to use the batter model field.
