### ISSUE TITLE
column_name_unknown error prevents changes to receiver deployments

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1299]
Multiple projects have been reporting a "column name unknown" error when trying to save or modify receiver deployments. Seems to be related to dongle types (at least the number of times the error is shown corresponds to the number of dongles).

**Comment by eageldart** [comment]
This seems to be related to issue #1295

**Comment by denislepage** [comment]
This is now fixed. As far as I can tell, all data was being saved anyway, and I changed the code so the error no longer appears. I deployed on beta and live, including any recent changes to the dashboard.
