### ISSUE TITLE
French species names

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#130]
French species names are only available for birds, are there plans to get French names for bats/insects?

**Comment by denislepage** [comment]
They are available for a few of them, but not many.

Not sure of a good source to use. I just downloaded NHIC species lists, and was able to add a number of French names for a few groups.

I’d like to get my hands on an electronic copy of this for mammals.  Not sure it exists.
https://www.amazon.fr/Mammif%C3%A8res-monde-Inventaire-scientifiques-fran%C3%A7ais/dp/2951909403

I suspect most bugs don’t have French names. The priority would be butterflies and odonates. Those are more likely to exist for North America and Europe, at least. But even if they do exist, the scientific name is the most important to present.

Denis

**Comment by cjardine-bsc** [comment]
I recently updated lk_species in dendroica with some french names for bats from the translation that we did of the wind energy report. So all Canadian species have French names. 

I'll sync that to Motus now. Having the Canadian species is probably the biggest priority.
