### ISSUE TITLE
Configuring WPForms to send emails

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1302]
I'm working on a couple of forms and it doesn't seem like I can get the mail delivery to work. It's likely that WP is not configured to use the PHP mail function. Another plugin, WP Mail STMP, gives other options, but all are paid services unless use our own STMP server. The only problem is that I can't access that info for my email account.

**Comment by denislepage** [comment]
We have access to an SMTP server managed by kwic. I can look to set up SMTP mail. I'm surprised it's not already.

**Comment by denislepage** [comment]
I set up the SMTP and tried a WP form submission.

**Comment by leberrigan** [comment]
Looks good!
