### ISSUE TITLE
No hits or runs for SRX receivers with active tags near them

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#1310]
Project 145 recently noticed that they did not have a single detection for their tags on their own receivers, despite many detections on other receivers.

The stations appeared to be functioning fine, including consistent antenna activity throughout the period. See [this one](https://motus.org/data/receiverDeployment?id=9101):

![image](https://user-images.githubusercontent.com/55001144/207633785-d055d05f-81c4-4fc8-a9e3-5359e6df8de6.png)

It's cropped out here, but the single antenna is `-1`.

Digging in a bit here, it looked like **there wasn't a single hit or or run** for these stations in this season. ~~Yet there were pulseCounts in many cases, nearly always just on port `-1`, though sometimes on port `0`~~ [Antenna `-1` is the result of the receiver being set to scan on all ports, rather than distinct ports and is nothing new.]

They sent over a sample raw data file for this receiver and there are clearly hits, though each line has all four antennas represented. The project says they've been recording this way for years, but I'm not sure if it's always been represented this way in the data. 

![image](https://user-images.githubusercontent.com/55001144/207632854-f2292d62-944b-42b2-9134-20f8b4a5eaf6.png)

**Comment by Hussell** [comment]
Bug found and fixed. Rerunning all Lotek receivers in project 145 now, then all other Lotek receivers.

**Comment by StuMackenzie** [comment]
What was the bug?

____________________

On Jan 19, 2023, at 10:04, Jeremy Hussell ***@***.***> wrote:

﻿

Bug found and fixed. Rerunning all Lotek receivers in project 145 now, then all other Lotek receivers.

**Comment by j-sayers** [comment]
Project 277 is the other project who recently noticed this.

**Comment by cjardine-bsc** [comment]
Nice solve J-Dawg!

**Comment by Hussell** [comment]
Thanks. $1 for changing 1 line and recompiling. $99 dollars for figuring out which line out of a hundred thousand needed to be changed. Thank you to Josh for collecting examples of affected receiver files, I wouldn't have been able to figure this out without his persistence.

**Comment by Hussell** [comment]
Reruns are complete.
