### ISSUE TITLE
404 error motus user guide

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#1314]
On: https://docs.motus.org/en/tags/tag-deployment

![image](https://user-images.githubusercontent.com/22172758/210814050-88639fb1-052f-4eed-8595-6d335b30eff8.png)

How to tag animals takes you to: 
https://docs.motus.org/tagguide/tag-deployment#how-to-tag-animals

Which returns a 404.

**Comment by leberrigan** [comment]
Thanks. Fixed.
