### ISSUE TITLE
Missing test tag deployments from dashboard API

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1315]
Currently the `/data/dashboard/tagDeployments` entry point does not include test tag deploymetns. These are required for the reporting tool as part of the offshore wind project deliverables. I would like to have a list of test tags and the associated metadata (deployment location, start/end dates, notes) to display in the report. 

There is also no way to associate test tag deployments with their tag metadata, like mfgID.

**Comment by cjardine-bsc** [comment]
Sure. I've taken out the code that removes the test tags from Sandbox. We excluded the test deployments from that view at your request (though I don't recall the reasons), so you may need to filter them out where you didn't want them. Let me know when I'm good to move that over to live. 

Test tag deployments should be associated with tag metadata via tag_id.

**Comment by leberrigan** [comment]
Thanks! Should be good to push to live.

**Comment by cjardine-bsc** [comment]
https://tenor.com/en-CA/view/frankenstein-its-alive-happy-excited-gif-5625959
