### ISSUE TITLE
Add three more variables to `antennaDeployments` API entry point

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#1316]
The dashboard entry point `antennaDeployments` requires three more variables for the reporting tool:
- dongleType
- cableType
- cableLength

**Comment by cjardine-bsc** [comment]
You betcha. All done in sandbox.

**Comment by leberrigan** [comment]
Looks good on Sandbox, thanks. Can you push to live?

**Comment by cjardine-bsc** [comment]
I can and I will and I did.
