### ISSUE TITLE
Missing GPS Data from CTT Sensorstation

### ISSUE THREAD

**Issue by eageldart** [MotusDev/Motus-TO-DO#1319]
GPS fixes are missing for a Sensorstation in Project 443 for long periods and this is evident in both the receiver timeline and deployment timeline:
https://motus.org/data/receiver/deployment/plot/CTT-25E960526809-2021%20Nashville[…]%20Nashville%20Zoo%20at%20Grassmere.png?id=8094&n=100&firstTag=0

https://motus.org/data/receiver/timeline?year=2023&id=4600

We wondered if it was the case that this was caused by a bug triggered when reprocessing the data. To confirm, we checked the raw data .txt files (from sgdata), and from the few I checked, the GPS hits are missing and showing up when the tables above highlight: 
https://sgdata.motus.org/status?serno=CTT-25E960526809

So it looks like it might be an issue with the receiver itself. 

Denis, are you able to diagnose this issue?

**Comment by denislepage** [comment]
Here’s what I found. There was a batch of data uploaded on Jan 1st, covering the period from around Dec. 21st to 31st.

On the CTT side, there were only few hits for that period, but at least some. The GPS files for the periods that are showing as blank are present, and a new file generated roughly hourly, but they contain no useful data.

E.g.

recorded at,gps at,latitude,longitude,altitude,quality,mean lat,mean lng,n fixes
2022-12-23 00:01:34,,,,,
2022-12-23 00:16:35,,,,,
2022-12-23 00:31:36,,,,,
2022-12-23 00:46:36,,,,,

On the SG side, same as you found, also based on a small sample. It’s harder to know without reopening every hourly file, but there doesn’t seem to be GPS records in the blank periods. At those times, I am also mostly seeing pulses come on port #2 and not others.  That could just have been a coincidence.

Unless there was a problem on the CTT processing server side, the more likely scenario is a faulty GPS or receiver.

I hope this helps.
