### ISSUE TITLE
Missing text fragment: Latest_detection_data_batch

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#132]
See https://sandbox.motus.org/data/receivers/edit?projectID=31&id=2161

I've created this text fragment in both the sandbox and the live database. Paul, let me know when you've added the English text (you know best what should be there), and I'll get it translated.

**Comment by pmorrill** [comment]
I have put something in place, but I am not convinced the wording is correct. 

https://sandbox.motus.org/data/receivers/edit?projectID=31&id=2161

**Comment by Hussell** [comment]
Maybe "Detection data from this receiver has been received and processed up to"? Slightly clearer that it's the last date at which data was collected, rather than the last date a batch was submitted.

**Comment by cjardine-bsc** [comment]
Hi Gents, 

The phrase "Up to" suggests all the data has successfully been processed, which might give the wrong impression for some projects. Could we change this to: 

"The most recent detection data for this receiver is from: XXXXX" 

Is that an accurate reflection of the date you're pulling? (sorry I haven't been part of the discussions implementing this.) Presumably this will ultimately link to the receiver timeline?

Thanks all!

**Comment by cjardine-bsc** [comment]
Actually, ultimately this might link to a page displaying the status of various upload batches, but in the mean time linking it to the timeline might be useful.

**Comment by Hussell** [comment]
Text has been updated per Catherine's request, and translated.

**Comment by pmorrill** [comment]
It's slightly more difficult to explain this on the website.... But the actual datetime being reported is the ts_end field from sg_batches, for that receiver device. I'd like it to be clear of course. I will also be adding the similar datetime to a couple of other places, such in the deployments list tables. So we need a concise version as well, suitable to use as a table header.

**Comment by denislepage** [comment]
Blurb looks good in both languages. If the time is GMT, it would be worth specifying it explicitly.

Les données de détection les plus récentes pour ce récepteur proviennent de: 2017-07-14 09:50 UTC

**Comment by cjardine-bsc** [comment]
How about "Last Data Processed" for the short table blurb?
