### ISSUE TITLE
Multiple identical errors under "Tag Missing Band Number" error

### ISSUE THREAD

**Issue by eageldart** [MotusDev/Motus-TO-DO#1322]
The "Tag Missing Band Number" Error in the Notification Center is generating multiples of the same error (for the same Deployment ID). 

![multiples in Missing Band Number](https://user-images.githubusercontent.com/94930170/217353285-63022dab-539a-480d-b7fc-936e8e23a79c.png)

So far this is evident on project 78: https://motus.org/data/issues?id=78#v_tag_deploy_bandnumber 

I caught this yesterday and it went away after a "Rerun Data Validation", but it is back today.

**Comment by cjardine-bsc** [comment]
ah, I know what happened, should be fixed.
