### ISSUE TITLE
Missing a generic 7-element Yagi antenna under Antenna Type drop-down menu

### ISSUE THREAD

**Issue by eageldart** [MotusDev/Motus-TO-DO#1324]
Project 446 is using the following antennas on their receivers: 7-element, http://econ2way.com/catalog/members/Comtelco_HD_Yagi.html

However, we currently do not have this brand of antenna, nor a generic 7-element Yagi option in our 'Antenna Type' drop-down list
![dropdown](https://user-images.githubusercontent.com/94930170/219448772-17795c04-7d8b-4334-8221-ab6c18f40983.png)

In the short-term, can we please add "7-element Yagi"? 

For discussion: How useful is it to track brand name as opposed to just number of elements? There are an increasing number of options - do we want to keep adding to our drop-down list?

**Comment by cjardine-bsc** [comment]
can add! 

Can you provide the descriptions for me: 


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/CATHER~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/CATHER~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



antenna_type | antenna_descr | antenna_descr_fr | directional
-- | -- | -- | --
custom | custom | personnalisée | 1
custom-6 | 6 element (custom) | 6 éléments, personnalisée | 1
custom-9 | 9 element (custom) | 9 éléments, personnalisée | 1
j-pole | J-pole (omnidirectional) | antenne en J (omnidirectional) | 0
monopole | monopole (omnidirectional) | monopole (omnidirectional) | 0
none | none | aucun | 1
omni-mast | mast radiator (omnidirectional) | antenne mât (omnidirectional) | 0
omni-whip | whip antenna (omnidirectional) | antenne fouet (omnidirectional) | 0
yagi-3 | 3-element Yagi | Yagi à 3 éléments | 1
yagi-3-maple | 3-element Yagi Maple Leaf 3E166 | Yagi à 3 éléments Maple Leaf 3E166 | 1
yagi-4 | 4-element Yagi | Yagi à 4 éléments | 1
yagi-5 | 5-element Yagi | Yagi à 5 éléments | 1
yagi-5-maple | 5-element Yagi Maple Leaf 5E166 | Yagi à 5 éléments Maple Leaf 5E166 | 1
yagi-6 | 6-element Yagi | Yagi à 6 éléments | 1
yagi-7-maple | 7-element Maple Leaf 7E434 | Yagi à 3 éléments Maple Leaf 7E434 | 1
yagi-8 | 8-element Yagi | Yagi à 8 éléments | 1
yagi-9 | 9-element Yagi Unknown Model | Yagi à 9 éléments, modèle inconnu | 1
yagi-9-laird | 9-element Yagi Laird PLC-1669 | Yagi à 9 éléments Laird PLC-1669 | 1
yagi-9-maple | 9-element Yagi Maple Leaf 9E166 | Yagi à 9 éléments Maple Leaf 9E166 | 1



</body>

</html>

Thanks!

**Comment by cjardine-bsc** [comment]
simple as?
: 

<html><body>


yagi-7 | 7-element Yagi | Yagi à 7 éléments | 1
-- | -- | -- | --



</body>
</html>

**Comment by eageldart** [comment]
Yes, that's the right correction. Thanks Catherine!

**Comment by cjardine-bsc** [comment]
Done

**Comment by cjardine-bsc** [comment]
Yes, you may need to reload the cached lookup tables (done on the admin tool page).

**Comment by eageldart** [comment]
Worked! Thank you.
