### ISSUE TITLE
Remove "Receiver GPS fixes" link on "Download data" page

### ISSUE THREAD

**Issue by eageldart** [MotusDev/Motus-TO-DO#1326]
We decided in our Motus Central Technical meeting yesterday to remove the "Receiver GPS fixes" link on "Download data" page as it has trouble actually downloading the table now that it is so large. 

The link to the page here: https://motus.org/data/downloads
You can also get to the page the following ways 1) Manage Data > Download Data, or 2) Explore Data > Download Data

Data Download Link: "Receiver GPS fixes"
Data Description: "List of periodic GPS fixes for all receivers. In general these are taken hourly for stationary receivers, and more frequently for mobile receivers."

**Comment by bcreightonyoung** [comment]
This change has been deployed to sandbox!

**Comment by eageldart** [comment]
Great! Tested and ready to be deployed to Live.
