### ISSUE TITLE
viewtracks generating error in main server 

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#133]
This page is generating an error.

https://motus.org/data/viewtracks.jsp

It is working in beta and sandbox.

**Comment by Hussell** [comment]
This is probably the same issue I encountered where the JSP pages have not been recompiled despite one of the includes having changed. It is affecting all the remaining non-servlet JSP pages (e.g. https://motus.org/data/partners.jsp, https://motus.org/data/publications.jsp, etc.) My solution was to delete and re-upload the directory with all plain JSP pages. A complete restart of the server would also work.
