### ISSUE TITLE
Missing Tag Registrations/Deployments

### ISSUE THREAD

**Issue by eageldart** [MotusDev/Motus-TO-DO#1336]
We are missing tag registrations in project 382 (Project Contact: Joe Nocera), and I am wondering if someone can find them in the tag database. 

Frequency: 166.380
Serial #: NQ0024564 through NQ0024605
Manufacturer Code: 479 through 521
Model: NTQB2-4-2S-M
Burst Interval: 29.3

According to the user, they registered them to this project in 2021, and deployed them on birds this same year. They also had accessed the detection data from these tags in the past so think they existed at one point. I am trying to figure out if they might be in another project, or deleted for some reason. 

I checked the Tags table and could not find tags with this combinations of characteristics, but maybe I am missing something.

**Comment by j-sayers** [comment]
These are in the table `api_import_tags` (the holding table where new registrations first arrive). They are all prefixed with `test-` which I think indicates they were registered during the auto registration testing period (though `date_bin` is 2021-01 which may be before we started testing this...) Either way I don't believe we have a method of forcing registration in this case other than manually inserting from `api_import_tags` to `tags`. I could be wrong about though though. @cjardine-bsc or @denislepage do you know? BTW these are records in question from `api_import_tags`...

(
47411'
47412'
47413'
47414'
47415'
47416'
47417'
47418'
47419'
47420'
47421'
47422'
47423'
47424'
47425'
47426'
47427'
47428'
47429'
47430'
47431'
47432'
47433'
47434'
47435'
47436'
47437'
47438'
47439'
47440'
47441'
47442'
47443'
47444'
47445'
47446'
47447'
47448'
47449'
47450'
47451'
47452'
48062'
48063'
48064'
48065'
48066'
48067'
48068'
48069'
48070'
48071'
48072'
48073'
48074'
48075'
48076'
48077'
48078'
48079'
48080'
48081'
48082'
48083'
48084'
48085'
48086'
48087'
48088'
48089'
48090'
48091'
48092'
48093'
48094'
48095'
48096'
48097'
48098'
48099'
48100'
48101'
48102'
48103
)

**Comment by eageldart** [comment]
Thank you for checking @cjardine-bsc . Would these tests have allowed them to look at detection data for these tags at one time? 

They contacted me yesterday explaining that they **did **not**** make recordings for these tags... So I think we are dealing with the worst case scenario. So now I am confused by how they said they once were able to look at these tags in the motus database.

**Comment by cjardine-bsc** [comment]
No, they would never have seen any detection data from tagfinder for these tags. I'm not sure what they are referring to. 

I'll push the lotek recordings to the live tag database, but we'll need to explain to them that we're using data generated through a test of a process we know was not accurate...so we'd expect some degree of wonkyness with detection data.

**Comment by cjardine-bsc** [comment]
Pushed.
