### ISSUE TITLE
Most recent processing time in recv deployment tool broken

### ISSUE THREAD

**Issue by pmorrill** [MotusDev/Motus-TO-DO#134]
The most recent processing datetime value for recv deployments is not querying properly, due to a scaling issue with time stamp comparisons. I am working on an adjustment.

**Comment by pmorrill** [comment]
Fix is in.

**Comment by Hussell** [comment]
I've deployed to beta with your fix, but I don't see any difference between beta and live on, e.g. https://motus.org/data/receivers/edit?projectID=1&id=383

Is there a link where the bug and fix can be tested?

**Comment by pmorrill** [comment]
ok. Strange. Am looking into it.

**Comment by Hussell** [comment]
Looks like it's my mistake: the bug is on the receiver deployment page not the receiver page: https://beta.motus.org/data/receiver/deployment/edit?projectID=1&id=3560

Fix seems to be working.

**Comment by pmorrill** [comment]
I think it is good yes.

I did update the Tx frag in beta5 just now: in the edit.jsp file which waa using the wrong text.
