### ISSUE TITLE
Links to update

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#135]
Links need to be updated on the following pages:

On the manage data page https://motus.org/data:
Submit detection data: https://sgdata.motus.org/upload/upload-from-computer.php

And the data download page https://motus.org/data/downloads?projectID=72:
unprocessed data: https://sgdata.motus.org/download/index.php

**Comment by Hussell** [comment]
These changed links are live now, but I'm getting 403: Forbidden from https://sgdata.motus.org/upload/upload-from-computer.php

**Comment by zcrysler** [comment]
John took the upload page offline yesterday to deal with a bug, the link should still work once it's back online
