### ISSUE TITLE
Create new 404 error page

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#136]
To avoid having to place redirects for obsolete pages after they are deleted, we should create a new simple 404 page.

Something equivalent to this:

http://www.bsc-eoc.org/doesnotexist

To activate it, an equivalent entry to this should be added to the web.xml page for the context, under the <web-app> root, using the correct location:

  <error-page>
    <error-code>404</error-code>
    <location>/404.jsp</location>
  </error-page>

**Comment by Hussell** [comment]
https://beta.motus.org/data/test

Note that this doesn't look much like the 404 page on Wordpress.
https://beta.motus.org/test

**Comment by denislepage** [comment]
We should make at least the text consistent, if not the full layout.  I might prefer something closer to your version than the one currently on WP.

Would it not make sense to do a redirect to a 404 page on WP as the best way to ensure consistency? If so, I can task Catherine to come up with a common page for that. I can’t remember how the WP error is being handled at the moment or where it resides, but that’s the page that we would likely need to modify.

We should also try to make it a little prettier, while we’re at it.

Denis

**Comment by Hussell** [comment]
I don't have sufficient permissions on the beta WordPress instance to view the 404 page, and there isn't one on sandbox.

**Comment by cjardine-bsc** [comment]
Okie, I've made a new sad-puffin error page. In wordpress it looks like so: 

https://sandbox.motus.org/test

If we're happy with that I can update the 404.jsp file. Jeremy, I'm not seeing that file here: motus\motus\web\data  did you push it to GIT?

**Comment by denislepage** [comment]
We may need to change the behaviour in the php file, so instead of printing the message, we force the page to be sent to a 404.php file in Wordpress, whether the request is originally sent to WP or Tomcat.

My hope/intent was that Tomcat would handle this the same way and send the request to the same 404 page, but I am not sure how you’d access it in WP, other than make a request to an inexistent page.

We need to figure out the proper way to handle errors in WP first. Creating the page should be easy, and so should be putting the redirection where you currently have the content of the error page.
https://codex.wordpress.org/Creating_an_Error_404_Page

**Comment by cjardine-bsc** [comment]
Okay, I added a 404.php page to our theme in sandbox and removed the code from index that I was using. 

https://sandbox.motus.org/404.php

We should mow be able to change tomcat to reference the 404.php page in wordpress. 

I'll add the wordpress page in live too.

**Comment by denislepage** [comment]
I think the last piece missing would be to redirect the Java errors to the Wordpress 404 page.

The page also is broken when the redirection comes from WP: https://motus.org/test
