### ISSUE TITLE
gps file empty

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#137]
"receiver GPS fixes" file downlaods an empty .csv: https://motus.org/data/downloads

**Comment by Hussell** [comment]
Works for me. I get a 479MB file.

**Comment by zcrysler** [comment]
Hm, maybe I wasn't logged in - can we remove that link when people aren't logged?  There's no point in allowing the download of an empty file

**Comment by Hussell** [comment]
A project may, if desired, make their GPS fixes available to users who aren't logged in, although no project has, yet.
