### ISSUE TITLE
change "from" address in email notifications

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#139]
I have changed at least some of the email notifications, so they use a different "from" address rather than support@bsc-eoc.org. One issue is that many of them are getting caught in spam filters, and I can't whitelist my own address.

I am therefore using no-reply@bsc-eoc.org when the email is meant to be sent at support@bsc-eoc.org. When the email is destined for a user, we should use motus@bsc-eoc.org as the "from" address (e.g. password reset).

I've changed this in a number of  places (including some of the obsolete sections). I am not sure I have caught them all, but most likely (searched for all uses of SendMail).

Issue probably can be closed as soon as someone confirms that there are no more left behind.

**Comment by Hussell** [comment]
Found one more in MotusTools (email to user, changed to motus@). Doesn't look like there are any more uses.
