### ISSUE TITLE
API: receiver/sensordeployments failing with database error

### ISSUE THREAD

**Issue by jbrzusto** [MotusDev/Motus-TO-DO#143]
e.g.
```bash
curl  -D- --data-urlencode 'json={"date":"20180124121322","fmt":"json","login":"john","pword":"XXX","projectID":78}'
 https://motus.org/api/receiver/sensordeployments
```
gives
```
HTTP/1.1 500 Internal Server Error
Content-Length: 85
Content-Type: application/json;charset=UTF-8
Server: Microsoft-IIS/7.5
X-Powered-By: ASP.NET
Date: Wed, 24 Jan 2018 12:12:29 GMT

{"version":"2.0","errorCode":"database-error","errorMsg":"A database error occurred"}
```

**Comment by jbrzusto** [comment]
(and sorry - this should have been filed against MotusDev/MotusAPI)

**Comment by Hussell** [comment]
No problem. I'm inclined to keep issues all in the same place while the volume is low enough to keep it practical. I've put the API tag on all existing issues so that you can filter out everything else.

**Comment by pmorrill** [comment]
John: we have changed the way we store the 'is_mobile' field for sensor deployments, and the query you are tapping here was not updated. It's an easy fix if you don't need the is_mobile field. Slightly more involved if you do.

Let me know.

**Comment by pmorrill** [comment]
Cancel that question - I've got a fix for you that includes isMobile field in the return. It's just gone in to the beta branch code so will first be deployed to https://beta.motus.org.

**Comment by jbrzusto** [comment]
Thanks.
It's working on beta.motus.org, but I can't test on motus.org as the server there is not responding
to *any* API requests at the moment.

**Comment by Hussell** [comment]
We just redeployed and restarted the live server.
