### ISSUE TITLE
missing error code new_recv_site_requires_location

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#145]
Exception:
java.lang.IllegalArgumentException: Unable to find 'new_recv_site_requires_location' in the table of error codes.
Stack trace:

File Name | Line Number | Class Name | Method Name | Native Method?
-- | -- | -- | -- | --
Messages.java | 80 | org.bsc.motus.web.Messages | lookup | false
Messages.java | 140 | org.bsc.motus.web.Messages | lookup | false
Messages.java | 223 | org.bsc.motus.web.Messages | add | false
EditRecvDeploymentServlet.java | 167 | org.bsc.motus.web.EditRecvDeploymentServlet | lambda$doPost$0 | false

**Comment by cjardine-bsc** [comment]
It was in sandbox, not motus. I've added it to motus. 

Would some fine gentleman be able to help a lady with a translation. *twirls parasol* 

"You must provide latitude and longitude when defining a new deployment site."


This was the only delinquent. The below returns zero errors. 

SELECT *
  FROM [motus_sandbox].[dbo].[adm_error_code] a
  where not exists (select error_code from [motus].[dbo].[adm_error_code] b where a.error_code =b.error_code)

**Comment by denislepage** [comment]
Vous devez fournir la latitude et la longitude lorsque vous créez un nouveau site de déploiement.

**Comment by cjardine-bsc** [comment]
Updated.
