### ISSUE TITLE
Data upload link dead

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#146]
From the menu Manage Data > Upload detection files, link not working, should be https://sgdata.motus.org/upload/upload-from-computer.php

**Comment by cjardine-bsc** [comment]
I updated the link, but it's not loading from that URL. Is it still down?

**Comment by zcrysler** [comment]
It's working for me, I've been uploading data all morning.  Does this work https://sgdata.motus.org/upload/index.php

**Comment by cjardine-bsc** [comment]
I'm getting this error: 


The page isn’t redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

    This problem can sometimes be caused by disabling or refusing to accept cookies.

**Comment by Hussell** [comment]
The link is working for me, too. Perhaps clear your browser cache/cookies?
