### ISSUE TITLE
Tag test deployments not saving dates

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#147]
A user and I have both been trying to create test deployments for her as she has Errors in her notification centre about "tag detections outside of deployments".  However when I create the new deployment, mark it as a test, and hit save, the page refreshes and I see the message "tag deployment #15631 was successfully updated." but the dates have returned to blank. 

This leads to her getting new errors generated about overlapping tag deployments.

This is project 49, I was attempting to do it for tag 25715: https://motus.org/data/tags/edit?projectID=49&id=25715

**Comment by zcrysler** [comment]
Just a gentle plea to have this looked at - a few users are trying to make test tag deployments to clear out their data issues page

**Comment by denislepage** [comment]
I like the sound of that… People are paying attention to the issue page!

**Comment by zcrysler** [comment]
Oh yes, people have found it and are using it, feedback has been good!

**Comment by pmorrill** [comment]
It's on my list this morning.

**Comment by pmorrill** [comment]
A fix for this is in beta5 and master branch;

**Comment by zcrysler** [comment]
I tried on beta and live, every other field seems to save fine, but dates are still not saving

**Comment by pmorrill** [comment]
I think that Jeremy was having trouble deploying the beta code this AM (MY FAULT). We are trying to correct it now.
