### ISSUE TITLE
API status

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#148]
It would be useful to have a simple API entry point that confirms that the API is still responding.

The api_info could be modified slightly to play that role, but I can't make it work at all. The first 2 calls below generate a server error. The third asks for a login, and the fourth, when using a valid login, still says that login is invalid. The SGDataAPI has an option for public calls associated with this entry point, but it doesn't seem to be working.

http://motus.org/api/user/api_info
http://motus.org/api/user/api_info?json={}
http://motus.org/api/user/api_info?json={%22date%22:%2220180127022353%22}
http://motus.org/api/user/api_info?json={%22date%22:%2220180127022744%22,%22user%22:%22user.name%22,%22pword%22:%22xxxxxxx%22}

My preference would be to allow the first call to work, without any parameters.

When set up, I can have a process ping the server every 10-15 minutes to confirm status like I do with the other servers/context.

Having a public page that we could link people to would possibly also help. IE, say in the book, if the tagme function returns an error, go here to check the API status.

**Comment by pmorrill** [comment]
I have added a simple '/api_info' entry point to the master and beta5 branches. It requires no json={} structure or authentication.  It returns the version number : 2.0

**Comment by Hussell** [comment]
The link is: https://motus.org/api/api_info

Seems to be working.

**Comment by pmorrill** [comment]
Yes - the url Jeremy lists above is the official 'Motus' api check-point. It should not require any authentication.

**Comment by denislepage** [comment]
I got the URL wrong, sorry.
