### ISSUE TITLE
motus FAQ:  minor revision needed re sensorgnomes

### ISSUE THREAD

**Issue by jbrzusto** [MotusDev/Motus-TO-DO#149]
Interestingly, the only mention of ["open-source" on motus.org](https://www.google.ca/search?q="open+source"+site%3Amotus.org)  is under point 7
of https://motus.org/faq/  which states:
 
> ... We have developed open-source technology called SensorGnomes 
 
SensorGnomes were developed by Phil Taylor's lab at Acadia U. and predate
motus:

$ whois sensorgnome.org
Domain Name: SENSORGNOME.ORG
...
**Creation Date: 2012-10-23T23:19:12Z**
(several SGs had already been deployed at this point)

$ whois motus-wts.org
Domain Name: MOTUS-WTS.ORG
...
**Creation Date: 2014-03-03T16:29:31Z**

**Comment by cjardine-bsc** [comment]
I've changed the text on the FAQ page. 

"Researchers and other people are also encouraged to deploy more receivers to expand the geographic coverage of our network. Technology called SensorGnomes has been developed that keeps the costs of each receiver relatively low,"
