### ISSUE TITLE
dongle type update

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#150]
Should have caught this sooner, but each antenna has a dongle, so on the receivers page, there should be a dropdown menu for each antenna, rather than 1 per receiver deployment

**Comment by pmorrill** [comment]
OK - I'll look into an interface adjustment by mid-week. Catherine, you will adjust the database for us?

This is only for sensorgnome antennas, yes?

**Comment by cjardine-bsc** [comment]
Database has been adjusted! 

I've left dongle_type in sensor_deployments for now, once this is adjusted, tested and deployed to live we can drop that column. 

I also updated the sensor_antenna column to match data that was populated in the dongle_type column in sensor_deployments. I'll need to re-run the below once the web change has been made to make sure we capture any info that is entered between now and then. Let me know. 

  use motus
  go 
  
  update  a
  set dongle_type = b.dongle_type 
  FROM sensor_antennas a inner join sensor_deployments b on a.deployment_id =b.id

**Comment by zcrysler** [comment]
yes - dongle type is only valid for sensorgnomes

**Comment by pmorrill** [comment]
I have moved the dongle_type handler to the antenna logic, and updated the interfaces. Is in the beta5 branch for next deployment. Will go into master branch today.

Once tested, the db fields on sensors_deployments can be removed in both databases.

**Comment by zcrysler** [comment]
Is beta5 accessed some special way?  I don't see changes here: https://beta.motus.org/data/receiver/deployment/edit?projectID=1&id=681

**Comment by cjardine-bsc** [comment]
Paul would have checked in his changes but until Jeremy re-deploys Beta they wont show up online. 

I've assigned him here, I'm sure he'll re-deploy when he gets a moment.

**Comment by pmorrill** [comment]
Correct. But I messed up a little bit of the code check-in, so he was not able to build. We are trying to correct it right now.
