### ISSUE TITLE
Minor translation fixes to Motus.org

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#151]
Identified by BSC's translator. I'm not sure if these are fragments, or text within the webpage itself. Please see below.

https://motus.org/data/login
In the dark blue menu band at the top, an "s" should be added to "donnée"
(i.e. Gérer les données).
In the sentence below "Nom d'usager requis", the verb "requère" should read "requiert".

https://motus.org/data/tracksSearch?lang=fr
In the dark blue menu headings band at the top, an "s" should be added to "donnée" (i.e. Gérer les données).
"Recherchez les pistes de l'émetteur pour voir:" should read "Recherchez les parcours de l'émetteur pour :"
"Seuls ces projets" should read "Seulement ces projets".
"Seules ces espèces" should read "Seulement ces espèces".

**Comment by Hussell** [comment]
I've done the ones on the page proper, but Catherine will have to change the menu. In addition to pluralizing "Gérer les donnée", "Exploration -> Visualiser les pistes" should be changed to "Visualiser les parcours".

**Comment by cjardine-bsc** [comment]
Changes made

**Comment by Hussell** [comment]
Reloaded the banner on all servers so the changes are visible.
