### ISSUE TITLE
data validation not updating

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#152]
I updated some tag deployment ranges yesterday afternoon for project 123 to include detections that occurred outside of their range.  I tried re-running the validation yesterday and this morning, but I'm still getting errors that there are detections outside of tag deployments.

project 123: https://motus.org/data/issues?id=123#v_tag_hits_out_deploy
Error: Number of detections : 7 From 2017-05-11 09:04:33 - 2017-05-11 09:05:17
tag you are brought to: https://motus.org/data/tag/edit?projectID=123&id=23410 which has a deployment running between 2017-05-11 08:00 to 2017-05-31 23:59 so should contain these hits.

It says the last validation was run  2018-01-31, 8:25 AM PST

**Comment by Hussell** [comment]
Possibly related to #140?

**Comment by cjardine-bsc** [comment]
Ah of course, same as https://github.com/MotusDev/Motus-TO-DO/issues/140 just with Tags, instead of sensors. 

I've implemented the fix across all prTaghitsSummaries procs.
