### ISSUE TITLE
Aliased Tags - see https://github.com/MotusWTS/MotusRBook/issues/15

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#155]
See https://github.com/MotusWTS/MotusRBook/issues/15

**Comment by Hussell** [comment]
A reasonably clear example of tag aliasing:
https://sgdata.motus.org/download/168/SG-4005BBBK4150-2018_MONTREAL_MOULT_McGill_Bird_Observatory_hourly_tags.png

The MONTREAL_MOULT tags are real. The rest are probably due to alias and/or noise.

**Comment by Hussell** [comment]
The Alaska Bats project also supposedly generated a some false positive due to aliasing:
https://sgdata.motus.org/download/75/SG-3214BBBK7294-2015_AlaskaBats_Mentasta%20Lodge_hourly_tags.png
https://sgdata.motus.org/download/75/SG-4001BBBK1790-2015_AlaskaBats_Ruby's_hourly_tags.png

**Comment by StuMackenzie** [comment]
Yes, there is a lot of junk being produced here. I'd suspect that almost all of the other detections aside from the moult birds are junk. Whether or not that's directly related to aliasing or not is another issue. The BANS seek like a reasonable aliasing case. 


Stu

**Comment by cjardine-bsc** [comment]
List from Stu, adding here so I have the examples all in one place: 

Alaska Bats - and Bank Swallows

McGill Thrushes

Lukosius - Deployments 2430, 2545 and 2544. These were creating aliases with Quebec Thrushes.

**Comment by StuMackenzie** [comment]
A receiver deployment example of likely aliasing occuring - https://motus.org/data/receiverDeployment?id=5369

Any tags that aren't KERL TRBL are likely bogus and should be removed from the public feed.

**Comment by adamdsmith** [comment]
Another example would be most (all?) non-project 4 tags detected at receiver 5062 (SG-32FDRPI3CB45) starting evening local time on 2019/10/27 when ~ 15 tags started going out over two days. 

The apparently aliased tags are fairly diverse in ID and burst interval. I’d be interested in the current approach to flag longer aliased runs (4+).
