### ISSUE TITLE
Receivers with gps data but no other information in sql file

### ISSUE THREAD

**Issue by tabanid** [MotusDev/Motus-TO-DO#157]
There are a number of examples in the databases I'm looking at where there is no information about the receiver a given batch of detections came from. 

E.g. in runID 18635943   batchID 87665

I didn't think this was even possible, since every batch must come from a particular receiver. 

It makes it difficult/impossible for a user to fix receiver metadata. 

So, two questions: 
1) How is this possible?
2) Is that information really missing or just not translating to the final table?

**Comment by jbrzusto** [comment]
On the sgdata server, this batch has motusDeviceID=19:
```sql
MariaDB [motus]> select * from batches where batchID=87665;
+---------+---------------+--------+----------------+-----------------+---------+------------------+-------------+----------------+------------+------------------+--------+
| batchID | motusDeviceID | monoBN | tsStart        | tsEnd           | numHits | ts               | motusUserID | motusProjectID | motusJobID | recvDepProjectID | status |
+---------+---------------+--------+----------------+-----------------+---------+------------------+-------------+----------------+------------+------------------+--------+
|   87665 |            19 |     55 | 1473253400.915 | 1473278675.4519 |    6882 | 1505309552.23755 |        NULL |           NULL |      86216 |               10 |      1 |
+---------+---------------+--------+----------------+-----------------+---------+------------------+-------------+----------------+------------+------------------+--------+
```
and device 19 has this serial number:
```sql
sqlite> select distinct serno from recvDeps where deviceID=19;
serno
SG-1614BBBK1631
```

**Comment by cjardine-bsc** [comment]
Hi Phil, 

I'll look into this now, are you pulling the data using a project ID or receiver ID? Which projects and/or receivers are you seeing this for? (that will give me a starting point to start sleuthing).

**Comment by tabanid** [comment]
Sorry, I should have added that bit ... from the projectID ...

blpw.sql <- tagme(86, update = TRUE)
blpw.tbl <- tbl(blpw.sql, "alltags")
blpw.df <- filter(blpw.tbl, runLen > 2) %>% 
  select(motusTagID, ambigID, mfgID, hitID, runID, batchID, 
                  ts, sig, runLen, freqsd, sigsd, slop, burstSlop,
                  antType, antBearing, gpsLat, gpsLon, recv, port,
                  recvDeployLat, recvDeployLon, recvDeployName, 
                  recvProjID, recvSiteName) %>% 
  distinct() %>% collect() %>% as.data.frame() %>%
  mutate(ts = as.POSIXct(ts, origin="1970-01-01"), 
         year = year(ts))

**Comment by tabanid** [comment]
Here is a list of batches from project 86 with NA for recv name (RDS file).
[batch.recv.NA.zip](https://github.com/MotusDev/Motus-TO-DO/files/1696355/batch.recv.NA.zip)

**Comment by tabanid** [comment]
Sorry, I closed this by mistake but eventually figured out how to reopen it. Here is a list of all batchID from project 86 with missing receiver information (an RDS file).

[batch.recv.NA.zip](https://github.com/MotusDev/Motus-TO-DO/files/1696369/batch.recv.NA.zip)

**Comment by cjardine-bsc** [comment]
I downloaded the data from project 86 using tagme. When I look at the Alltags view for the batches you list, there is receiver deployment information (i.e. 195 and 87665 are complete) so it appears that our two .motus files for this project are different (drat). 

I'm doubtful that this is a permissions issue, given that project 86 is just a tagging project and does not have any sensors. If it was a permissions issue you wouldn't be getting the data for any receivers. Can you look in the recvDeps table in your .motus file and see if there are any deployments for deviceID 19 (there should be 5). Knowing if this is in that table will help me pinpoint the issue. 


That said, there were some batches that were also returning as NA in my file, such as batchID 1290. That was related to another separate issue recently resolved. This metadata should show if you run:

blpw.sql <- tagme(projRecv = 86, forceMeta = TRUE) 

Cheers,

**Comment by tabanid** [comment]
_Can you look in the recvDeps table in your .motus file and see if there are any deployments for deviceID 19 (there should be 5) .._

There are actually 7. I can't seem to replicate the batch/runIDs above (the do have receiver information) so I must have messed up somewhere. However, there are still 'missing receivers' so I'm going to close this, and open a new issue, with proper code to document the missing receivers.

**Comment by denislepage** [comment]
If you have additional deployments, you may be better off deleting the existing content of the metadata tables and forcing an update again. The metadata function allows that, and you can specify which project you want instead of asking for the entire metadata set, or you can use DBI to send a delete command for the tables.
