### ISSUE TITLE
TrackSearch - Missing 2017 Project Data from James Bay Project # 38

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#158]
As far as we know/can tell, all of the tag and station metadata is entered and correct, and most of the station data has been processed and is in the system (at least enough to show birds detected on James Bay).

However, only 29 tags show up from this project in 2017 using the Track Search tool (most tracks look like junk). 

It's possible they're just not showing up because they haven't been detected elsewhere, but the majority were detected on James Bay.

**Comment by zcrysler** [comment]
I think most if not all of these were deployed in 2016, so it seems like no tags deployed in 2017 are showing up here

**Comment by Hussell** [comment]
The tracks are supposed to be recomputed on a schedule. It appears this isn't happening: the tracks have only been computed as a job once, on 2017-12-19.

**Comment by denislepage** [comment]
Schedule was never set up. Now done, as a daily process for the moment. Seems a bit slower to run than before (5-6 minutes). We can try to speed it up and run more frequently on the live database.

James Bay for 2017 now shows ~150 tags.
