### ISSUE TITLE
track tool show motusTagID

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#159]
if the track search tool showed the motusTagID instead of or in addition to the deployment ID, it would make it easier to find out which tag this is on the tag page

**Comment by Hussell** [comment]
Which tag page are you referring to? https://motus.org/data/projectTagDeployments?id=38 may help.

**Comment by zcrysler** [comment]
on the track tool page (https://motus.org/data/tracksSelect?e=2013-01-01&l=2018-12-31&p=38), it's listing tag deployment ID, so trying to find out more info on those tags online is difficult since you can't directly link to the tag, and navigating back to the project tag page lists by motusTagID rather than deployment ID

**Comment by Hussell** [comment]
https://motus.org/data/projectTagDeployments?id=38 lists by tag deployment ID, unlike https://motus.org/data/projectTags?id=38. You can also get to information about a specific track by clicking on it on the map and following the link.

**Comment by zcrysler** [comment]
I meant that when on the track tool page https://motus.org/data/tracksSelect?e=2013-01-01&l=2018-12-31&p=38, when it lists the tags, before you make the map, it lists tags like:

Least Sandpiper #15218, James Bay Shorebirds, 2017-08-31, 2017-09-08

the ID is the deployment ID.  My next step if I'm curious about one of those tags as a manager of the project, is to go to my manage tag page to see them all in one place https://motus.org/data/project/tags?projectID=38.  Here tags are listed by motusTagID, so to get more info on a tag on the track page, I have to download tag metadata to look for deploymentID.   

Since this is meant as a public tool and you can get info on tags one by on once you make the map then it's fine as is, it just takes a few more steps if you're looking for info from a project management perspective.

**Comment by Hussell** [comment]
https://beta.motus.org/data/tracksSelect?e=2013-01-01&l=2018-12-31&p=38

I've added a link to the tag deployment page. If you're logged in, there's a link directly from there to the project management page for the tag deployment. Good?

**Comment by zcrysler** [comment]
Great, thanks!
