### ISSUE TITLE
Data Issues bugs

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#162]
For v_sensor_invalid_dt_end and v_sensor_invalid_dt_start prDataValidation_pr is inserting the receiver ID instead of the receiver *deployment* ID, which breaks the url_fix link (e.g. https://motus.org/data/issues?id=170#v_sensor_invalid_dt_end)

url_fix for v_sensor_no_detections should be: /data/receivers/edit?projectID=%d&id=%d (e.g. https://motus.org/data/issues?id=4#v_sensor_no_detections)

url_fix for v_sensor_not_registered should be: /data/receivers/edit?projectID=%d (e.g. https://motus.org/data/issues?id=3&lang=en#v_sensor_not_registered)

**Comment by cjardine-bsc** [comment]
Changes implemented.
