### ISSUE TITLE
acceptance of collaboration policy

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#163]
We discussed this a while back, and we should now look at implementation. I couldn't find a previous issue created for this.

Whenever people log in, we need to make a check to confirm if they have accepted the collaboration police available here: https://motus.org/policy/

There is a placeholder in the user_properties table (policy_accepted_dt) to store this information, and I just created a new table called adm_policy (field policy_dt) to compare the current version. 

Expected behaviour: Within the Java filter that verifies the credentials of any page, there should be a verification of the policy_accepted_dt. NULL values or values that pre-date the adm_policy.policy_dt value, should trigger a redirect to a simple page, where user are asked to confirm their acceptance of the revised policy document. If possible, they can then be redirected to the original link they tried to access originally once accepted. The user properties is already part of the MotusUser bean, and should simply have to be handled through that object.  The global version date is null at the moment, which means that people will not be asked to confirm until a date is set.

This validation should not be limited to the initial login process, but presumably on any page that requires Motus authentication. That, or we delay creating the session object until the conditions are met, the key being that they can't access user pages until they've accepted.

I have added a new getPolicyDt() and setPolicyDt() static field to MotusProjInfo, and we should add an option under the admin tools page to call the set method and refresh the static object. I'm fine if you deem there is a better place to store that value, but that one would be usable from all contexts.

The checkbox for acceptance should also be added to the registration page when new people sign up. The message should probably a bit different for updates vs. first time (e.g. Start with: Please note: the collaboration policy has changed). We can handle adding a few highlights of the changes on the wordpress page itself if necessary, rather than in the notification.

Finally, at the moment at least, I would limit this behaviour to the web site only, and not the API authentication, including the calls made by John's user for SG data, his upload site, or the R package. We may eventually want to return an authentication error on the R package, but let's wait a bit on that.

**Comment by denislepage** [comment]
From Stu: "I can't really think about how robust we need this statement to be beyond: "I agree to the terms and conditions outlined in the Motus Collaboration Policy and associated Fee Schedule."  "

The above works for the registration page, and to appear besides the checkbox on the new page.

We should probably add a generic sentence above that saying that "All Motus users are asked to read the Motus Collaboration Policy and associated Fee Schedule".

And if this is an update: "Please note that the collaboration policy has been modified on XXX and must be accepted again in order to continue using the Motus Research Platform. 

Stu: "The complication arises with what permissions or authority that individual has over the project, but if we ask it to everyone then we nail it by default. Many PI's for instance will never log on necessarily. We could add, "I have the authority, and I agree", or "On behalf of my project, I agree"

Once the page is up on Sandbox, we can revise what it says again.

**Comment by Hussell** [comment]
Now duplicated by #292.
