### ISSUE TITLE
Collecting Additional Project and User Information 

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#165]
Hi all,

I think it would be very useful to make a few changes to how we're collecting and organizing both project and user information. I've assigned Catherine, because we've talked about it before and I know she's given it some thought, but please modify as you see fit.

We talked about aspects of this before, but there have been a number of issues lately (updating supporters/partners page, proper acknowledgment, and invoicing) that have brought this back to the forefront. 

User Information: 

Affiliations/Organizations and physical mailing address should be required information upon registration, not optional for at least PI's, but perhaps everyone. We may want this to initiate a notification centre flag - 'missing user information'

Project Information:

Newly required and displayed information:

1) Lead Organization
2) Partner Organizations or Collaborators
3) Funders

**Comment by cjardine-bsc** [comment]
Hiya, 

I have some database structure in place to handle this, we'll just need to make a few decisions and implement a web interface. 

We have a table in the database called "institutions" this is the table that populates the Collaborators and Supporters table here: https://motus.org/data/partners

We also have a table called projects_institutions. This isn't implemented yet, but the purpose is to track which institutions are associated with what projects and in what capacity. 

When editing their projects, I can envision a table with: 

Organization (dropdown lookup to institutions table) 
Lead (Checkbox)
Collaborator/Partner (Checkbox)
Funder (Checkbox)
Rank (Numeric) 

This data will be written to the projects_institution table. PIs/users should be able to select existing institutions from the institutions table. We'll also need an interface for creating a new institution for organizations that are not yet on the list. We'll need to add a "reviewed" or "approved" bit to the table so that newly added institutions can be glanced over by Zoe to check for duplicates or duds before they are added to the partners list (https://motus.org/data/partners). 

The institution table doesn't have a great way to deal multiple languages at this point. I suspect we'll probably just add a few new fields to capture key information in both languages (Institution_name_fr). How we'll handle multiple languages when users create institutions will need to be discussed. 

An unresolved question is which users will be able to edit an existing institution. Possibly something for one of our calls. 

Once this is set up I can set up a notification center alert for missing information.

**Comment by denislepage** [comment]
As discussed today, there are 2 aspects to this.

1) The first is probably most relevant to Stu’s communication needs, is having contact information for each users, and in particular PI’s. It presumably easier to deal with. There are 2 possible places we can capture this:

New registration https://motus.org/data/user/new

Profile: https://motus.org/data/user/edit

Part of the reason we left the contact information out of the registration page is spam. The more fields we open up, the more likely we will get inundated with spam registrations. (Related, I’m still unclear that people are being asked to confirm their registration via an email?)

My preference would be to require PI users to fill in their registration either: 1) after they submit their registration (that may still lead to spam), 2) every time they log in, we verify and force them to enter the details if they are an approved PI (similar to the policy acceptance), and/or 3) rely on the notification center (we should do that regardless of the rest – feel free to add this now). For PI’s, we should make address, city, stateprov and zip/postal code required. I’m not sure about affiliation begin required (not everyone is affiliated), but Stu can decide. That brings the same question about state/province being a drop down as we deal with previously.

2) The second aspect, which I think is less critical for Stu’s current need, are the institutions linked to a project.  Is this list being used in anything currently outside of the partners page? Having a common list of institutions could be useful in a few places. This includes being used to standardize the affiliation field in the user profile, the landowner, or simply listing supporters and funders as we do now.  A “relatively” simple interface change for entry would be to let them type a name, and then make suggestions to help standardize. We could store the organization ID in place of the name, maybe, which would imply changing the output in a number of places, I expect.

The complications for allowing people to manage this table may not be worth the effort though, and this may be something that we continue to manage ourselves. People need to be able to enter new organization names that may not already exist, but we may or may not want to use those names in a common list. There is the related question about whether and when people should be able to make changes to existing names in the common table, and how that process works.

When and if we start allowing people to access third-party data, I think we are going to want to have in place a acknowledgment field where PI are able to enter how they would like their projects to be acknowledged. It’s only vaguely related to the list of organizations, but it’s also about recognition.

**Comment by StuMackenzie** [comment]
Not sure this issue needs to be open anymore, but I'm writing here to remind us of a few changes that may need to be implemented to make invoicing and correspondence much easier. Most I think have been resolved:

1) Mandatory contact information for all PI's - still 'optional' here - https://motus.org/data/user/edit
- I haven't looked at what's required from a new registration

2) This is linked to our drop-down - Fees will be paid by.

I hate to say it, but suspect that we may need an 'institutional affiliation' and a separate address for 'billing information' as they are often the same.

Anyway - for further discussion.

**Comment by jsayers-bsc** [comment]
We could definitely still use some tweaks and improvements. 

There are a couple recent related comments [here ](https://github.com/MotusDev/Motus-TO-DO/issues/628)and [here](https://github.com/MotusDev/Motus-TO-DO/issues/650). 

I had some notes scribbled out to bring up tomorrow along these lines, that I'll insert below... 

**Project level contacts**
- PI. _Usually_ the one who is invoiced, but more fields should be mandatory as described above. In some cases the PI may have nothing at all to do with the day to day aspects of managing the project, accessing data, etc...
- Additional contacts per project
   - There is a list of users added to the project, which sort of gets at this. But there are often users on the project list who are only involved with certain stations, or who aren't even involved at all anymore, or who are only there to give them access to download data.
    - Is there a need for additional drop-down options to better define users role with regards to a project?

**Site level contacts (site stands in for active deployments in most cases)**
- We really only have a landowner category for contacts. That's necessary, but often not the person who is involved with it day to day
- Additional contact fields would be helpful for sites where we deal with other individuals at that site. 
- Generally, something similar to the user list for a Project would be helpful here
  - Add multiple people to a site (they could be landowners, site contacts, volunteers, etc)
  - Define their role with a series of drop-downs similar to the user list in Projects
    - Part of the purpose of that is to inform us who to contact, when, and about what. For instance, we want reminders to check the site and download data going those individuals doing that, and not cluttering the inbox of someone not involved in that aspect.
  - This can be done in a spreadsheet, but keeping it in the DB seems ideal if possible

Those are some thoughts...

**Comment by denislepage** [comment]
For creating a separate address for billing, we’d mainly have to add a new billing_user_id field and generate a new user record that has the details. Most of the work would be on the user interface, and we should have a toggle that allows to use the same info in both places.

I don’t think the toggle needs to be a database field. If the billing_user_id is null, the form assumes that the same address is being used. Users can then uncheck it to enable to other address.
