### ISSUE TITLE
`tagme` not yet working with individual receivers?

### ISSUE THREAD

**Issue by adamdsmith** [MotusDev/Motus-TO-DO#167]
Attempting to grab data from an individual receiver fails with an Internal Server Error:

``` r
library(motus)
library(motusClient)

ci <- tagme(projRecv = "SG-3115BBBK0782", new = TRUE, update = TRUE)
#> 
#> updateMotusDb started (8 rows)
#>  - Create new view allambigs that converts ambig columns into rows
#>  - remove previous version of alltagswithambigs view
#>  - Remove empty gps detections
#>  - Add a new column "siteName" to table "recvDeps".
#>  - Remove previous version of alltags
#>  - Create new version of alltags that includes additional deployment fields
#>  - Create (or modify previous version of) filters
#>  - Create (or modify previous version of) runsFilters
#> Error: Internal Server Error
```
Attempts to update the object per the troubleshooting guidance in the [Motus R book](https://motus.org/MotusRBook/appendixB.html#i-get-an-internal-server-error-message-when-using-tagme-update-true) also fail...

```r
ci <- tagme(projRecv = "SG-3115BBBK0782", update = TRUE)
#> Error: Internal Server Error

packageVersion("motus")
#> [1] '1.0.0'
packageVersion("motusClient")
#> [1] '1.0'

sessionInfo()
#> R version 3.4.2 (2017-09-28)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 7 x64 (build 7601) Service Pack 1
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_United States.1252 
#> [2] LC_CTYPE=English_United States.1252   
#> [3] LC_MONETARY=English_United States.1252
#> [4] LC_NUMERIC=C                          
#> [5] LC_TIME=English_United States.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#>  [1] motus_1.0.0     motusClient_1.0 ggmap_2.6.1     ggplot2_2.2.1  
#>  [5] lubridate_1.7.1 maptools_0.9-2  sp_1.2-5        dbplyr_1.2.0   
#>  [9] dplyr_0.7.4     RSQLite_2.0    
```

**Comment by zcrysler** [comment]
Working when logged in as an admin - not as a user with full permissions

**Comment by denislepage** [comment]
Yes, I am getting the same. Narrowing down the problem now.


Seems to happen with get_runs_for_receiver, right on the first batch. E.g. with batchID = 79418

No issue when logged in as admin.

**Comment by denislepage** [comment]
This API call is returning a 500 error. I can't seem to find details in the log that can help.

https://motus.org/api/sgdata/custom/runs_for_receiver?json={"authToken":"xxxxx","runID":0,"batchID":79418}

**Comment by pmorrill** [comment]
I've just noticed this discussion; Is this a recent problem? Have we updated the live server recently? 

I can run a test from here on that specific call, in the next 30 minutes.

**Comment by denislepage** [comment]
Actually, none of the receiver calls seem to work for non-admin users at the moment, not only this specific one. I have figured out the problem, and working on a fix now. We stopped trying to resolve the projectID for each receiver batch, but did not update our script to correctly do the authentication for batchID.

**Comment by pmorrill** [comment]
They seem to be working ok in my test environment, which has the same java code. Is this something in the views? I don't really follow....(but trust you are on top of it)

**Comment by denislepage** [comment]
The problem was in validating the batchID when calling runs for receivers, since all batches were now returning projectID = 0. I changed the SQL being used for validating the batchID. I pushed a change earlier to sandbox and that fixed the issue.

I had to resolve the http jar issue in order to bring over those changes into beta5. I just pushed beta5 again, and all seems to be working.

I expect to deploy the live branch tonight, after I have removed the old http jars from shared lib. That will also fix a couple other issues that were on hold, like the 2100 parameter limit.

**Comment by denislepage** [comment]
appears fixed now.

**Comment by adamdsmith** [comment]
Working here too. Thanks! Any idea when internet-connected SGs will resume updating daily? The data from those I have access to all stop ~ 7 Sep.

**Comment by denislepage** [comment]
I'm passing the question to John on that.
