### ISSUE TITLE
General issue of missing receiver data

### ISSUE THREAD

**Issue by tabanid** [MotusDev/Motus-TO-DO#170]
Can we do a query on the entire database that compares the motus metaData (as entered by users) and the actual receiver deployments (as processed) to see which receivers haven't made it over? Maybe you are already doing this, maybe there is another way, but some quick-and-dirty check would be useful.

**Comment by jbrzusto** [comment]
There are several things to be done on the sgdata.motus.org and discovery.acadiau.ca servers:
- [ ] ensure every file embedded in an uploaded archive on discovery or sgdata is present in the file_repo
- [ ] ensure every file embedded in a receiver DB on discovery but not present in the file_repo has
  been exported to the file_repo
- [ ] ensure every raw receiver file in discovery's receiver file_repo has been copied to sgdata
- ensure every file in sgdata's file_repo has been processed:
   - [ ] make sure it is listed in the appropriate receiver's DB
   - [ ] make sure the tag_finder run succeeded, and e.g. used the correct paramOverrides
 - [ ] compare the receiver deployment metadata to the file repo on sgdata for each receiver, to look
  for gaps in received files.
