### ISSUE TITLE
CANARIE tasks

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#172]
Here’s a draft list of tasks to finish in the coming few months. I may be missing a couple key items. We should discuss this tomorrow. They are more or less ordered by importance, starting with the highest priorities. We may need to start trying to knock off some of them in basic terms, so they are released sooner, and then revisit them if time allows. I’ve assigned a few of the tasks to individuals for things that are currently in the works or should be soon.

Priorities for CANARIE:

- [ ] Upload tool with tracking of uploaded files and status (in progress): Paul
- [ ] Movebank transfer API (started): Paul/Catherine
- [ ] Data request tool (requesting user project permissions for tags based on various search criteria, such as species)
- [ ] Timeline plots showing receiver activity vs. deployments and gps locations (in progress)
- [x] CANARIE API (grant requirement): Paul
- [ ] Apply data filtering rules into database, and use them to filter public outputs, and share with R package: Zoe (for now)
- [x] Translation of Motus R Book, application, etc.
- [ ] Sensor registration (from a file provided by SG, depending on John’s progress with this)
- [ ] Build database structure to host modeled data (e.g. position and error). Anything preliminary we can try to populate this with? Tara?
- [x] User survey

Other tasks

- [x] Receiver map: change to a proper WMS map server (moot: Jeremy found a way to speed up the map sufficiently for the near future)
- [x] User acceptance of the collaboration policy upon login. (a prototype is on sandbox)
- [ ] Tracking Tool filtering options - setup ways for users to identify bad tags, runs, etc., so they are flagged in the main database as suspect, and remove them from the public view
- [ ] Plots showing signal strength vs. time for any tag/antenna combination.

Anything I missed?

**Comment by Hussell** [comment]
4. from #131

**Comment by Hussell** [comment]
Plots showing signal strength vs. time for any tag/antenna combination.

**Comment by StuMackenzie** [comment]
User acceptance of the collaboration policy upon login.

**Comment by cjardine-bsc** [comment]
Probably can be closed in favour of new task-specific issues?
