### ISSUE TITLE
SG-1315BBBK0085 returning different data with tagme() by project vs receiver

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#175]
tagme(92, new = TRUE, update = TRUE) returns data that is missing detections between May 17 - Jun 12, and July 3 to july 26 2017

tagme("SG-1315BBBK0085", new = TRUE, update = TRUE) returns detections for this whole period.

All detections in this period are from tags registered to project 92, so they should be showing up in both databases.  Hourly plots show continuous, processed data for that period: https://sgdata.motus.org/download/92/SG-1315BBBK0085-2017_GuelphBARS_unregistered_deployment_hourly_tags.png

**Comment by denislepage** [comment]
I would need some examples of batchID’s, runID’s or hitID’s that refer to the missing records, and/or some row counts for each table to try to narrow this down.

As far as I can tell, there are 4 batches that relate to this receiver in project 92: 108318-108321.

I am seeing 38997 runs (289,732 detections, I think?) that refer to tags from project 92 in these 4 batches, and 118,198 runs (292,419 detections) over for these 4 batches across all tag projects.

**Comment by zcrysler** [comment]
Some examples of data that's missing when tagme() is run for project 92, that ARE present when data is run for SG-1315BBBK0085:

batchID 108318, runID 20587771, hitID 283569629
batchID 108320, runID 20675149, hitID 284872363

The below two detections are also missing, they're the same tag at the same time on the same antenna - this is a BARS colony that was tagged so lots of detections and possible aliased tags, it looks like this happens a lot on this receiver.
batchID 108318, runID 20591736, hitID 283591567
batchID 108320, runID 20675382, hitID 284873203

**Comment by denislepage** [comment]
Found it. There was a bug in the import code from sgdata.  Data is being imported in batches of 10,000 from sgdata, but any subsequent imports of the same batch was missing a key step necessary to make the data available to users.

We may need to recommend to users that they reload their project files. I think I have my code fixed up, but I still need to push it to the server, and also clean up the data left behind. I’ll see if there is a list of projects that would be impacted, but I think it will be any with data for the last several weeks.

Damn. Good catch though.

**Comment by denislepage** [comment]
I have finished applying the changes. The new data should be correctly linked moving forward, but we will need to check again in a couple days.

There were 111 projects affected by this problem, but “only” 2.3 million hits, with some being presumably disproportionally impacted. We should probably confirm that all is working before advising all users to reload their data.

**Comment by zcrysler** [comment]
So should I try downloading this project again now, or do I need to wait?  What other projects were affected?  Project 92 is massive, it took me almost a full day to download that file, and I had to keep running tagme as I was getting timed out, so spot checking with smaller projects would be better.

**Comment by denislepage** [comment]
Pretty confident it's fixed, since I can see them now in the view.

There are no other way to know for sure to try it though. It may be faster for me to try from here.

Mostly need to ensure that it's also working for newly imported data. I should know within 1-2 days as soon as new data comes in with more than 10000 detections.

**Comment by zcrysler** [comment]
Working now for project 92, all detections are there
