### ISSUE TITLE
tag registration

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#177]
I think it could be useful to have a slightly more friendly way of registering tags, that would look a bit like this:

https://sandbox.motus.org/data/tagupload.jsp 

The idea would be offer to package the individual wav file(s) into a zip file along with a text manifest that we create ourselves following these specs:
https://sensorgnome.org/VHF_Tag_Registration

People could then submit a zip file that we could quickly check for a few criteria (e.g. whether it contains a manifest) before writing to the NAS, or we take the input from users and create our own zip file with the properties into a manifest.

Once you’ve uploaded your files (or maybe before, if we can get the list of filenames before the actual upload), we could build a table of file names, and allow people to confirm their tagID’s and frequency. We’d assign the tagID if they followed the naming convention, or ask them to enter the tag ID’s manually, if they didn’t (?).

I don't think this would be too complicated to do, even though it replicates some of the validations done in sgdata. I find the idea of a creating manifest file somewhat tedious and error-prone.

**Comment by StuMackenzie** [comment]
even easier if we just get Lotek to do it. We should revisit that discussion. The hold up was an efficient 'package' or mechanism for them to do so. Perhaps we design this to suit mass registration by manufacturers instead of catering to users.

**Comment by denislepage** [comment]
I’d be all for this.

We should work with Lotek and CTT to sort the details out. Whether we get them to submit wav files and manifest files, or rely on them to figure out the details we need. For Lotek tags, we may want to pursue the first option. We’d have to discuss with CTT and sort out what we need, the level of precision required, etc. (period, frequency, etc.)

Maybe we hold off on making the user improvements until we can sort this out.

**Comment by StuMackenzie** [comment]
David is on vacation next week, but I'll bring it up with him when he's back.  I'd rather not start that conversation while he's away, but it fits in well with other discussions we're having (aggreement, tags, etc., FedDev, etc.)

**Comment by denislepage** [comment]
I view this more as part of CANARIE #2, though we can start discussing.
