### ISSUE TITLE
antenna port -48

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#178]
We should understand the implications of changing the ant values in sg_runs (see below) on the Motus side. As a minimum, we will need to update the sg_runs table to change all ant=-48 for ant=0.

The runs have values port = 0, port - 1, and port = -48 (plus positive values). I can't remember what port 0 and -1 stand, but I believe that one of them is the spliced antenna port on Lotek units.

There are no port -48 or -1 in sensors_antennas, so this I think this change is limited to the detection data, and not the metadata. There are however a few port 0.

- [ ] receiver deployment interface? 
- [ ] R deployment view?
- [ ] elsewhere?

Changing the existing Motus data files would be trickier, as all projects with tags detected on these units would be impacted.

Paul, if you can confirm that changing the port from -48 to 0 in sg_runs will have no impact, I can run the update.

From https://github.com/jbrzusto/motusServer/issues/364 

due to tag finder bug: antenna A0 is being recorded as -48, rather than as 0.

    fix tag finder
    set antenna field to 0 for 3728 records in runs table of master DB where it is -48
    set antenna field to 0 for records in runs tables of these receiver DBs where it is -48:
        Lotek-279
        Lotek-280
        Lotek-384
        Lotek-370

**Comment by pmorrill** [comment]
Changing the port number in the sg_runs table should have no impact. That field is not used for filtering or sorting: it is just passed through to the client.
