### ISSUE TITLE
add CANARIE api to ant build

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#180]
Paul: I have updated the platform api context today, so that it includes placeholders for the 
required functions. Several of the responses are just redirects to pages on the motus.org 
main site, and we will have to review the content for suitability.

The canarie api should be part of the daily deployment again.

In fact, I am not sure that we ever deployed it in the past. According to specs, it has to sit at 
this url:

https://motus.org/platform

and of course, our sandbox version should deploy to:

https://sandbox.motus.org/platform

**Comment by Hussell** [comment]
Done on sandbox. Since there's nothing in the current beta branch or live branch to deploy, nothing has changed there.
