### ISSUE TITLE
ambig tags not pulling metadata in alltags view

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#182]
Although ambig tags have a motusTagID in the alltags view, no other tag metadata is carried through resulting in users having to import tag metadata from other tables or the website.

Eg. motusTagID 19128 from project 38 shares an ambigID of -205 with motusTagID 23081 from project 57.  When data is downloaded to project 38, motusTagID 19128 has all deployment metadata included until it's deployment overlaps with the other tag and it becomes an ambig tag.  At that point all deployment metadata for motusTagID 19128 and 23081 is NA.

**Comment by denislepage** [comment]
From what I understand, the problem is with the alltags view, but the appropriate metadata is in the tables, since some of the records are properly linking to their metadata.

Can you check if you have the proper records in tagAmbig, with ambigID = -205

If not, that would explain what you see (but not why the record is missing there).

**Comment by denislepage** [comment]
You should also check the content of the view allambigs for the same (you should see 2 rows there).

I’m downloading the file now. An earlier version seemed to have the ambig records, but I am waiting to load the alltags view to see if the same problem occurs in that version.

**Comment by denislepage** [comment]
Do you have some specific hitID’s that are showing a possible inconsistency?

If I look at the deployment record for those 2 tags, the hit records have missing deployID’s seem to fall outside the existing tsStart-tsEnd period, so it’s not surprising that they are not linked. At least in the cases that I am looking at. I’m also still looking at the old version of the database. The new one is nearly finished loading.

You can confirm, I may have missed some cases where something is wrong in the view itself.

What I found very surprising however was that the tsEnd field was filled up for virtually all tags. Looking at the view for tag metadata, there was a decision made at some point to insert the calculated end date of the deployment in place of an actual date. I only vaguely recall this.

The fact that some of the records are being assigned as ambiguity but that we’ve determined that the tag was probably terminated at the same time suggests that there are discrepancies in the calculations between John’s tagfinder and ours.

I think that if the tagfinder is determining that a tag is potentially active at a certain time, and unless the deployment was “actually” terminated with a known date, I think those detection records should be linked to the deployment, even past our calculated date.

We need to be able to discriminate what is the basis for the tag end date, or potentially simply ignore entirely the end date in linking the records in the view.

**Comment by denislepage** [comment]
Data finished downloading.

tagme didn’t bring the metadata for 23081. Maybe this is what you are referring to.

I’m not sure if it is supposed to in the current motusClient code (e.g. if ambig tags from other projects are included in the metadata requests). I’ll have to check.

**Comment by zcrysler** [comment]
Ok, so it's the end date that's doing it, I should have caught that.

I think it would be useful if metadata from ambig tags from other projects were included so users know the start date and location to help discriminate potentially ambiguous detections from their own.
