### ISSUE TITLE
View all-time receiver function appears not to be working

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#187]

**Comment by Hussell** [comment]
It looks like Google has changed the code for markers again, making them even slower than before. We also have more data to display than before. So, technically this is still working, it's just really really slow. I guess it's time to rethink how the receiver map works.

Related to a task in #172 (1st in the "Other tasks" section).

**Comment by Hussell** [comment]
Ok, I was wrong, there was a bug there. Fixed on beta and sandbox.

**Comment by denislepage** [comment]
Beta5 or beta6? We should be able to push to live also.

**Comment by Hussell** [comment]
I need to test on the beta server for a bit. I'll copy the changes to beta5 and the live branch once I'm confident I haven't broken anything in IE or Chrome.

**Comment by Hussell** [comment]
Ok, the fix is in the beta5 and live branches now too.
