### ISSUE TITLE
Bulk tag upload updates

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#189]
We need more options for allowable age and sex fields, currently entering Male, Female, Juvenile etc. is not allowed and returns an error on bulk upload even though these are the options in the dropdown menu.  When you download tag metadata with these fields filled in through the manual drop-down menus, they are filled in with M, F, and juv respectively. Allowable options for sex should be male, Male, M, m, female, Female, f, F, Unknown, unknown; for age Adult, adult, ad, Ad, Immature, immature, imm, Imm, juvenile, Juvenile, juv, Juv, Unknown, unknown

**Comment by cjardine-bsc** [comment]
Okay, I changed the validation proc. You can test when you have a moment.

**Comment by zcrysler** [comment]
Working great
