### ISSUE TITLE
bulk tag upload missing text fragment

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#190]
After successfully uploading a tag metadata file, there's a missing text fragment:

Upload Complete
Your data has been successfully transferred to the Motus Database.
New deployments created:: 59
Text fragment not found in database: (EN) Current_deployments_updated	: 4
You may review your updated tag deployment records on the Tag Management Page.

**Note this tool cannot be used to delete existing tag deployments. Please remove deployments using the Tag Management Page.

Also - the last line about deleting tag deployments needs to be updated to "**Note this tool cannot be used to delete existing tag deployments.  Please contact motus@birdscanada.org if you would like any deployments removed" since users don't have the ability to do this themselves

**Comment by pmorrill** [comment]
Jeremy: this is a puzzle. The text fragment 'Current_deployments_updated' does exist in the sandbox database. See:

https://sandbox.motus.org/data/admin/tx_text?id=740

But when an upload is followed to it's conclusion, the msg Zoe shows above is displayed (the fragment is not being resolved). I've checked for white-space around the code line in the template, which looks like this:

<p>
  <strong>${lang.e('New_deployments_created')}:</strong> ${importResults.inserted}<br />
  <strong>${lang.e('Current_deployments_updated')}:</strong> ${importResults.updated}<br /> 
</p>

(The first fragment resolves and the second does not)

There is something obvious that I am missing here, likely. Any suggestions?

**Comment by Hussell** [comment]
I found a tab in the template. Fix checked in and deployed to beta and sandbox.

https://en.wikipedia.org/wiki/Linus's_Law

**Comment by pmorrill** [comment]
Aha! I get it. I have the 'white-space' detector (mostly) turned off on my merge tool here, so while my local version works ok, the one on sandbox suffered with the undetected tab. Thank-you.
