### ISSUE TITLE
missing a boot session of files from SG-1515BBBK0377

### ISSUE THREAD

**Issue by jbrzusto** [MotusDev/Motus-TO-DO#191]
For this receiver we are missing all files from boot session 15, which [covers June 6 to Sept 9, 2017](https://sgdata.motus.org/status?serno=SG-1515BBBK0377).

The upload by user 2565 on 2017-12-03 had all files from boot sessions 14 and 16, but none from 15, and no `2000-01-*` folders.

Two possible reasons:
  - files were stored in flash storage on that SG for that boot session, because of SD card problems, and were not downloaded, possibly because not visible; if not visible, booting without an SD card 
installed would make them visible (more recent versions of SG software show both internal and SD
card storage)
  - the GPS failed to set the clock for that boot session, so all files are in folders like `2000-01-01` and were not sent to us.

**Comment by zcrysler** [comment]
I'll contact the user and get them to upload this data if they have it

**Comment by zcrysler** [comment]
They believe that the missing data is from when their solar panel was disconnected so they don't think there's any data, although the missing boot session would indicate otherwise.  She thinks she does have some 2000 folders, if she can find them and send them is there a way to get data from them?
