### ISSUE TITLE
Landowner detail text cutting off

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#194]
There's a cutoff for allowable text in the landowner fields which you're able to write past, but then gets deleted on saving. There's no warning or error message so text is getting lost with no warning.  Specifically I was trying to enter too much info in the first and last name fields. There are a number of sites that have more than one contact person, so sometimes I'll enter one full contact for the first name, and a second contact in the last name field.

Can it be made obvious when you've entered too much text?

Would also be useful to either be allowed to have multiple contacts for a site, or if that's too complicated, to have a comment field or something to enter additional details in

**Comment by denislepage** [comment]
I don’t think the landowners info is visible, generally?

The comments field could certainly be made visible to PI’s within their own project.

Denis

**Comment by pmorrill** [comment]
I am now allowing comments on landowner record: this is in sandbox only. See #222
