### ISSUE TITLE
Old .motus files still available

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#195]
Need to delete the "Download Detection Data" link on the tag pages: https://motus.org/data/project/tags?projectID=177

**Comment by pmorrill** [comment]
I noticed hits too - just this morning. It should provide the csv template file, right? That is what it used to do, but somehow it got altered during cleanup of those sqlite links.

**Comment by zcrysler** [comment]
Do you mean the tag metadata csv for bulk upload?  That's available further down the page right above the tag list "Download all tags", so I'm not sure we need it both places

**Comment by pmorrill** [comment]
Yes - I see it now. My mistake.

OK - so do we remove this button that still links to the old sqlite files, or do we leave it and have it take user to https://motus.org/MotusRBook?

**Comment by zcrysler** [comment]
May as well link it to the RBook

**Comment by pmorrill** [comment]
This is resolved in beta6 (and master). As soon as we deploy to live it will be good there as well.
