### ISSUE TITLE
doubly-prefixed filenames sent to sgdata.motus.org/status/process_new_upload API

### ISSUE THREAD

**Issue by jbrzusto** [MotusDev/Motus-TO-DO#197]
I'm guessing this is just from re-trying files, but e.g.

```
545_2018-03-16T20-49-09.103_545_2018-03-16T20-40-24.400_SGdata Sewage Treatment 2018-03-09.zip
```
has the username and (different) timestamp prefixed twice.

Just filing this in case I'm wrong and it actually does indicate a problem.

**Comment by pmorrill** [comment]
Zoe: check the file name John posted above: do you know what it was actually called when you uploaded it from your computer?

**Comment by zcrysler** [comment]
I think this is the full large file I uploaded called "SGdata Sewage Treatment 2018-03-09.zip", jobID 168499.  It looks like the same thing happened to a small subset of that data that I uploaded an hour earlier, jobID 167935, uploaded file was called "proj6_sewagePlant_may6to31.zip".  The earlier uploads to that project from December don't have the double prefix.

**Comment by pmorrill** [comment]
This should now be resolved. It was a by-product of the file naming used to store the '.part' file version during chunked upload.
