### ISSUE TITLE
Server hangs while a job is running

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#202]
This morning a 5-minute long job ran on the beta server (prTaghitsDeployIDNew, 2018-03-29, 10:48:41 to 10:53:58), and during that time all attempts to view pages at beta.motus.org/data/ hung. When the job finished, all hanging requests went through. It was my impression that the whole point of the jobs queue was that long-running tasks would run in background threads without affecting anything else, with the exception of locks on tables in the database which were being written to by the jobs. Do jobs need to occasionally yield to prevent starvation of server threads, or something like that?

Now strictly speaking, this doesn't matter because only the beta and sandbox servers are running jobs, so the live server isn't affected. But I'm worried that our model of how the procedures queue works is flawed. Should we just assume in future that the server can only do one thing at a time? I think we should figure out why this happened, instead.

**Comment by denislepage** [comment]
Made some modifications that makes the prTaghitsDeployIDNew proc much faster. (average time of 451 seconds before change to 2 seconds now!).

There are a couple remaining queue items that are running for an extended period, so we should make sure they are not locking the database tables for that long:

org.bsc.motus.process.ComputeTracks: 320 seconds
EXEC prDataValidation_prL 201 seconds

I added some NOLOCK options to compute tracks in sandbox. That should minimize the risk of locking either sides.

It'd be worth investigating the data validation steps a bit and see which components are running for the   longest. I'm looking into this now.
