### ISSUE TITLE
MoveBank -  discussion questions

### ISSUE THREAD

**Issue by pmorrill** [MotusDev/Motus-TO-DO#205]
In general, I'd like to see info on the responses that Movebank will return after we submit data. 

For example, we'd like to be able to verify a user's Movebank credentials and study ID when one of our users saves it. A possible mechanism would be: we submit an empty 'data' file, with user credentials. If the credentials are invalid, do we see a 403 Forbidden error? If the credentials are ok, do we see some other error, due to the empty / missing data file?

**Comment by denislepage** [comment]
Other things to check with Sarah:

- confirm the list of fields and mappings
- confirm how to best deal with tag metadata or data updates (i.e., receivers locations, updated batches).

Do we have details on the types of error responses we will get under the following conditions:

- study ID no longer exists
- user no longer has permission to submit data to study ID
- others?

**Comment by pmorrill** [comment]
One confusion I have is how we will assign the tag data to the MB studies. The documentation describes an 'Access Permissions' file that must be submitted, with format such as:

login,tag
theo,2234
martin,2211

This seems pretty cumbersome for us. Rather, we'd like to simply associate our data sets with a MB study user, as a whole....not tag by tag. The study account user then assigns access permissions within the MB interface. See my next entry on Data Transmission.

**Comment by pmorrill** [comment]
I think that we'd like to:

a) drop the access permissions file entirely

b) use the curl data transmission post to associate a data file (either detections or tag metadata) with a specific Movebank studyId (and user account) via something like this:

FOR **metadata**:

curl --user "user:pw" -F "operation=add-data" -F "feed=motus/tags" -F "study=48511693942" -F "data=@gps_example.csv" "https://www.movebank.org/movebank/motus-interface"

OR for **detection data**:

curl --user "user:pw" -F "operation=add-data" -F "feed=motus/detections" -F "study=48511693942" -F "data=@gps_example.csv" "https://www.movebank.org/movebank/motus-interface"

(Obviously, the use of 'motus' in two places - as the feed name and also the interface url - is redundant: we'll let MB make those decisions for us)

**Comment by pmorrill** [comment]
In case you don't have a copy: here is the doc I am referencing above.

[movebank_live_feed_provider_manual_201702.pdf](https://github.com/MotusDev/Motus-TO-DO/files/1963856/movebank_live_feed_provider_manual_201702.pdf)
