### ISSUE TITLE
How to deal with incorrect GPS values

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#209]
Question: What's the best practice for dealing with gps values that are thought to be incorrect?  This is specifically referring to an error for project 1 for incorrect deployment location.  There are 2 GPS points that occur within an hour of each other that fall beyond 1000m for a receiver (~10km away), but these points occur right in the middle of a deployment which wasn't moved, and all other GPS hits are correct: https://motus.org/data/receiverMap?receiverDeploymentId=672.  So I'm guessing the GPS unit couldn't get a strong signal for a short period.  

The reason I ask is because the error message says to contact Motus if we're positive the deployment is correct, which I am.  So is best practice to just set this error as ignore - or is there something in place to deal with these incorrect GPS readings in the database?

There are also 50 warnings about gps fixes far from deployment (100m) - in all the cases I've looked at so far, it seems like the gps was just having issues finding a precise location, in many cases you can even see the station on the google map right where we've placed the deployment, so I'm positive the deployment is correct.  Not as serious as being >1000m away, but all of these are GPS issues, not deployment issues, that I'll mark as "ignore" unless there's a way to deal with them in the database

**Comment by Hussell** [comment]
I sent Catherine updated text for the instructions on the data issues page last week, but I think she has a big backlog still. Here's the proposed new text: "Please check that your deployment location is correct. This can also happen if your deployment start and end times are off by enough to include GPS fixes from the receiver when it wasn't at the deployment location. Please check that your deployment start and end times are correct. If you are positive that your deployment information is correct but your GPS locations are consistently incorrect, you may have a faulty GPS unit and should contact us at motus@birdscanada.org."

Note the part that says "consistently incorrect". If it's a transient error, then you should ignore it. We could add a sentence to that effect to the new instructions?

There are some known bugs in the GPS views which cause problems when a receiver is registered to multiple projects or when there are GPS readings from outside any known deployment. Once Catherine lets us know she's fixed these, you should retest these.

**Comment by Hussell** [comment]
Resolved in #377.
