### ISSUE TITLE
Change receiverID to deviceID on error page

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#211]
Receiver ID isn't listed anywhere online that I can find, instead the receivers page and deployment pages list device ID.  Can we switch the identifier on the error page to be deviceID for user ease?  

Eg. working on detections outside of receiver deployment for receiverID 424, it brings me here https://motus.org/data/receivers/edit?projectID=1&id=424, but the only receiver identifier on that page is deviceID 350

**Comment by denislepage** [comment]
The deviceID is listed on the page you link below, but not the sensorID.

deviceID is unique to a hardware device.

Each registration to a project creates a new sensorID.

The sensorID is the one that is part of the URL in this case (424). It would be a good idea to add this number to the display, but I would also keep deviceID. They serve different purposes, though I understand that it can be confusing for users, and the names aren’t necessarily the best fit (those concepts have evolved over time, so we’d likely name them differently if we had a chance to start over).

**Comment by Hussell** [comment]
I'm a little confused about which page(s) you're referring to. Would you please provide a link to the error page (or a copy of the text) where the confused terminology appears?

**Comment by zcrysler** [comment]
So the issues page: https://motus.org/data/issues?id=1, under the error "Detections Outside of Receiver Deployment" says:
Receiver ID: 1282, number of detections: 2055, from 2015-03-25 14:31:02 - 2015-03-25 15:15:17

When I click on the edit button for that issue I get brought to the deployment page: https://motus.org/data/receivers/edit?projectID=1&id=1282, and nowhere on that page (other than the url) does it have the number 1282.  Similarly, on the receivers page:https://motus.org/data/project/recvs?projectID=1, it doesn't have the 1282 identifier.

So there are two issues:
1) on the issues page the identifier is called Receiver ID, but really it's referring to sensorID - for simplicities sake they should be called the same thing if they are the same thing
2) if the identifier on the issues page is going to remain as sensorID, then the sensorID should be present on the receiver and deployment page to help users track down issues.  Alternatively the issues page should just list the deviceID which is present on the receiver and deployment pages.

I'm not picky on which value gets used, but we've now got users having to understand serial number, sensorID/receiverID, and deviceID, it all gets a bit confusing.

**Comment by zcrysler** [comment]
I'd like to revisit this issue, I was trying to figure out an error backwards - I had made a correction to a receiver deployment which I expected would resolve a receiver error, then I reran the data validation.  However as the project I was working on had a large number of errors I wanted to search the issues page to see if the receiver in question was still coming up as an error.  But since the receiver deployment page (https://motus.org/data/receivers/edit?projectID=10&id=2474) and the receivers page (https://motus.org/data/project/recvs?projectID=10) only show the deploymentID and deviceID, there is no way to find the receiverID/sensorID which is the only identifier on the issues page (https://motus.org/data/issues?id=10).  To sort this out I had to look in the database which isn't an option for users. As far as I can tell the alltags, recvDeps, and recv tables within the .motus file users can access does not contain the receiver/sensorID - only the deviceID and the serial number.

Can we please change the identifier on the error page to be the deviceID OR show the receiverID/sensorID clearly on the receiver and receiver deployment page.

**Comment by cjardine-bsc** [comment]
The user, to my knowledge, doesn't often see the sensor_id. I think that's a concept that is fairly restricted to the database. The R-views all return the Device ID. 

So, I think that I shouldn't be reporting the sensor ID in this error, and should be reporting the Device ID instead, since it seems like that is what we're listing everywhere else. 

I've changed all the errors that had sensor id to instead report device ID.  That should resolve this I think?

**Comment by zcrysler** [comment]
Yes, that clear everything up, thank you!
