### ISSUE TITLE
bulk tag upload

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#214]
a user for project 22 is having issues uploading bulk tag metadata.  They sent me the file and I'm having the same problem:

Every row is getting the error "You have entered a start date in the past without providing a species. You may either enter a future start date or populate the species column. If you're not yet ready to provide this data you may omit this deployment from your upload template.", and the warning "'Species Fields' does not resolve to a valid species ID. Please consult the Motus species list.", however the speciesName column is entered as "Passerculus sandwichensis princeps" which is in the species list, I also tried entering "Savannah Sparrow (Ipswich)" which is also in the species list.  Also, when I download her existing metadata there are speciesName variables filled in as "Passerculus sandwichensis princeps" - so why can't anything be updated with this species?

I can send the file if that would be helpful

**Comment by pmorrill** [comment]
The 'concat_species_name' generated in the proc should be 'Passerculussandwichensisprinceps', and a query reveals that this species record does exist in our lk_species table:

SELECT * FROM [motus].[dbo].[lk_species] where concat_scientific_name = 'Passerculussandwichensisprinceps'

Catherine will have to dig in a bit deeper.

**Comment by cjardine-bsc** [comment]
Sorry, already fixed and tested outside of github. Issue can be closed.

Catherine Jardine
Ph: (604)-350-1972
www.birdscanada.org
