### ISSUE TITLE
Send emails notifications when API registration calls fail

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#216]
Split from #213.

"Paul, could we easily set up email notifications when API registration calls fail? Have them sent to support@bsc-eoc.org for now, or better yet, to motusProjInfo.getErrorEmail()"

**Comment by pmorrill** [comment]
I have added a general purpose notification into the api. At the moment, there might be too many notifications,as all errors result in an email. Probably better than noting. We can discuss throttling it back some.
