### ISSUE TITLE
View all option in Manage sites and landowners

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#221]
View all option in Manage sites and landowners  - for both project sites and project landowners

https://motus.org/data/project/sites?projectID=1&page=1

Also - a link directly to editing landowners from each site within 'project sites' would be much more user-friendly, or a way to search by site within the project landowners page.

**Comment by pmorrill** [comment]
I've made several updates to the landowner mgmt, including 

a) the ability to search by site name;

b) the ability to add a new landowner or edit in existing one from **within** the sites listing page;

This will be in sandbox on next deployment:

https://sandbox.motus.org/data/project/sites?projectID=1
