### ISSUE TITLE
Add 'notes' field to landowner contact details

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#222]

**Comment by Hussell** [comment]
I.e. on 'Edit Project Landowner' pages:
https://motus.org/data/project/landowners/edit?projectID=1&id=277

There's an unused 'comments' column in projects_landowners which is probably intended for this very purpose.

**Comment by pmorrill** [comment]
I have added the comments field into landowner editing, in sandbox only at this point.
