### ISSUE TITLE
Duplicate data in sg_taghits_runs

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#223]
I've been looking at the data in sg_taghits, sg_taghits_runs, sg_taghits_daily, etc., and found a lot of duplicate data.

Example:

select *
from sg_taghits_daily a
where a.tag_deploy_id = 1003
and a.sensor_deploy_id = 3604
order by a.min_ts, a.batch_id;

<table>
<tr><th>device_id</th><th>sensor_id</th><th>tag_id</th><th>sensor_deploy_id</th><th>tag_deploy_id</th><th>date</th><th>batch_id</th><th>min_ts</th><th>max_ts</th><th>n_hits</th></tr>
<tr><td>499</td><td>1469</td><td>10726</td><td>3604</td><td>1003</td><td>2014-08-13</td><td>4599</td><td>1407974280.74</td><td>1407974398.7083</td><td>4</td></tr>
<tr><td>499</td><td>1469</td><td>10726</td><td>3604</td><td>1003</td><td>2014-08-13</td><td>126113</td><td>1407974280.74</td><td>1407974398.7083</td><td>4</td></tr>
<tr><td>499</td><td>1469</td><td>10726</td><td>3604</td><td>1003</td><td>2014-08-14</td><td>4599</td><td>1407974563.8666</td><td>1407974640.5461</td><td>3</td></tr>
<tr><td>499</td><td>1469</td><td>10726</td><td>3604</td><td>1003</td><td>2014-08-14</td><td>126113</td><td>1407974563.8666</td><td>1407974640.5461</td><td>3</td></tr>
</table>

select *
from vwData_taghits_daily a
where a.tagDeployID = 1003
and a.recvDeployID = 3604
order by a.minTS

<table>
<tr><th>motusRecvID</th><th>motusTagID</th><th>recvDeployID</th><th>tagDeployID</th><th>date</th><th>nHits</th><th>minTS</th><th>maxTS</th><th>recvProjectID</th><th>tagProjectID</th><th>accessLevel</th></tr>
<tr><td>1469</td><td>10726</td><td>3604</td><td>1003</td><td>2014-08-13</td><td>8</td><td>1407974280.74</td><td>1407974398.7083</td><td>14</td><td>47</td><td>0</td></tr>
<tr><td>1469</td><td>10726</td><td>3604</td><td>1003</td><td>2014-08-14</td><td>6</td><td>1407974563.8666</td><td>1407974640.5461</td><td>14</td><td>47</td><td>0</td></tr>
</table>

Note how the number of hits (n_hits) are aggregated in the view (nHits).

Here's a query for finding some duplicated batches:

select a.*
from sg_batches a
join sg_batches b on b.motusDeviceID = a.motusDeviceID and b.monoBN = a.monoBN and b.batchID != a.batchID and b.numHits > 0
where a.numHits > 0
group by a.batchID, a.projectID, a.motusDeviceID, a.monoBN, a.tsBegin, a.tsEnd, a.numHits, a.motusUserID, a.motusJobID, a.ts, a.tsMotus, a.batchFilter
order by a.motusDeviceID, a.monoBN

This query shows there are about 3,000 batches with detections that are obsolete - the boot session has been rerun as a new batch, so the detections from the new batch should have replaced the detections from the old batch.

So far as I can recall, almost none of our queries de-duplicate detections, so this is probably an important performance problem. Also, some reruns produced different data, presumably because the tagfinder was improved or had some bugs fixed, so some of the obsolete data is **not** duplicated, but instead just wrong. This may be one source of bad detections being displayed on the tracks map, for example.

I think there is no reason to keep the superseded detection data: all the raw signal files are archived on sgdata.motus.org and the new detections were re-derived from the same files. If necessary we could even go back to an earlier version of the tagfinder and re-create the obsolete detections.

Proposed solution: find batches with the same motusDeviceID and monoBN, and overlapping tsBegin-tsEnd timespans, and delete the detections from the overlapping time period which belong to the batches which were run earlier (batches having smaller ts or tsMotus). Arrange to do this when new batches arrive.

I think it's likely we'll soon fix some bugs in the tagfinder, and we'll need to re-run it on all the archived files and replace buggy detections with (more) correct ones.

Thoughts?

**Comment by cjardine-bsc** [comment]
This should be handled by batch filtering. Closing this in deference to #236
