### ISSUE TITLE
Bah�aAsunci�n

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#225]
There were 6 uploads for project 125 on April 30, all but one failed for type "SGfiles", and then log errors of 

"Log for 177672

Warning: these 1 files are empty:
   Bah�aAsunci�n-3214BBBK8648-000158-2017-11-30T03-42-14.9960P-all.txt
Processing will continue with the remaining 976 files.

Log for 177675

Error: Error in rsqlite_send_query(conn@ptr, statement): database is locked"

All uploads are for the same receiver: SG-3214BBBK8648, can this data be processed or does the user need to re-upload?

**Comment by Hussell** [comment]
I think I got this to go through. I'm seeing "database is locked" errors in other jobs though, and I haven't figured out what's causing it. Still, I think this particular file does not need to be re-uploaded.

**Comment by zcrysler** [comment]
I'm not sure they went through, there should be data for October 2017 to March 2018, but only February is in the hourly plot: https://sgdata.motus.org/download/125/SG-3214BBBK8648-2016_GuyraPARA_Asunci%C3%B3n%20Bay_hourly_tags.pdf.

Data downloaded through tagme() only goes to 2017-09-02 but hard to know if that's just from lack of detections

**Comment by Hussell** [comment]
Non-UTF8 characters in the filenames for this upload caused the problems. Not fixed yet, but now we know. When the temporary files went into the trash directory, they caused #230, affecting many other projects.
