### ISSUE TITLE
processing paused - unable to submit

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#226]
Some data was submitted for project 1 through the sgdata site: https://sgdata.motus.org/upload/upload-from-computer.php, although it uploaded correctly, it doesn't appear to have been processed.  The upload doesn't show up on the jobs page: https://motus.org/data/project/sgJobs?projectID=1&type=all, and when I go to the sgdata site and click "manage files" I can see the upload but it doesn't have a jobID and there's a button for "submit for processing".  The file is called "TTP May1.7z", when I click the submit button I get an error message.

There are a number of jobs on that site that need to be "submitted" but I'm not able to get them to go through.  Jeremy, can you get these to process?

Looking through the sgdata upload site, this has happened to other projects recently as well

**Comment by Hussell** [comment]
I deleted the file. (Sorry!) Would you upload it again?

There's another big chunk of code here that I'm unfamiliar with. So much to learn...

**Comment by zcrysler** [comment]
So you're not seeing the "TTP May1.7z" file?  When I go to the status page (https://sgdata.motus.org/status) and search by jobID it comes up.  jobID 178996 for TTP and 179005 for Flamborough

**Comment by Hussell** [comment]
Yes, I'm seeing those too, but the errors are different. 178996 is another example of #230, and 179005 I'm not sure yet.

**Comment by zcrysler** [comment]
Similar issue with a new upload, I can see it here: https://sgdata.motus.org/upload/manage-files.php, the file is "North Bay May29.7z" with no jobID submitted May 29, when I click "submit file for processing" I get an error page. The upload doesn't appear here: https://sgdata.motus.org/status

Does the user need to re-upload?

**Comment by Hussell** [comment]
Which user uploaded this? Also, check to see if the file size reported on his/her computer is the same as the file size reported on the web page (1.37 MB, which seems suspiciously small.)

**Comment by zcrysler** [comment]
User ID 2560, the file on his computer was 1,401kb, he re-uploaded and it went through fine.

**Comment by zcrysler** [comment]
Same thing is still happening, file "SCNWA June9.7z" was submitted on 2018-06-09, it doesn't show up on the status page, but it shows up on the old uplaod page with the button "submit file for processing" but the button takes me to an error page https://sgdata.motus.org/upload/manage-files.php?page=4.

**Comment by Hussell** [comment]
Due to a bit of insanity on the part of computer people, file sizes are often reported as if kilo meant 1,024 instead of 1,000 and mega meant 1,048,576 instead of 1,000,000. So 301,274 kB is actually the same file size as 294.21 MB. On behalf of my profession, I apologize.

Assuming User 2560 submitted this, I don't see the file on the server. So, re-upload?

**Comment by jbrzusto** [comment]
I thought https://sgdata.motus.org/upload was no longer needed and had been replaced by something
on motus.org?  Should I remove the link to that page from sgdata.motus.org? (the sgdata file
uploader is an unmaintainable hack that should be retired ASAP)

**Comment by zcrysler** [comment]
I'll re-upload the data now, but I'm worried about the other files on sgdata.motus.org/upload that didn't fully submit. If those users didn't notice then they're probably just assuming their data went through. Ross just noticed that he didn't get the auto email so asked about it, others might pay less attention.

**Comment by Hussell** [comment]
Ok, we discussed the upload pages on the call, and we'll be updating all links to point to https://motus.org/data/project/sgJobs (currently only works if you provide a project ID, ?projectID=1, but this is fixed on beta and the fix will be live soon (by the end of Friday, I guess)). So John, yes, please update those links on sgdata.

Zoe: I'm not sure what can be done about that other than scan through the list of uploaded files for the past few months, check the corresponding jobs on sgdata.motus.org, and re-upload what needs to be re-uploaded.
