### ISSUE TITLE
CANARIE Platform API documentation pages in wordpress missing

### ISSUE THREAD

**Issue by pmorrill** [MotusDev/Motus-TO-DO#227]
Some of the redirects in the platform api are returing 404 errors. We need to work on the documentation for Motus platform under the various categories. Here is the spec:

[Research Platform Support for the CANARIE Registry and Monitoring System.pdf](https://github.com/MotusDev/Motus-TO-DO/files/1971586/Research.Platform.Support.for.the.CANARIE.Registry.and.Monitoring.System.pdf)

The urls are stored in out table adm_platform_api.

**Comment by pmorrill** [comment]
Redirects are stored in adm_platform_api, or can be viewed by following the links below:

https://motus.org/platform/doc
https://motus.org/platform/releasenotes
https://motus.org/platform/support
https://motus.org/platform/source
https://motus.org/platform/tryme
https://motus.org/platform/license
https://motus.org/platform/provenance
https://motus.org/platform/factsheet

Several of these lead to a 404 error. All content needs to be review consulting the CANARIE Platform document posted in previous comment.

**Comment by StuMackenzie** [comment]
Stu's comments/additions with notes

- [ ] https://motus.org/platform/doc
• Given their descriptions - I think the best redirect to use here is https://motus.org/resources/ is the best place to start and the documentation probably detailed enough. One thing missing is:
• Plugin architecture and/or API descriptions, if applicable ??? @denislepage 

- [ ] https://motus.org/platform/releasenotes
•  looks good

- [ ] https://motus.org/platform/support
•  two copies of this page exist @cjardine-bsc 
https://motus.org/troubleshooting/
and 
https://motus.org/troubleshooting-guide/

Even though it needs to be rewritten generally, the latter looks to be the better/more up to date version. Change https://sensorgnome.org/VHF_Tag_Registration link to  "https://motus.org/tag-deployment/"

- [ ] https://motus.org/platform/source
•  404

- [ ] https://motus.org/platform/tryme
• 404
•  I'm not sure we're going to be able to accommodate this aside from browsing public data?

- [ ] https://motus.org/platform/license
•  linked to https://motus.org/policy/ which is probably OK

- [ ] https://motus.org/platform/provenance
**Required** @denislepage @cjardine-bsc 
 • Information about who authorizes releases
• A description of the validation procedures that are completed prior to each release
• A list of documentation that is created as part of the release package
• A statement regarding your policy in dealing with upgrades/patches to any third party
software packages you may be using

- [ ] https://motus.org/platform/factsheet
•  404
• I wonder if linking to https://motus.org/faq/ is good enough for now. **_Also needs to be rewritten_**
