### ISSUE TITLE
Posting french RBook

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#229]
The French R book is compiled and ready to go, is there any reason to hold back or can it be uploaded?

https://github.com/MotusWTS/FrMotusRBook

**Comment by Hussell** [comment]
I've uploaded it to https://beta.motus.org/FrMotusRBook/ . At first glance, I see several places where bits of English remain.

**Comment by zcrysler** [comment]
Can you give me an example?

**Comment by zcrysler** [comment]
Do we have a french Motus logo somewhere? Even on the website it's in english: https://motus.org/?lang=fr

The BSC logo has the French and English name

Changed "R for Motus" and pushed changes to git

**Comment by Hussell** [comment]
https://motus.org/images/motus-logo_FR.png

You're right, we should be using this on the website.

**Comment by zcrysler** [comment]
Perfect, updated with the french logo and pushed to git
