### ISSUE TITLE
The French Motus logo isn't being used on the French part of the website

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#231]
https://motus.org/images/motus-logo_FR.png

https://motus.org/?lang=fr
https://motus.org/data/projects?lang=fr

**Comment by cjardine-bsc** [comment]
Fixed.

**Comment by Hussell** [comment]
I reloaded the headers for the Tomcat section of the site, but nothing changed. (Last link above.) I think https://www.motus.org/stripped-header-2/?lang=fr needs to be changed too.

**Comment by Hussell** [comment]
👍
