### ISSUE TITLE
User not authorized to upload

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#232]
A user attempting to upload to project 169 through the new upload tool can get her data successfully verified, but then she's unable to click "upload file for sensorgnome processing".  Nothing happens when she tries the button, when she refreshes the job list nothing happens, and eventually she gets the message:
"You are not authorized to edit the project with ID = 1."
She's definitely uploading to project 169 since it says "upload files for project 169" at the top of the page.

She's using Linux with Chrome, and ended up finding the other upload page on her own and that seems to be working for her.

**Comment by pmorrill** [comment]
Do you think that we should get the file from her? To test? Or, more likely, this is a Linux browser issue.

I don't like the reference to Project with ID = 1 at ALL. I will look at where that might be coming from.

**Comment by zcrysler** [comment]
She already started upload on the other site and it went through, she's sending me the file via wetransfer but she said it was going to take a few hours. I can send that to you once I have it, the jobID for the successful upload to https://sgdata.motus.org/upload/upload-from-computer.php is 179289

**Comment by pmorrill** [comment]
I have tested this file in various ways - simulating god and bad uploads. The interface seems to be ok. So, I don't believe this is an issue with this specific file. It *may* be related to the Linux platform, but even that seems unlikely.

Do we know how use the upload tool is getting? I'd say we should turn off the old interface, and force people to use the new one. If they have issues, we'll know about it and be able to test those files before the old interface is used solve the problem.
