### ISSUE TITLE
Failed tag registrations - CTRiver

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#233]
Job ID 178353, tag registrations for project 74 have an error for "registerTags", these tags have unfortunately already been deployed, can they still be processed? The user still has the recordings but we need to confirm if we can properly register these tags.  These are tags 373 and 374.

jobID 178362 has another attempt at registering tag 374
jobID 178395 another attempt at tag 374

This project had a lot of issues registering tags, so although these ones have already been deployed I'd like to answer her as quickly as possible so that everything is squared away

**Comment by Hussell** [comment]
I've found a bug and submitted a patch to John. This is my first time doing this, so it may take longer than I'd like to get it deployed. Once that's done I'll retry this job, and if all goes well the tag will be registered.

**Comment by Hussell** [comment]
The patch has been deployed, so this shouldn't happen again.

**Comment by zcrysler** [comment]
Can these jobs be re-run, the tags still aren't in project 74

**Comment by jbrzusto** [comment]
To fix current registrations for this project, we need something like this in the master tag DB:
```sql
delete from tags where tagID in (28759,31896,31897,31898,31899); -- remove duplicates with incorrect BI
update tags set mfgID = replace(mfgID, ".1", "") where tagID in (28759,28747,28760,28743,28755,28756,28757); -- switch to unsuffixed mfgID to avoid confusion 
```

**Comment by cjardine-bsc** [comment]
I have a procedure that merges incorrectly registered tags, and all associated data, into the new correctly registered tag and removes the old tag.

Zoe can send me the pairs of tags and I'll run that in the master database.
