### ISSUE TITLE
Registering and testing a tag on the same day doesn't work due to metadata being cached for 24 hours

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#235]
Project 168 was doing a tag test - tag attached to a balloon filled with water - on May 2nd, around 9-11am EDT.  They could see that the tag was being picked up on SG-4005BBBK4150 on the web interface, but there are no detections during that time on the hourly plots or through tagme() although the antennas seem to have been working fine and data looks like it was processed normally.

The tag being used was 26315 from project 168.

Is there any way to see if somehow these detections weren't processed or were removed through tagme()?

**Comment by Hussell** [comment]
The deployment in question doesn't show any detections at all on the web interface. https://motus.org/data/receiverDeployment?id=4585

I would say this is yet another example of #217, the big bug we need help from John to fix quickly.

**Comment by zcrysler** [comment]
Sorry - by web interface I mean the live feed they see when their computer is connected to the gnome in the field: https://sensorgnome.org/The_Web_Interface

**Comment by zcrysler** [comment]
User asked again about this issue, I'm not sure it's related to the metadata issue because they just uploaded data that should include detections of tags that they registered on July 27th which was after metadata was correctly syncing no?

**Comment by denislepage** [comment]
I also noticed something probably related to this error in the SG logs.

2018-07-27T16-24-43.641879: Error with call stack saved to /sgm/errors//00195850.rds
No tags found for project 209 with dateBin in 2018-3
createRecvTagDB(projectID, dateBin, isTesting)
stop("No tags found for project ", projectID, " with dateBin in ", paste(da
createRecvTagDB(projectID, dateBin, isTesting)
h(j)

I thought this error was a bit odd given that the tags were in the datanase, but given that the metadata in SG is being refreshed only once a day, and that the tags were only registered today, they don’t seem to be available to the tag finder. I don’t have a work-around at the moment except that detection files can’t be processed on the same day that tags are registered. We can have Jeremy try to re-initiate the run early next week for this one, and see if that works better.

I am slowly catching up on some aspects of the SG server now. I may be able to figure out how to re-run before Monday, but more likely not.

**Comment by zcrysler** [comment]
Ok, so that answers another question I had from a user. They registered a tag to be used as a test, drove around with it about an hour later, downloaded data and uploaded it with 0 detections. I figured they might have been too far away for detections and haven't heard back yet how they did the testing, but it sounds like it's actually the issue you just described.  The tag is 30849, the receivers she uploaded were SG-1814BBBK0371, SG-0414BBBK0236, and SG-1814BBBK0809, all project 25

**Comment by Hussell** [comment]
I'm still waiting for SG-1814BBBK0809 to finish rerunning, but it looks like the tags mentioned in this issue show up on the plots now that the disappearing detections issue has been partially fixed. (It was tag 308**94** for project 25.)

This is still going to be an issue in the future though, so I won't close it for now.

**Comment by jbrzusto** [comment]
Refiled as an issue here:  jbrzusto/motusServer#412
