### ISSUE TITLE
Urgent:Tags uploaded to bogus project

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#245]
A user uploaded tag registrations, but had no project permissions so it was uploaded to project -1.  The file also didn't complete processing.  Can you re-run file "2018 Nano Tag Registration.zip", uploaded on 2018-05-21? there's no jobID, but it's visible here: https://sgdata.motus.org/upload/manage-files.php?page=3.  

When I click on "submit for processing" I get led to an error page.  If you can't re-run please let me know so I can get the user to upload asap.

**Comment by Hussell** [comment]
Which project is this supposed to belong to?

**Comment by zcrysler** [comment]
Ah sorry, that would be useful info, project 40

**Comment by Hussell** [comment]
I found a partial upload by user 654 on 2018-05-21 named "2018 Nano Tag Registration.zip". So, the upload never completed, and there doesn't seem to be a job which I could re-run. So, please ask the user to re-upload.

**Comment by zcrysler** [comment]
will do, thanks!
