### ISSUE TITLE
"mast radial" antenna type does not require bearing

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#246]
Eg. errors for missing antenna bearing https://motus.org/data/issues?id=26#v_sensor_antenna_bearing, lead you to deployment 723 https://motus.org/data/receiver/deployment/edit?projectID=26&id=723.  The only missing bearing is for an antenna type "mast radial" which is omni directional and therefore shouldn't be flagged as missing metadata

**Comment by cjardine-bsc** [comment]
I've added a new column to lk_antenna_type called directional and set it to false for j-pole, omni-mast and omni-whip. I modified the data validation proc to exclude any antenna types that have directional = false from the requirement of having a bearing.
