### ISSUE TITLE
Sample auto emails

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#247]
Below are samples of email confirmations after data/tag uploads:

hank-you for the upload - it has been processed.  Any product(s) are listed here:

  https://sgdata.motus.org/download/191/project_191_2018-2_tag_database.sqlite

Processing Summary:

File uploaded: 545_2018-05-24T18-48-47.671_proj191Tags35_49.zip
Registered 15 tags with motus.

The on-board database for your recent tags is available here:
   https://sgdata.motus.org/download/191

Instructions for installing it on a sensorgnome are here:
  https://sensorgnome.org/VHF_Tag_Registration/Uploading_the_tags_database_file_to_your_SensorGnome

You can see the detailed log here:

   https://sgdata.motus.org/status?jobID=183219

if you log in with your motus.org credentials.

Regards,

The people at motus.org / sensorgnome.org

**Comment by zcrysler** [comment]
Successful data uploads:
Thank-you for the upload - it has been processed.  Any product(s) are listed here:

  https://sgdata.motus.org/download/1/SG-5113BBBK0425-2017_Motus_Cabot_Head_hourly_tags.png
  https://sgdata.motus.org/download/1/SG-5113BBBK0425-2017_Motus_Cabot_Head_hourly_tags.pdf
  https://sgdata.motus.org/download/1/SG-5113BBBK0425-2017_Motus_Cabot_Head_hourly_tags.rds

Processing Summary:

File uploaded: 545_2018-05-24T21-27-55.768_Cabot Head 2018.zip
Will run tag finder on 39 receiver boot sessions


You can see the detailed log here:

   https://sgdata.motus.org/status?jobID=183279

if you log in with your motus.org credentials.

Regards,

The people at motus.org / sensorgnome.org

**Comment by zcrysler** [comment]
Tag upload with processing issue:

Thank-you for the upload - it has been processed.  Any product(s) are listed here:

  https://sgdata.motus.org/download/40/project_40_2018-2_tag_database.sqlite

Processing Summary:

File uploaded: 545_2018-05-23T15-40-34.583_proj40tags.rar
Registered 1 tags with motus.
Warning: another 2 tags failed to register
Warning: 1 tags had no estimate of BI error;
their registrations might be faulty

The on-board database for your recent tags is available here:
   https://sgdata.motus.org/download/40

Instructions for installing it on a sensorgnome are here:
  https://sensorgnome.org/VHF_Tag_Registration/Uploading_the_tags_database_file_to_your_SensorGnome



You can see the detailed log here:

   https://sgdata.motus.org/status?jobID=183110

if you log in with your motus.org credentials.

Regards,

The people at motus.org / sensorgnome.org

**Comment by Hussell** [comment]
Is there a motus.org URL to view a job's detailed log? It looks like that's the only link in these emails which could be updated.

**Comment by zcrysler** [comment]
There's no motus.org URL, just the https://sgdata.motus.org URL.  But the motus.org URL brings up the same page.  I noted here https://github.com/MotusDev/Motus-TO-DO/issues/248 that it would be useful to have some more links on motus.org which you can already access through the sgdata.motus.org status page.
