### ISSUE TITLE
Motus upload page

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#248]
One thing that might be useful to add to the upload page, is a link to the status page for the specified receiver, ie. https://sgdata.motus.org/status?serno=SG-1614BBBK1968, I find it useful to be able to see all the date folders that have been uploaded.  That way if the hourly plots are missing dates, I can see if it's due to lack of data or some other reason.  You can get to that on the status page (https://sgdata.motus.org/status) by clicking on the serial number once you have the job open, but it's not obvious, and those links aren't available when you click "view log" on the Motus uplaod page https://motus.org/data/project/sgJobs?projectID=1

**Comment by pmorrill** [comment]
I have added a link as suggested, to the 'view log' tool, where receiver data has been processed and plotted. It is in the sandbox only: take a look (after tomorrow's build) and see if it helps.
