### ISSUE TITLE
unpackArchive Error

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#252]
jobID 184602 failed to process on the step "unpackArchive" with the error "file = /sgm/queue/1//00184602/upload/3167_2018-05-31T20-11-25.804_Pepita 2.rar"

Can it be rerun, or do we need a re-upload?

**Comment by Hussell** [comment]
I tried unpacking that archive, and got some files (which were processed), but a checksum error at the end. So this file should be re-uploaded.

**Comment by zcrysler** [comment]
She uploaded again, but with the same error, jobID 184694

**Comment by Hussell** [comment]
The file sizes of the two uploads were different. More data was successfully unpacked and processed from the second file, but it eventually ran into the same sort of error. So, try uploading again.

What dates are supposed to be in this file? 2018-03-04 to 2018-03-11 were successfully unpacked from the second file.
