### ISSUE TITLE
a tale of two queries

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#254]
I discovered that we have two queries that are doing the same thing. 

vwSpeciesList and vwSpeciesID both return the list of 169 species motus tags have been deployed on. 

Sorry about this, from the style of the two queries one is mine and one is Denis's. Looks like I made one not realizing that Denis already had. 

I'm going to remove vwSpeciesID from sandbox. Jeremy I'm assuming that the species list in the admin tools references vwSpeciesList. We can keep an eye out for anything that breaks on sandbox, just in case.

**Comment by Hussell** [comment]
The species list in admin references vwBase_tags_deployments_basic or vwData_tags_deployments_basic depending on the viewer's status. It was originally going to be visible to everyone, so it uses access levels. Right now it's only visible to admin users, who can see everything, but the full code is still there. I probably wrote the query before vwSpeciesList was created.

There are no references to vwSpeciesID in the code, so it should be safe to delete it.

**Comment by cjardine-bsc** [comment]
Cool. It has been vanquished.
