### ISSUE TITLE
SG-3F8CRPI32CF2 missing data

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#257]
Although there are data files uploaded for each day between 2018-04-30 and 2018-05-14 for SG-3F8CRPI32CF2 (https://sgdata.motus.org/status?serno=SG-3F8CRPI32CF2), the hourly plot shows a gap in data for that period: https://sgdata.motus.org/download/48/SG-3F8CRPI32CF2-2017_NE-Motus_Bucktoe%20Preserve_hourly_tags.png

Was this data not properly processed, or did something go wrong with the receiver? Project 48

**Comment by Hussell** [comment]
I've rerun this receiver, and the gap is gone.
