### ISSUE TITLE
Project 145 Lotek potentially unprocessed files

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#258]
There are a number of Lotek receivers for project 145 where I'm not sure if the data was fully processed. For example Lotek-D000452:
- the hourly plot is blank: https://sgdata.motus.org/download/145/Lotek-D000452-2017_KIWA_BAH_MI_Red%20Oak_hourly_tags.png
- the receiver timeline shows all ports are being detected up to 2017-07-29: https://motus.org/data/receiver/timeline?id=2126&year=2017
- when downloaded through tagme() I get detections between 2017-05-08 to 2017-07-27
- the status page for that receiver shows that there are data files for 2017-05-01 to 2017-11-14: https://sgdata.motus.org/status?serno=Lotek-D000452

So since there are data uploads into November, was the receiver not working properly after July 29th, or is there a processing issue, or is there a plotting issue with both the hourly and receiver timeline?

Similar issues with Lotek-D000453, Lotek-D000454, Lotek-D000456, Lotek-D000457, Lotek-D000458, Lotek-D000459, Lotek-D000460, Lotek-D000461

**Comment by zcrysler** [comment]
Update - user just uploaded a bunch of 2018 data for receivers in this project which seems to be having the same issues. jobID 185665, userID 2458

**Comment by Hussell** [comment]
For the receivers which are showing no data in the plots, no new batches have been exported to the motus.org database, despite what the log says. (E.g. Lotek-D000452, Red Oak, job ID 185675.) Other receivers in this upload appear to have been processed and exported correctly. (E.g. Lotek-D000593, Washington Oaks.)

**Comment by zcrysler** [comment]
Ok, so how can this be resolved? This was an issue dating back to 2017 data, not just the most recent upload from yesterday.  I can see on the receiver timeline that there are gps hits up to July 29th 2017 https://motus.org/data/receiver/timeline?id=2126&year=2017, but I can see there are data folders into November 2017 https://sgdata.motus.org/status?serno=Lotek-D000452.

I think you're saying that none of these date folders have made it over to motus, so how can we get them there so that I and the user are assured that all uploaded data that says it's been processed is available?

**Comment by zcrysler** [comment]
I got some raw data for receiver Lotek-D000452, the status page indicates that there's no data for some dates like 2018-05-26 and 2018-05-17, but the raw data clearly has something recorded for those days. So would this indicate that pieces of data aren't making it through the upload? Or is there something in how Lotek receivers deal with data that makes this a (confusing) non-issue?

**Comment by zcrysler** [comment]
The user is asking about this issue again, no detections beyond July despite data uploads, does he need to re-upload all 2017 data?

**Comment by jbrzusto** [comment]
Rerun of project 145 after fixing jbrzusto/find_tags#71:
 - [x] [Lotek-D000461](https://sgdata.motus.org/status?serno=Lotek-D000461)
 - [ ] [Lotek-D000458](https://sgdata.motus.org/status?serno=Lotek-D000458)
 - [ ] [Lotek-D000460](https://sgdata.motus.org/status?serno=Lotek-D000460)
 - [ ] [Lotek-D000455](https://sgdata.motus.org/status?serno=Lotek-D000455)
 - [ ] [Lotek-D000453](https://sgdata.motus.org/status?serno=Lotek-D000453)
 - [ ] [Lotek-D000456](https://sgdata.motus.org/status?serno=Lotek-D000456)
 - [ ] [Lotek-D000457](https://sgdata.motus.org/status?serno=Lotek-D000457)
 - [ ] [Lotek-D000452](https://sgdata.motus.org/status?serno=Lotek-D000452)
 - [ ] [Lotek-D000462](https://sgdata.motus.org/status?serno=Lotek-D000462)
 - [ ] [Lotek-D000454](https://sgdata.motus.org/status?serno=Lotek-D000454)
 - [ ] [Lotek-D000459](https://sgdata.motus.org/status?serno=Lotek-D000459)
 - [ ] [Lotek-D000597](https://sgdata.motus.org/status?serno=Lotek-D000597)
 - [ ] [Lotek-D000602](https://sgdata.motus.org/status?serno=Lotek-D000602)
 - [ ] [Lotek-D000594](https://sgdata.motus.org/status?serno=Lotek-D000594)
 - [ ] [Lotek-D000598](https://sgdata.motus.org/status?serno=Lotek-D000598)
 - [ ] [Lotek-D000604](https://sgdata.motus.org/status?serno=Lotek-D000604)
 - [ ] [Lotek-D000601](https://sgdata.motus.org/status?serno=Lotek-D000601)
 - [ ] [Lotek-D000595](https://sgdata.motus.org/status?serno=Lotek-D000595)
 - [ ] [Lotek-D000606](https://sgdata.motus.org/status?serno=Lotek-D000606)
 - [ ] [Lotek-D000605](https://sgdata.motus.org/status?serno=Lotek-D000605)
 - [ ] [Lotek-D000593](https://sgdata.motus.org/status?serno=Lotek-D000593)
