### ISSUE TITLE
SG-5113BBBK3126 missing data

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#265]
receiver SG-5113BBBK3126 has data uploaded for all of July and August 2017 (https://sgdata.motus.org/status?serno=SG-5113BBBK3126), but the hourly plot indicates there's no data for this period (https://sgdata.motus.org/download/1/SG-5113BBBK3126-2017_Motus_Holiday_Beach_CA_hourly_tags.png), can someone confirm if this is a processing issue or if there's just no data or antenna info for that period?

**Comment by jbrzusto** [comment]
Probably due to a bug in the tag finder's resume option, since fixed.
I re-ran boot sessions 2185 and 2186; results [here](https://sgdata.motus.org/status?jobID=186825).
Yes, nearly a million detections were missed!
