### ISSUE TITLE
Duplicate data project 174

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#267]
I've got data from project 174 with detections that as far as I can tell are identical but have different hitIDs runIDs and batchIDs, all values for all variables are the same (eg. sig, port, runLen, bootnum, etc.), the only difference is that out of 4 nearly identical hits, 1 has gps info and the other 3 have NA for gpsLat, gpsLon, and gpsAlt.

An example set of 4 "identical" detections:

hitID | runID | batchID | ts | sig | motusTagID | gpsLat | gpsLon
-- | -- | -- | -- | -- | -- | -- | --
320489716 | 21329450 | 114529 | 2018-01-19   18:10 | -61.9444 | 27413 | -52.4693 | -69.3849
435321856 | 26477970 | 155265 | 2018-01-19   18:10 | -61.9444 | 27413 | NA | NA
448273679 | 27184398 | 164077 | 2018-01-19   18:10 | -61.9444 | 27413 | NA | NA
449126203 | 27259189 | 164104 | 2018-01-19   18:10 | -61.9444 | 27413 | NA | NA

Can someone take a look at these hits and tell me how they differ? Having all 4 totally throws off any calculation about number of hits at a station, but I don't know which batchID to trust. Is this duplicate data?

**Comment by denislepage** [comment]
These are presumably re-runs that will be removed through the process we discussed recently. Have we only implemented this in sandbox so far?

**Comment by cjardine-bsc** [comment]
yes. this is currently in sandbox only. it's probably okay to deploy to live if that's okay with Zoe.

On Jun 12, 2018 8:57 PM, denislepage <notifications@github.com> wrote:
These are presumably re-runs that will be removed through the process we discussed recently. Have we only implemented this in sandbox so far?


-

**Comment by Hussell** [comment]
Zoe: yes, this is duplicate data. It was brought up in #223, but discussion was all offline.

**Comment by zcrysler** [comment]
I gather this still hasn't been deployed to live? I just re-downloaded the file and am getting the same duplicates

**Comment by denislepage** [comment]
Correct.

**Comment by cjardine-bsc** [comment]
I'll take care of it first thing tomorrow.

On Jun 18, 2018 18:02, denislepage <notifications@github.com> wrote:
Correct.

**Comment by cjardine-bsc** [comment]
I've implemented batch filtering in live. 

The summary tables need to be re-run to remove these batches, that will take a little while, but in the meantime Zoe, you can re-download this data through R and check to make sure duplicate batches are being removed. Batches 155265 and 164077 should disappear. 

Right now there are some duplicate batches that are not being filtered out by this process, this is awaiting some clarification (#236) So you'll still see two batches that look like duplicate hits 114529 and 164104. Still not perfect, but improving!

**Comment by zcrysler** [comment]
I can confirm that batches 155265 and 164077 have been removed

**Comment by cjardine-bsc** [comment]
Okay, I'm closing this one in deference to #236
