### ISSUE TITLE
Triplicate link on user landing page

### ISSUE THREAD

**Issue by pmorrill** [MotusDev/Motus-TO-DO#268]
We have now pointed all file uploads to the same place, which has resulted in 3 separate links on the user landing page, all pointed to the same tool. EG:

https://beta.motus.org/data

'Register Tags'
'Data Upload and Job History'
'Submit detection data'

Seems excessive. Can we coalesce them into one or two? Post preferred change to this and I'll update it.

**Comment by Hussell** [comment]
I would merge the 'Data upload and job history' link with the 'Submit detection data' link, but leave the separate 'Register tags' link. Maybe:
'Register tags'
'Upload detection data'

**Comment by zcrysler** [comment]
Agreed, leave register tags, and merge submit/upload

**Comment by pmorrill** [comment]
This has been updated now in beta and sandbox. We may need to change the tx frag for Submit_detection_data and Submit_detection_data_definition.
