### ISSUE TITLE
Null pointer error when editing a receiver

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#270]
https://motus.org/data/receivers/edit?projectID=64&id=2373

I got there by going to https://motus.org/data/project/recvs?projectID=64, clicking the "undeployed" tab, then clicking "Edit Receiver properties", but this doesn't seem to have anything to do with it not having any deployments.

**Comment by Hussell** [comment]
Traced the cause to the receiver_type columns in sensors and sensors_hash_keys not being foreign keys of lk_receiver_type.

**Comment by cjardine-bsc** [comment]
I've synced the tables and put in a FK
