### ISSUE TITLE
Auto emails

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#271]
I was under the impression that we hadn't started sending confirmation emails to new users yet, but this morning I've got 5 identical messages telling me that delivery to the same recipient failed:
"Delivery has failed to these recipients or groups:
756fgjggk@gmail.com
The email address you entered couldn't be found. Please check the recipient's email address and try to resend the message. If the problem continues, please contact your helpdesk.
The following organization rejected your message: gmail-smtp-in.l.google.com."
This is a fake registration that I deleted and didn't answer, so seems like auto emails are going out, which then begs the question as to why I'm still getting ~10 fake registrations a day. Are some fake registrations happening through beta and getting auto emails?

**Comment by Hussell** [comment]
Correct, the code for confirmation emails is only in sandbox.

Please forward me one or two of these failure emails.

**Comment by Hussell** [comment]
As far as Denis and I can tell, these are password reminders being sent by very old, very obsolete code. We have some cleanup to do to delete this code, but beyond that there doesn't seem to be a bug here. This issue has bumped the cleanup a little higher on my priority list. It's still a fairly large job, but I think I'll probably get it done soon-ish.
