### ISSUE TITLE
R-client detection data access too restrictive?

### ISSUE THREAD

**Issue by pmorrill** [MotusDev/Motus-TO-DO#272]
This is to document our investigation into shifting the R-client's server-side queries, aiming to allow access to detection data via the 'securables' model. The queries currently use the securables approach when delivering meta-data on tags and receivers associated with detections. But, the initial access to batches / runs / raw data appears to be restricted to those data points linked to projects on a 'direct-access' list (ie: user is linked via projects_user table).

As with all things involving 'securables' - the complexity will take some time to sort through.

**Comment by pmorrill** [comment]
R client queries for tag-project data happen via tagme(projectID) calls. These calls get a list of batches, then runs, then raw data. On the server-side each query checks the tag project ID via a MotusUser#isDetectionsViewer call. This function builds a map of project permissions for the user, and if a user is not registered with the project, they are assigned PERMISSION_NONE. See MotusUser#getProjectPermissions(int projectId).

This will have to be replaced. One possibility is to perform a 2nd check if the isDetectionsViewer call return false. The 2nd check would to determine if that project 'data securable' level is set below or equal to the current user's status, as per the general model.

If we take this approach, is a view of some sort appropriate to perform this check? Maybe it has to be done in java code. The inputs are the project ID and the user's status (ie: user / PI / admin). The output is just a true/false. Possibly we already have something that does this? It's been a long time since we meddled with securables.

**Comment by Hussell** [comment]
On the web, I've been doing the following:
If the user is a detection viewer for a project, then query one of the vwBase views (full access).
If the user is NOT a detection viewer for a project, then query  one of the vwData views, using "where view.accessLevel <= @userStatus" to filter out data which needs a higher access level.

To do this for the R queries, a view which includes the access level for each row will have to be created.

**Comment by pmorrill** [comment]
Yes - that is basically how this is handled in the rest of the api (our csv downloads, for example). But here, we are restricting the query to a single (tag) project at a time. Would it not be easier to just ask the project if the detection-data access level is <= the current user status? This can be packaged in a simple func (if we don't already have one) on the ProjectBean, maybe?

Am I missing something here? It has been awhile since I worked in securables.

**Comment by Hussell** [comment]
The procedure for getting the correct access level is a little tricky, and has changed in the past, so I usually try to go through views. There's a view called vwProjectsSecurables which, given a project ID and securable (e.g. 'tags_deployments_basic') will give you the access level, after dealing with default values and expiry dates. The Base and Data views use the project-level privacy flags to decide what to include in each view and how many digits to round off on latitudes and longitudes. In some cases the Data views modify the access level of individual rows based on things like is_test flags, deployment status, etc.

**Comment by pmorrill** [comment]
Agreed - it is complicated. The R-client api uses the vwProjectsSecurables view (via vwR_Metadata_for_tags for example) to return the metadata associated with tag / recv deployments, for the reasons that you wrote above.

But, we made a decision at some point that we would return ALL data points (detections) of all tags on the project, regardless of those subtleties. The **metadata** associated with the detections is subject to filtering based on the views, so metadata for some detection points might not be returned. That leaves those detection points of no use: a point by itself reveals about nothing, without the metadata for the recv deployment.

At this time, I'd rather not revisit the decision to return all detection points (though it probably does need review). Which is why I am leaning towards an approach that does not require we alter the views for batches, runs, hits. Since we know the tag project id (and don't care about the recv project id at this point, because of above), a query for the securable level (and whether the tag project is_private is false) seems all we need. However, maybe Catherine could consider altering the vwR views to incorporate vwProjectsSecurables. The views in question would be:

vwR_Batches_for_tag_project
vwR_Runs_for_tag_project
vwR_Hits_for_tag_project

I really can't decide whether it;'s worth it or not, as opposed to just querying the tag project securable level against the current user status.
