### ISSUE TITLE
Error: Error in gzfile(file, mode): cannot open the connection

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#273]
Job ID 187485 resulted in the above error, the user then re-uploaded the same file and got the message "there were no new files in the dataset, so I didn't do anything" jobID 187497. Can the first job be re-processed since neither of these uploads seems to have gone through?

There are data files up to 2018-06-11, but hourly plot only goes til 2018-04-27

**Comment by Hussell** [comment]
The error was in the final subjob, the one which generates the hourly plots. So everything is processed and exported to Motus - no re-upload or re-processing necessary. I'm looking into the problem in the plotting job now.

**Comment by zcrysler** [comment]
Ok - so can you confirm that there are 0 hits on this receiver? The alltags view in tagme() is empty

**Comment by Hussell** [comment]
I can confirm that the Motus database contains no hits for this receiver in any batch, not just the one from this job.

**Comment by Hussell** [comment]
It looks like John fixed the error, but retrying the job doesn't update the hourly plot. On Motus I can see that the receiver was active from Feb. 1st through April 27th and from May 14th to June 11th. https://motus.org/data/receiver/timeline?year=2018&id=2343

**Comment by jbrzusto** [comment]
I've rerun that receiver.  Is one affected by the period during which the servers were running as root.
Still no hits, but at least plots show up now (you might need to refresh your page).

**Comment by zcrysler** [comment]
Great - thanks John and Jeremy!
