### ISSUE TITLE
add frequency to antenna records in deployment

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#276]
This should probably be based on a lookup table. I've created a new one, lk_frequency, in sandbox. 

Paul, can you add this field as a drop down in the antenna section of the receiver deployment page?

**Comment by jbrzusto** [comment]
This should probably be a project-wide property, not for a specific receiver.  Receivers usually
record what frequency they are listening on.  The only reason to have it is to handle cases where
they don't.  I'm not aware of any project using more than one frequency, at least for funcubedongles
and rtlsdr.

**Comment by jbrzusto** [comment]
Also, this is just one special case of a parameter override, for which an API has already
been proposed here:
https://github.com/jbrzusto/motusServer/blob/master/inst/doc/status_api.md

**Comment by denislepage** [comment]
Does that currently allow to have different antennae at different frequencies on the same receiver?

**Comment by jbrzusto** [comment]
No.  Is anyone doing that?  If so, why?

**Comment by StuMackenzie** [comment]
The projected reason to have more than one frequency on a receiver is to accommodate CTT/Cornell dongles when we start tracking their use, at least on the metadata side of things for starters.

**Comment by jbrzusto** [comment]
Okay, separate issue. The tag finder isn't doing anything with Cornell XCVR data, and even if it did,
the frequency of those Cornell XCVRs is fixed; all we get from them are putative tag IDs.

**Comment by denislepage** [comment]
On the call today, we decided to hold off adding the frequency to the web interface.

**Comment by pmorrill** [comment]
I am removing it from the sandbox, where I had already added the edit fields .
