### ISSUE TITLE
Clicking on the logos in the French header sends you to the English sites

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#278]
Clicking on the Motus logo should send you to motus.org?lang=fr
Clicking on the BSC logo should send you to www.birdscanada.org?lang=FR

**Comment by denislepage** [comment]
@cjardine-bsc reviving this old one. Could you make the header link to the French version of the birdscanada page?

**Comment by cjardine-bsc** [comment]
Done on the wordpress pages.
