### ISSUE TITLE
no tag detections proj 147

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#279]
A number of tags were deployed by project 147 near SG-1914BBBK0916, but the most recent data upload shows 0 detections: https://sgdata.motus.org/download/147/SG-1914BBBK0916-2017_SNPL_Mound%20Lake%202_hourly_tags.png. The user is expecting all tags to be detected regularly at this station.  There could be a few issues:

- some of these tags (she thinks about 5) were deployed BEFORE she submitted the registration package, so I assume to get those detections the station will have to be re-run
- most deployed tags were put out AFTER she submitted the registration package, leading me to believe there's something else going on here.
- the 2018 tags were registered on 2018-06-18, so I'm not sure if the recent metadata issue would be behind these tags not being picked up
- some of the tags were registered in 2017 so the recent metadata issue shouldn't affect this

Hoping to at least rule out if this is a potential receiver issue that the user needs to deal with ASAP or if we can resolve any issues on our end

**Comment by jbrzusto** [comment]
I reran that receiver, and a number of tags are now showing up.
Yes, this is part of the general problem of registered tags not having
been searched for due to a break in metadata syncing between servers.

**Comment by zcrysler** [comment]
Perfect, glad it's not a receiver issue, thanks!

**Comment by denislepage** [comment]
Are we now ready to re-run more globally for all affected receivers. Jeremy mentioned a couple days ago that he seemed to have lost the ability to initiate a re-run using the method he used before? Is there anything else pending that needs addressing?

There’s also an outstanding question as to how we can identify deprecated batches. Ignoring the few cases where ts for batches with the same deviceID + monoBN don’t perfectly line up, I am not yet clear how partial batch re-runs that used the --resume option can be identified within the database? See #236

**Comment by jbrzusto** [comment]
Jeremy:  can you please file an issue against jbrzusto/motusServer for "lost the ability to initiate a re-run"
And no, we're not ready; I need to resolve jbrzusto/motusServer#407.  I'm going to write up a milestone on what's needed to get things moving again; this thread is getting
too unwieldy.
