### ISSUE TITLE
issues page: Overlapping Tag Deployments (TagID)

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#281]
I think this warning on the issues page could be made more clear. The instructions say "Please confirm the deployment dates for both deployments are accurate" but it's not easy to see what the pairs of overlapping deployments are: https://motus.org/data/issues?id=38#v_tag_overlap_deploy_prop. Could we list the pairs together - or if it's because it's in a different project then I think we need another line in the instructions that states this and tells users to just confirm the deployment dates for their tags (rather than both deployments)

**Comment by zcrysler** [comment]
Can I make another suggestion? It shows the deploymentID for the second tag in the pair but not the first, can we get both in there?

**Comment by cjardine-bsc** [comment]
As you command :) 

You stay closed now ya hear?
