### ISSUE TITLE
Issues page: Invalid tag location coordinates

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#282]
A user has said that displaying the motusTagID rather than the deployment ID would be more useful for this error as going to the projects tag page only shows motusTagID. Could we add motusTagID or replace deploymentID? Although when clicking the edit button, or doing bulk uploads it doesn't matter, it is true that trying to navigate the tag page with only deployment ID is time consuming

**Comment by Hussell** [comment]
I think I don't fully understand the problem on this one. Why is the user attempting to navigate the project's tags management page when the "Edit" link goes directly to the tag deployment page where the latitude and longitude can be fixed?

**Comment by zcrysler** [comment]
Yes and I pointed that out to the user, but they still said it would be much easier to enter data if they had tagID rather than deploymentID. It's possible they're entering missing metadata through the tag page which only shows tagID and not deploymentID. 

Sometimes to assess whether to fix an issue or ignore it it's easier to see the bigger picture in the tag page than through each individual issue. If there's an argument not to include tagID here then that's fine, just reporting a user request/issue

**Comment by Hussell** [comment]
So if we added a "View" link which went to the tag edit page, the problem might be solved. Wish I knew more about the user's workflow.

Example of this issue: https://motus.org/data/issues?id=3#v_tag_deploy_coordinates
Example of the "Edit" link: https://motus.org/data/tag/deployment/edit?projectID=3&id=13884
Where a "View" link should go?: https://motus.org/data/tags/edit?projectID=3&id=26483

**Comment by zcrysler** [comment]
I think it's more that they want to be able to see the tagID without having to click through other steps, I don't think the view link would provide much more information since you can get the tag id by clicking on the existing "edit" link

**Comment by cjardine-bsc** [comment]
That's an easy enough field to add to the description. 

They should be included now, once the validation is re-run for the project.

**Comment by Hussell** [comment]
Ok. I would have said no until we understood why.
