### ISSUE TITLE
receiver re-runs project 147

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#283]
Can we re-run receivers from project 147? Their tags aren't showing up because of the metadata issue, they want to see the data to ensure the stations are running properly:
SG-1914BBBK0851
SG-1914BBBK0935
SG-1914BBBK0894
SG-1914BBBK0819
SG-1914BBBK0887
SG-BB71RPI31CE1

**Comment by Hussell** [comment]
I reran the receivers for project 147, but all detections disappeared. I'll be looking into why this sometime in the next few work days.
