### ISSUE TITLE
project 197 detections

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#286]
Project 197 is tagging swallows and the receivers are next to where the tags were deployed, user expects constant detections at these stations, when she's at the receiver she can see that there are constant pulses coming through on the live feed.

Receiver SG-1614BBBK1911 shows detections of 5 birds as expected: https://sgdata.motus.org/download/197/SG-1614BBBK1911_1-2018_TaylorSwallows_unregistered_deployment_hourly_tags.png

But other receivers don't show any detections, eg. SG-1614BBBK1922:
https://sgdata.motus.org/download/197/SG-1614BBBK1922-2018_TaylorSwallows_Wells2_hourly_tags.png (only detection is a test tag when station was setup)

and receiver SG-2313BBBK3402 https://sgdata.motus.org/download/197/SG-2313BBBK3402-2018_TaylorSwallows_Wells1_hourly_tags.png

Is this related to the metadata issues? Why would one receiver get detections of her tags but not the others?

**Comment by Hussell** [comment]
No, this is not related to the metadata issues. If it were, then rerunning the receivers would show new detections, but rerunning SG-1614BBBK1922 instead caused the test tag detection to disappear.

**Comment by StuMackenzie** [comment]
So this appears to be a similar issue to project 147? 

____________________

**Comment by Hussell** [comment]
Probably the same issue as #283, #235, #217, etc.

**Comment by zcrysler** [comment]
FYI Phil has said that John thinks it's a bug and will look into it
