### ISSUE TITLE
Collaboration policy confirmation

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#292]
I' have made the following changes to the Collaboration policy feature in sandbox.  I will post those shortly. Stu/Zoe should probably revise the language.

- [x] the page is now a stand-alone page separated from the profile (/data/user/policy)

- [x] I have replaced the text and added a checkbox, etc. 

- [x] the button should now rather say "Confirm" or "Save".

- [ ] The error message appearing and message is now tailored depending on whether the user has never accepted the policy, or when his last accepted date is older. 

- [x] Users are now returned to whatever page they were trying to access, or the /data home page by default. 

- [x] The user profile page shows the date at which the policy was last accepted (read-only).

- [x] On the WP page, I have updated the photo labels to include the date when the documents were last modified.

- [x] I have modified the redirection to exclude /data/admin pages from the requirement.

**Comment by zcrysler** [comment]
The language looks clear and concise, the links to the policy and tag fee schedule don't work on sandbox though: https://sandbox.motus.org/data/user/policy

**Comment by denislepage** [comment]
Thanks!

It’s probably not worth posting these on the sandbox, so the links there will remain broken.

I also forgot to mention that once you approve the policy, you have to modify your profile in the database to see the notification again. It’s be worth testing both instances when the date is null and the date is older than the policy date. The interface and language look slightly different. You can also see the text in the fragments if you search for “policy”

**Comment by Hussell** [comment]
I've tested both with and without null in user_properties.policy_accepted_dt. Everything seems to be working as intended.

Will the collaboration policy be updated soon? If not, policy_accepted_dt should be set to a recent date for all users before deploying this to live.
