### ISSUE TITLE
Known duplicate receiver data not processing

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#294]
A recent upload for data from a known duplicate receiver, Lotek-270 in project 64, resulted in an error message: https://sgdata.motus.org/status?jobID=193705, the error is "Error: Error in getRecvSrc(serno, dbdir = dbdir): invalid receiver serial number Lotek-270_1".  I'm guessing the error is because of how these duplicates were dealt with? For reference:
https://github.com/jbrzusto/TO_DO/issues/126
https://github.com/jbrzusto/TO_DO/issues/176

This receiver is currently only active in project 64, but the duplicate from past years is in project 32. Both are listed as Lotek-270, but one of them must have been named Lotek-270_1 somewhere?

**Comment by zcrysler** [comment]
Friendly reminder from me and the user that this is still an issue and they're waiting on data

**Comment by Hussell** [comment]
John, should motusConstants MOTUS_RECV_SERNO_REGEX match Lotek-270_1?

**Comment by jbrzusto** [comment]
Yes, this is now part of jbrzusto/motusServer#417

**Comment by zcrysler** [comment]
Where does this issue stand? It seems like data was processed for this station, but the hourly plot looks like the antenna was never really online reliably, I'm also not sure if this covers all the available data.
