### ISSUE TITLE
Edit receiver properties page - receivers go out of page bounds

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#297]
eg. https://motus.org/data/receivers/edit?projectID=191&id=2573, the receivers box goes outside of the page
<img width="1185" alt="screen shot 2018-07-19 at 6 37 06 pm" src="https://user-images.githubusercontent.com/22080197/42978759-7edfe586-8b83-11e8-8c82-d40bf929b519.png">

**Comment by Hussell** [comment]
There are limits to what can be done here, since the table can contain many rows, but I've removed the useless box around the table and shortened a couple of the table's headers. https://sandbox.motus.org/data/receivers/edit?projectID=1&id=384
