### ISSUE TITLE
sensor gnome file format documentation

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#300]
I have been trying to sort through the file formats generated by sensor gnomes, for our discussion with CTT (assuming they may be able to include Lotek tags in their output of their own receiver). I am putting this here as an issue until we can figure out how to organize our documentation a bit better.

<h3> File structure and file name </h3>

 Taken from https://sensorgnome.org/Download_data_from_a_SensorGnome

On SG, files are organized as follow:

`disk_port7-1/SGdata/000026/2013-06-17/ACON-1012BB012090-000026-2013-06-17T13-11-47.9750Z-all.txt.gz
`

- disk_port7-1:
- the first partition on the disk plugged into USB Hub port 7
- SGdata: the complete folder of sensorgnome data on this disk
- 000026: boot count; data recorded during the 26th power cycle of the SensorGnome; this value increases by 1 after each SensorGnome restart
- 2013-06-17: all datafiles recorded starting on June 17, 2013 UTC.  (some of those files might data from up to an hour into the next day)
- ACON-1012BB012090-000026-2013-06-17T13-11-47.9750Z-all.txt.gz:  horrible filename, with these components: 
o 	ACON: short label for the deployment (from deployment.txt)
o	1012BB012090: beaglebone serial number
o	000026: boot count, as above
o	2013-06-17T13-11-47.9750: timestamp when first record was written to file; Year-Month-Day T Hour - Minute - Seconds
o	Z: timestamp is in UTC, and GPS has already set clock; alternatively P: timestamp is from before GPS set beaglebone clock; may be very wrong (e.g. from year 2000)
o	all:  data from all antennas; if doing acoustic monitoring, this is replaced by '1', '2', etc. according to which USB port the microphone is plugged into
o	txt.gz: this is a compressed text file; if the ".gz" is missing, the file is a partial uncompressed form
-	A new file is initiated every hour or whenever the uncompressed file exceeds 1,000,000 bytes

<H3> File content </H3>

The gz files contain the time-stamped data: individual radio pulses, the GPS readings and the XCVR tags, using the following structure:

**Lotek pulses**: 

Llines prefixed with “p”. Individual pulses (not sure what criteria are used by FunCube to identify pulses, etc.).

Sample:
```
p2,1522973327.9528,4.79,-69.24,-76.16
p2,1522973328.1530,4.626,-68.75,-75.96
p2,1522973328.1725,3.886,-69.42,-76.38

```
Field details:
1)	“p” + USB port number (e.g. p2)
2)	timestamp (0.1 millisecond precision)
3)	pulse frequency offset, in kHz 
4)	estimate of pulse strength, in dB max 
5)	estimate of noise surrounding pulse, in dB max

**GPS readings**

Lines prefixed with G. Usually recorded every 5 minutes by default.

Sample:
```
G,1522974031,47.071905,-70.785236667,-16.5
G,1522974331,47.071903333,-70.78524,-13.2
G,NaN,undefined,undefined,undefined
```

Field details:
1)	G for GPS
2)	timestamp (0.1 millisecond precision)
3)	Latitude (dec. degrees)
4)	Longitude (dec. Degrees)
5)	Altitude (metres)

**XCVR detections**

Time-stamped detections from XCVR (aka "Cornell/CTT" tags).

Sample:
```
T4,1526057517.917,682BEDF1
T4,1526057517.924,2439B3D3
T4,1526071534.21,C507440C
```

Field details:
1) Letter T, followed by port number
2) timestamp (0.1 millisecond precision)
3) 32-bit tag code, provided by XCRV

**Lines prefix with C**
???

Sample:
```
C,1436965482.979,6,0.000006826
C,1427552519.035,0,0
```

Fields:
1)	Letter C
2)	Timestamp (0.1 millisecond precision)
3)	Port number?
4)	???

**Lines prefix with S**

Setup details? Is this being used by tag finder?

Sample:
```
S,946684819.509,3,frequency,151.496,0,
S,946684819.515,3,gain_mode,1,0,
S,946684819.516,3,tuner_gain,40.2,0,
S,946684819.516,3,test_mode,0,0,
S,946684819.517,3,agc_mode,0,0,
```

Fields:
1)	Letter S
2)	Timestamp (0.1 millisecond precision)
3)	Port number??
4)	Descriptor??
5)	Value??

**Comment by jsayers-bsc** [comment]
Has anyone discovered what those lines that begin with "C" or "S" mean or how they are used? I've seen this a few times in downloaded files but it's not clear what the purpose is.

> Z: timestamp is in UTC, and GPS has already set clock; alternatively P: timestamp is from before GPS set beaglebone clock; may be very wrong (e.g. from year 2000

So _that's_ what that is for!

But interestingly, as I look on my own computer, those aren't the only options. In addition to files ending in `Z-all.txt.gz` and `P-all.txt.gz`, I also have files that include T, U, V, W, X, and sometimes Y (yes, and sometimes Y!). The number present in the other letters are all suspiciously similar, and may be related to reboots (at a glance anyway).

suffix | number
-- | --
all files | 477389
P-all | 380179
T-all | 95870
U-all | 55
V-all | 55
W-all | 53
X-all | 53
Y-all | 53
Z-all | 53


Note: most of the detection data on my computer is in archives in online-only cloud storage so not actually present or searchable at the moment, so this is probably just 10% of what would normally be on my computer.

**Comment by leberrigan** [comment]
Every time one of the weird file suffixes shows up, it's always with other files with the other weird suffixes in this order: Z, Y, X, W, V, U, T

This seems to happen each time the device boots up and files are only 1 KB in size. They also always start with a line starting with 'C':
File suffix Z: C,1568053281.319,0,7.86e-7
File suffix Y: C,1568053281.518,1,3.31e-7
File suffix X: C,1568053281.81,2,3.31e-7
File suffix W: C,1568053281.899,3,3.31e-7
File suffix V: C,1568053282.003,4,3.31e-7
File suffix U: C,1568053282.105,5,2.48e-7

You can see that with each line, the third object is an integer that goes from 0 to 5 which corresponds with the letters Z to U - this seems to always be the case. The fourth object is a very small float that seems to get smaller from Z to U.

I believe the lines starting with 'S' are parameter changes, but I'm not certain with that. I can say fairly confidently this is not used by tag finder, but is likely displayed on the web interface when connected to the SG locally. 
S,1568053281.601,1,-m,166.376,0,
S,1568053281.636,3,-m,166.376,0,

**Comment by leberrigan** [comment]
If you look in the [Sensorgnome master control process](https://github.com/sensorgnome-org/sensorgnome/blob/rpi/master/master.js), you can see where the lines starting with 'S' and 'C' come from:
```
TheMatron.on("setParam", function(s) {
    AllOut.write("S," + s.time + "," + s.port + "," + s.par + "," + s.val + "," + s.errCode + "," + s.err + "\n");
});

TheMatron.on("gpsSetClock", function(prec, elapsed) {
    AllOut.write("C," + (new Date()).getTime() / 1000 + "," + prec + "," + elapsed + "\n");
});
```

So:
- 'S' is for parameter setting.
- 'C' is for GPS clock setting precision. It outlines the time the GPS was set, the precision it was set to, and the time elapsed in running the time

The [gps.js file](https://github.com/sensorgnome-org/sensorgnome/blob/rpi/master/gps.js) explains the file name suffixes:
 ```
   this.timeStampCodes = ["P", "Z", "Y", "X", "W", "V", "U", "T"];
    // "P" clock not set by GPS
    // "Z" = 1 second
    // "Y" = 0.1 second
    // "X" = 0.01 second
    // "W" = 0.001 second
    // "V" = 0.0001 second
    // "U" = 0.00001 second
    // "T" = 0.000001 second
```

So what I think is happening as part of the 'normal' function is that each time the SG reboots, it asks the GPS for more precision until it reaches 0.000001 second precision where it stops. Each time the GPS gets more precise, the file suffix changes and a new file is written with a line in it that starts with 'C' that records the action of pinging the GPS and how long it took.

I'm not familiar enough with this stuff to explain why it's done this way since it seems fairly convoluted to me, but that's what I can tell is happening from reading the scripts.

**Comment by denislepage** [comment]
I created documentation about the data formats last year. There were some gaps left, including I think the meaning of these Z and others, and certain prefixes used in the data files.

https://github.com/MotusWTS/motusServer/blob/master/inst/doc/motus_data_formats.md

Good timing, I’m going to add the new CTT fields there.

It probably would be useful to consolidate all internal documentation in a single place, or at least have a master table of content that serves as the entry point.

**Comment by denislepage** [comment]
Very helpful. I have added those to the data format documentation:

https://github.com/MotusWTS/motusServer/blob/master/inst/doc/motus_data_formats.md

Also, I hadn’t included the –m variable type associated with the S prefix, but they seem to relate to the listing frequency, presumably of each antenna. I’ve added this also.

**Comment by jsayers-bsc** [comment]
Nice find, that explains a lot!
