### ISSUE TITLE
French info on english site

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#302]
On the receiver deployment page, if you click on "advanced antenna properties", and hover over the question mark for "mount bearing", the pop-up box is in French: https://motus.org/data/receiver/deployment/edit?projectID=1&id=681

I did try to search it in text fragments on sandbox, but after searching I get:
Developer Error!
Exception:

Encountered a DBException type 7 - Low-level Database error.

Error description: Creating prepared statement on: tx_keys (Made it to result set wrapper)

SQL exception: com.microsoft.sqlserver.jdbc.SQLServerException: Incorrect syntax near 'axe'.

While attempting: SELECT a.key_id,a.key_name,b.lang_code,b.text,a.type,a.needs_translation FROM tx_keys a LEFT JOIN tx_text b ON a.key_id = b.key_id WHERE (a.key_name LIKE '%azimut de l'axe%' OR b.text LIKE '%azimut de l'axe%') ORDER BY a.key_name

**Comment by denislepage** [comment]
I have pushed a fix for the error on the beta server. I haven't systematically looked for other cases where the string wasn't checked for single apostrophes, and I am not sure if my fix is generally how this has been handled elsewhere in Motus. This was in org.bsc.motus.web.admin.AdminTools, line 193. I used the encodeSqlString method.  I also overlooked that this was also a problem in line 236.

Seems to work now in beta. I have also modified the string in Beta, but it was already OK in the sandbox (I thought we were only updating fragments on Sandbox?). I can deploy to live shortly also.
