### ISSUE TITLE
Duplicate receiver not assigning serial number correctly

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#304]
receiver SG-1614BBBK1911 exists in both project 74 and 197, it's a duplicate receiver (see https://github.com/jbrzusto/TO_DO/issues/176). The receiver in project 74 was assigned to be SG-1614BBBK1911_1 and the receiver in project 197 set as SG-1614BBBK1911. The metadata reflects this correctly. 

However, a recent upload from project 197 assigned it as SG-1614BBBK1911_1 resulting in no associated metadata.  So, was the metadata mixed up (ie should it actually read SG-1614BBBK1911_1 for project 197), or is there a process somewhere that is incorrectly adding _1 to this receiver for the wrong project?

**Comment by denislepage** [comment]
Yes. The details for adding a new exception for dealing with collisions is detailed here:

https://github.com/jbrzusto/motusServer/blob/master/inst/doc/status_api.md#serno_collision_rules

**Comment by zcrysler** [comment]
I think we had already dealt with this as a duplicate which is why we would have called it SG-1614BBBK1911_1 in project 74. So how do we resolve this? Does it actually need to be SG-1614BBBK1911_1 for project 197 and SG-1614BBBK1911 for project 74?. 

See https://github.com/jbrzusto/TO_DO/issues/123, https://github.com/jbrzusto/TO_DO/issues/176

One of these receivers has always been in project 74, but the one that's now in project 197 used to be in project 2 which may be why it's not working for this upload?

**Comment by denislepage** [comment]
We’ll have to pull the rules used to identify and resolve the conflict (the API allows us to do that too, now). I think it’s based on a user-entered file stored on the SG. If the values used to resolve the conflict have changed, the resolution may no longer operate as expected.

**Comment by cjardine-bsc** [comment]
Ya, I think that's why. 

My understanding from this: https://github.com/jbrzusto/motusServer/issues/363 is that John is using a table in his database called serno_collision_fixes to code which checks to see if the serno is in an expected project (in this case project 2) and if it's not (which is true here because it's been moved to project 197) then it adds the _1 suffix to the serno. 

Actually, it looks like he's not doing this by uploaded project but by the site code set on the receiver. 

Zoe, do you think they might have changed the site code on the receiver when they moved it from project 2 to 197?

If so then we'll need to change the entry in the table to the new site code from project 197.

**Comment by zcrysler** [comment]
Ah I see, yes probably.  The only spot I know where you can personalize an SG is in the deployment.txt file. I think by site code you mean what's called the shortLabel in that file:

{
    "info": "default deployment",
    "who": "who is responsible for this deployment",
    "contact": "contact information for responsible party",
    "shortLabel": "SG1",
    "acquire": {
        "gps": {
            "secondsBetweenFixes": 300
        },


The individual text files containing detection data has the shortlabel at the beginning of each file, looking at the status page for that upload I see a file called "Aube-1614BBBK1911-000465-2018-07-02T11-04-14.4910T-all.txt.gz" so the shortLabel is Aube which matches the deployment in project 197 for that receiver. Meaning that she must have updated it since it was moved from project 2.

**Comment by denislepage** [comment]
I expected so. We’ll need to change the collision record accordingly. It’s a good learning opportunity for us.

Being thankful that this only involves a few receivers, but what a mess these duplicate serials.

We should try to have a clear path for how we deal with this, and how we tell people to do it. Maybe there’s a warning that we can display on the receiver page when there are more than 1 device ID linked to the same serial (before the _x suffix).

It wouldn’t allow us to detect when new units are deployed, but once they are flagged, we could at least warn users who try to move them to new projects and even display the short label that is expected (and/or allow them to change it, but I would be more hesitant to do so.

The other question I am wondering is whether this exception is going to work for re-runs. If we change the rule, and then go back to run the batches associated with the previous label, will that mess things up? We need to check if we can keep both labels with an OR condition, to be on the safe side.

**Comment by Hussell** [comment]
After experimenting and investigating a bit, it looks like serno_collision_fixes is obsolete and no longer referenced anywhere in the code. What appears to be in use is a table in /sgm_local/motus_meta_db.sqlite called serno_collision_rules. Entries in this table are modified using the sgdata.motus.org/status2/ API (https://github.com/jbrzusto/motusServer/blob/master/inst/doc/status_api.md). I've updated the rule there to trigger on the prefix "Aube" as well as the prefix "Lepreau".

**Comment by denislepage** [comment]
Can we manually fix the existing data that was mis-assigned, rather than reprocess them?

Though, confirming that the fix worked would be helpful.

Denis

**Comment by cjardine-bsc** [comment]
Yes, we should just need to change the device ID in the sg_batches table.

**Comment by zcrysler** [comment]
Do we need to re-run these receivers?

**Comment by zcrysler** [comment]
I'm seeing deployments for SG-1614BBBK1911 for projects 2 and 197:
project 2: 726, 2254, 2283, 2671, 2967, 3251, 3571
project 197: 4727
Most of these are after 2014

It's also in project 74 a number of times in 2015, 2016 and an active deployment in 2018. Am I misunderstanding?

**Comment by denislepage** [comment]
My bad. I made a typo in my query.

From that list, receiver SG-1614BBBK1911_1 was not used after 2016, so any detections in 2017 and 2018 should be assigned to SG-1614BBBK1911 (#43).

Despite that they have been re-run, we also needed to reassign the incorrect batches to the correct receiver. It’ll ensure that they are correctly marked as duplicates (once this is in place), and prevent them from showing up in the other project.

I am now re-running the link to assign those deployment ID’s to the correct detections.

The batch that was processed yesterday was correctly assigned to 43, so I think we’re in bizniz.

**Comment by cjardine-bsc** [comment]
Hey Zoe, 

Denis was referring to motus device ID 43, that was for me to update the sg_batches table. 

I've gone through and assigned the 2014 data to deviceID 43. 
All 2017 and 2018 data is assigned to deviceID 43. 

When both receivers were active (2015-05-04 to 2016-10-25) we'll need to look at the gps values for the batches to assign them to the correct deviceID (like we've done before Zoe). 

We can focus on the batches that have data. The list of batches you need to look at is below: 
124303
124357
124361
124370
124395
124404
124411
124378
78235
124382
124083
124428

**Comment by zcrysler** [comment]
Is there a way to see what user uploaded those batches? Would be a better indication of the receiver than GPS, I've only looked at one (124395) but it has no GPS values, I think a lot of them will be missing GPS records.
