### ISSUE TITLE
bulk tag upload creates blank deployments

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#309]
If you download a tag database with no deployments (ie. column tagDeployID is blank), enter relevant info for some but not all tags, and upload, you end up creating blank deployments for all tags that you made no changes to. So all the tags that you did NOT update are given a tagDeployID. This isn't a big issue but could easily result in projects having multiple unnecessary deployments for tags. It also affects how we categorize tags since all these blank deployments get listed as "pending" despite the user not having any info entered.

**Comment by cjardine-bsc** [comment]
I've changed it so that it should only make new deployments if date start or species ID is populated. 

Please test :)

**Comment by zcrysler** [comment]
in live or beta?

**Comment by cjardine-bsc** [comment]
both or either.
