### ISSUE TITLE
Receiver deployments download missing "notes"

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#31]
Any reason receiver deployment "notes" aren't included in the download file?  It's probably not appropriate to share this info with people outside the project (sometimes we have landowner notes there that probably shouldn't be seen by everyone), but even when I select "Motus Ontario" to download project specific receiver data from here https://motus.org/data/downloads - or click the "download all receivers" button here: https://motus.org/data/project/recvs?projectID=1 it's not included.  It would be really useful on a project scale to easily see important notes from all receivers rather than clicking through each receiver and each deployment

**Comment by Hussell** [comment]
Information in vwData_receivers_private should be made available to project members who have read permission for receivers (and to admins, of course).
