### ISSUE TITLE
Data processing for SG-4001BBBK2690

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#311]
There should be data in the system up to 2018-01-14 for Nanticoke SG-4001BBBK2690 but it seems to have been deleted.  The link provided on the status page (https://sgdata.motus.org/status?serno=SG-4001BBBK2690) takes you to "page not found": https://sgdata.motus.org/download/1/SG-4001BBBK2690-2017_Motus_Nanticoke_hourly_tags.png

There likely aren't any detections during this period, and tagme() doesn't return data for this receiver beyond 2016-09-14 so can you confirm that data has been processed? A user recently asked about detections here and I want to make sure there aren't any issues before reporting back.

**Comment by Hussell** [comment]
I've rerun this receiver, just in case. It looks like everything has been processed correctly.

**Comment by zcrysler** [comment]
I ran tagme() again and this time it downloaded 161 new batches so the re-run definitely added data, plus there's a fall detection of a GRSP now, thanks!
