### ISSUE TITLE
Long lived test tag

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#312]
motusTagID 27483, currently registered to project 0 has been used as a test tag since 2015, no deployment was ever created for it as far as I can tell. Project 48 was using this tag to test their receivers, most recently at stations SG-0816BBBK03BB and SG-0816BBBK03BB. The test tag doesn't show up which is to be expected but they'd like it to.

A suggested potential solution was to create a test deployment from 2015-10-01 to 2017-12-31, and a second deployment starting 2018-01-01 to see if a re-run would then show the tag on these receivers.

I've made those two deployments in project 0, Jeremy can you re-run the above receiver to see if that gets the test tag to show up?

Catherine, can you move this tag from project 0 to project 48?

**Comment by cjardine-bsc** [comment]
Moved.

**Comment by Hussell** [comment]
I'll rerun this on Monday, once the cached metadata has been refreshed.

**Comment by Hussell** [comment]
https://sgdata.motus.org/download/48/SG-0816BBBK03BB-2017_NE-Motus_Marshlands%202_hourly_tags.png
