### ISSUE TITLE
Tag Registration Error: Project 134

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#319]
Project #134 under Josephsjohnson. 20 tags attempted to register, but received the following error message. They are hoping to deploy as soon as possible.

I have created a registration package, but we received an error:
 
File uploaded: 2398_2018-08-08T19-08-51.224_MOTUS_2018_Tags_FINAL.zip
Registered 0 tags with motus.
Error: Error in createRecvTagDB(projectID, dateBin, isTesting): No tags found for project 134 with dateBin in 2018-3

**Comment by Hussell** [comment]
It looks like the server is expecting .wav files named like this:
tag010.wav
tag140.wav
tag521.wav

But the upload contained files named like this:
tag.010.wav
tag.140.wav
tag.521.wav
