### ISSUE TITLE
SG-3615BBBK1E34 duplicate data

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#321]
downloading receiver SG-3615BBBK1E34 with tagme() results in what I think are duplicate data, but one set has GPS coordinates and one doesn't. I'm not sure if this is a sign of some other unknown issue so details below:

hitID | runID | batchID | GPS
-- | -- | -- | --
37639354 | 3600292 | 17928 | Yes
439497525 | 26716667 | 159353 | No

This is just one example from this receiver but there are a lot of records like this where there are pairs of hitIDs with all other data identical (ts, sig, sigSD, etc), except one record has GPS data and one doesn't

**Comment by zcrysler** [comment]
I did this all through R with tagme() looking at the alltags table which is what users will be dealing with:

library(motus)
projnum = "SG-3615BBBK1E34"
tmp <- tagme(projnum, new = TRUE, update = TRUE, dir = "C:/Users/cryslerz/Documents/motusDownloads")
tmp <- tbl(tmp , "alltags")
tmp <- tmp %>% collect() %>% as.data.frame()
tmp$ts <- as_datetime(tmp$ts, tz = "UTC")

**Comment by Hussell** [comment]
Ok, this is a bug in the alltags view. The GPS coordinates are present in the regular tables.

**Comment by Hussell** [comment]
Looks like I spoke too soon. The view is pulling the most recent GPS coordinates that were recorded before the hit, and all the GPS coordinates in batch 159353 are later than the hits in question. In fact, all the GPS coordinates from the first batch are from 2016, and all the ones from the second batch are from 2017.

**Comment by denislepage** [comment]
The 2 batches may overlap, but they aren't covering the same period (based on tsBegin and tsEnd). They start almost at the same time (0.5 second difference), but they end 456 days apart.

The hits and the runs, however, are the same (identical?).

The difference, as pointed out above, is in the gps table. The gps readings for 159353 are done at a very difference time from the tag detections, which explains why the batch is so long.

batchID | tsBegin | tsEnd | hitsBegin | hitsEnd | gpsBegin | gpsEnd
-- | -- | -- | -- | -- | -- | --
17928 | 1.462 | 1.473 | 1.463 | 1.473 | 1.462 | 1.473 
159353 | 1.462 | **1.513** | 1.463 | 1.473 | **1.512** | **1.513**
