### ISSUE TITLE
Unable to download project 47

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#323]
Using tagme(), I haven't been able to download project 47. At home yesterday on my Mac I tried multiple times on fairly fast internet, the .motus file would be created but it would never start downloading batches, eventually I'd get an error message that the connection timed out. I tried doing this over and over, and would try deleting the existing .motus file, no luck.

This morning I'm trying on a PC with hardwired internet, again the .motus file is created, but no batches will download and after several minutes of nothing happening I get the message:

Checking for new data in project 47
Error in function (type, msg, asError = TRUE)  : Empty reply from server

I'm not sure what to do about this or how to get the data, is it because it's a particularly large file?

The call I'm using (and always have with no problems until now) is:
library(motus)
projnum = 47
tagme(projnum, new = TRUE, update = TRUE, dir = "C:/Users/cryslerz/Documents/motusDownloads")

**Comment by zcrysler** [comment]
Still no luck for me, other projects download fine

> projnum = 47
> tagme(projnum, new = TRUE, update = TRUE)

updateMotusDb started (9 rows)
 - Create new view allambigs that converts ambig columns into rows
 - remove previous version of alltagswithambigs view
 - Remove empty gps detections
 - Add a new column "siteName" to table "recvDeps".Error in rsqlite_send_query(conn@ptr, statement) : 
  duplicate column name: siteName

 - Create (or modify previous version of) filters
 - Create (or modify previous version of) runsFilters
 - Create new table for custom tag metadataError in rsqlite_send_query(conn@ptr, statement) : not an error

 - Remove previous version of alltags
 - Create new version of alltags that includes additional deployment fields

Checking for new data in project 47
Error in function (type, msg, asError = TRUE)  : Empty reply from server

**Comment by zcrysler** [comment]
Also - on that last attempt I got this email:
API Error generated: Failed to build response vectors.

User:  - Zoe Crysler

Service: /sgdata/custom/batches_for_tag_project

Parameters:

json => {"authToken":"-YkcypnSLHGBZsOdMjhQKkqdfcI7fwVUN7xXlJlDvHH7","projectID":47,"batchID":0}

**Comment by Hussell** [comment]
I was able to download this project today. Is it still not working for you?

**Comment by zcrysler** [comment]
I was able to download eventually and seems to still be working today. I'm not sure what changed it just seemed to start working one morning with the same process as always.
