### ISSUE TITLE
Forgot password update

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#324]
When you click on forgot password, it takes you to a page that says "An email has been sent to you with one-time token which will allow you to log in and change your password. You can either enter it here or use the link in the email to fill in this form automatically." there's then a box to enter the token.

The email you get does not contain a token, it contains a link which takes you to a new token page with the token box filled out.

I suggest two things:

- a better word than token as this is not intuitive - a user actually just emailed me frustrated that he had no idea what to do or what a token is and I agree, I haven't seen this language used on other sites when I forget password. Maybe something like "temporary password" would be better
- After clicking "forgot password", instead of going to the token page (https://motus.org/data/loginFromToken), I would suggest a different page that says something like "an email has been sent to you with a link to reset your password", with no room to enter the token that they never receive. Either that, or the email should include the token so they can enter it on the page they were brought to. It's confusing to tell people to enter a token (temporary password), that they never see in the email we tell them to look at.

For reference the email you get is:
Hello Zoe

Login name: zcrysler

You recently requested to reset your password for your Motus account. Use the link below to reset it. This password reset is only valid for the next 30 minutes, after which you will need to submit a new request. If you did not request a password reset, please ignore this email or contact us if you have questions.

Click on this link to reset your password: https://motus.org/data/loginFromToken?token=13p88s73146u3vahdft8od8gsk&lang=EN

Thank you,
The Bird Studies Canada team.

**Comment by denislepage** [comment]
One thing I would also like is to have a dedicated page for asking for the password reset.

This is a good example of what I think we need:
https://www.birdscanada.org/birdmon/default/pwordreset.jsp

Let’s wait until after beta7 to do this, however.
