### ISSUE TITLE
Incorrect TagIDs being detected

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#327]
Data from a station in Tofino shows 4 tags being constantly detected, which is to be expected as they've got shorebird tags out right now...the issue is that the tags are labelled as RBrownAMWO: https://sgdata.motus.org/download/191/SG-2313BBBK3569-2018_Tofino_Kwisitis%20Visitor%20Centre,%20PRNPR_hourly_tags.pdf

The 4 AMWO being detected have the same Lotek IDs and BI as the Tofino tags that were deployed (https://motus.org/data/project/tags?projectID=191), I'm confident that all these detections are Tofino shorebird tags and most definitely not AMWO tagged in Maine, but given that they're likely ambigs, why is only the AMWO label showing up?

Same results with data downloaded through tagme(), all tags are assigned to the AMWO project and there's no ambigID associated with any of the detections on that station. AMWO is project 82, Tofino is 191.

I'm guessing a metadata issue as the tags were registered in May, but since the data was just run today, shouldn't it be ok? Can we re-run it so the proper tags are showing up to ease user's minds and make tagme() functional for them?

**Comment by Hussell** [comment]
Rerunning had no effect. Normally ambiguous tags would be listed at the bottom of the plot (<a href='https://sgdata.motus.org/download/2/SG-1614BBBK1603-2017_MotusATL_Lookoff_hourly_tags.png'>like this</a>), so the tag finder must not be detecting an ambiguity in this case. Something does look wrong though: the tags being detected were all deployed in 2016, so they shouldn't be considered by the tag finder in 2018 data.

**Comment by zcrysler** [comment]
may be related to issue https://github.com/MotusDev/Motus-TO-DO/issues/330

**Comment by zcrysler** [comment]
These tags were registered manually since the user deployed without registering so that's why there's no record of them being registered, the user sent me a scanned copy of the Lotek PO and I just double checked and they are NTQB2-5-1, unless Lotek made a typo there. 

I have an old email from Stu listing new models from Lotek, but no battery info:
NTQB2-1
NTQB2-2
NTQB2-3-2
NTQB2-4-2
NTQB2-5-1
NTQB2-6-1
NTQB2-6-2
I think they behave like the old NTQB models, but I don't think an NTQB-5-1 existed. The Lotek order sheet says they're 0.5g tags though, so by weight they fall between NTQB-2 and NTQB-3-2

**Comment by jbrzusto** [comment]
Thanks Zoe - I'll tentatively assign them a battery size 1/2 way between NTQB-2 and NTQB-3-2.

**Comment by denislepage** [comment]
Catherine should be able to share what values she’s used for the same tag, so we’re consistent.

**Comment by jbrzusto** [comment]
After dealing with several blocking issues, this receiver [has been rerun](https://sgdata.motus.org/status?jobID=204941) and appropriate tags appear to be detected (with ambiguities, but that is a well known upstream problem.)

**Comment by zcrysler** [comment]
Thank you!!
