### ISSUE TITLE
Lack of expected detections SG-5DDFRPI3131A

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#330]
Project 201 deployed 30 tags near SG-5DDFRPI3131A, but only 2 were detected, they're positive the tags were on. Is there any way this is somehow a metadata issue or are there really no detections for any other tags at this station?

https://sgdata.motus.org/download/201/SG-5DDFRPI3131A-2018_PUMA_Altona_hourly_tags.png

**Comment by Hussell** [comment]
Rerunning this receiver has revealed no new detections, so it doesn't seem to be a metadata issue.

**Comment by Hussell** [comment]
Digging into this a bit more:
- Purple Martins were tagged at this location on July 5th and July 8th.
- Uploaded data files from this receiver only cover July 20th to August 14th.

So, it shouldn't be too unexpected that only 2 of 30 birds were still in range after 2 weeks. Possibly the researchers thought they'd already uploaded data files from the same time the birds were tagged?

**Comment by denislepage** [comment]
I am still trying to figure out whether there is any unaccounted data in the files left behind in /sgm/uploads/partial, but none that seem to relate to this receiver, in any case.

Everything that I have looked at so far seems to have already been parsed in /sgm/file_repo
