### ISSUE TITLE
Unable to register SRX 800M/MD

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#331]
Trying to register receiver for an SRX 800M/MD as "Lotek-668" results in the below error despite following the instructions we have online:

- Lotek SRX 800M/MD: "Lotek-XXX", where "XXX" is in the range 391 to 999

An error has occurred while we were processing your request.
This error has generated an email that has automatically been sent to the technical support staff. We will investigate this problem and will try to resolve as quickly as possible. It is possible that this was only an error caused by a temporary condition, and that you will not get this error again. If that is the case, then whichever operation that failed should succeed if you try it again. If it does not, then you can assume that there is a problem which we will need to resolve from our end.

If you wish to contact us about this error, please provide this reference number: 1535067154933

**Comment by Hussell** [comment]
I'm getting a 'String or binary data would be truncated.' error when I try to insert a receiver type of 'LOTEKSRX800M/MD' into the sensors table. I don't quite understand why, since len('LOTEKSRX800M/MD') == 15 and the column is varchar(15).

**Comment by cjardine-bsc** [comment]
The receiver_id column in the backup table was varchar(12), the error was occuring when writing to there. 

I've changed the backup table to varchar(15) and you should be good.
