### ISSUE TITLE
Error: Error in gzfile(file, mode): cannot open the connection

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#332]
3 failed data uploads yesterday for various projects failed due to the message above, jobIDs:
206883, 206924, 206937

**Comment by Hussell** [comment]
The folders these jobs are trying to access have their permissions messed up, as in #325.

**Comment by denislepage** [comment]
John, let me have a look at what the permissions are before making changes, so I understand a bit better how this is happening.

Denis

**Comment by Hussell** [comment]
Closing in deference to #325
