### ISSUE TITLE
Need lifespan/battery specs for NTQB2-5-1 tags 

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#334]
We don't have any information on the lifespan of this tag model. We need to get this information from Lotek.

**Comment by StuMackenzie** [comment]
For now I suggest replicating the specs for NTQB-6-1. 

I spoke with Lotek last week, and based on their tests and user feedback, they'll be ready to circulate their 'real' estimates of tag life for this whole new line 'soon' at which point we can update all of the new tags. At this point, anything more precise would just be a guess.

**Comment by Hussell** [comment]
We now have some numbers from Lotek for the following models:
* NTQB2-1
* NTQB2-2
* NTQ2-5-1
* NTQ2-3-2
* NTQ2-4-2
* NTQ2-6-1
* NTQ2-6-2

Can we pass these on to John?

**Comment by StuMackenzie** [comment]
[NTQB2 Weight & Life Estimates.pdf](https://github.com/MotusDev/Motus-TO-DO/files/2774979/NTQB2.Weight.Life.Estimates.pdf)

**Comment by leberrigan** [comment]
Is the 'expected' lifespan the same as the 'calculated' or 'warranty' lifespan? 

[warranty lifespan] = 0.8 * [calculated lifespan]

**Comment by StuMackenzie** [comment]
Expected should be the same as calculated. Lotek won't warranty the entire lifespan.

**Comment by cjardine-bsc** [comment]
Hey guys, I've got a couple other commitments to get to this week, But the next steps are to run these numbers through the attached and see how they compare to the first models with the same batteries. 

[Motus_tag_lifespan_CBJ.zip](https://github.com/MotusDev/Motus-TO-DO/files/2779810/Motus_tag_lifespan_CBJ.zip)

We can then update the database with the new values for these tags and see how that impacts the lifespans we're calculating. John will have to do the same in tagfinder, right now he's basing things on battery type I think, not tag model, so this may mean he needs to tweak things on his end a bit. But that's getting a little ahead of ourselves, lets see what these numbers get us first. 

Lucas if you want to run these scripts while you're waiting for me to free up some time I'd welcome the help!

**Comment by jbrzusto** [comment]
Model results here:
https://github.com/jbrzusto/motusServer/blob/master/inst/doc/modelLotekTagLifeSpan.pdf
from which:
```R
> load(file.path(system.file("", package="motusServer"), "doc/modelLotekTagLifeSpan.rda" )
> round(tail(tagLifespanPars, 7), 1)
                D   rt
NTQB2-2     332.3 31.6
NTQB2-3-2   759.8 31.0
NTQB2-4-2  1522.7 31.1
NTQB2-4-2S 1522.7 31.1
NTQB2-5-1   601.7 31.0
NTQB2-6-1  2160.0 31.1
NTQB2-6-2  4083.4 31.1
```

**Comment by cjardine-bsc** [comment]
I've changed the D and rt values in the lk_tag_models table.

**Comment by StuMackenzie** [comment]
Trying to close the loop on this issue. Is there anything left to implement before the changes will be implemented in tagfinder?
