### ISSUE TITLE
filtering

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#336]
I have added a new step to the import of SG data into Motus. This has been pushed to sandbox/master branch, and will be included in the beta7 branch shortly. Be aware that the beta branch will be operating directly on the live database.

EXEC [prSGBatches_filters_ts] @ts 

where ts is the start of the import process on the SQL server. This will:

1) identify duplicate batches and flag deprecated ones that have been superseded by a more recent run.

2) identify noisy batches where individual days have >= 80% of len = 2 and where runs are < 4 (runs of 2 and 3 are added to filters in noisy environments)

We will need to confirm: 

- [ ] that duplicate batches are excluded from any outputs.
- [ ] that filtered runs are excluded from public summaries, but not from the API downloads. 

Also:

- [ ] - We should also plan new R views that will make this table available for import into sqlite motus R files.
- [ ] - Modify the API to add the new views
- [ ] - Modify the motusClient package to pull the filters

**Comment by denislepage** [comment]
The sg_runs_filter table currently has a constraint with lk_filter_status (values -1, 0 and 1) on the probability field. I don't remember setting this up, but the probability field is an arbitrary value between 0 and 1. I have removed the foreign key , at least until we can discuss. I don't think it will be worth adding a constraint (between 0 and 1).

**Comment by cjardine-bsc** [comment]
closing in deference to #493
