### ISSUE TITLE
mobile receiver clarification

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#337]
On the English receiver deployment page, the dropdown menu makes it clear which receivers are mobile, eg. it says "Aircraft (mobile)", the French site doesn't specify that these are considered mobile - can we add that to the French dropdown menu for station type since the mobile box is gone?

Also - as some users are putting receivers on drones, do we want a new drone option? It might not be necessary since we have aircraft as an option but going forward it might be a distinction we want to make.

**Comment by denislepage** [comment]
Fixed. The word is the same (mobile). There were no names entered in French in sandbox, and a couple discrepancies between the 2 db that I also fixed.

I would be hesitant to add a breakdown of types of aircrafts, ground vehicles or ships. It clearly can have an impact on detections, but we could end up with a rather long list of options. We could rather encourage people to give more details in the comments? That said, I could imagine someone interested in pulling data for say only drones.

Couple translation comments:


-          I changed the translation of aircraft to Aéronef, which includes anything that flies.



-          Trying to translate Pop Tower is interesting. How would you explain in normal words the difference between a Pop Tower and a Tower, so I can try to find a proper qualifier? Is “pop” referring for instance to the fact that those can be assembled dismantled easily as opposed to a more permanent structure? This is what I always understood. It probably isn’t clear in English either. I used “Tour démontable” (i.e. removable). Does that make sense? Should we also clarify the English description?

**Comment by zcrysler** [comment]
Pop tower: The way you explain it is how I've been thinking of it, I consider the pop-towers the tripod with extendable mast setups that we do, and tower like an existing permanent tower of some kind. If we aren't distinguishing between types of aircraft, do we need a tower distinction? Just looking at our own deployments for Motus Ontario, a lot are listed as "tower" that are pop-towers so this likely isn't a clear distinction online. I don't think it tells us much about antenna height either unless we make sweeping assumptions so I'm not sure that we need to differentiate the two.

**Comment by cjardine-bsc** [comment]
The lookup table translations came back from Serge while I was away. I'll update the database with his proofed/translated fields today. 

He translated pop tower as: Tour autoportante
