### ISSUE TITLE
166.380 tags on 152.1 station

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#339]
Project 214 - stations and tags are set to 152.1 MHz, but hourly plot shows detections of Canadian 166.380 tags and no Australian detections, related to https://github.com/MotusDev/Motus-TO-DO/issues/236

They're testing tags and stations, can it be re-run?

**Comment by Hussell** [comment]
Could you double-check the frequency? I set the default frequency for the project and re-ran the receiver, but the tag which was detected had an ID of 152.1 and a frequency of 151.5.

**Comment by zcrysler** [comment]
Sorry for the mistake, I meant it should have been picking up tags at 151.5 but it was getting 166.380 tags. It's now getting the expected tag at the correct frequency, thanks!

**Comment by Hussell** [comment]
Right, changing it to 151.5 now.
