### ISSUE TITLE
French instructions on English errors page

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#340]
Under receiver issues, half the instructions are in English, half French when on the English site. The French site only has French instructions: https://motus.org/data/issues?id=123&lang=en#v_sensor_hits_out_deploy

"Detections Outside of Receiver Deployment
Severity: Error 

These receivers have tag detections that are outside of any deployments for the receiver.

Veuillez créer des déploiements pour ce récepteur qui incluent les positions de ces détections."

**Comment by cjardine-bsc** [comment]
Should be fixed.
