### ISSUE TITLE
Incorrect errors project 123

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#341]
There's a receiver error for detections outside of deployments for project 123, deviceID 703:

Device ID: 703, number of detections: 131223, from 2018-04-14 14:20:31 - 2018-04-22 04:55:57

But deployment ID 4633 for that device goes from 2018-04-06 05:30 - 2018-04-23 23:59

Also - for the same project there are warnings about ambiguous tags, project 123 is running off of 150.1MHz, and the ambig tags are from project 124 using 166.380MHz tags - would it make sense not flag ambig tags if they run off of different frequencies?

**Comment by cjardine-bsc** [comment]
Should be fixed.

**Comment by zcrysler** [comment]
Another project (177) is also getting errors about tags registered twice, but the duplicate is in another project, this is causing confusion among users. If possible can we change it so that errors of duplicate tags are only flagged if the duplicate is in the same project?

**Comment by cjardine-bsc** [comment]
I'll add the frequency to the check so that this error isn't returned if tags are on different frequencies. 

Otherwise I think instead of removing the error we should expand the description to limit confusion. Users should be warned if two tags might result in ambiguities between projects so they can time their deployments accordingly and prevent future confusion. Unless I'm misunderstanding?

**Comment by zcrysler** [comment]
I think the way the message for duplicate tags reads, is that it's really suggesting these are really duplicate registrations done by a single project by mistake, or that they are within project ambiguities. It suggests that if they're correct registrations to alter deployment times accordingly - I'm not sure how realistic it is that projects will contact each other and delay deployment due to this. If that's what we're expecting then we should provide an easy way for users to find out which project the other tag belongs to and the contact info for the PI.

"These pairs of tags were registered during the same time period and have the same properties. They are very likely duplicate registrations.

Please confirm whether or not these tags are duplicate registrations. If they are duplicate registrations, contact us at motus@birdscanada.org to request that one of the duplicate registrations be deleted. If these are not duplicate registrations, it is important that the tags not be deployed at the same time, as they will not be differentiable when detected, leading to ambiguous detections."

There's another warning for overlapping tag deployments that also flags ambigs from other projects, and I think does a better job of covering ambig tags:

"These tag deployments overlap in time with a deployment for a tag with identical properties, which may lead to ambiguous detections.

Please confirm the deployment dates for both deployments are accurate. You may need to resolve ambiguities between these two tags using spatial or temporal factors."

Or maybe we need to make the duplicate tag error project specific to cover registration errors, and a separate ambig warning that covers tags network-wide

**Comment by cjardine-bsc** [comment]
we may need a third error here. 

1. duplicate registrations. (easy fix)
2. pre-deployment warning about ambiguous tags (maybe the most useful?) 
3. post-deployment warning about ambig tags

What do you think? If so you could draft some instructions for number 2 and I can split those errors.

**Comment by cjardine-bsc** [comment]
I re-ran the validations and the issue with DeviceID 703 disappears: https://motus.org/data/issues?id=123
