### ISSUE TITLE
Data issues page: tags registered twice

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#342]
Project 134 has data issues for tags registered twice:

Tag ID : 31301 is equivalent to Tag ID : 31864 | Edit |  
-- | -- | --
Tag ID : 31302 is equivalent to Tag ID : 31865 | Edit |  
Tag ID : 31303 is equivalent to Tag ID : 31866 | Edit

Looking at their tag page, only the first of each of those registrations exists, the partner tag is in project 177. So can this error be updated to not be flagged if the duplicate registrations were in two separate projects? These should be flagged as ambigs, not duplicate registrations

**Comment by zcrysler** [comment]
Also, project 177 is on a different tag frequency so they shouldn't be duplicate tags really at all

**Comment by cjardine-bsc** [comment]
Okay, I added the frequency to the check so these no longer are reported as duplicate registrations.  I did the same for the the overlapping tag deployments check. 

I only did this in sandbox for now. I'll change live after the Canarie presentation :)

**Comment by cjardine-bsc** [comment]
Issue related to #341
