### ISSUE TITLE
upload to wrong project

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#343]
I know that if data is uploaded to the wrong project it should still be available to the correct one through tagme(), but the hourly plot doesn't get created which is useful for users to quickly check functionality. SG-314BBBK5554 was uploaded to project 1 but should have been uploaded to project 48, can it be re-run so that we can see the hourly plots?

**Comment by Hussell** [comment]
SG-3214BBBK5554?

**Comment by zcrysler** [comment]
oops - yes

**Comment by zcrysler** [comment]
Another group of data was uploaded to the wrong project, the jobIDs are below. They were uploaded as project 218 but should have been uploaded to project 123. Can they be re-run so the user can see the hourly plots?
214310
214315
214316
214328
214334-214338
214342-314344
214347-214349
214352
214354
214356-214364

Some of those jobs have error "File uploaded: 2340_2018-09-11T11-10-54.199_61_FINO1-2018-08-SGdatatxt_ERRORDAY_01_02_03_04_05_06_07_08_09_10_11_12_13_14_15_16_17_18_19_rm_defect8.zip Will run tag finder on 6 receiver boot sessions" 

And some of them made hourly plots in project 218 as "unregistered deployments" (the SG is not registered to project 218), and some didn't make any plots - is there a reason they're dealt with differently? Eg. jobID 214363 created this plot https://sgdata.motus.org/download/218/SG-3615BBBK0CD0-2018_BIRDMOVE_Autumn_unregistered_deployment_hourly_tags.pdf, but jobID 214359 didn't create a plot. Neither receivers are registered to project 218, both are registered with deployments to project 123.
