### ISSUE TITLE
prSearchSpecies ignores group parameter

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#345]
https://motus.org/api/species?json={"date":"20180913142244","qstr":"zebra","group":"SPIDERS"}

The above query (with a current date timestamp) should only return species in the given group. Instead it returns species from all groups. The problem seems to be in the parentheses in prSearchSpecies (some OR clauses are outside parentheses they should be inside).

**Comment by cjardine-bsc** [comment]
Moved one parentheses and all is well again. Thanks for the flag.
