### ISSUE TITLE
Registration link not working

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#347]
I registered as a new user on beta and got the confirmation email, but the link in the email takes me to an error page, this is the link I got: https://motus.org/data/user/confirmEmail?key=D4FA635E55ACBF8244C9AE3D3C26222E

And it re-directed me here: https://motus.org/404.php

I registered as PI if that makes a difference

**Comment by Hussell** [comment]
Ah, you'll have to manually change the link to beta.motus.org, since the thing isn't deployed yet. The link is in one of the text fragments, so changing it for testing is annoying.

**Comment by zcrysler** [comment]
Oh ok, got it working thanks
