### ISSUE TITLE
Helgoland: suspected missing detections

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#351]
Is there any reason to suspect that there might be detection issues of a project where some tags are getting picked up and others aren't?  All tags were registered this August, the user is expecting them to be picked up by nearby stations.

Project 76 user says they have no detections of the following tags:

Tagnumber                                   nearest receiver

431 - 434 and 436 to 441                       SG-4414BBBK0722
435                                                             SG-4414BBBK0737
3,4,6,7,11,13,14,18,19,22,23,24,25     SG-4414BBBK0737

of the following tags we got just signals of one receiver (which seems a bit unlikley)
5,8,9,10,12,17,20,415,442,444,445       SG-4414BBBK0737
412,422,429                                                SG-4414BBBK0722

**Comment by Hussell** [comment]
I reran these two receivers (and the other two on Helegoland, just in case), and some of these tags showed up. https://sgdata.motus.org/download/76/SG-4414BBBK0722-2018_Helgoland_MTL_autumn_2018_hourly_tags.png

**Comment by zcrysler** [comment]
Thanks!

Any idea why this happened so I can assure the user it's behaving as expected now?
