### ISSUE TITLE
Add new filter parameter for tags API calls

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#352]
Add a new field called dateLastModified that can be used to restrict the list of returned tags from the Motus API to only those that have been modified since the said date. This will have to be based on the last_edited_dt of the tag_deployments table.

See https://github.com/jbrzusto/motusServer/issues/419

**Comment by cjardine-bsc** [comment]
We're using vwBase_API_search_tags for this right?

I've added this field to that query. It returns the last_edited_dt from tag_deployments when that exists and if not it returns the last_edited_dt of tags. 

 ISNULL(b.last_edited_dt, a.last_edited_dt) as dateLastModified
