### ISSUE TITLE
Old Cut plot error

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#355]
JobID 216885, seemed to process ok and the email didn't indicate any errors but the hourly plot wasn't updated and the detailed log indicates that there are errors:

"Unpacking file 2510_2018-09-13T17-58-21.869_WPBO_Motus_Data_2018-04-12.zip with unzip -o
Error: Error in safeSys("cd", dir, nq = ";", cmd, file, postopts, shell = TRUE, : Error 3 from 'cd '/sgm/queue/1//00216013/00216018' ; 'unzip' '-o' '/sgm/queue//1//00216013/upload/2510_2018-09-13T17-58-21.869_WPBO_Motus_Data_2018-04-12.zip' '-x' '/'':
warning [/sgm/queue//1//00216013/upload/2510_2018-09-13T17-58-21.869_WPBO_Motus_Data_2018-04-12.zip]:  2301870395 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [/sgm/queue//1//00216013/upload/2510_2018-09-13T17-58-21.869_WPBO_Motus_Data_2018-04-12.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)"

Another upload for this station jobID 216894 failed for "Error `Error in rsqlite_send_query(conn@ptr, statement): database is locked
` while trying to make plot for SG-5113BBBK2972 2015_MotusON_Old Cut"

An earlier upload today for this station went through ok (jobID 216872), this first upload was smaller than the other two, is this a  file size issue?

Hoping to upload a few days of data for this station during the presentation tomorrow, can it be re-run asap?

**Comment by zcrysler** [comment]
The last issue for jobID 216971 can be ignored - I uploaded to the wrong project, uploading that file to the correct project updated the hourly plot. I'm not sure if it's a coincidence, but these last few days that I uploaded show that the antennas are offline and the GPS is online. Not sure if it's related to the upload issue or not, but seems like a strange coincidence that the antennas would go offline the same date as the files I originally uploaded to the wrong project

**Comment by denislepage** [comment]
I tried a few options for re-running that batch. So far, with the same outcome.

I am currently trying one last option with the cleanup option = TRUE.

If that continues to fail, there may be something else happening, such as folder permissions preventing from saving the PNG files.

**Comment by denislepage** [comment]
The reprocessing gave the same error

Error `Error in png(plotfilename, width = rv$width, height = rv$height, type = "cairo-png"): unable to start device 'png' ` while trying to make plot for SG-5113BBBK2972 2015_MotusON_Old Cut

I looked at the products folder permissions for this receiver from Linux, and they appear correct. Not sure what else is happening.

**Comment by Hussell** [comment]
I reran this receiver (job ID 217492) and got the same error:
`Error in png(plotfilename, width = rv$width, height = rv$height, type = "cairo-png"): unable to start device 'png'` while trying to make plot for SG-5113BBBK2972 2015_MotusON_Old Cut

There's no error report though (the sub-job reported itself as completed without any errors). Brainstorming: this receiver has been deployed in a busy location since 2015, so maybe the PNG height is insane?

**Comment by jbrzusto** [comment]
Good thinking:
```R
> png("/tmp/bogus.png", width=32768, height=8192)
Error in png("/tmp/bogus.png", width = 32768, height = 8192) : 
  unable to start device 'png'
In addition: Warning message:
In png("/tmp/bogus.png", width = 32768, height = 8192) :
  cairo error 'invalid value (typically too big) for the size of the input (surface, pattern, etc.)'
> png("/tmp/bogus.png", width=32767, height=8191)
```
```sh
$ cd /sgm/products/SG-5113BBBK2972
4934$ file *
...
SG-5113BBBK2972-2015_MotusON_Old Cut_hourly_tags.pdf:       PDF document, version 1.4
SG-5113BBBK2972-2015_MotusON_Old Cut_hourly_tags.png:       PNG image data, 7941 x 31875, 8-bit/color RGB, non-interlaced
SG-5113BBBK2972-2015_MotusON_Old Cut_hourly_tags.rds:       gzip compressed data, from Unix

```

So the last time that plot was generated, it was very close to the limits of the PNG size.

Two simple options: 
- add a (re-)deployment record for that receiver, just to break up the time period
- reorder code in `motusServer::handlePlotData()` so that a pdf is generated even if `png()` fails
I'm doing the latter.

**Comment by denislepage** [comment]
Excellent.

Breaking the long deployments is a good workaround also for now.

John, I’m am not sure how your plots are generated, but another possible workaround would be to create distinct plots by year or dateBin within the same deployment, which would make it less likely to exceed the max. Not a big priority, but if it’s easy enough to do, that could help.
