### ISSUE TITLE
•ÈÀ"tagID" added to tag deployment file

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#356]
A user working off of a Mac sent me their tag metadata csv file that they wanted to bulk upload, the first column "tagID" had been changed to •ÈÀ"tagID" at some point automatically. This hasn't happened to me on my Mac, so it might be a specific setting on his computer, but posting in case it's related to https://github.com/MotusDev/Motus-TO-DO/issues/348

**Comment by denislepage** [comment]
Yes, the first character is the so-called BOM. I’ve taken it out of sandbox. I think we’ll leave it out.
