### ISSUE TITLE
EC Quebec: manual tag registration

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#357]
A tag registration file didn't register 6 tags because it was "Unable to get a good estimate of burst interval", user didn't notice this and has already deployed the tags. These are for project 3, jobID 192132. Since we have the recordings, can we manually register these tags from what we've got?

**Comment by cjardine-bsc** [comment]
when were these done? I think John made some tweaks to the tag registration process recently. If you have the files you could try to re-upload them for registration and see if they go through. 

Alternatively, if you send me the list of 6 mfg_ids and burst intervals I can register them with the work-around we have for tags that were not recorded, but that's a last resort option. Especially if the BI isn't clear from the recordings.

**Comment by Hussell** [comment]
I tried rerunning this job (new job ID 217742) and the same six tags failed.

**Comment by zcrysler** [comment]
Darn, ok thanks.

Catherine can you manually register them? mfg_ids are 158, 159, 165, 166, 174, 184. The BIs should be 12.7 based off of the other tags registered during that batch

**Comment by cjardine-bsc** [comment]
I need tag model and frequency then I can run that. 

I'd like to double check the BI. We can do that after I've registered them so that they are available for tagfinder in the mean time. Can you either look at their recording file and verify the BI or ask for their data sheet from Lotek?

**Comment by zcrysler** [comment]
Jeremy, are you able to see the uploaded file to confirm BI? I don't have access to it and the users haven't been able to track it down yet.

Tag Model is NTQB2-3-2, 166.38 MHz

**Comment by Hussell** [comment]
I can see the .wav files, but I don't know how to measure BI from those. (Isn't the whole point of this that the BI can't be measured from these six files?)

**Comment by zcrysler** [comment]
If Catherine just wants confirmation on BI, then I'd just open the file in Audacity to confirm if the time between recorded pulses is 12.7s, I don't know how precise that time needs to be for each detection for the registration to be accepted so it may still look like all of them are 12.7s apart despite being rejected

**Comment by Hussell** [comment]
All six tag recordings show a BI of 12.7s, plus or minus a tenth of a second.

**Comment by jbrzusto** [comment]
The tag finder needs precise BI estimates, to within 20 milliseconds or less.

**Comment by zcrysler** [comment]
Updated title - it's for an EC project in Quebec (3), not Helgoland, unless the title change was referring to something else

**Comment by cjardine-bsc** [comment]
Okay, that opened up a can of worms on the DB side, but I've successfully stuffed them all back inside. 

Those tags have now been registered. Be sure to have them create the appropriate deployments ASAP.
