### ISSUE TITLE
receiver daily summaries showing detections outside of deployment

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#358]
https://motus.org/data/receiverDeploymentDetections?id=4721
This hourly summary shows a bunch of 2015/2016 detections for a receiver deployment that was only active in 2017/2018. I'm guessing these old detections are from a deployment under a different project but it's confusing since the page clearly indicates that the tags are for a specific deployment and not for all deployments for that receiver:

Tag detections: daily summary
Receiver deployment: Marshlands 1 (ID# 4721)
Receiver ID: SG-0816BBBK03BB
List of daily tag detections by this receiver deployment.

**Comment by zcrysler** [comment]
Actually, as far as I can tell that receiver is only registered to project 48, so I'm not entirely sure where these detections are from

**Comment by cjardine-bsc** [comment]
I think this is related to the error we saw when trying to delete a fake receiver. I'm working on resolving that now.
