### ISSUE TITLE
Some jobs seem to be waiting for a long time

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#361]
![screenshot](https://user-images.githubusercontent.com/28784000/45780833-6ee6c300-bc2c-11e8-8289-f26470efeb06.gif)

**Comment by denislepage** [comment]
I think there are 4 threads available, and it seems like they are all tied up. Server #2 has been running for 7 hours, but it seems like this is a full re-run, so that is possibly expected. I’m not seeing an issue here?

John was planning to shut down the linux server tonight. Those will presumably restart with the server if they get stopped.

Denis

**Comment by Hussell** [comment]
The threads are supposed to switch regularly, so every job gets a little time now and then. Process #4 in the screenshot had been waiting for at least 6 hours, and as far as I could tell all four of the processes had been waiting for at least an hour. In the past, similar jobs have been completed within ~10 minutes.

**Comment by Hussell** [comment]
The restart of the server seems to have massively improved the situation. I just reran 7 receivers in two minutes, instead of two hours.

**Comment by jbrzusto** [comment]
Sorry, folks - I did not get a chance to restart the server the other day, so there has been no change
there.  (I need to reschedule a chance to do this).
Most of the time the tag finder is I/O-bound, and waiting for blocks from the NFS, so total throughput
increases by running more processes than there are cores.
Is there any evidence it's memory thrashing?  More likely, some receivers with large numbers of big
files (e.g. long-deployed noisy sites have been re-run for all or most of their history).  You can selectively re-run by choosing a range of boot sessions, although there are unresolved problems
with this for some receivers:  jbrzusto/motusServer#407

**Comment by jbrzusto** [comment]
Also, each tag finder session sends its results to the mariadb SQL (master database) server, so that also serves as a bottleneck.
