### ISSUE TITLE
Future dates in "last data processed"

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#362]
There are a few active receivers in the Motus Ontario project 1 that have "last data processed" dates well into the future:
deploymentID 645: 2022-08-05
deploymentID 3971: 2020-05-15
deploymentID 2549: 2022-05-31

There aren't date files for these dates so I don't think it's a receiver issue, eg. deploymentID 645: https://sgdata.motus.org/status?serno=SG-5113BBBK3169

Update: deploymentID 2549 isn't showing a future date for "last data processed" because I ended the deployment as per https://github.com/MotusDev/Motus-TO-DO/issues/355#issuecomment-423212055. That receiver now has a pending deployment, and if I activate the pending deployment it gets assigned the future date for last data processed of 2022-05-31, so it's still an issue for this receiver even though it isn't showing up right now. Pending deployment is because of https://github.com/MotusDev/Motus-TO-DO/issues/363

**Comment by Hussell** [comment]
I see 29 batches in the database with tsEnd in the future, ranging from 2018-10-20 to 2023-07-21. (There are also a large number of batches (22,000+) with tsEnd before 2000, but those don't affect anything.)

**Comment by zcrysler** [comment]
Any idea if this is a GPS or receiver malfunction?

**Comment by denislepage** [comment]
I suspect these are occasional bad fixes from gps receivers, or misconfigured units that haven’t had a gps fix yet. Or something…

Is this value currently calculated from the tsEnd of the sg_batches table?

Easiest is probably to ignore batches where end dates that are in the future when calculating this value (e.g. “where tsEnd <= dbo.datetime2st(getdate())”).It’s not a perfect fix, but probably good enough. The latest date will still be valid as long as the highest valid detection date is not contained in that batch.

There are likely other places where this will create issues, but the batch tsEnd may not be used so much compared to values from the runs and/or hits table, and neither of them have values in the future.

The pulse counts table however does. I’m not sure if an easy way to clean this up, or whether it’s even needed beyond the above fix for this page along.

We “could” manually fix the problematic batches by either taking the highest valid ts from pulse counts or hits, but we’d have to repeat this process once in a while, and I am generally not so keen on modifying the data imported into SG tables.

**Comment by cjardine-bsc** [comment]
Should this be added to the notification center to alert users that there is something wonky with their GPS timestamps?

**Comment by denislepage** [comment]
Potentially, but not sure. Nothing the user can do about the data processed, but I’m not sure if there’s something they can do about their receiver settings.

We’d have to try to understand the patterns, but I think most batches with future dates start at a normal date, so only some of the detections are incorrect.

If so, they can probably be attributed either to a few faulty gps times, or incorrect dates before a proper gps fix.

**Comment by Hussell** [comment]
Since the last comment I've found a few more receivers with anomalous activity pulses. Here's a list, along with what I estimate to be the actual latest date for which we have **real** data:

SG-3115BBBK1D41	2017-11-01
SG-1614BBBK1956	2017-11-12
SG-5113BBBK3169	2017-07-08
SG-0613BB000613	2016-10-12
SG-1212BB000254	2016-10-24
SG-3214BBBK5686	2018-08-01
SG-5113BBBK3171	2018-09-04
SG-5113BBBK3089	2018-09-14
SG-5113BBBK2972	2018-09-01
SG-2712BB000055	2018-10-27
SG-5113BBBK0555	2018-11-15
SG-1012BB012075	2016-03-24
SG-5113BBBK3118	2018-05-17
SG-4712BB000832	2015-08-25
SG-2312BB000505	2015-01-08
SG-4712BB000817	2014-10-31
SG-4712BB000750	2014-10-28
SG-1012BB012090	2014-09-22
SG-1212BB000258	2014-07-22
SG-4712BB000827	2014-08-20
SG-3214BBBK9591	2016-10-28
SG-2712BB000014	2013-09-24

In addition to messing up the latest-data date, this is annoying on the receiver timelines, which by default show the most recent year with data, e.g. https://motus.org/data/receiver/timeline?id=584

**Comment by StuMackenzie** [comment]
Old Cut's recent run resulted in another - 
Old Cut (ID# 5061)
Last data received: | 2022-05-31 23:00:00 UTC

**Comment by Hussell** [comment]
On the call yesterday I said that if the batches were fixed in the database then they would be permanently fixed, and the future dates wouldn't show up in new batches created by rerunning. I'm not so certain that's true now, but it would still be good to do a one-time fix to past batches.

**Comment by cjardine-bsc** [comment]
Blech. This is very difficult to figure out programatically. 

Here's one option deal with these going forward. 

What we are really interested in is whether batches have data from the future. Which essentially mean cases where the tsEnd is greater than the tsMotus. 

SELECT  [batchID],[motusDeviceID],[monoBN],[tsBegin],[tsEnd],dbo.ts2datetime([tsEnd]),dbo.ts2datetime([tsMotus])
 FROM [motus].[dbo].[det_batches]
  where tsEnd - tsMotus > 36000

Now, that's only going to be guaranteed true for the first run of the receiver. As time progresses and tsMotus increases these receivers will eventually no longer be flagged by the above query (which explains why the above query only returns 13 receivers where as Jeremy has identified 20 with this problem). 

That means that as time goes on we will loose some ability to detect this issue, and will instead have to rely on the activity plots to identify these anomalies, or figure out a way to identify them programatically in retrospect (see "blech" above). 

What are people's thoughts on a proc that will:

1. Scan the det_batches table at some interval (daily) and identify new instances that match the parameters of the above query.
2, Write them to a separate table that will track batches which have bad tsEnds That table can also include a column with the "right" tsEnd that can be used to replace the bad tsEnd in subsequent re-runs of the same batch. That "right" tsEnd can be initially assigned as the tsMotus of the first running of the batch, and refined based on our review of the plots as needed. 
3. All subsequent re-runs of the batch would then be compared to this table upon import into the database, and have their tsEnd updated. 

I know this is a lot of gymnastics, but I don't have a better way of scrubbing out these bad timestamps once we get the data. Even if we asked tagfinder to scrub out bad timestamps as it processes the data, that too will eventually stop catching bad data as we inevitably march slowly forward in the toils of time. So the only way I can think of doing this is to keep a list of cases and update re-runs. 

That or remove the bad data directly from the detection files (no....). 

Thoughts?
