### ISSUE TITLE
copy deployment from previous not using most recent deployment

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#363]
Trying to create a new deployment for receiver SG-5113BBBK2972, deviceID 304, in project 1. When I click "copy this deployment from the previous deployment", it copies information from the very first deployment for that receiver (deployID 4611) not the most recent which should be 2549. On the receivers page you'll see a pending deployment which is what was automatically filled in when I clicked copy from previous deployment: https://motus.org/data/receivers/edit?projectID=1&id=435

**Comment by pmorrill** [comment]
That's pretty annoying. I will figure it out by tomorrow.

**Comment by pmorrill** [comment]
I have adjusted code to do a better job of selecting a source for the clone. It will now take the most recent, based on deployment END date. Or, if a deployment is active, it will consider it's START date. This will be in tomorrow's Beta build, so should be tested there before deploying to live.
