### ISSUE TITLE
Tags to manually register

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#366]
20 tags failed to register in 2016 and were just recently noticed. The tags have been deployed but they're hoping we can manually register them. The tags might have been uploaded with a bunch of other tags that processed correctly but we don't know this for sure, they may have just never been registered.

The tags are Lotek IDs 263-282, they should be registered to project 3, BI of 14.9, NTQB-2

IF the tags were uploaded but failed to register, they would have originally been uploaded to project 15 with a number of other NTQB-2 14.9s tags, this other group of tags was registered on 2016-10-04, I can't see files that far back so I'm not sure if the missing tags were uploaded at the same time. All these tags have a bI of 14.89ish

**Comment by cjardine-bsc** [comment]
Jeremy can you check to see if you can find the files from this far back? If not I'll manually register.

**Comment by Hussell** [comment]
I've been unable to find any files older than around August 2017.

**Comment by jbrzusto** [comment]
These were registered on the old server.  Looking into why they didn't make it over to the new one.

**Comment by jbrzusto** [comment]
Not sure why, but these tags were not even in the master database on the old server for that year.
I have the recordings and can bundle them up and run them through the usual tag registration
process.  That way the recordings will be archived on the new server.

**Comment by jbrzusto** [comment]
registration job here: https://sgdata.motus.org/status?jobID=225013

**Comment by jbrzusto** [comment]
A big re-run of many receivers will be required before any of these tags show up.
