### ISSUE TITLE
Receiveres to re-run project 3

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#367]
Some tags were recently manually registered for this project after they were deployed, can these receivers be re-run in the hopes that the tags will now be visible?

SG-5113BBBK2528
SG-5113BBBK3108
SG-1914BBBK0929 
SG-5113BBBK0555
SG-1315BBBK0136
SG-1315BBBK0083
SG-5113BBBK3183 
SG-1614BBBK1928

**Comment by Hussell** [comment]
I've rerun all of these, but I can't tell if anything new has showed up.
