### ISSUE TITLE
Project 2 Missing Data

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#371]
There are apparently quite a number of data files that were uploaded, processed, and used, but never made it over to the new server. The below periods of missing data were identified by Dave for project 2 only, so I expect there are a lot more files from other projects:

SG-1614BBBK1880	2016-10-25 to 2018-04-03
SG-1614BBBK1900
SG-1614BBBK1613	2014-06-14 to 2015-04-30, 2016-09-20 to 2017-11-20
SG-1614BBBK1954
SG-4005BBBK4310	2015-06-05 to 2017-11-17
SG-4001BBBK2310	2016-04-11 to 2017-05-12
SG-4002BBBK0360	2015-05-15 to 2018-02-26
SG-4005BBBK3400	2015-05-25 to 2016-09-16
SG-1614BBBK1618
SG-4001BBBK1670	2015-11-30 to 2016-08-04
SG-1614BBBK1954	2017-04-08 to 2017-09-05
SG-1614BBBK1869	2014-06-02 to 2016-11-07
SG-1614BBBK1911	2014-10-08 to 2016-11-12
SG-1614BBBK1954
SG-4001BBBK2010	2015-09-30 to 2018-01-27 (m Sep/Oct 2017)
SG-4001BBBK2310	2015-05-24 to 2015-11-05
SG-4002BBBK0020	2015-11-23 to 2018-01-27, m may/jun 2017
SG-1614BBBK1638	2014-05-18 to 2016-11-26
SG-4001BBBK2330	2015-07-29 to 2017-11-16 m may-nov 2016
SG-1614BBBK1663	2016-04-27 to 2017-04-29
SG-4002BBBK2240	2015-08-03 to 2016-04-25, 2016-11-13 to 2018-02-25

**Comment by zcrysler** [comment]
Sorry, the list wasn't clear, the dates given are the dates we have data for. So for example the receiver that brought this issue up is SG-1614BBBK1613, it should have data between 2015-04-20 and 2016-09-20, but there's none online. Apparently Dom has seen this processed data at some point and is sure it exists.

**Comment by Hussell** [comment]
Lucas, I think this issue got dropped during the transition from Zoe to you. It would be helpful to get a description of the problem from Dave (Dom?), since the info we have here is contradictory.

**Comment by leberrigan** [comment]
Thanks for bringing this up. I can talk with them about these issues to see if anything has changed on their end.
