### ISSUE TITLE
Project 159 manual tag registration

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#375]
tag 101 should have been registered at the same time as tags 25795-25798 but failed. I can't find the original upload as it was back in June 2017. Jeremy if you can find the original upload can you try re-registering this tag, otherwise Catherine can you manually register it?

NTQB-2, BI ~19.89

**Comment by Hussell** [comment]
I haven't found any files older than about August 2017 in the upload directories of the users registered with project 159.

**Comment by zcrysler** [comment]
Catherine can you try manually registering?

**Comment by cjardine-bsc** [comment]
Tags 25795-25798 were registered to project 161, not 159. Can you confirm the project you want this tag with mfg_id 101 registered to?

Frequency = 166.38 period = 19.8948

**Comment by zcrysler** [comment]
Sorry, they were originally registered to project 159 and then we moved them to project 161 a week or two ago. So I thought the original upload would have been to 159. 

This tag should be put in project 161

**Comment by cjardine-bsc** [comment]
Done.
