### ISSUE TITLE
Deployment Location Incorrect - should only have deployments for selected project

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#377]
Some error messages for Deployment Location Incorrect, refer to gps points taken during a deployment from another project. For example, the following error under project 1:

Receiver deployment ID: 2192, # of days: 1 | View \| Edit |  
-- | -- | --

the "edit" button takes you to an error page: https://motus.org/data/receiver/deployment/edit?projectID=1&id=2192 because it's referring to a deployment in project 54 which is only apparent if you click "view": https://motus.org/data/receiverMap?receiverDeploymentId=2192.

I can see that this receiver exists in both projects, but only since I have access to both, a regular user wouldn't be able to determine which receiver this is associated with. But regardless, since this error is deployment - and not receiver - specific, I don't think I should see errors for another project for this error

**Comment by cjardine-bsc** [comment]
Ah, Denis, Jeremy and I had an email exchange about this months ago which was still in my inbox and hadn't been put to bed. Until now! 

It involved a change to one of the base views: vwBase_gps 

Denis and I conferred on the change, but just keep an eye out for anything wonky, this change might have repercussions elsewhere.

**Comment by zcrysler** [comment]
Seems to have fixed the issues for project 1, I'll close for now
