### ISSUE TITLE
Update Error text fragment

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#378]
Small thing, but can we update the error message for "receiver not registered" from:

Receiver detection data has been uploaded by a user registered to this project, however the receiver is not registered to _any_ project.

to:

Receiver detection data has been uploaded by a user registered to this project, however the receiver is not registered to _this_ project.

Since the receivers in this error are actually registered to a project, just not the one in question.

**Comment by cjardine-bsc** [comment]
done
