### ISSUE TITLE
Large number of detections on SG-4005BBBK4150

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#379]
There are some detections listed as ?proj?-168#370:7.1 M.31095 which belong to project 168 but aren't being listed as such. The metadata is entered online so I'm not sure why it's not assigning the right project name.

There are also a large number of false positives at this station, is this just a noisy site or is there something going on with detections for these tags?

**Comment by Hussell** [comment]
Listed here: https://sgdata.motus.org/download/168/SG-4005BBBK4150-2018_MONTREAL_MOULT_McGill_Bird_Observatory_hourly_tags.png

The detections with the question marks are all from outside of known tag deployments. Detections of many of the same tags, inside known deployments, are shown further down the chart.

The station is at a bird observatory where tags were being put on (and, apparently, tested), so we should expect a large number of different tags to be detected there. Other than that, how do you know there are a lot of false detections?

**Comment by zcrysler** [comment]
As far as I know, only tags for the Montreal Moult project are being tagged there: AtlCanShorebirds are being tagged in NB, BARS migration don't have deployment info yet but are in ON, same with GuelphBARS, SNPL detections were all from birds tagged in Oklahoma.

All these tags only start showing up once the Montreal Moult project starts deploying, so it seems like a strange coincidence. The user alerted me to this, they're tagging and hand tracking in the area and feel like these are all false detections and I agree.

**Comment by Hussell** [comment]
Looking at the detections in the database, it looks like there are a lot of runs of length 3-8 which may be false detections. So, the noisy-site hypothesis seems plausible? This is just from the most recent batches for the dates covered by the plot.

**Comment by adamdsmith** [comment]
Not to crash this issue, but does the same "noisy site" hypothesis apply to SG-1215BBBK1791 (project 150)? This site:
- produces large numbers of files in a short period of time
- often detects tags with the same ID across multiple projects
- repeatedly detects tags over a period of several weeks

**Comment by tabanid** [comment]
I would also look at tag aliasing ... which is the likely culprit here.

**Comment by zcrysler** [comment]
There are also some tags that only start being detected Sept 26th but were deployed in August, you can see they all clearly start being detected on the same day despite existing deployments: https://sgdata.motus.org/download/168/SG-4005BBBK4150-2018_MONTREAL_MOULT_McGill_Bird_Observatory_hourly_tags.png

8
MONTREAL_MOULT#373:7.1 M.31259
MONTREAL_MOULT#374:7.1 M.31260
MONTREAL_MOULT#375:7.1 M.31261
MONTREAL_MOULT#376:7.1 M.31283
MONTREAL_MOULT#377:7.1 M.31284
MONTREAL_MOULT#378:7.1 M.31285
MONTREAL_MOULT#379:7.1 M.31286
MONTREAL_MOULT#380:7.1 M.31287
MONTREAL_MOULT#381:7.1 M.31288
MONTREAL_MOULT#382:7.1 M.31289
MONTREAL_MOULT#383:7.1 M.31290
MONTREAL_MOULT#384:7.1 M.31291
MONTREAL_MOULT#385:7.1 M.31292
MONTREAL_MOULT#386:7.1 M.31293
MONTREAL_MOULT#387:7.1 M.31294
MONTREAL_MOULT#388:7.1 M.31295
MONTREAL_MOULT#389:7.1 M.31296
MONTREAL_MOULT#390:7.1 M.31297
MONTREAL_MOULT#391:7.1 M.31298
MONTREAL_MOULT#487:10.3 M.31244
MONTREAL_MOULT#488:10.3 M.31245
MONTREAL_MOULT#492:10.3 M.31248
MONTREAL_MOULT#493:10.3 M.31249
MONTREAL_MOULT#495:10.3 M.31251
MONTREAL_MOULT#496:10.3 M.31252
MONTREAL_MOULT#497:10.3 M.31253
MONTREAL_MOULT#521:5.9 M.26315

**Comment by Hussell** [comment]
I reran this receiver, and some issues disappeared. I'm assuming metadata about tag deployments were updated at some point. Many false positive detections remain, which may be due to aliasing as Phil suggested, since there were many tags being detected simultaneously for long periods.
