### ISSUE TITLE
Tag template processing fails when tab-delimited file uploaded

### ISSUE THREAD

**Issue by pmorrill** [MotusDev/Motus-TO-DO#380]
Our processing assumes comma-value delimited files. The following looks to have been generated when a tab-delimited file was uploaded: the column headers are lumped into a single 'custom property' name.

It is a little hard to sanity-check this with 100% assurance. But we could look for:

- unusually long custom property names
- presence of tabs embedded into the property name

The Exception trace follows:

Error type = 7 - Low-level Database error
Error Code = 547
SQL = INSERT INTO api_tag_properties (apiBatchID,rowNum,propNum,propName,propValue) VALUES
(46428,421,0,'tagID  tagProjectID    dateBin mfgID   period  lifeSpanDays    tagDeployID  
utcYearStart    utcMonthStart   utcDayStart     utcHourStart    utcMinuteStart  utcYearEnd
utcMonthEnd     utcDayEnd       utcHourEnd      utcMinuteEnd    deferSec       
speciesName     markerNumber    markerType      decimalLatitude decimalLongitude       
elevationMeters sex     age     weightGrams     wingMillimeters tarsusMillimeters      
culmenMillimeters       billMillimeters headMillimeters fatScore        comments       
test','19004    14      2016-2  94      4.6974          13441   2016    6       27      0 
0                                                       Sterna antillarum                 
41.3509883      -71.6634383                                                               
FALSE'),
(46428,422,0,'tagID     tagProjectID    dateBin mfgID   period  lifeSpanDays   
tagDeployID     utcYearStart    utcMonthStart   utcDayStart     utcHourStart   
utcMinuteStart  utcYearEnd      utcMonthEnd     utcDayEnd       utcHourEnd     
utcMinuteEnd    deferSec        speciesName     markerNumber    markerType     
decimalLatitude decimalLongitude        elevationMeters sex     age     weightGrams    
wingMillimeters tarsusMillimeters       culmenMillimeters       bill...
Description = Creating prepared statement on: tags (Made it to result set wrapper)

Browser info:Unknown
Auth type = Unknown
Method = Unknown
Query = Unknown
Uri = Unknown
All parameters:Unknown
Stack trace:
com.microsoft.sqlserver.jdbc.SQLServerException: The INSERT statement conflicted with the
FOREIGN KEY constraint "FK_api_tag_properties_api_tag_deployments". The conflict occurred
in database "motus", table "dbo.api_tag_deployments".
        at
com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.j
ava:216)
        at
com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515
)
        at
com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServ
erPreparedStatement.java:404)
        at
com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServe
rPreparedStatement.java:350)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
        at
com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1
715)
        at
com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180
)
        at
com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:1
55)
        at
com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedSta
tement.java:314)
        at org.bsc.SQLPreparedStmt.executeUpdate(SQLPreparedStmt.java:229)
        at org.bsc.motus.TagBean.insertRecords(TagBean.java:507)
        at org.bsc.motus.TagBean.processCSVRecord(TagBean.java:449)
        at org.bsc.motus.ApiImport.walkCSV(ApiImport.java:105)
        at org.bsc.motus.TagBean.uploadBulkDeployments(TagBean.java:424)
        at
org.bsc.motus.web.UploadTagTemplateServlet.doPost(UploadTagTemplateServlet.java:133)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.ja
va:291)
        at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.ja
va:239)
        at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

        at org.bsc.motus.web.SetupFilter.doFilter(SetupFilter.java:86)
        at
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.ja
va:239)
        at
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)

        at
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at
org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)

        at
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
        at
org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:844)
        at
org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java
:668)
        at
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
        at
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Unknown Source)

**Comment by denislepage** [comment]
Would it be easy to switch the import process from CSV to tabs if tabs are detected in place of commas in the header? The alternative would be to return an error.

Are we checking for a few key fields such as tag I'd before trying to insert? If so, the tabs should prevent the import from proceeding?

**Comment by pmorrill** [comment]
I think that the fastest sol'n is what you propose: verifying that there is a tagID column present - and presenting an error is not, Switching to CSVReader that recognizes tabs instead of commas is possible, but a little more elaborate.

**Comment by denislepage** [comment]
that sounds good.
