### ISSUE TITLE
Error when looking up landowners

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#381]
I've run into this before and I'm not entirely sure what makes it happen, but in project 1, on the landowners page (https://motus.org/data/project/sites?projectID=1) you automatically start on the "project sites" tab, sometimes when I switch to the "project landowners" tab I get the below error, sometimes I don't. It first started if I searched for a name and then switched tabs, sometimes I get the error if all i do is try to search. This might be hard to troubleshoot because it doesn't happen consistently, but it was happening earlier this week and again today.

An error has occurred while we were processing your request.
This error has generated an email that has automatically been sent to the technical support staff. We will investigate this problem and will try to resolve as quickly as possible. It is possible that this was only an error caused by a temporary condition, and that you will not get this error again. If that is the case, then whichever operation that failed should succeed if you try it again. If it does not, then you can assume that there is a problem which we will need to resolve from our end.

If you wish to contact us about this error, please provide this reference number: 1538606981835

(The rest of this page is only visible to administrators like you.)

These details have been sent by email:

Motus Application error (motus.org)
Error reference number: 1538606981835

**Comment by denislepage** [comment]
I think this is fixed in beta but I was waiting to hear back from Jeremy to post to live. If you want to try in beta.

**Comment by zcrysler** [comment]
In Beta I was able to swtich between tabs a few times with no issues, but then when I searched for a name under landowners it gave me the error page. Seems to happen whether you search for an existing name or a non-existing name
