### ISSUE TITLE
tagme() error "Failed to generate hits for tag project"

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#386]
A user is downloading data for their project, they keep getting the below error through tagme(), it starts up again if they re-run the line, but they only get a few batches downloaded and then it stops again. Any idea as to the cause?

Error in srvQuery(API = Motus$API_HITS_FOR_TAG_PROJECT, params = list(projectID = projectID,  : 
  Failed to generate hits for tag project.

I was also receiver API errors from the same user which I had sent to Jeremy, an example is below:
API Error generated: Failed to generate hits for tag project.

User:  - Elora Grahame

Service: /sgdata/custom/hits_for_tag_project

Parameters:

json => {"authToken":"oGnCutdHvkJD8xK1wM5R1B6_eDULYpiNtTGKEQBzzMCX","projectID":194,"batchID":176410,"hitID":511176972}

Exception: org.bsc.exceptions.DBException com.microsoft.sqlserver.jdbc.SQLServerException: Socket closed SQL: "SELECT top (10000) * FROM vwR_Hits_for_tag_project a  WITH(NOLOCK)  WHERE hitID > ? AND batchID = ?  AND projectID = ? ORDER BY hitID"

Trace:

------------------------
org.bsc.SQLPreparedStmt.executeQuery(SQLPreparedStmt.java:271)
org.bsc.motus.servlets.SGDataAPI.sendHits(SGDataAPI.java:659)
org.bsc.motus.servlets.SGDataAPI.doPost(SGDataAPI.java:164)
javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:844)
org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
java.lang.Thread.run(Unknown Source)

**Comment by pmorrill** [comment]
Could our mssql experts (C and D) inspect the query itself and let us know if there is a potential for problems there, given the large size of the batch, the structure of the query, the ordering requirement, the underlying view? I will go through the Java code - though it is pretty minimal.

> Exception: org.bsc.exceptions.DBException com.microsoft.sqlserver.jdbc.SQLServerException: Socket closed SQL: "SELECT top (10000) * FROM vwR_Hits_for_tag_project a WITH(NOLOCK) WHERE hitID > ? AND batchID = ? AND projectID = ? ORDER BY hitID"
