### ISSUE TITLE
Project #219 manual tag registration

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#391]
Tags 206 and 215, and with a BI of ~7s should have registered at the same time as tags 32131-3214, but failed.  User tried to upload twice more but still failed.

Tags 32417 (209) and 32418 (217) were registered with BI of ~14 s instead of ~7 s. Need to be deleted and re-registered.

Can these be uploaded manually?

NTQB-2, BI ~7s

**Comment by cjardine-bsc** [comment]
Hey Lucas, 

I can upload manually, but there are a few things I want to check first. Manual registration should always be a last resort. 

If the tags are still in the users possession (i.e. not on a bird somewhere) they should re-record them and re-upload. That includes tags that registered with the wrong BI. We can then merge the incorrect registration with the correct one. 

You can also check with the user to see if they recorded with a lotek receiver or a SG funcube. We were having some troubles similar to what you describe above with .wav files recorded from Lotek. 

Finally, you can ask the user if they have the shipping sheet that came with their lotek tags. That will have the exact BI for the tags on it. The ~ symbol gives me anxiety :D

**Comment by leberrigan** [comment]
Thanks Catherine. I understand where the anxiety could be coming from!

He sent me all recordings and it may merely be that the recordings are just not 'loud' enough.

I'll see what he has to say.

**Comment by leberrigan** [comment]
User says they are recording with a AOR (AR8200) wide range receiver and a Zoom H4n handheld recorder to record tags but it produces lots of noise so they apply the noise filter on Audacity to fix this issue. I will recommend they get their hands on a Funcube Pro or Lotek receiver to record the tags, otherwise continue with current method with higher gain on recorder. Any other suggestions?

**Comment by leberrigan** [comment]
After a fourth try, I managed to get 209 (32441) and 217 (32442) registered with the correct burst interval, but 206 and 215 are still not working.

I think the user has exhausted their options for recording tags - how should we proceed? Recordings are attached below.
[unregistered_Tags.zip](https://github.com/MotusDev/Motus-TO-DO/files/2595389/unregistered_Tags.zip)

**Comment by jbrzusto** [comment]
Looking at the signal directly in audacity:

### 206 ###

- recording rate: 96 ksps
- pulses appear of equal length, but 50% wider than in a clean recording;
  there's probably ringing or an echo somewhere.
- gaps between four pulses in first burst are c(6327, 3815, 11755) samples,
  which is consistent with Lotek ID 206
- gap between first pulse in bursts 1, 7 is 4089003 samples, which translates
  into a burst interval of 7.099 seconds

### 215 ###
- recording rate: 96 ksps
- gaps in first burst consistent with Lotek ID 215
- gap between first pulses in bursts 1, 8 is 4770172, which translates
  into a burst interval of 7.098 seconds

I'm manually registering these two tags on the server like so:

```R
library(motusServer)
## silly boilerplate code to load some required globals
getMotusMetaDB()
ensureServerDB()

motusQuickRegTag(projectID=219,
   mfgID="215",
   period=7.098,
   model="NTQB2-6-1",
   species="DUNL",
   nomFreq=150.1,
   tsStart=lubridate::ymd_hms("2018-10-10T00-00-00"),
   dateBin="2018-4"
)

motusQuickRegTag(projectID=219,
   mfgID="206",
   period=7.099,
   model="NTQB2-6-1",
   species="DUNL",
   nomFreq=150.1,
   tsStart=lubridate::ymd_hms("2018-10-10T00-00-00"),
   dateBin="2018-4"
)
```


Catherine:  motus tags 32417, 32418 should be deleted; they
are duplicate registrations of 32441, 32442 but with the
wrong BI.

**Comment by cjardine-bsc** [comment]
I've merged those old incorrect tags into the new tags and deleted the old registrations.
