### ISSUE TITLE
bscutil.js

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#397]
/scripts/bscutil.js used to be referenced from Motus pages, but it has been removed from the folder. It is however still included in the banner and coming up with a 404 error.

Assuming the file isn't used anymore, we should remove it from the WordPress headers.

**Comment by Hussell** [comment]
I'm getting 200 OK for https://motus.org/scripts/bscutil.js

**Comment by cjardine-bsc** [comment]
Denis may have put it back when he discovered the 404 error. 

Do you know why it might have been removed? Are you still using it?

**Comment by Hussell** [comment]
So far as I can recall bscutil.js has never been used on the /data part of the site. It isn't referenced by the stripped headers, so any use of it must be in the WordPress part of the site.

**Comment by denislepage** [comment]
The 404 was limited to Sandbox.
https://sandbox.motus.org/scripts/bscutil.js?ver=1.0

If we don’t use any functionalities from it, we should prevent it from loading.

To be safe, we should probably grep all of the function names included in the file to confirm that none are  in use. If the file is missing from sandbox, we would probably have known by now. I don’t think we really use Javascript on WordPress, except for a couple pages like the maps.

**Comment by Hussell** [comment]
I confirmed that none of the functionality in bscutil.js is being used (by searching for each of the function names). I removed the line that loads the script from the headers on sandbox and beta. Appearance -> Editor -> functions.php, remove this line:

wp_enqueue_script( 'bscutil', '/scripts/bscutil.js', array( 'jquery1-11-0' ), '1.0', false );

Catherine, would you remove this line from the live WordPress sometime? (No hurry.)

I've deleted the script from the sandbox and beta servers.

**Comment by cjardine-bsc** [comment]
Done :)
