### ISSUE TITLE
Duplicate Data in Project 214

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#398]
I have a user with many duplicates within their dataset. They are identical save the batchID and runID, a similar issue as in #267. Multiple receivers have duplicates. Example:

hitID | runID | batchID | ts | sig | sigsd | noise | freq | freqsd | slop | burstSlop | done | motusTagID | ambigID | port | runLen | bootnum | tagProjID | mfgID | tagType | codeSet | mfg | tagModel | tagLifespan | nomFreq | tagBI | pulseLen | tagDeployID | speciesID | markerNumber | markerType | tagDeployStart | tagDeployEnd | tagDeployLat | tagDeployLon | tagDeployAlt | tagDeployComments | fullID | deviceID | recvDeployID | recvDeployLat | recvDeployLon | recvDeployAlt | recv | recvDeployName | recvSiteName | isRecvMobile | recvProjID | antType | antBearing | antHeight | speciesEN | speciesFR | speciesSci | speciesGroup | gpsLat | gpsLon | gpsAlt
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
6.61E+08 | 33626598 | 187590 | 1537340304 | -4.7199 | 3.5665 | -27.0198 | 1.8365 | 0.0015 | 2.00E-04 | 0 | 1 | 31834 | NA | 1 | 15 | 8 | 214 | 150 | ID | Lotek4 | Lotek | NTQB-6-2 | NA | 151.5 | 5.3004 | 2.5 | 19509 | NA | NA | NA | 1.54E+09 | 1.6E+09 | NA | NA | NA | NA | Wyndham Finches 2018#150:5.3@151.5(M.31834) | 1144 | 4911 | -15.4708 | 128.1068 | 116 | SG-E561RPI3DE10 | Quarry.1 | Quarry | 0 | 214 | yagi-5 | 207.8419 | 4.7 | NA | NA | NA | NA | -15.4708 | 128.1068 | 105
6.61E+08 | 33626598 | 187590 | 1537340384 | -4.8624 | 1.5359 | -26.5959 | 1.8345 | 0.0018 | 3.00E-04 | 0 | 1 | 31834 | NA | 1 | 15 | 8 | 214 | 150 | ID | Lotek4 | Lotek | NTQB-6-2 | NA | 151.5 | 5.3004 | 2.5 | 19509 | NA | NA | NA | 1.54E+09 | 1.6E+09 | NA | NA | NA | NA | Wyndham Finches 2018#150:5.3@151.5(M.31834) | 1144 | 4911 | -15.4708 | 128.1068 | 116 | SG-E561RPI3DE10 | Quarry.1 | Quarry | 0 | 214 | yagi-5 | 207.8419 | 4.7 | NA | NA | NA | NA | -15.4708 | 128.1068 | 117.4
6.59E+08 | 33353038 | 186336 | 1537585309 | -16.3751 | 10.4494 | -29.8046 | 3.5095 | 0.0126 | 2.00E-04 | 0 | 1 | 31834 | NA | 2 | 124 | 13 | 214 | 150 | ID | Lotek4 | Lotek | NTQB-6-2 | NA | 151.5 | 5.3004 | 2.5 | 19509 | NA | NA | NA | 1.54E+09 | 1.6E+09 | NA | NA | NA | NA | Wyndham Finches 2018#150:5.3@151.5(M.31834) | 1124 | 4909 | -15.4628 | 128.1177 | 151 | SG-AED4RPI38099 | Powerline.1 | Powerline | 0 | 214 | yagi-5 | 182.843 | 5 | NA | NA | NA | NA | -15.4627 | 128.1177 | 156.6
6.59E+08 | 33353037 | 186336 | 1537585309 | -13.8718 | 4.4263 | -34.7563 | 3.4928 | 0.0016 | 2.00E-04 | 0 | 1 | 31834 | NA | 3 | 122 | 13 | 214 | 150 | ID | Lotek4 | Lotek | NTQB-6-2 | NA | 151.5 | 5.3004 | 2.5 | 19509 | NA | NA | NA | 1.54E+09 | 1.6E+09 | NA | NA | NA | NA | Wyndham Finches 2018#150:5.3@151.5(M.31834) | 1124 | 4909 | -15.4628 | 128.1177 | 151 | SG-AED4RPI38099 | Powerline.1 | Powerline | 0 | 214 | yagi-5 | 120.843 | 5 | NA | NA | NA | NA | -15.4627 | 128.1177 | 156.6
6.59E+08 | 33353039 | 186336 | 1537585309 | -7.8855 | 12.7742 | -28.9643 | 3.4975 | 0.0023 | 2.00E-04 | 0 | 1 | 31834 | NA | 1 | 123 | 13 | 214 | 150 | ID | Lotek4 | Lotek | NTQB-6-2 | NA | 151.5 | 5.3004 | 2.5 | 19509 | NA | NA | NA | 1.54E+09 | 1.6E+09 | NA | NA | NA | NA | Wyndham Finches 2018#150:5.3@151.5(M.31834) | 1124 | 4909 | -15.4628 | 128.1177 | 151 | SG-AED4RPI38099 | Powerline.1 | Powerline | 0 | 214 | yagi-5 | 242.843 | 5 | NA | NA | NA | NA | -15.4627 | 128.1177 | 156.6
6.61E+08 | 33626585 | 187588 | 1537585309 | -16.3751 | 10.4494 | -29.8046 | 3.5095 | 0.0126 | 2.00E-04 | 0 | 1 | 31834 | NA | 2 | 124 | 13 | 214 | 150 | ID | Lotek4 | Lotek | NTQB-6-2 | NA | 151.5 | 5.3004 | 2.5 | 19509 | NA | NA | NA | 1.54E+09 | 1.6E+09 | NA | NA | NA | NA | Wyndham Finches 2018#150:5.3@151.5(M.31834) | 1124 | 4909 | -15.4628 | 128.1177 | 151 | SG-AED4RPI38099 | Powerline.1 | Powerline | 0 | 214 | yagi-5 | 182.843 | 5 | NA | NA | NA | NA | -15.4627 | 128.1177 | 156.6

More examples:

[proj214Duplicates.txt](https://github.com/MotusDev/Motus-TO-DO/files/2549720/proj214Duplicates.txt)

- Is this a result of a receiver rerun? 
- Can these duplicates be removed from the database or does the user have to sort it out?

**Comment by denislepage** [comment]
Duplicates is a well known issue caused by re-runs of previous data (there could be other reasons, such as resubmitting a file that contains some of the same data). We are now excluding at least some of the duplicate batches, but not all. I am not 100% sure where the filtering is currently applied (e.g. in the R views), and what is it exactly that we "should" do.

First issue: how to correctly identify duplicates. This is theoretically done on the basis of the boot number for each receiver. This is however not a perfect solution. Re-runs for the same boot numbers do not always have the same start and end TS. This is one of outstanding issues that John was working on.

Once duplicates are correctly identified, I am of the opinion that "all batches" should be provided to users in R, including duplicates, rather than only the most recent ones. We should in addition, provide the filters to identify which batches are duplicated. We could further make the default R view only show the most recent batches, for instance.

A downside is that this approach increases the data file size, and could confuse users.

Our web outputs will be mostly based on the most recent batches, but again, we don't have a safe way to correctly identify all duplicate batches yet.

**Comment by cjardine-bsc** [comment]
The filtering of duplicates is currently being applied to the R views and all the website views.

I see a conceptual difference between filtering out re-run of batches using the same parameterization but updated metadata, and the re-run of batches using different parameterization (i.e. tighter filters for noisy sites). We have lots of the former in the database at the moment, but as of yet we don't have any of the latter. We do have plans to differentiate these two concepts in the future using the batch_filter categories: 

0	valid	
1	invalid 
2	deprecated (re-run)	
3	noisy

At the moment I'm filtering out 1s and 2s from all outputs. But I'd agree that 3s should stay in future exports if we get to the point where we are able to run tagfinder with different parameterization. 

So, if these data are showing up from a recent download in R then the batches were not correctly identified as duplicates. Right now batches are only counted as duplicates if they have the same deviceID, monoBN, tsBegin and tsEnd. See https://github.com/jbrzusto/motusServer/issues/407
There are duplicates that don't match those requirements though, as you can see from #407. 

In these cases you can send me the batch IDs and we can manually flag them as duplicates. We'll have to carefully check that there isn't data in an earlier batch that isn't covered in a subsequent batch.  This isn't ideal but until we can get firm answers in terms of what constitutes a duplicate batch we won't have a way to automate this any more then we already are. 

Note that they should try a complete re-download of their SQLite file. If they are just adding new data to their file that wont remove the duplicates that they've already downloaded.

**Comment by cjardine-bsc** [comment]
There were some duplicate batches that were previously being included that we can now exclude. Cases where the subsequent batch completely encompasses the time frame of the previous batch (a-okay)  for the same device ID (regardless of boot number).

I've now implemented these changes on the live database. 

That's probably the best we will ever do in terms of filtering out entire batches. Batches that partially overlap will need to remain and we will have to flag runs from the previous batch that are overlapped by the subsequent batch.
