### ISSUE TITLE
Error Messages not Sending to Motus Email

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#400]
Recent error messages seen on 'Uploads' page for Project 145 (#399) says an email will automatically be sent to technical support staff, but no email received on my end.
https://motus.org/data/project/sgJobs?projectID=145

I have not yet received any automatic error messages from the Motus website since I started on Oct 10.

**Comment by Hussell** [comment]
The automatic error emails of this type get sent to Denis, I think.

**Comment by denislepage** [comment]
Can you confirm how they are caught, to what email address they go, and what SMTP server is being used?

I am not seeing them.

Thanks

**Comment by Hussell** [comment]
The handler for Java errors on the Motus website is set by an entry in web.xml (error-page). On the live website, the handler is /motus/web/WEB-INF/data/info.jsp, and everywhere else it's error.jsp which doesn't send emails. (I made certain, the live website is pointing to info.jsp not error.jsp.) info.jsp gets the mail server and email address from MotusProjInfo, which delegates to ProjInfo, where I lose the trail (the code for setting the mail server is opaque to me at first glance). But info.jsp also displays detailed information along with the error message if you're logged in as an administrator, and that includes the stringification of MotusProjInfo, which includes the line "MailServer: saturn.kwic.com", but doesn't include the error email. Going back to ProjInfo, it looks like the error email is retrieved from the database, adm_proj.error_email. The value of that column in the live Motus database is 'support@bsc-eoc.org,cjardine@birdscanada.org'. Maybe a comma-separated list of emails doesn't work?

**Comment by denislepage** [comment]
The comma-separated list should be properly parsed by the SendMail method (which generates 2 separate emails). Jeremy and I figured out that emails are being sent to him right now (based on web.xml settings), but they don't seem to ever reach him. If I change the address to myself, it works fine. He will add an exception to use the database adm_proj value for the live site.

We'll also have to address the underlying issue (casting of the JSON), but that is a separate topic.

**Comment by StuMackenzie** [comment]
I'm still getting the error when logged in as project 145.

**Comment by Hussell** [comment]
I'd like to figure out why I'm not receiving anything sent from the live site before we close this. It might be related to a few previous reports of emails not being received which we were never able to replicate on sandbox or beta.
