### ISSUE TITLE
404 error from track tool when selecting many tracks

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#402]
I tried to use the track tool to make a map of bat movements in N.A. today and I’m getting a 404 error when I click on “make map” 
 
I’m selecting a lot of tags because I wanted all bat tracks. The URL it’s trying to send me to is: https://motus.org/data/tracksMap?t=4976&t=10510&t=19217&t=19221&t=19222&t=19231&t=19718&t=15927&t=2451&t=254&t=255&t=257&t=258&t=268&t=271&t=274&t=301&t=375&t=2373&t=2462&t=4197&t=4888&t=4970&t=5255&t=5256&t=5257&t=5279&t=5297&t=8500&t=8505&t=8506&t=8508&t=8509&t=8511&t=8512&t=9094&t=9095&t=9136&t=9138&t=9141&t=9142&t=9143&t=9148&t=9151&t=9152&t=9153&t=9154&t=9212&t=9213&t=9643&t=9644&t=9646&t=9647&t=9651&t=10505&t=10506&t=10507&t=10520&t=10521&t=10522&t=10523&t=10524&t=11935&t=11966&t=12023&t=12031&t=12033&t=12063&t=12070&t=13877&t=14076&t=14077&t=14093&t=14095&t=14510&t=14514&t=14515&t=14664&t=4971&t=4972&t=4975&t=5421&t=19228&t=256&t=295&t=300&t=5252&t=5273&t=8510&t=10519&t=2304&t=2306&t=2308&t=2309&t=2310&t=2311&t=2312&t=2315&t=2317&t=2318&t=2319&t=2321&t=2322&t=2324&t=2325&t=2326&t=2327&t=2329&t=2332&t=2333&t=2334&t=2337&t=2338&t=2339&t=2340&t=2343&t=2349&t=2350&t=2353&t=2354&t=2357&t=2358&t=2369&t=2371&t=2384&t=2385&t=2386&t=2389&t=2390&t=2392&t=2395&t=2396&t=2399&t=2401&t=2403&t=2405&t=2406&t=2407&t=2408&t=2409&t=2411&t=2413&t=2417&t=2419&t=2421&t=2423&t=2425&t=2426&t=2442&t=2445&t=10891&t=10893&t=10894&t=10895&t=10897&t=19885&t=264&t=265&t=266&t=267&t=272&t=273&t=275&t=277&t=278&t=280&t=282&t=284&t=292&t=294&t=307&t=311&t=312&t=314&t=315&t=316&t=317&t=318&t=319&t=338&t=339&t=340&t=342&t=344&t=345&t=346&t=347&t=348&t=349&t=350&t=351&t=352&t=354&t=355&t=357&t=358&t=359&t=360&t=361&t=362&t=363&t=364&t=365&t=366&t=367&t=368&t=369&t=371&t=372&t=2466&t=2467&t=2468&t=2469&t=2470&t=2471&t=2472&t=2473&t=2474&t=2475&t=2476&t=2477&t=2478&t=2479&t=2480&t=2481&t=2482&t=2483&t=2484&t=2485&t=2486&t=2487&t=2488&t=2489&t=2490&t=2491&t=2492&t=2493&t=2494&t=2495&t=2496&t=2499&t=2500&t=2501&t=7427&t=8624&t=9632&t=9633&t=18214&t=18216&t=18977&t=18983&t=4973&t=10892&t=10896&t=12631&t=19219&t=19226&t=251&t=259&t=261&t=269&t=270&t=297&t=299&t=303&t=343&t=373&t=374&t=4252&t=5246&t=5250&t=5267&t=5268&t=5269&t=5270&t=5271&t=5295&t=5298&t=8952&t=9137&t=9139&t=9140&t=9144&t=9149&t=9150&t=9155&t=9156&t=9157&t=9158&t=9159&t=9160&t=9161&t=9162&t=9163&t=9165&t=9166&t=9167&t=9168&t=9169&t=9170&t=9171&t=9172&t=9173&t=9174&t=9175&t=9177&t=9179&t=9180&t=9181&t=9182&t=9184&t=9185&t=9186&t=9187&t=9188&t=9189&t=9190&t=9191&t=9192&t=9193&t=9194&t=9195&t=9196&t=9197&t=9198&t=9200&t=10760&t=10762&t=10763&t=11294&t=11447&t=11448&t=11934&t=11965&t=12027&t=12028&t=13860&t=13861&t=13862&t=13863&t=13864&t=13865&t=13866&t=13867&t=13868&t=13869&t=13870&t=13871&t=13872&t=13873&t=13874&t=13875&t=13876&t=13878&t=13879&t=13880&t=13881&t=13882&t=14073&t=14075&t=14078&t=14079&t=14082&t=14083&t=14085&t=14087&t=14088&t=14089&t=14090&t=14091&t=14092&t=14094&t=14302&t=14508&t=14526&t=14540&e=2013-01-01&l=2018-12-31&s=100190&s=100230&s=100250&s=100270&s=100370&s=100420&s=100430&s=100450&s=100460&s=100580&s=119680&s=123940 
 
When I use just one tag it works: https://motus.org/data/tracksSelect?e=2013-01-01&l=2018-12-31&s=100190&s=100230&s=100250&s=100270&s=100370&s=100420&s=100430&s=100450&s=100460&s=100580&s=119680&s=123940
 
If there is a limit on the number of tags we can select in this tool we should make that clear and not allow users to select beyond that limit. 
 
I can make a git issue if you’d prefer.

**Comment by denislepage** [comment]
The maximum length of a URL with a GET call is 2083 characters in some browsers. That seems to apply to Firefox. This particular URL has 2821. If you truncate it under 2080, that works.

One workaround is to use a POST method, but that prevents users from copying their URL for sharing. Which brings me back to the idea of converting URL’s into short links, and offering the users to save them in the database (I wouldn’t save all URL’s, but just those requested by users).

We could rebuild the list of parameters in a hidden field, and allow users to save this for future uses.

https://motus.org/data/tracksMap?id=f6a11ba5

As a minimum, I think we should change the call for  POST.

**Comment by StuMackenzie** [comment]
Getting this again when searching Purple Martin. Perhaps if the fix isn't a priority, or a little more complicated, we could just add the instruction ' will only work for XX number of birds'. Unfortunately given the size of the database I think many species will return this error.

**Comment by denislepage** [comment]
Almost certainly due to the length of the URL. Changing to a POST would fix that, but also prevents from sharing the URL.

I’ve asked for this for a while, but having a short-url function that allows saving the parameters and creating a shortcut would address that:

E.g. https://motus.org/tracks/f65a001c

Where we have a table where the key links to the parameter string (e.g. a JSON object) to be parsed as the input.

If we have a button/link on the page that says “share this URL”, builds a json objects and sends it to a url where a key is generated, and saved with the json string, and then the key is returned to the calling page, and finally displayed to the users.

**Comment by StuMackenzie** [comment]
Closing in deference to https://github.com/MotusDev/Motus-TO-DO/issues/894 where track search issues can be consolidated.
