### ISSUE TITLE
Tag Deployment Template Fields

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#403]
Fields for tag deployment need to be updated or clarified.

1.  'Band Number' and 'Marker Number' are probably the same thing. Should just keep marker number and marker type combo. 
2.  There is no field for 'Band Number' in bulk tag deployment template CSV ('MotusTagsTemplate')
3. Fields with restricted values (such as 'Age' and 'Sex') are not restricted in bulk uploads tag deployment template resulting in some values not appearing on web interface. For instance, if '5' is entered instead of 'Female', nothing will be selected in the dropdown when looking at tag deployment individually, but correct value ('5') is present in all downloaded data.
4. We should give the option of recording tag harness sizes. This is something that researchers would find very valuable and we are in the best position to collect that information.

**Comment by Hussell** [comment]
Bands are the standard aluminum bands put on by all bird observatories. Markers are the colour flags with a few large letters and numbers, often put on shorebirds (e.g. Red Knots) so that observers can read them through binoculars. That could definitely be clarified on the tag deployment page, and the markers de-emphasized (since relatively few projects use them now), but both should be kept.

**Comment by cjardine-bsc** [comment]
1/2. I've added band number to the bulk tag upload process. If you can test to ensure its all working well that would be good. 

3. Ah, this was a requested feature, as we didn't want to restrict what users could upload. But if it is causing issues on the data entry interface then maybe we need to tighten that up. I've done so for sex, but not yet for age. Our current allowable values are ad, im, juv, unk. We probably don't want to force users to use the columns if they have more detail (i.e. SY, ASY etc). So I've left this one alone.   

4. People can add custom columns to their tag deployment data. At this point I suggest users create their own custom field if they want to track harness size.
