### ISSUE TITLE
Project 113 (Wageningen) Missing Detections

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#404]
User has two tags that should have been detected on multiple receivers, but tags have zero detections in whole database. They had a mobile Lotek receiver that did detect these tags so they 'should' be showing up somewhere. Lotek receiver data has not been uploaded.

Tags (deployed Oct 3 and 9, 2018):
- 32272
- 32294

Should be detected on these receivers:
- 1151, deployment 4926
- 1010, deployment 4310

**Comment by jbrzusto** [comment]
Not to bud in, but this was easy to check and those two tags have deployment periods that do not match the true deployment dates.  If users don't set correct metadata on motus.org, the tag finder won't find their tags.  Search [this timeline](https://sgdata.motus.org/public/motus_tag_timeline.html)  for 32272 and 32294. It is updated daily and is the definitive picture of what the tag finder is looking for.
And until we implement a mechanism to deal with this autmatically, any receivers where the tags might be expected will have to be re-run once the metdata have been corrected.

**Comment by leberrigan** [comment]
Thanks John.

Just to clarify, the reason why these tags were missed was because the tags are set to a default deployment date of 2018-04-01 and that 2018-10-01 falls outside of the assumed 3-month tag lifespan?

I'll let the user know so they can change the metadata accordingly.

**Comment by jbrzusto** [comment]
That's right.
