### ISSUE TITLE
Unable to bulk upload tag metadata with deployment year set to 2019 - Project 68

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#407]
User is trying to update tag metadata, but MotusTagsTemplate-68.csv contains deployment dates set to 2019-07-01 and produces an error:

Row number | Tag ID | Field name | Error messages
-- | -- | -- | --
22 | 16908 | utcYearStart | The utcYearStart value is not a recognized date.
23 | 16909 | utcYearStart | The utcYearStart value is not a recognized date.
... | ... | ... | ...
133 | 29506 | utcYearStart | The utcYearStart value is not a recognized date.

It should be possible to set future deployment dates to prevent missed detections in such cases where receiver data is uploaded prior to tag metadata being updated.

**Comment by denislepage** [comment]
At the moment, the validation allows for future dates, but not past the current year.

We could change that to be no more than 1 year in the future (or what we think makes sense like 15 months). The script would be changed from

INSERT INTO api_errors (apiBatchID,rowNum,error_code,field_name)
SELECT @apiBatchID,rowNum,'api_value_dt',field_name
FROM #temp_utcYearStart a
WHERE utcYearStart NOT BETWEEN 2010 AND DATEPART(YEAR,GETDATE())

to something like

INSERT INTO api_errors (apiBatchID,rowNum,error_code,field_name)
SELECT @apiBatchID,rowNum,'api_value_dt',field_name
FROM #temp_utcYearStart a
WHERE utcYearStart < 2010 OR DATEDIFF(YEAR, utcYearStart, GETDATE()) < -365

And the same of utcYearEnd, though do we really want to allow deployment “end” dates in the future?

**Comment by cjardine-bsc** [comment]
I've made that change in sandbox and live.
