### ISSUE TITLE
receiver deployment record for site CHDE in project 14 is wrong

### ISSUE THREAD

**Issue by jbrzusto** [MotusDev/Motus-TO-DO#408]
```
meta "select * from recvDeps where name='CHDE'"
1976|Lotek-371|LOTEK|742|0|terminated|3706|CHDE|Tower|38.7703|-75.0852|0|1469577600.0|1510531200.0|14|
1976|Lotek-371|LOTEK|742|0|terminated|4505|CHDE|Tower|38.7703|-75.0852|0|1510531200.0|1540252800.0|14|
1459|Lotek-6517|LOTEK|507|0|active|5009|CHDE|Tower|38.7703|-75.0852|0|1540252800.0||14|
```
shows Lotek-6517 as the receiver actively deployed at 'CHDE', but we just received a file for
that site which has Lotek-371 as its embedded serial number, as for previous deployments
at the site, and the lat/lon in the file also match previous deployments.

**Comment by leberrigan** [comment]
User says they definitely swapped out Lotek-371 for Lotek-6517 due to a faulty power cord. How long do you see data coming from Lotek-371 beyond the supposed deployment end date?
