### ISSUE TITLE
Error caused by table filter on the manage tags page

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#409]
If you enter a date which doesn't parse correctly into one of the filters on the manage tag page (e.g. "2016 10 01" with spaces instead of hyphens), then the page crashes. More seriously, the value is stored in a session attribute, so if you reload or otherwise try to return to the page, the page will crash again, not giving you any opportunity to fix the mistake until your session expires.

**Comment by pmorrill** [comment]
got it. will take a look after lunch.

**Comment by Hussell** [comment]
Another input which triggers this error: "2018-24-10"

**Comment by denislepage** [comment]
ready for live, then?

**Comment by denislepage** [comment]
Pushing beta7 to live now.
