### ISSUE TITLE
PHP errors

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#411]
We've been occasionally getting PHP errors that bring down the main Motus WP site. 

Faulting application name: php-cgi.exe, version: 5.5.38.0, time stamp: 0x578fc02c
Faulting module name: php_wincache.dll, version: 1.3.7.11, time stamp: 0x576afcf8
Exception code: 0xc0000005
Fault offset: 0x000078d9
Faulting process id: 0x2c80
Faulting application start time: 0x01d4884abb2f5622
Faulting application path: **** \php-cgi.exe
Faulting module path:  **** \php_wincache.dll
Report Id: d24bfbd1-f443-11e8-80be-00155db12606
Faulting package full name: 
Faulting package-relative application ID: 

I found these, but I am still not sure of the root source of the problem:

https://www.experts-exchange.com/questions/29049180/Faulting-application-name-php-cgi-exe-Exception-code-0xc0000005.html

https://bugs.php.net/bug.php?id=64904

http://php.net/manual/en/wincache.configuration.php#ini.wincache.srwlocks

I tried to turn on this option in php.ini, but so far, I am not seeing any cached files being created in the temp folder. Not sure whether the caching is working or not.

wincache.fcenabled=1

**Comment by jbrzusto** [comment]
Do you know what the last HTTP request before the crash is?

**Comment by denislepage** [comment]
using wp caching seems to have resolved this issue.
