### ISSUE TITLE
Project 113 AND 217 Receiver Re-run

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#414]
Tags deployed in Project 113 had incorrect metadata resulting in missed detections. This has since been fixed, but receivers at which tags may be detected need to be re-run. This includes all receivers currently deployed in Project 113. See #404. 

Deployment   ID | Device ID | Receiver | Type | Deployment Range | Last Data Processed | Deployment Name
-- | -- | -- | -- | -- | -- | --
4307 | 1005 | SG-5016BBBK1B6A | SENSORGNOME | 2017-09-30 - ? | 2018-11-08 9:15 | Zwan.002-2017
4309 | 1004 | SG-5016BBBK1687 | SENSORGNOME | 2017-10-01 - ? | 2018-10-11 2:37 | Zwan-001.2017
4310 | 1010 | SG-5016BBBK0DC0 | SENSORGNOME | 2017-09-30 - ? | 2018-11-26 18:23 | ECN-003-2017
4315 | 1013 | SG-5016BBBK18D2 | SENSORGNOME | 2017-09-30 - ? | 2018-12-04 14:40 | Cast-005-2017
4312 | 1009 | SG-5016BBBK17E4 | SENSORGNOME | 2017-09-30 - ? | 2018-10-31 13:01 | Pett-006-2017
4313 | 1008 | SG-5016BBBK17D2 | SENSORGNOME | 2017-09-30 - ? | 2018-08-28 19:04 | Pett-007-2017
4316 | 1007 | SG-5016BBBK0F73 | SENSORGNOME | 2017-10-01 - ? | 2018-11-07 9:38 | Cam-008-2017
4317 | 1006 | SG-5016BBBK0F85 | SENSORGNOME | 2017-09-30 - ? | 2018-11-07 9:04 | Camp-009-2017
4454 | 1012 | SG-5016BBBK1123 | SENSORGNOME | 2017-10-12 - ? | 2018-12-04 13:03 | IJmuiden - WURSG011
4455 | 1011 | SG-5016BBBK23B1 | SENSORGNOME | 2017-10-11 - ? | 2018-11-02 10:36 | Schagerbrug - 004-2017
4625 | 1062 | SG-5016BBBK23B6 | SENSORGNOME | 2018-04-19 - ? | 2018-11-26 20:45 | SG-WUR12 Julianadorp vuurtoren
4669 | 1081 | SG-5016BBBK15A4 | SENSORGNOME | 2018-05-24 - ? | 2018-12-03 10:30 | WUR-SG016 Reddingsbrigade Maasvlakte
4715 | 1082 | SG-5016BBBK200B | SENSORGNOME | 2018-06-14 - ? | 2018-12-03 13:19 | WUR Zandmotor Argusmast
4892 | 1148 | SG-5016BBBK1B68 | SENSORGNOME | 2018-09-13 - ? | 2018-11-30 12:32 | Huiberts
4638 | 1063 | SG-5016BBBK18E8 | SENSORGNOME | 2018-05-02 - ? | 2018-11-26 11:34 | vuurtoren Den Helder
4657 | 1083 | SG-5016BBBK1B7C | SENSORGNOME | 2018-05-15 - ? | 2018-11-26 21:45 | Westkapelle
4658 | 1105 | SG-5016BBBK19D5 | SENSORGNOME | 2018-05-15 - ? | 2018-12-03 11:53 | Breskens
4805 | 1108 | SG-5016BBBK177E | SENSORGNOME | 2018-07-26 - ? | 2018-11-27 0:00 | Stellendam Haringvliet
4711 | 1080 | SG-5016BBBK1B75 | SENSORGNOME | 2018-06-07 - ? | 2018-11-26 21:48 | WUR Noorderhaven Julianadorp
4747 | 1107 | SG-5016BBBK17DA | SENSORGNOME | 2018-06-27 - ? | 2018-12-03 11:11 | SG-WUR017 Brandweer Maasvlakte
4746 | 1106 | SG-5016BBBK19C0 | SENSORGNOME | 2018-06-28 - ? | 2018-12-03 12:34 | Hoek van Holland Zeetoren
4838 | 1159 | SG-FC74RPI3EE3D | SENSORGNOME | 2018-10-02 - ? | 2018-11-26 22:33 | Heemtuin Hillegom
4926 | 1151 | SG-5016BBBK19BB | SENSORGNOME | 2018-09-24 - ? | 2018-11-30 13:04 | Kennemerwind
4987 | 1166 | SG-A655RPI363B3 | SENSORGNOME | 2018-10-24 - ? | 2018-10-26 4:44 | Barts mobile
5013 |   | SG-5016BBBK1995 | 2018-11-12 - ? | Bergen aan zee

**Comment by Hussell** [comment]
All receivers in project 113 have been rerun.

**Comment by leberrigan** [comment]
Thanks Jeremy. He has just asked for **Project 217** receivers to be rerun since he thinks his tags could be detected there as well:

Deployment ID | Device ID | Receiver 
-- | -- | -- 
4860 | 710 | SG-0816BBBK0909 
4861 | 677 | SG-4815BBBK20BC

**Comment by Hussell** [comment]
Ok, those two receivers have been rerun. (They reran quickly because they were only up for a few months together.)
