### ISSUE TITLE
Motus by the numbers summary page

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#416]
Here is a starting point for a 'Motus' by the numbers page. Feel free to add/delete or discuss any of the potential points. It would be nice for this to be a bit more 'glossy' than a list - i.e. BSC by the numbers found here: https://www.birdscanada.org/download/AnnualReportCurrent.pdf , but that may not be worth the effort.

Number of Motus stations:

Number of animals tagged and tracked:

Number of species tracked (link to list of species):

Number of Projects to date:

Number of Collaborators/Partners:

Number of Countries:

Number of Continents:

Estimated worldwide investment: $35 million (this number will be hard to automate, and we'll just have to update periodically.

**Comment by cjardine-bsc** [comment]
You can use the table adm_platform_stats for populating this. I've included all of Stu's requests there.

**Comment by cjardine-bsc** [comment]
Also altered prAdminTableStats to update these values, it now takes 3 minutes to execute. I've changed the frequency at which we run this proc from every 2 hours to every 4 hours.

**Comment by Hussell** [comment]
https://beta.motus.org/data/numbers
