### ISSUE TITLE
List of new features in the latest release

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#417]
New things in beta8, checkmark if they seem to be running correctly on live (no checkmark mostly means no testing yet):
- [x] Motus By the Numbers page (https://motus.org/data/numbers)
- [x] frequency and dongle type added/moved to antennas
  - [x] changes to receiver management page for same
  - [x] filters for frequency <s>and dongle type</s> added to receivers map
- [x] remove mobile deployments from receivers map
- [x] lifespan column removed from tag deployment tables and views
- [ ] fix to taghits_daily filtering (now generating summary tables pre-filtered)
- [x] display last known activity of receivers in a limited number of places
- [x] display tag code instead of tag deployment ID in some places
- [x] display lat/lng of tag deployment in some places
- [x] reorganized links on Manage Data page (moved some to other pages)
- [x] overhaul of timelines (not yet complete, but these changes are in)
  - [x] internal reorganization, making further changes possible
  - [x] show only one year at a time, so we don't have 30-page-long timelines
  - [x] highlight detections from the same tag/receiver under the cursor
  - [x] popup the relevant part of the legend when a detection is clicked
  - [x] some changes to navigation in an attempt to make it harder to get lost or confused
- [ ] changes to API for CTT
- [ ] changes to ReadSGFiles (commit says: sorting all files by date)
- [ ] changes to job locking (Commit says: "Adding a job locking feature on the proc queue to minimize conflicting procs and database locking. Jobs with the same lock_id should not run concurrently.")
- [x] changes to WordPress header and associated JavaScript to remove dependency on menu plugin
- miscellaneous minor bugfixes and refactoring in a half-dozen files

Things which are not in beta8:
- CTT registration page prototype
- support tickets prototype
- some debug code which shouldn't have been checked in to master (keep it in your development branch, please!)

**Comment by denislepage** [comment]
let's talk about the outstanding questions on the call tomorrow. Can't figure out what Job locking refers to. The other 2 points for me should be in beta8.

**Comment by Hussell** [comment]
Job locking: changes to the motus-base Job class, and to code which calls its constructor. Commit says:
"Adding a job locking feature on the proc queue to minimize conflicting procs and database locking. Jobs with the same lock_id should not run concurrently."

**Comment by pmorrill** [comment]
I don't think there is any need to push the CTT web work to next beta. It is in very preliminary state waiting for their participation. On the other hand, it should not impact the live data site.

The API changes can definitely be pushed to beta.

**Comment by denislepage** [comment]
Should be good on job locking, though I am not seeing any jobs that have used that feature. I can't entire remember if this was fully implemented, but apparently not. In any case, it's good to add to beta8.

**Comment by leberrigan** [comment]
This looks good. I especially like the new timelines. I just have a couple of comments:
1. Users need to 'discover' that the timeline has hidden information embedded in it on mouseover. Maybe add some writing to indicate this is possible to avoid any 'mystery meat'.
2. Timelines that are accessed through _Manage Data > Manage Receivers_ are not the same as the interactive ones. Is there any reason for this? If so, there should still be a link to the interactive version on this page just so users don't get confused.

**Comment by pmorrill** [comment]
I have done basic testing of the api on the beta server, and it seems to hold up fine. Someone should point the R-client at the beta and run a few checks there, before we can sign-off on the beta8 api completely.

**Comment by denislepage** [comment]
Same here. My testing of sandbox and beta both worked well just now, though I haven't confirmed the content of the retrieved data. Not sure there are any reasons to worry that they would have changed.

**Comment by pmorrill** [comment]
There is no reason for the content to have changed... unless an underlying view has been altered. Probably good-to-go.
