### ISSUE TITLE
Tag Deployment Bulk Upload Stripped of Deployment Start/End Dates (Project 8 and 110)

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#420]
When uploading tag deployments in bulk, tags are stripped of deployment dates. 

Files that were uploaded (CSV): [TagDeploymentsTemplate.zip](https://github.com/MotusDev/Motus-TO-DO/files/2691170/TagDeploymentsTemplate.zip)

This is a recent bug. Was not an issue ~2 wks ago.

Also, tags without deployments cannot be commented. This is probably because comments are associated with deployments only, but they can be useful for tags.

**Comment by cjardine-bsc** [comment]
I tried rerunning the proc that imports the data from the upload to the tag deployment tables and everything went smoothly and the dates are there. 

Did you get a message when you uploaded saying X number of new deployments were created and X number of deployments were updated?

I'm trying to get a sense of whether the whole upload failed or just the dates. Did you see other things change when you uploaded?

**Comment by leberrigan** [comment]
Just tried again and it's getting hung up on the sex column on only three rows for some reason even though all cells in that column are blank. I get the following errors:

Row number | Tag ID | Field name | Error messages
-- | -- | -- | --
10 | 10935 | sex | The sex value is not contained in the list of available values.
11 | 10936 | sex | The sex value is not contained in the list of available values.
39 | 16678 | sex | The sex value is not contained in the list of available values.

When uploading this file:
[MotusTagsTemplate-25-cleaned.zip](https://github.com/MotusDev/Motus-TO-DO/files/2742111/MotusTagsTemplate-25-cleaned.zip)


I my mind, the wrong input in this column should just be omitted with a warning message, but does not warrant stopping the entire process. Maybe this should be changed along with the other optional columns?

I also had to add a species to the test tag (bottom of template file) to get rid of an error.

**Comment by cjardine-bsc** [comment]
Sorry I missed this Lucas. I found the issue and put in a fix. I created the problem when I was addressing #403  (the check was looking at all uploads, not just the batch you were working on) 

You should be good to go.

**Comment by StuMackenzie** [comment]
test and close @leberrigan
