### ISSUE TITLE
Longer than expected lifespans

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#422]
Catherine - good point re tags still being detected at the end of their so-called active lifespan.
The first thing to check is whether the battery for the NTQB2-1 is really the same as the 
battery for NTQB-1, as that's how it's currently coded in the `modelBattery` map [here](https://github.com/jbrzusto/motusServer/blob/master/inst/doc/modelLotekTagLifeSpan.Rmd).  I believe the
battery mapping for the new tags came from Lotek, but it would be good to verify that.

If these are the same battery but the NTQB2 tags have longer life, then one approach to 
accomodating this is to treat "battery" in the more general sense of "power system", and
add new "battery types" (i.e. tag power consumption model + battery model) and assign
those to the NTQB2 line of tags.

It would be worth going through all tags systematically to see how close the last detection date
is to the estimated end-of-life, as we might also be falsely truncating the lifespan even of
some of the original tag models.

_Originally posted by @jbrzusto in https://github.com/MotusDev/Motus-TO-DO/issues/256#issuecomment-395386038_

**Comment by cjardine-bsc** [comment]
John, I've gone through as you suggested and calculated the difference between last detection date (with run length > 3) and the expected end date based on our lifespan calculations. There are about 1300 cases where these values are within 14 days of one anther, suggesting we are going to need to revisit our lifespan calcs. Stu is passing this information onto lotek and trying to get some more information for us to work from.  The models that seems to be the biggest culprits are NTQB2-2 and  NTQB-2. I'd like to suggest we increase the D value for these two tags while we wait to hear back from lotek. 

I bumped the D values for the new tag models back in June by 50% (see below). I'm just wondering if you followed suit in tagfinder or not? 

model | D | rt
NTQB2-1 | 109.158 | 12.25288
NTQB2-2 | 172.0884 | 12.24444
NTQB2-3-2 | 407.3315 | 11.93482
NTQB2-4-2S | 820.4426 | 11.79558
NTQB2-5-1 | 1163.292 | 11.71992
NTQB2-6-1 | 1163.292 | 11.71992
NTQB2-6-2 | 2203.553 | 11.66201

I think we should start to use a D of 172.0884 for NTQB-2 and NTQB2-2 immediately. Are you comfortable making that change?

**Comment by Hussell** [comment]
Closed in favor of #334 now that Lotek has sent us some real measurements.

**Comment by cjardine-bsc** [comment]
I'd like this to stay open until I assess how loteks new estimates compare to detections.

**Comment by cjardine-bsc** [comment]
I'd like this to stay open until I assess how loteks new estimates compare to detections.
