### ISSUE TITLE
incorrect tsbeign and tsEnd for batchs

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#424]
Moving this over from email from Lucas: 

Upon monitoring our projects tag detection list on the Motus.org website I noticed a large amount of 'days detected' and 'receivers detected by' gone. I noticed this on January 2, 2019 at 1 PM. I had been out for holidays and it was my first time checking in maybe a week. We have two receiver stations; one on site of the deployments (Patuxent River Park) and one 35 miles down range (Newtowne Neck State Park). The missing hits are from the one on site. The detections from the one downrange remain as well as detections from other projects receiver stations. Oddly, there are three tags from the project that still have the detection's from our on site receiver station. As we are attempting to complete our projects report this is very worrisome and I am unsure how this happened or if it can be fixed. 
One of our research assistants has begun working in R with our data, does this have any connection?
 
Please help me to understand why this has occurred. 
 
thank you,

**Comment by cjardine-bsc** [comment]
from Jeremy:

Project #172 (SORA), here's the latest detection chart from sgdata:
https://sgdata.motus.org/download/172/SG-5304RPI3AAED-2018_SORA_Patuxent%20River%20Park_hourly_tags.png

Not sure why these detections aren't showing up in the summary tables.

**Comment by leberrigan** [comment]
I'm assuming this has been resolved considering there hasn't been an update for 3 years....
