### ISSUE TITLE
test tag deployments with species_id

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#425]
I've noticed that we have a good number of test deployments in the database that include species_ids. 

The following species are currently assigned to test deployments: 

Bicknell's Thrush
Black Tern
Dunlin
Eurasian Hoopoe
European Robin
Gray Catbird
Human (Man)
Kirtland's Warbler
Northern Saw-whet Owl
Northern Wheatear
Rusty Blackbird
Savannah Sparrow
Savannah Sparrow (Ipswich)
Semipalmated Sandpiper
Swainson's Thrush
Temminck's Stint
Tennessee Warbler
Wood Thrush
Yellow-bellied Sapsucker
Yellow-billed Cuckoo

This doesn't seem right to me. If the tag is on a real bird then it shouldn't be flagged as a test. I would expect species_Id to be blank for all test deployments. I suspect users are just populating this field with their general study species since it's on the form.  I also think sometimes they might be using a nonsense bird (i.e. there are no real deployments on Eurasian Hoopoe) just because they feel they need to include a species_id.  This is impacting our overall count of species tracked. 

I'd like to add some error handling here: https://sandbox.motus.org/data/tag/deployment/edit?projectID=1&id=19797 That flags cases where a deployment is marked as test but includes a species ID. 

I'll also need to add the same error flag to the bulk deployment upload processing. 

The 59 deployments where this is currently a problem cover 18 projects. Maybe we can contact them directly to ask them to make sure their test deployments are really tests and if so remove the species ID from them?

Projects impacted:
35
46
49
57
64
67
76
90
100
113
123
145
153
156
161
168
175
193

**Comment by StuMackenzie** [comment]
I think these are all related to individuals assigning species during the tag registration process. I think we should remove this feature as it seems to only cause, or potentially cause, more problems than the minor inconvenience it fixes.

**Comment by leberrigan** [comment]
I agree with Stu. Currently, it is not possible to bulk upload tag metadata without adding a species to the test tag. This requirement should be removed.

**Comment by cjardine-bsc** [comment]
I think you (Lucas) and Stu are talking about different things. 

Stu is referring to assigning a species when registering tags. That, to me, is less critical as only occasionally are tags set to test and its fairly easy to remove the species from those deployments as long as we flag to the user that they need to do so. But if there are others reasons for removing this feature it shouldn't be hard to drop it. Maybe we can discuss later today?

Lucas is referring to the data checks done on the bulk tag deployment metadata upload. Which is probably where these errors are originating. I've altered the proc in Sandbox so that species_ids are not required for test deployments. Lucas would you like to test it and I can deploy to live if you're happy?

Regardless, I'd still like a flag included on the data entry page that prevents users from doing this. Hopefully Paul can add that easily.

**Comment by leberrigan** [comment]
Oh, my mistake! 

I just tried uploading to Sandbox and it gives me the same error as before:


Row number | Tag ID | Field name | Error messages
-- | -- | -- | --
10 | 21752 | sex | The sex value is not contained in the list of available values.
11 | 21753 | sex | The sex value is not contained in the list of available values.
39 | 21959 | sex | The sex value is not contained in the list of available values.
71 | 25761 | speciesID | You have entered a start date in the past without  providing a species. You may either enter a future start date or  populate the species column. If you're not yet ready to provide this  data you may omit this deployment from your upload template.

**Comment by pmorrill** [comment]
Looking at the tag deployment config tools in web interface: how severe do you want to be? If someone sets a deployment as 'test' we can:

a) disable the species select-name and other morphology boxes

b) If they have already set a species, WARN them, but leave the species intact in database

c) Or, Null out the species id and other morphology if they save the deployment to the database

**Comment by leberrigan** [comment]
I think it is a good idea to warn users once they have created a test deployment to tell them what that means in case some people do it by accident (i.e., data won't be show up in detection summaries, metadata will be ignored).

**Comment by cjardine-bsc** [comment]
If we use option a) what will happen if the species is already populated? 

I'd like to make sure whatever we do the species_id is not saved to the database when test = TRUE

**Comment by Hussell** [comment]
There are also a few species which are obviously placeholders, but are not marked as test deployments, such as Commons' Panicgrass (Dichanthelium commonsianum) and Pale-bellied Frost Lichen (Physconia subpallida). Test deployments are filtered out of the species tagged number on the Motus By the Numbers page, but these aren't.

**Comment by leberrigan** [comment]
Good point, Jeremy. I think in some cases like what you've mentioned it's easy for us to determine what is a test deployment, but there are bound to be some ambiguous unmarked test deployments that only the researcher would know about. 

Perhaps we should send out a message to all Motus users asking them to indicate which of their tags are test deployments? I suppose that depends on how important this really is.

**Comment by Hussell** [comment]
I don't think it's important enough to bother the ~500 researchers who don't have test deployments or have marked their test deployments as test deployments.

**Comment by denislepage** [comment]
We should exclude plants at the very least within the list of validly supported species_id's....! Whether they are entered through the web or the import tool.

That won't solve everything, but it will avoid the obvious error with that group. I think the list of supported species should come from a view where we can set the rules, if not already so, so the code should only ever refer to lk_species table for data outputs, not inputs.

**Comment by cjardine-bsc** [comment]
I've changed the prSearchSpecies and prAPIValidateTagDeploy procs to only accept species in the following groups. 

'BATS', 'BEETLES','BIRDS', 'BUTTERFL', 'HYMENOPTERA', 'MAMMALS', 'MOTHS', 'ODONATA','ORTHOPTERA','REPTILES' 

I've set those plants to test deployments and removed the species_id.
