### ISSUE TITLE
Some overlapping deployments not showing up in Data Issues

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#426]
I happened to notice there are 3 receivers with more than one active deployment, meaning the deployments must overlap. However, only 1 of them shows up on the corresponding Data Issues page. The 2 that don't show have the same start date/time for both deployments, so I suspect this is a bug in the procedure looking for overlapping deployments, which may affect terminated deployments as well.

Receiver IDs: 2050, 2088, 2737.
https://motus.org/data/issues?id=65#v_sensor_overlap_deploy (ID 2050, critical error, as expected)
https://motus.org/data/issues?id=143 (2088, no error)
https://motus.org/data/issues?id=31 (2737, no error)

**Comment by cjardine-bsc** [comment]
yup. Its because those two sensors don't have records in the sensors_hash_keys table yet. Which the check relied on. 

I tweaked the check to no longer rely on the sensors_hash_keys table and they show up now. 

Thanks for the heads up!
