### ISSUE TITLE
Project 145 Error when downloading data with R - "NOT NULL constraint failed: tagAmbig.motusTagID2"

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#429]
When downloading data from project 145 using the 'motus' R package I get the following error:
```
Error in result_create(conn@ptr, statement) : 
  NOT NULL constraint failed: tagAmbig.motusTagID2
```

Updating the database or downloading a new database makes no difference; it always gets hung up on this step.

~~If this is not  a quick fix, can somebody provide me with a workaround?~~

**Comment by leberrigan** [comment]
Error only occurs once all data has been downloaded. 

I get access to data with the following code:
```
sqldata <- tagme(projRecv = 145, new = F, update = F, forceMeta = F)
flatData <- sqldata %>% tbl('alltags') %>% collect() %>% as_tibble()
```

**Comment by cjardine-bsc** [comment]
The error happens when you open the alltags view?

Can I assume you downloaded the data from live (or beta) not sandbox?

**Comment by leberrigan** [comment]
This error occurs at the end of downloading, after executing the 'tagme' function. 

Yes, downloads have been attempted through both live and beta.

**Comment by denislepage** [comment]
An ambiguity is not expected to have a single tag, so there is a requirement in the database for tag1 and tag2 to be provided.

If I query our database, there are a number of ambiguities containing only a single tag. We'll need to resolve those cases, and ensure that we are avoiding them in the future.

SELECT * FROM [vwR_Tags_for_ambiguities]  where motusTagID2 IS NULL

**Comment by plorch** [comment]
This still seems to be an issue.  I just got this error when running
`rec.sql.motus <- tagme(projRecv = Honeyhut, forceMeta = TRUE)`
where `Honeyhut="SG-1215BBBK1794"`
just after updating the database with 
`rec.sql.motus <- tagme(projRecv = Honeyhut, new = FALSE,update = TRUE)`

**Comment by adamdsmith** [comment]
Likewise this just started happening to one of my receivers as well:

``` r
library(motus)
rcv <- "SG-3115BBBK1383"
fail <- tagme(projRecv = rcv, update = TRUE, forceMeta = TRUE)
```
The error disappears with `forceMeta = FALSE`

**Comment by cjardine-bsc** [comment]
@steffilazerte I believe we wanted to remove the IS NOT NULL restriction on the motusTagID2 column. Is that still in place?

**Comment by steffilazerte** [comment]
When `motus` creates/ensures the SQLite database, it creates/checks for a `tagAmbig` table which has both `motusTagID1 INT NOT NULL` and `motusTagID2 INT NOT NULL`.

There is also a note: "not null because there have to be at least 2"

So, yes, the restriction is in place for both tags.

**Comment by cjardine-bsc** [comment]
can we remove that constraint please?

**Comment by steffilazerte** [comment]
In theory yes, but I think this will involve updating existing databases. I'll look into it.

**Comment by steffilazerte** [comment]
Sorry for the delay in this.

Just to confirm, the constraint should be removed from JUST `motusTagID2` or from BOTH `motusTagID1` and `motusTagID2`?

**Comment by steffilazerte** [comment]
Okay! I have a working fix, but as this has to update currently existing databases it's a bit tricky. 

Could someone with a SQLite background comment on this workflow and let me know if it's problematic?

To remove the `NOT NULL` constraint from `motusTagID2` (and/or `motusTagID1`) in an existing database:
1. `DROP VIEW IF EXISTS allambigs`  (depends on `alltags` view)
2. `DROP VIEW IF EXISTS alltags` (depends on `tagAmbig` table)
3. Make new `tagAmbig2` table exactly like `tagAmbig` but without the `NOT NULL` constraint
4. `INSERT INTO tagAmbig2 SELECT * FROM tagAmbig`
5. `DROP TABLE tagAmbig`

Does that make sense? My tests work, but I want to make sure this isn't too computationally expensive, etc.
6. `ALTER TABLE tagAmbig2 RENAME TO tagAmbig`
7. Recreate all the views

**Comment by steffilazerte** [comment]
@denislepage do you have any feedback regarding this approach?

**Comment by denislepage** [comment]
Hi, the question I haven't seen resolved is what is the value of an ambig that only has 1 tag. I think I need to talk to Catherine before we commit to this approach. But if you need to remove the constraint, your suggestion is pretty much the only way to do it.

**Comment by steffilazerte** [comment]
This is currently implemented in the beta3 branch of the R project, but is easy enough to remove. We'll just have to make a decision before we merge beta3 into master.

**Comment by cjardine-bsc** [comment]
There is no value other than the fact that we need to keep the ambigID and resolved tagID in the database to correct new data as it come in. 

Plus, I think it's needed in R if they have hits already downloaded that associated with that ambigID, even though it's been resolved.

**Comment by denislepage** [comment]
I’ve never been totally comfortable with the idea of modifying the ambig list of tags. Should we rather provide the R package with the original list, rather than the modified one?

**Comment by cjardine-bsc** [comment]
I'm not sure we have a way around it. This happens when someone registers a tag twice by mistake. So I think we do need to delete one tag. 

If we continue to pass them both ambigIDs their hit will be associated with a tagID that doesn't exist and has no metadata. Not the best.

**Comment by denislepage** [comment]
Grmblblb. ☺

Sure, let’s allow it then. The SQL outlined by Steffi seems to work fine.

**Comment by steffilazerte** [comment]
:smile: @cjardine-bsc this has been implemented on the beta3 branch. Is there anyone who had problems who can test this to see if it fixed their issue?

**Comment by cjardine-bsc** [comment]
@jsayers-bsc Can you test?

**Comment by jsayers-bsc** [comment]
Hmm... here's a question: how to test the beta R package?

**Comment by steffilazerte** [comment]
1. Carefully :wink: If you want to try with one of your active projects, make sure to backup your .motus file somewhere, just in case
2. `remotes::install_github("MotusWTS/motus", ref = "beta3")` This will install `motus v.3.0.1` 
3. Try downloading project 145 (at least that was the project that sparked the problem): 

```
library(motus)
packageVersion("motus") # make sure using new version
tagme(projRecv = 145, new = TRUE, update = TRUE)
```

Thanks!

**Comment by jsayers-bsc** [comment]
Ran into this issue with project 225 which recently had one of its test tags merged into Project 322 TestTags. 

Using the beta version, everything seems fine. Tested with project 145 as well and this error did not appear.

**Comment by steffilazerte** [comment]
Great! Thanks for testing. I'll try to get the beta branch merged with master soon. There are a couple of other issues that need to be tested first, but hopefully I'll get this figured out soon
