### ISSUE TITLE
Add field description template to tag deployment bulk upload page

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#43]
Need field descriptions  FROM [motus].[dbo].[vwBase_API_field_descriptions]
where table_name = 'vwBase_API_tag_deployments_template_short' 

Should be able to use: https://beta.motus.org/data/downloads/api-proxy/fields for this.

**Comment by pmorrill** [comment]
I have added a button to download the descriptions (master branch only first). It is the same file as you get on the download data page. Do you want me to add some filtering so that it only shows the TagTemplate fields? That would be an adjust to the api is all.

**Comment by cjardine-bsc** [comment]
Yes, please filter for when table_name = 'vwBase_API_tag_deployments_template_short'

Thanks!

**Comment by pmorrill** [comment]
OK. Close: had to use table_name = 'MotusTagsTemplate'. But it will in place tomorrow (master branch)
