### ISSUE TITLE
Device ID vs Receiver ID vs Deployment ID (vs Sensor ID vs Serial Number)

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#431]
This is a re-occurring source of confusion, and I'm not sure I fully understand the situation myself, so I'll write up what I think I know here. I'll incorporate corrections as they arrive. (Prompted by [a comment by Lucas](https://github.com/MotusDev/Motus-TO-DO/issues/396#issuecomment-455184909) in a thread where this reply would be getting off-topic.)

In the beginning, we had deployment ID and sensor ID. (This was before we made an effort to consistently call receivers "receivers". Before, a page might have referred to "sensors", "receivers", and "antenna stations" in the same paragraph.) Deployment ID continues to make sense, since there's no other unique identifier for a deployment. (People kept reusing the same name for deployments at or near the same location, which is one of the reasons "sites" were later added to the database: it's how people typically think about deployments. What we call a "deployment" is different from what users think of when they hear the word.)

Receivers, on the other hand, each have a (supposedly) unique serial number (SG-XXXXXXXXXXXX, Lotek-XXX, etc.), which is (confusingly) called "receiver ID" in the database. This is the sensible way for users to identify receivers. Internally though, an integer is much more efficient as an identifier than a 16-character string, and a couple of receiver serial numbers turned out not to be unique after all. The internal integer ID is in the "id" column of the table (still) called "sensors", so it's the sensor ID, but in many database views it's also called "motusReceiverID", to distinguish it from "receiverID", which is the serial number. Got it?

Unfortunately, our initial database model assumed that each receiver would be used by one, and only one, project. The first time a receiver got passed from one project to another, rather than fix the data model we created a duplicate data record with the same serial number (aka receiver ID), a different project ID, and a new internal ID (sensor ID). Tags used by multiple projects were handled the same way. So sensor IDs (sometimes known as receiver IDs) now actually identify a receiver+project combination, instead of just a receiver.

Our initial ideas also had everyone "registering" their receivers in our database before uploading data. When we started receiving uploaded data from receivers which we had no record of, we had to create a new table: sensors_hash_keys, where we store all the receiver serial numbers from which we have received data, along with the (truly) unique hash keys generated during data transfer, hence the name. This table has its own integer "id" column, which is used to link batches of data to receivers. To distinguish this from the other IDs, it is called the "device ID". So device IDs identify receivers from which we have received data. #84

**Comment by Hussell** [comment]
My thoughts:
* Users should not have to care about our internal ID numbers. In almost every case, receivers should be referred to using serial numbers. #34 #106 #211 One possible exception is in URLs, but if the data model never gets fixed, then even there we might be better off using serial number and project ID, since URLs are visible to users.
* Situations like this are common enough that it is said one of the two hardest problems in computer science is naming things, by which they mean it's hard to name things before you know what all the things to name are, it's hard to keep names consistent and sensible as a system evolves, and it's even harder to re-name things once they've been given a "temporary" name.
* This is a good example of what people mean when they say "technical debt". To fix the data model, we would have to make simultaneous changes to the database and a couple of hundred SQL queries in the code. This would make things a lot simpler for us in the future, but because it would require a big coordinated effort, and almost no user-visible changes for a lot of coordinated effort, it keeps getting pushed down the list.
* It is sometimes said that, in software development, one should plan to build a prototype then throw it away and start over with a new design using the lessons learned. I think we actually did this, back before we had many users. We have since learned many new lessons, but now we have users and data which make starting over more complicated because we would have to transfer all the old data into a new system. Our best option may be to pick one lesson learned, then refactor the existing code to incorporate that lesson. This would require, at the least, that we carefully review of a lot of existing code to make certain we don't create new bugs when we change one of the basic assumptions in the design.

**Comment by denislepage** [comment]
You are correct in your understanding

deviceID: unique for each serial number
receiverID: the alphanumeric serial number (e.g. SG-xxx)
sensorID: unique for each serial number AND project

As Jeremy says, the costs of changing any of the names is pretty high. There are many things we would likely do differently if we were given a chance for a do-over. The name “sensor” should actually match the antenna level, for instance. But reusing the word sensor in a new context would be highly confusing. So, we’re likely stuck with these for a long time.

The field names are partly explained here, but they could potentially be expanded to include fields from all tables:
https://motus.org/MotusRBook/appendixA.html

The internal ID’s of receivers and sensors are actually not included in the view.  Only the serial number and the projectID, which should be more meaningful to users.

**Comment by Hussell** [comment]
On the Manage Receivers pages (list of receiver deployments, edit receiver deployment, edit receiver) the deployment ID is shown. If it isn't shown or used anywhere else on the website, should it be removed from these pages to reduce confusion among users? **Is** it shown or used anywhere else?

**Comment by leberrigan** [comment]
Thanks for putting this git together, Jeremy.

Here's what I think we should do with those variables:


Variable | Description | Keep/Hide? | Reasoning
-- | -- | -- | --
Device ID | unique to each serial number | Hide | Not all receivers have one (if no data uploaded yet) and provides same   amount of info as serial no
Receiver ID | alphanumeric serial number | Keep | Helps us match registered receivers to physical units
Sensor ID | unique to serial number and project | Keep | Helps us identify duplicate receiver registrations and it's a faster way   to reference a receiver, but maybe not as important to show?
Receiver Deployment ID | unique to each deployment | Keep | Very useful when analyzing data and troubleshooting. For instance, when looking for active deployments during a given time frame.

**Comment by denislepage** [comment]
I would agree with that.

**Comment by StuMackenzie** [comment]
What's the resolution here or changes that need to be implemented? Or can we close?

**Comment by Hussell** [comment]
I think this one is useful as documentation, so it should be left open.

There are occasional places where sensor ID and device ID are visible on the website, and it's still a source of confusion. I've been replacing some of them with receiver serial number, when I happen across them and it's easy to do. It will be good to keep this in mind as we do the dashboards.

**Comment by StuMackenzie** [comment]
Is it worth considering finding, or making a better place for this kind of documentation? Perhaps on the website, if it's the type of documentation that would be useful to more people beyond just us. That way we can keep this space clear for active issues and development.

**Comment by denislepage** [comment]
This is as close as we have to documentation on the individual fields, I think.

https://motus.org/MotusRBook/appendixA.html

We probably should try to provide documentation on tables and fields at some point, especially if we are going to suggest that people build their own custom table joins to speed up things.
