### ISSUE TITLE
Tag Registrations Failed due to botched attempt to remove lifespan from tag deployments

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#433]
**This now appears to be a widespread issue**

Multiple users tried uploading tag recordings twice but each times failed (example Job ID: [266872](https://sgdata.motus.org/status?jobID=266872)) with the following error:
> Error: Error in createRecvTagDB(projectID, dateBin, isTesting): No tags found for project 232 with dateBin in 2019-1

It get stuck at this job [266880](https://sgdata.motus.org/status?jobID=266880) where it repeates this error:

> Query to motus server to register tag 10:17.3 failed with this error: database-error: A database error occurred - org.bsc.exceptions.DBException com.microsoft.sqlserver.jdbc.SQLServerException: The index 26 is out of range. SQL: "dbo.[prAPIImportTags](?, ?, ?, ?, ?, ?, ?, ?, DEFAULT, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"

I can't try uploading this file again because it says a copy already exists on the server.

**Other projects:**

 Project 19: job ID   [266890](https://sgdata.motus.org/status?jobID=266890)

 Project 239: job ID [271822](https://sgdata.motus.org/status?jobID=271822)

**Comment by Hussell** [comment]
It looks like this one was my fault: I botched the removal of the lifespan parameter, back in October. I've committed a fix to beta8. Once it's deployed to live I'll start rerunning the affected jobs.

**Comment by Hussell** [comment]
The bug fix has been deployed, and I've rerun all affected jobs.

**Comment by denislepage** [comment]
A few questions.

Will the users be notified automatically, or would it be worth sending them a quick note? Can you provide a list of affected projects to Lucas, maybe?

Has the correct data been inserted in Motus database?

**Comment by Hussell** [comment]
Only 3 users were affected. They re-uploaded their files a couple of times each.
[Bryant Dossman](https://motus.org/data/user?id=205)
[Ana Gonzalez](https://motus.org/data/user?id=584)
[Rebeca Linhart](https://motus.org/data/user?id=7873)

I don't think they get notified automatically, but I'm not 100% certain.

The correct data has been inserted in the Motus database.

**Comment by StuMackenzie** [comment]
As far as I know we haven't setup any kind of automatic user notifications. @leberrigan , you OK to send them a little note?

**Comment by leberrigan** [comment]
Thanks for putting the fix in. I'll let those users know.
