### ISSUE TITLE
Project 10 Missing Spring 2013 Detections from Three Receivers

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#434]
Project 'Taylor - Receivers' is missing data on some older deployments that used to exist before it was migrated to the new website. User only knows of missing detections of Ipswich Sparrows from project 22 during Spring 2013 (April/May), but there are likely others. They are asking us to have these receivers rerun:
 
- Clam Harbour (CLHRB; ID = [2837](https://motus.org/data/receiver/deployment/edit?projectID=10&id=2837))
    - At least 6 sparrows should be on this receiver
- Ryan Leet (LEET; ID = [3554](https://motus.org/data/receiver/deployment/detections/timeline?id=3554&year=2013))
   - 2 sparrows should be on this receiver. Additionally, the website deployment date is 1 May 2013 but should be 19 Apr 2013 (has been changed)
 - Taylor Head (TAYL; ID = [2839](https://motus.org/data/receiver/deployment/detections/timeline?id=2839&year=2013))
   - At least 2 sparrows should be on this receiver

**Comment by leberrigan** [comment]
Thanks Jeremy. 

The user was looking for detections in **Spring 2013** of which there isn't anything new. In addition, there is no antenna and GPS activity during this period for all three receivers. Is it possible that these data somehow never made it over to the new server?

**Comment by jbrzusto** [comment]
Probably can be closed in deference to jbrzusto/motusServer#435

**Comment by leberrigan** [comment]
John has made some progress on this, but I think we will need to be a coordinated effort to get this fixed. From the sounds of it, this is a widespread issue that needs to be addressed. See jbrzusto/motusServer#435

Phil's students could really use these data before the fall, especially regarding Ipswich Sparrow data which is already lacking (oddly). I know there isn't a quick fix  -- if we can figure out a workaround for those receivers in the time being that would be helpful.

**Comment by Hussell** [comment]
Progress!

[Clam Harbour (CLHRB; ID = 2837)](https://motus.org/data/receiver/deployment/detections/timeline?year=2013&id=2837) - 9 Ipswich Sparrows detected

[Ryan Leet (LEET; ID = 3554)](https://motus.org/data/receiver/deployment/detections/timeline?id=3554&year=2013) - 2 Ipswich Sparrows detected

[Taylor Head (TAYL; ID = 2839)](https://motus.org/data/receiver/deployment/detections/timeline?id=2839&year=2013) - 5 Ipswich Sparrows detected in April-May 2013

I'm currently doing a systematic search to find and repair all other receivers which lost data in the same way.
