### ISSUE TITLE
Project 62 Missing Detections from Tags with Altered Nominal Frequency

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#435]
Message intercepted from Google Groups: 

> I was wondering if anyone had any experience with getting detections of tags on frequencies besides the usual 166.380? In lieu of the nano tag shortage last year, I tagged a small sample of chickadees on **166.360** (and tuned a nearby tower to pick them up) but can't see the detections at all. I've checked that the tags are correctly registered online.
> Any help would be appreciated as currently I have 0 data on these birds.
> 

We have seen issues with the project come up before in #316 and #412, but most other issues have been resolved.

Tags that were registered: 

Tag ID | Nom.Freq. | Deployment Date
-- | -- | --
[30031](https://motus.org/data/tags/edit?projectID=62&id=30031) | 166.36 | 2017-10-06 - ?
[30032](https://motus.org/data/tags/edit?projectID=62&id=30032) | 166.36 | 2017-10-06 - ?
[30033](https://motus.org/data/tags/edit?projectID=62&id=30033) | 166.36 | 2017-10-05 - ?
[30034](https://motus.org/data/tags/edit?projectID=62&id=30034) | 166.36 | 2017-10-06 - ?
[30035](https://motus.org/data/tags/edit?projectID=62&id=30035) | 166.36 | 2017-10-06 - ?
[30036](https://motus.org/data/tags/edit?projectID=62&id=30036) | 166.36 | 2017-10-19 - ?
[30037](https://motus.org/data/tags/edit?projectID=62&id=30037) | 166.36 | 2017-10-07 - ?
[30038](https://motus.org/data/tags/edit?projectID=62&id=30038) | 166.36 | 2017-10-07 - ?
[30039](https://motus.org/data/tags/edit?projectID=62&id=30039) | 166.36 | 2017-10-07 - ?
[30040](https://motus.org/data/tags/edit?projectID=62&id=30040) | 166.36 |  NA
[30041](https://motus.org/data/tags/edit?projectID=62&id=30041) | 166.36 | 2017-10-07 - ?

According to previous emails, his receiver ([SG-4001BBBK1770](https://motus.org/data/receiver/deployment/edit?projectID=62&id=2782)) was tuned to 166.356, but the metadata for this receiver deployment has a frequency set to 166.380 MHz. Could this be the issue? I will get in touch with the user to confirm that this is a mistake.

**Comment by cjardine-bsc** [comment]
Ya, I think you need to manually override the receiver frequency in Tagfinder. There's a table that Jeremy should be able to alter.

**Comment by Hussell** [comment]
I need to know when the frequency of the receiver was changed, and for how long. Right now this receiver has one long deployment from 2015-01-27 to 2018-07-19. When the frequency was changed, a new deployment should have been created.

(P.S.: This is why the frequency in the antenna table should not be a foreign key: we don't have a predefined, unchanging list of frequencies which will be used. Similarly on the user interface: we should not force users to enter an incorrect frequency. A drop-down list prevents typos, but in this case a text-box with auto-complete would be better.)

(P.P.S.: Why "the user"? It would be good to know the name of the person we're helping.)

**Comment by jbrzusto** [comment]
I made a copy of the meta database where the nominal frequency of those tags was set to 166.38 MHz then ran raw files for SG-4001BBBK1770 from Nov-Dec. 2017 through the tagfinder, but none of those tags where detected (it also looked for others from the same project not listed above but which were at 166.320 MHz, with again no detections).  So I think it's very unlikely they were detected anywhere.

**Comment by Hussell** [comment]
Nov-Dec. 2017? Not Oct-Dec.?

**Comment by jbrzusto** [comment]
Sorry, from Oct. 20 (boot session 538).  We have no data from that receiver between June 1 and Oct 19, 2017.

**Comment by leberrigan** [comment]
The user did not follow the correct instructions to alter the FCD listening frequency for this receiver. They did not change the deployment.txt file, nor did they set the frequency on the web interface (not a good method, I know). They assumed that by changing the frequency of the FCDs using QTHID while it was plugged into their laptop would do the trick which of course it did not. In the end, this receiver was tuned to 166.376 MHz the whole time, as indicated by John. I don't believe there is anything else we can do at this point. Case CLOSED!
