### ISSUE TITLE
Upload Does Not Produce Output Files - Project 57 (232)

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#438]
Data for receiver SG-0816BBBK0206 were uploaded recently and job was 'successful' but did not produce output files. I don't have sufficient internet to check whether these data are present in downloads thru tagme, but I have asked the user for this project to do so. 
https://sgdata.motus.org/status?jobID=275984

Data were uploaded to project 232 when this receiver is only registered to project 57. I'm not convinced this is the only problem since I haven't encountered this issue before and I can't imagine others haven't done this as well (I even think I have at some point).

SG jobs shows all the files that were uploaded and an output plot that ends in April 2018.
https://sgdata.motus.org/status?serno=SG-0816BBBK0206

**Comment by denislepage** [comment]
There is a recent batch (Feb 3) with 69,000 hits.

The metadata points that receiver to project 57, and would normally be available under that, but not 232.

The project ID under which the file is uploaded should not impact that.

**Comment by Hussell** [comment]
Rerunning this receiver for project 57 caused the plots to be generated.

In my experience, if an incorrect project ID is given then all data is processed correctly but plots are only generated for the given project, and even then only if some of the data uploaded was for the given project.
