### ISSUE TITLE
List of landowners needs to be cleaned up

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#440]
On the <a href='https://motus.org/data/partners'>partners page</a>, there's a list of landowners. There's some embarrassing stuff in there: half a dozen "test test"-type lines, a couple where the wrong stuff was entered (an email address, notes about how to access the site), one that's just "Dr.", another in ALL CAPS, etc.

Someone should go through the list carefully, fix the ones which can be fixed, set projects_landowners.acknowledge = 0 on the ones which can't, and delete the obvious tests. (I might be able to do this by using admin privileges to edit landowners on the website, but it would probably be a lot faster for someone with direct access to the database.)

**Comment by denislepage** [comment]
I am not sure this is a battle we can ever win. If we are relying on people to provide the data that we use for this page, we perhaps should have a checkbox that explicitly makes the name visible on the partners page, so they realize that this will be publicly listed. We’d have to be explicit also that only the name would be visible, not any other details.
