### ISSUE TITLE
Deprecated and placeholder species

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#443]
There are some species in the database marked with status = 0, which seems to be "deprecated", as in the species isn't acknowledged anymore or there's some other option with status = 1. You can see these on the species table in beta: https://beta.motus.org/data/species?n=1000&q=&f=1&o=6a0a1a2a3a4a5a

Sorting taxonomically, it looks like the following replacements could/should be made:

Deprecated Species ID | Deprecated Common name | Replacement Species ID | Replacement Common Name
-------------|-------------------|--------------|-------------------
36276 | Eurasian Reed-Warbler | 46507 | Eurasian Reed Warbler
36640 | European Robin | 45843 | European Robin
40717 | Northern Wheatear (nominate) | 42068 | Northern Wheatear (Eurasian)
40802 | Summer Tanager (Eastern) | 17670 | Summer Tanager

**Comment by Hussell** [comment]
There are a couple of projects using odd placeholder species, like Commons' Panicgrass (Dichanthelium commonsianum), Pale-bellied Frost Lichen (Physconia subpallida), or Human (Homo sapiens). Does anything need to be done about that?

**Comment by cjardine-bsc** [comment]
See 443, there is probably some mop up to do after the fix is in place.

**Comment by denislepage** [comment]
We should indeed avoid offering species with status = 0, and fix any that are currently there. There are a few subspecies groups (status = 3) that may be worth tracking, but generally, we want status = 1.

The taxonomy is updated annually around August. I would then normally update any species ID’s based on the latest taxonomy. I have mostly been focusing on Canadian and North American species in previous updates, so I’ll have to keep an eye on other regions with Motus.

We should thus exclude the ability of users to pick the following levels:

0              No longer recognized
2              Now split
4              Hybrid
5              Exotic
6              Extinct
9              Unidentified

This leaves only status 1, and perhaps 3. However, I would be inclined to severely restrict status 3 if we offer it at all.

Maybe the easiest option is not to offer it by default, and only show taxa that are species or for which there are already a deployment, whatever their status.

select * from lk_species a where species_status = 1 or exists (select id from tags_deployments where a.species_id = b.species_id)

That means that users would have to make a request to have an explicit value for a subspecies, and once it’s been used once, it remains available for other users. I fixed everything that was status 0. There are a few cases of status 2. I’d be a bit surprised if they can’t be resolved by the users, but I don’t know if it’s worth following up.

select species_id, species_status, english_name from lk_species a where (species_status = 1 or exists (select id from tags_deployments b where a.species_id = b.species_id))
and species_status not in (1,3)

species_id           species_status  english_name
2160       2              Leach's/Townsend's/Ainley's Storm-Petrel
12150    2              Alder/Willow Flycatcher (Traill's Flycatcher)
18961    2              Nelson's/Saltmarsh Sparrow (Sharp-tailed Sparrow)
40362    2              Semipalmated/Western Sandpiper

**Comment by Hussell** [comment]
Only species with status 1 can be entered through the web interface, and it has been that way for a while, so now that the old status 0 species have been fixed, I think nothing else urgently needs to be done besides #425.
