### ISSUE TITLE
Project 3 Manual Tag Registration

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#444]
I have just been provided with a long list of tags that were deployed in Project 3 that had failed to register. It sounds like users are not reading the full upload confirmation email and instead interpreting any message as a successful registration.

The following 4 tags were registered, but with an incorrect burst rate:

tagID | mfgID | correct period | file upload
-- | -- | -- | --
30490 | 96 | 5.9 | 233_2018-07-09T20-36-08.240_REKN_Mingan1.7z (registered July 9, 2018)
30477 | 214 | 12.7 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z (registered July 9, 2018)
30484 | 229 | 12.7 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z (registered July 9, 2018)
30487 | 236 | 12.7 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z (registered July 9, 2018)

These following tags were uploaded, but were never successfully registered:

mfgID | approx period | reason tag registration missing | upload date | file uploaded
-- | -- | -- | -- | --
272 | 12.7 | unknown - purchased 2017 | NA | NA
273 | 12.7 | unknown - purchased 2017 | NA | NA
274 | 12.7 | unknown - purchased 2017 | NA | NA
275 | 12.7 | unknown - purchased 2017 | NA | NA
276 | 12.7 | unknown - purchased 2017 | NA | NA
277 | 12.7 | unknown - purchased 2017 | NA | NA
278 | 12.7 | unknown - purchased 2017 | NA | NA
279 | 12.7 | unknown - purchased 2017 | NA | NA
280 | 12.7 | unknown - purchased 2017 | NA | NA
281 | 12.7 | unknown - purchased 2017 | NA | NA
282 | 12.7 | unknown - purchased 2017 | NA | NA
283 | 12.7 | unknown - purchased 2017 | NA | NA
284 | 12.7 | unknown - purchased 2017 | NA | NA
285 | 12.7 | unknown - purchased 2017 | NA | NA
286 | 12.7 | unknown - purchased 2017 | NA | NA
287 | 12.7 | unknown - purchased 2017 | NA | NA
288 | 12.7 | unknown - purchased 2017 | NA | NA
289 | 12.7 | unknown - purchased 2017 | NA | NA
290 | 12.7 | unknown - purchased 2017 | NA | NA
292 | 12.7 | unknown - purchased 2017 | NA | NA
293 | 12.7 | unknown - purchased 2017 | NA | NA
294 | 12.7 | unknown - purchased 2017 | NA | NA
296 | 12.7 | unknown - purchased 2017 | NA | NA
368 | 14.9 | tag failed to register | 12/27/2017 | 233_2017-08-24T19-00-56.356_WHIM_YA2017Mingan.7z
374 | 14.9 | tag failed to register | 12/27/2017 | 233_2017-08-24T19-00-56.356_WHIM_YA2017Mingan.7z
97 | 5.9 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-36-08.240_REKN_Mingan1.7z
99 | 5.9 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-36-08.240_REKN_Mingan1.7z
101 | 5.9 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-36-08.240_REKN_Mingan1.7z
102 | 5.9 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-36-08.240_REKN_Mingan1.7z
111 | 5.9 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-36-08.240_REKN_Mingan1.7z
208 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
211 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
213 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
215 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
217 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
219 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
220 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
222 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
224 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
227 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
228 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
232 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
233 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
234 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
235 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
238 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
239 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
240 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
243 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
244 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
245 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-34-04.800_SESAMingan_2018.7z
248 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-41-47.124_REKN_MinganHY_2018.7z
249 | 12.7 | tag failed to register | 7/9/2018 | 233_2018-07-09T20-41-47.124_REKN_MinganHY_2018.7z
367 | 16.7 | tag failed to register | 7/10/2018 | 233_2018-07-10T16-20-55.090_REKN_Mingan3.7z
371 | 16.7 | tag failed to register | 7/10/2018 | 233_2018-07-10T16-20-55.090_REKN_Mingan3.7z
373 | 16.7 | tag failed to register | 7/10/2018 | 233_2018-07-10T16-20-55.090_REKN_Mingan3.7z
376 | 16.7 | tag failed to register | 7/10/2018 | 233_2018-07-10T16-20-55.090_REKN_Mingan3.7z

**Comment by cjardine-bsc** [comment]
Jeremy go ahead and try to re-register those tags from the recordings. We'll end up with duplicates but we should be able to manage those. 

Anything that doesn't register we can try to do manually.

**Comment by Hussell** [comment]
Rerunning these upload jobs didn't result in any new registrations. I did get a few new error messages. It looks like the NA entries above were uploaded in job 105411, 2017-12-27, filename SESA_YA2017Mingan.7z. Of those, most were registered, except for the following mfgIDs: 282, 289, 291, and 294. Those 4 and the non-NAs on the list all generated variants of the following error message: "Unable to get a good estimate of burst interval for tag id 368 in file tag368.wav Please re-record this tag and re-upload"

There were also 7 more tags in the last job (REKN_Mingan3) which didn't register (same error as above), but aren't on the list: mfgIDs 378, 380, 390, 399, 403, 406, and 415.

**Comment by cjardine-bsc** [comment]
I'm not seeing any tags for project 3 with a 2019 datebin. So I'm assuming no duplicates registered when you tried Jeremy. 

Lucas can you please confirm these next two steps: 

1. Change the period of the below existing tags: 

30477 to 12.7
30484 to 12.7
30487 to 12.7
30490 to 5.9

2. Manually register the following 58 tags. Lucas can you please provide a tag model for each? It looks like they had a mix of tag models registered in 2017 and 2018. 

[manreg.xlsx](https://github.com/MotusDev/Motus-TO-DO/files/2902603/manreg.xlsx)

mfg_id | project | period | frequency | model
272 | 3 | 12.7 | 166.38 |  
273 | 3 | 12.7 | 166.38 |  
274 | 3 | 12.7 | 166.38 |  
275 | 3 | 12.7 | 166.38 |  
276 | 3 | 12.7 | 166.38 |  
277 | 3 | 12.7 | 166.38 |  
278 | 3 | 12.7 | 166.38 |  
279 | 3 | 12.7 | 166.38 |  
280 | 3 | 12.7 | 166.38 |  
281 | 3 | 12.7 | 166.38 |  
282 | 3 | 12.7 | 166.38 |  
283 | 3 | 12.7 | 166.38 |  
284 | 3 | 12.7 | 166.38 |  
285 | 3 | 12.7 | 166.38 |  
286 | 3 | 12.7 | 166.38 |  
287 | 3 | 12.7 | 166.38 |  
288 | 3 | 12.7 | 166.38 |  
289 | 3 | 12.7 | 166.38 |  
290 | 3 | 12.7 | 166.38 |  
292 | 3 | 12.7 | 166.38 |  
293 | 3 | 12.7 | 166.38 |  
294 | 3 | 12.7 | 166.38 |  
296 | 3 | 12.7 | 166.38 |  
368 | 3 | 14.9 | 166.38 |  
374 | 3 | 14.9 | 166.38 |  
97 | 3 | 5.9 | 166.38 |  
99 | 3 | 5.9 | 166.38 |  
101 | 3 | 5.9 | 166.38 |  
102 | 3 | 5.9 | 166.38 |  
111 | 3 | 5.9 | 166.38 |  
208 | 3 | 12.7 | 166.38 |  
211 | 3 | 12.7 | 166.38 |  
213 | 3 | 12.7 | 166.38 |  
215 | 3 | 12.7 | 166.38 |  
217 | 3 | 12.7 | 166.38 |  
219 | 3 | 12.7 | 166.38 |  
220 | 3 | 12.7 | 166.38 |  
222 | 3 | 12.7 | 166.38 |  
224 | 3 | 12.7 | 166.38 |  
227 | 3 | 12.7 | 166.38 |  
228 | 3 | 12.7 | 166.38 |  
232 | 3 | 12.7 | 166.38 |  
233 | 3 | 12.7 | 166.38 |  
234 | 3 | 12.7 | 166.38 |  
235 | 3 | 12.7 | 166.38 |  
238 | 3 | 12.7 | 166.38 |  
239 | 3 | 12.7 | 166.38 |  
240 | 3 | 12.7 | 166.38 |  
243 | 3 | 12.7 | 166.38 |  
244 | 3 | 12.7 | 166.38 |  
245 | 3 | 12.7 | 166.38 |  
248 | 3 | 12.7 | 166.38 |  
249 | 3 | 12.7 | 166.38 |  
367 | 3 | 16.7 | 166.38 |  
371 | 3 | 16.7 | 166.38 |  
373 | 3 | 16.7 | 166.38 |  
376 | 3 | 16.7 | 166.38 |

**Comment by Hussell** [comment]
Perhaps I wasn't clear enough. It looks like most of the tags in the first part of the list, up to and including mfg_id 296, were successfully registered when they were first uploaded, except for mfg_ids 282, 289, 291, and 294. So, 19 tags which don't need to be registered. (Though it wouldn't hurt to double-check that.)

Also, there are some tags not on the list which probably need to be manually registered: mfg_ids 378, 380, 390, 399, 403, 406, and 415, still from project 3.

**Comment by cjardine-bsc** [comment]
Lucas would you like to do that double checking and send me a list of tags you need manually registered?

**Comment by leberrigan** [comment]
There are other tags that exist with these specs, but they were registered in 2014 and deployed no later than 2015 on bats in projects 50 and 71. The tags for project 3 are still not registered. I will confirm with the user which model they were and then provide with you with a list.

**Comment by leberrigan** [comment]
Here's the list of tags that need to be manually registered with tag models:

Tags with incorrect period:

tagID | mfgID | correct period | tag model
-- | -- | -- | --
30490 | 96 | 5.9 | ANTC-M4-2S
30477 | 214 | 12.7 | NTQB2-3-2
30484 | 229 | 12.7 | NTQB2-3-2
30487 | 236 | 12.7 | NTQB2-3-2

Tags to be manually registered:

mfgID | approx period | tag model
-- | -- | --
272 | 12.7 | NTQB-3-2
273 | 12.7 | NTQB-3-2
274 | 12.7 | NTQB-3-2
275 | 12.7 | NTQB-3-2
276 | 12.7 | NTQB-3-2
277 | 12.7 | NTQB-3-2
278 | 12.7 | NTQB-3-2
279 | 12.7 | NTQB-3-2
280 | 12.7 | NTQB-3-2
281 | 12.7 | NTQB-3-2
282 | 12.7 | NTQB-3-2
283 | 12.7 | NTQB-3-2
284 | 12.7 | NTQB-3-2
285 | 12.7 | NTQB-3-2
286 | 12.7 | NTQB-3-2
287 | 12.7 | NTQB-3-2
288 | 12.7 | NTQB-3-2
289 | 12.7 | NTQB-3-2
290 | 12.7 | NTQB-3-2
292 | 12.7 | NTQB-3-2
293 | 12.7 | NTQB-3-2
294 | 12.7 | NTQB-3-2
296 | 12.7 | NTQB-3-2
368 | 14.9 | NTQB-4-2
374 | 14.9 | NTQB-4-2
97 | 5.9 | ANTC-M4-2S
99 | 5.9 | ANTC-M4-2S
101 | 5.9 | ANTC-M4-2S
102 | 5.9 | ANTC-M4-2S
111 | 5.9 | ANTC-M4-2S
208 | 12.7 | NTQB2-3-2
211 | 12.7 | NTQB2-3-2
213 | 12.7 | NTQB2-3-2
215 | 12.7 | NTQB2-3-2
217 | 12.7 | NTQB2-3-2
219 | 12.7 | NTQB2-3-2
220 | 12.7 | NTQB2-3-2
222 | 12.7 | NTQB2-3-2
224 | 12.7 | NTQB2-3-2
227 | 12.7 | NTQB2-3-2
228 | 12.7 | NTQB2-3-2
232 | 12.7 | NTQB2-3-2
233 | 12.7 | NTQB2-3-2
234 | 12.7 | NTQB2-3-2
235 | 12.7 | NTQB2-3-2
238 | 12.7 | NTQB2-3-2
239 | 12.7 | NTQB2-3-2
240 | 12.7 | NTQB2-3-2
243 | 12.7 | NTQB2-3-2
244 | 12.7 | NTQB2-3-2
245 | 12.7 | NTQB2-3-2
248 | 12.7 | NTQB2-4-2
249 | 12.7 | NTQB2-4-2
367 | 16.7 | ANTC-M4-2S
371 | 16.7 | ANTC-M4-2S
373 | 16.7 | ANTC-M4-2S
376 | 16.7 | ANTC-M4-2S




mfgID | approx period | tag model
-- | -- | --
272 | 12.7 | NTQB-3-2
273 | 12.7 | NTQB-3-2
274 | 12.7 | NTQB-3-2
275 | 12.7 | NTQB-3-2
276 | 12.7 | NTQB-3-2
277 | 12.7 | NTQB-3-2
278 | 12.7 | NTQB-3-2
279 | 12.7 | NTQB-3-2
280 | 12.7 | NTQB-3-2
281 | 12.7 | NTQB-3-2
282 | 12.7 | NTQB-3-2
283 | 12.7 | NTQB-3-2
284 | 12.7 | NTQB-3-2
285 | 12.7 | NTQB-3-2
286 | 12.7 | NTQB-3-2
287 | 12.7 | NTQB-3-2
288 | 12.7 | NTQB-3-2
289 | 12.7 | NTQB-3-2
290 | 12.7 | NTQB-3-2
292 | 12.7 | NTQB-3-2
293 | 12.7 | NTQB-3-2
294 | 12.7 | NTQB-3-2
296 | 12.7 | NTQB-3-2
368 | 14.9 | NTQB-4-2
374 | 14.9 | NTQB-4-2
97 | 5.9 | ANTC-M4-2S
99 | 5.9 | ANTC-M4-2S
101 | 5.9 | ANTC-M4-2S
102 | 5.9 | ANTC-M4-2S
111 | 5.9 | ANTC-M4-2S
208 | 12.7 | NTQB2-3-2
211 | 12.7 | NTQB2-3-2
213 | 12.7 | NTQB2-3-2
215 | 12.7 | NTQB2-3-2
217 | 12.7 | NTQB2-3-2
219 | 12.7 | NTQB2-3-2
220 | 12.7 | NTQB2-3-2
222 | 12.7 | NTQB2-3-2
224 | 12.7 | NTQB2-3-2
227 | 12.7 | NTQB2-3-2
228 | 12.7 | NTQB2-3-2
232 | 12.7 | NTQB2-3-2
233 | 12.7 | NTQB2-3-2
234 | 12.7 | NTQB2-3-2
235 | 12.7 | NTQB2-3-2
238 | 12.7 | NTQB2-3-2
239 | 12.7 | NTQB2-3-2
240 | 12.7 | NTQB2-3-2
243 | 12.7 | NTQB2-3-2
244 | 12.7 | NTQB2-3-2
245 | 12.7 | NTQB2-3-2
248 | 12.7 | NTQB2-4-2
249 | 12.7 | NTQB2-4-2
367 | 16.7 | ANTC-M4-2S
371 | 16.7 | ANTC-M4-2S
373 | 16.7 | ANTC-M4-2S
376 | 16.7 | ANTC-M4-2S

**Comment by cjardine-bsc** [comment]
All but two have been registered. NTQB2-4-2 is not a valid model. Can you double check?

EXEC prTagManualRegistration 248,3,12.7,'NTQB2-4-2',166.38
EXEC prTagManualRegistration 249,3,12.7,'NTQB2-4-2',166.38

**Comment by leberrigan** [comment]
Hmm that's odd.. This model is listed in their new series of NTQB2's:
[NTQB2 Weight & Life Estimates.pdf](https://github.com/MotusDev/Motus-TO-DO/files/2906959/NTQB2.Weight.Life.Estimates.pdf)

But I'll ask to confirm since that does seem suspicious.

**Comment by cjardine-bsc** [comment]
I have a 2S listed. Is it the same?

NTQB2-4-2S

**Comment by leberrigan** [comment]
Yes, these tags were supposed to be labeled as NTQB2-4-2S.

As for the new tags listed in the PDF I provided, I'm not certain if they also have that suffix.

**Comment by cjardine-bsc** [comment]
Registered at  NTQB2-4-2S. 

You can let the user know they can create their deployments now.

**Comment by StuMackenzie** [comment]
@leberrigan - resolved?
