### ISSUE TITLE
Admin user management issues

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#45]
On https://sandbox.motus.org/data/admin/user_id , clicking either of "Users with Accounts" or "Users without Accounts" causes an error.

When editing a user from this page, there's no easy way to view or update the user's status, as you can on https://sandbox.motus.org/data/admin_users.jsp (which is no longer linked from anywhere, but might be bookmarked by Stu).

**Comment by pmorrill** [comment]
The first part of this should be ok now. The user tool needs a work over - it was never really finished and uses a generic template, rather than a custom form, which is what it needs. Let's make sure we don't remove the old jsp version for the time being.

**Comment by Hussell** [comment]
Attempting to change a user's status results in an SQL error.
https://sandbox.motus.org/data/admin/user_id?id=347

**Comment by pmorrill** [comment]
The exception is not related to updating the user status.

It arises from a fk constraint on the user_id table, when either country or state/province are missing from the update. This constraint does not seem as rigid on my (earlier) version of the sandbox database.

The admin tools are no longer requiring state/province or country for users: making them mandatory reduces the utility of the tool. Landowners in the system are often missing country / state information, for example. (Strangely, landowners can be updated even if missing these fields, but they use the bsc utility class to make their updates.)

I don't think that we have a world-wide listing of state/province codes, so this constraint might need to be removed. (The statprov_codes table only carries 97 records).

Here is the Exception, for reference (there is a 2nd one for the country  field)

Encountered a DBException type 7 - Low-level Database error.

Error description: Creating prepared statement on: user_id (Made it to result set wrapper)

SQL exception: com.microsoft.sqlserver.jdbc.SQLServerException: The UPDATE statement conflicted with the FOREIGN KEY constraint "FK_user_id_statprov_codes". The conflict occurred in database "motus_sandbox", table "dbo.statprov_codes", column 'statprov_code'.

While attempting: UPDATE user_id SET backup_id = ?,re_user_id = ?,user_code = ?,login_name = ?,salutation = ?,email = ?,last_name = ?,middle_name = ?,first_name = ?,street1 = ?,street2 = ?,company = ?,city = ?,statprov_code = ?,post_code = ?,country_code = ?,phone = ?,phone_business = ?,fax_number = ?,pword = ?,last_login_dt = ?,create_dt = ?,real_user = ?,ghost_user = ?,pw_must_change = ?,enabled = ?,newsletter = ?,language_code = ?,solicit_code = ?,last_edited_dt = ?,last_edited_user_id = ?,is_new = ?,pword_salt = ?,pword_hash = ? WHERE user_id = ?

**Comment by Hussell** [comment]
Looks like that's fixed. I'll make a note that we can probably delete admin_users.jsp too.
