### ISSUE TITLE
Project 211 - wrong frequencies being used. 

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#452]
Can we confirm that these receivers are being dealt with on 150.100 MHz and not 166.380MHz, and rerun if necessary. This may have been dealt with, if so, please close.

**Comment by Hussell** [comment]
There were no overrides set. Two of the four receivers in the project appear to be reporting their listening frequency correctly (SG-1816BBBK2137 and SG-4616BBBK2363), one I'm not sure (SG-2316BBBK0426) and the last definitely isn't (SG-1914BBBK0960). I've set a project-wide override, and I'll rerun these receivers today.
