### ISSUE TITLE
Data Issues not being updated for projects with ID > 178

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#455]
If I go to, e.g. https://motus.org/data/issues?id=179, I see "Your data has never been validated.", and pressing the button has no visible effect. In the table adm_validation_process, there are no rows for projects with ID > 178. It looks like pressing the "Validate Button" data does, in fact, run prData_Validation_pr for that project, even though the status message can't update, but it also looks like the nightly prData_Validation_pr is **only** validating projects with ID <= 178.

**Comment by cjardine-bsc** [comment]
New projects need to be written to [motus].[dbo].[adm_validation_process], looks like that wasn't implemented. 

Presumably we're using prCreateNewProject for new projects. I've added a step to that proc that inserts into adm_validation_process. 

I've also added the more recently created projects to that table.

**Comment by Hussell** [comment]
I accidentally created a new project in the live database, ID 245. Would you delete that, please?

**Comment by cjardine-bsc** [comment]
Deleted. I notice it didn't populate adm_validation_process.

**Comment by Hussell** [comment]
Indeed. prCreateNewProject is used by the API, but the webpage calls upsert on a ProjectBean, which does nothing but update the project table. I've added some code to insert a new row into adm_validation_process, and added a project to my list: rewrite that to use prCreateNewProject. Low priority, though.

**Comment by Hussell** [comment]
It might be simpler to have prData_validation_pr insert rows into adm_validation_process for projects which don't have a row, and delete rows for projects which no longer exist. That way project creation and deletion code doesn't have to know anything about that table, and almost everything about that table will be in one place instead of scattered around.

**Comment by Hussell** [comment]
Ok, code for adding a row to adm_validation_process when a new project is created has been deployed to live, but a couple of new projects were created in the interim. Catherine, would you add projects 246 and 247 to the table? This should be the last fix for this issue, hopefully.

**Comment by cjardine-bsc** [comment]
Done. 

HIYA! Closed.
