### ISSUE TITLE
Data Issues: Receiver Not Registered

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#457]
<s>Every time an individual project reruns their data validation, a new set of errors of type v_sensor_not_registered is added to **every** project, without erasing the old ones.</s> Fixed.

Possibly related: the description says "Receiver detection data has been uploaded by a user registered to this project, however the receiver is not registered to this project", but there are several cases where errors are being generated for users not registered to the project, and for receivers registered with another project. E.g. project 1 is getting an error about receiver 'SG-2313BBBK3275', registered with project 10, uploaded by user 347 (me!), who isn't registered with any project.

Be aware that the user IDs and project IDs in batches are often inaccurate. E.g. people upload things to the wrong project ID pretty frequently, the uploads from automatically synced receivers are all attributed to the same user ID (347) no matter what project they're registered with, and administrators have to rerun upload jobs sometimes.

**Comment by cjardine-bsc** [comment]
The first issue is a simple fix. Those checks were not referencing the @proj variable. I've added that, which should fix the first problem. 

For the second.  

The project_id used for the check is the project that the user uploaded the dataset under. The assumption is that the user can`t upload data under a project they are not registered too. I'm guessing that is not accurate?

Looks like I might need to tweak the check based on auto synced receivers since the behavior of the upload is inaccurate (or should we change it so the user and project of auto synced receivers is NULL?).

**Comment by Hussell** [comment]
> The assumption is that the user can`t upload data under a project they are not registered too. I'm guessing that is not accurate?

Correct, this assumption is not accurate. Mostly the tagfinder relies on the serial number of the receiver and our deployment metadata to decide which data belongs to which device. But the batches are sent with the project ID which the user provided, which may or may not be correct, not the project ID of the deployment.

Another thing which users do is upload archives with data for multiple projects. Of course, they can only give one project ID with the upload, so the others get an inaccurate project ID.

**Comment by Hussell** [comment]
Ok, there are 11 receivers registered to project 0, not registered to another project, and which have batches of data with a project ID. I think these are the only ones which should be generating this error. But we have 171 of these errors. The key, I think, is to make certain that the receiver is not registered to any project except project 0. Otherwise, we can't be certain the batch of data was not uploaded to the wrong project by accident. (Well, we can't be certain this way either, but at least none of these 11 have had data uploaded as if to multiple projects despite being registered to only one project like, say, SG-3615BBBK0DB6 or SG-4001BBBK1870.)

|Probable project|Receiver|
|-|-|
|1|SG-3CD7RPI30747|
|1|SG-CE18RPI39271|
|35|SG-0C94RPI3335E|
|74|Lotek-313|
|120|SG-2516BBBK1DAE|
|120|SG-7100BBBK0176|
|181|SG-18DFRPI2062E|
|181|SG-21CCRPI3EA67|
|181|SG-5AA7RPI2D99F|
|181|SG-9AFARPI2F695|
|181|SG-B541RPI27574|

A different test case: SG-4002BBBK1620 is registered to project 0, not registered to any other project, but doesn't have any associated batches of data which could clue you in to what project it goes to. (I think this was registered because of a typo in the serial number during a manual receiver rerun.) This receiver should not generate an error.

**Comment by denislepage** [comment]
The key issue for those is that they do not have any deployment information. They obviously also need to be registered to a project, but getting the deployment info would be key.

I did some work last fall to try and help identify missing deployments based on batch and gps data. I had done some work on a tool showing the GPS locations on a receiver timeline, with the idea of identifying periods for missing deployments. That page was deleted recently and should be restored. I think it was called receiver_timelines.jsp or timelines.jsp or something along those lines.

**Comment by cjardine-bsc** [comment]
Okay, I've removed the part of the check based on the projectID in sg_batches. That brings things back to 12 errors. 

We have a different error for receivers without deployments or for hits outside of existing deployments.

**Comment by Hussell** [comment]
Awesome!
