### ISSUE TITLE
SGDataImport doesn't resume correctly

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#458]
I have been noticing some instances where tables have been incompletely loaded, but the batches record was still marked as completed. This has caused several issues in sandbox, since we had disabled the referential integrity among SG tables. After re-enabling the referential integrity, we started getting database errors suggesting that runID records were missing when trying to insert hits. It appears that the runs table is not correctly being resumed.

I think this has to do with the fact that the runs are overlapping batches, and that a failed batch import is set aside, allowing subsequent ones to continue importing.

Say batch 1 imports, and that none of the runs records are imported because of a database failure. The loop stops for that batch, and hits are also being ignored.

Batch 2 then correctly imports within the same import event, along with all associated run and taghits. Important here, some of the runs (and hits) included in batch2 were initiated on batch 1 (batchIDBegin = 1).

One the next import event, batch 1 is being resumed. When trying to see the last runID record that was read, the process looks for lastRunID = max(runID) where batchIDBegin = 1. Because batch 2 also had runs initiated on batch 1, a number of runs records may thus be skipped.

Two options seem available:

- stop the entire import event, and prevent new batches from being imported while any failed batches still exist
- get the last runID from sg_batches_runs

The latter approach may be the best. However, it also presumes that the sg_batches_runs table is correctly created and in sync with the sg_runs table. If the error happens on the last step (inserting into sg_batches_runs, then the next import may try to re-insert duplicate runs records. This is still better than doing the sg_batches_runs insert first (which could lead to sg_runs records being missed).

I have changed the getLastRunID method to rely on sg_batches_runs table for now (option 2), in sandbox.

**Comment by denislepage** [comment]
Other potential issues with derived SG tables caused by an interruption of the import loop:

- sg_batches_runs: as mentioned above, a failed run import will lead to missing records in sg_batches_runs. This will lead to insert errors if the runs records were inserted, but not the batches_runs ones. One option is to add IF NOT EXISTS statements before each insert when in resume mode for sg_runs records. Another one is to remove runs records at the start of a resume batch where sg_batches_runs don't exist. Not sure which is most efficient, but I think the delete option may not work (runs may be tied to other subsequently imported batches).

- sg_batches_runs_tags: should work ok. addBatchesRunsTags is always called for a batchID after the runs records are read, so resuming a batch should work here. Only new records are being added, so partial transfers should be ok.

sg_taghits_deploy_id and sg_gps_deploy_id: Failed inserts in those tables did not previously recovered correctly, and likely resulted in missing records. I have replaced the explicit inserts in java with INSTEAD OF triggers in sg_taghits and sg_gps. Inserts in the deploy_id tables now happen in the same transactions as the inserts in the main table, which should eliminate childless records.

**Comment by denislepage** [comment]
I have now implemented BOTH options from the original issue:

1. If have made several changes to SGDataImport for resuming transfer of failed batches. I am now reading lastRunID from sg_batches_runs and assuming that some run records may already present during a resume loop (using an upsert, which only does the NOT EXISTS and not the update). 

2. Errors will also stop the entire thread, which should limit the possible errors caused by earlier missing data. This is a bit overkill, but there will otherwise be some rare instances where this causes problems. One downside is that if a single batch has a consistent problem and cannot be imported, the entire import process will fail until the problem is resolved. I am not aware that this has ever been an issue, though failed relational integrity with tagID's or receivers could cause such problem (this is currently disabled in sandbox for that very reason)

Steps to deploy in beta:

- [ ] stop the SGDataImport recurring queue (active = 0)
- [ ] add triggers to sg_taghits and sg_gps
- [ ] merge changes from master and redeploy beta8

**Comment by denislepage** [comment]
OK, all done. We should keep an eye on the queue in both db, and make sure that the sg_taghits_deploy_id and sg_gps_deploy_id tables are correctly populated by the triggers.

Also keeping an eye for errors, and making sure that the resume features now work well, since chronic errors will now stop the queue from continuing.

There are some inconsistencies in records between sandbox and live. This would likely be a bit challenging given the size of some of the tables, but it would be nice to try to resolve them, mostly so we can keep track of any new ones being created in the future.

**Comment by denislepage** [comment]
The following tables should now be consistent between db's: sg_batches, sg_gps, sg_gps_deploy_id, sg_runs

still remaining to sync:

sg_batches_runs, sg_pulse_counts, sg_taghits (in progress), sg_taghits_deploy_id

**Comment by denislepage** [comment]
I think this can be closed for now. The tables above are now the same size in both db. There are a few other tables that differ, but those are mainly due to difference in metadata (e.g. at the time when the summary was generated for a batch), and it is probably not worth trying to synchronize them (would likely require a full re-run of some of the summaries, or a transfer from live, but both would be messy).

sg_ambig_tags, sg_ambig_tags_orig, sg_batches_activity, sg_batches_runs_tags, sg_batches_tags,  sg_runs_filters, sg_runs_tags_orig.

That said, I am going to look into the latter (sg_runs_tags_orig). I also just noticed that it did not have a primary key, nor a foreign key to sg_runs. I am not sure yet if I would put a foreign key on motusTagID or ambigID, however.

**Comment by cjardine-bsc** [comment]
No FK on sg_tuns_tags_orig for motusTagID please, the idea is that that table will still contain deleted (merged) tag IDs. 

AmbigID is probably okay to have a FK.
