### ISSUE TITLE
Motus Upload Errors not Flagged Correctly

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#464]
It appears that some upload jobs are not processing successfully, but they are still labeled as 'complete'. See Job ID [363338](https://motus.org/data/project/sgJobs?projectID=247) for example.

It's helpful to have these labelled correctly so we can easily identify erroneous uploads. This will also be important for the response email once we implement the changes mentioned in #445.

**Comment by StuMackenzie** [comment]
presumed resolved.
