### ISSUE TITLE
Project 1 file repo/db mismatches in 2015

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#468]
I've noticed there are quite a few receivers in project 1 which have repo/db mismatches in 2015, e.g. [SG-5113BBBK3116](https://sgdata.motus.org/status?serno=SG-5113BBBK3116), [SG-4002BBBK1580](https://sgdata.motus.org/status?serno=SG-4002BBBK1580), [SG-5113BBBK2661](https://sgdata.motus.org/status?serno=SG-5113BBBK2661), [SG-4001BBBK2440](https://sgdata.motus.org/status?serno=SG-4001BBBK2440), [SG-4002BBBK1770](https://sgdata.motus.org/status?serno=SG-4002BBBK1770), etc. Further examples aren't difficult to find.

Any idea what's going on there?

**Comment by Hussell** [comment]
#170

**Comment by denislepage** [comment]
I have no idea what that error refers to, but the db in this case almost certainly doesn’t refer to the Motus database. Perhaps the MariaDB, or the project SQLite files.

The data that we seem to have for say receiver SG-5113BBBK3116 (device id: 331) in Motus Starts on 10 July 2015.

there are batches for the Jan- July 2015 period, but most of them have 0 detections. The data appears consistent between Motus and MariaDB.

If there are data available for the periods in red, or earlier through most of 2014, they are not available, so the question is what is this summary based on, and what are the numbers associated with each dates.

**Comment by Hussell** [comment]
Right, this question was intended for John, thus the assignment to him. I forgot (again) that you (Denis) receive every comment here as email. The numbers are: actual number of data files in the receiver's directory, on the left, and number of files recorded in the database, on the right. So in these cases there are files missing from the server, which were processed earlier and thus left a record in the database.

**Comment by Hussell** [comment]
Seems unlikely we'll ever find a copy of the missing files.
