### ISSUE TITLE
sensor antennas unique key needed

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#470]
I did a bit of motus-synching today.

I created the new sample_r_batch_activities table in motus, in support of the new activity API entry point.

I was looking at the sample tables in motus_sandbox, and realized that none of those tables have primary keys. All tables should have a primary, really. I started created them, but discovered another problem when I reached “sample_r_metadata_for_receivers_antdeps”. DeployID + ant is not unique. The same problem occurs in the sensor_antennas table. E.g. this one has antenna #1 on all 3 rows.

select top 100 * from sensor_antennas where deployment_id = 2941

This should not be allowed. We should add a unique index to the sensor_antennas table (Catherine), but that will require fixing the existing port numbers. We may have to assign them to arbitrary numbers, but we should check with users to do correctly wherever possible (Lucas). 

select deployment_id, port, count(*) from sensor_antennas 
group by deployment_id, port
having count(*) > 1

Paul: The web interface may also need to be modified to prevent this from attempting to reach the database.

**Comment by denislepage** [comment]
I also noticed that port was not a required field, so I added this constraint. I have modified the existing non-clustered index to include the port field as well as the deployment_id. We'll still need to add a unique constraint once the issues with duplicate port numbers are fixed.

**Comment by cjardine-bsc** [comment]
Paul, I just tested the website and it does indeed allow you to enter two port numbers the same. We'll need to add an error flag for this which prevents entry of duplicate port number (or just pre-populate the port numbers on the form?)

Lucas, the problem exists in the following projects:
2,64,106,78,130,3,172

And these deployments: 
2941,
2946,
3194,
3219,
3394,
3875,
4189,
4265,
4272,
4342,
4989,
5014,
5015,
5016,
5020,
5047

**Comment by cjardine-bsc** [comment]
Denis, I notice your new table (sample_r_batches_activity) doesn't have the not null restrictions that are included in sandbox. Was this on purpose?

**Comment by denislepage** [comment]
I may have added not null to sandbox after I created the table. Add away.

**Comment by pmorrill** [comment]
Have checked in a handler (master and beta8 branches). It adjusts any duplicates to the next available port, and posts a warning to the user to check the port information.

It only works on NEW ports added: it will not correct existing duplicates.

**Comment by pmorrill** [comment]
I will add the warning msg manually into both sandbox and live databases (EN only)
