### ISSUE TITLE
List of features in beta9

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#472]
* Allow receiver and tag deployment start/end dates to be edited at any time (#456)
* Disallow setting a species on a test tag deployment (#425)
* Support for new column in user_properties: policy_accepted_dt
* New entry on project page: institution which will pay fees (#515)
* New on Lotek receiver deployment pages: specify UTC offset (#478)
* Receiver deployments: handle duplicate port numbers
* Receiver deployments: handle CTT serial numbers (#521)
* CTT registration page
* API for CTT authentication (login)
* API for CTT authorization (project permissions)
* API for CTT receiver registration (#509)
* API for CTT tag registration
* API for SGData activity query
* Interface for administrators to browse the files in CTT's AWS storage and our NAS
* File transfer to and from CTT's AWS storage
* Background process to automatically download and process files from CTT's AWS storage
* R-client API for returning deprecated batches (#511)
* Support for batch version numbers (#437, #461)
* Switch from sg_ to det_ tables (#508, #510)
* Create fewer new ProjInfo objects
* Improved handling of job processes which are interrupted
* Many improvements to logs produced by background processes
* Increase minimum # of database connections in the pool from 3 to 15
* Changes to filters in detection summaries (now handled when summaries are generated) (#493)
* Performance improvements in ComputeTracks (#460)
* Support for batch updates in Database (#460)
* Change Attributes and Messages to match the model used by Parameters and Database (slightly reduced boilerplate necessary for use, internally simplified)
* Access all session and application attributes through Attributes class
* Deleted a lot of unused dead files (#271)
* Miscellaneous bug fixes
* Miscellaneous cleanup suggested by static analysis

**Comment by StuMackenzie** [comment]
can we close?
