### ISSUE TITLE
add new field utcOffset to R package

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#477]
For Steffi.

We should add a field utcOffset in the motus R package for the table recvDeps.

It will also need to be added in the updateMotusDb database.

The field is already in the R view and should be picked up by the API automatically. As far as I remember, you should only have to ensure that the new field is added with new database and existing ones. The rest should be done automatically.

We’ll need to amend the R book also.

**Comment by steffilazerte** [comment]
This feature is in the staging branch, but hasn't been added to the R book yet.
