### ISSUE TITLE
Add tag label to 'frequency' on receiver map

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#479]
Related to #396 

Can you please add the labels corresponding to each frequency - 

150.1 MHz (Lotek NanoTags - Europe)
151.5 MHz (Lotek NanoTags - Australia)
166.380 MHz (Lotek NanoTags - Western Hemisphere)
433 MHz (CTT Life & Power Tags - Worldwide)

I'm not sure about including the geographic reference.

**Comment by Hussell** [comment]
On beta, frequency descriptions are being pulled from the database now.

**Comment by StuMackenzie** [comment]
looks good thanks
