### ISSUE TITLE
Missing tag registration for project #185

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#483]
Tag Mfg ID 141, NTQB2-3-2, 3.7 sec burst is missing from project 181. It was not recorded.  Contact is Phillip Vasseur <PVasseur@wlf.la.gov> if we need more information, or for followup.

**Comment by cjardine-bsc** [comment]
Registered at 166.38

**Comment by StuMackenzie** [comment]
Still now showing up in Project 181. ;) Thanks.

**Comment by Hussell** [comment]
It looks like that's the _only_ tag registered to project 181.

https://motus.org/data/tag?id=34326

**Comment by Pvasseur-ldwf** [comment]
Just to clarify, the project is #185. Thanks

**Comment by StuMackenzie** [comment]
whoops - my bad. Original querry was for project 181, all other tags are in 185.

**Comment by Hussell** [comment]
Ping to Catherine: this tag should be moved from project 181 to project 185.

**Comment by cjardine-bsc** [comment]
Thanks for the ping. Tag has been moved.
