### ISSUE TITLE
New Sensorgnome Website = Broken Links on Motus.org

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#484]
John has recently re-vamped the Sensorgnome website, archiving all the old docs in the meantime. As a result, all links on that refer to Sensorgnome.org docs are broken.

Luckily, John has just moved these to the 'archived.' subdomain so we need only add this prefix to all URLs.

I'll go through what I can to update links, but I may need help finding them all! From what I can tell, all links to Sensorgnome.org are in the pages under 'Resources'.

**Comment by Hussell** [comment]
I found a couple of links to https://sensorgnome.org/VHF_Tag_Registration in the database and changed them to https://archived.sensorgnome.org/VHF_Tag_Registration.

There are a few more sensorgnome.org URLs in the table adm_platform_api, which I don't have the permissions to change.

**Comment by cjardine-bsc** [comment]
Updated adm_platform_api in live and sandbox.

**Comment by leberrigan** [comment]
Links in all PDF documents are also broken:
https://motus.org/wp-content/uploads/2017/08/Motus_LandownerInformation_April2017.pdf
https://motus.org/wp-content/uploads/2016/01/MotusCollaborationPolicy.January2016.pdf

These have not been fixed.

**Comment by cjardine-bsc** [comment]
Hi lucas, you should be able to edit the files and then just re-upload to wordpress.

**Comment by leberrigan** [comment]
There is a broken link in the response email when registering tags:

https://.sensorgnome.org/VHF_Tag_Registration/Uploading_the_tags_database_file_to_your_SensorGnome/

**Should be:**
https://archived.sensorgnome.org/VHF_Tag_Registration/Uploading_the_tags_database_file_to_your_SensorGnome/

**Comment by Hussell** [comment]
Ok, I've fixed that link in the code and deployed the fix. I also searched the motusServer repository for more links to sensorgnome.org. That seems to have been the only one.
