### ISSUE TITLE
frequency accuracy requirements for tag registration?

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#486]
Lotek is nearing completion of an automatic tag registration process files for upload to Motus prior to tag delivery. 

How precise does the frequency calculation have to be? They currently record it to 0.1kHz.

**Comment by Hussell** [comment]
It looks like the bulk of the tags in our database are also recorded to 0.1kHz. Also, the tag finder allows the frequencies of the pulses within a burst to vary a little, so long as they're all within a range of 0.5kHz.

**Comment by denislepage** [comment]
Assuming this all works, the next step will be to modify tag finder to accept registrations through an API. I’ll talk to Joey this week and add this to the list of desirable features.

We’ll need to compare the values we get from recordings vs. the Lotek provided ones, and see how much variation we get. Some testing of tag finder using these values would also be desired.

Having a test environment should make this simpler to do.
