### ISSUE TITLE
Lotek-313 vs Lotek-D000313

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#490]
Project 74 has uploaded some files with data for receiver Lotek-313, but don't have it registered. On the other hand, they have registered Lotek-312, -314, -315, and Lotek-D000313, the latter of which has no data.

I guess we should contact someone with project 74 to confirm before we try to fix anything, in case I'm wrong about this.

**Comment by leberrigan** [comment]
Uploaded file was labelled '**Arcadia**_14Nov18_allsinceJune18.DTA'. Registered deployment for Lotek-D000313 is also called 'Arcadia'.

I think it's safe to assume these are supposed to be the same receiver. I'll go in and change the serial number to **Lotek-313**

**Comment by Hussell** [comment]
The serial number should be 'Lotek-313' and model 'SRX-800', I think. 'Lotek-D000313' is a serial number for a receiver of model 'SRX-800D' (or it would be, if it existed).

My guess: someone entered the wrong model (understandably, they only differ by one letter), then fudged the serial number when the form complained that the serial number didn't match the pattern for the model.
