### ISSUE TITLE
Overlapping deployment and duplicate tag registration errors for tags of different frequencies

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#491]
See data issues for project 186 as an example: https://motus.org/data/issues?id=186

Users are getting the errors "Overlapping Tag Deployment" and "Tag Registered Twice" where the 'other' tags have a different nominal frequency. All tags in project 186 are tuned to 150.100 MHz whereas the tags they are supposedly overlapping with are all tuned to 166.380 MHz.

**Comment by cjardine-bsc** [comment]
Ah, fixed.

**Comment by Hussell** [comment]
I just reran project 186's data validation, and they still get many overlapping tag deployment warnings for tags with different frequencies: https://motus.org/data/issues?id=186#v_tag_overlap_deploy_prop

**Comment by cjardine-bsc** [comment]
I just did it and it came out clean: https://motus.org/data/issues?id=186

**Comment by cjardine-bsc** [comment]
I hadn't done sandbox until I had run a comparison of the two procs to make sure I didn't over write anything we were testing ;)
