### ISSUE TITLE
Evaluate run filtering based on batches_activity 

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#493]
Moving this over to git-hub from my Feb 25 email. Sans SQL code. 

I’ve made changes in sandbox to implement the filtering on the basis of RunID based on hourly batch activity.  I’m starting with a fairly broad strokes filter:

Hourbins with > 100 runs where the proportion of runs of length 2 is greater than > 0.85  results in filtering out everything of run length < 5.  I also exclude any runs of runlength = 2. (not 3, that’s to be discussed, see below). 

Next I’ve added the a new column motusFilter to vwR_Runs_for_receiver and vwR_Runs_for_tag_project. These new fields have been added to the R package and the allTags view in sandbox. 

I’ve created a new view called vwR_Batches_Activity. This is a new table that has been included in the .motus file, for every batch that is included for the project/receiver.

I’ve changed the below procs to stop filtering in the proc itself and instead just exclude runs in the runs_filters table from the taghits summaries tables. 
prTaghitsSummariesBatchID, prTaghitsSummariesSensorDeployID, prTaghitsSummariesSensorID, prTaghitsSummariesTagDeployID, prTaghitsSummariesTagID

I’ve added a new field (motusFilter) to sg_taghits_runs and am updating that in the summaries since this table contains ALL runs (for movebank) we will need to filter this table based on motusFilter for public outputs. Jeremy there are likely some implications for you there but it shouldn’t be too complicated to change your run length > 3 filter to motusFilter IS NULL.  (or this which is quite efficient if you have runID:  and not exists (select * from sg_runs_filters g where b.runID = g.run_id)

For Data views, I’m not 100% sure what to do for vwBase_taghits_runs. This one was only including everything with n_hits > 3, so I’ve applied the motusFilter there, but we might want that at the vwData level instead. 

Unresolved questions: 

•         Do we continue filtering all runs with len < 3 from public outputs now that we have this information about noisy sites incorporated? 
•         Should I include a field for Proportion Run Length 2 in the sg_batch_activity table and vwR_Batches_activity views or continue to calculate these on the fly (both for prSGBatchesActivityBatchID and for users in R) 
•         Need a new R book section explaining the motusFilter column and the BatchesActivity table. 
•         What is vwBase_API_taghits used for? I need to sort out whether filtered Runs should be excluded from this or not. 

For testing we should look at how this filtering approach compares to the old approach (run_length > 3, still implemented on live). And 

- make sure that this approach isn't removing a lot of seemingly real runs
- make sure that the run length = 3 runs that are now being included using this new approach look seemingly real and should stay. 
-Steffi made a little function in R that allows users to create runs filters based on tweaking the parameters above (with respect to the batches activity table) folk should feel free to tweak the defaults I've chosen and see if they can get a better standard filter.

**Comment by cjardine-bsc** [comment]
Some examples of noisy sites to look at can be found here: https://github.com/MotusDev/Filtering-Noisy-Sites/issues/2

**Comment by cjardine-bsc** [comment]
Some examples of noisy sites to look at can be found here: MotusDev/Filtering-Noisy-Sites#2

**Comment by leberrigan** [comment]
I was emailed about a sketchy track from the Pacific Shorebirds project (#191). I don't see any differences between the three sites (Sandbox, Beta, Live), but there are definitely many false detections here. Is this relevant? In addition, there are no receivers showing up on the Sandbox map and the project name is different.

Live: https://motus.org/data/tracksMap?t=19151&t=19152&t=19153&t=19154&t=19156&t=19157&t=18935&t=19148&t=19149&t=19150&t=18638&t=18640&t=18641&t=18642&t=18643&t=18644&t=18645&t=18646&t=18674&t=18675&t=18676&t=18677&t=18678&t=18679&t=18931&t=18932&t=18933&t=18934&t=18936&t=18937&t=18938&t=18939&t=19155&e=2013-01-01&l=2019-12-31&p=191

Beta: https://beta.motus.org/data/tracksMap?t=19151&t=19152&t=19153&t=19154&t=19156&t=19157&t=18935&t=19148&t=19149&t=19150&t=18638&t=18640&t=18641&t=18642&t=18643&t=18644&t=18645&t=18646&t=18674&t=18675&t=18676&t=18677&t=18678&t=18679&t=18931&t=18932&t=18933&t=18934&t=18936&t=18937&t=18938&t=18939&t=19155&e=2013-01-01&l=2019-12-31&p=191

Sandbox: https://sandbox.motus.org/data/tracksMap?t=19151&t=19152&t=19153&t=19154&t=19156&t=19157&t=18935&t=19148&t=19149&t=19150&t=18638&t=18640&t=18641&t=18642&t=18643&t=18644&t=18645&t=18646&t=18674&t=18675&t=18676&t=18677&t=18678&t=18679&t=18931&t=18932&t=18933&t=18934&t=18936&t=18937&t=18938&t=18939&t=19155&e=2013-01-01&l=2019-12-31&p=191https://sandbox.motus.org/data/tracksSelect?e=2013-01-01&l=2019-12-31&p=235

**Comment by Hussell** [comment]
Stu found a good test case: https://motus.org/data/receiverDeployment?id=4945 

Noisy hours:
2018-10-09 18:00
2018-11-08 20:00
2019-02-08 19:00

**Comment by cjardine-bsc** [comment]
I synced the databases. There will no longer be differences between the two sites. 

We'll need to evaluate in R now instead using the motusFilter field in the runs table
