### ISSUE TITLE
Project 143 receivers

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#494]
Similar to #490, but different. Project 143 has [registered four Lotek receivers](https://motus.org/data/projectReceivers?n=1000&id=143), e.g. Lotek-441, but received data from four different Lotek receivers, e.g. LOTEK-D000441. In this case I'm not sure whether I can just change the serial numbers and models of the receivers with deployment metadata but no data. Will the records get merged properly?

My best guess: I should go ahead and fix the metadata, then rerun the receivers. I just want to double-check with others before doing that.

**Comment by cjardine-bsc** [comment]
It should update the data yes. There is a trigger on the sensor table the inserts prTaghitsDeployIDSensorID into the procs queue when the receiver ID is changed.

**Comment by Hussell** [comment]
This has been resolved except for Lotek-339 through Lotek-442 still having entries in the 'sensors' table. @cjardine-bsc, if you delete those, you can close this issue.

**Comment by cjardine-bsc** [comment]
I'm not seeing anything in the sensors table:

SELECT *
  FROM [motus].[dbo].[sensors]
  where receiverID in ('Lotek-339', 'Lotek-340','Lotek-341', 'Lotek-342')

**Comment by Hussell** [comment]
Sorry, I typo'd the numbers: Lotek-439 through 442. See here: https://motus.org/data/projectReceivers?id=143

**Comment by cjardine-bsc** [comment]
Okay I've removed those left over sensors. Closed! Woopa!
