### ISSUE TITLE
prDataValidation_pr updating adm_validation_process with wrong job ID

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#500]
The data validation procedure starts by setting the job in progress like so:

UPDATE adm_validation_process
SET job_id = (SELECT MAX(job_id) FROM procs_queue_steps 
WHERE name = 'prDataValidation_pr' and status = 'in_progress')
WHERE project_ID = ISNULL(@proj,project_ID)

It finishes by setting the job in progress like so:

UPDATE adm_validation_process
SET job_id = (SELECT MAX(job_id) FROM procs_queue_steps
WHERE name = 'prDataValidation_pr' and status = 'Complete')
WHERE project_ID = ISNULL(@Proj,project_ID)

The last step, however, sets it to the job ID of the **previous** job, since the current job isn't marked complete until this procedure exits. This leads to the Data Issues page showing the wrong date and time for completed data validations.

Since adm_validation_process only stores the job_id, I think it only needs to be set once, at the beginning of the procedure.

**Comment by cjardine-bsc** [comment]
#467
