### ISSUE TITLE
Lotek-D000739 missing detections from one antenna

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#501]
Receiver **Lotek-D000739** is missing detections on certain antennas only. Looking at detections from Project 227, we can see over the period of Nov 22-23 there were several detections on Antenna 1 according to the raw data, but these data are not present on the .motus sqlite file.
![proj227_recvDetections_byRecvAntenna](https://user-images.githubusercontent.com/35931796/59113412-51bd6600-891b-11e9-9b61-9d294f230cbf.png)

I took a closer look at the detections for tag 32440 (mfgID: 102) and tried to recreate what [find_tags ](https://github.com/MotusDev/Motus-TO-DO/issues/465) does with the code at the end of this post. ~~Unfortunately, the last plot reveals an issue with the dataset I was provided - the times were rounded to the nearest second, so I can't replicate find_tags until I get the original files. The following plots were made with the data rounded to the nearest second (not very useful...).~~ I used the original DTA file from the Lotek recevier and the sqlite downloaded thru R to create these plots.

---

**Plot 1**
Here I filtered out all detections where the burstSlop was greater than the maximum allowed slop, as defined by the parameters in find_tags. 
 - maxAllowedSlop = 10 + (1 * [#skipped bursts])
 -  slopDiff = maxAllowedSlop - abs(burstSlop)

![proj227_recvDetections_byRecvAntenna_2](https://user-images.githubusercontent.com/35931796/59113435-5b46ce00-891b-11e9-9f47-e3ccf214e1da.png)

**Plot 2**
In this plot  I also filtered out detections where the number of skipped bursts was greater than 20:
![proj227_recvDetections_byRecvAntenna_nSkipped](https://user-images.githubusercontent.com/35931796/59113446-626ddc00-891b-11e9-8ff7-a717d4c484c2.png)

---

Code:
```

library(motus)
library(tidyverse)
library(lubridate)

Sys.setenv(tz = "GMT")

dir <- '../Data/'

projID <- 227

sql <- tagme(projRecv = projID, new = T, update = T, forceMeta = T, dir = dir)

df <- sql %>% tbl('alltags') %>% collect() %>% as_tibble()

options(digits.secs = 4)

df.lotek <- read.csv(paste0(dir, 'Lotek-D000739_20181123_tab.DTA'), sep = '\t') %>% 
  mutate(ts = as.POSIXct(paste(Date, Time), format = "%m/%d/%y %H:%M:%OS", tz = 'GMT'),
         mfgID = as_factor(Tag.ID),
         source = 'Lotek',
         port = Antenna) %>%
  filter(!is.na(ts), !is.na(mfgID)) %>%
  select(ts, mfgID, port, source)

df %>%
  mutate(ts = as.POSIXct(ts, origin = '1970-01-01'),
         source = 'Motus')%>%
  filter(recv == 'Lotek-D000739',
         year(ts) == 2018,
         month(ts) == 11,
         day(ts) == 22 | date(ts) == 23) %>%
  select(ts, mfgID, port, source) %>%
  rbind(df.lotek) %>%
  mutate(port = paste('Antenna', port)) %>%
  ggplot(aes(ts, source, color = as_factor(port)))+
  geom_point()+
  facet_wrap(.~port)+
  theme(axis.text.x = element_text(angle = 90, vjust = 1))+
  labs(x = 'Time', y = 'Data Source', color = 'Antenna', title = 'Detections on Lotek-D000739 by data source')

# Tag 102
period <- 4.699699878692627


df.motus.lotek <- df %>%
  mutate(ts = as.POSIXct(ts, origin = '1970-01-01'),
         source = 'Motus') %>%
  filter(recv == 'Lotek-D000739',
         year(ts) == 2018,
         month(ts) == 11,
         day(ts) == 22 | date(ts) == 23) %>%
  select(ts, mfgID, port, source) %>% 
  rbind(df.lotek) %>%
  filter(mfgID == 102) %>%
  arrange(source, mfgID, port, ts) %>%  
  mutate(port = paste("Antenna ", port),
         tss.prev = ifelse(port == lag(port) & 
                             source == lag(source),
                           difftime(ts, lag(ts), units = 'secs'), 
                           NA),
         slop = ifelse((tss.prev %% period) > (0.5 * period), (tss.prev %% period) - period, tss.prev %% period),
         nSkipped = floor(tss.prev / period),
         maxAllowedSlop = (10 + (1 * nSkipped)) / 1000,
         slopDiff = maxAllowedSlop - abs(slop))

df.motus.lotek %>%  
  filter(tss.prev >= 0, slopDiff > 0) %>% 
  ggplot(aes(ts, slopDiff, group = source, color = nSkipped))+
  geom_point()+
  facet_grid(source~port)+
  theme(axis.text.x = element_text(angle = 90, vjust = 1))+
  scale_color_continuous(low = '#00FF00', high = '#FF0000')

df.motus.lotek %>%  
  filter(tss.prev >= 0, slopDiff > 0, nSkipped < 20) %>% 
  ggplot(aes(ts, slopDiff, group = source, color = slop))+
  geom_point()+
  facet_grid(source~port, scales = 'free_y')+
  theme(axis.text.x = element_text(angle = 90, vjust = 1))+
  scale_color_continuous(low = '#00FF00', high = '#FF0000')

```

**Comment by leberrigan** [comment]
Jeremy, could you reprocess the data from this receiver?

**Comment by Hussell** [comment]
Done, though it was last reprocessed 8 days ago, on May 31st.

**Comment by leberrigan** [comment]
Thanks Jeremy. Yeah, nothing changed by reprocessing data. I'm stumped at this point!
