### ISSUE TITLE
Duplicate Data Proj 132

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#504]
There's duplicate data in project 132, related to issue #398, #267, #236 

Everything is the same except hitID, runID, batchID. An example of a pair of duplicates:

hitID: 1223053214:, runID: 56956061, batchID: 367627
and
hitID: 998553885, runID: 49686425, batchID: 274240

also batchID's 367624 and 274237

**Comment by Hussell** [comment]
Batch 274240 is marked as deprecated, batch 367627 is not. Is the batchFilter column not included in the table?

**Comment by cjardine-bsc** [comment]
If you download the data before it is marked as deprecated it is not deleted from your .motus file when you do updates. if Zoe re-downloaded the file from scratch those duplicate batches would be excluded. 

I don't think we've had a discussion about this. I don't think we want to remove data from user's files, but we should mark the deprecated data in updates somehow. 

Right now we're not passing the batchFilter column through R. We could, or we could flag these records as duplicated using the runsFilter column. Probably a good discussion for our weekly meetings. 

p.s. Hi Zoe!

**Comment by cjardine-bsc** [comment]
*note to self* this same issue will need to be tackled with versioning.

**Comment by denislepage** [comment]
One possible way to handle this is to add a R function/API call to provide the full list of batches and the filter column, so the local database could be updated.

One issue is that we talked about deleting those batches from the server, which complicates slightly the process to provide missing batches to users (unless we kepts the batch record and only deleted the associated data, for instance).

We could also have a purge command that would delete the duplicate records from the local database, if the user wanted.

**Comment by zcrysler** [comment]
Ah that's my bad, I was working with old data and updated rather than re-downloaded it, sorry!

**Comment by adamdsmith** [comment]
Kicking the tires on an old thread here. What's the state of the art for purging deprecated batches from local databases without a fresh download? Thanks!

**Comment by leberrigan** [comment]
Sorry Adam, I'm closing this issue since it has been resolved. If this is still an issue for you, please open up an new topic - thanks!
