### ISSUE TITLE
plotData inefficient when number of detections by receiver is high

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#507]
After processing an upload motusServer draws charts showing detection times for each detected tag in the uploaded data. It draws one chart per deployment. However, the time to execute apparently depends on the total number of detections for the receiver, whether they're being displayed or not. This is particularly apparent for syncReceiver jobs, where a new upload is done each hour. Some examples: SG-5113BBBK2972 (MotusON, Old Cut), SG-5113BBBK2853 (MotusON, BSC HQ), SG-4414BBBK0737 (Helgoland, FG1_2018), and SG-5016BBBK1B68 (Wageningen University, St Maartensvlotbrug Huiberts), all of which have well over 1 million detections. Sometimes 50+ syncReceiver jobs will be waiting for one of these to complete.

For Old Cut, a test was done: terminating the old, long-running deployment and creating a new one. But the new deployment still takes just as long to plot, even though only a couple of tags have been detected.

handlePlotData.R - does setup and file output
makeReceiverPlot.R - does most of the work to create the plots
tagview.R - creates a horrific "Big Fat Join" view of tag detections

The problem is apparently that makeReceiverPlot begins with a call to tagview then adds all kinds of additional conditions to it. Somewhere in there, something massively inefficient happens. The solution may be to dig through and debug the generated query, or to create a custom query specifically for this job.

**Comment by denislepage** [comment]
It may be possible to add indexing to tables to improve the efficiency. That would likely require changing the sqlite database schema for new receivers, and adding indexes to all existing sqlite files (that can be scripted from R once we figure out the changes we want to make).

The first question we should ask though is whether there is enough value in keeping those plots, or whether they can be replaced by a functionality on the motus site.

I am not convinced it makes sense to redraw the plots every time new data come in, and a better solution may be to do away with them entirely on motusServer.

**Comment by Hussell** [comment]
Disabling plots for syncReceiver jobs might be OK, or just for specific receivers. Drawing the plots for manual uploads is important to users, and drawing plots for reruns substantially shortens the feedback loop for taking care of particular issues.

**Comment by Hussell** [comment]
New observation: using the 'top' command on Linux while plots are being generated reveals that the R processes are CPU-bound, not bottle-necked by memory or IO. So when I or someone else gets around to digging into this, try ignoring the query and looking at the filters and manipulations the R code is doing to the results of the query.

**Comment by denislepage** [comment]
Would limiting the query to only the most recent period be a short-term work-around?

**Comment by Hussell** [comment]
I've turned off plot generation for all receivers until we can figure out how to make it run fast enough to keep up with all the uploads and rerunning.

**Comment by Hussell** [comment]
There's now a prototype replacement on sandbox.

https://sandbox.motus.org/data/receiver/deployment/plot?id=4488 (random small example)
https://sandbox.motus.org/data/receiver/deployment/plot?id=5004 (deployment with no detections)

Examples which took hours to generate in times past now take ~30 seconds:
https://sandbox.motus.org/data/receiver/deployment/plot?id=2549 (MotusON, Old Cut)
https://sandbox.motus.org/data/receiver/deployment/plot?id=2146 (MotusON, BSC HQ)
https://sandbox.motus.org/data/receiver/deployment/plot?id=4532 (Helgoland, FG1_2018)
https://sandbox.motus.org/data/receiver/deployment/plot?id=4892  (Wageningen University, St Maartensvlotbrug Huiberts)

Things which have changed:

 * The new plots are being generated from the daily summary table, so there's a delay of about 20 minutes between the time the sgdata email notification arrives and the time the new data appears on these plots. Occasionally the delay will be many hours, when an upload or rerun with millions of detections happens and fills the bottlenecks.
 * The new plots are filtered, so there are inevitably going to be a few "Where are my detections?" conversations even after the daily summary table is updated.
 * Ambiguous tag detections aren't shown, since those aren't in the daily summary table either.
 * Exact detection times aren't plotted, because the **daily** summary table is being used. This shouldn't matter much, since one day on the old plot was only 7 pixels wide.
 * Tags are assigned arbitrary colors, where before each detection was colored by the antenna it was from. The daily summary table doesn't contain any info about which antennas a tag was detected on.
 * Tags are plotted in order of most recent detection, instead of by project and tag ID.
 * By default, only the 100 most recently detected tags are shown. Very few deployments are affected by this, but if necessary the number displayed and the first tag ID to display can be given as parameters to the plot generator.
 * Changes to the plots can be made, now. For example, I've duplicated the labels on the gradation marks to both sides of the plot, and labelled every day instead of just the months.

Testing along the way showed that for plots with ~1000 tags detected and millions of detections, generating directly from det_taghits_runs takes ~30-40 min, from det_taghits_daily ~5 min, and showing only 100 tags cuts the time down to ~30 seconds. The same plots on sgdata were taking 6 hours or more, for unknown reasons (too many possibilities to bother untangling). Most deployments have far less detections, and can now be generated in 10 seconds or less. My gut feeling is that there's still room for optimization in the queries of the GPS fixes, antenna activity, and reboot odometer, though giving diminishing returns. It might also help to optimize the drawing routines to do everything needed for each row at once, instead of drawing the the gridlines for all rows, then the labels for all rows, then the detections. It also might not make a noticeable difference.

Can generated .png images for terminated deployments somehow be cached until reruns are done? For active non-networked deployments until new uploads happen? For active networked deployments, where new data arrives every hour? The prototype as it is now generates the plots dynamically, on demand. That's simplest, but may be annoying since plot generation still takes a noticeable amount of time.

Currently these are only available to users registered with the project of the receiver, because I began development pulling data from detailed detection data. Now that it's all from the daily summary, it's simple to let anyone see almost the same plots through vwData_taghits_daily.

A French plot is now possible, unlike on sgdata, though I haven't begun that part yet.

**Comment by denislepage** [comment]
Looks great. Catherine or I should probably look at the queries for possible optimizations. I’d likely want to use NOLOCK options for most of this.

**Comment by StuMackenzie** [comment]
Thanks Jeremy - these look great.

**Comment by leberrigan** [comment]
Besides the antenna colours, which was useless anyways, this only looks better. Nice work!

**Comment by denislepage** [comment]
As an aside, on this plot, we can see possible issues with the boot number
https://sandbox.motus.org/data/receiver/deployment/plot/SG%2D2616BBBK1111-2017%20Loring%20BIWF.png?id=4488&n=100&firstTag=0

**Comment by StuMackenzie** [comment]
When can this go live?

**Comment by denislepage** [comment]
If you test on beta, I can publish to live in the next couple days.

**Comment by Hussell** [comment]
Ok, the receiver plots are on beta now, and can be viewed in French as well.
https://beta.motus.org/data/receiver/deployment/plot?id=4488&lang=fr

**Comment by Hussell** [comment]
The new plots have been deployed to the live/production server, and I've updated the emails sent out from sgdata to include a link to them.
