### ISSUE TITLE
update webcode and remove SG_ refereces

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#510]
The sg_ tables in motus_sandbox have officially been retired and renamed to "old". I've gone through and updated the database to reference the new tables prefixed det_ so all the procs and views should continue to return as expected. 

We'll need to check the java code to make sure there are no references in there to the sg_ tables. I'm sure there will be for the compute tracks code, but otherwise I'm hoping the number of fixes needed will be quite light. 

If you find any places where the DB returns an error feel free to flag them for me.

**Comment by denislepage** [comment]
Note that there are a couple sg_ tables that have remained in place, however, so we can’t do a wholesale replace.

At least the following tables are still in use:

sg_api_fields
sg_api_tokens
sg_uploads

We still have sg_versions, but I think it will switch to det_versions

sg_import_log will be gradually replaced by det_import_log, but let’s keep both for the moment.

The latter 2 tables are only used by the SGDataImport scripts, so I will handle that one.
