### ISSUE TITLE
new api entry for deprecated batches

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#511]
I created a couple new views that will be used to return the list of deprecated batches for the R client.

[vwR_Batches_for_all_deprecated]
[vwR_Batches_for_receiver_deprecated]
[vwR_Batches_for_tag_project_deprecated]

We should create new API entry points that return those:

batches_for_all_deprecated
batches_for_receiver_deprecated
batches_for_tag_project_deprecated

The list of API request parameters should be the same as the matching batches entry points, but the response really only need to return the batchID field. 

At the moment however, the view doesn't work for tag_projects (some of the necessary tables are currently empty for deprecated batches). We'll need to work on that. The view will no record until that's fixed, but we can test this on receivers for now.

**Comment by pmorrill** [comment]
I have added these entry points to the api: they should appear in today's deployment.

**Comment by pmorrill** [comment]
One question about deprecated batches response packages: should I be allowing pagination of the result set? Or can we return the entire set of deprecated batches to the R-client in **one** structure?

**Comment by denislepage** [comment]
I think I would go with 10000 rows per page. Many projects will be under that, or have a couple pages only.
