### ISSUE TITLE
R api_info needs to return the data version

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#512]
api_info is currently returning a 500 error, but we should add the following additional details: 

current_data_version: 2
supported_data_versions: e.g. [1,2]

These values probably can be stored as static objects in the SGDataAPI, and read at initialization.

select * from det_versions where available = 1

current_data_version should be the maximum value of the versions available. Not sure if it makes a difference whether the API only returns the list or also includes the max. value. Easy enough to figure out in R also.

This maximum should also be used as the default version whenever the version parameter is missing.

E.g.

Long version = ctx.getParamLong("version",current_data_version);

**Comment by pmorrill** [comment]
I must be misunderstanding: I have tested the sgdata api_info function on sandbox, beta, and live servers, and I always get back the 'maxRows' field. I don't see a server 500 error. For example:

 https://www.motus.org/api/sgdata/api_info

Note that all returns from the sgdata api encode as bzip compressed streams. This is probably over-kill in the case of the api_info call!

EG: returns {"maxRows":10000} once uncompressed.

**Comment by denislepage** [comment]
Yup. All works.

I am not sure what I did earlier.

¯\_(ツ)_/¯
