### ISSUE TITLE
"Fees related to this project will be covered by"

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#515]
New dropdown on edit-project page:
https://sandbox.motus.org/data/project/edit?id=137

Populated from table lk_project_fees, stored in projects.fee_id.

**Comment by Hussell** [comment]
lk_project_fees in the live database is empty, so the box on the project page is empty.

**Comment by cjardine-bsc** [comment]
Okay, I've populated that. We have two that need to be translated. Do we have any other translation needs?

**Comment by StuMackenzie** [comment]
I've had some recent translation work handled separately, so probably OK to proceed with whatever you have.
