### ISSUE TITLE
Lotek SRX-600 Failed Upload - No Receiver Serial No.

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#518]
Data from a SRX-600 isn't getting processed, produces the following error:

> _File uploaded: 2934_2019-07-11T21-47-51.827_Lotek-6535_DTA_2019-07-11.zip
> Error: Error in lockSymbol(serno): invalid symbol NA_

User says response email states there is no serial number included in the file.

**Project**: 67 
**Job ID**: [496905](https://sgdata.motus.org/status?jobID=496905)
**Receiver**: [3261](https://motus.org/data/receivers/edit?projectID=67&id=3261)
**Serial No.**: Lotek-6535
**Files**: [Proj-67_Lotek-6535.zip](https://github.com/MotusDev/Motus-TO-DO/files/3387039/Proj-67_Lotek-6535.zip)

I'm waiting to hear back from them to see if there's an older file that was successful in the past.

**Comment by denislepage** [comment]
There is indeed something wrong with the DTA file name included in the archive for the 2 most recent uploads by this user (they appear to be the same file with different names), in that it doesn’t follow the expected pattern produced by sensor gnome. It looks like a name that was given by the user.

The serial number is read from file name itself (within the archive, not the name of the archive itself). We may be able to rename it to be readable, but that’s not ideal. You should get back to the user and see if they can resolve this.

**Comment by leberrigan** [comment]
I haven't had any issues when I have modified file names in the past and I don't believe the user modified the document in any way. 

The first few lines for the above file starts like this:

> Environment History:
> changed: 43637 08:36:11
> Site number 001
> Codeset = Lotek4

All the other DTA files I have are from SRX-800 and they start like this:

> SRX800 / 800D Information:
> Environment History:
> changed: 04/05/18  17:46:38
> 
> Master Firmware: Version 9.10.14
> Slave Firmware:  Version 20.0
> **Receiver S/N:    D000597**

**Comment by denislepage** [comment]
Yes, sorry. I was strictly thinking of SG files, not DTA.

I can confirm that this particular file doesn’t have a serial number inside. The code could handle that more gracefully, but something is wrong with the way the receiver appears set up.

Also, there is something weird with the dates and times in the data portion, which is potentially a fatal problem. Date are represented by integers, but more importantly we only have integer second precision on the time.  I don’t think this data can be processed without the millisecond precision. It may still be useable by the user, but we likely won’t be able to feed it through tag-finder.

********************************* Data Segment *********************************

ID Only Records:

Date   Time    Channel Tag ID  Antenna   Power
43637 08:36:23        0    999      AH0      61
43637 08:36:29        0     14      AH0     255
43637 08:36:31        0    999      AH0      95
43637 08:36:36        0     14      AH0     254
43637 08:36:44        0     14      AH0     254
43637 08:36:52        0     14      AH0     255

**Comment by leberrigan** [comment]
[Resolved.](https://sgdata.motus.org/status?jobID=954195)

Turns out they didn't download the file correctly. Unfortunately, I'm not familiar enough with Lotek SRX receivers so I can't say exactly what happened, but they got in touch with Lotek and was givwn instructions on how to make a DTA file using the SRX software. 

That's all I know!
