### ISSUE TITLE
Lotek Receiver GPS Rollover Results in Incorrect Dates

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#519]
A user from Project 152 has told me that his receiver ([Lotek-0000473](https://sgdata.motus.org/status?jobID=594160))  was affected by the GPS rollover event. This receiver has detections for August 23-26, 1999. 

Unfortunately, the deployment for this receiver starts in August 2017, but the only data that iexists is from March 27, 2019 onward. This imakes it a bit unclear when these hits actually occurred so I have asked the user to help us sort that out.

As a refresher, this is the information provided to us by Lotek about the rollover event:

> After April 7th, 2019, some of the GPS modules used in SRX800 receivers will be affected by a GPS rollover event.  This rollover is an inevitable event in the life of the GPS module, which has a cycle period of 1024 weeks. Upon reaching the end of this period, the module resets the week number back to zero and starts counting up again. Week zero was in August 1999.
>  
> Downloading the new SRX HOST software and updating the firmware will counter the effects the rollover event has on logging incorrect timestamps. Any incorrectly logged time stamps can be corrected simply by converting any downloaded date .bin files collected after this time using the new SRX HOST.
>

**Comment by Hussell** [comment]
Same problems as #533: the tag finder filters these out, so they never reach our database.
