### ISSUE TITLE
ctt file name in motusServer

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#521]
I modified the files handleSGFiles.R and sgFilenameRegex.R in motusServer to allow the use of CTT serial numbers. 

My changes should be double-checked and deployed on the sg server. 

The following 3 jobs failed earlier today and could be tried again once the package has been updated.

Those 2-3 receivers are not already in Motus, and we should confirm that they are registered during the data processing, and that data is flowing in.

971448    View log | uploadFile | 2019-07-15   07:12:55 | 2019-07-15   07:13:01 | Paul Morrill | Complete | File   name:   688_2019-07-15T11-12-55.720_DFB_SG_Pi3_Test-CTT-867459049270838-20190712.zip   Upload ID: 6708

971436    View log | uploadFile | 2019-07-15   07:12:05 | 2019-07-15   07:12:11 | Paul Morrill | Complete | File   name:   688_2019-07-15T11-12-05.781_DFB_SG_Pi3_Test-CTT-867459049265267-20190712.zip   Upload ID: 6707

971406    View log | uploadFile | 2019-07-15   07:09:09 | 2019-07-15   07:09:14 | Paul Morrill | Complete | File   name: 688_2019-07-15T11-09-08.659_changeMe-CTT-867459049265267-20190712.zip   Upload ID: 6706

**Comment by Hussell** [comment]
I double-checked your changes and found a couple more places where serial number regexes needed to be changed. I've made those changes, checked in the code, deployed to sgdata, and rerun the upload jobs. The new upload job IDs are 986971, 986990, and 987009. The first two appear to have succeeded, but the third failed to export the data to the main server due to the receiver already being registered. I'm not sure how to deal with that.

**Comment by denislepage** [comment]
CTT-867459049265267 was registered today. I don't know if the error happened because the motusServer code doesn't deal with registering twice the same new receiver before it refreshes its metadata, or because there is a missing exception that we need to deal with due to the different serial number pattern. We will need to examine the part of the code that submits the registration. One possible solution is to modify our code to return a device ID when it already exists, but the motusServer part may not be currently able to handle that without some changes. I am inclined to think that this is related to the ctt pattern, but we may just not have noticed that error before for xy reason.

**Comment by denislepage** [comment]
OK, I think I sorted this out.

The receiver registration error here comes from the fact that the same receiver was already registered by a different process (CTT data import) and with a different key than the one assigned independently by tag finder.

I changed the registration proc so it assigns the key by tag finder when one doesn’t already exist and the receiver type is SENSORSTATION or the serial number matches CTT-[0-9]{15}.

I don’t think we’ll ever need to rely on the sg-assigned secret key for CTT receivers for other things than tag finder (we barely do regardless), but if we do, we’ll have to ensure that we have a process to generate such keys and/or share them with SG.

Note that I am also converting the SENSORGNOME type to SENSORSTATION when a CTT prefix is used. I am not sure if we feed that information back to tag finder, and whether it relies on it for anything, but there will be a mismatch between our data and tag finder for that field.

The failed batch should hopefully go through and register the receiver correctly this time (you can check also that the key, currently set to 0, gets assigned).

**Comment by Hussell** [comment]
I'm getting an "invalid_receiver_typ" [sic] error when trying to register CTT-867459049270838. Looking at prInsertSensorsHashKeys, I don't see why that's happening. I've tried a receiverType of both "SENSORGNOME" and "SENSORSTATION".

**Comment by denislepage** [comment]
Perhaps the type is not in the lookup table?

I'll check.

**Comment by denislepage** [comment]
How are you trying to “register” the receiver? By sending the file for processing you mean? Where do you see that error? In the SG logs?

This error doesn’t happen in our code and is likely coming from tagFinder. I trying grepping the error in motus server and find_tags, but I am not finding it either.

Can you confirm the spelling (with underscores, not hyphens): invalid_receiver_typ

I anticipated we might get issues if the code was doing anything with the receiver type. We should have a look at that code, and treat SENSORSTATION as an equivalent of SENSORGNOME there, or change the API or database view to make the conversion before passing the data back to tagFinder, whichever is easiest.

**Comment by Hussell** [comment]
I introduced an additional spelling error in my comment, it should have been "invalid-receiver-typ" [sic], with hyphens, not underscores. The missing 'e' at the end is what [sic] refers to. It's in prInsertSensorsHashKeys, which is called by motus-api's ReceiversAPI.java, which is called by sgdata's motusRegisterReceiver.R. The missing 'e' is due to the return value being varchar(20), which is too short to contain that return value.

**Comment by denislepage** [comment]
Still haven’t found the error, but there are at least a few places where I can find “SENSORGNOME” in motusServer. A simpler solution would be to modify our api and treat all CTT receivers as SENSORGNOME for that purpose, but I can also see at least once place where the prefix is used to determine the receiver type, which will need some tweaking:

refreshMotusMetaDBCache.R

recv$receiverType = ifelse(grepl("^SG-", recv$serno, perl=TRUE), "SENSORGNOME", "LOTEK")

If we are keeping only SENSORGNOME, we could do this:

recv$receiverType = ifelse(grepl("^(SG|CTT)-", recv$serno, perl=TRUE), "SENSORGNOME", "LOTEK")

There may be other places to fix.

Let’s chat about this on today’s call.

**Comment by Hussell** [comment]
I've already fixed that. Pull!

**Comment by denislepage** [comment]
I extended the response code to 32 characters. I don’t know if anything was made to accommodate the truncated response that needs to be undone. I didn’t find anything in the code referring specifically to that error, but it could be handled from a database (in motusServer or our code).

We may be able to find out what request was sent by looking at the logs.

**Comment by Hussell** [comment]
Job successful. CTT-867459049270838 has been registered, and the data "exported" to the MariaDB on sgdata. Also, most (hopefully all) code on sgdata dealing with SG- vs. Lotek- prefixes has been modified to behave sensibly when a CTT- prefix is encountered. I think testing can resume.
