### ISSUE TITLE
Project 197 Receiver Rerun

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#522]
User uploaded receiver data before updating tag metadata and want to see their detections asap. Can the following deployments be rerun?
5347
5345
5346

**Comment by Hussell** [comment]
Done, but no new detections have shown up. It looks like this morning they edited a lot of tag deployments and uploaded data for each of these receivers, so this request may have been premature. I'll try rerunning again on Monday.

**Comment by Hussell** [comment]
Ok, done, and new detections appeared. Next time this happens I'll check that the new tag deployment metadata has actually made it to sgdata before rerunning.
