### ISSUE TITLE
CTT Node metadata Mgmt tools needed

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#523]
CTT allows users to deploy "nodes" around their base station, which have a single whip antenna and act as relay for tag signals, with one the goals being the ability to offer greater accuracy in position.

My understanding is that at the moment, nodes are not equipped with GPS receivers, so we need to allow users to track the associated metadata, primarily the GPS position of each node receiver over time. 

I would strongly advocate NOT to ask users to create new receiver deployments for each change in node configuration, but rather to track the position with start and end time for each node (node deployments within a receiver deployment, if you will). 

It's hard to predict exactly how they will get used, but I suspect nodes may be more versatile than antennae, and that users may be more inclined to move them regularly, creating a challenge in how this information is entered and managed by users. 

We'll need to amend the receiver metadata management page to add a new table of node deployments.

- I created a new table called sensor_nodes:

id: identity field
deploy_id: id of the sensor_deployment record to which each node is attached.
nodeId: I've allowed up to 8 alpha characters (so far, only 3 chars used, e.g. 3f4).
latitude/longitude
dt_start/dt_end: datetimeoffset
copy_dates: whether node start/end times are a match for the whole deployment (bit field).

We should allow the following user options within the receiver deployment page:

- I would add a new tab called "Nodes" (besides Antennas and Advanced Antenna Properties) with a table of node deployments, with the fields above (ID, nodeId, latitude, longitude, dt_start, dt_end).

- Similar to antennae, there could be a few empty rows for new nodes. 

- Also like for antennae (perhaps the same map for both purposes), we would have a map where the user can see the antenna directions and the positions of all nodes relevant to that deployment

- If possible, users could click on the map to add new node records, though there should be a toggle rather than the default action linked to a map click. The rest of the details (nodeId, dates) would be entered when they go back to the table.

- The copy_dates field controls whether the user can edit dates. It should be checked by default. Perhaps we can copy the deployment dates when the box is first unchecked, and clear the start/end dates when the box is checked again. 

- Start and end dates fr nodes should be constrained within those of the deployment when manually entered, and should not allow to overlap with another record that has the same deployment and the same nodeID. NodeId's are almost certainly NOT globally unique, so the same nodeId can be shared among different users or environments. 

Let's discuss this Thursday

**Comment by denislepage** [comment]
Forgot to specify that this option should only be available for CTT receivers.

**Comment by StuMackenzie** [comment]
Believe this to all be in order.
