### ISSUE TITLE
changes gps table to use gpsID as a primary key in R

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#529]
This is for sandbox only at this point.

I have included the field called gpsID in the R views vwR_gps_for_tag_project and vwR_gps_for_receiver. 

We should add this field to the gps table in R, replace the primary key to rely on this new field and use it to loop gps records instead of the batchID + ts. Looping on ts can be problematic due to imprecision of the float values. I ran into a case where the loop was running an infinite loop due to this problem.

I tried to update the sample r table sample_r_gps_for_tag_project to include the gpsID from det_gps, but most records were not present because they have been replaced by new batches, so only a small portion were updated by linking with batchID and ts. I was able to update them by comparing ts, lat and lon instead of batchID but that still left a few records that I could not match (about 66,.000)

Catherine, we will need to fix the sample data table before we can make this change. One option would be to remove gps records that could not be matched to gpsID's. Those represent less than 10% of the total sample dataset. As to why those records haven't been replaced by active batches is a puzzle at this point.

**Comment by denislepage** [comment]
I put in a quick fix for now in API sandbox, waiting to be deployed.

This I think will ensure that if the float is slightly smaller than the original ts due to imprecision, that it will round it to the nearest 1/10000th.

WHERE a.ts > round(?, 4) 

Relying on the gpsID is a safer option. I'm making changes in the API now so we can support both types of parameters (ts and gpsID). If we entirely remove ts, then older packages won't work, so I would wait a little bit at least to stop supporting that. looping on gpsID should be supported in sandbox tomorrow.

**Comment by denislepage** [comment]
Actually, the changes are now published to sandbox. Adding rounding in the R package is probably not necessary now. We can rather plan to switch to using gpsID for looping.

I can't think of or find other places where we loop using ts, but we'll have to fix those as well if there are.

**Comment by cjardine-bsc** [comment]
The only other place I can think of where we compare by ts is prSGBatches_filters_ts but I think that one is safe enough. 

As for the sample tables. The fact that some of those GPS fixes have disappeared seems reminiscent of the missing gps records we found in the comparison we did between data in sg_ tables and det_ tables.  I did a little poking around but don't know what the cause might be, perhaps a tagfinder fix applied to subsequent batches. Given it's sample data I don't see an issue with removing those records from the sample table, but I also don't think the gpsIDs for the sample data need to match the gpsIDs for the real data (the batchIDs, hitIDs, runIDs wont) so we can probably just keep those old records and make the gpsID field fro the sample table an auto-increment. Unless you're considering updating all the key fields for the sample data? *wrinkles nose*

**Comment by denislepage** [comment]
Let’s not touch the sample data, as much as possible.

**Comment by cjardine-bsc** [comment]
Cool. In that case can we just use an auto-increment gpsID for sample data. Permission to implement?

**Comment by denislepage** [comment]
Granted. ☺ Beam me up Scotty.

**Comment by cjardine-bsc** [comment]
okay, done in sb and live and PK redefined. Steffi can now work on the change to R.

**Comment by steffilazerte** [comment]
This is currently implemented in v3 (sandbox)
