### ISSUE TITLE
Can't enter an end date for new receiver deployments

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#53]
You have to enter a start date, click "create deployment", then enter an end date.

**Comment by pmorrill** [comment]
I'll take a look this AM. I suspect it is by design (start date has to be saved before the end date can be entered). It is the same with existing (pending) deployments: you can't enter both start date and end date at the same time.

**Comment by pmorrill** [comment]
With changes made to how we calculate 'status' of a deployment, I should be able to make it possible to enter both start and end date at the same time. But we'll have to live with the current restriction (a start date must be saved before an end date can be entered) for the moment.

**Comment by pmorrill** [comment]
As of the next beta, you will be able to enter both start and end dates for recvs at the same time, when creating a new deployment, or updating a pending deployment.
