### ISSUE TITLE
Need support for multiple concurrent R-client sessions for a user

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#530]
It seems that when I use R in 2 distinct sessions, creating a new token deprecates the old one. We should change that behavior so users are allowed to have multiple active tokens. I am not sure yet if this is a problem in the base Java token classes, or the API.

Also, an enhancement for R would be to ask again for a login when a token becomes deprecated.  Right now, I get an error "Authentication token was absent, invalid or expired", which will likely be cryptic to users. We should probably add a more friendly note to users indicating that their session has expired and prompt them to log in again.

This won't be as much a problem if we allow concurrent tokens, but people may leave their R session open and eventually time out.

**Comment by pmorrill** [comment]
When we set this up, we decided to only allow one session token at a time. (Unlike in the NatureCounts API where we had to write specific code to get around that and allow multiple active sessions at once)

I will take a look at how we did it in NC and what needs to change in Motus to make that happen. However, there was a reason why you wanted to go with one session at a time..... I do not recall what it was at the moment.

**Comment by denislepage** [comment]
Right. I’m sure there was a reason, but we may need to rethink that. I am not sure how common it will be for users to have parallel sessions, but I guess some people may share their passwords rather than setup new user accounts, and they would run into this issue. Maybe part of the issue is we didn’t want to have too many keys floating around, but in insight, there were probably better ways to deal with this.

**Comment by steffilazerte** [comment]
The error "Authentication failed : Authentication token was absent, invalid or expired." is returned by the API. The most I could do in the R package is make the assumption that if you get this error in the middle of a download, then it's probably due to having more than one session on the go and offer that as a potentially explanation, but it won't always be correct.

I think it would be more elegant to make the error code more informative on the server side, is that possible?

**Comment by pmorrill** [comment]
We could split these cases out and try fr unique error codes for a) missing token; b) invalid token. I am not sure if we can track tokens that are expired or not. Well, we can do anything but I am thinking of the difficulty level. I can't recall how long a lifespan we grant them so I am not sure how likely they will expire while in use. Would it be helpful to give you an expiry datetime when a token is created? You could keep track of tokens nearing their life-span in the client?

However, allowing multiple tokens at once (per single user) makes sense to me. I have it on my list to look at what has to be done to achieve that.

**Comment by steffilazerte** [comment]
If we're going to allow multiple tokens on the server, then I would do that and not worry about this use case too much.

If I remember correctly, the tokens don't expire quickly, so it should only happen if a user has a really really really long R session, and hopefully if something goes wrong they think to just try restarting R :) which would fix the problem!

**Comment by denislepage** [comment]
Regarding tokens, I think most of the restrictions we created are defined in org.bsc.Tools, but I don’t remember specifically where the one about not having multiple tokens is defined. It the token used for the R client a session token

I do agree that we should remove that restriction and allow multiple tokens. There are a couple approaches possible, but perhaps the simplest is this:

We could have tokens of shorter duration that get renewed periodically when they get used. Perhaps not at every call, but for example once they reach a certain percentage of their total lifespan. If you set the token for 1 week lifespan, we could extend the life of the token whenever it gets used an has a remaining life of less than 6 days. That way, tokens won’t be renewed more than once a day. There is a function called Tools.extendUserToken available for that.

We’d also want to set up a task to clean expired token, but that’d be easy to do through the procs queue. That said, deleting expired tokens means that the error message will revert back to token not found rather than token expired.

**Comment by pmorrill** [comment]
I have adapted the sg data servlet to allow multiple sessions for a single user, ad also to extend token life as they get used. The key elements:

1. lifespan is set to 7 days when a token is first generated
2. a subsequent token generation event by the same user will NOT create a new token, but will return the existing one
3. if the token exists and is within 2 days of its expiry, the expiry will be extended out to be 7 days again (the generate function is now globally synchronized to make this update safer)

Note that the token generation used here is not the Tools version. I would like to switch over to using the Tools version, but let's make that a separate issue.

Note also that we only extend lifespan on the 'generate_token' event, not on subsequent token use events (eg: listing batches, etc). This is consistent with the initial thinking, which is that people would be re-authenticating once per session. In fact, if you leave your session active over night, you will be able to proceed with tagme activities using the previous days token (even if you went home and ran a few more tagme's on a different computer), which seems ok.

**Comment by denislepage** [comment]
Sounds good. My only concern though is that if someone has a token and leaves their computer open for a week, and initiate a script towards the end of the week, their script may fail. Granted, there isn’t as much server back-and-forth in Motus then there could be in NatureCounts (e.g. loop species and sites and run analysis on each step). In a case like that, I can easily see long-running scripts extending more than a week.

Is it possible to compare the token expiry date every time it is being used for authentication instead on only during creation? I think that would be safer, and probably doesn’t add much overhead (tokens would still be updated only every few days at most).

**Comment by pmorrill** [comment]
We do check for token expiry on every query made, but we do not extend it on those queries, even if it is nearing expiry (extension is only happening when a new token is generated).

You also want it to be extended during general querying, in the even that it is nearing expiry. (I don't have much sympathy for people who leave session open that long! They are putting far too much trust in software!)....

**Comment by pmorrill** [comment]
anyway - I spoke too soon, as these changes are not going to make it into git today, given added time to extend lifespans on all queries.

**Comment by pmorrill** [comment]
I have added the code to beta9 and master, to allow multiple sessions per user, and also to extend token lifespan when it nears expiry (2 days from expiry).

This needs to be tested with the R-client, presumably against the beta server.

**Comment by steffilazerte** [comment]
Superficial testing confirms that this works in R!

**Comment by steffilazerte** [comment]
I just tested again with the master branch (`motus` package accessing the master API) and this works fine for me. As in I'm able to simultaneously download two different receivers with the same credentials in two different R sessions.

If no one else has any problems, I'll close this issue as solved!
