### ISSUE TITLE
Registration Failure due to duplicate tags? Project 213

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#532]
Project 213 attempted to register 20 tags, but only 1 of them appeared to work because they 'already exist'.

I don't have a copy of the original summary email, but it returned the error: Query to motus server to register tag 201:25.1 failed with this error: registration-failed: Tag registration failed - tag-exists.

It looks like they were able to register number 200.

Model: NTQB2-3-2
Burst: 25.1s
IDs: 201-219
Est Life: 339D
Users: University of Montana/MPG Ranch
Purchased: July 2019

**Comment by Hussell** [comment]
The project has another set of tags with the same mfg_id and date_bin, but different model (NTQB2-4-2S) and period. There's a check in prAPIImportTagsTransfer which prevents tags with the same project, mfg_id, and date_bin from being registered.

Possibly add to the check that the absolute difference between the two tags' periods can't be within a certain threshold? I'm uncertain how sensitive the tag finder is to differences in period.

**Comment by StuMackenzie** [comment]
Are you able to change that or is it a Catherineism?

**Comment by Hussell** [comment]
Catherinism. (I think the 'e' drops off because it's silent?)

**Comment by denislepage** [comment]
Actually the error seen doesn’t relate to the burst interval. Tags also have to be unique within a project for a mfgID and dateBin.

The error links to this validation in prAPIImportTagsTransfer:

                SELECT @tag_id = a.id from tags a inner join api_import_tags b
                on a.mfg_id = b.mfgID and a.project_id = b.projectID  and a.date_bin = b.dateBin

The tags already registered have a different burst interval from the new ones.  I think this is a case where the user is expected to add a suffix to the mfgID (e.g. 220.1, 221.1, 222.1), but I am fuzzy on the details, or can’t remember why tag finder required that, but that should be an easy work-around.

I don’t know that we ever check for conflicting tags across projects during registration (same dateBin and burst interval), expect perhaps in the notification center, but we should confirm. Lotek in theory issues tags with 0.1 second of precision on the BI (so far, we have been discussing going to 0.01 seconds a while back), but in practice, it’s not exactly that precise. so you can likely have 2 different tags that are validly only say 0.09 seconds away from each other. A safe distance is probably 0.05 seconds, but I see that we use 0.01 in the notification center validations (e.g. 2 tags with a period within less than 0.01 seconds are considered the same).

**Comment by Hussell** [comment]
Right. So, Stu, advise project 213 to add suffixes to the tag numbers, e.g. 201 -> 201.1, then re-upload them.

If I remember right, some people write these suffixes on the physical tag, to help keep them differentiated for the people in the field doing data entry.

**Comment by cjardine-bsc** [comment]
Conflicting tags (same mfg_id and BI) are not checked upon registration. Just in the notification centre. 

If the duplicates are real physical tags (and not re-registrations under a new model number) than yes, have them add the suffix and re-upload.

**Comment by denislepage** [comment]
Perhaps our notification for duplicates within a project and the need to add the prefix should be more explicit.

**Comment by StuMackenzie** [comment]
This has long passed and I'm not sure if I followed up, but I assume there was been some resolution? There are no tags in their project with .1 suffix.

**Comment by denislepage** [comment]
I have been wondering recently if that’s even a requirement that we need to enforce. I think it’s still useful to ask people to add that .1 for duplicates, so they don’t mix tags, but I don’t think that having duplicates (same project, mfg and dateBin) has any impact on the database processing per se. I think John had originally set up things on his end to rely on this as a primary key, but we never did.

Unintended consequences being what they are, I have been a bit hesitant to change that, but I am pretty sure it serves no purpose other than tag handling on the user end, and in some data visualizations if you are relying on the mfgID rather than the tagID.

**Comment by cjardine-bsc** [comment]
Just a note for the new Lotek registration, we'll be checking if there is an active tag for the same mfg_id and period in our DB and returning an error (with a 30 day grace period for soon to be released tags).
