### ISSUE TITLE
Endless loop retrieving activity records

### ISSUE THREAD

**Issue by adamdsmith** [MotusDev/Motus-TO-DO#534]
This attempt to download receiver data proceeds fine until it gets to retrieving activity records for batchID 273907:

```
> endless_loop <- tagme(projRecv = "SG-1215BBBK1769", new = TRUE, forceMeta = TRUE)

batchID   273907 (#     1 of     31): got     10 activity records
batchID   273907 (#     1 of     31): got      2 activity records
batchID   273907 (#     1 of     31): got      2 activity records
batchID   273907 (#     1 of     31): got      2 activity records
batchID   273907 (#     1 of     31): got      2 activity records
batchID   273907 (#     1 of     31): got      2 activity records
batchID   273907 (#     1 of     31): got      2 activity records
batchID   273907 (#     1 of     31): got      2 activity records
batchID   273907 (#     1 of     31): got      2 activity records
batchID   273907 (#     1 of     31): got      2 activity records
batchID   273907 (#     1 of     31): got      2 activity records
batchID   273907 (#     1 of     31): got      2 activity records
batchID   273907 (#     1 of     31): got      2 activity records
batchID   273907 (#     1 of     31): got      2 activity records
... repeat ad infinitum
```

**Comment by denislepage** [comment]
I had the same a couple days ago with gps. In my case it was due to imprecision of the float value. ts was rounded down very slightly, grabbing the next same record at every loop.

I asked Steffi to stop repying on ts to loop on how (we now also have a gpsID field).

I suspect the same applies to activity.

If so, a workaround for now is to increment the last ts value very slightly (e.g. +0.0001 or +0.001). We'll work on a better fix.

**Comment by denislepage** [comment]
Activity is not being retrieved using ts, but hourBin, so the issue sounds different. We'll look into it.

**Comment by denislepage** [comment]
Ah, some earlier version of the R package on the staging had an issue with the field name (hourbin vs. hourBin). Make sure that your motus package is up-to-date (presuming you are using staging branch). You can also manually fix an existing motus file by renaming the field to hourBin.

```
remove.packages(c("motusClient"))
install.packages("remotes")               ## if you haven't already done this
remotes::install_github("motusWTS/motus@staging")   ## the development version
```

**Comment by steffilazerte** [comment]
Ah yes, I didn't add the name change to the update so if this is a SQLite file that had an earlier version of the activity, you'll either have to remove the activity table or rename `hourbin` to `hourBin`.

**Comment by adamdsmith** [comment]
Thanks. Seems to run without issue now.

**Comment by denislepage** [comment]
Cool. Closing this issue then.
