### ISSUE TITLE
list deployments with landowners

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#54]
I noticed you can only delete landowners that don't have a deployment associated with them.  This is fine, but I wanted to see what deployment was associated with a certain landowner to do some tidying up (duplicate landowners), but clicking on the landowner does not show you what deployments are associated with it.  There used to be a list at the bottom of a landowner of the deployment name and ID which was really useful, can it be added again?

**Comment by pmorrill** [comment]
I'm sure it can be added back in, yes. I guess that we want to list the sites, and also the deployments associated with those sites (landowners are no longer directly linked to deployments).

**Comment by zcrysler** [comment]
Right, I forgot it's by sites, so a list of sites and deployments would be great

**Comment by pmorrill** [comment]
In the sandbox (and next beta release) you will find enhanced site and landowner mgmt tools, which include active deployments listings, and hyperlinks to visit those deployments directly.
