### ISSUE TITLE
CANARIE 3 Enhancements

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#543]
-  User Interface enhancements
- SG support and upgrades
- integration of motus.org with sensorgnome and CTT live feeds (Eg. view station status - link to SG status page, or CTT status page)
- Map of 'online' receiver stations and link to real-time and most recent data from motus.org., not a subsite
- streamline registration tables - eg. fields to enter for antenna. Move all normally unpopulated fields such as 'angle' and 'polarization' to 'advanced' to make it cleaner.
- streamlining of station tag reports - report on individuals detected, not on individuals detected/day

See also:

https://github.com/MotusDev/Motus-TO-DO/issues/396

- ability to filter map by scale of when receivers were last checked, etc. 'view table' function 

- Public Education/Outreach portal. Broader application and refinement of https://beta.motus.org/education/school/ 

Dashboard:

Working, or coordinate with Oceans Tracking Network?

Project Planning and Development tools: 
- collaboratives and collaborator lists

- map of regional coordination hubs (A map is a great idea, but we might want to put more thought into how that might be done. I think a choropleth will work best – something like what they’ve got on eBird but not as annoying to navigate. https://leafletjs.com/examples/choropleth/)

- project planning/site planning tools - see Western working group tools

**Comment by StuMackenzie** [comment]
Improve mobile functionality!

**Comment by StuMackenzie** [comment]
Website functionality on mobile devices.

**Comment by jsayers-bsc** [comment]
https://github.com/MotusDev/Motus-TO-DO/issues/698

**Comment by jsayers-bsc** [comment]
Improvements to Data Issues page

https://github.com/MotusDev/Motus-TO-DO/issues/738

**Comment by StuMackenzie** [comment]
For Reference. This is not doctrine, just a guide:

**Enhancements to SensorGnome software** 

| 1 | Update and   standardize computer hardware and host versions (to current Debian)
  | 2 | Automate building and testing of software release (e.g. using   Docker)
  | 3 | Automated configuration and deployment of software for users
  | 4 | Update communication protocols between receiver and   sensorgnome.org (replace reverse SSH tunneling with a VPN)
  | 5 | Add monitoring software to report receiver metrics (load   average, RAM usage, storage usage, GPS status, boot and shutdown events,   etc.)
  | 6 | Update   user documentation and redesign  the   sensorgnome Wiki.

**Enhancements to sensorgnome.org** 

| 1 | Create new user dashboards   reporting the sensor metrics.
  | 2 | Integrate new dashboards (e.g. Graphana) with   existing tools
  | 3 | Add VPN support.
  | 4 | Adjust communication and data formats to Motus server.
  
**Enhancements to tag finder and motusServer** 

| 1 | Modify motusServer to allow   adjusting for timestamp errors, GPS rollover issues, boot number resets
  | 2 | Improve database cleanup procedures and   optimization
  | 3 | Automate receiver data reprocessing schedule
  | 4 | Address memory overflow issues

**Enhancements to Motus Research Web Platform** 

| 1 | Modify site style sheets (e.g.   enhanced mobile support)
  | 2 | Updated site navigation and organization of   the  management pages
  | 3 | New project dashboard (top level project metrics   allowing further drilldown to recivers and tags)
  | 4 | New tag dashboard (information about a specific   tag, including detection summaries and deployments)
  | 5 | New receiver dashboard (information about a   specific receiver, including detection summaries and deployments)
  | 6 | Modify platform to support new station activity   metrics reported by sensorgnome and CTT and making those available to users
  | 7 | Project planning and coordination toolkit to allow   for mapping of stations at various stages to facilitate greater coordination   and communication between research teams.
  | 8 | Update documentation of all website instructions   and manuals.


**Development of new API functionalities** 

| 1 | New API entry points (e.g. track   data, station near me, summaries of recent detections at a receiver, etc.)
  | 2 | Integration of species tracks into NatureCounts   species account pages.
  | 3 | Resolve access to third party data for public   projects
  | 4 | List of public projects and searchable queries   (e.g. list of projects for a given species)

**Enhancements to motus R package** 

| 1 | Support for new sensorgnome fields
| 2 | New functions to search and download public   projects
| 3 | Integration of advanced movement modelling code and   documentation - instructions for use and preparation of data.

**Modification of CANARIE Research Software Registry** 

| 1 | Updated registry API
