### ISSUE TITLE
New antenna types to add - CTT accommodation

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#549]
1) 7 element Yagi - Mobile Mark, Y3347D-B. UHF, 7 element, 10 dBd gain - Heavy Duty

There will likely be more...

**Comment by StuMackenzie** [comment]
"2. 6 element Yagi - Lair YS4306" | 430-450 MHz, 6 element, 12 dBi, Aluminum Yagi with Fixed N-Female Connector

I don't know how crazy we want to get with this - seems like we might be going down a rabbit hole.

**Comment by adamdsmith** [comment]
Yep, a deep one. 

Thinking about value-added metadata from, say, a state-space modelling approach, I'd say:
- omni or directional
- gain (dbi probably most often reported and easily convert to dbd)
- \# elements (for directional antennas); but less important if gain is known
- beamwidth at -3db for Yagi (pie in the sky)

We're early enough in this, with few enough currently used options, that we could probably fill in those values for nearly every antenna in the system...

**Comment by denislepage** [comment]
Yup. I share the concerns about this becoming unwieldy.

The antenna model is one way to get at the various pieces that we need. It’s the simplest, for as long as there are not too many options. At that point, we may need to replace the drop down by a search box, like we do for species.

**Comment by leberrigan** [comment]
I agree should stick to antenna model and # of elements on the antenna deployments page. All the other information (radiation pattern, gain, efficiency, impedence, directivity) is still useful, but doesn't need to be peoples face all the time.

A good overview of antenna characteristics can be found here: http://www.waves.utoronto.ca/prof/svhum/ece422/notes/06-antennachar.pdf

There are two approaches I can think of:
1. Make a lookup table that includes all the specs for each antenna model that users can refer to
2. Just have the antenna model and # elements like we currently have and users can do their own Google searches.

While the 1st option will take a lot more effort, it at least preserves this information in case, say, a manufacturer decides to discontinue their product.

This also brings up a much larger issue of calibrating antennas and radio dongles. We don't actually know how well tuned these antennas are, we just assume they work indefinitely as they were designed, but that probably isn't true. I've talked with out local radio expert about this and he seems to think we should be doing regular checks on these antennas for antenna impedence/tuning and FUNcube gain/tuning. Eventually, this might be something we'd want to record with the antenna deployments so having the manufacturer's antenna specs will be very useful.

**Comment by StuMackenzie** [comment]
I wasn't suggesting we track all the intricacies of each antenna type, actually going the other way - Do we really even want to track them down to Mft, and Model#, or just stop at # elements? I think element|model and manufacturer| are probably sufficient.
