### ISSUE TITLE
R Package - Sandbox `dataVersion` is still 1 (should be 2?)

### ISSUE THREAD

**Issue by steffilazerte** [MotusDev/Motus-TO-DO#551]
@pmorrill @denislepage @cjardine-bsc 

Right now I'm overriding the `dataVersion` returned by the server response package from the sandbox server. It's always reported as 1, but it should be 2 so the package can download the new CTT tags (without a hard coded override).

**Comment by denislepage** [comment]
OK, we should change the API so it relies on the version table in SQL (which should be 2 in sandbox now)
