### ISSUE TITLE
Add link to receiver remote web interface on Station Dashboard pages

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#552]
Probably this page: https://motus.org/data/project/recvs?projectID=137 

Will need links added to here for CTT receivers: 
https://account.celltracktech.com/station/station-home/867459049297393/

**Comment by StuMackenzie** [comment]
IF we're going to do this we should be doing the same for connected sensorgnomes - https://sensorgnome.org/status/

While we're discussing new functionalities - 

Also, some way of tracking (1/0) whether a station is 'online', and perhaps display that from the receiver map, or

**Comment by tve** [comment]
Was something done here?
