### ISSUE TITLE
The sgdata crash of Sept 2019 - Processing Priorities

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#554]
1) Tag registrations from Noah Perlut Project 104 - tag recordings in email
- notified noah 14/9 of 12/14 tags being registered

2) Tom Rasmussen data - Project 177 - Data needs to be uploaded by user. Stu contacted 13/9

**Comment by Hussell** [comment]
The tag registration failed with this error for each tag:
Operand type clash: bit is incompatible with datetimeoffset SQL: "dbo.[prAPIImportTagsTransfer](?, ?, ?)"

This is probably a bug introduced elsewhere while sgdata was down, rather than something directly related to the sgdata crash.

**Comment by denislepage** [comment]
This is indeed related to recent changes.

We are now registering tags in both databases for consistency, but the deprecated field is a bit in live and datetimeoffset in sandbox, so inserting fails.

I have made a temporary fix to convert bit to the current UTC date when transferring. This will have to be undone when we convert the live table field type.

It should work now.

**Comment by Hussell** [comment]
12 tags successfully registered, 2 failed:

Unable to get a good estimate of burst interval for tag id 107 in file tag107.wav
Please re-record this tag and re-upload

Unable to get a good estimate of burst interval for tag id 108 in file tag108.wav
Please re-record this tag and re-upload

**Comment by denislepage** [comment]
Are we caught up on priority jobs? If so, I can send an update on the listserv.

**Comment by StuMackenzie** [comment]
I think we're all wrapped up here.
