### ISSUE TITLE
R Package: Replace cat() with message()

### ISSUE THREAD

**Issue by steffilazerte** [MotusDev/Motus-TO-DO#559]
Currently the `motus` R package uses the `cat()` function to return download progress messages to the user. Current R standards suggest that `message()` is more appropriate as they can be suppressed by the user (e.g., `suppressMessages()`).

I'd like to change all `cat()` to `message()`.

From a developer perspective, this helps me ensure my console isn't cluttered every time I run tests or build the package (making it easier for me to spot and fix problems). From a user perspective, it's nice to have control of the verbosity of a function's output.

The only problem I can think of when changing `cat()` to `message()` is if we think users are logging these progress messages. `cat()` sends the output to stdout, `message()` sends it to stderr, so the users would have to log it from a different output location.

Any objections?

**Comment by denislepage** [comment]
Sounds fine to me.
