### ISSUE TITLE
Tag Deployment Glitches

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#56]
1) Tag status still 'pending' in deployment summary after entering and saving a past deployment date when species not selected from pre-defined table which adds a speciesID.

When a species is just entered, without selecting from the drop-down list, a species, or species ID, isn't properly assigned, and therefore the deployment not activated. When I species are selected 'properly' it seems to resolve the problem.

This problem is also true for auto-fill - so if an auto-fill is selected from a previous deployment, species and speciesID aren't properly assigned and deployment not activated. Perhaps disengage auto-fill so that users have to choose from the drop-down list?

2) Other Properties. No results presented after "Add Property" selected - no new fields presented to enter data into.

3. When 'Add Deployment' selected, and new deployment page opened, there is no reference to the tag number the deployment is for. Once saved, a deployment ID is shown, but no tag number. Tag number should be prominent whenever possible.

**Comment by Hussell** [comment]
Re-tested everything mentioned here, and the problems all seem to be fixed.
