### ISSUE TITLE
safeFileRename can't handle a sufficiently large number of files/directories at once

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#561]
In safeFileRename, if too many files (or directories? Unclear) are uploaded in a single archive, then a call to stat to find out the device numbers of the source and destination files fails due to exceeding the size of shell's command-line buffer. Recently a try-catch block was put around this section to provide a comprehensible error message for users, but we'd like to prevent this error entirely by calling stat for, say, 100 files at a time instead of one call for all of them at once.

Currently waiting for a test environment to be available.

**Comment by denislepage** [comment]
This is the code that needs revisiting. 

In particular, that line, where the vector of folder names once concatenated exceeds the command line buffer size:

`        devNo = function(x) system(paste0("stat -c '%d' ", paste0('"', x, '"', collapse=" ")), intern=TRUE)
`

```
    ## get device number each directory resides on; requires that sum of path lengths of unique top-level directories
    ## don't exceed the shell's command-line buffer

    tryCatch({
        devNo = function(x) system(paste0("stat -c '%d' ", paste0('"', x, '"', collapse=" ")), intern=TRUE)

        levels(src$dirname) = devNo(levels(src$dirname))
        levels(dst$dirname) = devNo(levels(dst$dirname))
    }, error = function(e) {
        stop(paste0("safeFileRename has failed with the message:\n", e$message, "\nOften this is because an archive with too many files was uploaded. Try uploading the files for one receiver at a time."))
    })

```
