### ISSUE TITLE
Managing R package branches

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#562]
I'd like to figure out a process that ensures that we can keep the R package branches pointing to the appropriate motus servers.

sandbox branch: sandbox.motus.org
beta branch: beta.motus.org
master branch: motus.org

This assumes that changes impacting the current major release are done in beta, and merged regularly into sandbox. Changes impacting the next major release are done in sandbox, and never merged into the current beta branch. A major release entails starting a new beta branch from sandbox, and remember to change configuration files to point to beta, etc.

Pushing the beta changes into the master branch also will need to ensure that the server location is correct.

Are there other aspects that merges will entail? Can we have a clear procedure established along the lines above? Anything that can help preventing from having to remember manual interventions is welcome.

**Comment by steffilazerte** [comment]
To a certain degree, we're just going to have to pay attention. However, I've made some changes that should make it easier for us to keep on top of this:

1. I added some utility functions which will quickly change the default server in the R package (i.e. the `make_master()`, `make_beta()`, and `make_sandbox()` functions.
2. I added instructions/reminders to the `RELEASE.R` file to use these functions to change the api to the correct version prior to release (note that this already exists in the MotusRBook package)

**Comment by denislepage** [comment]
I am not entirely comfortable in exposing the changes of server in a function, so I would prefer not to have those available. I realize that people can access the code and figure it out easily, but most users won’t. A function would make that all the more tempting.

I think that this is partly a matter of having a proper protocol for merging among branches.

We have the same type of issue with our Java code. The only time where we have to tweak the configuration files are when we initiate a new beta branch, or transition the live/master branch between major versions.


1.       changes in the sandbox branch are typically not rolled up to the current beta branch, except punctually for individual files, or when we generate a new beta version.

2.       changes in the beta branch are those impacting the current major version. They are first done in beta, then merged into sandbox. They can be tested in beta and/or in sandbox.

3.       whenever we are ready for a minor release (e.g. from v3.1 to v3.2), this involves merging the changes in the current beta into master (e.g. beta3 -> master)

4.       whenever we are ready for a major release (e.g. from v3.3 to v4.0), this typically first involves starting a new branch from the sandbox (e.g. beta4), testing, and then merging that new beta branch into master.  Both those steps require reconfiguring the configuration files, so we should have a list of changes necessary, and the sequence in which those changes need to happen to support the above protocols.

For instance, when starting a new beta branch (say we are at beta2 now).

git checkout sandbox
git checkout -b beta3
# make changes to beta3 configuration files (e.g. point to beta.motus.org)
git add -A
git commit -m “Create new v.3 release”
git checkout sandbox
git merge beta3
# revert changes to sandbox configuration files (e.g. point back to sandbox.motus.org)
git add -A
git commit -m “Adjust sandbox branch following v.3 release”

If we follow that sequence, I think that we can always assume that changes made in beta3 can be merged into sandbox, but that the opposite would undo the proper configuration in beta3 and should be avoided (sandbox would then represent content meant for v.4 after that point).

**Comment by steffilazerte** [comment]
Okay, my mistake. I'll revert that back and just leave a note in the `RELEASE.R` script reminding us of the process.

For the record, the functions I've created are not 'exported', so when someone uses the motus package, they wouldn't see these functions anywhere. They only way they could use them is if they were advanced enough to know to use the triple colon notation: `motus:::function()` and even then, they'd need to know that the function existed.

That actually brings me to a side note (perhaps better posted as a separte issue?), another thing I'd really like to do in the `motus` package is to 'un'-export all the functions that we don't want users using (all of the `srv_` functions for one). Having all of these functions exported makes it hard for users to understand the work flow they should be using. Also if anyone is advanced enough that they should be allowed to use those functions, they should be advanced enough to know to use the `motus:::function()` notation ;)

**Comment by steffilazerte** [comment]
One more thing: is there any reason to number the `beta` branches? Presumably we shouldn't have more than one on the go at a time. As long as we tag the releases, we'll have a marker of each version. I would suggest keeping it to: master, beta, sandbox

Minor release: `master <- beta -> sandbox` (or if you prefer: `sandbox <- master <- beta`)
Major release: `master <- beta <- sandbox`

And we update the api we point to as we go through each stage of testing (i.e. branch)

**Comment by denislepage** [comment]
Yes, we may have overlap between releases, hence the beta numbering. When we upgrade a new beta version 3, and before beta 3 gets released formally, there may be fixes that we still want to do in live as minor releases (in beta2) while the beta3 version is being tested.

I know there’s also the github feature for versioning,  but I am not sure how we would use it to do the above scenario.

**Comment by denislepage** [comment]
Yup, un-exporting makes sense.

**Comment by steffilazerte** [comment]
I think the best would be to avoid that scenario if at all possible. If sandbox has moved on to beta, and we have a new minor fix we want to introduce, I think we should either:

a) wait until the current beta is tested and released to master, and then add it to the beta branch, or
b) add it to the current beta branch and include it in the round of testing

Otherwise we're looking at releasing beta 3 before beta 2, or releasing two versions back to back which is unnecessarily confusing, and I think should only be done if a release turns out to have a bug that we missed and which we really need to fix quickly.

**Comment by denislepage** [comment]
> I think should only be done if a release turns out to have a bug that we missed and which we really need to fix quickly.

Yes, that’s the purpose. The one-line bug fixes sort of thing. So how are those cases handled in your model?

**Comment by steffilazerte** [comment]
If the big release is so close to being released that it's in the beta branch, then any further changes we have to make should go there too. If we have 'would like' changes (as opposed to 'must have' changes), then we decide if we want them badly enough to delay the release so we have time to test them. If not, we wait until after the release, then add them to the beta branch and wait a bit to make sure we have no other 'would like' change to make before we make a second, patch-level release.

If the big release is still far away from being pushed to beta, then the small change goes into beta, is tested and then released as a minor patch change within the next days/weeks.

I don't mean to say that we can't make small patch-level changes as we go, but I don't think we should ever need more than one beta branches. Does this make sense?

**Comment by denislepage** [comment]
By my experience, beta releases can linger for a while before they are ready to publish as master. Say a few weeks is not atypical.

If we discover a bug in the interim that we want to fix immediately in the master branch before the next major version release, where do we do it? Do we revert back to starting a new branch of the last published version? I tend to find that more confusing.

Essentially, once we move a new major release from beta to live, we would never downgrade the live branch. Once a new version is released to master, the previous beta version would have no reason to ever change again, and there is no guarantee that they would even work.

For consistency with our Java code approach, I think I would still want to keep beta numbering. Is there really a downside? That way, each beta branch is done in a way that matches the latest minor release of a version number. I’m sure it’s a problem affecting everyone at a point or another. How do they generally handle it?

**Comment by steffilazerte** [comment]
It is definitely tricky, what about something like this: https://nvie.com/posts/a-successful-git-branching-model/

Our simplified version would be:
- sandbox (combined feature/develop branches)
- beta (their green release branches)
- hoxfix (a new type of branch for us, their red hotfix branch)
- master

With this system, if we're busy testing beta (v3.1.0), and something comes up that has to go into master (v3.0.0) and beta, we could work on it quickly in a side branch (based on master) then push to master (then merge master with beta) resulting in master (v3.0.1) and beta (v3.1.0) both having the fix. Then when we're ready to release v3.1.0 off we go, and it already has our quick fix.

That being said, if everyone's used to and prefers numbered beta branches, then that's fine, I won't argue any more ;)

**Comment by steffilazerte** [comment]
I've clarified the branch structure and instructions for keep the versions and API URLS consistent for each branch ([commit](https://github.com/MotusWTS/motus/commit/9b83bc5cacf171b8d1b03fe8eff027e398e6f464))
