### ISSUE TITLE
create new ctt_outgoing folder and process

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#563]
- [X] Step 1 (Jeremy). We need a new folder to host the CTT data files that will be moved during the zip file unpacking and that will await to be pushed to the S3 bucket.

I would like to use: /sgm/ctt_outgoing/

1- we need to modify the motusServer scripts so the folder is added as part of the build code.
2- we should add that folder in the list of constants in motusServer (e.g. CTT_OUTGOING)
3- we should set the appropriate permissions (read/write for the sg account). 
4- We have to ensure the folder can also be accessed by the Windows Java user.

- [X] Step 2 (Paul/Joey). We should modify handleNewFiles.R to recognize the CTT file name pattern (yet to be determined), and copy the .gz files into the folder represented by CTT_OUTGOING. At that point, all files can be placed in the same folder.

- [x] Step 3 (Paul/Denis). We need to set up a Java Process class that will obtain a list of all files contained in CTT_OUTGOING and push them to the S3 bucket (I think this is the purpose of /motus/data in S3). 

Once the files are uploaded, they should then be moved to the following folder (the serial and date values will be determined by parts of the file name):

\\\\10.100.100.9\\ctt_data\outgoing_archive\\<receiver_serial\>\\<yyyy-mm-dd\>\

- [X] Step 4 (Denis). I will also modify my earlier script that reads the Lotek data files for dual mode receivers, so the same format of files are also placed into the ctt_outgoing folder, and where they can be handled the same way by the process at step 3.

- [ ] Step 5. We should figure out what log messages and report will be available to users if their zip file only contain CTT files. I already added a log entry that reports the number of CTT files moved, but we may need to adjust the other messages.

- [ ] Step 6 (all). These changes should be scrutinized and deployed on the production server for testing, as well as merged with the master branch.

**Comment by pmorrill** [comment]
I was actually thinking that the sgServer would ping the api and include the current path to the CTT detection files, rather than copy them to yet another spot. The api would then copy them from the original path (where they were placed when the zip file was unpacked) to the S3 drive. Do we need to create a new intermediate location for them (eg: sgm/ctt_outgoing) ?

**Comment by pmorrill** [comment]
From an email I sent to Denis moments ago. I originally thought that the sgServer could send a request to our api (which would include the path to the CTT files as part of the request). then:

> It seems simpler to leave the files where they are and have the api copy them from THERE to the S3 drive.

> Each set will already be in a distinct sub-foilder (I believe) and so the process is that
the api code copies them all from that source folder (sent by the sgServer when it pings the api) 
up to AWS.

I am just trying to keep this simple, but there may well be good reasons to go the more elaborate route....
However, a monitoring process would replace this, with considerable more coding on our 
side.

**Comment by denislepage** [comment]
OK, Paul and I had a chat. We'll stick with my original plan of pushing all ctt files to the sgm/ctt_outgoing folder.

A couple key arguments in favor of this approach:

- we don't want the completion of the SG batches to be held back by the upload to AWS, or interrupted in case of failure, so moving the files aside and having a separate process for the upload makes sense.
- we will have 2 distinct processes feeding data files into the same ctt_outgoing folder for the foreseeable future (including with dual mode data extractions)

I think I have now figured out the key changes we needed to make in a new branch called motusServer@ctt_outgoing:

1. motusConstants.R:  I have added a regex to recognize the files prefixed with CTTDATA- (MOTUS_CTT_SG_DATAFILE_REGEX), or those that are created by SensorStations (MOTUS_CTT_SS_DATAFILE_REGEX) and added a new constant MOTUS_PATH$CTT_OUTGOING. We still have to confirm whether this folder is correctly dealt with with ensureServerDirs.R, but I think it is.

I have also manually created the sgm/ctt_outgoing folder, changed the ownership to sg:sg user (I also had to add some Windows write permissions to the Tomcat user as well on the NAS console, but that is only relevant for the Java side of things).

2. I added a short block of code that deals with files matching MOTUS_CTT_SG_DATAFILE_REGEX or  MOTUS_CTT_SS_DATAFILE_REGEX and moves them to the CTT_OUTGOING folder. The main parts I am not 100% sure is testing my regex patterns and the call to moveFilesUniquely. This (as opposed to moveFiles) should ensure that unlikely file name collisions are dealt with. I expect that the folder structure is **not** retained, which is the behavior we want.

I have been able to test the key parts of the code in R locally and I confirmed that both the REGEX and the moving of files are working as expected in my test environment.  We should do a bit more testing, but I think this will work and should have minimal risks.

Those steps should deal with point 1 and 2 above.  Can Joey, Paul and Jeremy all have a look?

I have also mostly completed point 4.

**Comment by denislepage** [comment]
Step 4 is currently running and creating all files from dual receivers. This will take a little while.

I have created a new Process class called org.bsc.motus.process.UploadCTTDataToS3, which does step 3, but I haven't yet tested it. Initializing the AWSClient fails on my local environment. I may be missing configuration values, or there may be a problem with my apache http client configuration, but I guess I can try with a small sample on sandbox next week.

I have also modified the regex pattern to match ctt files created by sensorgnome in motusServer (motusConstants and handleNewFiles), based on exchanges with Bob today.

**Comment by denislepage** [comment]
so, the approach with handleNewFiles seems to be silently failing. I think the files do not exist at the location anticipated, and that they need to be extracted with a new subjob before they can be moved. The log reports the correct number of files being moved, but no files appear in the CTT_OUTGOING directory as expected. I pushed a change to motusServer with the newSubJob line added below. I don't know that the sub job types is based on a controlled vocabulary or not. Can we give this a try? The message Josh sent yesterday at 11:29 am has plenty of files that we can try to upload for a test.

    ## move CTT SensorGnome and SensorStation data files
    cttdata = grep(paste0("(?i)(?:", MOTUS_CTT_SG_DATAFILE_REGEX, ")|(?:", MOTUS_CTT_SS_DATAFILE_REGEX, ")"), all, perl=TRUE)
    if (length(cttdata)) {
        sj = newSubJob(j, "CttFiles", .makeFolder=TRUE)
        moveFilesUniquely(all[cttdata], MOTUS_PATH$CTT_OUTGOING))
        eg = all[cttdata[1]]
        all = all[ - cttdata]
        jobLog(j, paste0("Moved ", length(cttdata), " CTT files for separate processing with names like\n   ", eg))
    }

**Comment by Hussell** [comment]
I'm not seeing any new commits to motusServer.

**Comment by denislepage** [comment]
Sorry. This is now in the ctt_outgoing branch.

This may not make a difference, but that was the only thing I could see that was different from the other subjobs, such as unknownFiles, which is simply moving files to a specific folder.

If this doesn’t work, we’ll have to dig deeper into the code to understand how subjobs are handled.

**Comment by joeybernard** [comment]
The functionality in the file processServer.R actually dynamically creates a function call based on the job "type" in the database. It creates a function name from "handle"+"job type", and then executes this to actually process the job. This code is "clever" but a pain to read and debug. This is one of the design decisions that I would like to fix when I have time. For now, I believe that we will need to create a file named handleCTT.R to manage the moving of the CTT files. I'll create one in the ctt branch and push it up so you can get an idea of what I mean.

**Comment by joeybernard** [comment]
Actually, checking the permissions for /sgm/ctt_outgoing, it looks like they are set to 555 on sgdata. Without write permissions, it might be a little hard to do much in that directory. Not sure if this is the cause of any issues, though.

**Comment by denislepage** [comment]
Permissions may well explain it. Jeremy, can you check this?

**Comment by Hussell** [comment]
Permission to write to the ctt_outgoing directory seems to have been the issue. I've identified a place in the code where the return value of file.rename is ignored, which explains why there was no indication of this in the job log. I'm adding some code there to at least log a warning when a file rename/move fails.

**Comment by denislepage** [comment]
Great! Did you also modify the script where permissions are originally assigned. Something like ensureMotus.R
