### ISSUE TITLE
Filtered Data Disclaimer Banner

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#564]
As discussed during **MotusFest 2019**, I would like the banner warning users about filtered data to be more obvious and on each page where filtered data exist. If you can make this an HTML text fragment to allow me to insert a link at some point that would be great. This would be a link to a page further describing how data are filtered and how to access unfiltered data.

**Pages where this should appear:**
 - https://motus.org/data/tagDeploymentDetections
 - https://motus.org/data/tag/deployment/detections/timeline
 - https://motus.org/data/track
 - https://motus.org/data/tracksSearch
 - https://motus.org/data/tracksMap
 - https://motus.org/data/projectTagDeployments
 - https://motus.org/data/tagDeployment
 - https://motus.org/data/projectTags
 - https://motus.org/data/projectReceiverDeployments
 - https://motus.org/data/projectActiveReceiverDeployments
 - https://motus.org/data/receiverDeploymentDetections
 - https://motus.org/data/receiver/deployment/detections/timeline

**Here are a couple sample formats that you can chose from:**
![filterData_topBanner](https://user-images.githubusercontent.com/35931796/65781571-37a1d080-e122-11e9-9f71-cab5f010b20e.png)

**HTML**
```
<div style="background-color:#FFFAC8;color:#500;border-bottom:solid 1px #770;padding: 20px;font-weight: bold;">
<img src="https://motus.org/images/warning.svg" alt="warning" style="float:left;margin-right: 20px;">
Attention: These public animations have been created using broad filters based on theoretical flight speeds, logical geographic/time sequences, and at least 3 consecutive tag bursts at a single station. Individual tracks have not been inspected for accuracy.
</div>
```
---

![filterData_midBanner](https://user-images.githubusercontent.com/35931796/65781597-4a1c0a00-e122-11e9-98df-5b9ce16e6197.png)
**HTML**
```
<div style="background-color:#FFFAC8;color:#500;border:solid 1px #770;padding: 20px;font-weight: bold;">
  <img src="https://motus.org/images/warning.svg" alt="warning" style="float:left;margin-right: 20px;">
Attention: These public animations have been created using broad filters based on theoretical flight speeds, logical geographic/time sequences, and at least 3 consecutive tag bursts at a single station. Individual tracks have not been inspected for accuracy.
</div>

```

**Comment by denislepage** [comment]
I think I would restrict that level of visibility to temporary warnings, not permanent ones about data disclaimers. I know we want people to see them, but seems overkill to have on every page in perpetuity, and may dilute the visibility of other proper temporary warnings.

We’ve mentioned that critical warnings would prevent the rest of the page from loading, so we probably also need a format for that when the warning is the only thing displayed on the page.

**Comment by jsayers-bsc** [comment]
This is a good format, especially linking to a page with a fuller description.

Denis's point is good though, that that style is maybe too bold for a persistent info bar and better suited for temporary alerts and warnings.

**Comment by leberrigan** [comment]
Okay, here's a new format:

```
<div style="background-color:;color:#000;padding: ;font-weight: ;max-width: 1000px;">
<img src="https://motus.org/images/warning.svg" alt="warning" style="float:left;margin-right: 20px;">
<b>Attention:</b> These public animations have been created using broad filters based on theoretical flight speeds, logical geographic/time sequences, and at least 3 consecutive tag bursts at a single station. Individual tracks have not been inspected for accuracy.
</div>
```

![image](https://user-images.githubusercontent.com/35931796/101175446-2f410180-3613-11eb-9fe9-1b545dddd1e5.png)

![image](https://user-images.githubusercontent.com/35931796/101177889-4e8d5e00-3616-11eb-99a4-e226b77bfcca.png)

![Uploading image.png…]()

**Comment by leberrigan** [comment]
We'll deal with this in the explore dashboard, but it's a good point
