### ISSUE TITLE
It's LUNCH time (ha...tricked you into paying attention....its actually LAUNCH time, almost)

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#568]
We want to launch beta9. Hopefully in the next few days. The list of things we need to do, and assignees, is below. Hopefully we can all prioritize getting this done ASAP. Please strike things from the list here as you complete them (or add things to the list....if you must).  

1.	Paul needs to remove CTT toggle from https://beta.motus.org/data/project/sgJobs
2.	R package needs testing to ensure it’s managing version correctly. (Josh and Lucas)
3.	Catherine needs to script database changes.
4.	Lucas and Josh to check list on github: https://github.com/MotusDev/Motus-TO-DO/issues/472

yum yum Launch. :)

**Comment by pmorrill** [comment]
I have removed the 'ctt toggle' on the detection data upload tool.

**Comment by cjardine-bsc** [comment]
I've scripted the necessary changes.
