### ISSUE TITLE
Networked receivers for project 113 - data not processing?

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#569]
Got a notification from Bart Noort that their networked receivers, which are online as per https://sensorgnome.org/status/, but data has not been updated on our servers.

**Comment by StuMackenzie** [comment]
From Bart:

The results of this station in 2018: https://motus.org/data/receiverDeploymentDetections?n=1000&q=&f=1&o=0a1a2a3a4a5a&id=4892

Exactly the same tagging location! So just as close, no hardware changes, and system is running fine

The are registered under project 113
One of our most successful stations for instance last year was, this one: https://sg-5016bbbk1b68.sensorgnome.org/

And this season no detections at all, https://motus.org/data/receiver/deployment/detections/timeline?year=2019&id=4892

Which is impossible since we are tagging pretty close, I dont know how “rerunning works or impacts performance” But if you can do a rerun on 1 station, could you please try that one?

**Comment by Hussell** [comment]
Alright, this one in particular has been rerun, and I'm about half through rerunning all the networked receivers.

**Comment by denislepage** [comment]
Instead of burdening the sgdata server, is there a reasonable compromise plot that we can create on our web site. What are the components that we would be missing to do the same plots, and is there a good replacement option that would achieve more or less the same thing?

**Comment by jsayers-bsc** [comment]
What ended up being the issue here? Just that the receiver processing had been backed up due to the server problems, delay from the plots, etc?

**Comment by Hussell** [comment]
So far as I can tell, almost everything was due to the processing outage delaying processing and delays in tag deployment metadata reaching us. Now that we're caught up I have much more time to dig into these things, but I checked a few here and they look OK now. If there are any remaining problems, each one should go in its own issue, I think, rather than here.
