### ISSUE TITLE
Sorting "Last Data Processed" field on website receiver tables

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#570]
This was discussed in our meetings last week. The ability sort by Last Data Processed would be very helpful in managing projects and ensuring timely data uploads.

It would also be helpful to include this field in the csv download option.

**Comment by pmorrill** [comment]
I have added full table-column sorting for the deployment list under 'Manage Recvs' and for the tag list under 'Manage Tags'. For CANARIE-3 we plan to re-work some of these pages, so I did not want to invest too much in this change before an over-all plan is in place. But I think that the system I added is intuitive, though we may want to add a not somewhere that columns are now 'sortable'.

This is in the sandbox only at the moment: @jsayers-bsc should take a look there. I can move it into beta9 and then Live if it passes muster.

**Comment by jsayers-bsc** [comment]
That's very helpful! Yes since there will (hopefully) be some other improvements and changes, something that just adds the basic function now is great.

There are actually some discrepancies in the two sources of deployments that jump out... Manage Revs doesn't contain any deployments post 2019-06-01 (below):

![image](https://user-images.githubusercontent.com/55001144/69202277-29af7100-0b0f-11ea-8f80-580d6e52e9af.png)

Whereas there are a quite a few since then, visible in the [Receiver Deployments page](https://motus.org/data/projectReceiverDeployments?id=1). 

![image](https://user-images.githubusercontent.com/55001144/69202331-52d00180-0b0f-11ea-8fd4-c396db1769d0.png)

Neither [Campbellville ](https://motus.org/data/receiverDeployment?id=5769 )nor [Discovery Island](https://motus.org/data/receiverDeployment?id=5785) deployments show up in Manage Receivers, but do in Receiver Deployments. Both of those deployments started prior to 2019-06-01, but were only entered recently — a couple weeks ago, and literally today.

But then [Waskanigash ](https://sandbox.motus.org/data/receiver/deployment/edit?projectID=1&id=5301)shows up in Manage Receivers, but not in Receiver Deployments. Presumably this had been in Project 1 but is no longer. 

Strange!

**Comment by pmorrill** [comment]
But, isn't this because you are comparing the sandbox with the live server? I sure hope so.

**Comment by jsayers-bsc** [comment]
Yes it is! I wondered that, but didn’t expect so many differences or such outdated data. How far back would one expect to go before the two mirror each other? Or is there a better way of describing the differences?



On Nov 20, 2019, at 8:08 AM, pmorrill <notifications@github.com> wrote:

﻿

But, isn't this because you are comparing the sandbox with the live server? I sure hope so.

**Comment by pmorrill** [comment]
I have put the changes into the beta9 branch so on next deployment (possibly this AM) the sort feature will appear in beat server.

>  How far back would one expect to go before the two mirror each other? Or is there a better way of describing the differences?

I'm not the one to ask! It is never clear to me precisely when data get's synchronized to sandbox etc.... :)

**Comment by StuMackenzie** [comment]
Beautiful - thank you @pmorrill 

Others? may have a suggestion on how or if they should be labelled as 'sortable' or if it's intuitive enough. I think it's intuitive. - often a classic mistake
