### ISSUE TITLE
Project 235 & 236 missing data

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#572]
Compiling a list of issues related to these projects here. Some are related to re-runs, others are new data coming in that's not showing up until it's rerun. 

Hi Stuart. Thanks for that, it looks like SG-96D1RPI36405 and SG-9198RPI35751 have been sorted out

But, SG-3B52RPI35BE8 has not.. There are still no detections, it is very close to the  receiver SG-6D7CRPI34135 which you can see has all 20 bats we tagged detected, so this one should have the same, if not more as it has a larger antenna and looks over a larger area. You can see on attached screen grab there is loads of data and it is totally consistent with timing of the nocturnal activity of the bats and it is the same for each night.. and pretty much mirrors the data rates/periods over the night as for 4135, so I am not sure why there are no detections? There certainly looks to be..

**Comment by StuMackenzie** [comment]
In addition to SG-3B52RPI35BE8 still not working, I just uploaded data from 4 more receivers, 2 worked, 2 did not despite also having loads of data.. The additional 2 that did not work are SG−CA4CRPI353E7 and SG−98D4RPI3B8B8..  I also have 1 more night of data from SG-3B52RPI35BE8 that I have not yet uploaded, I wanted to wait until that one has been fixed and then I will upload it as a test to see if it is working going forward..

If you figure out what the problem is with these, can you please let me know? I'm finding it very frustrating that some work and some don't, Its very confusing.. 

Regards,
Thomas

**Comment by Hussell** [comment]
I've rerun them both, and they both got new detections. The detections have (finally) made their way over to the main database, and are visible on the website as of now. Sorry for the long delay.

**Comment by StuMackenzie** [comment]
RE. SG-9198RPI35751 (Job 1543765) but it looks like we only reran boots 6 and 7, where in recent upload (job 1510645) it was boots 1 and 2 that were included (That look like they have data).. 
can we please get that one sorted out?

**Comment by Hussell** [comment]
Yes, but boots 1 and 2 were uploaded after the problem was resolved, so there's no need to rerun them. The boot number reset occurred on 2019-08-26, and on the plot and the receiver timeline there's only sparse activity after that point.

https://sgdata.motus.org/download/236/SG-9198RPI35751-2019_BIO-RTIO_5751-2_hourly_tags.png
https://motus.org/data/receiver/timeline?year=2019&id=2695

**Comment by Hussell** [comment]
Rerunning such sparse batches takes a trivial amount of time, so I did it anyway. No change to the activity, but a handful of new detections showed up in a few of the tiny periods when the receiver was active. I'm not sure why. I checked the metadata available at that time and it's the same as it is now.
