### ISSUE TITLE
Why would the Date of Last Upload be in the future?

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#574]
The Date of Last Data Upload for Conestoga receiver is in 2022. Anyone know why that would be?

![2019-10-04_124842](https://user-images.githubusercontent.com/55001144/66226254-6383ff80-e6a8-11e9-96cf-d2f4b0b6c8aa.png)

I started looking into this because I found an SD card with Conestoga data on it from 2018 and I wanted to confirm it had been uploaded. 

According to sgdata, the last file upload apparently was in Dec 2017, and no detections occur after that.

There was a receiver re-run in early 2019, which indicated antenna activity at points in 2018, though no new detections (and no indication here at least that a more recent file was uploaded).

**Comment by denislepage** [comment]
Faulty GPS readings, almost certainly.

In some places at least we ignore data outside a certain date range (2010-current), but I don’t know on which source this value here is based.

**Comment by jsayers-bsc** [comment]
I see... Could this perhaps be why there also appears to be missing data and no uploads since 2017? If the erroneous date(s) was associated with earlier data it was simply ignored? Then again, there are not even file upload events listed later than 2017...

**Comment by denislepage** [comment]
I have seen discrepancies between hits and the table range in batches.

At least some corrections that are are done probably aren't integrated into batches.

**Comment by cjardine-bsc** [comment]
I'm referring to the ts field (i.e. the timestamp when the batch was run by tagfinder) not the tsBegin or tsEnd fields. 

I'm not sure why the ts field would be off.

**Comment by Hussell** [comment]
The "Last **Data** Processed" column uses the largest tsEnd from all batches for the receiver, not the largest ts. So, the last date that a signal was recorded, not the last date that a file was uploaded. See #362 for speculation on why one of this receiver's batches has a future date. Also from there, 2018-07-08 should be the correct date for Conestogo.
