### ISSUE TITLE
Sensorgnome Status Page Updates

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#575]
There is a terminated and supposedly networked gnome at Wildwood listed on https://sensorgnome.org/status/

SG-1253RPI32253 

![image](https://user-images.githubusercontent.com/55001144/66320741-628fdf80-e8ed-11e9-85ba-7cc94464a94a.png)

The deployment at Wildwood ended in April 2018 when receiver was moved to a new location.  Additionally, the gnome was never networked in the first place apparently.

**Comment by jsayers-bsc** [comment]
There is a secondary issue here that I'm curious about. Maybe it's just a misunderstanding of mine regarding how the system works, but it seems odd...

The Wildwood deployment ended in April 2018 according to the receivers page. That's also the date of the last data upload.

![image](https://user-images.githubusercontent.com/55001144/66323386-b997b380-e8f1-11e9-8910-344d40211aaa.png).

However, in the job processing status, the last file upload for Wildwood is Dec 2017 (Job ID 110535). All the time stamps for the processing are Dec 2017. Yet, the detection data in the output file goes all the way to April 2018! 

I had assumed the "product" in each of these jobs would be the output only from that particular job, but maybe that's not the case?

**Comment by Hussell** [comment]
SG-1253RPI32253 has never uploaded anything through a network connection ("synced"), but it must have been connected to sensorgnome.org at least once, apparently on Sept. 16th (of some unspecified year). Since nothing ever disappears from that list, I recommend you ignore the entry unless/until it shows as being connected.

In job processing status, I see several upload jobs for the Harrington deployment, right up to 2019-10-04. The first upload for the Harrington deployment (2018-09-08) also contained files for the last part of the Wildwood deployment, and thanks to knowing when the deployments started and ended, the each part of the data was assigned to the correct deployment.

**Comment by jsayers-bsc** [comment]
nothing ever disappears from that list

That explains a lot!

Next item: Ok so when the plot is viewed for any particular upload job, it does not simply display the output for that particular job. Rather, it pulls all known detections for that deployment regardless of when they occurred. That is why the plot for Wildwood showed data after the last file upload, and why all the Harrington plots are the same as each other. Is that correct?

**Comment by denislepage** [comment]
I was going to suggest something similar regarding the plots so they are truncated in time. Showing the latest batch only sounds reasonable, but we would have to modify the plots so they are archived with each new batch (adding the batch number to the file name might be an easy way to do so).

**Comment by jsayers-bsc** [comment]
Not necessarily resolved, but not an issue either. It's a quirk of the sensorgnome.org page that many receivers are displayed simply because they connected once.

**Comment by StuMackenzie** [comment]
@dfloer - can we make a partition in this list where only those that have connected consistently, moving data, etc., are separated from those that connected only once, or infrequently?

- Making the list searchable by each column, and include the Motus project would be ideal.
- This is covered elsewhere, but link this list to the active deployments for these receivers on Motus.org
- I'm sure there are other suggestions for this page

**Comment by dfloer** [comment]
Forgot to reply to this, I'm planning on having different sorting and filtering/searching options for the updates status page.
