### ISSUE TITLE
What's the current situation with: repositories, branches, versions, servers, etc.

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#577]
The home pages and static content at https://motus.org/, https://beta.motus.org/, and https://sandbox.motus.org/ are hosted on IIS servers running WordPress. The /data parts of the websites are hosted on Tomcat servers connected to MS SQL Server databases.

 * https://git.birdscanada.org/Bonobo.Git.Server/Motus.git has the Java and JSP source for motus.org/data/, where deployment data is entered and detections are viewed.
   * The master branch is our alpha branch (non-standard), and is usually deployed to https://sandbox.motus.org/data/, which has its own copy of the database.
   * The beta branches, e.g. beta8, beta9, beta10 are for final testing at https://beta.motus.org/data/, which uses the live database.
   * The live branch is deployed to https://motus.org/data/
   * Currently live and master are almost identical to beta9.
 * https://github.com/MotusWTS/find_tags has the C++ source for the tag finder, which searches through signal files uploaded from receivers for the different signal patterns each tag transmits.
 * https://github.com/MotusWTS/motusServer has the R source for sgdata.motus.org, where tags are registered, receiver data is uploaded, and the tag finder is run.
 * https://github.com/MotusWTS/motus has the R source for the Motus R Client, through which detections can be downloaded to an individual user's computer.
   * The master branch currently is at version 3.0

The database has a version number for the data itself. This is about the arbitrary keys generated for each row of data. When we went from beta8 to beta9, we also went from version 1 of the data to version 2. Version 1 data was kept in tables prefixed sg_ and version 2 data is kept in tables prefixed det_.

 * The main database is used by both motus.org and beta.motus.org.
 * The shared test database is used by sandbox.motus.org: on sandbox it's safe to enter test metadata and test things which might delete or alter data if they go wrong.
 * Some programmers have a copy of the database for testing during development, usually a copy of the sandbox database.

On sgdata.motus.org, there is a MariaDB database which holds the results from tag_finder (in other words, detections) to be transferred to the main database. In addition there are a multitude of small sqlite databases, including one for each receiver, one for metadata copied from the main database, a database which records waiting, in-progress, and finished processing jobs, and several tiny databases for details which didn't obviously fit anywhere else.

**Comment by leberrigan** [comment]
Closed and moved to documentation
