### ISSUE TITLE
434 MHz tags cleanup

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#578]
Couldn’t find the original issue, but 433 is still listed in Manage Data/ Manage Tags table here: https://motus.org/data/project/tags?projectID=207

**Comment by Hussell** [comment]
I don't remember this, so I need a little more background. The tag was registered 2018-07-25, deployed 2018-08-01, and has no obvious issues.

**Comment by StuMackenzie** [comment]
Sorry Jeremy, the frequency listed is 433 MHz instead of 434 MHz

**Comment by cjardine-bsc** [comment]
yes, removing it triggered a DB error. Denis requested that we leave it there until the beta9 launch

**Comment by Hussell** [comment]
Another misunderstanding, cleared up now. Catherine changed all the frequencies to 434 MHz, and fixed the date bins too.
