### ISSUE TITLE
Terminated deployments showing up on small receiver map on motus.org

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#579]
Recently, the Old Cut deployment has shown up as terminated on the receiver map at Motus.org

![image](https://user-images.githubusercontent.com/55001144/67115002-2f7e0380-f1ab-11e9-8339-b29294fe914a.png)

A second terminated deployment is showing up on this map as well (Anderson, on highway 24 East of 59). 

This only affects the small inset map on motus.org homepage. The larger map with additional controls displays the proper information.

**Comment by Hussell** [comment]
Old Cut was the result of a bug, now fixed. Anderson is showing because that little inset map shows all deployments for the last year, instead of today's deployments.

**Comment by jsayers-bsc** [comment]
Interesting — two totally different causes!

On Oct 18, 2019, at 4:17 PM, Jeremy Hussell <notifications@github.com> wrote:

﻿

Old Cut was the result of a bug, now fixed. Anderson is showing because that little inset map shows all deployments for the last year, instead of today's deployments.

**Comment by StuMackenzie** [comment]
Apparently Project 213 is still seeing terminated deployments on the map?

**Comment by Hussell** [comment]
To clarify, is this also about the map on the homepage?

**Comment by jsayers-bsc** [comment]
That's it! They are looking at the small map that includes terminated deployments from the same year. I'll pass that along to them.

- Would it be easy to simply display the same map source for both of these pages? If so, maybe that would help reduce some confusion. Or maybe it's still worth displaying deployments by year on the landing page?

- This is another example of why, in cases where two multiple deployments from different time periods overlap the same physical location it would be ideal to show the most recent deployment rather then the earliest (#822)

Closing this one...

**Comment by Hussell** [comment]
I remember it like this (take it with a grain of salt): Stu wanted a year's worth of receivers to be displayed on the homepage, back in ~2015-2016 because a lot of deployments disappeared during the winter, so the map didn't look impressive enough.

I think the array of towers is now impressive enough at any time of the year, so I'd be happy to switch the homepage map back to showing the current day instead of the current year if it will reduce confusion like this.

**Comment by jsayers-bsc** [comment]
Yeah I figured that was the ultimate reason :) But yes, also true that it's probably not needed anymore given the density (especially on the smaller map, which tends to highlight that in the first place!)
