### ISSUE TITLE
Table filters

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#58]
From Stu:

Not sure who's bailiwick this is, or how easy this is, but in addition to the existing tag metadata filters, it would be nice to be able to filter by each field although only a few of them make sense - TagID, Date Bin, deployment range, species.

**Comment by Hussell** [comment]
This is already available when browsing the public tables, e.g. https://motus.org/data/projectTags?id=38, so the issue is about filtering when managing tags. https://motus.org/data/project/tags?projectID=38

I would like to discuss unifying the UI of the tables shown when browsing and managing data. The browsing ones were created by me, the managing ones were created by Paul. They both have features I like, and I think it would be nice to have the same UI everywhere on the site.

When browsing, one search box is used to filter the entire table, whereas when managing there are custom filters for specific fields. At the very least, the managing tables should have a simple search which covers everything visible in the tables. Adding custom filters is still useful, though. E.g. "on or before: YYYY-MM-DD" does something which can't be done with the basic search.

The managing tables have tabs which filter specific categories. That's a really nice feature which I'd like to add to the browsing tables.

The browsing tables can be sorted in arbitrary ways. That's a feature I'd like to see on the managing tables.

The managing tables pre-load the entire table, so flipping through the pages is faster than on the browsing tables, where each page is fetched from the server one at a time. It would be nice to combine these: pre-fetch nearby pages, but don't load the entire table if it isn't needed.

**Comment by StuMackenzie** [comment]
Specifically, refering to tag tables in the "Manage Your Tags" Page - data entry platform. eg. https://motus.org/data/project/tags?projectID=112

Thanks

Stu

**Comment by Hussell** [comment]
On the explore side I created a couple of classes to generate the tables and handle the common parts of the queries.
http://localhost:8080/javadocs/motus/org/bsc/motus/TableQuery.html
http://localhost:8080/javadocs/motus/org/bsc/motus/web/TableBuilder.html

They aren't properly documented, but there are plenty of examples of how to use them in the code.

**Comment by Hussell** [comment]
Useful link, since I keep coming back to this issue:
https://uxdesign.cc/design-better-data-tables-4ecc99d23356

And discussion of same on HN:
https://news.ycombinator.com/item?id=21460966

**Comment by jsayers-bsc** [comment]
The examples on that page are awesome. It would be great to get more depth and function in the web tables on motus.org similar to the design demonstrated there.
