### ISSUE TITLE
missed tag registration, project 191

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#584]
Hello Denis,
I would like to report to you that unfortunately we have deployed a tag that was missed in the course of recoding and registration.
Tag NTQB2-3-2, Serial Number NQ0014210, 166.380, 55.460000, Code 96
was activated at 08:50 UTC 10 Sept 2019 and deployed on a western sandpiper in the vicinity of this project 191 receiver:  
Data from the received that cover this period have been uploaded to the motus website.
![image](https://user-images.githubusercontent.com/21110542/67354488-3b5b2400-f523-11e9-9d63-ac6d1427c5af.png)

If there is a way to “recover” the, it would be greatly appreciated.
Otherwise – my apologies for any inconvenience caused.

Thank you and best wishes,

Yuri Zharikov

**Comment by leberrigan** [comment]
I tried finding the tag within the raw SG data for that day, but was unsuccessful, although it may just be a problem with my code. 
![tag96_pulses](https://user-images.githubusercontent.com/35931796/67391805-c9f89100-f575-11e9-9eca-d7b03d89aa3c.png)

The average period for tags 95 and 97 is **10.6990003586**. Should we just use that number?

Motus Tag   ID | MFG ID | Period
-- | -- | --
36218 | 95 | 10.6997003555297
36219 | 97 | 10.6983003616333

**Comment by cjardine-bsc** [comment]
If we knew it had the same period as the other two that should be fine. I've registered the tag, if we need to change the period or anything we can.

**Comment by denislepage** [comment]
The default burst_slop is 4 ms, + 1ms per extra intervals missed.

10.699 is probably a reasonable guess, which I assume will allow between 10.695 and 10.703 seconds.

We can always look at a few more in that range of period, see if many of the theoretical 10.7 fall outside the above range.
