### ISSUE TITLE
Outstanding Minor issues to discuss/resolve 

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#586]
- [x]  Fixing 2022 date issues in database (outstanding) - 

-  [x] Assigning all Funcubes as FunCube Pro across all deployments to remove those notifications in database, or just accept undefined radio as OK - taken care of. 

-  [x] education pieces for Liza

-  [x] Lotek tag registration piece - Denis will forward a new file format to Catherine.

-  [x] discuss potential implications of changes to https://sensorgnome.org/status/ 

-  [ ] Labeling stations at 'networked' and providing direct links from motus.org - see https://github.com/MotusDev/Motus-TO-DO/issues/601 @dfloer 

-

**Comment by Hussell** [comment]
There's a list of all the future dates in #362.

**Comment by StuMackenzie** [comment]
Motus Call Notes October 23: (incomplete)

Jeremy to investigate reassigning/fixing year 2000 data

Solution could also help us to resolve timezone issue?

Boot number issue: 

Sensorgnome Plots: - 

Step 1 - rewrite notification and let know what the alternatives are. (Luc)
Step 2 - redo timelines to create more at a glance data
Step 3 - integrate more immediate feedback and summaries into Motus station dashboards

Seems like a solution may involve 2 summaries - one performance based on reboots, pulse counts, , the other detections.

Reprocessing data: still requiring quite a bit of manual attention until we're up to date.

Fixing 2022 date issues in database - Jeremy to ping Catherine on the outstanding issue.

Catherine will add FunCube Pro and FunCube Pro Plus, and remove the notification flags for undefined funcubes. assign all Funcube s as FunCube Pro across all deployments to remove those notifications in database, or just accept undefined radio as OK -

**Comment by cjardine-bsc** [comment]
I've added FunCube Pro Plus to the lookup options and updated the existing FunCube Pro dongles to FunCube Pro Plus. 

Next step is for @pmorrill to look at the web interface and ensure that users cannot enter a null value in the dongle column, and that "unconfirmed" only shows in cases where it is already selected. 

I have also commented out the check for Unconfirmed FunCube dongles in the data validation proc. They should be removed from the validation centre on the next re-run

**Comment by pmorrill** [comment]
I have added code to beta9 and master branches, so that the dongle type option 'Funcube; unconfirmed' is only available is it was set earlier.  

The dongle type is a mandatory field for SENSORGNOME receivers. Should it also be mandatory for SENSORSTATION?

**Comment by StuMackenzie** [comment]
Yes Dongle Type should be mandatory for SensorStations, but it will only be relevant to the 'Sensorgnome' USB ports.

**Comment by jsayers-bsc** [comment]
Looks like the dongle type error is back for Funcube: Unconfirmed.

[https://motus.org/data/issues?id=1#v_sensor_antenna_dongle](https://motus.org/data/issues?id=1#v_sensor_antenna_dongle)

**Comment by cjardine-bsc** [comment]
huh. I must not have executed my change. Its actually done now. Promise.

**Comment by jsayers-bsc** [comment]
It actually _was_ fixed. But something changed!

**Comment by StuMackenzie** [comment]
Closed in deference to https://github.com/MotusDev/Motus-TO-DO/issues/601
where we'll continue the conversation. #601
