### ISSUE TITLE
parameter overrides table

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#591]
motusServer relies on a sqlite table called parameterOverrides.sqlite that allows to specify various exceptions to the detault running values, including for instance the expected tag nominal frequencies to look for. The list of supported parameters is described here: #465 

I would like to examine the possibility of using this table to make other types of corrections, particularly those related to timestamp and boot number issues.

projectID | serno | tsStart | tsEnd | monoBNlow | monoBNhigh | progName | paramName | paramVal | why
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | SG-4414BBBK1318 | 0 | 1262304000 | 25 | 25 | find_tags_motus | ts_corr | 307584000 | GPS failure
1 | SG-4414BBBK1318 | 0 | 1262304000 | 26 | 26 | find_tags_motus | ts_corr | 309655711 | GPS failure
8 | Lotek-1234 |   |   | 12 | 15 | find_tags_motus | ts_corr | -14400 | Lotek time offset correction
10 | SG-4414BBBK1318 | 1546300800| 1556668800 |   |   | find_tags_motus | bn_corr | 16 | MonoBN reset
10 | SG-4414BBBK1318 | 1556668800 |   |   |   | find_tags_motus | bn_corr | 22 | MonoBN reset

1- First 2 lines would provide a manual corrections of ts for periods where a GPS had failed to set the clock for extended periods that cannot be accounted for by the software. We would probably need at least the receiver serial number, and a boot number. In this case, boot number 25 and 26 would each be added a ts increment to bring them from January 1st, 2000 to October 1st, 2019 and Oct. 24th, respectively, but only when the original timestamp is less than January 1st, 2010.

2. The third line would be used to correct for invalid time offsets in Lotek files. Again, the ts_add variable would here subtract 4 hours to the ts values. I think in this case, we can rely on the receiver serial and boot numbers to identify the rows to correct, and perhaps a range of ts values.

Both of the ts corrections above would be applied in the same place where we made the GPS rollover correction recently. They may only need one variable ts_corr, rather than one for each type of corrections.

3. Finally, this approach could potentially also be used to correct for Boot number resets. A complication here is finding identifying criteria to correctly identify files that need a corrections, and I haven't looked at where this correction should be applied. The general idea here is that files that pertain to data between a certain ts range should have a boot number incremented (e.g. if ts > xxx, boot numbers + 16). But, the ts range should exclude invalid GPS fixes, and I expect we don't know the batch ts until we're at least some way into reading the files. Either we wait until we reach a line with a valid ts and then immediately apply the boot number correction to the entire batch, or we only do that step at the end of the batch. I'm not sure what the implications of either approaches are in the code.

In my example above, batches between 1 Jan and 1 May 2019 would see their monoBN incremented by 16, and those after 1 May by 22 (assuming there has been 2 resets applied to that receiver).

Finally, in addition, I would like to to transfer the management of that table into the motus SQL server database. This will mean adding a job to refresh periodically the content of this using a new API entry point in the motus API. Catherine, could you tentatively create a new table with the content I sent you, create the views that are in sqlite, and send those 2 views to Paul for adding as an API entry point?

The main benefit of that migration is to be able to reconcile more easily the various receivers with their metadata.

**Comment by joeybernard** [comment]
I don't see any reason why we can't do this. The first step is to pull up the sections on the motusServer R code where the parameter overrides are read in and used. I already know a couple of spots. I'll do a search of all of the spots where it shows up. Once we have something working reliably on sgdata, we can look at adding an API to synchronize between sgdata and motus.

**Comment by joeybernard** [comment]
It does look like all of the 'handleXXXfindtags.R'  files do call getParamOverrides.R. So if we create a new API to transfer overrides, we should be able to define overrides per device serial number.
