### ISSUE TITLE
problem uploading file

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#592]
Copied from email. I'll forward to Lucas and Josh. 

Hi Denis,

I'm trying to upload detection files. Twice I've tried to verify the file first and it doesn't' work. The message is:

Verify file with identifier:1e237f6f49a28c800b9e8277d536dc9311403b4c

From there I can't do anything. Thoughts?

Kristen Heath, 
Texas Tech University

**Comment by denislepage** [comment]
Josh suggested to the user to wait for a bit longer, and it eventually worked. I don't know if there's a way for us to display a clearer message (e.g. please hold, this could take a few minutes), while the process is happening.

**Comment by pmorrill** [comment]
When this message is displayed:

> Verify file with identifier:1e237f6f49a28c800b9e8277d536dc9311403b4c

The Motus server is communicating with the sgServer to determine is the file has been previously uploaded.

I have noticed widely varying response times. Maybe we just need to change the text to say (eg):

> Verifing file with identifier: 1e237f6f49a28c800b9e8277d536dc9311403b4c. This may take a few moments.

**Comment by denislepage** [comment]
Agreed

**Comment by jsayers-bsc** [comment]
Just wanted to point out that the new "this may take a few moments" message has intruded where it's not welcome.

![image](https://user-images.githubusercontent.com/55001144/68222285-c541cd00-ffb8-11e9-952f-add287f1c8fe.png)

**Comment by pmorrill** [comment]
Actually, I think we just have to deploy the beta code to live (Denis?) to solve that. If you run an upload on beta, it will show you how it should look....

**Comment by denislepage** [comment]
Things were deployed earlier today.

**Comment by pmorrill** [comment]
@jsayers-bsc have you checked the data upload ('This may take a few moments') msg, to verify that is is correctly formatted since Denis deployed beta to live?

**Comment by jsayers-bsc** [comment]
Yes it is all good!

On Nov 19, 2019, at 11:24 AM, pmorrill <notifications@github.com> wrote:

﻿

@jsayers-bsc<https://github.com/jsayers-bsc> have you checked the data upload ('This may take a few moments') msg, to verify that is is correctly formatted since Denis deployed beta to live?
