### ISSUE TITLE
New Receiver Uploads Messaging

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#593]
Just remembered it's best if I post this kind of stuff on here! Proposed message follows:
Dear Motus Collaborators,

> **Preliminary Receiver Plot Change**
> We have temporarily paused the production of receiver plot graphics to reduce the strain on our processing servers. These are the graphics typically linked in notification emails and provided through our SGData server. We understand users often rely on these plots for quick diagnostics after uploading their data and we are working on creating a new method for plot production that is less resource-heavy. At this time, we suggest users use other tools already available on the Motus website:
> 
>-  To see which tags have been detected, please use the publicly available interface in Explore Data > Projects and select the receiver of choice. Note these data are filtered so you may not see everything.
>
>  -  You will need to download data through the Motus R package to view all your unfiltered data.

>-  To inspect antenna activity, you can review the receiver timeline under Manage Data > Receivers and select 'Edit Receiver Properties' for the receiver of choice. The receiver timeline can be viewed by clicking on 'Receiver Timeline' in the top-right corner.

**Comment by denislepage** [comment]
A few changes below. I’m wondering if it would be relatively quick to set up a query that includes the list of tags in the notification email directly. A query like this would do it, but I expect that a single top job may be associated with multiple subjobs? Is the list of jobs and subjobs kept in Maria db? I am not finding it there. The query is very slow, so a new index would be required on motusJobID in batches.

select distinct motusTagID from batches a inner join batchRuns b on a.batchID = b.batchID inner join runs c on b.runID = c.runID where a.motusJobID = 1767047;

This below is much faster, but we’d need to be able to sort out the link between the top jobID and the batches.

select distinct motusTagID from batches a inner join batchRuns b on a.batchID = b.batchID inner join runs c on b.runID = c.runID where a.batchID = 650630;



Corrected email:

We have stopped the production of receiver plot graphics generated after the tag processing as those were consuming a large portion of the processing time in many cases. These are the graphics typically linked in notification emails and provided through our SGData server that show the antenna activity and a list of detections found. We understand users often rely on these plots for quick diagnostics after uploading their data and we are working on creating a new method for plot production that is less resource-heavy. At this time, we suggest users use other tools already available on the Motus website:

To see which tags have been detected, please use the publicly available interface in Explore Data > Projects and select the receiver of choice. Please note that short runs are filtered out, so you may not see all tags. For the time being, you will need to download data through the Motus R package to view all your unfiltered data.



To inspect antenna activity, you can review the receiver timeline under Manage Data > Receivers and select 'Edit Receiver Properties' for the receiver of choice. The receiver timeline can be viewed by clicking on 'Receiver Timeline' in the top-right corner.

**Comment by StuMackenzie** [comment]
Please replace ‘users’ with ‘collaborators’ or just change the language so we don’t need to identify anything - we understand these plots are often used for...
