### ISSUE TITLE
Unable to Delete Duplicated Tag Deployments

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#595]
Trying to delete [one of the many duplicated tag deployments in **Project 197**](https://github.com/MotusDev/Motus-TO-DO/issues/594), but the 'Delete (Admin)' option just refreshes the page with no changes. 
https://motus.org/data/project/tags?projectID=197

This seems to only affect _duplicated_ deployments; I can delete deployments as long as there are no others with the same metadata.

**Comment by pmorrill** [comment]
Lucas: I need a link to a tag that has duplicate deployments, if I understand this correctly. Can you post here a tagId where I will find a duplicate?

**Comment by pmorrill** [comment]
This action uses prDeleteTagsDeployment, which attempts to de-link any linked records from det_* tables. I can't see why a duplicate (2 active deployments of the same tag?) will affect this. Catheirne?

**Comment by cjardine-bsc** [comment]
I ran a test on one of the duplicate deployments in the DB and the proc ran fine when given a projectId and TagDeployID

EXEC	[dbo].[prDeleteTagsDeployment]
		@proj = 197,
		@deploy = 24544

It did take a while to execute though, 28min (likely waiting behind some of the delete procs that are running in the det tables). So it may be something to run in the queue instead?

Of course the real solution is to prevent the creation of duplicate deployments in the first place. I'm back at my desk and working through the backlog. I should address that issue today.

**Comment by denislepage** [comment]
If there are 2 overlapping deployment, and we delete the one that was associated with hit records, the other won’t automatically be re-linked. Catherine will need to run the deploy ID proc for the remaining one if not already done.
