### ISSUE TITLE
Overlapping deployment date not caught in bulk deployment upload

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#596]
This was reminded by a recent issue posted by Lucas here: #594, regarding duplicate deployments. 

In this case, the duplicate deployments also had identical dates, which should not have been permitted, but ended up throwing no error.
 
This came up several weeks ago when I got duplicate deployments after uploading a file for project 222. I was trying to update the Lat Lon of deployments that had already been uploaded. There was user error involved: I made the mistake of uploading an outdated deployment file, and not the most up-to-date file downloaded so it lacked the DeployID field.

BUT, all the deployment dates were overlapped completely, so it _should_ have been caught during the process and not permitted into the database. As I understand (from Catherine) there is already a constraint that should prevent tag deployments with overlapping dates from being registered twice. For some reason it still happened in this case.

**Comment by cjardine-bsc** [comment]
Ah, yes. The check for this relied on the deployment status field, which we removed from the upload since it is now auto-calculated based on the dt_start and dt_end. 

I've updated the proc and it should hopefully flag duplicate tag deployments now. If you'd be willing to test that would be good.

**Comment by jsayers-bsc** [comment]
Removed the DeployID and tried to upload Deployments again with identical IDs and Dates.

Validation worked as expected and prevented the duplicate.
