### ISSUE TITLE
"File corrupted on upload" message with successful uploads

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#598]
User from **Project 280** has uploaded data from **12** receivers (separately) and each time has gotten the message:

>  "The file has been corrupted during upload. Please re-zip the file and upload again." 

This message appears on the UI after it finished uploading (not in an email), but those files were still sent for processing. All processed successfully except for one of them that appears to have actually been corrupted and now user cannot re-upload the file because the old one is has been retained on the server:
https://sgdata.motus.org/status?jobID=1801875
 
Project has multiple receivers, but none have deployment names - is that in any way related or problematic? https://motus.org/data/project/recvs?projectID=280

**Comment by denislepage** [comment]
This seems resolved? There is now a 7z version of the file uploaded today, which also reports no issue at my end. https://sgdata.motus.org/status?jobID=1819607

The above log for that file seems all normal. The fact that a few of the 18,000 gz files are corrupted is normal.

The original file was a zip format, which has a standard capacity of 4GB. Interestingly, I was able to run a test on it without problem using 7z software, but looks like Tag Finder wasn't able to deal with that. It may be worth recommending to everyone to use a format not subject to a size limit, such as 7z, in all instances as a matter of standard practice.

**Comment by jsayers-bsc** [comment]
Lucas suggested trying the upload again with a different archive format.

The .7z must have been the new format.

The user also just reported back that it worked.

So yes, that seems to have resolved the issue!
