### ISSUE TITLE
Undeployed receivers not showing up in Undeployed Receivers list

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#600]
Many undeployed receivers are not showing up in the Undeployed tab of the [receivers list](https://motus.org/data/project/recvs?projectID=1#tabs). 

For instance, both SG-67CARPI37819 and SG-F28CRPI33503 are currently undeployed but neither shows up in this list. 

They do show up in the Terminated list, but as they are both registered receivers without an associated active deployment, it seems that they should show in the Undeployed list until they once again have an active deployment associated with them

**Comment by jsayers-bsc** [comment]
Confirmed with several other undeployed serials that they are not showing up in the Undeployed list.

I just registered a new receiver and it did show up there. So it seems that that Undeployed list displays receivers that have never been deployed, rather than any receiver this is not currently deployed. The latter would be preferred I think.

**Comment by denislepage** [comment]
Undeployed means that there are no (and never were any) deployments. The 2 examples had prior deployments, so they can be found under the Terminated tab.

I guess a possible confusion here is that we are not providing a list of all receivers regardless of their status. If you terminate a deployment and want to create a new one, you have to look for the receiver under the terminated tab, which isn’t all that intuitive, or look under the All tab, or search for the receiver ID by serial number, which makes that easier. I would assume most people do the latter.

One addition we should make here is allow searching by site name also and display the site name in the result table.

The “Receiver name” search box is also misleading. I think this needs to be changed to “Deployment name”. We are not allowing to give names to receivers, only sites and deployments.

The table is getting a bit crowded, but I am not sure what I would remove.

While we are on this, I would change the “Edit” link to “Edit deployment” for clarity.

I also think that starting a new deployment isn’t super intuitive at the moment. One has to find an existing deployment for the same serial, click on “Edit Receiver Properties”, and then only can then click on the not so obvious Add deployment button.

Can we improve this?

**Comment by jsayers-bsc** [comment]
Yes the existing “Manage Receivers” page really is a Deployments page, which is confusing. But we also do have a “[Receiver Deployments](https://motus.org/data/receiverDeployment?id=629)” page. The deployments page is buried on the site and doesn’t appear in the menu as you’d expect. It has much of the same information but also contains a summary of tag hits, plus each column is sortable, so it can be quite useful. 

It would be helpful if a receiver that was currently undeployed would show up in the undeployed tab, even if had at some point been deployed. This is useful for knowing how many spare receivers are in play that could be deployed elsewhere. (And actually, the 2 receivers that have never been deployed also show up in Terminated, which seems to be in error given the current sorting.)

I think we could add clarity as well as streamline the workflow by essentially:
- Use the Manage Receivers page primarily for managing the inventory of physical receivers
- Use the Receiver Deployments page for managing deployments (and link to it in the Manage Data menu so folks know where it is)

There are a number of other modifications that could be made to improve the function of these two pages:
- Add Date of Last Data Upload to Receiver Deployments page
- Add the filter options from Manage Receivers to Receiver Deployments
- Change tabs in Manage Receivers to reflect the current status of the physical receiver in question
- Could add a "Create Deployment" button at the top of the Receiver Deployments page 
   - There would need to be a way to search and add from the list of known receivers (or add a new one) since it wouldn't automatically have a receiver associated with it
   - Could possibly also search by deployment name and copy the details to the new deployments 

Some of these may be simple to implement with the existing site, but much of it may be better suited as suggestions for a general site update. Speaking of which, do we yet have a central place for discussing potential changes and upgrades to the site? I know we've talked a lot about dashboards, but there a lot of other potential improvements we could make in how users interact with information the site.

**Comment by jsayers-bsc** [comment]
Apparently there _is_ a page that lists all Receivers in a project, with only one entry per receiver.

[https://motus.org/data/projectReceivers?id=1](https://motus.org/data/projectReceivers?id=1)

I literally only just stumbled upon this page this morning. It's not directly linked to in the menu, though this is what I would expect to find when clicking on a "Manage Receivers" link.

The existing manage receivers page really is a hybrid between the one above that deals strictly with Receivers, and the [this one](https://motus.org/data/projectReceiverDeployments?id=1) that deals strictly with Deployments. 

This page when then be the place to sort receivers by whether they are currently deployed, undeployed, etc

**Comment by pmorrill** [comment]
Originally, the page that we now call 'Manage receivers' was in fact a list of physical receivers along with some information on their most recent deployment ONLY. You had to click through to the 'Receiver Properties' page to actually see all deployments on a receiver, to edit them, or to add a new deployment. In sandbox, this page:

https://sandbox.motus.org/data/project/recvs?projectID=1

Really was a 'manage receivers' page. And deployments were managed for example here:

https://sandbox.motus.org/data/receivers/edit?projectID=1&id=383

The breadcrumbs on the 'Edit Deployment' page still reflect this hierarchical structure. EG:

https://sandbox.motus.org/data/receiver/deployment/edit?projectID=1&id=3560

The argument was made that what people really wanted was to manage their **deployments** easily, so the 'Manage Receivers' page was changed to list ALL deployments, and allow direct editing of those deployments. My feeling has always been that this is messy, and a bit confusing, but I am not a 'user' in this system.

(Note that the 'Manage Tags' pages still reflect the hierarchical structure that originally existed for Manage receivers)

In any case, the change was made, probably too quickly under pressure to get a beta release.  I am all for hierarchical structure, and liked the old system better, though it did require an extra click to actually edit a receiver deployment.

This issue thread probably contains too many ideas to all be in one item, but the over-riding theme is that the 'Manage receivers' page is difficult to use, and somewhat inconsistent in it's presentation of records (which are in fact Deployment records, not receiver records at all).

So: do we want to move back to a hierarchical structure for the pages, where a list of physical receivers is first presented, and you have to click through one of them to then manage the deployments on that receiver? Presumably if we did this, the search function would include matches on Deployment properties (site name, deployment name in particular), and that search would allow for previous (non-current) deployment matches. It gets a little muddy at this point, as to how to list the search results.

Or, are SITES the actual first-level management object? Unfortunately, SITES is a fuzzy concept in our system, as we know.

We need to discuss this on a Thursday call, in some depth. This amount of refactoring would be a beta10 job.

**Comment by denislepage** [comment]
Definitely part of beta10 if we do it, but also part of our possible overhaul of the user interface for CANARIE 3.

We will need a bit more thoughts going into all this.

**Comment by pmorrill** [comment]
Yes - when I say 'beta10' I guess I mean 'canarie-3' :)

Let's discuss then create some new git issues addressing specifics. I am looking at what can be improved in the short-term (beta9), in terms of suggestions made above.

**Comment by jsayers-bsc** [comment]
Thanks for that context, Paul. That helps to understand the current format.

I definitely have a lot of thoughts and suggestions from a couple months of heavy use of the site. I’ve been keeping general notes both on paper and in my head as I’ve gone along regarding features and changes that I think would be improvements. Call it a wish list :). No point further muddying the waters here with more items in this one issue so maybe what I’ll do is formalize it a bit more and either start a separate issue later or present it in another format if that works better

**Comment by pmorrill** [comment]
Sounds good. I am making some changes to the existing interface, to add table-column sorting, and a few other suggestions above. I will let you know when that is ready to look at (probably in sandbox first). These changes will not solve all the issues, so next step is to concoct a plan to improve usability, as part of the Canarie-3 proposal.
