### ISSUE TITLE
Adding Software version to Deployment record

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#602]
The Deployment, as you all know, is basically a combination of the receiver plus the properties that affect how that receivers will detect tags.

Those properties should not change across the lifetime of a Deployment, and if the properties do change, we create a new Deployment to capture the change.

Perhaps we should be keeping track of Software versions / updates as well in these deployment records? Changes in the software could conceivably affect receiver performance and we have quite a few different versions out there. We aren't tracking this anywhere at the moment and it may even help to identify issues that only affect a particular software version, or a combination of receiver type and software version. 

Just putting that out there. Maybe it's already been discussed...

**Comment by leberrigan** [comment]
There doesn't seem to be much of a difference between software versions when it comes to the SG's ability to detect tags. These updates address device compatibility and bugs as well as connectivity to the SGData server.  The only value I can see in knowingthe SG software version is when we're trying to debug issues that are reported to us (i.e.: networking, dongle compatibility, etc.) in which case we just ask the users to check the software version. The one exception is the old software version of the BB White that didn't increase the monotonic boot number, but it's too late to do anything about that now...

That being said, it's very possible it will be more important to have software version reported in the future. I wonder if we could keep track of this by including the software version in the downloaded SG data. It could be part of the file name or included in a log file that has other info like parameter changes, etc.

**Comment by jsayers-bsc** [comment]
Yes definitely some troubleshooting advantages. For instance we currently have a number of receivers that do not show the “Live tags” section in the web interface, which is incredibly useful in confirming that a station is being left in working order. That may be related to a particular software version but it’s hard to say.

It’s actually not just primary software version. There are patches and updates that affect various aspects (connectivity, CTT compatibility, etc) that may often be relevant. Which of these is installed doesn’t seem to be available anywhere, other than to look at the timestamp on the “used_sensorgnome” file and see if it matches up with any of the known patches/updates.

Recording the information somewhere would also make it easier to ensure that software is up to date, that relevant patches have been applied where needed etc. Deployment may not be the place for it; maybe it would be better associated with the device itself, or in the file output name. An excel file seems much less desirable, though that is another option.

This may, like many of the other topics I bring up, be mostly relevant to the Ontario array or other projects with a large number of stations. We can easily inquire other users about that status of a particular receiver, but if we are also the user and we have 100 receivers out there, a better way of organizing and tracking would be useful.

**Comment by denislepage** [comment]
There are probably several dozen version numbers to possibly track (most of them probably wouldn’t be relevant), from firmware for each devices to sensorgnome, to any number of dependent packages. Tracking individual custom settings in some cases might be more relevant. Use of filters, parameters used, etc. Which one do we mean? Clarifying the purpose would likely help.

It’s not a bad idea in principle, but it’s not necessarily simple.

I think that adding some of that in the data files would be my preferred approach. We’d also have to make modifications to tag finder if we wanted to feed those into the database.

**Comment by jsayers-bsc** [comment]
A couple practical uses I had in mind when originally posting were:

-  What software version is receiver X running? — the most recent one or one a few years old
- Which receivers have had the CTT compatibility patch installed and which still require it?
- Does there appear to be a particular software/patch present every time we encounter issue Y?

Though my the sounds of it this may be one of those things that would be useful but isn't worth the effort the implement...



------ Original Message ------

**Comment by jsayers-bsc** [comment]
May be covered by some of Dale's work with the new images, but isn't as big a deal in retrospect. Ensuring the most recent software is installed is a first step to most troubleshooting.
