### ISSUE TITLE
Project 4 manual tag registration/recovery 

### ISSUE THREAD

**Issue by adamdsmith** [MotusDev/Motus-TO-DO#603]
One of our refuges deployed 10 tags without first registering them. I’m hoping we can register them by extracting their pulse information from deployed receiver data. They would have been deployed at or very near station deployment 5062 on the evening of 26 October 2019 (America/New_York).

The [tag information from Lotek is also attached](https://github.com/MotusDev/Motus-TO-DO/files/3809257/lotek.082319.pdf).

Sorry for the inconvenience.

**Comment by denislepage** [comment]
I think we should try to add a database proc to allow manually registering tags based on expected values for a given number. Catherine?

If we have the tag mfgID, the model and the expected burst interval, that will be enough in most cases. We make the assumption that the tag properties match the base codeset. It’s a small gamble, but manually extracting the values from the detection data is probably too onerous for us to offer, and most often not necessary.

If all goes well, manual tags registrations may soon be a thing of the past, anyway. Let’s hope.

**Comment by adamdsmith** [comment]
I’m satisfied with this option. I think you’ve alluded to it in other places, but the tagfinder’s permitted burst slop allowance will probably cover deviations from nominal burst intervals in most cases.

**Comment by cjardine-bsc** [comment]
For once I'm ahead of you D-boss. The proc is called prTagManualRegistration 

It needs the following parameters: 
@mfgID
@projectID
@period
@model
@nomFreq

Adam, if you can provide a spreadsheet of those values for your 10 tags I'll get them registered for you.

**Comment by adamdsmith** [comment]
Catherine,
[Spreadsheet attached](https://github.com/MotusDev/Motus-TO-DO/files/3816136/Mackay_unregistered_tags.xlsx). Thanks!

**Comment by cjardine-bsc** [comment]
Thanks, you should now see those in your project.
