### ISSUE TITLE
Beeper Tags?

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#605]
What's the status on these? The Sensorgnome website says it's compatible with them, but we don't have any registered to Motus as far as I know: 
https://archived.sensorgnome.org/Automated_VHF_Telemetry/1._Tags/Using_beeper_tags_with_a_SensorGnome/

I'm assuming we don't have that capability, but perhaps that doesn't matter so much. From what I understand, researchers can more easily interpret the raw data since these aren't digitally encoded tags.

There are some nifty tags out there that use a similar frequency so this is just a general inquiry about the feasibility of using the same infrastructure.
https://www.lotek.com/wp-content/uploads/2019/01/Core-Implant-Series-Spec-Sheet.pdf

**Comment by StuMackenzie** [comment]
Most beeper users do their own thing. I don't think it's worth our effort to provide any support for beepers at this stage. I'm sure it's all possible.

**Comment by Hussell** [comment]
There's code in the tag finder for dealing with beeper tags, because the output in the files is different than for normal tags, but beyond that I don't know anything.

**Comment by denislepage** [comment]
I'm fine with not supporting those. Is anyone asking?

**Comment by leberrigan** [comment]
Someone wanted to use Nanotags on snakes and I suggested beeper tags. Just thought I'd check to make sure they weren't compatible with Motus.

**Comment by StuMackenzie** [comment]
We still need some closure on this as some 'users' or people are using beeper tags with sensorgnomes and we have assumed some responsibility for that.

It is worth understanding how this works, and providing updated instructions where our new documentation resides. We should even test to make sure it actually works as intended, and discuss if there are any examples within the database of people registering tags with us under frequencies other than the normal ones. I know a bunch of projects have used beepers for whatever reason, but I’m not aware of them going through Motus to do so. 

See - https://github.com/MotusDev/Motus-TO-DO/issues/605 for not much info beside our agreement not to support them in the Motus context. 

However, if sensorgnomes handle this functionality, and users want to use them independently I see no reason not to ‘allow’ it and provide instruction.

The big unknown is whether the tags need to be registered and how they’ll get their data back? I’m particularly concerned if the project using them currently can actually get what they want out of it. 

I’ve never used them, or paid much attention, so I don’t know the answer to this.
