### ISSUE TITLE
Server Not Responding - from Motus Group

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#606]
| Server Not Responding (show original)   5 Nov (17 hours ago)     Hello,I am trying to update detection data and R keeps stating:Checking for new data in project 47 Project    47:  got   242 batch records batchID   665203 (#     1 of    242): got      1 runs starting at               0 batchID   665203 (#     1 of    242): got      2 hits starting at               0 batchID   665216 (#     2 of    242): got      7 runs starting at               0 The server did not respond within 120s. Trying again... Error: The server is not responding, please try again later.  Is  anyone else experiencing this same issue?  Is there maintenance  occurring on the motus server?  Or is this something on my end I need to  fix?  Thank you.
-- | --

**Comment by steffilazerte** [comment]
This also reflects a timeout of 2min (120s) that I implemented in the motus package back in July. Although if that was the problem I would have expected it to crop up earlier in August when we released motus package v2.0

**Comment by denislepage** [comment]
I fixed the  proc that delete batches yesterday. That was likely causing the hang-ups, and things are now deleting much faster.
