### ISSUE TITLE
Motus in the News

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#608]
Can we dream up a way to make this page more effective and up to date? I think keeping a list of everything is unnecessary. 

Or, maybe remove it until we know what we to do with it. Doing so manually isn't really realistic? 

There may be a more creative, meaningful, or visually appealing ways to display info to the [google search results ](https://www.google.com/search?q=Motus+Wildlife+Tracking+System&client=firefox-b-d&sxsrf=ACYBGNRzRrjucKxYylzjhtzayGipjVulzA:1573076227538&source=lnms&tbm=nws&sa=X&ved=0ahUKEwjzxvzNxdblAhXPJt8KHUETB1kQ_AUIEigC&biw=1198&bih=673&dpr=1.25 )

Maybe just a snapshot of recent stories, or highlights?

**Comment by leberrigan** [comment]
We can use a RSS aggregator and just automatically show any news items in the 'Motus Widlife' Google News alert.  That wouldn't let us chose what shows up in the list, but I'm not sure how much that matters.
https://www.google.com/alerts/feeds/07692776860739222990/10874057592527579878

**Comment by StuMackenzie** [comment]
If there are no other ideas or suggestions, I suggest we implement this for the time being. It beats having an out of date or incomplete list.

**Comment by denislepage** [comment]
If you can, include an exclusion for MOTUs (molecular operational taxonomic units or something).

E.g.

Motus Wildlife -taxonomic

Or
Motus Wildlife -molecular

Those combinations should be rare in relevant papers.

**Comment by leberrigan** [comment]
I hit a snag while trying to add the RSS feed and then got sidetracked. I'll keep on it, but it may be more complicated than it should be (stupid Google).

**Comment by leberrigan** [comment]
Alright, I think I figured it out.

I have an Google News RSS feed for **motus wildlife -"molecular operational taxonomic units"** posting to https://beta.motus.org/news.

Unfortunately, Google News no longer includes thumnail URLs nor text snippets in their RSS feeds. That means we can only display the title and date for each article, as you see on the webpage.

An alternative would be to use a different source for news, like Bing, but I don't know if anything will suffice. For instance, Bing News has _zero_ results for 'motus wildlife'. Why do they have to suck all the time?
