### ISSUE TITLE
How many active Motus stations do we really have?

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#611]
This number keeps creeping up higher and higher and I don't trust it.

Can we share the exact definition of what this is based on?

I think it should only reflect unique stations that are active at 'this' moment in time, not that were ever deployed.

**Comment by cjardine-bsc** [comment]
Currently there are 906 sensors in the deployment table where dt_end is null and test is 0. 

SELECT * 
  FROM [motus].[dbo].[sensor_deployments]
  where dt_end is null and test = 0 

So, it doesn't seem too far off. Though people not closing deployments is probably inflating this number. 

Jeremy, I don't see where the motus by the numbers page is pulling the 919 value from, it's not adm_platform_stats, what table are you using?

**Comment by Hussell** [comment]
select count(distinct a.receiverID)
from vwData_receivers_deployments a
where a.accessLevel < 3
and a.deploymentStatus = 2

**Comment by leberrigan** [comment]
Plotting deployments over time, there seems to be a steady increase of just over 1 new receiver every 3 days. It looks like there are fewer deployments ending in the winter as the years go on, but maybe that's just because we're getting more partners down south?
![nRecvs](https://user-images.githubusercontent.com/35931796/68481365-632dd580-020d-11ea-9800-09a0f9108016.png)

**Comment by leberrigan** [comment]
![nrevs_ani](https://user-images.githubusercontent.com/35931796/68701636-95b53680-055d-11ea-9c05-743e6ca7f835.gif)

**Comment by Hussell** [comment]
The animation above can be reproduced on the website's receiver map by setting "Show active antennas by month" and dragging the slider. Once focus is on the slider you can also manipulate it using your keyboard, e.g. left and right arrow keys, Home key, or End key.

https://motus.org/data/receiversMap

**Comment by Hussell** [comment]
Ping

**Comment by StuMackenzie** [comment]
This is fine, but at the mercy of up to date # metadata.
