### ISSUE TITLE
Receiver rerun for previously unregistered tags

### ISSUE THREAD

**Issue by adamdsmith** [MotusDev/Motus-TO-DO#613]
Please rerun receiver deployment 5062. Several unregistered tags were deployed on 10/27/2019, causing many false positives from lots of other projects. [Catherine registered the tags manually using manufacturer specs on 11/6](https://github.com/MotusDev/Motus-TO-DO/issues/603).

It's conceivable these tags have been detected elsewhere as well, though not with high probability.

**Comment by Hussell** [comment]
Done. Some of the newly registered tags have detections now.

Note: the next scheduled rerun of the affected data would have been in the 2nd week of January.

**Comment by adamdsmith** [comment]
Thanks Jeremy
