### ISSUE TITLE
All tags tested/detected on deployment 5520 should be labelled as test tags

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#617]
https://motus.org/data/receiverDeploymentDetections?id=5520

**Comment by jsayers-bsc** [comment]
Do we know what the deal is with these then? The one is labelled as species TRES.

**Comment by StuMackenzie** [comment]
They were all used as test tags from the various projects. species can be removed if present and all flagged as test tags. 

This is an example of brut force cleanup that we need to start doing whenever we see things that are fishy.

**Comment by jsayers-bsc** [comment]
There's a band number recorded for the TRES band. Maybe this had been deployed then recovered and reused with ending the previous deployment? https://motus.org/data/track?tagDeploymentId=26388

The SORA project tags are already labelled as test actually, though that isn't visible without editing the tag.
