### ISSUE TITLE
Unable to select L- antenna ports in SensorStation

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#618]
This may just be a "not yet implemented" as this was discussed on a call recently. But anyway:

I'm trying to add test deployments for some CTT SensorStations. The built-in 434 MHz ports are labelled with an L prefix. As I recall, that L prefix on the port is important when handling data later as it is one way of identifying CTT data.

Currently though, the only port values that are accepted are integer. If I type in L1 for instance, the option to specify dongle type (which would always be CTT Integrated) or frequency (which would always be 434) is greyed out.

For now I've been leaving them unpopulated entirely as they are test deployments.

But what's the best option here? Should we specifically designate L1 as the port in the deployment record (and if so, are pre-populated dropdowns a way of ensuring proper formatting?). Or should we just stick to integers 1-x? That raises its own issues since it would cause confusion between say L1 and port 1 since the remaining 7 USB hubs are labelled 1-7. 

![2019-11-15 11 15 20](https://user-images.githubusercontent.com/55001144/68992926-dfdd3700-083f-11ea-94a2-07d471742c30.jpg)

**Comment by denislepage** [comment]
Yes, CTT ports on SensorStations must have the L prefix in the metadata. Integers are reserved for USB ports (or Lotek SRX).

The other fields may need a slight adjusting to display the correct values when L is used (434 Mhz and CTT integrated).

This will have to be clearly communicated to users, somehow.

**Comment by jsayers-bsc** [comment]
Currently the L prefix ports aren't entirely supported in the Deployment page. There appears to be a constraint that only permits selecting dongle type if the value in the Antenna field is an integer. You can work around it by selecting the dongle type first, then entering the L1 antenna. However, upon saving, the selection reverts again, and further changes are not permitted.

![image](https://user-images.githubusercontent.com/55001144/69063877-405ca780-09eb-11ea-8a9b-39e2f8933c07.png)

Also,[ the issue of frequency selection reverting](https://github.com/MotusDev/Motus-TO-DO/issues/612#issue-521215634) is present with these as well. Seems to revert to whatever frequency was first selected in the first antenna port. The changes stick the _second_ time it is saved.

**Comment by pmorrill** [comment]
OK - must have got our wires crossed. I understood that dongle selection was only relevant to the USB ports? That is why the greyed out dongle selection dropdown.

**Comment by StuMackenzie** [comment]
I think you're correct @pmorrill . Dongles are only relevant to USB ports. Perhaps @jsayers-bsc was trying to do something else? Not sure what we would ever put in as a dongle in an L port.

**Comment by jsayers-bsc** [comment]
Yes an L port will only ever be a CTT Integrated “dongle” so it could be greyed out if CTT Integrated is pre-selected.

Regarding clarity, we’ll have to also try to make it clear that the port refers to the connection point into the computer board, and not the entry point into the case. That really isn’t a source of confusion with the SG but since the SensorStation already has 5 antenna bulkheads installed and connected via the L ports into the CTT integrated receiver/dongle, people may confuse the two.

On dual mode stations some of those existing bulkheads will be disconnected and reattached to a FunCube dongle, and then into a USB port, potentially causing confusion about which port is being used.

**Comment by StuMackenzie** [comment]
I think making 'CTT Integrated' the default for L ports would provide clarity in this instance.

I would hope that collaborators never us an L port for anything other than CTT antenna.

**Comment by pmorrill** [comment]
I think what happened is we thought first we'd just add the option to the dropdown list, but then decided it was confusing. Catherine added it while we were on the phone (c=efficient), but by the time we finished we' d decided to just leave it blank for those 'L' antennas. I set up the jscript to disable the selection for them, to enforce that.

I will take another look at where this stands when on Motus duty tomorrow. The frequency field is a problem too, I gather?

**Comment by StuMackenzie** [comment]
Frequency should probably default to 434 MHz for now. In the future we may need to customize, but not any time soon.

**Comment by pmorrill** [comment]
In beta9, I have removed the disabling of the dongle field for 'L' prefixed ports, and set default to 'CTT Integrated'. I have also set the default for 'freq' to 434.00.

Test tomorrow in beta server.

**Comment by jsayers-bsc** [comment]
Just gave this a whirl.

Typing L1 or any other L port automatically populates with both CTT Integrated and 434 MHz. 

However upon trying to save I got an "invalid port" error.

![image](https://user-images.githubusercontent.com/55001144/69447444-8637a980-0d24-11ea-9d0b-21b8054a68a6.png)

Additionally, what about the following two suggestions:

- L ports are defaulted to 434 / CTT integrated as they are now,  **and then** greyed out so that further changes cannot be made with that port type.  When users disconnect this antenna port to plug in, say a 166 antenna and FunCube, they will then be plugging that FCD into one of the USB ports, and it will be _that_ port that the computer affiliates incoming pulse data with.

- Is there any benefit to providing a dropdown containing the various antenna options, especially the L ports?  I can see a lot of potential confusion over what port number to use, even in cases where people are leaving the 5 antenna bulkheads attached to the 434 antennas. You can't see it in the original image but above the L port labels is another label with just the number, exactly as you'd expect to enter it in the deployment record (the other USB ports on the SensorStation are actually labelled USB1 - USB7). I've attached another pic closeup to give a sense for how easily one might get those mixed up.

![2019-11-22 12 44 14](https://user-images.githubusercontent.com/55001144/69448457-92246b00-0d26-11ea-9781-e61b044a2d0e.jpg)

**Comment by pmorrill** [comment]
@jsayers-bsc did you test the L port on a SENSORSTATION receiver? The message that you saw would normally be delivered if you tried to enter a L port on a non-SENSORSTATION. 

Regarding your other points, I hesitate to make it more sophisticated at this point, for the effort required (as you likely no, if I disable the dropdown, the value will not make it back to the server, so I will have to insert code there to set up SENSORSTATION defaults and get the correct values into the db record).

But this is all part of our CANARIE-3 work-over, I believe. So it should be registered as an enhancement on that list.

**Comment by jsayers-bsc** [comment]
Yes this would have been a SensorStation.

Ah, yes I see...

**Comment by pmorrill** [comment]
I have tested this and it seems to accept L ports, up to 5 only, and only on sensorstation deployments, and I checked that the lk_ant table holds the full set of possibilities:

1 - 8 for non-sensorstation deployments
and
L1 - L5 added for sensorstation deployments

Can you post the link to the actual deployment where this failed to work (or send it by email)?

BTW: I am in favour of a dropdown, but there was some discussion about this and we did not implement. I cannot recall why not. It seems pretty straight-forward.

**Comment by pmorrill** [comment]
OK - @jsayers-bsc you have convinced me. I looked it over and have made a few updates to meet your requests above. See the beta server after the next deployment. It will need testing carefully:

a) New port selection is now a dropdown
b) for L ports, the dongle-type and frequency are both disabled on new antennas

**Comment by jsayers-bsc** [comment]
It was this [deployment here](https://motus.org/data/receiver/deployment/edit?projectID=1&id=5816).

I just tested several times again to add and remove additional antennas.

In beta, I can see the dropdown and automatically populated frequency and dongle for L ports. Awesome. 

In live, there is no dropdown for ports , though that's likely just because the changes haven't been pushed there yet. But there is no error when adding an L port though, so that's good!

However, in both Live and Beta, the frequency of the L port reverts to 166 following the save if the frequency selection is still 166.38 instead of Multiple (as it was when I first tried modifying these). This only happens when adding a 434 antenna to a previously all-166 deployment (adding a 166 or other frequency to a previously all 434 deployment requires a manual change of the deployment Receiver Frequency setting).
[
Actually, I see now that changing the Receiver Frequency for the deployment will overwrite either the antenna frequency with the new value, though that only happens in Live.](https://github.com/MotusDev/Motus-TO-DO/issues/612)

**Comment by pmorrill** [comment]
The changes have not been moved to live, so base your testing in the beta server, definitely. We won't deploy to live until we are satisfied.

The multiple mode is always a bit problematic, but I will look again at what you report above. If the mode is not 'Multiple' then the frequency selection option should be disabled for new and existing antennas. That might solve part of this, but I had thought it was set up that way already.

But if someone switches away from 'Multiple' (selecting some specific frequency) then yes, the frequency values will be over-written. That is what the user is specifying, after all.

**Comment by pmorrill** [comment]
I have updated this so that if 'Multiple' is showing on the deployment, it is disabled so not possible to switch back to a specific frequency. This heads-off the over-writing issue. It prevents a cttIntegrated port from reverting to something other than 434. 

Secondly, if you leave the frequency selection on a specific port, then add a 'L' port to the deployment, the L port will have it's frequency set to 434, and the deployment frequency will switch to 'Multiple' when the browser refreshed after the Save operation.

Changes available after next deploy to beta / sandbox

**Comment by StuMackenzie** [comment]
2. The text fragment for Port "(USB (0-255)" makes no sense. Should probably read (0-9)?

**Comment by ajmacdonald3** [comment]
I found that when starting an new deployment, there were no L-port options (only 0-9), but when editing an existing deployment, I could add new antennas (or modify existing ones) as L-ports (L1-L5). But yes, this was not immediately obvious, took a bit of playing around to figure out. So for new deployments, I added the USB ports fr 166 frequencies, saved it, then went back and added the L ports for 434 frequencies. It would be much clearer if they were available right at the start - maybe "create new deployment" just hasn't been set up quite the same way as "edit deployment"?

**Comment by pmorrill** [comment]
Sounds like a bug, yes. The option is based on the receiver type being sensorstation, so the create tool should be able to support the L options. I will take a look.

**Comment by denislepage** [comment]
In theory, you can use a USB hub with a very high number of ports. In practice, we are limiting the options available. There’s no theoretical limit to go above 9 (or whatever is the limit we picked), but we’d have to tweak our interface to support it.

**Comment by mmwebb** [comment]
> 1. When I added a deployment today, I was only presented with the port options 0-9. (no "L" SensorStation options). Now, perhaps I didn't do something 'properly', but the point is more that if it didn't work for me, it won't work for others. I played around with a bunch of different options, but they never came up as an option.

This problem still persists, causing some stations to have ports selected incorrectly.

**Comment by denislepage** [comment]
Interesting. Did the changes we made a while back get reversed @jhussell @pmorrill. We did add support for the L ports a while back.

**Comment by pmorrill** [comment]
This issue - whereby the options for L ports were not present when creating a  NEW deployment - has not been fixed. I was looking at it Thursday morning but it'll be next week before I can re-visit.

**Comment by pmorrill** [comment]
I have put a fix into master and beta9 branches for this issue. It should be tested after the next build, then to live.

**Comment by jsayers-bsc** [comment]
@pmorrill This seems to work fine in beta; L ports are now selectable without having to first create a deployment.
