### ISSUE TITLE
Website - Drop-down menus don't work on mobile device

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#620]
Don't work on a phone. Haven't tried an ipad.

**Comment by leberrigan** [comment]
On my phone  I can get the menus to drop down by long-pressing the menu option. In general, though, this is a very mobile-unfriendly site.

We may want to rethink this menu all together. The design is outdated and link items don't match content on the pages.

There are many designs for website menus, but most major sites no longer use drop down menus (unless it's a store). This helps simplify and streamline the website and I think we can easily follow suit.

Removing the drop down options does introduce an added line of clicks, but I think that will have a minimal effect if we organize properly and put more content on each page. As long as content is 1 or 2 clicks away we should be good!

**Comment by StuMackenzie** [comment]
Mobile friendly has long been identified and known as an improvement we need to make.
