### ISSUE TITLE
Private Tracks Visible to Public

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#621]
I stumbled upon the track of a Kirtland's Warbler while _logged out_ and noticed that while none of these tracks can be found by navigating through 'explore data', users can still view these tracks if the correct deployment ID is typed into the address bar.
https://motus.org/data/track?tagDeploymentId=20801

These data are listed as visible to logged-in users only.

**Comment by StuMackenzie** [comment]
Just wish this data wasn't hidden to begin with...
