### ISSUE TITLE
Tag Deployments With Obviously Incorrect Species

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#622]
This is an extension of the discussion in #425 about test tag deployments, but in this case I'm talking about deployments **not** listed as a test.

Liza pointed out **Project 288** to me where they have Topknot Pigeons (10) and Ruby-topaz Hummingbirds (32) deployments starting in **Sep 01 2019**: https://motus.org/data/projectTagDeployments?id=288

What do we do in these instances and how do we catch them in the future?

**Comment by Hussell** [comment]
Doing a quick scan over the table of species looking for weird ones can find many of these rapidly, so long as you double-check that the species isn't just something normal being tagged in Australia which you happen to be unfamiliar with.

https://motus.org/data/species

What to do with them? I don't know. In this case, all the deployments were entered with future dates, so there's an issue for each of them on the Data Issue page for the project. If the researchers are in the field or on vacation and haven't had time to update the metadata, is that even a problem we should be concerning ourselves about?

**Comment by StuMackenzie** [comment]
Generally, Yes. Any obvious incorrect data needs to be corrected with brute force if even just reverting them to 'unknown' by default if they're a known error. In the the case of project 245 - they're all wrong.

In terms of catching them in an automated fashion, I'm not sure it's possible.

However, if these were set at the time of registration it is avoidable. I will state my strong opinion again that I don't think that collaborators should be able to designate species until the tag has actually been deployed. I don't see one benefit aside from the illusion of convenience to the collaborator.

**Comment by Hussell** [comment]
It looks like I can't correct this through the web interface, so I guess this is a job for Catherine.

32 Ruby-topaz Hummingbird in project 288
10 Topknot Pigeon in project 288

Probably also needing nullification:
2 White-tailed Emerald in project 152
4 Human (man) in project 113
6 Rufous-browed Conebill in project 194
21 Melanesian Kingfisher (Dampier Straits) in project 162

**Comment by Hussell** [comment]
For Paul: for future deployments can the species be set to null no matter what the input is?

**Comment by cjardine-bsc** [comment]
I can change that in the database proc. But really we should remove it from the upload options and instructions during tag registration so users do not expect it. 

Why can't you change the species on the web interface? Do you need to change the date start at the same time for that?

The ones on Human (man) probably need to be set to test deployments no?

**Comment by Hussell** [comment]
> I can change that in the database proc. But really we should remove it from the upload options and instructions during tag registration so users do not expect it.

Right, that's the sort of thing I was thinking would be easiest for Paul to do.

> Why can't you change the species on the web interface? Do you need to change the date start at the same time for that?

Right, the interface won't let me update anything without also updating the start date, for reasons which aren't relevant. I've encountered a couple of these situations now, where I'm trying to fix one thing and it's prevented because something else is also in a bad state. Submission should only be prevented when we detect new input that's wrong, not when unmodified fields are wrong, because a lot of the time the unmodified fields can't be fixed until later. Warning messages every time you submit and an unmodified field is wrong are good, just don't prevent other things from being updated.

> The ones on Human (man) probably need to be set to test deployments no?

If they were actually deployed on people walking around, then yes. Otherwise, no. The former possibility didn't occur to me earlier, and I don't know what was actually done, so best to leave those alone, I guess.

**Comment by pmorrill** [comment]
Adding support into our base MotusBean, to allow tracking WHICH fields have actually been modified and only validating those on save, is a potential CANARIE-3 enhancement. It would improve usability for all the reasons mentioned above. It is not trivial, but we can figure something out at the java level.

**Comment by cjardine-bsc** [comment]
Heya, 

The lock on editing species is based on the concept of confirm_dt_start. Removing the ability to assign species during tag registration should be all we need to do.

**Comment by cjardine-bsc** [comment]
Heya, 

The lock on editing species is based on the concept of confirm_dt_start. Removing the ability to assign species during tag registration should be all we need to do. I've taken out the speciesID and speciesName from prAPIImportTagDeploymentsTransfer. Species will no longer be assigned when registering tags. 

As for cleaning up the existing problems, I've removed the issues from project 288. And set the "human" deployments in project 113 to "test". The last three are below. The word "probably" gives me pause. Can we confirm with certainty that the species ID should be removed for these three?

Probably also needing nullification:
2 White-tailed Emerald in project 152
6 Rufous-browed Conebill in project 194
21 Melanesian Kingfisher (Dampier Straits) in project 162

**Comment by Hussell** [comment]
Project 152 is New York Lake Plains Motus.
Project 194 is Common Nighthawk/Eastern Whip-poor-wills.
Project 162 is Western MA Tree Swallows.

White-tailed Emeralds are hummingbirds found only in Costa Rica and Panama.
Rufous-browed Conebills are similar to tanagers and found only in Colombia and Venezuela.
Melanesian Kingfishers are, obviously, not Tree Swallows, nor found in western MA.

The "White-tailed Emeralds" both have deployment dates of 2019-05-15.
The "Rufous-browed Conebills" all have deployment dates of 2019-05-16 and the start dates were saved when they were in the future.
The "Melanesian Kingfishers" all have deployment dates of 2018-06-01 and the start dates were saved when they were in the future.

Nothing is certain, but I'm not worried about nullifying these.

**Comment by StuMackenzie** [comment]
I think nullifying is fine. @jsayers-bsc can follow up with each telling them what changes we've made.

**Comment by cjardine-bsc** [comment]
I am comforted. 

Nullification complete. 

Close-ity close!

**Comment by Hussell** [comment]
Reopening to help Paul keep track of this task.
