### ISSUE TITLE
Duplicate data Project 74

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#623]
Duplicate data present, but off by one hour. 

Waiting for confirmation of station ID, project, etc. 

I am having some issues when plotting flybys of several birds near my towers. Im seeing identical replicates of the detection patterns of signal strength vs time as shown in the plot attached below. Ive been able to figure out which one is most likely correct given previous and subsequent redetections but I'm wondering if anyone else has this issue and knows why it may be happening? I want to make sure I am recording the correct flyby time. 

Thanks!
Jess Tatten (Ruebesam)
MSc Candidate 
Dept. of Environmental Conservation
University of Massachusetts, Amherst
Attachments (1) 
	
![image](https://user-images.githubusercontent.com/21124211/69238628-707c8580-0b66-11ea-9e7e-e9a0b8bafb06.png)

**Comment by leberrigan** [comment]
Looks like daylight savings to me...

Jess is registered to project 74 which mostly just has data from Lotek receivers.
https://motus.org/data/project/recvs?projectID=74

Still waiting on a response for station ID.

**Comment by StuMackenzie** [comment]
I think it may be an updated package issues - she's using old data, but we should check. See below.

I agree on daylight savings issue, but the duplication is the issue. Duplicates exists in two different time zonee.

From Jessica:

Stu,

Thanks for the prompt reply. It seems that a few of my towers are doing this. I looked through my 2015 data and found that its happening most frequently on:

MountToby : deployment id 2508
FortRiver: 2504
Wantastiquet: 2515

When trying to plot some of the data and conduct my movement analysis, those three for some reason were missing their lat/long coordinates, so I manually added the coordinates into the data frame. 
I think that may be the problem actually, because in each season, the coordinates of the towers I added in are the ones that are causing problems, but Im not sure how to get around that because if I dont manually add them in, I cant calculate distance between towers for movement analyses. 

I could try redownloading the data, but right now I'm working with the old format of motus data in R and havent redownloaded since my analysis was started because I would have to reformat all of my code and relearn everything, which I plan to do eventually,  but dont want to mess with the analyses Ive already conducted. 
Any advice would be greatly appreciated!

Thanks,
Jess Tatten 

![image](https://user-images.githubusercontent.com/21124211/69285385-c7ae4480-0bbe-11ea-9b23-f49aac406e23.png)

**Comment by leberrigan** [comment]
The updated packages aren't compatible with earlier versions of the Motus database so I don't think that's the issue.

I have an example here from **receiver deployment 2504** and **tag deployment 1951** where the data is from the same 'batch' and the 'tsCorrected' columns are exactly 1 hour apart. I might need to do a bit of digging, but I'm guessing this is the result of multiple data downloads from a Lotek receiver with the wrong timezone.
![proj74-FortRiver](https://user-images.githubusercontent.com/35931796/69287779-dbad7280-0bcd-11ea-8754-429c3add3f89.png)



**First set of data - Starting 19:11:00 HRS**

  | hitID | runID | batchID | ts | tsCorrected | sig | sigsd | noise | freq | freqsd | slop | burstSlop | done | motusTagID | ambigID | port | runLen | bootnum | tagProjID | mfgID | tagType | codeSet | mfg | tagModel | tagLifespan | nomFreq | tagBI | pulseLen | tagDeployID | speciesID | markerNumber | markerType | tagDeployStart | tagDeployEnd | tagDepLat | tagDepLon | tagDepAlt | tagDepComments | fullID | deviceID | recvDeployID | recvDeployLat | recvDeployLon | recvDeployAlt | recv | recvDeployName | recvSiteName | isRecvMobile | recvProjID | recvUtcOffset | antType | antBearing | antHeight | speciesEN | speciesFR | speciesSci | speciesGroup | tagProjName | recvProjName | gpsLat | gpsLon | gpsAlt
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 4.5E+08 | 24550046 | 370625 | 10/7/2015 19:11 | ######## | 42 | 0 | -96 | 4 | 0 | 1.00E-04 | 0 | 1 | 15554 | NA | -1 | 7 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | NA | NA | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA
2 | 4.5E+08 | 24550046 | 370625 | 10/7/2015 19:11 | ######## | 44 | 0 | -96 | 4 | 0 | 1.00E-04 | -0.0033 | 1 | 15554 | NA | -1 | 7 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | NA | NA | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA
3 | 4.5E+08 | 24550048 | 370625 | 10/7/2015 19:11 | ######## | 44 | 0 | -96 | 4 | 0 | 1.00E-04 | 0 | 1 | 15554 | NA | 1 | 10 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | yagi-9 | 3 | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA
4 | 4.5E+08 | 24550048 | 370625 | 10/7/2015 19:12 | ######## | 45 | 0 | -96 | 4 | 0 | 1.00E-04 | -0.0033 | 1 | 15554 | NA | 1 | 10 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | yagi-9 | 3 | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA
5 | 4.5E+08 | 24550046 | 370625 | 10/7/2015 19:12 | ######## | 49 | 0 | -96 | 4 | 0 | 1.00E-04 | -0.0022 | 1 | 15554 | NA | -1 | 7 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | NA | NA | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA
6 | 4.5E+08 | 24550048 | 370625 | 10/7/2015 19:12 | ######## | 50 | 0 | -96 | 4 | 0 | 1.00E-04 | -0.0021 | 1 | 15554 | NA | 1 | 10 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | yagi-9 | 3 | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA
7 | 4.5E+08 | 24550049 | 370625 | 10/7/2015 19:12 | ######## | 48 | 0 | -96 | 4 | 0 | 1.00E-04 | 0 | 1 | 15554 | NA | 3 | 7 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | NA | NA | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA
8 | 4.5E+08 | 24550049 | 370625 | 10/7/2015 19:13 | ######## | 47 | 0 | -96 | 4 | 0 | 1.00E-04 | 2.00E-04 | 1 | 15554 | NA | 3 | 7 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | NA | NA | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA
9 | 4.5E+08 | 24550046 | 370625 | 10/7/2015 19:13 | ######## | 57 | 0 | -96 | 4 | 0 | 1.00E-04 | 3.00E-04 | 1 | 15554 | NA | -1 | 7 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | NA | NA | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA
10 | 4.5E+08 | 24550048 | 370625 | 10/7/2015 19:13 | ######## | 60 | 0 | -96 | 4 | 0 | 1.00E-04 | 2.00E-04 | 1 | 15554 | NA | 1 | 10 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | yagi-9 | 3 | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA


**Second set of data - Starting 20:11:00 HRS**

  | hitID | runID | batchID | ts | tsCorrected | sig | sigsd | noise | freq | freqsd | slop | burstSlop | done | motusTagID | ambigID | port | runLen | bootnum | tagProjID | mfgID | tagType | codeSet | mfg | tagModel | tagLifespan | nomFreq | tagBI | pulseLen | tagDeployID | speciesID | markerNumber | markerType | tagDeployStart | tagDeployEnd | tagDepLat | tagDepLon | tagDepAlt | tagDepComments | fullID | deviceID | recvDeployID | recvDeployLat | recvDeployLon | recvDeployAlt | recv | recvDeployName | recvSiteName | isRecvMobile | recvProjID | recvUtcOffset | antType | antBearing | antHeight | speciesEN | speciesFR | speciesSci | speciesGroup | tagProjName | recvProjName | gpsLat | gpsLon | gpsAlt
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1 | 4.5E+08 | 24550062 | 370625 | ######## | ######## | 42 | 0 | -96 | 4 | 0 | 1.00E-04 | 0 | 1 | 15554 | NA | -1 | 7 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | NA | NA | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA
2 | 4.5E+08 | 24550062 | 370625 | ######## | ######## | 44 | 0 | -96 | 4 | 0 | 1.00E-04 | -0.0033 | 1 | 15554 | NA | -1 | 7 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | NA | NA | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA
3 | 4.5E+08 | 24550064 | 370625 | ######## | ######## | 44 | 0 | -96 | 4 | 0 | 1.00E-04 | 0 | 1 | 15554 | NA | 1 | 10 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | yagi-9 | 3 | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA
4 | 4.5E+08 | 24550064 | 370625 | ######## | ######## | 45 | 0 | -96 | 4 | 0 | 1.00E-04 | -0.0033 | 1 | 15554 | NA | 1 | 10 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | yagi-9 | 3 | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA
5 | 4.5E+08 | 24550062 | 370625 | ######## | ######## | 49 | 0 | -96 | 4 | 0 | 1.00E-04 | -0.0022 | 1 | 15554 | NA | -1 | 7 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | NA | NA | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA
6 | 4.5E+08 | 24550064 | 370625 | ######## | ######## | 50 | 0 | -96 | 4 | 0 | 1.00E-04 | -0.0021 | 1 | 15554 | NA | 1 | 10 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | yagi-9 | 3 | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA
7 | 4.5E+08 | 24550065 | 370625 | ######## | ######## | 48 | 0 | -96 | 4 | 0 | 1.00E-04 | 0 | 1 | 15554 | NA | 3 | 7 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | NA | NA | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA
8 | 4.5E+08 | 24550065 | 370625 | ######## | ######## | 47 | 0 | -96 | 4 | 0 | 1.00E-04 | 2.00E-04 | 1 | 15554 | NA | 3 | 7 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | NA | NA | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA
9 | 4.5E+08 | 24550062 | 370625 | ######## | ######## | 57 | 0 | -96 | 4 | 0 | 1.00E-04 | 3.00E-04 | 1 | 15554 | NA | -1 | 7 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | NA | NA | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA
10 | 4.5E+08 | 24550064 | 370625 | ######## | ######## | 60 | 0 | -96 | 4 | 0 | 1.00E-04 | 2.00E-04 | 1 | 15554 | NA | 1 | 10 | 5 | 74 | 378 | ID | Lotek4 | Lotek | NTQB-1 | 49 | 166.38 | 10.0954 | 2.5 | 1951 | 15580 | 2.71E+08 | metal band | 1.44E+09 | 1.45E+09 | 42.85507 | -72.5381 | NA | NA | CTRiver#378:10.1@166.38(M.15554) | 514 | 2504 | 42.34121 | -72.566 | NA | Lotek-161 | FortRiver | FortRiver | 0 | 74 | 0 | yagi-9 | 3 | NA | Swainson's Thrush | Grive à dos olive | Catharus ustulatus | BIRDS | CTRiver | CTRiver | NA | NA | NA

**Comment by StuMackenzie** [comment]
@leberrigan have you followed up with Jess about this?

**Comment by leberrigan** [comment]
We need to make sure this was resolved – it's been too long since I've worked on this

**Comment by leberrigan** [comment]
Not sure if it's resolved - I'm working on it now. Will reopen if not
