### ISSUE TITLE
Updates to About, Get Involved, and Resources

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#627]
As mentioned in our call today, we have been working on changes with the Motus website that we'd like to launch to live soon.

These changes are a long time coming and with Motus continuing to explode, we need new resources available. 

Please take a look through the sections below and let me know if you have any recommendations about the content, formatting, or coding.

- [About](https://beta.motus.org/about/)
  - [Frequently asked questions](https://beta.motus.org/faq/)
  - [Motus in the News](https://beta.motus.org/news/)
- [Get Involved](https://beta.motus.org/get-involved/)
  - [Become a Collaborator](https://beta.motus.org/collaborate/)
- [Resources](https://beta.motus.org/resources/)
  - [Tag Deployment](https://beta.motus.org/tag-deployment/)
  - [Receiver Deployment](https://beta.motus.org/receiver-deployment/)
  - [Antennas, Cables, and Dongles](https://beta.motus.org/antennas/)
  - [Selection Guide](https://beta.motus.org/selection-guide/)
     - We will delay the release of this until after we hear back from Lotek/CTT.
  - [Troubleshooting Guide](https://beta.motus.org/troubleshooting/)
- [Explore Data](https://beta.motus.org/explore-data/)

**Comment by cjardine-bsc** [comment]
I'm loving the increased organization. 

We might want to start looking for instances of "Bird Studies Canada" and replace them with "Birds Canada" where we can. 

Ideally we should update the logo in the header as well. I can look into that.

**Comment by Hussell** [comment]
Continued in #639
