### ISSUE TITLE
Station Landowner Contact mods. (formerly Add more than one contact and notes in site record)

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#628]
[Currently, only one contact can be added for a site](https://motus.org/data/project/sites?projectID=1).

Though often, there are multiple contacts — perhaps both spouses for private landowners, or a landowner and PI or station manager. Or sometimes the primary contact isn't the one who should be dealt with day to day.

- Can we add the ability to specify multiple contacts per site?
- Can we also add a notes field for general comments?

I'm not sure how easily this fits in with the existing format, or whether some messiness matters too much at the moment (this is not a page used often, or by many people) but those changes would be helpful.

**Comment by StuMackenzie** [comment]
Until elevating this we should be a bit more specific and examine why the current setup isn't meeting our needs. If each station has a primary, or important contact, why isn't that one used, and other details tracked in notes?

Does the current comments not work, or does this notes suggestion relate specifically to landowner contacts?

Now applies to 'stations'

**Comment by StuMackenzie** [comment]
See also - https://github.com/MotusDev/Motus-TO-DO/issues/626

Unless resolved @leberrigan

**Comment by jsayers-bsc** [comment]
Support for multiple contacts (e.g. landowners) is in the works as part of the move to manage at the Station level.
