### ISSUE TITLE
NonDeployed receivers not visible in ManageRecvs page when searched for

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#631]
Two receivers are currently not deployed show up in the Undeployed tab of [Manage Receivers](https://motus.org/data/project/recvs?projectID=1#tabs) when no filters are applied.

However, if they are searched for, they do not appear in the search results. 

Unfiltered results: 

![image](https://user-images.githubusercontent.com/55001144/69447055-ad41ab80-0d23-11ea-872a-03afc6a34e5c.png)

Filtered results:

![image](https://user-images.githubusercontent.com/55001144/69447131-d5c9a580-0d23-11ea-89fd-7bdd3eee933a.png)

They do appear in both the unfiltered and filtered list of the [Receivers](https://motus.org/data/projectReceivers?id=1) page.

**Comment by pmorrill** [comment]
I have checked in a fix for this issue. Please test again after next deployment to beta server.

**Comment by jsayers-bsc** [comment]
Seems to be fixed in beta

**Comment by denislepage** [comment]
Should I do a final push of beta9 to live before the holidays?

**Comment by pmorrill** [comment]
I think so, yes. But Josh and Lucas might be better to decide.
