### ISSUE TITLE
Trailing spaces not caught by search in ManageRecvs, Receivers, and Deployments

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#632]
The search in [Manage Receivers](https://motus.org/data/project/recvs?projectID=1#tabs), [Receivers](https://motus.org/data/projectReceivers?id=1), and [Deployments ](https://motus.org/data/projectReceiverDeployments?id=1)does not remove trailing spaces and thus returns 0 results even for otherwise valid searches. 

I use triple clicking relatively often to select an entire line when that line contains a serial number or something similar. But apparently that will also copy any trailing spaces. Other attempts to copy will sometimes also copy any trailing space if present. Of the examples below, one will result in search results whereas the other will not.

This may be the case elsewhere as well, but the above three pages are the only ones I just now tested.

Receiver:

SG-5113BBBK0173 
SG-5113BBBK0173

Deployment name:

Werden 
Werden

**Comment by jsayers-bsc** [comment]
Interestingly, Github stripped the trailing space when I posted, so the above examples no longer work as examples!

**Comment by Hussell** [comment]
I'm tempted to say this is by design, that whitespace characters should be searchable. For example, searching for "Black" vs "Black " in the receivers of project 48. Or searching for receiver deployments with a space in the name, i.e. search for " ".

If this is a common mistake, maybe if a search returns zero results and there's a trailing space in the search box, display a message to the user so they can quickly figure out what went wrong?

**Comment by leberrigan** [comment]
Is is possible to use spaces as a delimiter for multiple terms unless there are quotation marks, like with Google searches? I can see how having trailing spaces could be useful for differentiating between whole word and partial word matches, but the difference in the number of results you get when searching for partial words will generally be negligible. 

If we use spaces as a delimiter a search like "black beach" would return names like "blackbeach" and "black rock beach" which is handy when there is so much inconsistency with labeling.

**Comment by pmorrill** [comment]
The search mechanism is literal, with no interpretational 'smarts'. It simply uses a `LIKE ('search-string')` filter on a DB query.

However, trimming the search value to get rid of white space (front and back) is easy, and I am thinking that is a good idea.

**Comment by jsayers-bsc** [comment]
Search bars across Motus.org would be more useful if they behaved more like filters, where any combination of the words would yield results (ignoring spaces anywhere)
