### ISSUE TITLE
Deployment name of networked receiver not updating

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#633]
We have a receiver that is to be deployed as a networked receiver in a few days at a new location. 

This receiver, [SG-91EBRPI3E583](https://motus.org/data/receiver?id=2502), was previously on Discovery Island BC. That deployment ended in summer 2019, but the change was only entered into the database a week or so ago (due to an unrelated sequence of events).

I had this connected to the BSC HQ WiFi yesterday, and while it immediately and repeatedly checked in with the server, it never synced any data. ([Similar to this issue.](https://github.com/MotusDev/Motus-TO-DO/issues/599#issue-515517233)) And the deployment name never updated either.

But now I have it connected at my home, on the same [test deployment](https://motus.org/data/receiverDeployment?id=5779), and it is now also syncing data, according to sensorgnome.org/status. But still, the deployment name hasn't updated to reflect the new deployment name.

How is this information on sensorgnome.org populated if not from the motus database or deployment file?

**Comment by jsayers-bsc** [comment]
This ended up resolving itself after several days.

There are a couple reasons I can think of why it took so long. 

One is that the name in the deployment file was "ChangeMe". It's possible that when that name is encountered it is simply ignored and the last deployment name associated with that receiver, however long ago, persists.

The other possible reason I can think of is that the deployment associated with this receiver last week when it was connected was a test. Maybe Test deployments are ignored as they are in many places on Motus.org. But I don't know if there is any two way communication between the motus DB and the server where sensorgnome is that would enable that sort of check...

**Comment by Hussell** [comment]
Should I close this until it happens again?

**Comment by jsayers-bsc** [comment]
I'll add any any other comments later if the reasons become more clear...

**Comment by jsayers-bsc** [comment]
The name of this other connected receiver hasn't been updating either....

![image](https://user-images.githubusercontent.com/55001144/69829640-d2845d00-11ee-11ea-8f7d-3f63d13b4ee3.png)

It's now been connected online for several days (with a deployment name set in deployment.txt as well as registered deployment). Unlike the previous receiver, which had previously been connected and showed up on sensorgnome.org (and just needed its name updated) this one has never been connected before...

Makes we wonder how exactly these names are pushed to sensorgnome.org in the first place... It's obviously related to the deployment file to some degree, but that's not the only factor. Where does the project come from, for instance?

**Comment by dfloer** [comment]
The code for this now lives at https://github.com/sensorgnome-org/sensorgnome-server.

From a quick glance at the code, the server software is storing its data on receivers in a SQLite database. Data on receivers and projects is pulled from calls to the Motus API to populate these. I'm not sure yet how and when updates are triggered.
