### ISSUE TITLE
Questions about networked gnomes on sensorgnome.org

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#635]
As a follow up to some of what Stu mentioned earlier today about the sensorgnome.org page, here are a few questions that have come for me when working with networked gnomes on sensorgnome.org. Some of you may have answers for these questions, or perhaps some of this is stuff we're all wondering about...

- How much time has to pass since the previous connection before "Connected" status changes from Yes to No?

![image](https://user-images.githubusercontent.com/55001144/69828857-871c7f80-11eb-11ea-8e20-8c33869ea341.png)

(Upon glancing through the list of "No" receivers just now, they all seem to share in common that the time of Last Sync is _earlier_ than the time of Last Connection, so perhaps that is the trigger for changing that status)

- How long until a networked gnome that fails to connect falls off this list entirely? [Zorad ](https://motus.org/data/receiverDeployment?id=3127)is a local example of "networked" gnome that no longer appears on this list. Presumably that's because it hasn't connected and/or synced data in a certain amount of time. But what what are the criteria, and how many other receivers may have fallen off the list entirely?

- Relatedly I'll link to a [discussion from earlier](https://github.com/MotusDev/Motus-TO-DO/issues/601) about the pros and cons of manually flagging stations that are _intended_ to be connected in a way that is separate and not reliant on them actually successfully connecting. Currently I don't believe there is any (easy) way of obtaining a list of receivers that _should_ be connecting but are not, if they have fallen off sensorgnome.org entirely (other than what's in people's heads). This may also help to differentiate between networked deployments and receivers that connected only briefly as part of a test, etc. 

- Why is the most recent connection time sometimes much earlier than the most recent data transfer? Shouldn't these always be more or less the same, or if anything, most recent connection is more recent than last data sync? Sometimes the time difference between these can be significant. The one below synced data today, but hasn't "connected" in a week.  In other words, how is data synced without first making a connection? Is there some other way that "connection" is defined here?

![image](https://user-images.githubusercontent.com/55001144/69829236-33129a80-11ed-11ea-94f3-cebeab95acbf.png)

- [How are names assigned to these deployments/receivers?](https://github.com/MotusDev/Motus-TO-DO/issues/633#issue-527631218) I thought earlier that it depended on the name in the deployment.txt file (and that does seem to part of it). But there is something else at play too, at least in order to assign receivers to projects. Project names don't occur in deployment.txt so presumably this is being pulled from some other source. It doesn't seem that sensorgnome.org cross references a deployment in the main motus database to assign the project, and further the project names in sensorgnome.org are often abbreviations or other versions of the official project name (eg. MotusON or TXShorebirds).

**Comment by StuMackenzie** [comment]
@dfloer For review and feedback re. SG live interface.

For information and future revision, but no immediate action to be taken so closing unless actions can be identified.
