### ISSUE TITLE
Error message about missing bearing on omni directional antenna

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#636]
[Deployment 3699](https://motus.org/data/receiver/deployment/edit?projectID=120&id=3699) in project 120 is receiving an error message about a Missing Antenna Bearing. Thing is, the antenna in question is a Mast Radiator and is omni-directional.

**Comment by Hussell** [comment]
An error message when you do what?

**Comment by jsayers-bsc** [comment]
I mean errors in the Data Issues page for that project.

![image](https://user-images.githubusercontent.com/55001144/70170695-2ed9f780-169b-11ea-9446-e446261bc544.png)

(Though I guess this particular one in a warning and non an error.)


The PI is trying to resolve the issues but pointed out that "Missing Antenna Bearing" warnings probably should only apply to directional antennas.

**Comment by Hussell** [comment]
Catherine, in prDataValidation_pr the section which computes v_sensor_antenna_bearing should use lk_antenna_type.directional to ignore non-directional antennas.

**Comment by cjardine-bsc** [comment]
I've made that change. We should re-run the validations and check that the problem disappears.
