### ISSUE TITLE
Updates to About, Get Involved, and Resources - Soft Launch

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#639]
As mentioned in our call yesterday, I have made the changes to the Motus live site that I had made in November.

Please take a look through the sections below and let me know if you spot any problems.

- [About](https://motus.org/about/)
  - [Frequently asked questions](https://motus.org/faq/)
  - [Motus in the News](https://motus.org/news/)
- [Get Involved](https://motus.org/get-involved/)
  - [Become a Collaborator](https://motus.org/collaborate/)
- [Resources](https://motus.org/resources/)
  - [Tag Deployment](https://motus.org/tag-deployment/)
  - [Receiver Deployment](https://motus.org/receiver-deployment/)
  - [Antennas, Cables, and Dongles](https://motus.org/antennas/)
  - [Selection Guide](https://motus.org/selection-guide/)
     - We will delay the release of this until after we hear back from Lotek/CTT.
  - [Troubleshooting Guide](https://motus.org/troubleshooting/)
- [Explore Data](https://motus.org/explore-data/)

**Comment by StuMackenzie** [comment]
Lots of minor corrections and edits shared via email.

**Comment by jsayers-bsc** [comment]
FYI “Download Data” returns a 404 error

**Comment by StuMackenzie** [comment]
This has been launched. Still needs finalization, notification to the Motus community, then translation.
