### ISSUE TITLE
Option to select "Project: All" instead of one project at a time

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#642]
Would it be possible to create the option to select All Projects one has access to, instead of only one at a time? 

![image](https://user-images.githubusercontent.com/55001144/70718710-b38dcc80-1cbe-11ea-9e36-d5cf9005c19c.png)

Nearly all access to receiver and tag data is filtered by project. This is often useful, but it just as often creates additional steps when trying to locate a particular receiver or tag deployment when project name is unknown. For myself, it feels like I'm constantly going through a few additional steps to identify the project in order to locate the information I'm looking for. Viewing all projects at the same time and filtering/searching from there would simplify things quite a bit. I feel like this would also be useful for other collaborators who manage more than one project.

There is a workaround when using the Download Data to csv functions that allows data from all projects to be viewed, but this only works for downloads, and not the general view in the web interface.

Project: All would also make a [great default selection too!](https://github.com/MotusDev/Motus-TO-DO/issues/629)

**Comment by StuMackenzie** [comment]
In relation to this and #629 . If the drop down menu was ordered numerically instead of alphabetically it would help us to locate projects more efficiently. That, or the option to sort this list alphabetically or numerically. It's only an issue for admin, in which case I would prefer to be ordered by project.

**Comment by StuMackenzie** [comment]
OR, if the main menu page simply returned a list of all projects similar to https://motus.org/data/projects?n=1000&q=&f=1&o=0a1a2a3a4a5a6a7a that could be selected from that list. OR, an easier way to link to Manage Projects from Explore Projects. 
 #543
