### ISSUE TITLE
API for new tag models

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#643]
At a meeting back in October, we discussed setting up an API entry point to allow CTT (and perhaps in the future Lotek) to register new tag models directly to the database. 

Paul, I've set up a new table for this: api_import_tags_model

Fields are: 
[id] [int] IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
	[api_batch_id] [int] NOT NULL,
	[manufacturer] [varchar](32) NULL,
	[model] [varchar](20) NOT NULL,
	[descr] [nvarchar](50) NULL,
	[descr_fr] [nvarchar](50) NULL,
	[length_mm] [tinyint] NULL,
	[width_mm] [tinyint] NULL,
	[height_mm] [tinyint] NULL,
	[weight_g] [real] NULL,
	[lifespan_2_sec] [smallint] NULL,
	[lifespan_5_sec] [smallint] NULL,
	[lifespan_10_sec] [smallint] NULL,
	[lifespan_10_sec_50] [smallint] NULL,
	[D] [float] NULL,
	[rt] [float] NULL,
	[lifespan_buffer] [decimal](4, 2) NULL,
	[battery_model] [varchar](20) NULL

I've also created a proc: prAPIImportTagsModles
@import_id int OUTPUT,
	@manufacturer [varchar](32),
	@model [varchar](20),
	@descr [nvarchar](50),
	@length_mm [tinyint],
	@width_mm [tinyint],
	@height_mm [tinyint],
	@weight_g [real],
	@lifespan_2_sec [smallint],
	@lifespan_5_sec [smallint],
	@lifespan_10_sec [smallint],
	@lifespan_10_sec_50 [smallint],
	@D [float],
	@rt [float],
	@lifespan_buffer [decimal](4, 2),
	@battery_model [varchar](20),
    @code varchar(20) OUTPUT

This still needs a few extra data checks before it's polished, but for now it is set up to import the data into api_import_tags_model. 

This is all in sandbox for the time being.

**Comment by pmorrill** [comment]
prAPIImportTagsModles ?? Modles, Moodles, or Models...?

**Comment by cjardine-bsc** [comment]
Moooooooooodddddles. 

ha! Typo fixed.
