### ISSUE TITLE
Birds Canada logo

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#651]
Due to the clock issue (#649), last week Denis deployed the fix from beta9 to live. Along with the fix, some changes for the Birds Canada logo were deployed. To complete that work, the header.php and strippedheader.php on live WordPress need to be updated to match the header.php and strippedheader.php on beta WordPress.

(I keep forgetting how, therefore you might have too, so: left menu "Appearance" -> "Theme Editor", then there's the list of files in a column on the right.)

**Comment by cjardine-bsc** [comment]
This is almost impossible to do over the TS with internet explorer. I've asked Denis to grant access to my IP and will take care of this once that's set up.

**Comment by leberrigan** [comment]
Yeah, I can't use that theme editor either - it's useless! When I made the education site I had to delete the old theme and re-upload it to make any changes which is risky and a pain.

**Comment by Hussell** [comment]
I think I don't understand what the problem is. I think you should be able to just copy the beta file from the edit box and paste it into the corresponding edit box on live, hit the "Update File" button, and be done.

You're seeing the same thing as me, right?

![beta WordPress](https://user-images.githubusercontent.com/28784000/71924754-8a5e4000-3187-11ea-92c5-3cb58724c772.png)

**Comment by Hussell** [comment]
Ah, looks like I forgot: there's style.css to copy over too.

**Comment by leberrigan** [comment]
I can't edit any text in the theme editor on Wordpress because it's constantly 'fixing' what I'm typing, making it impossible to enter anything. Pasting text into the editor doesn't work either - it gets all messed up.

**Comment by denislepage** [comment]
Can someone email me the necessary edits to the template files?

Also, the map on the home page is broken.

**Comment by denislepage** [comment]
The map is back. This was database related, not Wordpress.

**Comment by cjardine-bsc** [comment]
I already edited the template files D-Boss. I'll do the .css now too. 

I think we also need to upload the new logo to live.

**Comment by cjardine-bsc** [comment]
S'all good

https://motus.org/data/login

Jeremy, the problem is internet explorer on TS. It corrupts the edit box.  If you're using another browser it works fine. I leapfrogged into our Simcoe server and did the edit there in firefox.

**Comment by Hussell** [comment]
That's done it. You'll need to reload the page to replace the cached stylesheet, but it looks good now.

What's TS in this context? Probably not TypeScript or Trusted Solaris.

**Comment by cjardine-bsc** [comment]
Terminal Server (remote desktop). You've never had to deal with it since you're local in Port Rowan.
