### ISSUE TITLE
Node insertion: Invalid column name 'deploy_id' error

### ISSUE THREAD

**Issue by pmorrill** [MotusDev/Motus-TO-DO#655]
File  Name | Line  Number | Class  Name | Method  Name | Native  Method?
-- | -- | -- | -- | --
SQLPreparedStmt.java | 244 | org.bsc.SQLPreparedStmt | executeUpdate | false
MotusBean.java | 196 | org.bsc.motus.MotusBean | insertFromMap | false
MotusBean.java | 339 | org.bsc.motus.MotusBean | upsertFromMap | false
MotusBean.java | 323 | org.bsc.motus.MotusBean | upsert | false
RecvDeploymentBean.java | 554 | org.bsc.motus.RecvDeploymentBean | upsertNodes | false
RecvDeploymentBean.java | 406 | org.bsc.motus.RecvDeploymentBean | upsertFromRequest | false
EditRecvDeploymentServlet.java | 164 | org.bsc.motus.web.EditRecvDeploymentServlet | doPost | false
HttpServlet.java | 648 | javax.servlet.http.HttpServlet | service | false
HttpServlet.java | 729 | javax.servlet.http.HttpServlet | service | false
ApplicationFilterChain.java | 291 | org.apache.catalina.core.ApplicationFilterChain | internalDoFilter | false
ApplicationFilterChain.java | 206 | org.apache.catalina.core.ApplicationFilterChain | doFilter | false
WsFilter.java | 52 | org.apache.tomcat.websocket.server.WsFilter | doFilter | false
ApplicationFilterChain.java | 239 | org.apache.catalina.core.ApplicationFilterChain | internalDoFilter | false
ApplicationFilterChain.java | 206 | org.apache.catalina.core.ApplicationFilterChain | doFilter | false
SetupFilter.java | 87 | org.bsc.motus.web.SetupFilter | doFilter | false
ApplicationFilterChain.java | 239 | org.apache.catalina.core.ApplicationFilterChain | internalDoFilter | false
ApplicationFilterChain.java | 206 | org.apache.catalina.core.ApplicationFilterChain | doFilter | false
StandardWrapperValve.java | 219 | org.apache.catalina.core.StandardWrapperValve | invoke | false
StandardContextValve.java | 106 | org.apache.catalina.core.StandardContextValve | invoke | false
AuthenticatorBase.java | 502 | org.apache.catalina.authenticator.AuthenticatorBase | invoke | false
StandardHostValve.java | 142 | org.apache.catalina.core.StandardHostValve | invoke | false
ErrorReportValve.java | 79 | org.apache.catalina.valves.ErrorReportValve | invoke | false
AbstractAccessLogValve.java | 617 | org.apache.catalina.valves.AbstractAccessLogValve | invoke | false
StandardEngineValve.java | 88 | org.apache.catalina.core.StandardEngineValve | invoke | false
CoyoteAdapter.java | 518 | org.apache.catalina.connector.CoyoteAdapter | service | false
AbstractAjpProcessor.java | 844 | org.apache.coyote.ajp.AbstractAjpProcessor | process | false
AbstractProtocol.java | 668 | org.apache.coyote.AbstractProtocol$AbstractConnectionHandler | process | false
NioEndpoint.java | 1521 | org.apache.tomcat.util.net.NioEndpoint$SocketProcessor | doRun | false
NioEndpoint.java | 1478 | org.apache.tomcat.util.net.NioEndpoint$SocketProcessor | run | false
␀ | -1 | java.util.concurrent.ThreadPoolExecutor | runWorker | false
␀ | -1 | java.util.concurrent.ThreadPoolExecutor$Worker | run | false
TaskThread.java | 61 | org.apache.tomcat.util.threads.TaskThread$WrappingRunnable | run | false
␀ | -1 | java.lang.Thread | run | false

**Comment by pmorrill** [comment]
It appears that the issue here is with a trigger: tr_sensor_nodes. It is referencing deploy_id rather than the correct sensor_nodes .deployment_id.

(However in the bt_sensor_nodes, the field is called deploy_id: this should probably be consistent).

**Comment by cjardine-bsc** [comment]
Fixed.
