### ISSUE TITLE
Tag Registration and Parsing

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#657]
Here is the outline of what we discussed today regarding the flow for registering tags from CTT and Lotek using an email. 

Note: The process for users to register their tags directly to a Motus project will remain in place for cases where the user provides an email that matches an email registered to a Motus account. In this case they can register the tag directly to a project they have manage tags permissions for. 

1. User orders tags through manufacturer and provides email that does not match an existing motus account. 
2. Tags are registered via the api to project 0. 
3. Tags registered as part of that API batch are also written to a new table called api_import_tags_token this includes:

 [id] ,[api_batch_id],[tag_id] ,[token],[email],[user_id],[created_dt]

At the onset user_id is null.

4. The user receives an email with a token link that takes them to a motus sign in (or register) page (need to determine if we need a special-case page or if we can use the existing one)  they sign in or create an account and then are taken to a page where they can confirm they want the tags from that batch associated with that userID (do we want a confirmation page?)

5. The api_import_tags_token table is updated with the user_id and the user is re-directed to a new tag transfer page. 

6. This page will allow users to view all tags they have permissions for (a combo of tag_ids from api_import_tags_token and from projects where they have manage tags permissions (a view for this will need to be created). The user will be able to filter based on: date registered, project, model, and deployment status. 

7. The user can select the tags they would like to move then identify the new project they will be transferred into. For the first iteration I suggest we only allow users to transfer tags that have never been deployed (using prTagTransferMove). We can plan for an added ability to move tags with their deployments, or copy tags (so they can have deployments in more than one project) in future iterations. 

Easy peasy ;-)

**Comment by leberrigan** [comment]
We have automated registrations now.
