### ISSUE TITLE
Status of dual mode SensorGnome data uploads?

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#658]
I had 2 RPi SensorGnomes running alongside 5 SensorStations for 5 days from 2019-11-13 to 2019-11-18. 

Throughout the period I was checking in with all the stations. The CTT test tags were active and visible in the Web Interface of the SensorGnomes, as well as in the raw data where expected.

But once I uploaded the detection data, there were no CTT tags detect

**Comment by jsayers-bsc** [comment]
Apparently a series of stuck keys resulted in a partially written issue being posted...

**Comment by jsayers-bsc** [comment]
Anyway, like the text above sort of says, I uploaded data from 2 dual mode SensorGnomes thinking that the process of parsing that out was completed. Once I didn't see any CTT tags in the detection data it became clear that either it's not completed, or it isn't working quite properly.

I also have a couple related clarification questions about the data flow here.

CTT detection data uploaded to Motus directly is supposed to then automatically get sent over to CTT, where they run their detection and tag analysis process, after which it returns to the Motus servers. Is that correct?

Do we know if Tag Deployments affect CTT's tag identification process as it does with the Nanotags (it obviously doesn't need to in the same way, but maybe they do as an additional validation)? 

And once the detection data comes back from CTT into Motus, does our accept those tag ID's as given, or do we/tagfinder then cross-reference them with Tag Deployments as with all other tags?

**Comment by jsayers-bsc** [comment]
What is the best way at the moment of processing dual mode data from SGs?

**Comment by jsayers-bsc** [comment]
Following up on yesterday's conversation about this...

One of the receivers in question is SG-1ACBRPI38EBA, [deployment ID 5882](https://motus.org/data/receiver/deployment/edit?projectID=1&id=5882).

The upload contained both CTT and SG files, and some of these are seen in the sgjobs (a couple of the CTT files were empty, so they were listed in that warning section). But in the files section for that receiver, it's all just SG files (as expected, I think). So the CTT files do seem to be getting parsed _out_. 

It was mentioned that currently the process of CTT acquiring them from the AWS folder is manual, so that may well account for why they haven't showed up. 

@pmorrill you asked for a couple files names just to confirm that they had made it over. Here are a couple of the files (that had detection data in them):

changeMe-1ACBRPI38EBA-000004-2019-12-26T16-55-02.2410T-ctt.txt.gz
changeMe-1ACBRPI38EBA-000004-2019-12-30T18-44-33.5620T-ctt.txt.gz

**Comment by pmorrill** [comment]
@jsayers-bsc have you ever used this admin tool:

https://sandbox.motus.org/data/admin/awsBrowser?bucket=ctt-motus-development

It allows you to browse the files currently sitting on the aws drive. There is a short statement for each of the 'buckets' that we are using, and a link to a longer description of how it works. I looked under the motus/data/sg bucket and there are loads of files there: I did not find the ones you mention on the first few 'pages' (there are 1000 files per page). I think this is where they should be.

The fact that some files date back to 2017 worries me - where did they come from? But I am not certain. Denis should take a look when he gets a chance.

Also, this interface is internal only, and could be improved to provide filtering of the long list, as well as a few other features. We probably need to get back to that.

**Comment by jsayers-bsc** [comment]
I hadn't see that, Paul, thanks. It would be hard to find them if they were there, though like you say they should be near the top.

Maybe thing to do then is to get another RPi running for a bit and recording data. Then I can upload again and we can see if the files are showing up here.

**Comment by jsayers-bsc** [comment]
There is a new [test deployment SG RPi](https://motus.org/data/receiverDeployment?id=5914) detecting both tag types. It's a SyncReceiver at the moment and it does look like it's parsing out the CTT files, at least based on the logs.

![image](https://user-images.githubusercontent.com/55001144/74259709-53b7a000-4cc6-11ea-8672-ade48c5fd817.png)

**Comment by denislepage** [comment]
The tag finder won’t have any more details than what you see in the logs provided, regardless of whether the rest has been completed or not (upload to AWS for CTT and eventually downloading the processed data)

However, there seems to be a good number of CTT files that have been moved to the outgoing folder that are still pending upload to AWS. I am looking into it now. Seems to be related to file permission issues.

**Comment by denislepage** [comment]
I figured it out. It was a file permission-related issue. I am now pushing the stalled detection files to AWS. We should still try to re-confirm that the old dual mode format, which embeds the CTT detections in the same files as Lotek's, also works.

1. CTT data that people upload to Motus get passed to CTT through AWS.
2. CTT filters data to include include tags that are relevant to Motus and place the data back on AWS for us, along with data from CTT receivers that they manage.
3. With the exception of tags that get redeployed, there should be no ambiguity about matching a tag code with a motusTagID. If the tag code doesn't already exist in our database, we register it at the time of the data import (under project 0, I assume), with the assumption that anything that CTT provides to us is a valid tag.
4. People continue to need to enter deployments for those tags for them to be available for download, I believe.

**Comment by denislepage** [comment]
I just checked, and I am not seeing the files that are listed in the example for receiver SG-9006RPI3CE4D. @jsayers-bsc Can you send me those 3 files only?

**Comment by jsayers-bsc** [comment]
I just did a manual upload of the last couple days and will send over some individual ctt files to you via email

**Comment by jsayers-bsc** [comment]
Just checked and none of the LifeTag detections have yet come through on the detections tables.

This is an [example](https://motus.org/data/receiverDeployment?id=5926), currently a syncReceiver that has been on for the last few days and picking up LifeTags, though none have made it through either to Motus or the R package.

**Comment by denislepage** [comment]
OK, I just realized that this a VERY LARGE number of files that are in the AWS drive, seemingly unprocessed. I haven’t paginated through to the end, but it may be as many as 112,000 files from 23 receivers with CTT dongles, some dating back to Wink’s early days in 2017.

The ones you mentioned are part of that lot:
https://motus.org/data/admin/awsBrowser?bucket=ctt-motus-development&prefix=motus/data/sg/changeMe-D2D4RPI32C60

I’ll check with Bob, but it seems like those aren’t being processed.

**Comment by StuMackenzie** [comment]
Closed in deference to #760 and #836
