### ISSUE TITLE
Parameters for "Current" and "Long Term" Feature Detection Rate?

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#662]
In the Web Interface for an SG, there is a section for the Feature Detection Rate for each dongle, broken into Current and Long Term.

![image](https://user-images.githubusercontent.com/55001144/72922612-548a9100-3d1b-11ea-988c-20cda77aa4eb.png)

It's [clear ](https://archived.sensorgnome.org/@api/deki/files/23/=web_interface_two_active_funcubedongles.png?size=webview)that this is a measure of Pulses per Unit Of Time.  But the Unit of Time is unclear. Does "Current" imply the most recent hour, the most recent day? Is "Long Term" the last month, the last year, etc?

Is anyone aware what time is meant by these?

**Comment by adamdsmith** [comment]
Not sure about current, but I believe long-term is the rate since last restart since it seems to reset to zero after a reboot.

**Comment by dfloer** [comment]
Here is where a row in the HTML table is being generated: https://github.com/sensorgnome-org/sensorgnome-control/blob/master/master/public/javascripts/sensorgnome.js#L373

`(pulse_rate * 60).toFixed(4)` is the code generating the value in the current row with `(tot_pulse_rate * 60).toPrecision(6)` generating the value in the long-term row.

pulse_rate is defined as either `pulse_rate = (plugin.totalFeatures - oldplugin.totalFeatures) / (fcd.totalFrames - oldfcd.totalFrames) * fcd.hwRate;` based on the variable `oldfcd` or
`pulse_rate = plugin.totalFeatures / fcd.totalFrames * fcd.hwRate;`.
tot_pulse_rate is `tot_pulse_rate = plugin.totalFeatures / fcd.totalFrames * fcd.hwRate;`

So the values may be different value, but still calculated over the same time period.

Based on my cursory look at the code, I'm not sure if the values used to calculated it are reset upon reboot, but if they are, I'd expect them both to be similar, barring bugs elsewhere in the code.
