### ISSUE TITLE
Permissions, data uploads, and the collaboration policy

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#664]
I promise these are related issues!

I recently received an email from someone who helps to manage a project and download their data. He's unable to upload the data because he has not been added to the project by the PI. I viewed the site as the PI and see he hasn't yet accepted the collaboration policy (which is actually preventing navigating the Manage Data page, as would be expected if the PI himself were logging in). The PI clearly doesn't use Motus.org and maybe hasn't even logged on before, which means him giving upload permission to anyone isn't happening any time soon. 

Since we have been talking about permissions and the collaboration policy this seemed worth bringing up. 

- Is there any value (or risk) in allowing data uploads by people who aren't associated with a particular project? Normally this isn't an issue, but apparently it is sometimes an obstacle. 

- The other option is for us to manually add the person to the project so they can upload. This is obviously fine in some cases if the individual and their relationship to the project are known. In other cases it's less clear. Either way it makes irrelevant the concept of the PI-determined project privileges.

**Comment by denislepage** [comment]
I would not allow uploads to all projects as a blanket rule (particularly an issue for tags), but I think the risk of adding someone without being 100% sure of their legitimacy has relatively little risk. The data really only gets assigned to a project if there are receiver deployments. But if the PI isn’t managing their project, does the metadata even exist? One person from each project has to manage the metadata, or the data is virtually useless. If we just make it easier for people to by-pass that requirement, we just encourage delinquent projects. It’s a bit painful, but either we add the users ourselves, or the person contacts the PI to get added. If the PI can’t at least do that, I am not sure they are actually a PI, and maybe the person uploading the data should set their own project… ☺

**Comment by StuMackenzie** [comment]
Whats the project number, the PI, and the person that wants access?

**Comment by jsayers-bsc** [comment]
> 
> 
> Whats the project number, the PI, and the person that wants access?

I sent you an email....

**Comment by StuMackenzie** [comment]
Closing in deference to numerous issues including https://github.com/MotusDev/Motus-TO-DO/issues/720
