### ISSUE TITLE
Project 63 - Caulin Bay Aliased Tags

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#667]
We are getting lots of false positives at Caulin Bay, Chile where I recently deployed a receiver. A total of 27 tags were also deployed here and 26 are actively being detected at each low tide cycle. 

During the same period we are getting a huge number of false positives which are most likely related to tag aliasing since they only seem to occur when the other birds are present.
![CaulinBay_uSask-vs-Other_allRuns](https://user-images.githubusercontent.com/35931796/73582345-23b90300-4463-11ea-852c-0e548201e8a1.png)
 
These stand out when looking at the 'slop' of false vs. true detections. Recall that slop describes the absolute difference between **pulses** in the recorded vs. detected tags. Tag finders allows for a certain slop in detections since we don't expect the pulse intervals to be exactly constant. For aliased tags we should expect this slop to be larger on average. 
![CaulinBay_false-vs-true_slop_allRuns](https://user-images.githubusercontent.com/35931796/73511068-bd78a580-43ba-11ea-8a2b-e3e3bb460336.png)

This is also true for false positives as a result of noise, but previous experience shows that sigSD and freqSD should be very different from true detections, but in this case they aren't which is not surprising if all these pulses come from real tags. We also see the signal-to-noise ratio to be similar between false and true detections.
![CaulinBay_false-vs-true_sigSD_allRuns](https://user-images.githubusercontent.com/35931796/73511056-b487d400-43ba-11ea-8146-31c86fb02d09.png)
![CaulinBay_false-vs-true_snr_allRuns](https://user-images.githubusercontent.com/35931796/73511057-b5206a80-43ba-11ea-8e88-d026c6d91454.png)
![CaulinBay_false-vs-true_freqSD_allRuns](https://user-images.githubusercontent.com/35931796/73511058-b5206a80-43ba-11ea-9259-37207f1829c7.png)

For reference, the following tags have been deployed at Caulin Bay:

tagDeployID | mfgID | tagBI
-- | -- | --
27300 | 5 | 9.5986
27301 | 6 | 9.5987
27302 | 7 | 9.5987
27303 | 8 | 9.598
27304 | 9 | 9.5987
27305 | 10 | 9.5998
27306 | 11 | 9.5988
27307 | 12 | 9.5987
27308 | 13 | 9.5987
27309 | 14 | 9.5988
27310 | 15 | 9.5985
27311 | 16 | 9.5988
27312 | 17 | 9.5988
27313 | 18 | 9.5987
27314 | 19 | 9.5987
27315 | 20 | 9.5987
27316 | 21 | 9.5984
27317 | 22 | 9.5988
27318 | 23 | 9.5987
27319 | 24 | 9.5988
27320 | 25 | 9.5997
27321 | 26 | 9.5984
27322 | 27 | 9.5988
27323 | 28 | 9.5987
27324 | 29 | 9.5996
27325 | 30 | 9.5987
27326 | 31 | 9.5988

We do not expect other tags to be present here unless some Atlantic flyway shorebirds make an unexpected visit to the Pacific.

**Comment by StuMackenzie** [comment]
Closed in deference to https://github.com/MotusDev/Motus-TO-DO/issues/779 - will discuss and solve problems there.
