### ISSUE TITLE
add disclaimer to all pages presenting public data 

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#668]
This disclaimer is at the top of the View Tracks pages, but is not available on other pages displaying public data, eg : detection tables from station map, other summaries, etc,  https://motus.org/data/receiverDeploymentDetections?id=5891

Should probably try and include this on all pages displaying public data or compile a list here of the most important pages to update.

"Attention: These public animations have been created using broad filters based on theoretical flight speeds, logical geographic8/time sequences, at least 3 consecutive tag bursts at a single station. Individual tracks have not been inspected for accuracy. Please report any questionable tracks to motus@birdscanada.org to help us refine the filters."

It wonder if it's worthwhile providing more details 'visit here for more details' that explains exactly what filters are being applied in details - e.g what flights speeds. sequences, etc. The composition of filters applied may not be straightforward enough to explain that way as we have manually identified many bogus tags and removed them. Up for discussion here???

**Comment by jsayers-bsc** [comment]
Definitely agree that this disclaimer should be shown elsewhere where detection data is displayed on the web. Along with that, a similar disclaimer may be warranted for plots where data is _not_ filtered.

I also think that more detail/explanation would be helpful — what exactly are the filter parameters. I'm a little unclear about it myself. Is it only runLen > 3 and motusFilter == 1? Do both of those filters apply for each view or are there differences say between detection tables and the track viewer?

**Comment by StuMackenzie** [comment]
Closing in deference to https://github.com/MotusDev/Motus-TO-DO/issues/853

ACTION - Detailed public documentation of the 'Motus Filter' is required. Public warnings need to be displayed somewhere whenever public data is shown.
