### ISSUE TITLE
Tag Missing Species data issue being triggered for Test Tag deployments

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#669]
A number of the "Tag Missing Species" [data issues for Project 1](https://motus.org/data/issues?id=1#v_tag_deploy_species) actually refer to Test Tag Deployments.

**Comment by cjardine-bsc** [comment]
Should be addressed. Test?

**Comment by jsayers-bsc** [comment]
Yup!

**Comment by diinrel** [comment]
This is occurring again, this time for Project 322 Test Tags: [https://motus.org/data/issues?id=322#v_tag_deploy_species](https://motus.org/data/issues?id=322#v_tag_deploy_species). And checking on the original link shows the error showing up for test deployments in Project 1 too.

**Comment by jsayers-bsc** [comment]
This is occurring again, this time for Project 322 Test Tags: https://motus.org/data/issues?id=322#v_tag_deploy_species. And checking on the original link shows the error showing up for test deployments in Project 1 too

**Comment by cjardine-bsc** [comment]
whoops, my bad guys, I left a section commented out when I addressed another issue. Fixed.

**Comment by jsayers-bsc** [comment]
Perfect, thanks!
