### ISSUE TITLE
Change regex for CTT data files

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#671]
The serial numbers used to represent the CTT Sensor Stations needs to accommodate new patterns. 

The current pattern:
^(CTT\\-[0-9]*)\\-(node|data|gps)

Should be changed to:
^(CTT\\-[0-9A-F]{12,16})\\-(node|raw-data|data|gps)

For example: 
•	CTT-DEC502C4C7F9-data.2020-01-14_124445.csv.gz

The new serial will have 12 alphanumeric characters [A-F0-9]{12}. The current pattern only deals with  all numeric digits. The "data" type may also get changed to "raw-data", but we need to be able to support both for a good while (alphanumeric with 12 to 15 characters, as a minimum).  data and raw-data will need to be treated as equivalents. 

I made the changes in the motus package (Java), as well as changed a couple files in motusServer (motusConstants.R and sgFilenameRegex.R). All motusServer is doing is moving those files to a different folder, so the change should have few implications.

Those changes should be looked at and deployed for testing. There hasn't yet been any data coming in with those new patterns that I am aware of, but that shouldn't be too much longer.

**Comment by cjardine-bsc** [comment]
This is also stored in the database in the lk_receiver_type table. 

It's currently: ^CTT-[0-9]{15}$

I've changed to ^(CTT\-[0-9A-F]{12,16})

**Comment by Hussell** [comment]
Just to make absolutely certain: when they say the serial number is going to have 12 "alphanumeric characters", they don't mean [0-9A-Z], they mean 12 hexadecimal digits?

**Comment by Hussell** [comment]
In the code, in different places I'm seeing either (data|gps|node) or (data|gps|node-data). Either one of those is wrong, or both should be supported everywhere. Any idea which of the three options is the correct one?

**Comment by denislepage** [comment]
Yes, they are hexadecimal values.

**Comment by denislepage** [comment]
I am pretty sure node-data is the correct one, but I should confirm that the 2 aren’t possible.

**Comment by Hussell** [comment]
Ok, I changed a couple of other places in motusServer and motus-api and deployed both. Hopefully that's everything.

**Comment by cjardine-bsc** [comment]
Alternative ^(CTT-([0-9A-F]{12}|[0-9]{16}))

**Comment by denislepage** [comment]
I may have created the error in my quick attempt to share the regex today, but I think the current numeric serial are 15 characters.

So:

^(CTT-([0-9A-F]{12}|[0-9]{15}))
Might be wise to confirm with Bob that these are the only 2 valid patterns.

**Comment by jsayers-bsc** [comment]
V2 SS serial numbers are 12 alphanumeric digits long. We accept this, but the Register Receiver page says that _only_ a 15 digit serial for CTT receivers can be registered.

I don't see how this page can be modified from WordPress though. @Hussell can you make this change.

Also, we have an "Unknown: Anything" category. Is this worth having at all if we're saying there are constraints on the other formats? 

![image](https://user-images.githubusercontent.com/55001144/115148666-a4472d80-a02e-11eb-9172-52fa6e088004.png)

**Comment by cjardine-bsc** [comment]
The regex does allow for that. It doesn't look like this is a text_key. Perhaps it should be. 

^(CTT\-[0-9A-F]{12,16})

**Comment by denislepage** [comment]
To be clear, the regex in the database already allows the pattern above, and it's the instructions that need updating. 

The actual valid pattern is "^(CTT-([0-9]{15}|[0-9A-F]{12}))$" , which I just confirmed against all existing serial # for sensorstations, and modified the lookup tables accordingly.

In human language, this would translate to: version 1: CTT-XXXXXXXXXXXXXXX (v1: 15 numeral digits 0-9) or version 2: CTT-XXXXXXXXXXXX (12 hexadecimal digits 0-9 or A-F) 

Unknown type is perhaps mostly for historical data? We have 3 receivers from at least 2-3 years ago marked unknown now, but their patterns suggest they are SENSORGNOME. Not convinced there is a value in keeping this option, except that it may prevent some people from entering a sensor record when they have an incorrect serial # (as opposed to being able to create it and have to fix it later).

**Comment by Hussell** [comment]
Updated the text fragment. I also moved the patterns for SensorGnomes and CTT Sensorstations to the top of the list, since they're the most common.

Also updated the French translation, which was way out-of-date (missing content). I figure a poor translation of the current information is better than an excellent translation of out-of-date information.

**Comment by jsayers-bsc** [comment]
Yes it's that the instructions suggested new SS weren't accepted, even though they actually are.

Thanks for updating!
