### ISSUE TITLE
Age and Sex not in R tag deployment metadata. 

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#672]
I've added age and sex to vwR_Metadata_for_tags_deps in sandbox. 

Steffi, can you modify the R package to accept these two fields into the TagsDeps table?

**Comment by steffilazerte** [comment]
Will do!

**Comment by steffilazerte** [comment]
I've added `age` and `sex` to the `tagDeps` table in the `sandbox` branch. Current databases should be updated accordingly, but `forceMeta = TRUE` will be needed in the `tagme()` function to re-get older metadata.

On sandbox I have access to projects 1, 4 and 185. Do any of them have current age/sex data that I can look for to make sure everything's working correctly?

**Comment by cjardine-bsc** [comment]
Project 4 has age and sex data.

**Comment by steffilazerte** [comment]
Thanks

When I look at Project 4, it is pulling in Sex and Age. Good! But it also has some from another project which has a different format for sex and age:

```
  deployID tagID projectID speciesID sex   age  
     <int> <int>     <int>     <int> <chr> <chr>
1    17538 29925       200     15580 0     2    
2    21580 33186         4      4670 U     ad   
3    21582 33188         4      4670 U     ad 
```

So the R side of things is working fine, but I think there are some inconsistencies in the data base.

**Comment by cjardine-bsc** [comment]
Yeah, we don't standardize those fields. Users are allowed to store the data in their preferred coding system.

**Comment by steffilazerte** [comment]
These tags are available in at least v.4.0.0
