### ISSUE TITLE
sqlite Tag Database not given unique name when downloaded

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#673]
Users can download a SQLite database of their registered tags to install on a SensorGnome to allow the local tagfinder process the identify their own tags in real time.

When viewing the list of available downloads, they are all given unique names: 

![image](https://user-images.githubusercontent.com/55001144/74258877-fd962d00-4cc4-11ea-8ee1-595044787d85.png)

However when they are downloaded, they all come down as "tagdb" with no other identifying information. 

![image](https://user-images.githubusercontent.com/55001144/74258997-2f0ef880-4cc5-11ea-8a0a-260c602c9d8b.png)

Can we modify this so that the downloaded files reflect the unique .sqlite files seen in the list?

**Comment by Hussell** [comment]
Are both Lotek and SG receivers able to use tag databases with arbitrary names? I.e. when you rename one manually, does the receiver use it, or is it still using an older version with the default name?

**Comment by jsayers-bsc** [comment]
The Lotek receiver can't accept these, so it's only for SGs.

The SG is very specific about the name actually. It has to be "SG_tag_database.sqlite" so the files need to be renamed prior to copying to the SG. 

In cases where there are tags in multiple dateBins, they'd have to be merged into one sqlite file, then renamed to the proper name, then copied over. Unique names on the downloads would help keep them straight on the computer and reduce confusion when merging, but wouldn't eliminate the need to rename.

**Comment by adamdsmith** [comment]
A question and a comment:

1. Where is this Tag sqlite databases page accessible from the `Manage Project` interface? I cannot find it anywhere and usually have to get my sqlite files from [sgdata.motus.org](http://sgdata.motus.org).

1. And not that it's complicated, but I wrote a quick function to consolidate multiple tag sqlite files and spit out a version ready for use on the SG (and the `data.frame` representation is returned for inspection). It's doesn't do error handling at the moment...

```r
make_SG_tag_database <- function(sqlite_dbs, out_sqlite = "SG_tag_database.sqlite") {
  out_db <- RSQLite::dbConnect(RSQLite::SQLite(), out_sqlite)
  for (i in sqlite_dbs) {
    message("Processing ", i)
    con <- RSQLite::dbConnect(RSQLite::SQLite(), i)
    df <- RSQLite::dbGetQuery(con, "SELECT * FROM tags")
    RSQLite::dbWriteTable(out_db, "tags", df, append = TRUE)
    RSQLite::dbDisconnect(con)
  }
  out_df <- RSQLite::dbGetQuery(out_db, "SELECT * FROM tags")
  RSQLite::dbDisconnect(out_db)
  message(length(sqlite_dbs), " tag *.sqlite files consolidated to ", out_sqlite)
  return(out_df)
}

(ex_dbs <- list.files("C:/Users/adsmith/Downloads/", pattern = ".sqlite$",
                     full.names = TRUE))
#> [1] "C:/Users/adsmith/Downloads/project_29_2017-1_tag_database.sqlite"
#> [2] "C:/Users/adsmith/Downloads/project_4_2018-4_tag_database.sqlite" 
#> [3] "C:/Users/adsmith/Downloads/project_4_2019-1_tag_database.sqlite" 
#> [4] "C:/Users/adsmith/Downloads/project_4_2019-2_tag_database.sqlite"
all_dbs <- make_SG_tag_database(ex_dbs)

#> Processing C:/Users/adsmith/Downloads/project_29_2017-1_tag_database.sqlite
#> Processing C:/Users/adsmith/Downloads/project_4_2018-4_tag_database.sqlite
#> Processing C:/Users/adsmith/Downloads/project_4_2019-1_tag_database.sqlite
#> Processing C:/Users/adsmith/Downloads/project_4_2019-2_tag_database.sqlite
#> 4 tag *.sqlite files consolidated to SG_tag_database.sqlite```

**Comment by jsayers-bsc** [comment]
There's an option to download the SQLite file on the [Manage Tags](https://motus.org/data/project/tags) page.

I forgot that you can also download them from sgdata.motus.org. The naming scheme there is probably what should be on the Manage Tags page too.

**Comment by adamdsmith** [comment]
Hopefully I'm not missing the obvious here, but I don't see that option:

![image](https://user-images.githubusercontent.com/3195855/74272229-49080580-4cdc-11ea-8f55-e3a0c7b385de.png)

**Comment by adamdsmith** [comment]
Never mind... Manage Tags... not project

**Comment by jsayers-bsc** [comment]
Superseded by #901
