### ISSUE TITLE
CTT Powertag lifespans

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#675]
As far as I know, we don’t track lifespans for CTT powertags in the system. Not sure if those models are specified differently than lifetags?

It doesn't matter as much, but we still may want to differentiate and terminate deployments after their intended lifespan is complete.

**Comment by cjardine-bsc** [comment]
We don't have any powertags in the lk_tag_models table at this point and have none registered to Motus. When CTT is ready to register a powertag we'll have to sort out this question. It will require a conversation with CTT to determine how their lifespans are calculated and if they relate to duty cycle or BI.

**Comment by StuMackenzie** [comment]
Closed in deference to https://github.com/MotusDev/Motus-TO-DO/issues/795

**Comment by cjardine-bsc** [comment]
#795 is closed (was about Lotek Models). 

Dealing with CTT solar tags is still needed. Keeping this open.

(sorry Stu, I use this git to track my to-do list. As much as I appreciate you trying to slim down that list, there are still some things here I haven't tackled yet).

**Comment by leberrigan** [comment]
This is growing higher on the list as we get more CTT Powertags registered to the network. This is an important feature for the dashboard and management tools.

**Comment by cjardine-bsc** [comment]
Tags table and API have been updated. Just waiting on CTT to start sending us lifespans for the tags (They confirmed they would look into it this week). 

I just altered the lifespan calculation function to use the new field, so as soon as we start getting the metadata from CT we should be good to go! 

Closing as everything on the Motus side should now be in place.
