### ISSUE TITLE
Central reference materials

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#676]
This is just a general comment. I think there's a use/need for central reference materials, both for our own internal use and for others. Mostly this has to do with back end processing that is often of critical importance to how Motus works or how data is accessed, but the details of which are not always clear. Here are a couple recent examples that come to mind.

- What is the process for determining tag life? Model and deployment date are key factors here, but is there a key that could be used to determine the calculation. Does test tag status change this calculation at all? Does a default deployment date start the clock? Is there a time after which a non deployed tag is automatically considered end of life, and relatedly, how should projects manage tags that are registered (and maybe given a default deployment date) but not actually deployed for months or even years after? 

- What are the filters applied to the various views of detections on the website? Is it just runLen and motusFilter? Do the filters differ at all depending on whether it is a detection table or track view etc? [See issue 668](https://github.com/MotusDev/Motus-TO-DO/issues/668).

- When are test deployments (tags and receivers) displayed on the website? My sense so far is that this is not consistent across the board and that sometimes tests show up and sometimes they don't. I haven't noticed much more than that it doesn't seem to be consistent. 

There are a number of other similar questions that I've wondered about that don't come to mind at the moment. I've found answers in various places, or simply by asking someone. There may actually be a resource for some of this, but if so it's not always easy to find.

**Comment by denislepage** [comment]
Yes, that would be good. Those ideas are good and I am sure we can expand on that further. Perhaps we can chat about how we organize this tomorrow. Perhaps having GitHub pages, with links in a chapter of the R Book pointing to them. There may be other ways to achieve this.

Filtering in particular would likely warrant a proper peer-reviewed publication. That is one of the items I have on my wish list for the new science person, but there is content that will be incumbent on current staff to document also.

**Comment by cjardine-bsc** [comment]
Just to answer one of your points. The process of determining tag lifespan for lotek tags is documented here: https://github.com/jbrzusto/motusServer/blob/master/inst/doc/modelLotekTagLifeSpan.pdf

**Comment by StuMackenzie** [comment]
Some of this could be dealt with at least rudimentary in the underutilized FAQ - https://motus.org/faq/

which is now a little more higher level and fluffy stuff

**Comment by leberrigan** [comment]
We should try to separate the fluffy from the gritty - they don't mix well. 

The FAQ should be for more generic questions - fluffy stuff. 

For the grit, we might need something more like "Definitions and Terminology".
