### ISSUE TITLE
Add "NTS-1" to list of possible tag models during registration validation

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#678]
We have some of the new Lotek Solar Nanotags here. The Model type of these is 'NTS-1' so we'll need that as a possible model type in the registration validation process. 

I'm not sure if [NTQB2-S](https://github.com/MotusDev/Motus-TO-DO/issues/609) is going to be used as well, or if they are just going with NTS-1. If the former, then NTQB2-S would also need to be added.

**Comment by cjardine-bsc** [comment]
I've added that to the lk_tag_models in live and sandbox. Right now I've set the battery type as "solar" but tagfinder will not know what do to with that. 

@Hussell will need to add this model to the mariaDB for tag registrations. We'll need to calculate a Dt and R value that will result in a very long lifespan for these tags.

**Comment by Hussell** [comment]
Ok, I think I've figured out how to add NTS-1 to the tagfinder with a long lifespan. Try registering those tags again.

It came out with D = 4305, rt = -5.793. I'm not sure whether that makes sense or not. It seems to produce lifespans >= 20 years, if I'm understanding it correctly.

**Comment by jsayers-bsc** [comment]
All good now, those can be registered!

Still leaves unresolved the larger question of how best to use these tags as test tags given that [they are all identical](https://github.com/MotusDev/Motus-TO-DO/issues/694).

**Comment by jsayers-bsc** [comment]
The [tag ](https://motus.org/data/tags/edit?projectID=1&id=44300)registered ok, but the model isn't associated with the tag record, nor is it in the model dropdown.

![image](https://user-images.githubusercontent.com/55001144/76102264-bf2b1f80-5f9d-11ea-9a2d-0a7ab7a04ff6.png)

**Comment by Hussell** [comment]
I refreshed the cached lookup tables on all servers. That seems to have done it.
