### ISSUE TITLE
Discrepancy between timeline and plot (GPS fixes shown on one, but not the other)

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#681]
The [Receiver timeline](https://motus.org/data/receiver/timeline?year=2019&id=1283) for one of our SW Ontario receivers is properly displaying the GPS fixes. However the [deployment plot](https://motus.org/data/receiver/deployment/plot/?id=3127) isn't showing any GPS fixes at all since May 2018. The antenna activity looks mostly the same between the two (though there are lots of problematic gaps). What would account for the difference with the GPS fixes?

**Comment by Hussell** [comment]
#607?

**Comment by jsayers-bsc** [comment]
Just got out of the field and noticed this with another [receiver](https://motus.org/data/receiver/edit?id=2611&projectID=1). The [timeline ](https://motus.org/data/receiver/timeline?id=2611&year=2019)is showing far more GPS fixes than the [plot](https://motus.org/data/receiver/deployment/plot/?id=4822). That is to say that the timeline has what you'd expect, whereas the plot shows none at all. In this case anyway, the contents look the same in live, beta, and sandbox

**Comment by j-sayers** [comment]
Unfortunately I didn't include screenshots here. The plots no longer match the description.
