### ISSUE TITLE
Prevent species designation while registering tags with a "default deployment date"

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#683]
Currently, when people register tags with a default/anticipated deployment date, they can add the species at that time. However this can be problematic since the actual species tagged may not ultimately be the same as what was planned. In cases like this, it would be easy to forget to correct these down the road. I don't know how often this happens, [but it's not unheard of](https://github.com/MotusDev/Motus-TO-DO/issues/622). It also may affect the incentive to update metadata after deployment since it may seem more like everything is already done. This was discussed in the linked issue, but it may be worth bringing it up again in its own topic: 

Can we prevent species designation in cases where tags are registered with a future deployment date? Simply ignoring that field when writing to the database and sending the user a clear message that species was ignore may do the trick (it would be important that the user is well aware that the species was ignore).

**Comment by denislepage** [comment]
Don’t we have a flag that requires users to confirm their deployments if they were based on future dates? Presumably that would apply to this case to?

**Comment by jsayers-bsc** [comment]
I believe the notification to correct the future deployment date only happens after that future date has come and gone, and only when the deployment record itself is opened on the website.

There may be a notification as well to confirm the species (I don't recall), but it may be better in the case of species to simply not allow it to be set when there is a future deployment date?

**Comment by denislepage** [comment]
I’d be more inclined to change the notification to include species as well. I feel that we may end up with unconfirmed deployments without any species, which is probably worst than the occasional case where it is wrong. I am not sure how much an issue it is either way.

**Comment by cjardine-bsc** [comment]
I thought I removed the ability for users to write the species name to the DB when they register tags a few months ago following a similar discussion? 

Do you have a case of this happening recently?

**Comment by jsayers-bsc** [comment]
Yes this is a recent case, with Project 191

![image](https://user-images.githubusercontent.com/55001144/76121327-5ce41600-5fc1-11ea-9a1f-24ec824a872a.png)

However. There is no species in the deployment record so maybe it's stripped out after this log message is written...

**Comment by cjardine-bsc** [comment]
Yup. That matches my memory. I removed the ability of that process to write the species to the DB to prevent this issue. We probably need to somehow update the log to remove the species note to avoid confusing people. I think the main issue is that we don't quite easily know how to do that. So the solution I implemented is a back end fix.

**Comment by cjardine-bsc** [comment]
Closing, even though it's not 100% perfect right now, we're changing how we register tags from lotek anyway.
