### ISSUE TITLE
Odd frequency offset values, project 124

### ISSUE THREAD

**Issue by adamdsmith** [MotusDev/Motus-TO-DO#686]
Poking around the [currently available tag metadata for all projects](https://motus.org/data/downloads/api-proxy/tags?fmt=csv), Project 124 has 33 tags registered with anomalous `offsetFreq` values:

|mfgID|nomFreq|offsetFreq|
|-------|--------------|---------------|
|43309|166.3800049|-153276.3438|
|43310|166.3800049|-153276.0625|
|43311|166.3800049|-153275.8438|
|43312|166.3800049|-153276.0313|
|43313|166.3800049|-153276.0469|
|43314|166.3800049|-153276.0938|
|43315|166.3800049|-153275.9219|
|43316|166.3800049|-153276.2031|
|43317|166.3800049|-153276.2344|
|43318|166.3800049|-153276.0781|
|43319|166.3800049|-153276.0781|
|43320|166.3800049|-153275.7813|
|43321|166.3800049|-153276.125|
|43322|166.3800049|-153275.9063|
|43323|166.3800049|-153276.3906|
|43324|166.3800049|-153276.4063|
|43325|166.3800049|-153276.0781|
|43329|166.3800049|-155476.1875|
|43330|166.3800049|-155476.1563|
|43331|166.3800049|-155476.0469|
|43332|166.3800049|-155476.0781|
|43333|166.3800049|-155476.0781|
|43334|166.3800049|-155476.4063|
|43335|166.3800049|-155476.0938|
|43336|166.3800049|-155476.1094|
|43337|166.3800049|-155476.0156|
|43338|166.3800049|-155476.0469|
|43339|166.3800049|-155477.2813|
|43340|166.3800049|-155476.0625|
|43341|166.3800049|-155476.2969|
|43342|166.3800049|-155476.0469|
|43343|166.3800049|-155476.0781|
|43344|166.3800049|-153275.9688|

**Comment by denislepage** [comment]
What is the impact of this on the ability to detect those tags? Should the offset be set to 0 as a fall back?

**Comment by adamdsmith** [comment]
That's my question as well, and why I was digging in the tag database. The tag finder's [0, 12] `dfreq` filter suggests that tags likely to have frequency offsets > 4 kHz lower (in theory, looks more like ~ 2 kHz in practice), or > 8 kHz higher, than the nominal 166.38 frequency are in danger of going undetected. But I have no idea if that's true.

Does the `offsetFreq` measurement of tags during registration give some indication of the likelihood a given tag will fall outside the [0, 12] window? If so, I see ~ [90+ additional tags in danger of going "undetected"](https://github.com/MotusDev/Motus-TO-DO/files/4259383/tags_borderline_offsetFreqs.zip).

**Comment by cjardine-bsc** [comment]
As a side note to the question of how this will impact detections, I double checked and those offset values were provided as part of the registration process. To correct the immediate problem, 

@Hussell could see if he can pull the original recordings for those tags and try to determine where these odd offset values came from.  
@cjardine-bsc  can add a check on that procedure to ensure the offset value falls within a certain range (suggestions?) so this sort of issue doesn't slip by again.

**Comment by Hussell** [comment]
It looks like the user uploaded these with manually specified frequency offsets in the filenames. This is a relatively unused option, and it looks like it was done by mistake and they should have been at an offset of ~0.

**Comment by denislepage** [comment]
Ok, I suggest we change those values to zero until we hear otherwise. Catherine, couldya?

Not sure if there is a way for us to warn users about this in the future.

Notification center, perhaps, but that’s not quite as interactive as a notification at the time of registration.

**Comment by leberrigan** [comment]
Ahh, is that true? I'll let them know. They got back to me and it turns out these tags _were_ deployed... in December.  Ugh..

I am finding out where and how many adjacent stations need to be reprocessed, but I suspect it was in Brazil where there are relatively few stations.

**Comment by leberrigan** [comment]
Yes, turns out those stations that would have detected the tags haven't had their data uploaded to the network yet, so we're good!

Is it possible to get the actual frequency offset from the tags without making the user re-upload their recordings? It's better if we don't just set the offset to 0.

**Comment by cjardine-bsc** [comment]
For now I've set offset_freq to zero so the tags can be detected. I can update it if you're able to figure out how to get correct values.

**Comment by Hussell** [comment]
Actually, can you just delete those 33 tags? Then I can easily re-upload the same tag recordings with the filenames fixed.

**Comment by cjardine-bsc** [comment]
No. Remember we never delete tags, because the metadata is synced into tagfinder. We can only merge two tags together. So you can re-register them with a suffix of 0.1 and I can merge the old tag into the new one.

**Comment by Hussell** [comment]
Oh. Duh. Looks like we need internal documentation as well as external documentation. #676.

Upload done, 33 tags re-registered and ready for merging. The frequency offsets are all within -2 to +2 range, instead of -153276 like they were before.

**Comment by cjardine-bsc** [comment]
Great. @jsayers-bsc will you send me the merge statements? Thanks!

**Comment by jsayers-bsc** [comment]
Out with the old, in with the new.

Done.
