### ISSUE TITLE
Batch deprecation when tsBegin = 1970 and tsEnd is correct

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#689]
I've noticed some connected receivers where occasionally a batch will arrive with the correct tsEnd (e.g. 2020-01-05) but a tsBegin of 0 (i.e. 1970-01-01). This causes all previous batches with the same boot number to be deprecated and then deleted, even though the newest batch contains at most 1 hour of data.

This is eventually resolved when the boot number is rerun, but since that can be months later, I think that when a batch arrives with an anomalous tsBegin (< 2013), but a regular-looking tsEnd (>= 2013), it should neither be automatically deprecated nor used as a reason to automatically deprecate any other batch.

**Comment by cjardine-bsc** [comment]
Can you provide an example? I'd like to look into this a bit more. The previous batches should only be deprecated if they have the same tsBegin and tsEnd, so I'm not sure how this is happening.

**Comment by Hussell** [comment]
They're also deprecated if one batch completely covers another, so when I rerun a connected receiver I'll end up with one large batch, which causes many 1-hour-long batches to be deprecated.

**Comment by cjardine-bsc** [comment]
Can you provide an example of a receiver this impacts?

**Comment by Hussell** [comment]
I just reran the receiver I was looking at, so everything's fixed on that one now. It was SG-DD76RPI3082F, boot number 6.
