### ISSUE TITLE
Sensor registrations to project 0

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#690]
Josh noticed a case where a sensor was registered to project 0 after it had been registered to an existing project. I looked and this is not an isolated incident. Looks like it started happening around July 2019. 

Off the top of my head I'm not sure how this is happening. The approved column is set to true for the project 0 sensors, which suggests the problem is in the import form tagfinder. I suspect that when the receiverID is missing from sensor_hash_keys it is always writing a new record to the sensors table and not checking to see if a sensorID already exists. Though I'm not positive. 

SELECT *
  FROM [motus].[dbo].[sensors] a inner join [motus].[dbo].[sensors] b on a.receiverID =b.receiverID 
  where a.project_id = 0 and b.project_id <> 0
  and a.last_edited_dt > b.last_edited_dt

**Comment by Hussell** [comment]
Possibly related to #526? It looks as though this has always been happening, but the project 0 ones were manually cleaned out last summer.

The registrations to project 0 all seem to happen on the first date at which data was uploaded to sgdata. Tracing through, a call is made to register the receiver through the API, which in turn uses prInsertSensorsHashKeys with a NULL project. The procedure converts the NULL to project 0. At the end of the procedure, if the insert into sensors_hash_keys has been successful it also inserts into sensors, provided the receiver isn't already registered to project 0.

**Comment by denislepage** [comment]
Looking at the insert proc, I am actually not seeing a provision to prevent inserting a receiver to project 0 if it has already been registered in a real project, or replace the existing project 0 to the new one. I think we did this for tags, but sounds like we didn't do it for receivers. So any registration coming in for project 0 will currently be added to sensors, whether something else already exists or not.

**Comment by cjardine-bsc** [comment]
Yup. Looks like it. 

I'll change the proc.
