### ISSUE TITLE
Increase default size of Notes in the Deployment page

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#691]
The Notes section of the Deployment is a very useful area to write comments regarding site visits, or reminders to do at the next visit, especially if site visits are conducted by multiple parties.

But the default size is really small and barely displays more than one line at a time. Looks like the default height is 30px. **Could this increased to something like 150px?** This would really improve the usability of this field.

![image](https://user-images.githubusercontent.com/55001144/75577029-188bcf80-5a2f-11ea-9c14-bab0f1c65db9.png)

**Comment by pmorrill** [comment]
I have increased the height 4x, to 120px

**Comment by jsayers-bsc** [comment]
I'm not seeing that for some reason (in live or beta).

**Comment by pmorrill** [comment]
try sandbox? It should be there in beta, but we have not deployed to live yet, I don't think.

**Comment by jsayers-bsc** [comment]
Hmm, I actually don't see it in sandbox either!

**Comment by Hussell** [comment]
I delayed deployment of these fixes to beta this week because of a backlog of processing, which I was reluctant to interrupt. As it turned out, there was a bug causing the processing to go into an infinite loop, so I should have just deployed anyway.

**Comment by pmorrill** [comment]
Thanks Jeremy for the update. I checked it this AM and was puzzled!

**Comment by jsayers-bsc** [comment]
That's great, much better!
