### ISSUE TITLE
SensorGnome.org certificate expired 2020-03-01

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#692]
![image](https://user-images.githubusercontent.com/55001144/75812258-e5617d00-5d5b-11ea-937c-c6753d8186a8.png)

**Comment by dfloer** [comment]
Already working on this. Something went wrong with the automated Let's Encrypt certificate renewal.

**Comment by denislepage** [comment]
I have been getting some notifications today about let's encrypt needing to reissue certificates (not sensorgnome related) due to some issues at their end. In my case, they were set to expire tomorrow, but it may have been related.

**Comment by dfloer** [comment]
This has been fixed with a new SSL certificate.

**Comment by cjardine-bsc** [comment]
Closing! Whoo hooo!
