### ISSUE TITLE
Default deployment not created during registration

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#693]
This may not be an issue that needs to be resolved by us with the future change to registration directly by Lotek. 

Either way, it's worth bringing up.

I registered tags for two projects in the last couple months, both of which I gave default/anticipated deployments for. 

This was tags for [Project 231](https://motus.org/data/project/tags?projectID=231) and [Project 258](https://motus.org/data/project/tags?projectID=258).

However in neither case was there any deployment made at registration time as expected. Other more recent registrations properly assigned the future deployment during registration. [(Example, most recent registrations by Project 191)](https://motus.org/data/project/tags?projectID=191).

I just checked back on the registration files I submitted and the dates are there, and nothing jumps out as being wrong.

> motusProjID: 258
> tagModel: NTQB2-1
> nomFreq: 166.380
> species: 
> deployDate: 2020-01-17
> codeSet: Lotek4

**Comment by leberrigan** [comment]
I wonder if the blank species field tripped it up. Next time try omitting that line entirely and see what happens.

**Comment by jsayers-bsc** [comment]
I just noticed this happen again, with 25 tags I registered with a default deployment, but that ended up being registered with _no_ deployment.  

I had forgotten about Lucas's suggestion to try removing the species line, so the verdict is still out on whether that helps.

And I realize that hopefully soon registration will occur at the time of purchase from Lotek, so this will (again, hopefully soon) be a moot issue.

But it's worth mentioning anyway...

**Comment by jsayers-bsc** [comment]
This is evidently still an issue, as reported by Project 113. Unfortunately this seems to be an issue when the species is left blank, which is what we want people to be doing for anticipated start dates.

**Comment by jsayers-bsc** [comment]
No longer a concern with Lotek pushing tag registrations

**Comment by cjardine-bsc** [comment]
Documenting the decision that deployments can no longer be created upon tag registration.
