### ISSUE TITLE
Map of Potential Receiver Hosting Sites

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#696]
One of the most difficult parts of establishing a station is finding a suitable location for hosting. From time to time we find potential sites, but we have no use for them - or at least funding to support them. Many of these potential sites come from folks who email us and would like to be part of the network, but do not have the means to purchase and install a station themselves.

I think it would be very helpful for collaborators if we were to start mapping these sites with contact information so that any _logged in user_ could see where they could easily place a station. The advantage of this approach is that collaborators across projects could see the same potential sites and team up to install stations at them, similar to what's happening with the PIF Western Working Group. We can have a form on the public side of the website that would allow anyone to submit their property into the database to be mapped, but we obviously can only make the map visible to registered users.

**Comment by StuMackenzie** [comment]
A network or collaborator planning map is part of CANARIE 3 - this is a logical extension of this. The Western Working Group has already established one - see https://ssrsmaps.maps.arcgis.com/apps/View/index.html?appid=26e8758ecacf49ab8f2dab4588cffd2c&extent=-136.3479,27.0863,-84.2287,49.9991

I'd like to get stuff like this running through Motus HQ that can be established across the board.

**Comment by adamdsmith** [comment]
Agree with both of you. This would be a useful feature, and I can think of several partners ready to go if funds were available. And I agree the more centralized information like this can be maintained and accessed, the better, otherwise few will ever find it...

**Comment by mmwebb** [comment]
This is a large part of Bird Conservancy's project to expand across the Great Plains and Chihuahuan Desert.  We're hoping to develop a planning map showing all planned station locations from which we could phase development as funding allows.  It would be great to have a place that all of our individual effort could feed into and inform, and be available to others.

**Comment by StuMackenzie** [comment]
Closed in deference to https://github.com/MotusDev/Motus-TO-DO/issues/873
