### ISSUE TITLE
Error while trying to log in via R package

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#699]
User in project 20 has been having difficulty logging in to download data through the R package. Every time she tries she gets: 

```
Error in value[[3L]](cond) : 
  Motus login failed with error message: Error: $ operator is invalid for atomic vectors
```
She's tried the usual steps (rebooting, restarting/refreshing desktop state/reinstalling RStudio, etc) but has been getting the same error over the past several weeks. She can log on to the website and confirmed the password is correct.

This look familiar to anyone?

**Comment by denislepage** [comment]
It'd be useful to see if we can replicate the issue here. We'd likely need her login details and password (not to share on git). The atomic vector error is typically an indication of missing data.

**Comment by steffilazerte** [comment]
A couple of questions to narrow things down:

- Was the user able to access data in past? Is this a recent issue?
- Has the user tried downloading the sample data? I.e. access project 176 with username `motus.sample` and password `motus.sample`? This would help figure out if it's a credentials issue or a coding issue.
- If there is a similar problem with the sample data, has the user tried updating R (you said RStudio, but R is usually the problem), what about all packages (`devtools::update_packages()`)? Sometimes intermediate package versions can have weird effects that are really hard to account for.

If accessing the sample data works, then it might be a credentials issue that the R package isn't handling very gracefully.

**Comment by jsayers-bsc** [comment]
I do know she has tried changing her password to something else and trying with that, with the same outcome.

I've asked those other questions and will post when I hear back.

**Comment by denislepage** [comment]
Have we checked that she has the right permissions?

**Comment by jsayers-bsc** [comment]
She updated R and, together with again ensuring that the packages were updated, seems to have resolved it for her. All good!
