### ISSUE TITLE
Best practices for Test Tags

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#700]
Following up on [this post](https://github.com/MotusDev/Motus-TO-DO/issues/694), which was the result of having multiple Test Tags with identical properties...

I'm thinking now that I should _not_ have registered each of these tags individually. Doing so resulted in multiple tags non differentiated properties. Instead I should only have registered each identical set _once_. 

That becomes a bit more complicated when sharing these tags across projects though. In that case, would the one individual tag simply be _copied_ over to the target project? It would appear as if there was only 1 tag showing up in each of the projects, though there would actually be multiple physical tags. 

Does that seem reasonable, or is there a better approach?

**Comment by jsayers-bsc** [comment]
To make Test Tags more conspicuous, could we incorporate something from the following list of options:

- Include Test Tag as an additional column in the detections table
- Add "TEST TAG" or similar as a species option
- Include the "Test" flag in the AllTags view

Some of the above may already exist in some way and I'm just missing them, or they aren't being utilized often. Anyway, just a couple suggestions to make Test Tags stand out from the crowd a little more easily.

**Comment by jsayers-bsc** [comment]
After hearing from Catherine, it sounds like my suggestion above was not a good one. Identical test tags _should_ be registered individually since there may be small differences in the properties, even though nominally they may be the same. So I didn't screw that up :)

But that still leaves the question of how to deal with them. Because multiple nominally identical tags are registered, they are identified as ambiguous tags, don't show up in detection tables, and show up in plots as NO_PROJ#999999 M.0 regardless of their other properties. 

One option is to not use identical tags as test tags, but that seems to be a waste of limited tag ID codes (and doesn't resolve what to do with the existing tags, including about a dozen not-yet-registered solar tags).

**Comment by StuMackenzie** [comment]
- [ ] TODO: Need to write instructions on Test Tag Etiquette/Best practices

**Comment by StuMackenzie** [comment]
Closed in deference to Slack #Guides
