### ISSUE TITLE
What is a "pending" deployment?

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#701]
I've noticed both receiver and tag deployments with a status of "pending". 

There are deployment records for them, but there are no start dates (unlike a "default deployment date" for a tag). 

Some properties of a ["pending" tag deployment](https://motus.org/data/tag/deployment/edit?projectID=193&id=24107) cannot be changed, such as the Test field. 

Additionally, the "pending" status triggers an overlapping tag deployment error if there is a real deployment associated with that tag. See [data issues for Project 193](https://motus.org/data/issues?id=193#v_tag_overlap_deploy_reg).

I'm not sure off the top of my head if similar data issues can be triggered with "pending" receiver deployments, but they also do not have start dates associated with their deployment record.

I'm very unclear about how "pending" status is set and what its purpose is? And to resolve problematic "pending" deployments, should I simply delete them?

**Comment by leberrigan** [comment]
From what I understand, pending deployments are intended for tags with deployment dates set in the future. This should only apply to tags so the fact they exist for receivers as well raises a red flag.

After looking at your examples, it seems that 'pending' tag and receiver deployments are also associated with deployments without any dates which probably shouldn't be lumped into the same category. These should throw an error to let collaborators know that their deployments are incomplete in case they did this by mistake. For instance, they may be missing detections from those tags as a result of this.

**Comment by jsayers-bsc** [comment]
There seems to be something else going on here though. At the moment there appear to be 697 "pending" tag deployments in the DB. Of those, only 34 have a start date associated with them (all of which are in the future). The rest of them have no start dates at all, and some of the date bins go back as far as 2013.

[Here is another example from the tags without species error](https://motus.org/data/issues?id=211#v_tag_deploy_species). There are no start dates or any other metadata associated with them, beyond the fact that deployment records exist. For many of these, a true deployment also exists alongside the "pending" deployment.

**Comment by adamdsmith** [comment]
I always assumed "pending" simply meant registered but not deployed, whether for tag or receiver.

I'm not sure if/how Lotek monitors the tag db to inform their tagID assignment, but there should be some designation that alerts them to the fact that tags are registered but not deployed so they don't produce and distribute ambiguous tags.

**Comment by denislepage** [comment]
We do calculate the information about active tags and have offered it to Lotek several times, but I don’t think it’s been properly built into their system yet, unfortunately.

**Comment by adamdsmith** [comment]
Thanks. That is unfortunate. This going to be an increasing issue with solar-powered tags on the landscape.

**Comment by jsayers-bsc** [comment]
Looking at the 34 tag deployments currently in the DB with start dates in the future, all have status Pending. Makes sense. Presumably this is set automatically whenever a deployment is created with a future date...? Also presumably when the current date is no longer earlier than the deployment start date, that status is changed in the background from Pending to Active...?

What's strange though is that the majority of the Pending deployments in the DB at the moment, have _no_ start date at all. Some of those may simply be registered tags with no deployment (if that is how "pending" is determined) but many of the tags also have deployments associated with them. 

Those are triggering Tag Deployment without Species and even Overlapping Deployment errors for some, despite the fact that these deployments don't really exist. I'm wondering if some of these "pending" deployments exist only in error.

**Comment by cjardine-bsc** [comment]
The status field is a computed field in the table. But it has little bearing on any of the web code or data validation errors. 

(case when [dt_start]<getdate() AND ([dt_end] IS NULL OR [dt_end]>getdate()) then (2) else case when [dt_end]<getdate() then (1) else (0) end end)

The pending deployments are triggering errors in the data validation centre which will hopefully induce users to delete the deployment if it is incorrect. Which is the intended purpose. I dont believe any changes are needed to that process?

We consider all deployments for a tag in the vwTagsActive view (this is what we occasionally provide to lotek to help them guide choices about which tags to manufacture. We've been trying to encourage them to access this table automatically. That conversation is ongoing). What that means is that if there is another deployment for the tag that has used up all off the battery life for a tag it will not be listed in this view as active, even if there is another pending deployment. So while these incorrect deployments are slight nuisances and I'd love to see the users clean them up they shouldn't be having consequences on that process. 

Note that the veTagsActive view also has an expiry built in, so if a tag has been registered for a long time (I think its three years I can check if you're curious) but has never been deployed it is considered deprecated and the codeset is released. The user gets a critical error warning them of this in the validation centre. 

Hopefully that clarifies things. I'm not sure what we still need to address here. We could potentially have someone go through all the pending deployments and communicate with users to help get them cleaned up, but in terms of the existing infrastructure and systems I dont think they are having dire consequences, though the untidiness makes me twitchy. :-)

**Comment by jsayers-bsc** [comment]
That does explain a bit. Many of the pending tag deployments have a NULL dt_start, so they'd resolve to status pending given the expression above. 

Ok so maybe the question then is, why are there deployment records without start dates? I guess that's what caused my confusion: there are pending deployments _with_ start dates, and there are pending deployments _without_ start dates (the majority of them actually).

In the two cases above, this came about from people going through their issues to try to resolve them (good!) but then being confused why there were overlapping deployments for a tag they only deployed once. Sounds like just deleting that weird pending one is the way to go.

**Comment by StuMackenzie** [comment]
Closing unless additional action and assignment can be identified. Perhaps a Motus Metadata Cleanup Issue #869

**Comment by cjardine-bsc** [comment]
Yup. Pending deployments will no longer be created with tag registration so this should no longer occur (historic metadata still needs to be captured).
