### ISSUE TITLE
Consistency in Variable Names

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#706]
This is a broad issue that applies to the Motus website and R package. As far as I'm aware, we have no reference for variable names, nor a standard naming convention when we create new variables. It's important we remain consistent between the website and the Motus R package, which is why I've put this here in the same Git.

Here are just a few examples where I've encountered inconsistencies or other problems with variable names:

**Motus Website**
- Device ID vs Receiver ID vs Deployment ID (vs Sensor ID vs Serial Number). See: https://github.com/MotusDev/Motus-TO-DO/issues/431
- Various tables still just say 'ID' (explore project tags and receivers, manage tags).
- Receiver ID on edit receivers is actually the serial number.
- Period vs. Burst interval. Burst interval is more intuitive.

**Motus R Package**
-  tagDeployID, tagDepLat, tagDeployStart, tagDepComments. (compare to: recvDeployID, recvDeployLat, etc.)
- sigsd, freqsd - are we not using camelCase?
- slop might be better named 'pulseSlop'.
- 'done' might be better named 'runEnd'. 
- recvUtcOffset should be recvUTCOffset if following convention, right?
- In general, variable prefixes should be consistent and always present, such as:
  - isRecvMobile >> recvIsMobile
  - port >> antPort
  - deviceID >> recvDeviceID
  - fullID >> tagFullID
  - bootnum >> recvBootNum or at least bootNum
- Changing variable names is tricky. It was done in the past without notifying collaborators which results in some frustrated emails. If we are to do it again, we need to provide a table with old vs. new names so that code can be more easily adjusted.

**Comment by denislepage** [comment]
This is a good reminder moving forward, but many of these are inherited from other systems built separately and unlikely to be resolvable without a ton of dominos falling.

We’ve made some effort to keep user-facing variable names somewhat consistent, but that’s far from perfect.

I don’t think we can seriously consider fixing this without spending months dealing with repercussions, unless we only did this for external variables in the R package and asked users to start from a clean slate. Even then, users who have build code on top of our package will then have to deal with fallouts.

**Comment by StuMackenzie** [comment]
closing. available for future reference.
