### ISSUE TITLE
Deployment timelines

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#708]
Can we please make 'Deployment timelines' accessible from all other menus of station data?

Eg. on the pop-up box from the receiver map, and from any receiver summary page - eg. https://motus.org/data/receiver/deployment/detections/timeline?year=2020&id=5857

We can discuss Thursday if neccessary.

**Comment by jsayers-bsc** [comment]
Along these lines, swapping the summary for previous deployment with the summary for the current deployment would be helpful. (in the pop up box in the map)


________________________________

**Comment by leberrigan** [comment]
These are raw data plots that are better suited for edge cases/diagnostics. We'll be including such plots in the explore dashboard, albeit with filtered data.
