### ISSUE TITLE
Problems with new "No Recent Data" error in Data Issue

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#710]
There seem to be some inconsistencies in the "No Recent Data" warning/error message in the Data Issues page. These are the new ones identifying stations that have not had data uploads in 1 year or 6 months.

Occasionally, when I log in, each of these is duplicated. At least once I've logged in and there were no issues at all in this category. This morning I noticed that there are three of each record.

![image](https://user-images.githubusercontent.com/55001144/78360281-8d997a00-7584-11ea-9267-3cdb2f01e83f.png)

Also, a minor note, this _No Recent Detection Data(3 months)_ should read, **6** months.

**Comment by cjardine-bsc** [comment]
Right you are. I didn't include the project clause in the proc. I've fixed that. 

You should be good to go.
