### ISSUE TITLE
No SQLite tag database available

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#712]
I'm trying to download the SQLite tag database for the Test Tags project (322) but when I go to the download page, there is nothing there. I've tried in sgdata.motus.org as well.

![image](https://user-images.githubusercontent.com/55001144/78715063-da65b380-78ea-11ea-8303-b7a0019ba3b7.png)

I'm wondering why I'm not seeing the .slqlite file here. These tags were all originally registered to Project 1 and then moved to Project 322. Maybe that has something to do with why this wasn't generated or available from Project 322? Is there another way of creating this file?

**Comment by Hussell** [comment]
I can manually recreate the tag database for any project. I've just done so for projects 322 and 1 (just in case). Tags being moved after registration is indeed the reason this file wasn't created; it's normally (re)created once when tags are registered with sgdata.
