### ISSUE TITLE
Data validation failing

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#714]
In the past couple weeks I've been seeing this issue off and on on the Data Issues page: 

_The last attempt to validate your data failed with the error message: org.bsc.exceptions.DBException com.microsoft.sqlserver.jdbc.SQLServerException: Error converting data type varchar to float. SQL: "prDataValidation_pr @proj = NULL" at org.bsc.SQLPreparedStmt.executeUpdate(SQLPreparedStmt.java:244) at org.bsc.motus.process.Job.run(Job.java:334)_ 

In these cases only a portion of the issues show up (those pertaining to detections outside a receiver deployment tend not to). The error has been pretty consistent in the last few days.

**Comment by denislepage** [comment]
That's been a long standing issue, though intermittent. It's be good to sort out which part of the validation is crashing. That's a Catherine thing, but you can let me know if needed.

**Comment by cjardine-bsc** [comment]
I think this is the first I've heard of this? We had an issue before with the procs queue failing when running prDataValidation_pr, but not a type conversion error. 

Ah, found the issue. Paul registered a test tag using the lotek registration API with a mfg_id = "test-test-16" which broke a compare statement that assumed it could cast non CTT mfg_ids to floats. 

I've put in a condition to filter out cases where the mfg_id is not numeric. And the proc is back in action. 

It's now a short standing issue. It would be excellent at limbo. https://www.youtube.com/watch?v=YvotR3WuVzE

**Comment by jsayers-bsc** [comment]
Resurrecting this (though the underlying problem here looks different...). I've been seeing this error a lot in the last few days, which again results in receiver-related issues not showing up.

`org.bsc.exceptions.DBException com.microsoft.sqlserver.jdbc.SQLServerException: The query has timed out. SQL: "prDataValidation_pr @proj = NULL" at org.bsc.SQLPreparedStmt.executeUpdate(SQLPreparedStmt.java:244) at org.bsc.motus.process.Job.run(Job.java:334)`

**Comment by denislepage** [comment]
I made some tweaks and narrowed down the parts that are slower to run. I sent this separately to Catherine.

I would be a bit reluctant to increase the timeout of 30 minutes we have now. I’d rather change the rules we are using to make them simpler to calculate in a couple places, if we can’t achieve the same more efficiently.

**Comment by jsayers-bsc** [comment]
Sorry everyone, but:

`org.bsc.exceptions.DBException com.microsoft.sqlserver.jdbc.SQLServerException: There is already an object named 'tagcombo2' in the database. SQL: "prDataValidation_pr @proj = NULL" at org.bsc.SQLPreparedStmt.executeUpdate(SQLPreparedStmt.java:244) at org.bsc.motus.process.Job.run(Job.java:334) `

**Comment by cjardine-bsc** [comment]
No biggie. Fixed.

**Comment by jsayers-bsc** [comment]
This error has been popping up the last couple days:

`org.bsc.exceptions.DBException com.microsoft.sqlserver.jdbc.SQLServerException: Socket closed SQL: "prDataValidation_pr @proj = NULL" at org.bsc.SQLPreparedStmt.executeUpdate(SQLPreparedStmt.java:244) at org.bsc.motus.process.Job.run(Job.java:334) `

**Comment by jsayers-bsc** [comment]
This particular issue is resolved. I'll open a new issue next time there is an error reported with the data validation.
