### ISSUE TITLE
Species search of tags only works for scientific, not common, name

### ISSUE THREAD

**Issue by adamdsmith** [MotusDev/Motus-TO-DO#715]
Filter options indicate either should work, but only scientific name filters work

**Comment by Hussell** [comment]
URL? Or is this in the R package?

**Comment by adamdsmith** [comment]
Under the "Manage your tags" page of a project.

For example:

https://motus.org/data/project/tags?projectID=253

**Comment by pmorrill** [comment]
I have added the English name to the search, in beta9 and master

**Comment by pmorrill** [comment]
Test and close???

**Comment by adamdsmith** [comment]
Seems to work for me now...
