### ISSUE TITLE
R package access issue - 

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#718]
Please respond to - Luke DeGroote <degroote.1@gmail.com>

I can’t access the data through R.  I’m getting the following error:

 

Error in value[[3L]](cond) :

  The motus data server rejected your login credentials

I updated my password on the website, is there a time lag between updating it and when it will work in R?  

 

Any suggestions on how to get the login to work?

 

Sincerely,

 

Luke DeGroote

Avian Research Coordinator

Powdermill Nature Reserve

Carnegie Museums of Natural History

Office 724-593-5521

Cell 724-771-3919

**Comment by denislepage** [comment]
Option 1 (easy) do motusLogout() or close and start a new session. May work.

Option 2: update the motus package and any other R packages.

Option 3: reinstall R. You would be surprised how many time this was by far the easiest option rather than fiddling with broken packages.

**Comment by StuMackenzie** [comment]
Thanks! 

Luc, this may be useful in our FAQ somewhere. Seems to come up a lot.

S

____________________

**Comment by StuMackenzie** [comment]
For our records, 2 worked.

____________________

**Comment by steffilazerte** [comment]
I can add this to the motus package README and perhaps in the motusRbook?

**Comment by leberrigan** [comment]
I think this should also be added in the Motus R book, maybe in a troubleshooting section at the end?

**Comment by steffilazerte** [comment]
That would be a good spot for it, I'll add it there.
