### ISSUE TITLE
Working with very large datasets

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#721]
A few questions have come up recently from members of Project 279. One common theme is that they are having difficulty simply getting their project's data into a format that they can work with. I've been trying to work through much of this with them and have been having considerable issues on my own computer.

Project 279's .motus file is just over 6 gb and contains nearly 52 million records, of which 50 million are Eurasian Blackbird.

It took a couple weeks with multiples of them attempting prior to successfully downloading the entire file. The timeout issues experienced in the last couple weeks thanks to Covid-related internet stress were part of the problem. 

But once they had the local .motus file, they have been running into all sorts of issues collapsing the data into a flat data frame to work with. Subsetting the data prior to collapsing works in cases where only a smaller portion is needed. (And the new alltags view without the GPS hits does help.)

```
## Define the start and end date desired
start_date <- as.numeric(as.POSIXct('2020-01-21'))
end_date <- as.numeric(as.POSIXct('2020-04-26'))

## Filter the entire table by the date criteria
tbl.tagSubset <- tbl.alltags %>% 
  filter(ts > start_date, ts < end_date)

## collect the subset of data into a dataframe
df.tagSubset <- tbl.tagSubset %>% 
  collect() %>% 
  as.data.frame()
```

But in this case, their focus is the Eurasian Blackbird over the entire period, so they essentially need 50 million records at any given time. 

As I've found by trying to help them, my new work computer with 12 GB of RAM is not up to the task. Even when closing down all non-essential programs, any process that attempts to use such a large portion of the records eventually uses up all 12 gb of RAM and encounters the "unable to allocate memory" issue and the process fails. 

I thought maybe that by subsetting only a portion of the records at a time and adding them to a data frame as I went along, that might make a difference. I also tried using `data.table::data.table` as this apparently has better memory management and performance with large datasets than `base::data.frame`, but this again ran into the same issue.

```
## min hitID present in the alltags view
min_hitID <- as.numeric(dbGetQuery(sql.con, 'select min(hitID) from alltags'))

## max hitID present in the alltags view
max_hitID <- as.numeric(dbGetQuery(sql.con, 'select max(hitID) from alltags'))

## number of hits to subset by in each iteration. Specifying integer with L will keep scientific formatting out of the query string
sub_hits <- 1000000L

## create empty data table, and appending it with "temp" until the end
dt.alltagsTemp <- data.table()

while (min_hitID < max_hitID) {
  query <- paste0('select * from alltags where hitID >= ', min_hitID, ' limit ', sub_hits)
  dt.sub <- as.data.table(dbGetQuery(sql.con, query)) # execute query and attach retrieved rows
  dt.alltagsTemp <- rbind(dt.alltagsTemp, dt.sub) # append the retrieved data to the data.table
  print(paste0('Retrieved ', nrow(dt.sub), ' rows between hitIDs ', min(dt.sub$hitID), ' and ', max(dt.sub$hitID)))
  rm(dt.sub) # does it help to remove this between loops? who knows....
  min_hitID <- max(dt.alltagsTemp$hitID) + 1  # set the new min_hitID to 1 more than the max just retrieved
}

## assign the now complete data.table to a new variable and delete the one with "temp" in the name
dt.alltags <- dt.alltagsTemp
rm(dt.alltagsTemp)
```
On my own personal laptop — purchased in 2012, weighing literally more than 10 lb, but crucially with 16 gb of RAM — I can get all 50 records into one data frame/table without much issue using multiple methods (though it takes some time). But it simply doesn't work on my newer computer with "only" 12 GB of RAM. 

I'm not sure what the largest dataset is for any project, but I doubt it's this one. And they are all likely to get a lot bigger as time goes on (and as CTT tags, with BI's of 2 seconds, become more common). Are there any suggestions or techniques for how best to work with datasets of this size?

**Comment by denislepage** [comment]
I’m not sure if I am stating the obvious, but here goes. Operations does within dplyr before the data is collected in a dataframe do not require any substantial memory. The package is merely building a SQL command to work against your sqlite file. One issue is that the functions and operations allowed at that stage are much more limited, as they have to be supported by sqlite.  Removing as may fields as possible when using collect will also help memory. As soon as you use collect, you are bound by how much RAM your computer has, there’s no way around that.

Another option is to subsample the data. Chances are they do not need a hit every 2 seconds. Doing this isn’t necessarily easy, and several strategies are possible depending on what they want. Taking 1 out of every X hit is one option, or summarizing the data by blocks of hourBin, minuteBin or some unit of time is another option. I suspect a group query on 50 million records isn’t going to work well in sqlite. Cutting it down to one hit per minute may bring down the size by a factor of about 30 for CTT tags. 50 million records is big(-ish) even for a Server with 64 GB of RAM.

If you can figure out which rows you want to use from the hits table, I would probably advocate creating a new table in sqlite that has the hitID field of every record you want to retain, and do an inner table join on hitID before collecting. With this approach, someone should be able to 1) get a dataframe of all hits records with only the minimal set of fields to make decisions about filtering (hitID, motusTagID, and ts may be enough). If that is even too big, you could break that step by tag and/or receiver, etc. 2) design a function that identifies which rows to keep for each tag and period (e.g. min value of hitID when each hourBin = ts/3600 or minuteBin = ts/60), 3) insert the subset of hitID’s into a new sqlite table, ensuring that hitID is set as the primary key and 4) include the new table in a join when extracting the data, and before converting to a dataframe.

In theory, the new table could be preserved for future use. You’d have to figure out a way to only add new hitID’s as they continue to accumulate. IE, use the max hitID from your new table as a way to filter the first step above (hitID > max(newtable.hitID)).

There are other ways, probably some better ones, but this is where I would probably start.

**Comment by jsayers-bsc** [comment]
Thanks Denis, those tips are helpful!

**Comment by jsayers-bsc** [comment]
Superseded by #900
