### ISSUE TITLE
Contact Info in Motus R Package

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#722]
Right now the contact information in the Motus R Package vignette links to John B's email and should be removed. This email is present on every page.

As discussed on our call today, we don't need to include an email here.

**Comment by steffilazerte** [comment]
Right now, every function has an author and email associated with it (except the ones I added). Generally, it's unusual for R package functions to be referenced like this. Contributions are usually listed in the DESCRIPTION and that's it. 

Should I 
a) Remove author names and emails from functions, or
b) Remove only emails from functions

**Comment by leberrigan** [comment]
Option A is fine enough. If you want, you can link to our Motus Contact page if you think a contact would be appropriate: https://motus.org/contact

**Comment by steffilazerte** [comment]
Sounds good. I think it would be appropriate to list Bird Studies or Motus in the DESCRIPTION as an author. 

Relevant roles might be:
-  "Funder", similar to rOpenSci (e.g., https://github.com/ropensci/taxize/blob/master/DESCRIPTION#L65-L67), or 
- "Copyright" Holder, similar to BC gov (e.g., https://github.com/bcgov/bcgroundwater/blob/master/DESCRIPTION#L6)

**Comment by steffilazerte** [comment]
@denislepage any opinion on adding Bird Studies or Motus to the DESCRIPTION as an author?

**Comment by denislepage** [comment]
Birds Canada is fine. If you want/need an email, you can use motus@birdscanada.org

**Comment by steffilazerte** [comment]
Great, should it be Funder or Copyright holder, or both? 

Funder [fnd]
- A person or organization that furnished financial support for the production of the work 
- similar to rOpenSci (e.g., https://github.com/ropensci/taxize/blob/master/DESCRIPTION#L65-L67)

Copyright holder [cph]
- A person or organization to whom copy and legal rights have been granted or transferred for the intellectual content of a work. The copyright holder, although not necessarily the creator of the work, usually has the exclusive right to benefit financially from the sale and use of the work to which the associated copyright protection applies 
- similar to BC gov (e.g., https://github.com/bcgov/bcgroundwater/blob/master/DESCRIPTION#L6)

**Comment by denislepage** [comment]
Hm. That’s a bit complicated. The original package was created by Acadia U., which we modified.

We’re at least a funder.

Given that the code is available under GNU, does copyright apply? Intellectual property is probably better for this, and that would be joint between Acadia and Birds Canada, or we just use funder.

I’d go with funder only, I think.
