### ISSUE TITLE
Project 250 missing data - reprocess receiver data

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#730]
Maybe related to #731, but probably not.

There is a test tag that should be showing up in the receiver data, but they are only showing up in a few. Data is all uploaded at around the same time, shortly an hour or more after the tag deployments are registered. 

All receivers have on-board tag databases and collaborator confirmed test tag was detected by receivers before downloading data. Raw data from receiver has the exact same pulses as what was seen on SG live web interface when confirming test tag detections. Data uploaded to Motus.org shows antenna activity, but no tag detections for most stations, except for three for some unknown reason (deployID: 6047, 6048, 6049). As far as I can tell, this is not an issue with the Sensorgnome, but an issue with metadata and the Motus processing server.

Can we have the latest two batches from the following receivers reprocessed to verify this issue is?

Deployment ID | Receiver
-- | --
6020 | SG-AAFFRPI33E39
6019 | SG-CC66RPI3E120
6022 | SG-2715BBBK0304
6050 | SG-84AERPI36BD3
6046 | SG-905CRPI3DEA0
6044 | SG-6F19RPI385F8
6043 | SG-DBC4RPI312EF
6042 | SG-E07FRPI33B9F
6051 | SG-23C5RPI33D16
6056 | SG-CC66RPI3E120
6057 | SG-905CRPI3DEA0

**Comment by Hussell** [comment]
I'm assuming the test tag you're looking for is the same one from #731. It has one deployment, from May 15th to midnight June 3rd/4th. If you're looking for hits after that, you'll need to extend the existing deployment or create a new deployment.

SG-AAFFRPI33E39 - rerun
SG-CC66RPI3E120 - rerun
SG-2715BBBK0304 - no uploads since 2019-10-10
SG-84AERPI36BD3 - data from June 3rd rerun
SG-905CRPI3DEA0 - data from June 1st to 4th rerun
SG-6F19RPI385F8 - data from June 3rd rerun
SG-DBC4RPI312EF - data from May 31st to June 4th rerun
SG-E07FRPI33B9F - no data during the test tag's deployment
SG-23C5RPI33D16 - data from June 1st rerun

**Comment by leberrigan** [comment]
Thanks for that. The tag we're looking for is actually [44970](https://motus.org/data/tags/edit?projectID=250&id=44970) which has a deployment overlapping the period that I'm expecting detections (June 5th and 8th).

I just checked the data from your reruns and it looks like this fixed the problem! This is very helpful - it's likely the issue was that the collaborator didn't leave enough time between registering a deployment and uploading receiver data during. It is strange, however, since they did these steps many hours apart, but on the same day. They did three tag tests at all stations over three days and uploaded the data on two days. Each each time the same 3 stations had all detections while the rest only had detections from the first day, even the receiver data was uploaded in a different order each time. 

Regardless, I think this solved the issue. I'll get in touch with the collaborator to confirm.

**Comment by Hussell** [comment]
For future reference: the tag finder updates its database of tag deployments once per day, so we should recommend that all relevant tag deployments be created or updated at least a day before data is uploaded.

**Comment by jsayers-bsc** [comment]
> For future reference: the tag finder updates its database of tag deployments once per day, so we should recommend that all relevant tag deployments be created or updated at least a day before data is uploaded.

Thanks, that's good to know.

**Comment by denislepage** [comment]
Is it easy (or meaningful) to increase the frequency to say hourly or a few more times per day? I know these metadata are being saved and committed to Github, so increasing their frequency might have some limits? It may not help anyway if people are trying to upload data immediately after registration. Doing it twice daily might help ensure that if they do it the next day, they’ll be covered.
