### ISSUE TITLE
Data Issue triggered for future tag deployments without species

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#732]
I noticed recently with Project 78 that they have quite a few [data issues](https://motus.org/data/issues?id=78#v_tag_deploy_species) triggered for future deployments that do not have species set. Future deployments _shouldn't_ have a species set so this error notice appears to be in error.

**Comment by cjardine-bsc** [comment]
I think this was a deliberate choice. But I suppose you're suggesting only triggering this error after the deployment start date has past. 

Can do. 
Did do. 
Bippity boo.
