### ISSUE TITLE
Station Photos

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#733]
We've discussed adding photos of stations to the Receiver Map in the past, similar to what I did on the [Education site](https://motus.org/education/station/). While this would be nice, it's not exactly top priority. I guess it still isn't, but I thought we could outline how that might look here and maybe discuss real uses for this as we are considering the new interface.

For one, I am in the habit of taking several photos of each station after installation and usually each visit. This allows me to remember the context of each setup and spot any issues that I may have missed. Having a photographic record of deployments can actually be quite helpful for this.

We already have an uploader in place for zip files that contain text and sounds; how complicated would it be to add images? We would obviously have to come up with some restraints, but I'm imaging there would be a smaller thumbnail (~200x200 px) that is visible on the Receivers Map after clicking on a receiver and then larger photos can be seen in the 'station profile', including a 'history'. We can decide on the max size of the images in terms of bandwidth, but having access to larger images will make it possible to spot small details that could hint to problems (chewed wires, corrosion, etc.). Perhaps these larger images can only be accessed by project collaborators?

Panoramas are really large, but they can be informative too..

![20200220_100522_2](https://user-images.githubusercontent.com/35931796/84378212-2c140e00-abba-11ea-8c2c-c0304b5acc1d.jpg)

<div style='text-align:center;'>
<img src='https://user-images.githubusercontent.com/35931796/84377732-79dc4680-abb9-11ea-862a-456f8df81119.jpg' height='200' alt='img1'>
</div>

**Comment by jsayers-bsc** [comment]
Now that we are moving toward Station records, being able to save photo  will become even more useful. Like Lucas, I take my own photos (web interface by habit, but occasionally others). That's all fine for me on my computer, but when multiple people are checking stations being able to aggregate those at the station level across deployments would be useful to have.

**Comment by StuMackenzie** [comment]
This should be part of the new station dashboards. We will have to think about how to handle it, but under that framework. Not sure if it's worth keeping an open git for.
