### ISSUE TITLE
Remove Tag Detections Outside Deployment - Project 323

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#734]
I've recently been in touch with a collaborator who has 14 tags that were detected outside of their deployments, even before they were ever registered to Motus. To further the mystery, there are thousands of these detections on stations not owned by the collaborator and no other tags with some of these IDs+BIs exist in the database. 
https://motus.org/data/issues?id=323#v_tag_hits_out_deploy

They would like these removed from their project - can that be done?

**Comment by cjardine-bsc** [comment]
@Hussell Can you please re-run the following batches:

1070832
1091265
1111240
1111353
1112567

I think I know how this happened, but I'd like to re-run the above to see if those hits outside the deployment disappear (for tag ID 44820)

**Comment by Hussell** [comment]
Done.
