### ISSUE TITLE
Download Tags Active List

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#735]
One for @pmorrill 

Can you please expand the API used on the download page:

https://motus.org/data/downloads

To make the vwTagsActive view publicly downloadable from this page?

**Comment by pmorrill** [comment]
This is available for review in the beta server:

https://beta.motus.org/data/downloads?projectID=137

**Comment by StuMackenzie** [comment]
Great. Thanks Paul. Looks good to me to implement.


For the time being we can just create Lotek a ‘project’ and provide them with access whenever they need it.

 

Stu
