### ISSUE TITLE
Hide Collaboration policy prompt for administrators

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#737]
When using the 'Assume user ID' tool as an admin, you can't use Manage Data until the collaboration has been accepted. Can we create a bypass for admins?

**Comment by pmorrill** [comment]
Just checking on this: we added this to the beta - has it been tested? Time to close this one? Lucas?

**Comment by leberrigan** [comment]
Awesome - just tested it and it works no problem. Just needs to be pushed to live and then closed?
