### ISSUE TITLE
Receiver deployment tables cumbersom

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#740]
Can we discuss a cleaner way to present this data based on indivduals rather than each day or period that an individual is detected? In it's current form the lists are too long, and too complicated to navigate/get useful info from.

see for example - https://motus.org/data/receiverDeploymentDetections?id=5521

**Comment by leberrigan** [comment]
Kind of like the tables at the bottom of the page here? https://motus.org/education/station/?school=3027

**Comment by StuMackenzie** [comment]
Exactly. I don’t know if it’s an easy fix now, or wait until the dashboard reset, but it would make a big difference.

____________________

On Jun 19, 2020, at 14:52, Lucas Berrigan <notifications@github.com> wrote:

﻿

Kind of like the tables at the bottom of the page here? https://motus.org/education/station/?school=3027

**Comment by jsayers-bsc** [comment]
The daily tally is actually helpful as well, especially for stations that aren’t near tagged breeding birds or other projects where individuals will be detected every day. So I don’t think we wouldn’t want to get rid of that format entirely.

**Comment by leberrigan** [comment]
Fixed with stations and all that
