### ISSUE TITLE
Project 310 missing registered tags

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#745]
List should include (bold are missing):

52195507
55190766
52667861
4C66074B
4C78612D
52523378
5519664C
5219782A
**5266071E
55192A2D**

Missing tags should be in project 0

55199664 - appears to be a duplicate? exists as 5519664 and 5519664C?

Including Denis because it is related to some actions being taken with CTT to better integrate tag registrations.

**Comment by cjardine-bsc** [comment]
Those two mfgIds are not in api_import_tags or tags. Looks like CTT did not attempt to register them. 

I've done the registration. 

5519664 and 5519664C are indeed duplicates, they have the same ctt_id in the api_import_tags import table. I have merged them.
