### ISSUE TITLE
Bulk tag upload failing "unknown reasons"

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#75]
I tried uploading bulk tag metadata for project 63 and got the warning:

Upload of your data file has failed for unknown reasons. Please contact Motus administration.

I got the warning even when uploading the tag template downloaded directly from the site with no changes.  Happens on beta and the live site

**Comment by denislepage** [comment]
Additional details on the error generated. Comments column used twice. Should be easy to fix.



Error type = 7 - Low-level Database error

Error Code = 264

SQL = INSERT INTO api_tag_deployments (apiBatchID,rowNum,tagID,tagProjectID,dateBin,mfgID,period,lifeSpanDays,tagDeployID,utcYearStart,utcMonthStart,utcDayStart,utcHourStart,utcMinuteStart,utcYearEnd,utcMonthEnd,utcDayEnd,utcHourEnd,utcMinuteEnd,deferSec,speciesName,markerNumber,markerType,decimalLatitude,decimalLongitude,elevationMeters,sex,age,weightGrams,wingMillimeters,tarsusMillimeters,culmenMillimeters,billMillimeters,headMillimeters,fatScore,comments,test,comments) VALUES (33935,281,'18633','63','2016-2','223','6.0962',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),

(33935,282,'18636','63','2016-2','220','6.0961',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),

(33935,283,'18639','63','2016-2','217','6.0962',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),

(33935,284,'18648','63','2016-2','226','6.0963',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),

(33935,285,'18645','63','2016-2','211','6.0963',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),

(33935,286,'18634','63','2016-2','222','6.0962',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),

(33935,287,'18631','63','2016-2','225','6.0962',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),

(33935,288,'18637','63','2016-2','219','6.0961',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),

(33935,289,'18640','63','2016-2','216','6.0962',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)

Description = Creating prepared statement on: tags (Made it to result set wrapper)



Browser info:Unknown

Auth type = Unknown

Method = Unknown

Query = Unknown

Uri = Unknown

All parameters:Unknown

Stack trace:

com.microsoft.sqlserver.jdbc.SQLServerException: The column name 'comments' is specified more than once in the SET clause. A column cannot be assigned more than one value in the same SET clause. Modify the SET clause to make sure that a column is updated only once. If the SET clause updates columns of a view, then the column name 'comments' may appear twice in the view definition.

      at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)

**Comment by zcrysler** [comment]
I deleted the multiple "comment" columns the first time I tried uploading (second time I just tried uploading the unchanged template).  Is there a way I can remove those columns?

**Comment by denislepage** [comment]
We’ll need to look into this. Is the comments column included twice in the template? Does it work when you remove the extra column?

In any case, the import tool should catch that error before it tries to insert the rows, and come back with a friendlier error.

**Comment by zcrysler** [comment]
The template you download has 3 "comments" columns, I deleted all of them and tried uploading and got that error.  I also tried uploading the template with no changes and got the same error

**Comment by pmorrill** [comment]
Just to clarify: what is happening here is that custom properties have been added to some deployments, using field names that are already defined on the main deployment table. ('comments' in this case). The custom properties end up in the templates and that gives the duplicates.

I will add an error condition when someone tries to add a custom property using a 'reserved' field name, as a first step.

It is not clear why removing these columns from the template, then uploading, did not work.

**Comment by denislepage** [comment]
You should also check that there are no duplicate names, including both custom and reserved fields.

**Comment by pmorrill** [comment]
We can add code to disallow custom properties with the same name as any 'standard' tag deployment fields. But obviously there are deployments out there that already have custom properties that use names that conflict with standard field names. Uploading template files has to rely on several assumptions, and I think it's reasonable that one of those assumptions is that the PI has not changed the column orders from the downloaded version. With that in mind, I have adjusted code in sandbox so that on upload, a second occurrence of a standard field name will cause that column's data to be interpreted as a a custom property: the data will end up in the api_tag_properties table.

Catherine: is this going to cause a problem with the validation proc?

**Comment by zcrysler** [comment]
Still able to add a custom property with an existing field name - I was able to add "age" and "Age" to live, beta, and sandbox with no errors. Tried uploading tag databases that had both of these field names added, since the one in the dataframe is titled "age", if I added my own column called "Age" I could still bulk upload. But if I successfully created a second "age" column, after uploading I get the error "Your template includes a duplicate header: 'age'."

I think this is fine how it is, but could we add to the error message: "Your template includes a duplicate header: 'age', please delete or rename the variable"
