### ISSUE TITLE
"Make a Map" of tracks fails with X number of species

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#750]
I'm getting a 404 error on the Make a Map feature in the View Tracks page when [viewing a large number of tracks](https://motus.org/data/tracksSelect?e=2013-01-01&l=2020-12-31&s=15580). 

![image](https://user-images.githubusercontent.com/55001144/85793705-65449600-b703-11ea-98d6-b1d8b852319a.png)

It may be due to the number of tracks I'm trying to view since it works with birds with fewer tracks. But if there's a clear limit, it's not clear what that limit is. It would be nice to have that limit or a warning message displayed somewhere on that page.

**Comment by denislepage** [comment]
Post requests would have a much higher allowed size, but couldn’t be copied with the URL only. One solution I had advocated a while ago was to allow people to save the map parameter and give them a unique short URL.

Are there other downsides to changing the request from GET to POST?

Denis

**Comment by jsayers-bsc** [comment]
Being able to copy and share the URL (either directly or with a short URL) is very helpful indeed.

**Comment by leberrigan** [comment]
I agree with Josh that it is more valuable to be able to share the URL. We should add some code for now that stops people from selecting more than ~200 boxes:

```
var limit = 200;
$('input[type=checkbox]').on('change', function(e) {
   if($(this).siblings(':checked').length >= limit) {
       this.checked = false;
       $('input[type=checkbox]').prop('disabled',true);
   } else {
       $('input[type=checkbox]').prop('disabled',false);
   }
});
```

Is there not a way to compress the URL? It's just a long array of numbers.

**Comment by denislepage** [comment]
The way I would like to handle this (which I have on my radar from the beginning) is


1.       Replace the GET by a POST request

2.       Build an object on the page that contains all the parameters (either a hidden field or a JSON object; the former may be a bit less work to set up).

3.       Have a service that can accept these parameters and generate a short key that can be stored in the database.

4.       Create a Javascript request that can send the parameters as a POST request when someone clicks on a button that says “Share this map” for instance and which displays the short link including the key (e.g.   https://motus.org/data/tracksMap?key=AF451AA0)

5.       Allow the map to be build from the saved parameters.

I don’t think I would create a short link for every request, but only those that people wish to share.

**Comment by j-sayers** [comment]
Unresolved but closing
