### ISSUE TITLE
View Tracks glitch? 

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#756]
I may have missed this discussion somewhere.

Project 263 - Purple Martin has 50 active tags however, only 15 of them show up via the view tracks tool (none of which have any useful data and can probably be deleted/flagged, but we can ignore that for now).

The tags only have a predicted start date and no metadata.

**Comment by StuMackenzie** [comment]
Only 15 from this project show up when only Purple Martin are selected as well.

**Comment by Hussell** [comment]
If a tag isn't detected at more than one receiver (so, it has no track), it won't show up on the track tool. Of the 50 tags in that project, 2 were detected on 3 receivers, 13 on 2, 18 on 1, and 17 on 0.

**Comment by denislepage** [comment]
Perhaps we should report single points on the track map?

**Comment by StuMackenzie** [comment]
View Tracks - perhaps for the new tool some of this is covered by providing deployment locations. Closing.
