### ISSUE TITLE
SensorStation data not being synced to Motus database

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#758]
I mentioned [yesterday ](https://github.com/MotusDev/Motus-TO-DO/issues/757)that we have no data yet for the 3 Version 2 SensorStations we have here in Ontario, though they've been on for over two weeks and as far as I can tell, recording data just fine and sending that regularly to CTT.

I thought that it might be due to the fact that these are V2 SS and the process on CTT's end wasn't fully configured. But when I mentioned this to CTT apparently data has been syncing data to Motus as usual (though transfer of data from the Version 2 SS is being manually triggered at the moment). 

Are there any changes we've made on our end that might account for data not properly making it into our database? I know we'd made some changes to the regex and parsing of files. Is it possible that this has prevented new data from entering the database?

**Comment by denislepage** [comment]
I have a note from Bob with instructions talking about having moved the detections to a new location on AWS.

I’m not sure yet, but it may well relate to this.

**Comment by StuMackenzie** [comment]
Just to close the loop - As far as I know we have not been receiving any SS data recently and need to ensure this is fixed - I think it’s on our end now as Denis described, but need to also ensure that it’s automated for both CTT and Lotek tags. Denis and I will speak to them again on Tuesady. Station connectivity problems is likely our next big issue.

____________________

On Jul 8, 2020, at 20:48, denislepage <notifications@github.com> wrote:

﻿

I have a note from Bob with instructions talking about having moved the detections to a new location on AWS.

I’m not sure yet, but it may well relate to this.
