### ISSUE TITLE
Registering LifeTags

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#761]
Project 310 recently purchased 20 LifeTags and is trying to register them. I thought that only half of them had registered, but in fact it's [10 completely different tags](https://motus.org/data/project/tags?projectID=310) in their project.

The tags in question don't appear to be in the db in project 0 or any other project either. The tags are: 

('78344C1920', '52072D552D', '524B662DF2', '3361340785', '521E55195C', '33612D7815', '524B331E26', '33072A78C6', '3307074B18', '521E196194', '524B7878DF', '072A4C348D', '7834192AF4', '7866526629', '7834666163', '7878664CDC', '78784C4BE5', '782A1E1E9D', '074C2A197D', '7852551E67')

**Comment by cjardine-bsc** [comment]
These don't appear to be in the import tables. Can we confirm that CTT tried to register them with us before shipping to the user?

The projects should not need to register CTT tags, this should be done when the tags are purchased.

I can manually register the tags, but before I do, I noticed that these are all 10 digits, the CTT tags we have in the database currently are 8 digits. Is this change expected?

**Comment by denislepage** [comment]
The list has been shared with Bob.

**Comment by jsayers-bsc** [comment]
Another handful of tags for Project 310 that were recently purchased but aren't registered:

('7834527881', '78197852A9', '784C331977', '7852612A46', '78781E197A')
