### ISSUE TITLE
"Ignoring" a Data Issue does not change anything in the underlying data

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#763]
Someone notified Project 240 that many of their tags were missing species and lat/lon information. They checked and saw that all of their tag deployments did in fact have all this information. On looking a bit closer it's that they had tested all their tags prior to deployment, which is a great things to do. But of course that creates a bunch of detections that occur outside a deployment, and these get downloaded with the R Package along with the all the real data. This was the source of the confusion, as the person was looking at these "detections" from the test period.

Issues like these are the reason that the Data Issues page highlights them so that they can be dealt with. The proper way of dealing with this particular issue is to create test deployments for each tag that covers the testing period. But this is not convenient by any means and in reality few if anyone will do it. 

There is also the "ignore" option in the Data Issues page, which brings me to the title. It makes some sense that "ignoring" doesn't change anything in the data that's downloaded. For some issues simply hiding them from view is fine (like "missing landowner information). But many tag and receiver related issues simply ignoring them on the project web layer doesn't really resolve anything. 

I'm not sure what the best option would be here... Maybe it would be helpful in the data issues to have other options in addition to "ignore" that will result in an change to data itself. 

One possible idea, especially for the "Detections Outside Deployment" errors would be to bulk flag as Test. Something to note here is that, because there are not currently deployments, there would have to be a way to flag outside of a deployment (e.g. **flagging Runs as Test**) or a process that creates a deployment spanning the period then flags it as a test (which has its own issues).

**Comment by StuMackenzie** [comment]
Closing unless an action can be identified. Solution appears to advise user to make test deployments, or expand deployments to include the test period that they want to view.
As for what to do with ignoring flags, I don't know.

**Comment by cjardine-bsc** [comment]
We have an option that controls which issues can be ignored and which cannot. If there are issues you feel should not be ignored we can add them.

**Comment by denislepage** [comment]
I’d rather have a label that we can attach to closed issues to indicate that they were left unresolved.
