### ISSUE TITLE
R-client needs a check whether the Collaboration Policy has been accepted

### ISSUE THREAD

**Issue by pmorrill** [MotusDev/Motus-TO-DO#764]
When a user authenticates via the R-client, the API will start verifying that the current Collaboration Policy has been accepted. If it has NOT, then no token will be created. Instead, a message (prompt) will be sent to the R-client. The R-client should present the message and prompt the user to ACCEPT the current policy. 

If the user accepts, the R-client should send the same authentication request back, along with a flag that indicates the policy has been accepted.

**Comment by denislepage** [comment]
Rather than a customized message, as I suggested today, it might be easier to point to a permanent link on the web site. There, we could highlight the most recent changes.

We need to sort out the message that people will see in R (should probably be consistent with the one on the web site, and the policy can be approved in either places, not both).

Something like this:

The Motus collaboration policy has changed. To see a summary of the recent changes, or read the full policy, please click here (or go to https://motus.org/{link}<https://motus.org/%7blink%7d>)

To continue, please confirm that you have read and agree with the Motus Collaboration Policy.

YES   NO

If they say yes, the R client should be able to resend the same request again. If they say no, we also need a message explaining that they need to agree to the policy before they can access data. I don’t know if we have any un-authenticated calls, but those can continue without the policy acceptance if so.

**Comment by cjardine-bsc** [comment]
Paul, do you know how you want to do the validation (stored in user_properties)? Do you want it added to this view: vwR_User_auth

**Comment by pmorrill** [comment]
If we are directing the user to a permalink on the website, maybe it also makes sense to have then accept the policy on the website, and not add support for accepting it in the API. This makes more sense to me because API users will otherwise simply hit 'accept' YES without reading the policy. The website is a more appropriate mechanism for encouraging care in this important step, no?

**Comment by denislepage** [comment]
Yes, I think that makes sense. From R, we could say something like:

You must accept the most recent Motus collaboration policy from this page before continuing: <link>

I’m assuming they will be sent to a link where they are asked to login (if needed) and then accept the policy. Not sure where they will be redirected then. Presumably their profile with a short thank you.

**Comment by pmorrill** [comment]
I have now added the Motus Collaboration Policy Acceptance check to the sgdata api. This check is made every time the user requests a new token OR makes a call using an existing token. If the policy has not been accepted, the error returned includes a message that can be displayed directly to the user. We have control of the EN version of that message via our text fragments (Authentication_failed_data_policy_not_accepted).

It is our intention to include a link to the actual policy acceptance web page - but I honestly can't find that page, since I have already accepted the policy! In any case: @steffilazerte  can point her R-client at the sandbox and try to generate this new error message, for display to the user. Let @denislepage know the account you are using and we can make sure that your acceptance check fails, so that the error is generated. 

Also - as Denis mentions: this check is not performed when someone is accessing the 'sample' data.

**Comment by steffilazerte** [comment]
@denislepage if you could revoke my policy acceptance (steffilazerte) I'll give this a try. 

Heads up that I'm canoe camping Wednesday afternoon through Sunday :grin: :canoe: :camping:

**Comment by denislepage** [comment]
Ok, should be done on the main db and sandbox.

It’s be great if we can deploy the latest build before you go, at least the new CTT fields. Let us know if there was anything standing in the way.

**Comment by pmorrill** [comment]
@denislepage did you rebuild sandbox? I just checked this code in an hour ago.....

**Comment by denislepage** [comment]
Ok, the latest build has been compiled and deployed.

**Comment by steffilazerte** [comment]
Okay, I can get the error and it displays to the users: 

```
tags <- tagme(projRecv = 207, new = new, update = TRUE, dir = "../")
 Error: Login failed with error message
'Server returned error 'You have not accepted the most recent Motus Collaboration Policy, which you can review here: https://motus.org/policy/''
```

But we'll definitely have to get the appropriate link in there or it's not a very helpful message :smile:

> @denislepage: It’s be great if we can deploy the latest build before you go, at least the new CTT fields. Let us know if there was anything standing in the way.

I haven't implemented some of the newer things (i.e. getting All activity and All gps, hits), but so long as they can wait I *thinnk* everything is good to go (once that link in the error message is better).

I'd suggest getting the appropriate link, let me try to "accept" the policy and then I can run my local tests to make sure everything checks out. I could merge tomorrow afternoon or Wednesday morning if all goes well.

**Comment by denislepage** [comment]
All people have to do is log in on any page. If their policy is expired, they’ll be redirected here, which is the link I would use for simplicity: https://motus.org/data/user/policy

or https://sandbox.motus.org/data/user/policy on sandbox.

Beta and live share the same database, so either places would work the same. If people are relying on sandbox, we should point them to the sandbox site. Accepting the policy on the wrong server won’t work for them. Given that we’re the only ones using sandbox, we don’t need to worry about this, and we only use the main URL.

Once you have accepted the policy, if you try to reach this address again, it will still ask you confirm again. We probably want to replace the option to accept the policy by a message that confirms something like “You have already accepted the current version of the policy on <DATE>” and remove the checkbox and save button. That can happen later if needed, so not to delay deployment.

**Comment by denislepage** [comment]
With regards to deployment, the key thing I would like to have out there sooner is the extra CTT field. The rest can wait.

We have an API version value, which I think we can use to force people to upgrade their package, right? I don’t quite remember the details of how we’ve implemented this.

**Comment by pmorrill** [comment]
I have only updated this feature into the api in **sandbox**. Deploying the R-client in live environment will not be affected by this message (since it will not show up until I add these changes). The message itself is edited as a text fragment, but that too is only available in sandbox.  (Note that the api does not support FR, at this point)

So I would say that for this week, just ignore this specific message handling. I will update the sandbox version of the text. But it sounds like we need some slight change in the coll. policy acceptance page as well, and that won't happen immediately.

**Comment by denislepage** [comment]
That sounds good. Is the URL part of the API or the client?

**Comment by pmorrill** [comment]
The message that gets displayed is 100% coming from the text fragments on our side. So I don't think that Steffi has done anything at all to support this feature, since she has always displayed the msg that comes back in event of an error. She can confirm that.

You can review / edit the msg here:

https://sandbox.motus.org/data/admin/tx_text?id=1123

**Comment by denislepage** [comment]
Great, looks good. I put in the translations.

**Comment by pmorrill** [comment]
We don't yet have language lookup in the api. But we are now able to do that (though it will be a bit of work to convert all string handling to using the txt fragments).

**Comment by denislepage** [comment]
That is probably a relatively low priority for the R package.

**Comment by steffilazerte** [comment]
Are we happy with this? Can we close the issue?
