### ISSUE TITLE
Erroneous Deployment End Dates

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#766]
Some users are entering end dates for deployments even if the tag was not recovered. This is causing a few metadata management issues so there are few things we need to do to address the issue. 

User Communication:

1. Deployments should only be assigned end dates if the tag has been removed from the animal. Otherwise the end date should be left blank and it will be calculated based on the life span of the tag. 

On https://motus.org/data/tag/deployment/edit?projectID=1&id=27476 I'd like to update the tool tip on the deployment end date to be clearer about this. 

When users enter an end date, they should see a warning when saving the tag deployment. Ideally it would say something along the lines of 

"You have entered an end date for this deployment. End dates should only be entered for tags that have been removed from the animal, otherwise please leave the end date blank. This tag has a remaining estimated lifespan of XX days, if you do not intend to use the tag again please mark it as deprecated here" 

The XX value can be pulled from a new view I've created in sandbox called dbo.vwTagsRecovered. The "here" should link to the tag management page for the tag_id of the deployment (i.e. https://motus.org/data/tags/edit?projectID=1&id=16357) 

Once a tag has been deprecated, no new deployments are permitted. However, users can deprecate a tag that has an active deployment. Can we add a validation step to the tag edit page that first checks for active deployments before allowing a tag to be saved as deprecated?

Finally, users are able to un-deprecate a tag. I think this needs to be accompanied by a warning:

"This tag was previously set as deprecated, during that time a new tag may have been manufactured with the same properties. Please check the data validation centre to ensure that no tags exist in other projects with these same properties. This is necessary to ensure that your tag does not return ambiguous detections"

@pmorrill 

2. Data validation

I've added a new error to the data validation procedure in sandbox that will warn users about recovered tags. Feedback on the error and fix descriptions are welcome. 

https://sandbox.motus.org/data/issues?id=113#v_tag_not_deployed_recovered

![image](https://user-images.githubusercontent.com/22172758/88225218-fcc3d880-cc1e-11ea-920b-50f47ef2c40d.png)

3. Finally, we need to sort out what information to provide back to Lotek for these tags regarding the re manufacture of tags with the same properties. Right now I've added details to vwTagsActive that tells Lotek the remaining lifespan on the tag, but we may want to remove some of the tags from this list ourselves based on the remaining lifespan. Say if a tag only has 5%? 10%? 20%? of battery life remaining should we assume it will never be deployed again? Remember that we add a 50% buffer to the tag lifespan (i.e. if we expect a tag to last 100 days, we look for it for 150 days).

**Comment by jsayers-bsc** [comment]
>     1. Deployments should only be assigned end dates if the tag has been removed from the animal. Otherwise the end date should be left blank and it will be calculated based on the life span of the tag.

That's good to know. I didn't quite understand that myself!

> "You have entered an end date for this deployment. End dates should only be entered for tags that have been removed from the animal, otherwise please leave the end date blank. This tag has a remaining estimated lifespan of XX days, if you do not intend to use the tag again please mark it as deprecated here"

The last sentence is a little unclear to me. A tag should only be marked as deprecated if it's damaged, out of battery, or otherwise known to be non-functioning, correct? It sounds a bit like people could mark a tag as deprecated even if it has _not_ been recovered, though I don't believe that's the case.

Maybe this should be: "If you have recovered this tag and do not intend to use the tag again please mark it as deprecated here"

> I've added a new error to the data validation procedure in sandbox that will warn users about recovered tags. Feedback on the error and fix descriptions are welcome.

This will be helpful.

**Comment by jsayers-bsc** [comment]
Here's an idea for a warning that could be used when someone wants to deprecate a tag, so that they understand the potential consequences of deprecating a tag that is still in circulation:

"Deprecating a tag will mark that tag ID as available for reissue by Lotek. Please do not deprecate a tag unless you are certain it is not currently deployed, and will not be deployed again in the future. If the tag is still in circulation, this could result in two identical tags being deployed at the same time. "

**Comment by denislepage** [comment]
A longer version, touching on some other aspects that may be worth mentioning (perhaps somewhere else):

Deprecating a tag will mark that tag ID as available for reissue by Lotek. Important: you should only deprecate tags that you are certain are no longer in circulation (preferably only those you have in your possession) and that you do not intend to use in the future. Deprecating an active tag could lead to having 2 identical tags active at the same time. Note that you must terminate any active deployment record before you can deprecate a tag. Note also that all Lotek tags automatically get deprecated after 3 years from the registration date.

I think it’s too long as is, but these are things that people should know about.

Also, As we discussed today, do we want to make it possible to deprecate a tag from the deployment page, or would that be too confusing?

**Comment by cjardine-bsc** [comment]
Thanks for the productive chat today everyone. 

Paul, I've created you a new query that will tell you everything you want to know about the lifespan of a given tag ID 

[prTagLifespan]
@tagId int,
@lifespanLotek int OUTPUT,
@lifespanBuff int OUTPUT,
@lifespanRemainLotek int OUTPUT,
@lifespanRemainBuff int OUTPUT,
@endDate datetime OUTPUT

This can be used in a few places. 

1. Display both the estimated lifespan and the estimated lifespan including a buffer on this page: https://motus.org/data/tags/edit?projectID=1&id=16357 

@jsayers-bsc can you provide tooltips for those?

2. Display the remaining estimated lifespand and the remaining estimated lifespan including buffer on the deployment page: https://motus.org/data/tag/deployment/edit?projectID=1&id=27476

3. Inform the warning message that will be displayed to the user if they provide a deployment end date 

"You have entered an end date for this deployment. End dates should only be entered for tags that have been removed from the animal, otherwise please leave the end date blank. This tag has a remaining estimated lifespan of XX days, If you have recovered this tag and do not intend to use the tag again please mark it as deprecated here"

Is that really it? I feel like I'm missing something

A remaining to-do item for me is to look at the bulk tag deployment upload process and see if there are some warnings we should include there for this.

**Comment by pmorrill** [comment]
For the alert msg, do we want to report the buffered days remaining? Or the lotek days remaining?

**Comment by pmorrill** [comment]
I have added the new interface elements to present estimated lifespans / remaining lifespans to the user (sandbox only). There are several tooltips that need editing. I have added the text frags, with stub test in place. 

In particular:

LIFESPAN_BUFFERED_HELP -> total buffered lifespan
LIFESPAN_LOTEK_HELP -> lotek's estimated total lifespan
LIFESPAN_REMAIN_BUFFERED_HELP -> buffered remaining lifespan
LIFESPAN_REMAIN_LOTEK_HELP -> manufacturer's estimated lifespan remaining
ESTIMATED_END_LIFESPAN_HELP -> esimtated end of life for tag

**Comment by StuMackenzie** [comment]
buffered I think

**Comment by pmorrill** [comment]
This is now in beta server and can be checked over: text fragments need updating.

**Comment by StuMackenzie** [comment]
Resolved ? @cjardine-bsc please review.

**Comment by cjardine-bsc** [comment]
There was a loose end here. I added a warning to the bulk tag deployment upload tool that warns users that they are setting an end date. That's deployed in sandbox and tested. I'll deploy to live unless anyone objects?
