### ISSUE TITLE
Mismatch between `receiver-deployments.csv` download and direct read from API

### ISSUE THREAD

**Issue by adamdsmith** [MotusDev/Motus-TO-DO#768]
Any expectation that the `csv`s acquired this way would differ?

``` r
# Read local csv downloaded manually on 2020-08-04 18:23 UTC
recv_manual <- readr::read_csv("receiver-deployments.csv")

# Direct read into R from link on motus.org
Sys.time()
#> [1] "2020-08-04 18:35:36 UTC"
recv_auto <- readr::read_csv("https://motus.org/data/downloads/api-proxy/receivers/deployments?fmt=csv")

identical(names(recv_manual), names(recv_auto))
#> [1] TRUE

identical(recv_manual, recv_auto)
#> [1] FALSE

nrow(recv_manual)
#> [1] 3729

nrow(recv_auto)
#> [1] 3562
```

**Comment by cjardine-bsc** [comment]
Hi Adam, What project are you using?

**Comment by Hussell** [comment]
select count(*)
from vwData_receivers_deployments a
where a.accessLevel <= 1

3578

select count(*)
from vwData_receivers_deployments a

3745

**Comment by adamdsmith** [comment]
This is Motus-wide receiver deployment data, on this page:
https://motus.org/data/downloads

ANd specifically the manual download from this link
<https://motus.org/data/downloads/api-proxy/receivers/deployments?fmt=csv>
differs from the same link read directly into R as the code demonstrates.
