### ISSUE TITLE
Magnetic vs. True Bearings

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#769]
The distinction between magnetic and true compass bearings can be confusing for many and we're not providing much information or warnings about it. I think we should pay more attention to this as a potential for widespread erroneous antenna bearings. For instance, the receivers map doesn't specify what kind of bearings are being used for antenna direction (they are magnetic).

I think this requires an explanation and instructions on best practices, etc. The typical compass of half-decent quality will have a way to set the magnetic declination which for many people only need to set once and then that's it. I bet there are plenty of folks who use a compass with the declination set and are entering the directions in Motus as a magnetic bearing. Smartphones have internal compasses which report magnetic bearings and most apps will display that raw reading, but some apps have the option to use GPS position to account for declination. Smartphone compasses also vary widely in performance must be calibrated from time to time.

**Comment by Hussell** [comment]
I'm pretty sure all the maps which show antennas are using true bearings (i.e. magnetic bearing + declination). Getting those maps right was pretty much the entire reason we started tracking magnetic vs. true bearings and magnetic declination.

I guess the compasses I've used must have all been cheap, because I don't think I've ever seen one with a way to set the magnetic declination.

**Comment by leberrigan** [comment]
Sorry, you're right in that the antenna directions are pointing in the true direction, but the information tooltip displays magnetic directions.

Yeah, usually cheaper compasses don't have the ability to set the declination, but you only need to spend $20 for a decent one. All the ones I've used in field work have had declination scales.

**Comment by StuMackenzie** [comment]
Closed - no action identified.
