### ISSUE TITLE
Tag Deployment Instructions 

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#775]
The current instructions provided [on our website](https://motus.org/data/tag/deployment/edit?projectID=1&id=29015) are incomplete so I'm rewriting them here. Stu, Josh: let me know if you have any edits.

Current version
---

> <b>Providing accurate deployment information ensures that the tag detection can be assigned to the correct animal.</b> Tag detections that fall outside known deployment dates will typically not be included within many data visualizations. Most tags are normally deployed only once, but a tag can occasionally be re-deployed on a different animal. You can only have one active deployment at a given time, and deployments cannot overlap in time. For the time being, once you create a new deployment, you can no longer modify its start date or delete it, so please ensure that you enter your information carefully. The ability to modify or delete deployments will be added in the future. You can also contact us for any problems.

New Version
---

> <ul><li><b>Tag deployments tell our system when your tag was active.</b> Without deployments, the <i>tag finder</i> algorithm won't know know when to look for your tag, so you will have no detections. You can have as many deployments for a tag as you want, they just can't overlap.</li><li><b>You must have your tags registered with a deployment prior to the actual deployment of your tags. </b> Tags are searched for in receiver data only when those data are uploaded to Motus.org and they cannot be searched retroactively. You may never get your tag detections if you do not have an early deployment set. Read more here [LINK].</li><li><b>Deployments should be ended</b> if and only if the tag has been removed from the animal and/or the tag is deactivated at any point.</li><li><b>Remaining tag life is calculated using accumulated deployment time.</b> We use the tag lifespan to tell the <i>tag finder</i> algorithm when to search for your tag. This means that if you start your deployments too early or if you don't end them when you should (see above), <i>tag finder</i> might think your tag has run out battery life too early and stop searching for it.</li><li><b>Providing accurate deployment information ensures that the tag detection can be assigned to the correct animal.</b> It also ensures data provided to the public is accurate. Please do not enter a species for tag testing and mark the tag as a test in the box below.</li><li><b>A deployment created cannot be destroyed, for now.</b> Please ensure that you enter your information carefully. The ability to modify or delete deployments will be added in the future. You can also <a href='contact'>contact us</a> for any problems. </li></ul>

**Comment by StuMackenzie** [comment]
Looks good - post it.
