### ISSUE TITLE
Project 250 Missing Data (tag lifespan expiring?)

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#776]
Ana has been very on top of her stations in SK and has noticed many inconsistencies that I've been working with her to sort out. We've already dealt with a couple issues (#752, #755, #730, #731), but this here seems to be a new one.

mfgID | tagID | deployID | lifespan_calc | date.registered | default.deployment.date | updated.deployment.date
-- | -- | -- | -- | -- | -- | --
457 | [44978](https://motus.org/data/tags/edit?projectID=250&id=44978) | 27872 | 88 | 2020-04-13 | 2020-05-15 | 2020-08-09
488 | [45325](https://motus.org/data/tags/edit?projectID=250&id=45325) | 28096 | 88 | 2020-05-08 | 2020-05-15 | 2020-07-27

Ana confirmed bird 457 was being detected at the site ['Bessie'](https://motus.org/data/receiver/deployment/plot/SG%2D4E86RPI36D29-2020%20Sask%20Passerine%2C%20Site3%2DBessie.png?id=6048&n=100&firstTag=0) while viewing the SensorGnome's web interface, and these data were uploaded to Motus ([they can be found here](https://sgdata.motus.org/status?serno=SG-4E86RPI36D29)). Yet, no detections exist for this tag. I thought that this might have to do with the tag lifespan being calculated from the registration date, but I'm not sure what buffer we're applying on top of the calculated lifespan - is it 20%? She also expected tag 488 to be here as she saw detections for it.

There is also a pattern visible in the receiver timeline below where antenna activity is intermittent when birds are not present, likely due to the antennas being at a low-noise site. You can see that when there are relatively few detections on Aug 12-14, there is still constant antenna activity. I'm sure hits exist here, they're just not being processed for some reason.

![image](https://user-images.githubusercontent.com/35931796/90315892-56a18080-def5-11ea-9a24-4ebf9dad2903.png)

---

The deployment timeline also shows detections of tag 457 leading up to the morning of the 12th and then shortly afterwards we get a detection from '[Pacific Shorebirds 369](https://motus.org/data/tags/edit?projectID=191&id=43839)' which is **currently not deployed**, but curiously has the same burst interval as the all of Ana's tags. So there is aliasing going on here, too! But that can only happen when there are multiple **real** tags present with the same burst interval.

![image](https://user-images.githubusercontent.com/35931796/90315945-ce6fab00-def5-11ea-9998-67fb4d98b3e9.png)

I'd say this is pretty clear evidence this is a processing error, even though these deployments have been registered for days to weeks from now. Ana is also experiencing similar problems with others, such as [to be added]. It may be worth reprocessing the most recent batches for [all 13 stations in her project](https://motus.org/data/project/recvs).

**Comment by Hussell** [comment]
Looking at the uploaded files for this receiver (https://sgdata.motus.org/status?serno=SG-4E86RPI36D29), there's an obvious drop in file sizes during the periods where little activity is shown on the timeline (e.g. 2020-07-08 to 07-14 and 08-05 to 08-09). So I think that's probably not an issue with the processing, rather a real lack of data.

For the tag 44978, a lot depends on when the deployment data was updated vs. when the receiver data was uploaded. I can't check the database right now to see when the deployment was edited (the database is being moved to a new server), but it looks like the receiver data was being uploaded frequently, increasing the chance it was processed using the old deployment date. Since it's recent data, it hasn't been rerun yet. Reruns are also paused right now, so I'll get back to you about this later.

The Pacific Shorebirds tag (43839) currently has a deployment starting 2020-08-15. That must have been added recently, because the tag finder shouldn't be looking for it earlier than its deployment. We'll see what things look like after I get the chance to rerun this receiver.

**Comment by leberrigan** [comment]
I realize I never specified this in my post - my bad! 

Ana confirmed both tag 457 and 488 were being detected at Bessie on **August 13 and 14**. 

She also said today that she is having similar issues at:
 - [SG-E124RPI3EB54](https://motus.org/data/receiver/timeline?id=3878&year=2020)
 - [SG-EC21RPI3BD57](https://motus.org/data/receiver/timeline?id=3876&year=2020)
 - [SG-CC66RPI3E120](https://motus.org/data/receiver/timeline?id=3168&year=2020)

However, [SG-FFFFRPI3266E](https://motus.org/data/receiver/timeline?id=3217&year=2020) is not experiencing this issue.

**Comment by leberrigan** [comment]
I'm quite confident this is a processing error of some sort.

We can see the aliased tag is _still_ being detected and no other real tags are being detected. At the same time, Ana had detections of bird 457 and 488 visible on the SG web interface. Those exact same hits are visible in the data uploaded to sgdata.motus, so....
![image](https://user-images.githubusercontent.com/35931796/90765271-07c26500-e2c0-11ea-9661-32842d53eed1.png)


On SGData:


Port | ts | freq.offset | sig | noise
-- | -- | -- | -- | --
p1 | 159743279**4.692**8 | 3.142 | -54.11 | -64.46
p1 | 15974328**07.502**0 | 3.143 | -45.3 | -63.77
p1 | 15974328**07.621**5 | 3.146 | -45.06 | -65.04
p1 | 15974328**07.733**7 | 3.147 | -45.04 | -65.56
p1 | 15974328**07.792**5 | 3.156 | -45.02 | -63.94
p1 | 15974328**20.601**5 | 3.131 | -46.87 | -64.05
p1 | 15974328**20.721**3 | 3.148 | -47.2 | -63.03
p1 | 15974328**20.833**5 | 3.146 | -47.95 | -63.62
p1 | 15974328**20.892**0 | 3.149 | -45.29 | -64.96

**Comment by Hussell** [comment]
I've rerun recent data in the 4 receivers. The Pacific Shorebirds tag has disappeared. Detections of 457 and 488 on SG-4E86RPI36D29 during August 13 and 14 are present. Is there anything I've missed?

**Comment by leberrigan** [comment]
Excellent - this looks good to me, but I'm waiting to hear back from Ana just to make sure. Any ideas what happened here?

**Comment by leberrigan** [comment]
Okay I think we should rerun the rest of them. We've just found problems with these two as well:
 - SG-67CERPI361F9
 - SG-FFFFRPI3266E

The last one is weird because we we're seeing the issue before. I'm not sure what's going on there.

**Comment by leberrigan** [comment]
I'm not sure what's going on here, but apparently there's still an issue.

Tag [44958](https://motus.org/data/tags/edit?projectID=250&id=44958) (#436:13.1) was deployed and the deployment was registered both on August 18. A week later, data was downloaded from this receiver and then uploaded to Motus, but [the tag did not show up.](https://motus.org/data/receiver/deployment/plot/SG%2D84AERPI36BD3-2020%20Sask%20Passerine%2C%20Site7%2DWestman%28W%29.png?id=6050&n=100&firstTag=0)

On August 25, receiver SG-FFFFRPI3266E was visited and tag [45329](https://motus.org/data/tags/edit?projectID=250&id=45329) (# 494:13.1) could be seen on its [web interface](https://drive.google.com/file/d/1xyvmmQDJBfNT9g5FeVBk5DlioU-SAznS/view?usp=sharing). However, when these data were uploaded to Motus, [the tag does not show up.](https://motus.org/data/receiver/deployment/plot/SG%2DFFFFRPI3266E-2020%20Sask%20Passerine%2C%20HANLEY%20EAST%202020.png?id=6059&n=100&firstTag=0)

**Comment by Hussell** [comment]
Tag 44958 has two deployments. The second was created on the 19th, and edited on the 29th. I'm not sure whether that has anything to do with what's going on or not.

The deployment for tag 45329 was edited from a start date of 2020-05-15 to 2020-07-27 on the 26th of August. The data from SG-FFFFRPI3266E was uploaded before that edit propagated to the tag finder.

I'll rerun August for these receivers this week, and we'll see what happens.

**Comment by leberrigan** [comment]
Tag  44958 now has 2 deployments as it has been retrieved twice off a bird (second time was on the 29th). Regardless, it should still have detections prior to the 29th as it was released adjacent to [SG-84AERPI36BD3](https://motus.org/data/receiver/deployment/plot/SG%2D84AERPI36BD3-2020%20Sask%20Passerine%2C%20Site7%2DWestman%28W%29.png?id=6050&n=100&firstTag=0) and it was being detected on the web interface.

As for tag 45329, I'm not sure what's going on here, but I had thought the deployment was registered earlier than that and the deployment actually starts August 8th. That said, shouldn't there still be data for these tags even if the deployment was still set to 15 May 2020 at the time of data upload? Not accounting for the added buffer, the default date of deployment plus calculated tag lifespan (88 days) is 11 August 2020 which is after the tag was deployed.

Further, we're getting an apparent [type 3 aliased tag](https://github.com/MotusDev/Motus-TO-DO/issues/779) for tag 494 on [August 27](https://motus.org/data/receiver/deployment/plot/SG%2DFFFFRPI3266E-2020%20Sask%20Passerine%2C%20HANLEY%20EAST%202020.png?id=6059&n=100&firstTag=0)! There are no detections of the real tag that's supposed to be present. The aliased tag has a BI of 19.7, similar to what's seen at [SG-2D6F19RPI385F8](https://motus.org/data/receiver/deployment/plot/SG%2D6F19RPI385F8-2020%20Sask%20Passerine%2C%20Site2%2DWestman%28E%29.png?id=6044&n=100&firstTag=0). See #755.

**Comment by leberrigan** [comment]
So it turns out the _buffered_ tag lifespan for these tags is actually 88 days! That means it would make sense for Tag Finder to stop searching for these tags on August 11 if it was going off its original 'anticipated' deployment date (15-May-20 + 88 days = 11-Aug-20). 

That said, the issues above are still confusing, but we'll see what happens after data is reprocessed. Ana has said that she updated deployments a few days ahead of uploading new receiver data, knowing that it could be problematic if she did it too soon.

**Comment by leberrigan** [comment]
@Hussell, did you ever re-run Receiver [**6179 | SG-67CERPI361F9**](https://motus.org/data/receiver/deployment/plot/SG%2D67CERPI361F9-2020%20Sask%20Passerine%2C%20BLADWORTH.png?id=6179&n=100&firstTag=0)? It's issues don't appear resolved.

**Comment by Hussell** [comment]
I did, on Sept. 1st, but at the time it only had data up to August 25th. There was another upload for that receiver on the 11th, containing data from August 25th to Sept. 10th. I'll try rerunning it again.

**Comment by Hussell** [comment]
No change. What are the issues with this receiver (SG-67CERPI361F9)?

**Comment by leberrigan** [comment]
I'm not really sure any more, but apparently they're happy with this so I think the issue can be closed. Thanks!
