### ISSUE TITLE
Receivers by station type

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#780]
![receivers_with_time](https://user-images.githubusercontent.com/35931796/90814221-2a27a300-e2ff-11ea-902d-f2dd7196f1f7.png)

Hard to tell what the trend here, but we can see that Lotek depoyments have flatlined whereas CTT deployments have increased. SG deployments don't seem to be increasing at the same rate as last year, but maybe that's a COVID artifact?

**Comment by cjardine-bsc** [comment]
Closing.
