### ISSUE TITLE
Issues with Species List for Tag Deployments

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#781]
It appears that the[ species list](https://motus.org/data/project/tags/template?projectID=123) used as a reference when entering tag deployments is not the same as the species list used for verifying species during deployment registration - it should definitely be the same! How they ended up being different, I don't know.

40717 | Oenanthe oenanthe oenanthe
40718 | Oenanthe oenanthe leucorhoa

Both of these show up in the 'species list', but neither are accepted when registering tag deployments.

**Note:** only _O. o. oenanthe_ throws an error during bulk upload, but both throw an error when making an individual deployment using the online form.

Could this actually be related to #214? I haven't been able to do enough testing to say whether this issue exists for anything besides subspecies, so perhaps it is.

**Comment by denislepage** [comment]
The species table includes some deprecated taxa that should not have been visible to users.

Typically, when a species gets split or lumped, the new forms all get a new ID, distinct from the original(s), even if they have the same name.

I’ve now added  a filter to exclude the deprecated concepts in the vwSpeciesLookup output. Those are identifiable by species_status = 0 in lk_species ( 1 is for full species, and other values represent subspecies, species groups, spuhs, hybrids, etc.). This will have removed the 2 following entries from the CSV (I think this followed changes related to the recognition of Seebohm’s Wheatear).

15310    0              Northern Wheatear (Eurasian)  Oenanthe oenanthe [oenanthe or libanotica]    Traquet motteux (Eurasie)                BIRDS    14597    NULL
40717    0              Northern Wheatear (nominate)                Oenanthe oenanthe oenanthe Traquet motteux (nominal)                BIRDS    14600    NULL

It’s also important that our code always filter out the deprecated code (e.g. matching name to speciesID should never result to a speciesID where species_status = 0.

Whenever I do the taxonomic update, usually shortly after Cornell’s annual update, I will also do my best to update the existing data and remap the old records to the new codes. There are no deployments currently that rely on a deprecated speciesID.

Generally, I would be encouraging people not to use subspecies, but a few are probably unavoidable.

**Comment by leberrigan** [comment]
Hmm I'm not sure I follow exactly. According to [Birds of the World](https://birdsoftheworld.org/bow/species/norwhe/cur/systematics#subsp), _O. o. leucorhoa_ is still a distinct monotypic subspecies, whereas _O. o. oenanthe_ and _O. o. libanotica_ have been lumped into a single, polytypic subspecies.

The researcher (Bianca Michalik) has both _O. o. oenanthe_ and _O. o. leucorhoa_ tagged in their project and they're looking at differences between these subspecies. I'm not sure if we should be so strict with taxonomy when we are including research that could potentially be used for identifying differences among taxa. Otherwise, Bianca would have to include a custom column to her metadata or add it after it has been downloaded thru R.

I think it's preferable to keep subspecies in there since there are several projects which are looking at specific subspecies that have different movement patterns. Subspecies such as the Ipswich Sparrow are so unique that it would be confusing to lump them together with the rest of the species.

If subspecies are still allowed, how come _O. o. oenanthe_ still doesn't work? Is there a new code?

**Comment by denislepage** [comment]
We follow eBird taxonomy, which doesn’t include subspecies, but rather subspecies groups (some/many are monotypic when they only include 1 subspecies, such as Ipswich’s Sparrow and Greenland NOWH). A polytypic subspecies isn’t a thing.

The group, on both BOW and eBird is “Northern Wheatear (Eurasian)” or “Oenanthe oenanthe oenanthe/libanotica“. For the scientific name to be recognized as the subspecies group, I expect it has to be entered in full:

“Oenanthe oenanthe oenanthe/libanotica”

eBird doesn’t have a separate entry for  Oenanthe oenanthe oenanthe and Oenanthe oenanthe libanotica, so those won’t match a record in Motus.

Most of the recognizable forms would be available as eBird groups, which should be plenty adequate in almost all cases.

**Comment by leberrigan** [comment]
Ahh I see - records for 'Oenanthe oenanthe oenanthe/libanotica' are now appearing in her database, but I didn't do anything which is weird. For some reason the autocomplete doesn't show any subspecies either. But at least its working!

**Comment by denislepage** [comment]
Autocomplete may be limited to species, and perhaps only subspecies that already have some records of deployments. I’m generally not inclined to encourage people to use subspecies, but it can be supported. If we need to implement a way to do it more easily, we can look into it, but I am not inclined to change the web autocomplete, and only tell those folks to use the CSV file.

**Comment by leberrigan** [comment]
I think there actually might be an issue with displaying the forward slash and following text. See:
https://motus.org/data/tags/edit?projectID=123&id=28317
https://motus.org/data/tag/deployment/edit?projectID=123&id=16718

**Comment by leberrigan** [comment]
I think we're good to close this one. Thanks for the fix!
