### ISSUE TITLE
Receiver Data Uploads - Sqlite error: database is locked

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#786]
I noticed that for some data uploads ([example 1](https://sgdata.motus.org/status?jobID=4347414), [example 2](https://sgdata.motus.org/status?jobID=4347650)) I'm getting the following errors with only certain pairs of batches within a single upload:

> 
> Subjob ID: 4347609
> 
> Running tag finder on receiver SG-4002BBBK1630 boot session 632
> Error in safeSys(bcmd, quote = FALSE): Error 2 from 'LD_LIBRARY_PATH=/usr/local/lib/boost_1.60 /sgm/bin/find_tags_motus --pulses_to_confirm=8 --frequency_slop=0.5 --min_dfreq=0 --max_dfreq=12 --pulse_slop=1.5 --burst_slop=4 --burst_slop_expansion=1 --use_events --max_skipped_bursts=20 --default_freq=166.376   --bootnum=632 --src_sqlite /sgm_local//motus_meta_db.sqlite /sgm/recv/SG-4002BBBK1630.motus  2>&1  ':
> unable to step statement
> Sqlite error: database is locked
> 
> 
> Subjob ID: 4347610
> 
> Running tag finder on receiver SG-4002BBBK1630 boot session 637
> Error in safeSys(bcmd, quote = FALSE): Error 134 from 'LD_LIBRARY_PATH=/usr/local/lib/boost_1.60 /sgm/bin/find_tags_motus --pulses_to_confirm=8 --frequency_slop=0.5 --min_dfreq=0 --max_dfreq=12 --pulse_slop=1.5 --burst_slop=4 --burst_slop_expansion=1 --use_events --max_skipped_bursts=20 --default_freq=166.376   --bootnum=637 --src_sqlite /sgm_local//motus_meta_db.sqlite /sgm/recv/SG-4002BBBK1630.motus  2>&1  ':
> Max num candidates: 51 at 1579613773.0093; now (1579613783.1842): 16
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  Failed to commit remaining inserts.
> Sqlite error: database is locked
> Aborted
> 
> 
> 

Batches appear to come in pairs every time. Batches before and after errors have been processed successfully and can be seen in the deployment timeline.

The job status is listed as 'error', but the response email say the same 'Motus job processing complete' and any indication of an error is buried at within the job summary.

**Comment by Hussell** [comment]
This happens when there are two or more uploads for the same receiver being processed simultaneously. I think the instructions already say to avoid doing that. I'm rerunning the receiver now.

**Comment by leberrigan** [comment]
I was only uploading a single file at a time so I'm not sure how that could have happened.

**Comment by Hussell** [comment]
If you upload a second, third, etc. file containing data from the same receiver before you receive the email about processing being complete, then this can sometimes happen. Mostly it doesn't, which is why this hasn't gotten fixed yet.
