### ISSUE TITLE
Users missing from project 27

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#79]
When logged into the livesite, there are no users listed for project 27: https://motus.org/data/project/users?projectID=27, I tried adding a user and they didn't show up (Willow English).  BUT there are 5 users listed when I check on beta: https://beta.motus.org/data/project/users?projectID=27 including Willow so the add I attempted on the live site did go through.

I don't know if this affects other things, but it's strange.  I tried the user page on Chrome, Safari, and Firefox but users never showed up on the live site

**Comment by pmorrill** [comment]
Try going to a different project users listing, then back to #27. This is a known issue. (I just signed in and the users are listed on live site for project 27, for me).

**Comment by zcrysler** [comment]
Ah ok that worked, thanks!  I'll close this thread if it's already a known issue
