### ISSUE TITLE
Last Data Date can precede Deployment start date

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#790]
Occasionally the date of Last Data Processed is earlier than the actual start date of the Deployment in question.

This occurs when a receiver is swapped and a new deployment is created. If the "new" receiver came from an earlier deployment, the Last Data date for the new deployment becomes the most recent data date of the previous deployment of that receiver.

This can be confusing when viewing these dates in the Manage Receivers section, but it can also trigger a "No recent data" validation error as well.

This does not happen everywhere. The pop up on the map correctly takes the current deployment into account.

Below is an example.

![image](https://user-images.githubusercontent.com/55001144/91665663-48428f80-eac5-11ea-82fe-de015e67ecd2.png)

Displayed correctly in the map (no data yet)

![image](https://user-images.githubusercontent.com/55001144/91665821-5e9d1b00-eac6-11ea-85a3-30530f9d763f.png)

Date of previous deployment for that receiver in the Manage Receivers page

![image](https://user-images.githubusercontent.com/55001144/91665816-547b1c80-eac6-11ea-8276-ee550306c9a8.png)

Date of previous deployment also in the Data Issues page

**Comment by StuMackenzie** [comment]
Please identify action to be taken, or close.

**Comment by jsayers-bsc** [comment]
"Last Data" date on the Manage Receivers and Data Issues page should track the current deployment, not a previous deployment. 

Not sure how quick a fix it would be or if it needs to wait until Stations replace deployments...
