### ISSUE TITLE
Test Tags in Data Summaries

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#792]
Contrary to what's stated on the [tag deployment editing page](https://motus.org/data/tag/deployment/edit?projectID=296&id=11465), test tags **[do show up in data summaries](https://motus.org/data/receiverDeploymentDetections?id=4972)**.

I do not think this is necessarily wrong - in fact, I believe we should keep it this way until we have a method to hide test tags when not logged in as a project collaborator. These detection summaries are used frequently by researchers for testing tags so we should not interfere with that.

---
If everyone agrees with the above, then I think we should: 
1. Label test deployments as tests in the 'species' field or something so it's obvious what they are. Right now they look the same except the species is blank.
2. Change text fragments to say that they will be labelled as tests in detection summaries.

**Comment by StuMackenzie** [comment]
Agree.

**Comment by jsayers-bsc** [comment]
Now done, and it's a big improvement for summary tables.
