### ISSUE TITLE
Erroneous Tag Models

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#795]
I just found out that project 250 has a number of [tags registered this year](https://motus.org/data/project/tags?projectID=250) with the **wrong tag model**. The model NTQB-2 was entered instead of NTQB**2**-2. This will affect the calculated lifespan as the newer tag models are expected to last significantly longer.

Given the tag models have fairly similar names, should we deprecate certain tag models as they are discontinued? 

Also, how do we go about changing a tag model after registration?

**Comment by leberrigan** [comment]
@denislepage - Could you contact Lotek about which tag models have been deprecated? 

<ul>
<li value="ACT-393">ACT-393</li>
<li name="ACT-521">ACT-521</li>
<li name="ACT-626">ACT-626</li>
<li name="ANTC-M1-1">ANTC-M1-1</li>
<li name="ANTC-M2-1">ANTC-M2-1</li>
<li name="ANTC-M3-1">ANTC-M3-1</li>
<li name="ANTC-M3-2">ANTC-M3-2</li>
<li name="ANTC-M4-2">ANTC-M4-2</li>
<li name="ANTC-M4-2L">ANTC-M4-2L</li>
<li name="ANTC-M4-2S">ANTC-M4-2S</li>
<li name="ANTC-M6-1">ANTC-M6-1</li>
<li name="ANTC-M6-2">ANTC-M6-2</li>
<li name="ANTCW-M1-1">ANTCW-M1-1</li>
<li name="ANTCW-M2-1">ANTCW-M2-1</li>
<li name="ANTCW-M3-1">ANTCW-M3-1</li>
<li name="ANTCW-M3-2">ANTCW-M3-2</li>
<li name="ANTCW-M4-2">ANTCW-M4-2</li>
<li name="ANTCW-M4-2L">ANTCW-M4-2L</li>
<li name="ANTCW-M4-2S">ANTCW-M4-2S</li>
<li name="ANTCW-M6-1">ANTCW-M6-1</li>
<li name="ANTCW-M6-2">ANTCW-M6-2</li>
<li name="LIFETAG1">LIFETAG1</li>
<li name="LIFETAG2">LIFETAG2</li>
<li name="NTQB-1">NTQB-1</li>
<li name="NTQB-1-LW">NTQB-1 (lightweight)</li>
<li name="NTQB-2" selected="">NTQB-2</li>
<li name="NTQB2-1">NTQB2-1</li>
<li name="NTQB2-2">NTQB2-2</li>
<li name="NTQB2-3-2">NTQB2-3-2</li>
<li name="NTQB2-4-2">NTQB2-4-2</li>
<li name="NTQB2-4-2S">NTQB2-4-2S</li>
<li name="NTQB2-5-1">NTQB2-5-1</li>
<li name="NTQB2-6-1">NTQB2-6-1</li>
<li name="NTQB2-6-2">NTQB2-6-2</li>
<li name="NTQB-3-2">NTQB-3-2</li>
<li name="NTQB-4-2">NTQB-4-2</li>
<li name="NTQB-6-1">NTQB-6-1</li>
<li name="NTQB-6-2">NTQB-6-2</li>
<li name="NTQBW-2">NTQBW-2</li>
<li name="NTQBW-3-2">NTQBW-3-2</li>
<li name="NTQBW-4-2">NTQBW-4-2</li>
<li name="NTQBW-6-2">NTQBW-6-2</li>
<li name="NTS-1">NTS-1</li>
</ul>

**Comment by cjardine-bsc** [comment]
I looked at making this change in the DB. All the tags registered in 2020 are NTQB2-2, the ones from 2019 are NTQB-2. 

Did someone else already make the change or is it the 2019 tags that need updating?

**Comment by denislepage** [comment]
Response from Lotek, though I am not sure how many of the other ones we need to continue allowing registration and for how long. 

We will need to follow up regarding NTP-1. What do we need from them to calculate the lifespan parameters? Anything else we need to know? @cjardine-bsc  Do we have that process documented?

Currently all that are now available are

•	ACT-393
•	ACT-521
•	ACT-626
•	NTQB-2
•	NTQB2-1
•	NTQB2-2
•	NTQB2-3-2
•	NTQB2-4-2
•	NTQB2-4-2S
•	NTQB2-5-1
•	NTQB2-6-1
•	NTQB2-6-2
•	NTS-1

there is also an NTP-1

**Comment by StuMackenzie** [comment]
Need to add CTT models to list - particularly PowerTags if not already on it and assign lifespan to PowerTags. See https://github.com/MotusDev/Motus-TO-DO/issues/675
