### ISSUE TITLE
Europe Issues

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#796]
Placeholder to summarize and discuss problems with Rene Jansen and Bart Noort's project as discussed in email.

1) processing issues (#799)
2) 166 tags being detected (#784)

Needs resolution.

**Comment by jsayers-bsc** [comment]
# 2 has been resolved through reprocessing the receivers. At least, of the receivers I'm aware of.

**Comment by StuMackenzie** [comment]
Has there been any correspondence/followup with the project(s)?

**Comment by leberrigan** [comment]
1. They would like all of Europe's receivers reprocessed from August 15 to now. Not sure how feasible that is...
2. [This has been resolved-ish](https://github.com/MotusDev/Motus-TO-DO/issues/800). We probably still need to fix the burst intervals of some tags that were manually registered.

**Comment by StuMackenzie** [comment]
Closed in deference to : processing issues (#799)
    166 tags being detected (#784)
