### ISSUE TITLE
Creating a new tag deployment

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#80]
When I create a new tag deployment:
- java.lang.IllegalArgumentException: Unable to find 'tag_deployment_edit_success' in the table of error codes. (Note this should probably be 'tag_deployment_create_success'.)
- when I go back to Manage Tags and edit the tag again, the new deployment doesn't show up in the table of deployments for the tag (e.g. https://beta.motus.org/data/tags/edit?projectID=0&id=14979) until I try to edit another tag first (i.e. the cached table isn't being updated when a new deployment is created)
- the deployment start and finish times I enter are saved as times four hours earlier (like #78, but for tag deployments)
- I can't edit the start or end times even if I'm logged in as an administrator

**Comment by pmorrill** [comment]
Good catch re the creation step: I have updated the code to force offset of 00:00 for these inserts. Also added the missing success code.
