### ISSUE TITLE
"Permission denied" when trying to download data through R

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#802]
A collaborator (userID [19686](https://motus.org/data/admin/user_id?id=19686)) is unable to access data from project 161 to which they were given read permission on September 8. They are still unable to access the project as of Sep 15.

They have been on other projects in the past (252 and 266) and are still able to access those projects.

This and #801 seem to relate to changes made around the same time as the service interruption on September 8 - could this have anything to do with it?

**Comment by denislepage** [comment]
I don’t expect the 2 things are linked. Permission issues are more likely related to recent changes that we made to support open access.

@pmorrill, what are the procs that you use to build a list of projects for the API? I can check the database.

**Comment by pmorrill** [comment]
The project lists are retrieved from vwR_User_auth. You should be able to query that view with the user id to see what project lists are in their for him.

Looks like all three of the access lists for id 19686 are: 161,252,266. So that part is working ok

**Comment by denislepage** [comment]
As discussed today, the R package was pointing to the sandbox server by mistake.

I have posted the fix. People should reinstall their R package again. It may be worth posting a note to the listserv for people to make sure they have the latest version.

@steffilazerte, the onload file had the sandbox URL in the master branch. I’m not sure whether we need to keep other branches when we’re not actively working on features. Perhaps not, but master should always point to the main server.

**Comment by steffilazerte** [comment]
Argh, I could have sworn that I fixed that :(

**Comment by denislepage** [comment]
OK, when trying to fix this, I accidentally recreated a sandbox branch from my local copy. That one probably needs to be deleted, as it is likely far behind, regardless whether we do want to keep a sandbox branch or not.

**Comment by steffilazerte** [comment]
> @steffilazerte, the onload file had the sandbox URL in the master branch. I’m not sure whether we need to keep other branches when we’re not actively working on features. Perhaps not, but master should always point to the main server.

Yes, I try to make sure (it's in my checklist but must have slipped through this time). But I usually delete the sandbox branch (I'm not sure if I did this time) and then recreate it based on master. Right now I have a local sandbox branch because I am working on the gpsAll and activityAll entry points to figure out... right?

**Comment by jsayers-bsc** [comment]
Is the version number changed at all following this fix or is is still 4.0.0?

**Comment by steffilazerte** [comment]
The version number was not changed... but it totally should have been. I bumped it up to v4.0.1.

**Comment by steffilazerte** [comment]
Can someone confirm that the new version does indeed solve the problem? Then we can close this issue and feel good :grin:

**Comment by leberrigan** [comment]
Yes, it works!
