### ISSUE TITLE
Tag Registration Codeset Handling

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#803]
Handle strings from "tagreg.txt": https://github.com/MotusWTS/motusServer/blob/b0c8e409f8320b3ed84221e05917ab4e7e4475aa/R/handleRegisterTags.R#L135

Get Lotek codeset: https://github.com/MotusWTS/motusServer/blob/b0c8e409f8320b3ed84221e05917ab4e7e4475aa/R/ltGetCodeset.R

**Comment by denislepage** [comment]
Those ones I have dealt with in the Lotek6M branch.

https://github.com/MotusWTS/motusServer/commit/05baf5b52d2a3595cfa73112d24a365bd1ea8f6b#diff-e1e1d3d40573127e9ee0480caf1283d6

This will need careful review before we can test on the server. Some changes are likely also needed on find_tags, and they are being investigated.
