### ISSUE TITLE
Reset sync on connected SG

### ISSUE THREAD

**Issue by adamdsmith** [MotusDev/Motus-TO-DO#808]
Had a unit fail last year that I just got online again yesterday morning.

SG-F964RPI3EF7C (https://sgdata.motus.org/status?jobsForSerno=SG-F964RPI3EF7C&excludeSync=0)

However, it doesn't appear to be syncing as the "next sync date" remains December 2, 2019.

Any need or way to reset this so it begins syncing again?

**Comment by StuMackenzie** [comment]
Sorry for missing this earlier Adam - we'll look into it.

**Comment by adamdsmith** [comment]
Thanks Stu. I think it worked itself out. Closing this...
