### ISSUE TITLE
Pros and Cons of Various Tracking Technologies

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#810]
I've put a comparison table of different tracking technologies for an upcoming presentation and I thought it might be a good thing to have on our website.

Let me know if you spot any errors in the table below:

  | Banding | Satellite | RADAR | Geolocator | GPS Tags | Radio Telemetry
-- | -- | -- | -- | -- | -- | --
Price | Cheap | Expensive | Cheap* | Moderate | Moderate | Moderate
Size | Tiny | Large | NA | Small | Small | Small
Location data source | Experienced observers | Satellite | RADAR | Sunrise, sunset, and clock | Satellite | Receiver stations
Track individuals | YES | YES | NO | YES | YES | YES
Must be recaptured | YES | NO | NO | YES | YES | NO

![tracking comparison table](https://user-images.githubusercontent.com/35931796/94200501-e4777080-fe90-11ea-92f8-023f218564e0.png)

**Comment by denislepage** [comment]
You can probably add some measure of recapture rate (% of birds re-sighted at least once, banding: very low, geolocator: medium, motus: high, satellite: very high), and perhaps the location precision of each sighting (banding = 0m, satellite 10m, geolocator 100km, motus 10km), and the number of data points available per track (banding: 1 per capture, motus, 1 per tag burst, within antenna range, geolocator: 1 per day (except at equinox), satellite and GPS tags (high rate; battery dependent).

**Comment by cjardine-bsc** [comment]
Some GPS tags will let you download data via a blue tooth connection without recapturing. But hard to capture that with a yes/no but its worth noting.

**Comment by adamdsmith** [comment]
VHF connection as well

**Comment by StuMackenzie** [comment]
Moved to Slack #guides
