### ISSUE TITLE
Confusing error message when downloading data from a receiver with no data

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#814]
When downloading data (via _tagme) from a receiver that has no data associated with it, you get the following error:

> Error in tagme(sampled_DONGLES$receiverID[k], new = T, update = T) : 
>   Either the serial number 'SG-9E7GRPI37554' is not for a receiver registered with motus
> or you don't have permission to access it

Just to confirm, I am using my admin account to access these data. The receiver is registered to Project 287: https://motus.org/data/receivers/edit?projectID=287&id=3393

I anticipate getting emails from collaborators who are confused by this message so I recommend we modify it as follows:

> Cannot access data for receiver 'SG-9E7GRPI37554' either because no data exists in our database, the receiver has not been registered, or you do not have permission to access this receiver.

**Comment by leberrigan** [comment]
Yes, that makes sense! So does that mean there is a different error when you don't have permission to access it?

**Comment by steffilazerte** [comment]
If the data exists and you don't have access to it, you do get a different message:

`You do not have permission to access the data for this project or receiver. Please contact Motus support.'`

**Comment by steffilazerte** [comment]
@leberrigan fix has been pushed to beta4
