### ISSUE TITLE
"You do not have permission" to download SensorStation data

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#815]
Recently having some issues downloading SensorStation data. I thought this applied to only one receiver, but it's more widespread. 

When I download from 3 of the SensorStations we have installed in Ontario, I get the following message

> You do not have permission to access the data for this project or receiver. Please contact Motus support

This is this doesn't happen until _after_ the download process has already begun. 

CTT-A8D3250A4A97. 

![image](https://user-images.githubusercontent.com/55001144/94725399-afa06900-0329-11eb-8be1-baeb554b08cc.png)

CTT-97FB9AB20E31

![image](https://user-images.githubusercontent.com/55001144/94728962-06f50800-032f-11eb-80cd-e7fc569bd79b.png)

CTT-CDE43745B223

![image](https://user-images.githubusercontent.com/55001144/94729357-884c9a80-032f-11eb-8881-6862e7b98cc1.png)

I thought this may be related to the issue of the [R package pointing to Sandbox](https://github.com/MotusDev/Motus-TO-DO/issues/802), but I believe I am running the most recent version (4.0.0). I have also tried with the beta 4.0.9999 with the same result.

All of these are V2 SensorStations (or SeñorStation as auto correct would like to suggest). I have tried downloading several V1 SS without any issue, as well as several SG. So it may be related to V2 in some way. We do have one more V2 SS in Ontario but at the moment I'm getting an [error](https://github.com/MotusDev/Motus-TO-DO/issues/816). 

(Edited to remove other receiver since it's likely a different problem)

**Comment by jsayers-bsc** [comment]
> I'll need access to one of these receivers for `beta` so I can see about troubleshooting (@cjardine-bsc? @denislepage?)

You should be able to access these all now

**Comment by steffilazerte** [comment]
So all I can say is that I'm extremely confused! 

Let's take "CTT-A8D3250A4A97" as an example. Below is @jsayers-bsc original output:

![](https://user-images.githubusercontent.com/55001144/94725399-afa06900-0329-11eb-8be1-baeb554b08cc.png)

- It looks like `batchID` 1306668 is in the data, because the `nodeData` function is looking for node data associated with that `batchID`
- But when I download data from this receiver, I do not have a `batchID` of 1306668... So how does @jsayers-bsc data have this? Was there an update issue? Have you tried with a fresh data base?
```
library(dplyr)
t <- tagme("CTT-A8D3250A4A97", update = TRUE, dir = "../")
# Checking for new data for receiver CTT-A8D3250A4A97 (deviceID: 1802)
# activity:   610 batch records to check
# batchID  1240533 (#     1 of    610): got      3 activity records
# Downloaded 3 activity records
# nodeData:   633 batch records to check
# Downloaded 0 nodeData records

tbl(t, "batches") %>%
    filter(batchID == 1306668)

# Source:   lazy query [?? x 11]
# Database: sqlite 3.30.1 [/home/steffi/Projects/Business/BSC/MOTUS/CTT-A8D3250A4A97.motus]
# … with 11 variables: batchID <int>, motusDeviceID <int>, monoBN <int>, tsStart <dbl>, tsEnd <dbl>, numHits <int>,
#   ts <dbl>, motusUserID <int>, motusProjectID <int>, motusJobID <int>, source <chr>
```
- Further, I do not have *any* node data, but since this is a V2 SensorStation receiver, I should, right?
```
tbl(t, "nodeData")

# Source:   table<nodeData> [?? x 15]
# Database: sqlite 3.30.1 [/home/steffi/Projects/Business/BSC/MOTUS/CTT-A8D3250A4A97.motus]
# … with 15 variables: nodeDataID <int>, batchID <int>, ts <dbl>, nodeNum <chr>, ant <chr>, sig <dbl>, battery <dbl>,
#   temperature <dbl>, nodets <dbl>, firmware <chr>, solarVolt <dbl>, solarCurrent <dbl>, solarCurrentCumul <dbl>,
#   lat <dbl>, lon <dbl>
```
- If I directly download the node data (using an internal function, do not do this at home unless trouble shooting) associated with batch 1306668, I do get node data (but the device ID doesn't match that of CTT-A8D3250A4A97...

```
motus:::srvNodes(batchID = 1306668, projectID = NULL, nodeDataID = 0)

#  projectID motusDeviceID nodeDataID batchID         ts nodeNum ant  sig battery temperature     nodets firmware solarVolt
#1        213          1860   24239011 1306668 1599792559  32b81c  L4  -99    4.11          20 1599792560    1.8.0      0.02
#2        213          1860   24239012 1306668 1599792571  327c40  L4  -92    4.07          23 1599792571    1.8.0      0.02
#3        213          1860   24239013 1306668 1599792598  32638b  L4  -92    4.06          21 1599792597    1.8.0      0.01
#4        213          1860   24239014 1306668 1599792612  3282b5  L4  -88    4.04          19 1599792612    1.8.0      0.02
```

So is it possible that @jsayers-bsc data base has incorrect batchIDs? If so, the motus R package would try to download the node data from the batches, and if @jsayers-bsc doesn't have access to THAT device (probably the next batchID in the list which isn't shown in this output), we would get the error message (looking like it was part way through the download because it's a separate server call). But that doesn't explain why there is no node data for that receiver...

I had very similar results for CTT-CDE43745B223.

@denislepage, @cjardine-bsc, @pmorrill, any thoughts?

**Comment by pmorrill** [comment]
Need a quick R tutorial! How do I get the actual MotusWTSD/motus source R code on my system? I have R-Studio, and Rtools in place. I ran remotes::install_github("motusWTS/motus@master") but only got binaries (I think). My R-studio does not give me access to the original R files. There must be an option I am missing?

I have done this before and don't recall this issue.

**Comment by denislepage** [comment]
From R studio, you can load the binaries with install_github as you did. To use the package, you can do library(motus) and then tagme()…

To debug instead and/or make custom edits, you need to clone the repo into a folder, and create a new project that points to that folder from R studio. To compile that version, you should only have to do build (on the right hand-side of your screen), then you can call library, then tagme. You can also set breakpoint in the code with that approach.

Running the install_github first will probably install the package dependencies. Pretty sure compiling your own code will not handle that.

**Comment by steffilazerte** [comment]
@pmorrill you can also use the `usethis` package to download and clone the package directly from github:

```
install.packages("usethis")
usethis::usethis::create_from_github("MotusWTS/motus", destdir = "folder-where-it-should-go)
```
As @denislepage said, by installing the package binaries, you've probably already installed the dependencies. But you can also do this by opening motus as an RStudio project (open the `motus.Rproj` file) and then use the remotes package:

```
install.packages(remotes")
remotes::install_deps()
```

Let me know if you have any more questinos

**Comment by jsayers-bsc** [comment]
So....

First it seems that the local data copy was part of the problem. Deleting and re-downloading each receiver resulted in success. So that's good. But there still seems to be some weirdness here.

Looking into the batchIDs that seemed to have triggered the error of two of the receivers confirmed that they belong to different receivers, as @steffilazerte noticed. But oddly, they _both_ belong to Device 1860, that's the receiver at the centre of [this issue](https://github.com/MotusDev/Motus-TO-DO/issues/813), where some of us got "Error: This receiver database does not have a valid deviceID stored in it".

It's not as clear which batchID might have triggered the error for the receiver CTT-97FB9AB20E31. When I looked at the last batchID printed it came from a different receiver yet again (a Lotek one). And when I looked into multiple other batchIDs, they _also_ came from different receivers.

So that leaves me with a couple questions.

- Shouldn't each receiver's data _only_ contain batchID's from that same receiver? How did batchIDs belonging to different receivers end up in any receiver's data in the first place? 
- Is it just a coincidence that at least two of these receivers had errors associated with the same other receiver, which itself has had been problematic recently?
- Does this error have anything to do with Permissions as the error suggests? I would think not since I should have access to Device 1860. But when I just tried now to download data directly from a couple other SensorStations as part of this project I get a similar Permissions related error:   _Either the serial number 'CTT-478D157E0C9A' is not for a receiver registered with motus
or you don't have permission to access it_. Well that's odd!

One side note for @steffilazerte : I don't believe it's odd that some of these SensorStations did not have node data. Nodes are only an option for SensorStations, but many or most won't actually have nodes associated with them.

**Comment by steffilazerte** [comment]
1. For what it's worth I don't *think* it's related to the CTT data in R bug (#813).
2. The "permissions" error you mention for "CTT-478D157E0C9A" is actually related to (#814), which is really just a confusing error message. The problem here is that there is no data for that receiver! I *just* fixed this in the beta4 branch.

**Comment by steffilazerte** [comment]
Is this issue still a problem? Or have we resolved this? [It sounds like a lot (if not all) of these issues have been addressed](https://github.com/MotusDev/Motus-TO-DO/issues/813#issuecomment-714828080)?

**Comment by jsayers-bsc** [comment]
Deleting local data files resolved the issue so in that sense it's resolved. No idea how multiple data files became corrupted on my end. But that's a question for another day -- next time it happens!
