### ISSUE TITLE
ChartsJS vs. D3

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#818]
I've been investigating the use of different tools for data visualizations and I've come to the conclusion that D3 beats them all, it's just more complex. 

ChartJS is probably the next best thing that is much simpler to use,  but also slower and more restrictive. I've done some playing around with both packages and found ChartJS to be somewhat frustrating to work with its constraints, while D3 is more difficult to understand, but actually works with a similar intuition as R so I'm finding it not that bad.

### Pros
- Very simple to code.
  - Responsive to screen size and other interactions by default.
  - Legends produced by default

### Cons.
- Relatively slow to render
- Uses Canvas rather than SVG
- Not as easy to load external data (e.g.: JSON)
- Difficult to manipulate data
- Fairly constrained to canned code.

### Pros
- Designed for data visualization, but far more versatile than that
   - Data and geo visualization, DOM utilities (replaces JQuery), Data utilities (replaces Lodash), animations, analysis
- Highly customizable
- Very fast
- Efficient data manipulation
- Compatible with many data types
- Structured as a vector-based language like R
- Can use SVG or Canvas
- Packages well with React

### Cons
- Complex --> steep learning curve which has [discouraged some](https://medium.com/@PepsRyuu/why-i-no-longer-use-d3-js-b8288f306c9a)
- Takes longer to code each component
  - Adding legends requires additional code
  - Making charts responsive requires additional code

**Comment by denislepage** [comment]
That is certainly also my conclusion for Naturecounts. Given that we won’t have a large number of plots to make, but they likely to be very customized, D3 is almost certainly the way to go.

I’m hoping @jhussell will become our resident expert of D3, and it would be great if you can start looking into the steps that you need to creating plots. In parallel, we should think about a structure for delivering the necessary data through the API. @lberrigan Can we identify a couple simple examples to get us started?

We are starting to work on something similar for NatureCounts, and I am sure we can share notes with the developers on this. Ideally, all plots would be built as a library of reusable functions, a bit like this:

```
<div id=”plot1”></div>
<div id=”plot2”></div>

<script src=”/scripts/motusDashBoard.js”></script>
<script>
var opts = {
                recv=”SG-1234BBK5678”,
                year=2019,
                height: 250,
                width: 600
};
                timelineRecvPlot(“plot1”, opts);
                timelineRecvPlot(“plot2”, opts);
</script>
```

**Comment by denislepage** [comment]
That is certainly also my conclusion for Naturecounts. Given that we won’t have a large number of plots to make, but they likely to be very customized, D3 is almost certainly the way to go.

I’m hoping @jhussell will become our resident expert of D3, and it would be great if you can start looking into the steps that you need to creating plots. In parallel, we should think about a structure for delivering the necessary data through the API. @LBerrigan Can we identify a couple simple examples to get us started?

We are starting to work on something similar for NatureCounts, and I am sure we can share notes with the developers on this. Ideally, all plots would be built as a library of reusable functions, a bit like this:

```
<div id=”plot1”></div>
<div id=”plot2”></div>

<script src=”/scripts/motusDashBoard.js”></script>
<script>
var opts = {
                recv=”SG-1234BBK5678”,
                year=2019,
                height: 250,
                width: 600
};
                timelineRecvPlot(“plot1”, opts);
                timelineRecvPlot(“plot2”, opts);
</script>
```

**Comment by leberrigan** [comment]
I have a working example here with three simple bar charts: https://lberrigan-motus.s3.us-east-2.amazonaws.com/d3test_02Oct20.html
- Deployment days per site
- Number of tag deployments per species
- Number of deployments per receiver

Ideally, we'd make these charts clickable, allowing us to view a receiver deployment history or a timeline when clicking on one of the bars, for example.

I've split things up into three main functions:
- **initiateChart(chartID, opts)**: Here you define the data source, variables to use, and chart type to create the chart object.
  - Data sources are database tables, such as 'recv-deps' or 'tag-deps'. Here I have them stored as JSON files.
  - Variables are defined as functions which accept an iterable and return a string or integer. 
- **loadChart(chartID)**: This is the function which loads the data and builds the chart based on which project has been selected.
- **updateChart()**: Loads data into all charts whenever project is changed.

**Comment by leberrigan** [comment]
# We've decided to use D3

**Comment by cjardine-bsc** [comment]
So much font.....
