### ISSUE TITLE
Boutique data permissions

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#819]
We need some testing of the permission structure of is_private_tag, is_private_project and is_private_sensor fields. Can I ask that @leberrigan or @jsayers-bsc use their non-admin accounts to test the following.

In sandbox:

    For a user registered to project 157 (investigating is_private_sensor)

f) tagme(SG-3214BBBK5558) : should succeed

    For a user registered to project 26 (investigating is_private_sensor)

g) tagme(26) : should succeed. Need to look a receiver deployment metadata. Is anything returned for SG-3214BBBK6472 (receiver from project 157, deployment id: 4092) ?

    For a user registered to project 1 (again) (investigating is_private_tag)

f) tagme(SG-5113BBBK0324) : Do any taghits or metadata come in for tag_id 16298 or 16208 (project 14) ?
f) tagme(1) : Same question: Do any taghits or metadata come in for tag_id 16298 or 16208 (project 14) ?

**Comment by leberrigan** [comment]
### Sandbox

#### For a user registered to project 157 (investigating is_private_sensor)
- tagme(SG-3214BBBK5558): SUCCESS

#### For a user registered to project 26(investigating is_private_sensor)
 - tagme(26) : SUCCESS
  - It's going to take me all day to download this so I'll update later.

#### For a user registered to project 1 (again) (investigating is_private_tag)
- tagme(SG-5113BBBK0324) : Do any taghits or metadata come in for tag_id 16298 or 16208 (project 14) ?
  - 16298: YES
  - 16208: NO
- tagme(1) : Same question: Do any taghits or metadata come in for tag_id 16298 or 16208 (project 14) ?
  - I have to download all this too.
---

### Setting the data server URL
Just as a note, it _is_ actually to possible to change the data server without rebuilding the package:
```
detach("package:motus", unload = TRUE)
motusServerURL <- "https://sandbox.motus.org/api"
library(motus)
```
I was using `Sys.setenv(...);` before which is not correct; [it needs to be a global environment variable](https://github.com/MotusWTS/motus/blob/9a8d9fe792579ab8b973a50e8fe22e5fb966cc34/R/z.onLoad.R#L54).

**Comment by leberrigan** [comment]
### Beta: https://beta.motus.org/api
####Same results 

#### For a user registered to project 157 (investigating is_private_sensor)
- tagme(SG-3214BBBK5558): SUCCESS

#### For a user registered to project 26(investigating is_private_sensor)
 - tagme(26) : SUCCESS
  - SG-3214BBBK6472: Yes, but only for deployment 2542 (project 75)

#### For a user registered to project 1 (again) (investigating is_private_tag)
- tagme(SG-5113BBBK0324) : Do any taghits or metadata come in for tag_id 16298 or 16208 (project 14) ?
  - 16298: YES
  - 16208: YES
- tagme(1) : Same question: Do any taghits or metadata come in for tag_id 16298 or 16208 (project 14) ?
  - 16298: NO
  - 16208: NO
---
