### ISSUE TITLE
Project 290 - missing CTT tags

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#820]
Twenty tags or so are missing from this project that were pushed from CTT?

These hung up somewhere? Bob apparently emailed Denis, Catherine, Paul.

Laura Cook is the contact on our end.

**Comment by cjardine-bsc** [comment]
No records in the DB API tables at the moment. I've emailed Bob to re-submit and we can do some testing. 

A couple of the tags (not all) are registered to project 0 right now, but the api import proc should update the project_id when CTT tries to register them.

**Comment by cjardine-bsc** [comment]
TagId MotusProject RegisteredAt
"61617F4B" 290 "2020-09-29 21:55:04.067765+00"
"6152004C" 290 "2020-09-29 21:55:03.382901+00"
"61617F4C" 290 "2020-09-29 21:55:02.586672+00"
"61333355" 290 "2020-09-29 20:43:45.964038+00"
"61332A07" 290 "2020-09-29 20:43:45.31916+00"
"61332D34" 290 "2020-09-29 20:43:44.637526+00"
"61332D33" 290 "2020-09-29 20:43:43.974049+00"
"61334B4B" 290 "2020-09-29 20:43:43.285468+00"
"61336661" 290 "2020-09-29 20:43:42.586262+00"
"6152614C" 290 "2020-09-29 20:43:41.880274+00"
"61525266" 290 "2020-09-29 20:43:41.186411+00"
"61332D78" 290 "2020-09-29 20:43:40.515557+00"
"61334B19" 290 "2020-09-29 20:43:39.764159+00"
"61525578" 290 "2020-09-29 20:43:39.047942+00"
"6133194C" 290 "2020-09-29 20:43:38.366149+00"
"61331907" 290 "2020-09-29 20:43:37.712786+00"
"61526634" 290 "2020-09-29 20:43:36.806585+00"
"61332D07" 290 "2020-09-29 20:43:36.102517+00"
"61334C07" 290 "2020-09-29 20:43:35.432813+00"
"61334B78" 290 "2020-09-29 20:43:34.751284+00"

**Comment by denislepage** [comment]
A bug has been located. A fix is in the works, and Bob should have the correct userID to use now.

Was tied to multiple profiles sharing the same email address (e.g. landowners). Credits go to @cjardine

**Comment by StuMackenzie** [comment]
Only elevating this because I think we can close?

**Comment by cjardine-bsc** [comment]
The bug has been fixed, but these tags are not all registered to project 290 yet. 13 of them are still in project 0. Should we be moving those to 290?

id	project_id	mfg_id
49034	0	6133194C
49033	0	61332D33
49032	0	61332D78
44283	0	61333355
48959	0	61334B19
49029	0	61334B4B
48969	0	6152004C
49043	0	61525266
43944	0	61525578
48958	0	6152614C
45838	0	61526634
49041	0	61617F4B
49044	0	61617F4C
49058	290	61331907    
49061	290	61332A07    
49057	290	61332D07    
49060	290	61332D34    
49055	290	61334B78    
49056	290	61334C07    
49059	290	61336661

**Comment by cjardine-bsc** [comment]
Whoops. I was looking in Sandbox. They are all in 290 in live. 

Closing!

**Comment by cjardine-bsc** [comment]
Should be closed.
