### ISSUE TITLE
"Pending" vs. "Active" deployments delineated by local time, not UTC.

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#825]
I'm assuming this is a minor one, but I thought I'd just throwing this out there in case it's an issue elsewhere or there are bigger consequences to this.

Normally deployments are set as 'pending' if they are in the future. However, if you register a deployment which starts at the current time, it will be listed as 'pending' until 3 hours (ADT) have passed.

Is it possible that this would prevent the first few hours of detections from being allocated to each deployment? Is this because of the way the deployment form is interpreting the dates, that is, converting them to UTC when it shouldn't?

**Comment by denislepage** [comment]
Deployment start dates are saved in the database as datetimeoffset (time with offset).

This issue however could have to do with the SQL function we use, where it expects the time to be provided in UTC and we’re passing the local time instead. I suspect it’s more of a display issue than a data storing issue.

**Comment by cjardine-bsc** [comment]
Yup. The computed column for status was using GETDATE()

I've changed that to GETUTCDATE() in sandbox. Want to test and close?
