### ISSUE TITLE
NodeNum vs. nodeNum for sample data

### ISSUE THREAD

**Issue by steffilazerte** [MotusDev/Motus-TO-DO#827]
I'm not sure if this is a recent change or just something I never noticed before.

**For the sample data only**

The `runs_for_tag_project` API entry point returns `nodeNum` on Sandbox, but `NodeNum` on beta and master.

This is a pretty minor fix, but would be nice if the sample tables matched the "real" tables.

**Comment by denislepage** [comment]
That’s a database fix for @cjardine-bsc

**Comment by cjardine-bsc** [comment]
Done while you were typing that ;-)
