### ISSUE TITLE
CTT Data Upload Interuption - October 2020

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#828]
Known issue, but not on Git - Only posting now because collaborators are wise to us...

Project 213 alerted us that their CTT stations have not been uploaded since October 9. They're needing to provide an update to funders so are antsy.

**Comment by denislepage** [comment]
After some digging, I found a bug in the AWS client that were made a while ago. We have created our own custom JSON libraries, but there was a conflict where the org.simple package was still being used. I don't know if this impacted all AWS related tasks. Possibly.

To compound the issue, the upload task was not correctly handling exceptions nor terminating properly, so it made it harder to see when problems occurred.

There are about CTT 80,000 files pending upload to AWS.  It's doing something now. I'll have to wait and see if that's anything useful...

**Comment by Hussell** [comment]
Paul found (another?) reference to org.json.simple and fixed it. It's deployed on sandbox and I'm monitoring to see whether the fix worked or not.

**Comment by pmorrill** [comment]
The aws browser is now working again, so that is a good sign.

**Comment by denislepage** [comment]
Great. One less problem to worry about for today, maybe.

Perhaps we should look to remove the jar for json simple and make sure we always use the custom one. I may have to do the same in bscbase, and perhaps some of the JSP’s, but I’ll look into that aspect.

**Comment by Hussell** [comment]
CTT files were successfully uploaded and processed last night.
