### ISSUE TITLE
Centralize field names and table creation

### ISSUE THREAD

**Issue by steffilazerte** [MotusDev/Motus-TO-DO#829]
@denislepage I'm running into some complicated testing procedures when it comes to ensuring that field names and table updates are consistent.

To streamline and centralized things, I'd like to create an internal data frame of field names, something like:

```
> field_names
     table           name                                type
1      gps          gpsID                  BIGINT PRIMARY KEY
2      gps        batchID INTEGER NOT NULL REFERENCES batches
3      gps             ts                              DOUBLE
4      gps          gpsts                              DOUBLE
5      gps            lat                              DOUBLE
6      gps            lon                              DOUBLE
7      gps            alt                              DOUBLE
8      gps        quality                             INTEGER
9      gps       lat_mean                              DOUBLE
10     gps       lon_mean                              DOUBLE
11     gps        n_fixes                             INTEGER
12 batches        batchID                 INTEGER PRIMARY KEY
13 batches  motusDeviceID                             INTEGER
14 batches         monoBN                             INTEGER
15 batches        tsStart                           FLOAT(53)
...
```

This would then be coupled with my existing `makeTables()` function in `ensureDBTables()` to quickly create tables for new data bases or replace missing tables (including extra SQL calls as necessary). 

`makeTables()` is already used to ensure consistent tables between tables created by `ensureDBTables()` and tables added through `updateMotusDb()`

This table would then also be used to make sure that we're not missing extra fields (I compare between the downloaded fields and the fields `ensureDBTables()` creates to make sure we're not missing any).

Right now I use an local sample data base, but it's a real pain to control differences between master, beta, and sandbox in this file.

What do you think? It would take a bit of time, but I don't think would be more than a couple of hours.

**Comment by denislepage** [comment]
The API could potentially provide this if that makes it easier, at least for data tables that are coming out of the API. SQL server and SQL lite fields are not exactly 1-to-1 matches in naming, but they all have equivalents.

There are a couple fields in the views that are not returned to the R client that would need to be stripped out, but that approach could in theory make it easier to add new fields, I think?

The risk is that the R package would then become closely dependent on the API, but it already sort of is, anyway.

Or, we can make this available to you and you still would have to manually compare with the local schema.

I will email you the current table names and columns, just so you can see what I mean.

We can make the content of this available through a motus_schema API entry point, for instance.

**Comment by steffilazerte** [comment]
I think it might be better to manually create the list locally for R to use. Any time we add new fields to a table, we need to make an update entry anyway, so I think it might be better to make sure that new fields are added deliberately to all data bases (new and existing) at the same time to avoid confusion. If we rely on the API then we risk having new data bases with fields that existing data bases don't have.

An alternative is to create the list of fields manually from the API, so it's quick and easy to update and we're not worried about typos. It'd be part of a script that gets run before every update, or as needed. I have tests that compare the locally created database fields to those returned by the API, it will error and warn me if the API returns fields which are not in the locally created databases, allowing me to check and see if I need to make an update.

I don't really think it's a problem that the R package depends on the API, since it's sole purpose is to interact with the API :grin: although I don't think we want minor API changes to break the R package.

**Comment by denislepage** [comment]
I’d probably be more comfortable with the alternative: make the metadata available for you, but still only do this at the build stage and make sure you have in place the right controls.

If the sort of data I sent you is helpful, we can turn that into an API entry point if you want, if only to allow you to find where changes might have happened and make sure we have all of the syntax consistent. Just say the word.

I guess you can do the same by calling each entry point, but that involves a bit more risk that something gets missed.

We’d probably want to avoid the app creating new schemas in real time based on the API, and as you say, we’d potentially have to deal with converting the schema of existing files as soon as changes are made, which isn’t what we want I think. IE, I think new fields should be dealt with by releasing a new package version, and that mismatched fields should continue to be ignored.

**Comment by steffilazerte** [comment]
I think having that table available through the API would be great, I'll just have to set up a script that pulls out the relevant details.  

However, this only makes sense assuming the table can be automatically populated. If someone has to manually add items to it, then it's probably simpler if I just manually add it to R directly without the middle step.

**Comment by pmorrill** [comment]
I have added this new entrypoint to the sandbox (only) api:

/api/sgdata/schema

At the moment, the code checks that the token is valid, but do we want to add further check? I am not perfectly clear how it will be used.

**Comment by denislepage** [comment]
Steffi will probably be the only user. Does having authentication make it more difficult for you @steffilazerte? I am not really concerned about making this available to anyone else, so we either only require user authentication, or no token at all.

**Comment by steffilazerte** [comment]
Working on sandbox now
