### ISSUE TITLE
API:  receiver/sensordeployments not returning any deployments

### ISSUE THREAD

**Issue by jbrzusto** [MotusDev/Motus-TO-DO#83]
I don't know when this began happening; but just noticed today.
e.g.

```bash
curl --data-urlencode json='{"serno":"SG-0815BBBK1352","hash":"XXX","date":"20171103080846",
   "fmt":"json","login":"john","pword":"xxx","projectID":null}'
   https://motus.org/api/receiver/sensordeployments
```
=>
```json
{"version":"2.0"}
```

**Comment by denislepage** [comment]
It seems to work for 1 project (e.g. “projectID”=1).

Did we change the behaviour of that API call to require a projectID? Are you expecting a complete list of all receiver deployments for all projects with this call?

**Comment by jbrzusto** [comment]
This used to return all receiver deployments.

**Comment by pmorrill** [comment]
By 'used to' - I assume that you mean 'before you switched to version 2', right?

I'll fix it up in v2 and post the change to beta server for deployment this AM.

**Comment by jbrzusto** [comment]
Sorry, my bad.  My code has been providing a projectID whenever it calls
this API, and that is working.  I only thought this was a bug because I was trying
to understand why I wasn't seeing the deployment record for SG-F783RPI36B63, which
is "deployed" on motus.org, but isn't making it into the list of records returned by
this API.
It is, however, listed by the API "receivers/list", but with a null deviceID.

So I'm closing this in deference to #84 and associated #55
