### ISSUE TITLE
User Interface Enhancements - CANARIE 3 October 2020

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#830]
Luc and I are brainstorming and playing with ideas in a powerpoint available here - https://drive.google.com/file/d/1MRM6PzfToNjaYfEzO4h_O32pq0djGwTX/view?usp=sharing

Using this git primarily as an FYI., but also to track changes, updates, and discussion.

If you want to look and don't have access, please let me know here.

We'll be primarily using Google Slides so we can mark, comment and chat as we go.

**Comment by jsayers-bsc** [comment]
I have ideas to add. I did send a request a while back but will send another.

**Comment by jsayers-bsc** [comment]
Nevermind, I just didn't realize I was let in!
