### ISSUE TITLE
Informing collaborators on tag model weight limits

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#831]
I had some thought about this today after a project had tags transferred to it that they cannot use under their permit. 

What do people thing about including recommended weight limits for all species in our species list? This would allow us to do the following:
- Warn collaborators when tag is too heavy for species selected ('Warning! Tag model weight exceeds %3 weight limit for typical lean weight of this species"). 
- Create a tag calculator to help collaborators design their study. 
  -  Select a tag to list compatible species or select a species to list compatible tags.

This might not be very straight forward as we'd have to deal with high variability among species and subspecies (i.e., SAVS vs. IPSP) and differences in regulations (are there all the same?).

**Comment by StuMackenzie** [comment]
That's a useful thing to put on our wish list. The warning is probably easy, but if it's part of the metadata then they've already deployed the tag on the species so it's too late. 

I'm a strong proponent in not allowing collaborators to select a species beforehand, so I'm not sure where it fits.

 Maybe part of a project planning suite. 1) Choose species 2) view available tag options... It's also a large part of guidance documents we're working on for tagging things in general, but that again is different.

S

**Comment by leberrigan** [comment]
> ... if it's part of the metadata then they've already deployed the tag on the species so it's too late.

That's a good point that I somehow missed! I agree that setting a species in the anticipated deployment doesn't make sense, but I'm pretty sure this is because of the way the current database validates deployments. I'll make a git about it.

I think there could still be use in flagging tag deployments so that collaborators know they exceed limits. Since we have an open dataset, anybody can go in and look for tags that have been deployed on birds that are too small and might raise a fuss - we should watch out for that. In most cases, there is just reasoning for large tags, such as the 2017 tag debacle, but we might want to keep track of this nonetheless.

**Comment by denislepage** [comment]
The rabbit hole here is generating the necessary data, which we likely don't have for all species globally, or even North America in a usable format. And of course, there is a range of values possible based on sex and subspecies. Some guidance would still be helpful. Perhaps a table of tags groups by weight categories, and some examples of species. Or interactive plots showing possible tags and have users enter the range of values manually for species that we don't have data for. I'm sure we can pull together SOME data, but having the flexibility to let users enter their own values seem key.

**Comment by denislepage** [comment]
Looks like we don't even have the weight in the database for more than a few tag models. Lotek can likely fill in the gaps easily.

**Comment by leberrigan** [comment]
Here's what I have on file:
### New tags
![image](https://user-images.githubusercontent.com/35931796/96646146-13eb9280-1302-11eb-83f7-819c0ec985a7.png)
### Old tags
![image](https://user-images.githubusercontent.com/35931796/96646180-249c0880-1302-11eb-9e7a-afb7b28dda22.png)

**Comment by denislepage** [comment]
I'm thinking of a presentation a bit like this (but better looking, and clearer). Pink shows the range of weight for a specific species. You'd only be able to use tags that are overlapping blue areas (<3%), and ideal would be to be in the paler blue section (<1%). Don't pay TOO much attention to the actual values, but the first tag 0.22 g would only support birds larger than 7.1g. Black-throated Blue are roughly 8.1 to 10.9, so they'd be ok. The next tag being heavier, it may only work for the larger individuals, and some tags would never work (e.g. the 1g tags!)

![image](https://user-images.githubusercontent.com/21110542/96650343-b99e0200-1300-11eb-85d4-8d59c949f002.png)

I find this a bit confusing myself to interpret, but may be be able to make this clearer somehow. You get the idea.

**Comment by denislepage** [comment]
The radio buttons would allow you to filter down the list to only tags that are within your target % of weight.

**Comment by StuMackenzie** [comment]
Closing until it becomes an active area of development and we can reopen.
