### ISSUE TITLE
CTT receiver uploads outage

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#833]
The ReadCTTFiles process on sandbox has been failing repeatedly for some time now. This prevents any new data from CTT receivers from reaching the tag finder.

**Comment by jsayers-bsc** [comment]
Would this also affect dual-mode SG's? I just ended a test deployment and don't see any LifeTags in the detections, though they were being detected on the Web Interface

**Comment by pmorrill** [comment]
I notice that the aws browser is not working either. Checked and recent changes to use org.bsc.json libraries missed one conversion in AWSClient. That **may** be the root of the issue, but not certain.

Please re-build the motus-base library with current code to see if it helps.

**Comment by Hussell** [comment]
Duplicate of #828.

**Comment by Hussell** [comment]
@jsayers-bsc, I think only uploads from CTT were affected.
