### ISSUE TITLE
Embedded Discussion Groups no longer supported

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#837]
We currently have posts to our discussion group embedded in the website here - https://motus.org/discussion/

There is a notice that this is no longer supported. I don't know how valuable having it on the website is, but I've always liked the transparency and openness it provides. 

So, perhaps we just ditch it, or perhaps there is a work around.

**Comment by denislepage** [comment]
The simplest would simply be to change the link in the menu to point directly to the Google site.

**Comment by denislepage** [comment]
They are also suggesting using iframes, which is easy enough.

Embedding groups in web pages


Using iFrames to embed groups in external web pages. Located in classic Groups under Manage group[and then]Information[and then]General information.
Instead, you can link to a group from an external web page and view the group in Groups.



It may be blocked by some people, but we can make the link to the group at the top.

Perhaps a better option if we want to keep some brand recognition.

**Comment by leberrigan** [comment]
iFrames are currently what we're using. This is what will be deprecated - links will soon be the only option.

**Comment by denislepage** [comment]
I misread, even after looking at it a second time. I thought these were 2 options on the right (iframe or link). We can simply use the direct link in the menu. Easy enough.

**Comment by StuMackenzie** [comment]
This is now in effect - google provides a redirect, but can we implement above, or we can we just link directly to https://groups.google.com/g/motus-wts

**Comment by denislepage** [comment]
I would just change the WP menu to point to that URL directly.

**Comment by leberrigan** [comment]
We might want to consider using groups.io
