### ISSUE TITLE
Receivers with no device ID

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#84]
There are receivers registered with deployments in project 123 that do not have receiver Device IDs associated with them: deploymentIDs 4130, 4203, 4378, 4364, 4365, 4366

**Comment by Hussell** [comment]
This is uncommon, but expected. It happens when people have entered metadata about their receiver, but the serial number hasn't been matched to a serial number from a batch of data yet. We currently have metadata for ~80 receivers with serial numbers which haven't been matched.

**Comment by denislepage** [comment]
More problematic is when it is the other way around. When John has pushed data for which there are yet no deployments.

Some of that may be due to typos in the project records.

John had outlined a solution to help with this (a registration file taken from the receiver). Not sure where that stands.

Denis

**Comment by zcrysler** [comment]
I'm not sure if this is the same or a slightly different issue, but there are receivers with no device ID that do have data associated with them, they were just placed with project 0:

project 48 has 6 receivers with data (https://sensorgnome.org/download/0/) but no device ID, they are deployments 4216, 4217, 4219, 4223, 4283, and 4338

**Comment by Hussell** [comment]
I've checked these deployments and receivers, and we don't have any batches of data from them yet. So I think this is the same issue.

**Comment by denislepage** [comment]
The 6 deployments listed above are for the following receivers, none of which have been registered or have a deviceID:

SG-0425RPI3CAF9
SG-0B38RPI3475B
SG-4F30RPI36C9C
SG-6581RPI35065
SG-7511RPI30BC5
SG-AC15RPI3C3A2

These are receivers that need to be registered.

**Comment by jbrzusto** [comment]
done:

serno| deviceID
---|---
SG-0425RPI3CAF9|951
SG-0B38RPI3475B|952
SG-4F30RPI36C9C|953
SG-6581RPI35065|954
SG-7511RPI30BC5|955
SG-AC15RPI3C3A2|956

**Comment by denislepage** [comment]
Thanks. I don’t know also if you need to do anything to ensure that the detection data gets included in the database.

We’ll need to start getting a better handle on these types of things once the process is up and running.

**Comment by zcrysler** [comment]
There are two more receivers that had data uploaded today that did not get device IDs for project 38:
SG-1315BBBK0113
SG-1315BBBK0132

Is this something I should be recording when I see it or have you guys got it covered?

**Comment by jbrzusto** [comment]
This issue is fixed on the new server; the old server (on which uploads are currently being
processed) is lagging further and further behind, but I'm getting close to everything running
from the new one.
