### ISSUE TITLE
Setting access levels at the receiver level

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#840]
Continuing from email...

Recently it was brought to our attention that a particular receiver is located next to a sensitive bat hibernaculum, and they would like the location somehow obscured.

But we don't currently have a way to set this at a receiver level; only project. So a couple options are:

- Set all receivers in this project to private. This gets the job done, but now everyone else whose tags were detected by any of this project's receiver won't see them. 
- Move the sensitive receiver to a new project with the appropriate access level. That's a much more targeted approach, but now adds some hassle for those management the project since there are two of them and they have to keep track of who's in each one. Not a big deal, but also not ideal.

Do others have a strong opinion on which is the "best" approach here? 

Also, I'm not sure how often this comes up, but a finer approach might be good — where access level can be set at the receiver (and tag?) level within a project (if it doesn't create too many other issues).

(for the moment actually, this isn't working as expected anyway when it comes to map view. see #839)

**Comment by denislepage** [comment]
It might be worth introducing the notion of private site, using the same rules as for projects (hidden or generalized), which would presumably override project status, as part of our site/location/station revamp. Not sure if that is something that will happen often enough. Creating a distinct project is easier for us, of course. Less convenient for users.
