### ISSUE TITLE
activity and nodeData re-check last batchIDs

### ISSUE THREAD

**Issue by steffilazerte** [MotusDev/Motus-TO-DO#841]
Right now, when an activity and nodeData download is resumed, the last batchID with activity/nodeData is used as the start point. However, if there are several batches that follow without any data, they will ALWAYS be rechecked, the messaging implying to users that there is new data.

Option 1. Hide the messages until there's "new" data
Option 2. Keep track of the last batchID actually checked... where would this be stored?

**Comment by leberrigan** [comment]
Is this still an issue? It's been over a year so it should be closed if not.

**Comment by steffilazerte** [comment]
It is, but I'm probably not going to fix it (it's not much of a problem). I'll close and reopen later if I think has to happen (thanks for the housekeeping!)
