### ISSUE TITLE
Mismatch between activity in R package and on receiver timeline

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#842]
Isolating this from https://github.com/MotusDev/Motus-TO-DO/issues/794#issuecomment-712249036 since it may not be related at all... 

There is a significant mismatch between the activity shown for this receiver in its [timeline](https://motus.org/data/receiver/timeline?year=2020&id=3395) and deployment plot. Both of those show radio activity between May and August 2020.

However, there is activity in the activity table downloaded through the motus R package since 2019-09-04 (the timeline shows activity up the 2019-11, then a large gap).

And even during the period in [2019 where both the timeline](https://motus.org/data/receiver/timeline?id=3395&year=2019) and the r data show activity, there is far more activity displayed in the timeline than in r, where only 10 days have activity. 

```
packageVersion('motus')
[1] ‘4.0.2’

m <- tagme('SG-4940RPI33FB7', new = F, update = T, forceMeta = T, dir = '../Data')
Checking for new data for receiver SG-4940RPI33FB7 (deviceID: 1506)
activity:     4 new batch records to check
batchID  1296586 (#     1 of      4): got      4 activity records
batchID  1296586 (#     1 of      4): got      0 activity records
batchID  1296587 (#     2 of      4): got      0 activity records
batchID  1296588 (#     3 of      4): got      0 activity records
batchID  1296589 (#     4 of      4): got      0 activity records
Downloaded 4 activity records
nodeData:     0 new batch records to check

# activity table
a <- tbl(m, 'activity') %>% collect() %>% as.data.frame() 

# most recent date in activity table
max(as.Date(paste(a$year, a$month, a$day, sep = '-')))
[1] "2019-09-04"

# number of days with activity
distinct(a, as.Date(paste(a$year, a$month, a$day, sep = '-')))
1                                         2019-07-17
2                                         2019-07-21
3                                         2019-07-23
4                                         2019-07-28
5                                         2019-08-01
6                                         2019-08-14
7                                         2019-08-02
8                                         2019-09-04
9                                         2019-07-01
10                                        2019-06-30
```

There are also no detections whatsoever in R for the period since the last activity record in 2019-09-04, not even anything with runLen of 2. Some stations are quiet, but that seems strange.

**Comment by cjardine-bsc** [comment]
We only generate batch Activity for hour bins where there are detections (the batches Activity table is used to determine noisy hourbins, so only hourbins with detections are relevant). 

The receiver timeline plots both detections and pulse counts. 

Looking at one of your batches from the example above (1296586) it has very few detections:

SELECT * 
  FROM [motus].[dbo].[det_runs]
  where batchIDbegin = 1296586 

But ample pulse_count data

SELECT *
  FROM [motus].[dbo].[det_pulse_counts]
  where batchID = 1296586 

Its maybe worth having a conversation about whether we want to change how we generate the batches activities summary (include hourbins with zero detections?) now that users may be using it for other purposes.

**Comment by jsayers-bsc** [comment]
Hmm... so Pulse Counts in the DB (and the receiver timeline) represent all recorded pulses, but the Activity table in the r data only contains pulse counts for hourBins that also have detections?

**Comment by cjardine-bsc** [comment]
I've always been a little unclear on the pulse count data and exactly what it represents, but yes, that's my understanding.

**Comment by denislepage** [comment]
Yes, pulse is the number of unique pulses per hour bin, including periods when there are no tags detected. That only applies to SG, not Lotek. It’s essentially a count of the number of rows in the data files (each represent a pulse).

Activity data is only calculated for those hour bins where tags have been detected, as far as I understand.

**Comment by cjardine-bsc** [comment]
The only issue with that explanation is that there are cases where the pulse_count is less than the number of detections for the same time period, which is what has me slightly unclear. 

It may be the number of non-identified pulses, but I'm not sure.

**Comment by denislepage** [comment]
My best guess is that it relates to which ts is used to calculate the hour bins. E.g., if they are calculated on the start of the run vs. the individual hits.

I’m not convinced it’s worth sorting out on the basis of a few discrepancies, but if there are bigger issues it may be worth it.

**Comment by jsayers-bsc** [comment]
Ok, so the mismatch I described above is not due to an error, but rather by design. I definitely was unaware of that distinction so that's good to know!

Ultimately, maybe it would be ideal to provide all activity in the r package (or at least mirror what's in the DB) for a couple reasons:

- We have been talking about offering the ability to access activity records across projects so that users can roughly determine what stations were active at a given time (#723). That's not nearly as useful if only a subset of activity records are passed into the r views.

- At the station level, activity in the Receiver Timeline and Deployment Plot are very helpful diagnostics. I don't know how many people would use the data coming from the R package for the same purpose, but consistency between what we are calling "activity" on the motus site and the r package would be helpful for its own sake. (Speaking of which, it's going to be _great_ when those timelines and plots are summarized by station across deployments!)

**Comment by cjardine-bsc** [comment]
Semantics...but ALL the activity data IS in the r-package and r views. We just don't generate activity data for hourbins that have no...well...activity.
 
Just wanted to make sure it was clear that we're not filtering anything from R  :D 

But yeah, as for figuring out which stations are active, I thought we were mainly using the GPS data for that. The activity data is mainly used to identify noisy sites and filter bad detections. The alternative would be to use pulse count data (though presumably a receiver could be active and not detecting any pulses?). 

As for nomenclature.......I'm staying out of it *holds hands up in surrender* 

I did some playing and I can change the activity calculation proc to include hourbins where there are no runs but there are pulse_counts. I've saved that and we can discuss rolling it out next Thursday.

**Comment by jsayers-bsc** [comment]
Semantics sure can be confusing!

We're using "activity" in two senses here. One refers to radio activity whether or not any of that activity resolves to a tag ID, and the other refers to radio activity that has been filtered based on whether there are tag detections. That the table simply called "activity" is the subset table is the what got me. Ok we're all good here! And it sounds like summarizing activity for any hourBins that contain pulses would be helpful.

(And yes, a receiver can be active and not detecting pulses. And actually a receiver can also be recording radio activity and detections, yet go long periods without GPS hits, so neither of those are entirely reliable for determining whether a station is active.)

Now that we got to the bottom of that, let's move on to agreeing on a single definition of the word "set".

**Comment by cjardine-bsc** [comment]
A summary for future @cjardine-bsc 

There is interest in a view (***not batches_activity***) that combines everything we know about pulse counts, tag detections, and GPS activity for all receiver deployments (and outside of deployments?) this could also potentially include some additional station health data from CTT that we don't currently have access to. The goal would be to pass this to users via R so they can know when a given station in the network is active. 

Notes: 

-Pulse counts from lotek receivers do not include detections that do not resolve to a tag_id
-pulse counts and numhits do not always align for sensorgnomes (reason unknown) 
-GPS data may be missing for batch re-runs
-no pulse count data from CTT yet.

**Comment by leberrigan** [comment]
This is a good time to start thinking of this again. A couple thoughts:
- We should discuss resolution: hour_bins are probably good enough
- We probably don't need to store this variable for each hour. Instead, it could be time up/time down as a 'active session' or something.
- We're going to need to develop a different proxy for up time for each receiver type. Here are some ideas on how to handle each type:
  - **Lotek SRX:** I think we can just not support this one. They account for a small proportion of stations and these receivers just don't provide us with the data we need.
  - **SensorGnome:** As stated previously, something like `(pulse_count > 0 || gps_hits > 0)` would suffice here. Yes, we have a bug with GPS hits being missing in some cases, but the plan is to fix that bug and even with it present this will still be useful for displaying up time on the dashboard.
  - **SensorStation:** Recall, these essentially contain SensorGnomes, but also provides more information through the SS side. So it already gets a GPS fix each hour, but we also get a check-in every six hours.

**Comment by cjardine-bsc** [comment]
I did a bunch of work to support this in sandbox: https://github.com/MotusDev/Motus-TO-DO/issues/1016

It needed testing, have you taken a peak? Do you feel its good to push to live?

**Comment by leberrigan** [comment]
Ahh -- one of those Gits that have run away... I'll take a look.

**Comment by tve** [comment]
Heads-up that the new SG emits a "C" record every 10 minutes into both data files (the "all" and the "ctt" ones). The C record has:
```
C,<timestamp>,<clock_accuracy>,<step>
```

**Comment by leberrigan** [comment]
Everything looks good from my end. Did you push to live?

**Comment by cjardine-bsc** [comment]
> Everything looks good from my end. Did you push to live?

You mean 1016?

**Comment by leberrigan** [comment]
Yes. and it has been.
