### ISSUE TITLE
Long site name causes error when creating a receiver deployment

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#845]
A few SQL errors have been received this morning from:

https://motus.org/data/receiver/deployment/edit?projectID=48&recvID=4105&action=create

The error is "String or binary data would be truncated.", and it seems to be due to attempting to insert a long site name into sensor_sites.name, an nvarchar(50) field. The new site name is "DuPont Environmental Education Center of Delaware Nature Society", 64 characters.

The database fix, for Catherine: increase the size of the column, e.g. to nvarchar(128) or nvarchar(MAX).

The website fix, for Paul: implement JavaScript and server-side checks to return error messages when the site name is too long to store in the database.

**Comment by cjardine-bsc** [comment]
Changed to varchar(128)

**Comment by cjardine-bsc** [comment]
Closed. Sensor Sites no longer used.
