### ISSUE TITLE
Pulse counts and radio activity for CTT antennas; 434 antennas are not displayed in plots on Motus.org

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#846]
Do we have plans to store pulse counts or their equivalent for CTT antennas in the database? While probably not as useful for flagging false positives as for Lotek tags, it's still useful information for determining whether a station is active. 434 antennas simply don't show up on the deployment plots, though detections do. On the receiver timeline there is a pop-up that says detections are ignored due to a lack of radio activity on the antenna, which causes concern for people when they see it.

**Comment by Hussell** [comment]
Ugh. I'm just going to remove that pop-up. Should have done that a long time ago.

**Comment by jsayers-bsc** [comment]
Do we plan on supporting activity tables as we do for 166 MHz antennas? Those are very helpful for identifying suspect periods for radio noise, and confirming station operation (though admittedly a little less so than for Nanotags).

**Comment by jsayers-bsc** [comment]
Poking again at this one (in response to another collaborator question about missing antennas in the Receiver Timeline and Deployment Plot).

We do seem to have pulse count data in the database for CTT receivers (and presumably dual-mode SG's once all the data is synced?) but this isn't represented on the website so when people check the status of their stations, all 434 MHz antennas are simply missing.

**Comment by jsayers-bsc** [comment]
We discussed yesterday that pulse counts are not available for SensorStations in the same way that they are for SensorGnomes, so we can't use that to generate "activity" summaries for each antenna. CTT does provide a crude measure of "activity" on the CTT portal for each SS using just the hit or beep data (probably similar to how we derive "activity" for Lotek receivers). I'm pretty sure beeps from false positives are included here as well, but how close this gets to the totality of radio activity recorded by the station isn't clear. 

![image](https://user-images.githubusercontent.com/55001144/112644601-fc1dba80-8e1b-11eb-9b8a-4a2d9a345b30.png)

On the Motus site, both the Deployment Plot and Receiver Timeline summarize activity per antenna. This is incredibly useful information in recognizing and diagnosing issue with a receiver. As it stands any 434 MHz is simply absent from both of these overviews, leading to frequent questions from collaborators as to why their antennas are missing. I've put in a couple screenshots below for a SensorStation where the 434 antennas are missing (the same is true for any dual-mode SG)

SS at [Little McCoy](https://motus.org/data/receiverDeployment?id=6129) has 2 434 and 3 166 antennas, shown in the deployment summary.

![image](https://user-images.githubusercontent.com/55001144/112645881-510e0080-8e1d-11eb-8b79-f860bb6267fe.png)

However only the 166 Antennas are displayed in the Deployment plot or Receiver Timeline.

![image](https://user-images.githubusercontent.com/55001144/112646068-84e92600-8e1d-11eb-92fd-301663421c42.png)


![image](https://user-images.githubusercontent.com/55001144/112646087-8adf0700-8e1d-11eb-8f43-b6dd821e84f8.png)

**Comment by adamdsmith** [comment]
Sorry, seeking clarification. Activity is not available for *any* ports, even 166s with FCD, or only for 434 ports?

**Comment by jsayers-bsc** [comment]
> Sorry, seeking clarification. Activity is not available for _any_ ports, even 166s with FCD, or only for 434 ports?

Activity on 166 ports shows up fine on both SensorStations and dual-mode SG's. But neither "activity" nor the antennas themselves show up for 434 MHz in the Deployment Plot or Receiver Timeline.

**Comment by leberrigan** [comment]
This is because we don't get activity data from 434 MHz radios. This is part of the nature of the data collected by these devices (via FSK modulated signal). What we can do is use # false positives as a proxy, but this isn't nearly the same. It will require further discussion with manufacturer to figure out what a good solution could be.

Closing comment since this is not a Motus-resolvable issue.
