### ISSUE TITLE
View Results Buttons - move/duplicate

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#85]
Can we please move or duplicate 'view results' options (e.g. 25,50, all) for all summaries to top of page as well as bottom.

**Comment by Hussell** [comment]
If you're using this control a lot, is there a better default value for some or all pages? (Not just from the ones on the list.)

**Comment by Hussell** [comment]
Speed doesn't seem to be a problem except with very large tables, so I've set the default to 100. I've also duplicated the control at the top of all tables that have it. Sandbox only for the moment, but we're planning to make a new beta deployment on Monday. E.g. https://sandbox.motus.org/data/projects
