### ISSUE TITLE
Summarizing detections by individual

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#850]
We were chatting a bit last week about displaying detections that are summarized by individual. We do in fact already have summaries by individual at the receiver deployment (soon to be station) level. They are presented in the timeline and to be honest even though they are very useful I often forget they are there!

Here are a couple suggestions for improvement of the individual summaries page to make it quicker and easier access to detections:

- Display individual summaries in table format with sortable fields (like the daily summaries)
- Provide column with information such as "number of days detected", "first date detected", "last date detected", etc. Similar information is provided already for tag deployments but not at the station level
- Display the summary of individuals _above_ the timeline plot? The timeline plot is a great visual presentation, but the list of individuals is probably a quicker way of getting at the important information (and put the visual presentation below the table? 
- Default sort by time Descending so that recent detections are displayed first (for individual and daily summaries)

**Comment by leberrigan** [comment]
I think this issue can be retired with regards to the new explore dashboard. This was posted prior to the initial demos.
