### ISSUE TITLE
Service Interruption: tagme failing - 09 Nov 2020

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#851]
We have received multiple emails this morning where collaborators have been unable to download data from Motus.org:

```
tagme(...)
Error: Login failed with error message
'Motus API request failed [503]
Unknown Error
```

I'm assuming this is just occurring because the server is unavailable.

It appears this no longer an issue, except one collaborators is still getting the following error which may or may not be related:
```
Error in UseMethod("db_has_table")  :
     no applicable method for 'db_has_table' applied to an object of class "c('SQLiteConnection', 'DBIconnection', 'DBIObject')"
````

I'm documenting this here so we can keep track of how often this happens.

**Comment by Hussell** [comment]
503 is the HTTP code for "Service Unavailable". We had an outage of 2 or 3 hours this morning where the servers and database were down.

**Comment by cjardine-bsc** [comment]
The database was locked this morning. I reset it when I got to the office and then went into a string of meetings (actually I did it while I was in a meeting....shhhhh). I'll try and sleuth out what went wrong now.

Denis, SP_WHO and SP_WHO2 were not returning anything in live. So I did a server restart.
