### ISSUE TITLE
Tag deployment info - metadata cleanup

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#852]
I'm not sure why I didn't catch this earlier or at the start, but never the less...

Display - eg. https://motus.org/data/tags/edit?projectID=231&id=32484

![image](https://user-images.githubusercontent.com/21124211/98732636-65b99280-236d-11eb-9883-cb0f1c19d6f7.png)

Marker Type and Number are really kind of useless to display here. Band/Ring number is more important.

Remove Marker Type and Number. Replace with Band/Ring Number.

Band Number should be Band/Ring Number

Marker Type - should be a marker in addition to a band or ring eg. Leg flag - this is really a yes/no because I can't think of any other type of marker. Open to suggestions. It isn't super important that we collect this, but 

There may be instances where marker number is populated and should be moved to band/ring number. 

Marker Number, should be a number in addition to band/ring number, eg. Flag Number.

**Comment by cjardine-bsc** [comment]
This is for @pmorrill

**Comment by leberrigan** [comment]
If you hover over the question mark next to 'marker type' when editing tag deployments, it says "Type of marker (e.g.: metal band)". This has resulted in many people entering 'metal band' as the marker type and entering the band number in 'marker number' field, leaving the 'band number' field blank.

If we are to force people to use the 'band number' field, we would also have to transfer everything from 'marker number' when band number is blank. Unfortunately, this would cause peoples scripts to break when joining by marker number so we'd have to warn everybody of this.

**Comment by StuMackenzie** [comment]
Closed in deference to #869
