### ISSUE TITLE
Insert Warning Notice on any public detection/track information 

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#854]
This notice is at the top of the View Tracks page - 

“Attention: These public animations have been created using broad filters based on theoretical flight speeds, logical geographic/time sequences, and at least 3 consecutive tag bursts at a single station. Individual tracks have not been inspected for accuracy. Please report any questionable tracks to motus@birdscanada.org to help us refine the filters.”

This should be bold, or bigger font. I can't change this from home if someone else can do that.

We've asked to put this warning wherever track information is displayed, but I can't remember or find where.

At a minimum can we put it at the top of every public detection table - eg. https://motus.org/data/receiverDeploymentDetections?id=4542

**Comment by leberrigan** [comment]
https://github.com/MotusDev/Motus-TO-DO/issues/564

**Comment by StuMackenzie** [comment]
Closed in deference to https://github.com/MotusDev/Motus-TO-DO/issues/564. Issue not resolved
