### ISSUE TITLE
Label Test deployments as such on outputs

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#856]
When test tags are used they still show up in station detection records - which is what we want, but it would be nice to be able to distinguish them more readily. 

Can we set a default species to TEST for any TEST deployment, or something like that ? See https://motus.org/data/receiverDeploymentDetections?id=5520

All SORA tags are accurately labelled as test deployments.

**Comment by cjardine-bsc** [comment]
Test tags should always have their species_id as null. We've blocked entry of species_id whenever it's a test (......right?). 

But we can alter the query to put "Test" in the name column if test = TRUE. 

I made that change in vwBase_tags_deployments but that did not update https://sandbox.motus.org/data/receiverDeploymentDetections?id=5520

@Hussell are you hard coding this query? If so then I'd like to move that over to the DB, pretty please. If not, can you tell me which view you're using and I'll update that in the DB. 

CASE WHEN test = 1 then 'TEST' else b.species_name END as speciesName,

**Comment by StuMackenzie** [comment]
That’ll do. Thanks!

____________________

**Comment by leberrigan** [comment]
https://github.com/MotusDev/Motus-TO-DO/issues/792

**Comment by jsayers-bsc** [comment]
Excellent
