### ISSUE TITLE
Adding Attachment to tags_deployments

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#857]
I've created a new table (Denis will be thrilled ;-) called lk_attachment and added a new column to tags_deployments called attachment  with a fk to lk_attachment. 

I've added attachment to:
vwBase_API_tag_deployments_template, 
api_import_tag_deployments, 
bt_tags_deployments, 
bt_api_import_tag_deployments, 
tr_tags_deployments, 
vwBase_api_tags_deployments, 
vwBase_tags_deployments, 
vwBase_tags_deployments_basic, 
api_tag_deployments, 
bt_api_tag_deployments

I've added a check to prAPIValidateTagDeploy to validate the attachment column for bulk uploads. 

I'm not going to add this to the R package just yet. But otherwise I hopefully should have found everywhere relevant (it's never "just" adding a field is it? Silly Motus) 

Over to @pmorrill to add the new field (as a drop down lookup to lk_attachment) to the tag_deployment metadata page.

**Comment by StuMackenzie** [comment]
Beauty - @ajmacdonald3 when this is function can you test with your Dunlin tags. Next step would be to contact all the shorebird projects asking them if they used any attachment methods other than glue to let us know and then we make all their attachment types glue-on. Some exceptions will be Hudwits...I'm not sure if anything else would have had a harness - some sanderling, maybe knots? Anyway, we should discuss how to deal with this. I would like to identify all glued on tags asap - the longer we leave it the harder it'll be to populate.

**Comment by StuMackenzie** [comment]
Lifespan. Next step may be to decide whether we should assign shortened lifespans to glued tags. this may make sense for Solar tags, not necessarily batteries. I’m not sure how much this really matter at this point but it will open up a lot of potential codes and probably reduce falsen positives.

**Comment by ajmacdonald3** [comment]
Will do! I think some Sanderling from the Cornell project had harnesses... not sure about any other shorebird projects using harnesses.

**Comment by leberrigan** [comment]
I'm not very experienced with shorebirds, but Christy Morrissey told me there are big differences in retention time for the different glue-on methods that researchers currently use. Lasting up to a year, she uses JB weld epoxy and trimmed the feathers before applying, ensuring there was a good bond with the skin. I think there can be a lot of variation based on: glue type; temperature; bonding to skin v. feather. 

Do we care enough to separate out various glue-on methods?

**Comment by StuMackenzie** [comment]
I don’t think we can get into that - all those nuances are best documents and discussed in methods documents.

In my opinion, if there isn’t skin contact, there isn’t much point.

S

____________________

**Comment by pmorrill** [comment]
I have added support for this field, to the sandbox only (I don't think we are ready for the beta server yet?? Catherine?)

**Comment by cjardine-bsc** [comment]
Live database should be updated to accommodate this. Can be deployed to beta and tested.

**Comment by pmorrill** [comment]
Added to beta9: will be avail. on next deploy to beta server.

**Comment by ajmacdonald3** [comment]
I've been trying this out on beta and I see the tag attachment field on both the webpage and in the bulk upload CSV. Awesome! If I populate the field with the dropdown on the webpage it works great, and is present if I download the bulk upload CSV after that. If I populate all entries at once in the CSV and then upload it, the field doesn't populate on the webpage and has gone back to blank in the CSV if I re-download it. I'm guessing this isn't the intention?

**Comment by cjardine-bsc** [comment]
Ha, indeed no. Making something that doesn't work was not my plan! 

Thanks for testing. I missed one proc. I've updated that. Go ahead and give it another go. Should be good in beta.

**Comment by ajmacdonald3** [comment]
Tested it again - looks good on beta! Bulk upload with the CSV worked and the field is populated on the webpage and in the CSV if re-downloaded.

**Comment by StuMackenzie** [comment]
Just needs a push to live? Then we can close this puppy?

**Comment by ajmacdonald3** [comment]
All shorebird deployments have been updated to glue attachments and collaborators have been notified.

**Comment by StuMackenzie** [comment]
Cool - was going to close, but our next step should be to specify different types of harnesses. leg-loop, neck-loop, other... This requires more thought and consultation.

**Comment by leberrigan** [comment]
It's been done - closing
