### ISSUE TITLE
'tagme' breaks with latest version of R?

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#858]
I have yet to test this myself, but it appears that the 'tagme' function throws the following error when updating a database after updating the R to version 4.0.3:

> Error in UseMethod("db_has_table") : 
>   no applicable method for 'db_has_table' applied to an object of class "c('SQLiteConnection', 'DBIConnection', 'DBIObject')"
>

**Comment by steffilazerte** [comment]
Hmm, not sure why this occurred, but there were a bunch of db_ functions from the dplyr/dbplyr packages that don't like the sqlite database format. I've transferred everything to DBI (which is probably the best to use anyway).

Check out the hotfix to see if this helps

```
remotes::install_github("MotusWTS/motus", ref = "hotfix")
```

I'll push to master as soon as I get confirmation.

**Comment by leberrigan** [comment]
I'm in the field, but I asked a collaborator to install this and it fixed her issue so I think you did it!

**Comment by jsayers-bsc** [comment]
There have been a few other people recently that have reported this error as well. Is the currently currently only present in ref="hotfix" and not ref='beta4"?

**Comment by steffilazerte** [comment]
Sorry, I was waiting for any other testers and then forgot 🤦🏼 It's merged into master now!
