### ISSUE TITLE
'tagme' fails when downloading data from 'SG-2016BBBK1E5A' only

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#861]
When trying to download data from receiver 'SG-2016BBBK1E5A' I get an error a 'server not responding' error, but I can download data from any other station.

```
tagme(projRecv = 'SG-2016BBBK1E5A', new = F, update = T, forceMeta = T)
The server did not respond within 120s. Trying again...
 Error: The server is not responding, please try again later. 

tagme(projRecv = 'SG-1913BBBK3258 ', new = F, update = T, forceMeta = T)
Checking for new data for receiver SG-1913BBBK3258 (deviceID: 598)
Receiver SG-1913BBBK3258:  got   159 batch records
batchID   919279 (#     1 of    159): got     79 pulse counts    
...

tagme(projRecv = 'SG-2016BBBK1E5A', new = F, update = T, forceMeta = T)
The server did not respond within 120s. Trying again...
 Error: The server is not responding, please try again later. 
```

**Comment by jsayers-bsc** [comment]
Odd, it's working fine for me here...

**Comment by steffilazerte** [comment]
This has to be a server issue, I can't think how it can be an R package problem... @denislepage?

**Comment by leberrigan** [comment]
I will try again when I get home. Sounds like it might be a 'local' problem

**Comment by denislepage** [comment]
Kwic was having some connectivity issues over the past weekend, so our servers were not reachable. I'll close until there's something else coming up.
