### ISSUE TITLE
What determines Batch length?

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#862]
Batches can have varying length, number of hits, pulses, etc. It's not clear to me how Batch size is determined so hopefully someone can clarify that and related questions.

- What determines Batch length/size? 
- Batch length is presumably determined in the same way during re-runs?
- Should there always be a one-to-one relationship between batches and deprecated batches?
- How might (or not) uploading data chunks of various sizes affect Batch length and when when those batches begin? For instance, some batches are very long (multiple days). If a portion of the data that began in the middle of a long batch was re-uploaded, what effect would have have on detections either at the time or during a re-run?
- in the R data tsStart and tsEnd are obvious enough.

**Comment by denislepage** [comment]
This is pretty well documented here: https://github.com/MotusWTS/motusServer/blob/master/inst/doc/motus_data_overview.md

Batches are related to processing.

The longest period a batch can last is the interval between reboots of the sensorgnome.

File uploads (including for connected receivers) are generally treated as their own distinct batches, which may get cut in parts if a reboot happened in the middle of the data period.

Re-runs will typically create longer batches, and will merge together all data available within a boot number on a receiver.

Runs, can in theory overlap several batches. This feature has added a lot of complication in the processing, which I am not sure were warranted, but hits with the same runID can occur in multiple batches. We are not allowing this with CTT tags.

**Comment by jsayers-bsc** [comment]
That's a great resource. I had not seen that. I may have some further questions later to clarify but for now I'll close this one.
