### ISSUE TITLE
Tags in raw data, but not in Motus data

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#863]
This is sort of a follow-up from #799, but I'm not sure if it's the same issue as the last time seemed to be related to and resolved by the default frequency. 

Though this is actually one of the same receivers that had its [default frequency set as 166 MHz.](https://github.com/MotusDev/Motus-TO-DO/issues/784#issuecomment-710692205). 

For a period of a several days in the last couple weeks none of the tags detected locally (and seen in the receiver data using the [local tagfinder](https://github.com/jbrzusto/find_tags) were seen in the data from Motus, either on the website or downloaded in R. 

Below is an example from what Bart sent from the local data:

> Something is really wrong, for instance look at TAG54, in the excel file.
> You will see it fly from SG-D22CRPI39DC5 appearing at SG-50D6RPI38864 until approx. 15:41, after that it leaves in the direction of  SG-32A1RPI36156 where it is detected up until 15:57
> 

![image](https://user-images.githubusercontent.com/55001144/99472608-f9afcf00-2916-11eb-8394-7e966b36f831.png)

But this particular [tag ](https://motus.org/data/tag?id=49362)does not show up at all in the data on the [Motus site](https://motus.org/data/tag/deployment/detections/timeline?year=2020&id=30766) or in the R package for this receiver. 

```
> sql <- tagme('SG-D22CRPI39DC5', update = T, new = F, forceMeta = T, dir = 'D:/MotusData')
Checking for new data for receiver SG-D22CRPI39DC5 (deviceID: 1946)
activity:     2 new batch records to check
batchID  1484300 (#     1 of      2): got      7 activity records
batchID  1484300 (#     1 of      2): got      0 activity records
batchID  1484379 (#     2 of      2): got      0 activity records
Downloaded 7 activity records
nodeData:     0 new batch records to check
> alltags <- tbl(sql, 'alltags') %>% collect() %>% as.data.frame()
> tag54 <- alltags %>% filter(motusTagID == 49362)
> nrow(tag54)
[1] 0
```

There are other tags as well that they feel are mysteriously missing from Motus data, though they can see them in the raw data, and which they expect to be in proximity of the station and detected.

**Comment by Hussell** [comment]
SG-D22CRPI39DC5 has been rerun, and detections of WUR#54:7.3 M.49362 were found.

**Comment by jsayers-bsc** [comment]
Great.

Curious why they didn't show up during any of the data processed during that period though, and not until the receiver was rerun. There should have been jobs in the few hours prior to rerunning and presumably the metadata was present and up to date.
