### ISSUE TITLE
Delay "Processing Complete" email

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#864]
I'm not sure this is worth doing but it's worth discussing anyway. Particularly for those of us who do a lot of station management...

There is a lag between the time the "Processing Complete" email comes in and when the new data actually becomes visible in the links. The email says it tends to be 20 minutes and rarely an hour, but I find it tends toward the longer end. The tendency is to see the email, figure enough time has passed, and then click the link only to find that no new data is there. It's actually not clear at a glance whether there is no data (station wasn't functioning during the period) or whether data simply hasn't percolated through all the various levels (which is usually the case). It can be confusing or simply distracting to receive email notifications that can't even be acted on at the moment.

What about just delaying the "Processing Complete" email until at least 1-2 hours have passed -- to be almost certain that when the email is received, all data are available?

Is that a simple thing to do? Would it help? Personally I think it would -- why get an email if there's nothing you can even do about it until an hour later -- but what do others think? @leberrigan @StuMackenzie @ajmacdonald3

**Comment by leberrigan** [comment]
I think it might be easier to just change the messaging in the email to say "2 hours or more if there is a lot of other processing going on".

**Comment by jsayers-bsc** [comment]
> I think it might be easier to just change the messaging in the email to say "2 hours or more if there is a lot of other processing going on".

Yes that's true it's certainly simpler. Though it still involves sending an email at a point when we can be pretty certain that none of the links in the email will include the new data. If the email notification itself is delayed until a couple hours after the processing has been completed all recent data will be in the plots etc.

**Comment by Hussell** [comment]
I've updated the message to say "Typical delays are ~20 minutes, but can be several hours (or more) if a lot of other processing is going on.", but I think that's probably not enough.
