### ISSUE TITLE
Motus Metadata Cleanup

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#869]
### **Projects
- [ ] Project descriptions are actually descriptive and make sense. **And bilingual**? Bilngual is up to the PI. 
- [ ] Project short descriptions exist and sensible.
- [ ] Empty projects are deleted or reassigned
- [ ] populate acronyms

### Users
- [ ] Names are real (person or institution)

### **Admin Responsibility
- [ ] Proper affiliation marked for admin

### Tag registrations
- [ ] Tag models match expected values for registration dates.
- [ ] Tag ID match expected value (i.e.; not '9999999').

### **Tag deployments
- [ ] Frequency matches tagging location.
- [ ] All non-test deployments have an accurate species.
- [ ] Tagging location exists and is accurate (i.e.; within range of species and on land).
- [ ] Test deployments are all flagged.
- [ ] Check comments for additional metadata.
  - Enter data in the appropriate column or add columns to the table.
- [ ] Marker number and band number are accurate:
  - Replace marker number with markerType set to 'metal band' with band number. see https://github.com/MotusDev/Motus-TO-DO/issues/852
- [ ] Attachment type is compiled for all tags - harness or glue

### Receiver registrations
- [ ] Data exist for old registrations (remove registrations with no data older than 3 yrs?).

### Receiver sites
- [ ] No unique sites overlap.
  - Lump together duplicated sites
- [ ] **Site names are easy to interpret?**
  - Not sure if we should be changing things, but we should consider this. For instance, _"UQO"_ should probably be _"Université du Québec en Outaouais"_.
- [ ] **Address ambiguous site names?**
  - Again, not sure when or if we should prioritize this, but we might want think about ambiguous names. For instance, 'Cape' or 'Forest' might be too vague.

### Receiver deployments
- [ ] Deployment location exists and is accurate (on land, unless defined as marine).
  - Do GPS hits match deployment location?
- [ ] Mounting structure is accurate:
  - Does it change over time?
- [ ] Check comments for additional metadata

### Antenna deployments
 - [ ] Antenna frequencies make sense for location.
 - [ ] Antenna directions are accurate:
   - Do they change in a clockwise/anticlockwise direction?
     - Like;y an accurate direction; shift probably due to accumulated change over time.
   - Do they change in alternating directions?
     - Could be inaccurate direction if measurements are taken in an inconsistent manner (sometimes too close to the tripod or switching between magnetic and true bearings), but could also be shifting due to wind and then fixed at a later date.
   - Are directions swapped between ports?
     - Likely human error, but sometimes done on purpose. If relative height also changes it is more likely a mistake.
 - [ ] Port numbers are accurate:
   - Do antenna directions swap between ports?
   - Do antenna heights relative to one another change over time ?
 - [ ] Antenna type is accurate:
   - Does it change over time?
   - Is it an unusual type? (i.e.; 'J-pole' and 'mast radiator' are often just mislabeled Omnis)

**Comment by cjardine-bsc** [comment]
Keep me in the loop if there are additional checks you'd like to see added to the data validation centre.

**Comment by StuMackenzie** [comment]
Moved to Slack - https://motuswts.slack.com/archives/C01K0NCJ29E/p1611503233001300
