### ISSUE TITLE
Replay option on map animations

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#87]
When the track animation is completed and the timeline is at the end, pressing the right arrow (play forward) should reset the timeline to zero and allow starting again.

Otherwise, one has to drag the timeline manually to restart.

The same behaviour could work in backward animations for consistency.

https://motus.org/data/track?tagDeploymentId=8617

**Comment by Hussell** [comment]
https://beta.motus.org/data/track?tagDeploymentId=8617
