### ISSUE TITLE
Sites - drop'em like they're hot.

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#876]
Most of yesterday's call, I tried to justify to myself the need for sites and couldn't come up with any. Kept me up all night :)

So here's your chance. The way I see it, we need a really good reason. A few exceptions or special cases doesn't really cut it in my mind.

We're building the capacity to lump stations spatially through different filters. Managing landowners and junk like that can still happen on a station level.

**Comment by cjardine-bsc** [comment]
Psssst Oh that's hot!

Sites removed from sandbox.
