### ISSUE TITLE
Project 280 - Failed Tag Registrations and Data Review

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#877]
The following tag registrations failed:

> 
> Query to motus server to register tag 35:25.1 failed
> with this error: registration-failed: Tag registration failed - tag-exists
> Query to motus server to register tag 36:25.1 failed
> with this error: registration-failed: Tag registration failed - tag-exists

The collaborator also claims they received this error for tag 37, but I can only find the following:

>Unable to get a good estimate of burst interval for tag id 37 in file tag037.wav
> Please re-record this tag and re-upload

The only other registrations for tags 35, 36, and 37 are from 2016 and 2018 so we shouldn't be getting this error.

I will get in touch with the collaborator about tag 37. For now, can @Hussell look into why this issue came up? Or is there something you need from me?

**Comment by Hussell** [comment]
I'm not seeing any uploads for project 280 since Nov. 14th, and no tag recording uploads for a long time before that. I'm also not finding any tag registration uploads for any project at all this week. Can you get me a date, job ID, user ID, or something else I can use to figure track this down?

**Comment by cjardine-bsc** [comment]
tag_ids:

48292
48293
48294

Registered to project 280.

**Comment by Hussell** [comment]
Those were registered on August 30th, job ID 4361573. Looking through the same user's uploads, I found the error messages quoted above during a few uploads the following week (Aug 31st - Sept 6th) while she fixed a lot of other issues. See jobs 4368961, 4383682, 4387234. They're tags of a different model (NTQB-2-3-2 vs NTQB-2-4-2) and different period (25.1 vs 11.3), so I'm not sure that's the conflict.

**Comment by StuMackenzie** [comment]
resolved?

**Comment by Hussell** [comment]
It isn't clear to me what happened here.

**Comment by StuMackenzie** [comment]
@leberrigan  any thoughts? 

Re. Data Review. This project did not receive many, if any, spring detections from birds deployed. Do you mind taking a look and seeing if anything looks funny. I suspect it may be a tag issue - either falling off or failing? I do wonder if it's a data issue though. 

We may have discussed this before, or in another issue, but I can't find it.

**Comment by StuMackenzie** [comment]
The crux of this data issue is that they had 64/119 birds detected during fall migration, but only 3/119 were detected during the returning spring migration. It could be a number of issues, but it's important for us to rule out something on our end.

It's difficult to assess which stations should be looked into, or potentially re-run to ensure it's not a data error, but it might not be a bad idea to re-run their 14 receivers to see if it makes a difference? Then, look elsewhere if need be.  Thoughts @Hussell
