### ISSUE TITLE
Remove or fix antenna beams for receivers map

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#880]
We think we should delete the beams entirely if it's too complicated or time consuming to fix (fixing will take > 1 wk.); or fix the issue by loading antennas _only_ when selecting 'view antenna beams'.

---

I have figured out where the code is slowing down page load times. In 'receiversMap.js', lines 215:282 there is a foreach loop that goes through each receiver deployment in the database and adds a marker to the map, setting the visibility according to the date selected on the slider and resolution selected in the dropdown menu. This code also loops through each antenna for each deployment and adds a polygon to the map. Loading this data is not important for the home page which can only display currently active receivers and no polygons. It should also be possible to add markers as they are needed instead of all at once.

Since this is JS, we're going to see variable load times according to the device and browser used. On cell phones it can be especially slow which is very annoying when trying to look up information while in the field.

**Comment by StuMackenzie** [comment]
Much faster - THANKS. Looks like we can close.
