### ISSUE TITLE
sgdata.motus.org unreachable

### ISSUE THREAD

**Issue by Hussell** [MotusDev/Motus-TO-DO#881]
sgdata.motus.org has been unreachable since sometime last night, both over the web and by SSH. I'm not sure it has completely crashed, because instead of 404 or some other error, I'm getting connection timeouts.

**Comment by Hussell** [comment]
This may have something to do with a rerun of receiver SG-5304RPI3AAED which was running overnight. This was a retry of a rerun I attempted last week, which halted due to database lock errors. I thought I'd figured out the cause of those, but I may have missed something.

**Comment by denislepage** [comment]
I have no clue.

One thought, but I doubt this is related to the changes we made to the config files as the server was restarted a couple times at least since, and it has presumably restarted after the recent reboot.

Apache presumably has a log file that we can look at.

**Comment by leberrigan** [comment]
I still can't connect to sgdata. Was this issue fixed yesterday or is this ongoing?

**Comment by Hussell** [comment]
Ongoing.

**Comment by Hussell** [comment]
The server is back online and everything is running. The root cause is being investigated.

**Comment by StuMackenzie** [comment]
phew.
