### ISSUE TITLE
No tag deployments present in .motus file and all fullIDs are ?proj?-0#:0.0

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#883]
I recently downloaded the receiver .motus file for [CTT-5031194D3168 ](https://motus.org/data/receiverDeployment?id=6115). There have been quite a few detections at this receiver, including some local birds that were detected basically every day.

But though the alltags view contains nearly 4 million records, there is only one fullID present: `?proj?-0#:0.0`. Similarly, the tagDeps table is empty.

I've noticed this multiple times lately. I downloaded data within the last week or two for Toronto Zoo, Ruthven, and Crysler Park Marina in Ontario. For each of these, many tag deployments were visible in the tag detections in the online summary/ plots. But when I downloaded them, only ?proj?-0#:0.0 was present. More recently when I downloaded again, all the proper fullID's were present. The opposite thing happened with #879: the first download contained all the proper fullID's, but the later download had only ?proj?-0#:0.0.

**Comment by cjardine-bsc** [comment]
Hey Josh, I don't work in the R SQLite files often, I'm guessing FullID is from the alltags view? What is the MotusTagID for the records?

I'm wondering if the problem is with the deployment metadata.

**Comment by jsayers-bsc** [comment]
Closed in deference to #879 as this seems to be the same issue
