### ISSUE TITLE
CTT Receiver R Package Download issue

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#885]
I didn't mean to accept this one publicly so that it went to the list. We should probably followup.

Stu

Hi everyone,

I cannot upload one of my CTT receivers in R and I am running out of options to access data using Motus R Book.

After following your typical Motus R Book guidelines to upload packages and setting your directory, I encounter an issue when running:

>proj.num <- "CTT-5031194D3168" # IndianRidge3-MPG-MT
>sql.motus <- tagme(proj.num, new = F, forceMeta = TRUE,  update=TRUE)

What happens is that the very first batch ID (e.g. #1 of 1979) seems to run forever and never goes to the next batch ID (e.g., #2 of 1979).

Any idea on the cause of this issue? 

Josh at Motus HQ had issues with this receiver a while back when trying to help me but it now works for him. I wonder if it is a computer compatibility problem as I am a Mac user (MacOS Catalina - Version 10.15.7).
I would appreciate any advice on this. I could try changing laptops to troubleshoot but ultimately want/need to use this particular laptop for future operations.

The same issue happens if I run the code without forcing metadata or forcing an update, or after deleting my receiver files and starting from scratch, or after uninstalling and then re-installing all my R packages.

Thanks for any feedback,

William Blake
IWC Motus Project #213 & #226

**Comment by jsayers-bsc** [comment]
This has been an odd receiver, over and above the other recent issues downloading data from CTT receivers (see #813). 

But since the updates to the R package (and downloading a new local database) I haven't had any issues with it. William has done all of that as well — updated packages, new local database, and keeps running into issues. 

The previous issue isn't necessarily the same as the issue he's reporting now, though, where the same batch segment was repeated over and over while downloading.

He reported this a few weeks ago  (for a different receiver: "SG-6F3BRPI3EA63"):

> proj.num1 <- "SG-6F3BRPI3EA63" # Indian Ridge  (twice)
> src1 <- tagme(proj.num1, new=T, update=T, forceMeta =T)
> newview <- "CREATE VIEW alltags_fast as SELECT t1.hitID as hitID, t1.runID as runID, t1.batchID as batchID, t1.ts as ts, CASE WHEN t6.utcOffset is null then t1.ts else t1.ts - t6.utcOffset * 60 * 60 end as tsCorrected, t1.sig as sig, t1.sigSD as sigsd, t1.noise as noise, t1.freq as freq, t1.freqSD as freqsd, t1.slop as slop, t1.burstSlop as burstSlop, t2.done as done, CASE WHEN t12.motusTagID is null then t2.motusTagID else t12.motusTagID end as motusTagID, t12.ambigID as ambigID, t2.ant as port, t2.len as runLen, t3.monoBN as bootnum, t4.projectID as tagProjID, t4.mfgID as mfgID, t4.type as tagType, t4.codeSet as codeSet, t4.manufacturer as mfg, t4.model as tagModel, t4.lifeSpan as tagLifespan, t4.nomFreq as nomFreq, t4.bi as tagBI, t4.pulseLen as pulseLen, t5.deployID as tagDeployID, t5.speciesID as speciesID, t5.markerNumber as markerNumber, t5.markerType as markerType, t5.tsStart as tagDeployStart, t5.tsEnd as tagDeployEnd, t5.latitude as tagDepLat, t5.longitude as tagDepLon, t5.elevation as tagDepAlt, t5.comments as tagDepComments, ifnull(t5.fullID, printf('?proj?-%d#%s:%.1f', t5.projectID, t4.mfgID, t4.bi)) as fullID, t3.motusDeviceID as deviceID, t6.deployID as recvDeployID, t6.latitude as recvDeployLat, t6.longitude as recvDeployLon, t6.elevation as recvDeployAlt, t6a.serno as recv, t6.name as recvDeployName, t6.siteName as recvSiteName, t6.isMobile as isRecvMobile, t6.projectID as recvProjID, t6.utcOffset as recvUtcOffset, t7.antennaType as antType, t7.bearing as antBearing, t7.heightMeters as antHeight, t8.english as speciesEN, t8.french as speciesFR, t8.scientific as speciesSci, t8.`group` as speciesGroup, t9.label as tagProjName, t10.label as recvProjName, NULL as gpsLat, NULL as gpsLon, NULL as gpsAlt FROM hits AS t1 LEFT JOIN runs AS t2 ON t1.runID = t2.runID left join allambigs t12 on t2.motusTagID = t12.ambigID LEFT JOIN batches AS t3 ON t3.batchID = t1.batchID LEFT JOIN tags AS t4 ON t4.tagID = CASE WHEN t12.motusTagID is null then t2.motusTagID else t12.motusTagID end LEFT JOIN tagDeps AS t5 ON t5.tagID = CASE WHEN t12.motusTagID is null then t2.motusTagID else t12.motusTagID end      AND t5.tsStart = (SELECT max(t5b.tsStart) FROM tagDeps AS t5b WHERE t5b.tagID = CASE WHEN t12.motusTagID is null then t2.motusTagID else t12.motusTagID end        AND t5b.tsStart <= t1.ts AND (t5b.tsEnd IS NULL OR t5b.tsEnd >= t1.ts) ) LEFT JOIN recvs as t6a on t6a.deviceID = t3.motusDeviceID LEFT JOIN recvDeps AS t6 ON t6.deviceID = t3.motusDeviceID AND t6.tsStart = (SELECT max(t6b.tsStart) FROM recvDeps AS t6b WHERE t6b.deviceID = t3.motusDeviceID          AND t6b.tsStart <= t1.ts AND (t6b.tsEnd IS NULL OR t6b.tsEnd >= t1.ts) ) LEFT JOIN antDeps AS t7 ON t7.deployID = t6.deployID AND t7.port = t2.ant LEFT JOIN species AS t8 ON t8.id = t5.speciesID LEFT JOIN projs AS t9 ON t9.ID = t5.projectID LEFT JOIN projs AS t10 ON t10.ID = t6.projectID"
> DBI::dbSendQuery(src1$con, newview)
> tbl.alltags1 <- tbl(src1, "alltags_fast") # virtual table
> df.alltags1 <- tbl.alltags1 %>%
>   collect() %>%
>   as.data.frame() %>%     # for all fields in the df (data frame)
>   mutate(ts = as_datetime(ts, tz = "UTC", origin = "1970-01-01”)
>  
> I save all the separate “df.alltags” (e.g. 1, 2, n) until I join all of them in a common dataset. 
>  
> Unfortunately many of the CTT sensorstations seem to be too slow to upload to my computer and internet connection.  Too much data perhaps? When I run the tagme() function for the first time, many tagme queries go through thousand of lines that look like this:
> Example: 
> ….
> batchID  1235774 (#     3 of   1435): got      1 GPS fixes                     
> batchID  1235774 (#     3 of   1435): got      1 GPS fixes 
> batchID  1235774 (#     3 of   1435): got      1 GPS fixes                     
> batchID  1235774 (#     3 of   1435): got      1 GPS fixes                                         
> …
> ETC…
> to infinity until memory runs out or my internet disconnects at some point overnight.
> 

In that email thread Denis suggested that maybe it "Sounds like an API paging issue for Paul to look into first and connect with Steffi if necessary"

Someone else reported a similar issue around the same time:

> I am trying to download tag detections from a single tower (Derby Hill). This would be my first time downloading the database.  When I use the tagme() function to start the download, I get the following message that repeats over and over again:
> 
> batchID  1236020 (#     1 of    684): got      1 GPS fixes  
> 
> This message repeated for 24+hrs before it gave me the following error message:                   
> The server did not respond within 120s. Trying again...
> Error: The server is not responding, please try again later.
> 
> The receiver number is:  CTT-E7BE27B8582A 

I haven't personally seen this particular issue at all in the last several weeks, and I think even the second example has found it was resolved after updating the R package and downloading a new local database. Off the top of my head I can't think of anyone else who has reported it. In the meantime I've sent William a copy of the .motus file for this receiver I just downloaded so that he has something to work with.

**Comment by cjardine-bsc** [comment]
Tagging @pmorrill to look into whether this is an API problem.

**Comment by StuMackenzie** [comment]
These issues still persist:

Recent update/note:
It’s the same exact issue of not being able to upload data from my CTT receivers. I’ve outlined it in past emails and in the google group but happy to do some email mining and send you those again if you need. I thought maybe it was one CTT receiver that wasn’t working, but several seem to not work for me anymore. They just stick on the #1 of many batches to upload, and that message: “batch #1 of xxx” goes on and on, to infinity, until I just have to stop or exit out of RStudio.

David La Puma was wondering if it was my computer so I used a different Mac this morning, and just confirmed I am experiencing the same issue. People on the google group have been mentioning various similar frustrations with uploading data from the Motus server, but all seem to have found a work-around their upload issues, and none of their suggestions have helped me (new directory, specifying directories, etc.).

I’m also thinking it could be the whole MPG admin security levels, or wifi firewalls, but that doesn’t make much sense to me because I can definitely upload all Sensorgnomes, and I think that some of the CTT receivers also update (haven’t tried other CTT receivers since december).

Recently Denis LePage commented on directory admin level being a potential issue (“read-only” folder), but again I don’t think this would be an issue if some of the receivers upload and some don’t.

Let me know if you need more info. I uploaded my code in GitHub:https://github.com/frenchwill23/motus-R-data

**Comment by pmorrill** [comment]
This is not clear to me, either what is happening or why it would be an API issue. This is apparently a sporadic issue at best: some people see it and others do not. Some machines exhibit it and others do not. And Josh references previous issues that might not be related. The R-ecosystem is further complicated by recent versions floating around that point at sandbox or beta, and by the fact that some may not be updating.

Ideally, Steffi would reproduce this issue first, then tell me if something (specific) in the API is not working. Then I'd be able to do more than guess. I don't see Steffi's account on the assignee's list though.

**Comment by steffilazerte** [comment]
I'll look into this and let you know what I find

**Comment by steffilazerte** [comment]
Okay, I maybe found the problem relating to the question outlined in the first comment (batch downloads forever), but I have no idea what's going on, I think it's something a bit funky on the server. Possibly a problem with the ts values (they should be integers, right?). @denislepage, @pmorrill, any ideas?

---

**API Entry point:** "custom/gps_for_receiver"

**Receiver:** CTT-5031194D3168**

### Good Batch (no problems)

Batch ID 1235830, page ts starting at 0, get four gps points
```
> srvGPSForReceiver(batchID = 1235830, ts = 0)
     gpsID recvDeployID         ts      gpsts batchID      lat      lon    alt quality lat_mean lon_mean n_fixes
1 29306294         6115 1596362938 1596362938 1235830 46.69295 -114.035 1098.3       3 46.69294 -114.035      50
2 29306295         6115 1596363839 1596363838 1235830 46.69295 -114.035 1096.8       3 46.69294 -114.035      50
3 29306296         6115 1596364739 1596364738 1235830 46.69299 -114.035 1100.5       3 46.69300 -114.035      50
4 29306297         6115 1596365639 1596365638 1235830 46.69296 -114.035 1099.8       3 46.69297 -114.035      50
```

So now we set `ts = max(ts)` and page the same batch with the last ts above
```
> srvGPSForReceiver(batchID = 1235830, ts = 1596365639)
 [1] gpsID        recvDeployID ts           gpsts        batchID      lat          lon          alt          quality     
[10] lat_mean     lon_mean     n_fixes     
<0 rows> (or 0-length row.names)
```
And we get zero returns, no problem

### Bad batch (infinite loop)

Batch ID 1235831, page ts starting at 0, get four gps points (so far so good)
```
> srvGPSForReceiver(batchID = 1235831, ts = 0)
     gpsID recvDeployID         ts      gpsts batchID      lat       lon    alt quality lat_mean  lon_mean n_fixes
1 29306298         6115 1596366540 1596366539 1235831 46.69297 -114.0350 1100.9       3 46.69297 -114.0350      50
2 29306299         6115 1596367440 1596367439 1235831 46.69294 -114.0351 1096.7       3 46.69294 -114.0351      50
3 29306300         6115 1596368340 1596368339 1235831 46.69293 -114.0351 1099.4       3 46.69293 -114.0351      50
4 29306301         6115 1596369241 1596369240 1235831 46.69293 -114.0351 1099.1       3 46.69293 -114.0351      50
```
So now we set `ts = max(ts)` and page the same batch with the last ts above
```
> srvGPSForReceiver(batchID = 1235831, ts = 1596369241)
     gpsID recvDeployID         ts      gpsts batchID      lat       lon    alt quality lat_mean  lon_mean n_fixes
1 29306301         6115 1596369241 1596369240 1235831 46.69293 -114.0351 1099.1       3 46.69293 -114.0351      50
```

But we get the same last GPS point again. Now the code takes the last ts, and tries again, making an infinite loop...
```
> srvGPSForReceiver(batchID = 1235831, ts = 1596369241)
     gpsID recvDeployID         ts      gpsts batchID      lat       lon    alt quality lat_mean  lon_mean n_fixes
1 29306301         6115 1596369241 1596369240 1235831 46.69293 -114.0351 1099.1       3 46.69293 -114.0351      50
```

**Comment by denislepage** [comment]
ts fields are almost always double float, at least in the database. I’m not 100% sure how the API handles those incoming parameters though. Improper rounding could potentially cause this sort of behaviour.

Could you send the parameters that are causing the infinite loop (batchID and ts, or whatever else is being sent and returned)?

**Comment by denislepage** [comment]
Disregard my request for details. I see they were in the earlier post.

**Comment by denislepage** [comment]
This indeed seems to have to do with float precision, which can be a bit hazardous at times. I thought we had a gpsID now, so I’m surprised that we’re still trying to page on the ts value.


1.       this returns no results (wrong in appearance).

select * from det_gps where batchID = 1235831 and ts = 1596369241


2.       This returns a single row (also wrong, which is what is happening in the infinite loop):

select * from det_gps where batchID = 1235831 and ts > 1596369241

gpsID batchID     ts    gpsts lat   lon   alt   quality     lat_mean    lon_mean    n_fixes
29306301    1235831     1596369241  1596369240  46.692933   -114.035067 1099.1      3      46.692928   -114.035068 50


3.       This is the correction needed. It provides no rows.

select * from det_gps where batchID = 1235831 and convert(bigint, ts) > 1596369241


4.       This demonstrate the impact of converting to integer vs. option #1 above. Now trying an equal condition works.

select * from det_gps where batchID = 1235831 and convert(bigint, ts) = 1596369241

gpsID batchID     ts    gpsts lat   lon   alt   quality     lat_mean    lon_mean    n_fixes
29306301    1235831     1596369241  1596369240  46.692933   -114.035067 1099.1      3      46.692928   -114.035068 50

That means that everywhere we rely on a float field for paging, we should convert them to bigint. I also think that the paging request should continue to use an integer value, but we have to be careful again there.

See this interesting experiment:

select convert(bigint, convert(float, 1596369240.9999))

1596369240

select convert(bigint, convert(float, 1596369240.999999999))

1596369241

The quickest fix should be to switch to paging based on gpsID, which is an integer.

**Comment by pmorrill** [comment]
Good catch, and yes, we should switch to using gpsID (I thought that we had). Still, there may be other cases where we paginate on time stamp - I will check later today.

**Comment by denislepage** [comment]
We may have to support both ts and gpsID , at least to allow the transition.

**Comment by pmorrill** [comment]
Inspecting the api code, it appears I was right: we already support gpsID as the pagination parameter. Timstamp (ts) is also supported, but clearly problematic as reported above.

@steffilazerte can you test a switch to using gpsID for page calls on each of the following entry points:

/gps_for_receiver

/gps_for_tag_project

As soon as you include gspID on the calls, the query will order by gspID (instead of timestamp) and should paginate based on gpsID. So make sure that even for the first call made when getting new data, you include a gpsID parameter of 0 (forces the correct order by clause).

**Comment by steffilazerte** [comment]
Ah good to know, I wonder if this is something I missed in an earlier iteration.  I'll give it a shot and let you know how it goes. Is this only on beta? Or master too? (i.e. could I submit a hotfix to master branch of the package?)

**Comment by pmorrill** [comment]
This feature should be in all versions of the api, including 'live' (motus.org). Test it against any version.

**Comment by steffilazerte** [comment]
Ugh, we *are* using gpsID in the project download, but *not* the receiver download. I must have missed receivers when I initially made the switch. Sorry for all the problems.

@StuMackenzie, I've made the fix. To test it, install the hotfix-gpsID branch and try downloading the receiver data, it should no longer be stuck at the 5th batch (or restart where ever the problem was, and it should no longer be stuck in a loop):

```
remotes::install_github("MotusWTS/motus", ref = "hotfix-gpsID")
tagme(projRecv = "CTT-5031194D3168", new = TRUE, update = TRUE)
```

Once I get confirmation that a) it solves the problem and b) doesn't create any others :grin: I'll push to master

**Comment by jsayers-bsc** [comment]
I'll pass this along and see if the results are different (and I'll use it on my end in the hopes that no other issues arise!).

**Comment by denislepage** [comment]
The fix is working for me. I was able to download the full database for the receiver. I think we’re good to merge to master.

**Comment by jsayers-bsc** [comment]
I heard back from Project 213 and they have now been able to download data from this receiver (and one other that had a similar issue). 

Does seem strange that so few (if any) other people actually ran into this while downloading data. I downloaded this one anew several times and never ran into this. Well anyway they are happy to be able to download all their data on demand now

**Comment by steffilazerte** [comment]
Pushed to master!
