### ISSUE TITLE
Demands!!!! (Useful Title = Testing of public data access through R) 

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#886]
@leberrigan and @jsayers-bsc  and @ajmacdonald3 Can we please test the following:

1. tagme(1) With an account registered to project 1  (should succeed) 
2. tagme(receiver) for a receiver from project 1 with an account registered to project 1 that has accepted the collab policy (Should succeed) 
3. tagme(1) With an account NOT registered to project 1  that has accepted the collab policy (should succeed) 
4. tagme(78) With an account NOT registered to project 78 that has accepted the collab policy (should fail) 
5. tagme(receiver) for a receiver from project 1 with an account NOT registered to project 1 (Should fail) 
6. tagme(1) with an account registered to project 1 that has NOT accepted the collab policy (Should force you to accept collab policy) 
7. tagme(1) With an account NOT registered to project 1 tagme(1) that NOT has accepted the collab policy (Should force you to accept collab policy)

**Comment by jsayers-bsc** [comment]
> 1. tagme(1) With an account registered to project 1  (should succeed)

Works 

> 2. tagme(receiver) for a receiver from project 1 with an account registered to project 1 that has accepted the collab policy (Should succeed)

Works

> 3. tagme(1) With an account NOT registered to project 1  that has accepted the collab policy (should succeed)

Works

> 4. tagme(78) With an account NOT registered to project 78 that has accepted the collab policy (should fail)

Permission denied

> 5. tagme(receiver) for a receiver from project 1 with an account NOT registered to project 1 (Should fail)

Permission denied

> 6. tagme(1) with an account registered to project 1 that has NOT accepted the collab policy (Should force you to accept collab policy)

Error: Login failed with error message
'Server returned error 'Authentication failed : Authentication token was absent, invalid or expired.''

> 7. tagme(1) With an account NOT registered to project 1 tagme(1) that NOT has accepted the collab policy (Should force you to accept collab policy)

Error: Login failed with error message
'Server returned error 'Authentication failed : Authentication token was absent, invalid or expired.''

**Comment by cjardine-bsc** [comment]
Yay! That is good news. 

I got a bunch of user authentication errors. I forwarded to @pmorrill to take a peak. Thanks!

**Comment by steffilazerte** [comment]
I'm holidays Dec 21st to Jan 5th, so I may not get to this until I'm back. How urgent is it?

**Comment by cjardine-bsc** [comment]
@StuMackenzie would know best, we'll definitely want this working before we update the Collaboration Policy. Thats still probably a few weeks out, though they are actively working on it. 

For now it probably isn't impacting most users since its been so long since we updated the policy.

**Comment by StuMackenzie** [comment]
It can wait until the new year. Thanks.

**Comment by StuMackenzie** [comment]
Related: I logged onto a project and noticed that the Data Sharing options were not pre-populated.

Do we not want 'Share only summary data' to be pre-selected by default.

Also, in description "Open Summary Data (default):"

?

**Comment by denislepage** [comment]
While I think we want to leave the field null in the database until they tell us, I would agree that the web form should have the default selected.

**Comment by cjardine-bsc** [comment]
For new projects yes, for existing projects I'd suggest no.

**Comment by jsayers-bsc** [comment]
Shouldn't the public presentation of a field should always match the value in the database? If people see that "Share only summary data" they are likely to think that the selection has already been made, when in fact it may not be. E.g. #872

**Comment by jsayers-bsc** [comment]
When creating a New Project, the text fragments describing the data sharing options are absent (only visible when viewing an existing project)

**Comment by cjardine-bsc** [comment]
@pmorrill Can you add those text fragments to the new project page please?

Merci!

**Comment by pmorrill** [comment]
Jeremy: can you edit that template - it's one of yours.

**Comment by cjardine-bsc** [comment]
Deployed. Closing.
