### ISSUE TITLE
~3200 undeployed CTT tags in project 0?

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#889]
There are about 3200 undeployed CTT tags residing in project 0, registered in all periods including as early as the new year.

Does anyone recall what's up with this, or how we were going to rectify this?

Was CTT going to make this correction when they 'registered' the tags?

I think there is a loop or two that we haven't closed.

Some of these may be duplicates?

**Comment by cjardine-bsc** [comment]
Yeah, if we get data for a tag from CTT we are registering it to project 0. 

When we get the registration from CTT it should update that registration to the correct project ID. 

I did a little query and there are no duplicates, so I think its working as expected. 

SELECT  count (*), [mfg_id]
FROM [motus].[dbo].[tags]
where manufacturer = 'CTT' 
group by mfg_id
having count(*) > 1 
  
Doesn't look like CTT is registering anything to project 0 

SELECT *
  FROM [api_import_tags]
  where manufacturer = 'CTT' and projectID = 0 

I did send the list of CTT tags registered to project 0 to Bob a while back for him to check to see if any of them were false mfg_ids (from when we were getting unfiltered data from CTT) we should follow up on that when next we chat with him.

**Comment by jsayers-bsc** [comment]
The CTT tags in Project 0 are in the tags table

**Comment by cjardine-bsc** [comment]
That's correct Josh. That's where they should be. 

When CTT registers a tag we've put in project 0, we update the tags table to the correct project.

**Comment by jsayers-bsc** [comment]
I think to answer the original question then, there is no issue with the 3200 CTT tags in Project 0 in the tags table. There are where they are supposed to be (for now). Correct?

**Comment by cjardine-bsc** [comment]
The new ones yes. 

There could be some historic clutter that needs to be addressed though. 

Hence "I did send the list of CTT tags registered to project 0 to Bob a while back for him to check to see if any of them were false mfg_ids (from when we were getting unfiltered data from CTT) we should follow up on that when next we chat with him."

**Comment by denislepage** [comment]
As Catherine says.

CTT tags in project 0 are the result of incoming tag detections for tags that we know nothing else about. We’re assuming that CTT is only sending us filtered data that relates to Motus tags. Some of that likely predates better controls. Assuming CTT registers the tags with us before shipping them, and uses the same source to filter what we see, all should match.

Good to hear that CTT is not attempting to register tags to project 0. Perhaps we should even disable that in the API for extra precaution.

They are not a major problem and can just be ignored, but if the leaks continue, it’d be good to try and repair those faucets. If those tags are showing in some undesirable places, we should try to hide them.

**Comment by StuMackenzie** [comment]
Ah - I forgot about those auto-assignments. Do we really need to keep doing that anymore?

____________________

**Comment by StuMackenzie** [comment]
Also just want to confirm that these aren’t included in our tag count in Motus By The Numbers and other purposes?

____________________

**Comment by cjardine-bsc** [comment]
We only report deployments there, not tags registered. 

Should be all good. 

https://motus.org/data/numbers
