### ISSUE TITLE
Ability to search for sites within receiver map

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#89]
Suggested by a user

Is it possible to make sites searchable within the receivers map, by site name, serial number, deployment, whatever makes sense? 

They suggested a dropdown menu of all active stations at time indicated by the date slider, and then have the map pin or zoom to the selected receiver.  

That dropdown menu would be huge though, so we it might be more reasonable to have a search bar that somehow highlights the site in question without removing all other sites.

Right now this is sort of available if you select a receiver from a project through the projects page, but it only shows the 1 receiver without any others for context, and they'd have to jump from project to project if they were interested in multiple receivers.

**Comment by denislepage** [comment]
Maybe an option to zoom in to a particular receiver through a search box.

IE, the user enters search criteria (name, serial), and they get a list similar to our species search. If they click on the hit, the map zooms in to their site, or highlight it somehow.

Revisiting this from way back, I also think the map should probably be showing inactive locations in a different color (e.g. gray). In this particular case, if someone is looking for a specific receiver, they won’t see it or find it if it doesn’t happen to be active at the date they selected.

I’d put a toggle checkbox that says “Show inactive receiver locations”. The antenna ranges would only be shown for active ones.

Denis
