### ISSUE TITLE
Add Deployment Error

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#891]
Project 35 Receives this error when trying to add deployments to newly deployed tags:

An error has occurred while we were processing your request.
This error has generated an email that has automatically been sent to the technical support staff. We will investigate this problem and will try to resolve as quickly as possible. It is possible that this was only an error caused by a temporary condition, and that you will not get this error again. If that is the case, then whichever operation that failed should succeed if you try it again. If it does not, then you can assume that there is a problem which we will need to resolve from our end.

If you wish to contact us about this error, please provide this reference number: 1610029002479

Contact: DeGroote, Lucas <DegrooteL@CarnegieMNH.org>

**Comment by cjardine-bsc** [comment]
It's a null pointer exception. I'll forward the error to @pmorrill and @Hussell 

Exception:
java.lang.NullPointerException
Stack trace:
File Name	Line Number	Class Name	Method Name	Native Method?
javax.el.ELException: Error reading 'lifespanEndDateStr' on type org.bsc.motus.TagBean

**Comment by pmorrill** [comment]
I have put a fix in for this (beta9 and master branches). We should test in beta, then deploy to live.

The test is: go to any tag in 'Manage your tags' and try to 'add a new deployment'. The error is thrown there. The fix should allow you to add a deployment.

**Comment by cjardine-bsc** [comment]
Deployed to live. Closing.
