### ISSUE TITLE
Manage Stations Interface in Sandbox

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#892]
https://sandbox.motus.org/data/project/stations?projectID=2

 - [ ] Table view shows deployments. Should be a list of stations.
 - [ ] Table view not sortable.
 - [ ] Add search function
 - [ ] Include 'Add landowner' button when adding new station. It's okay if it just links to the new landowner management page.

**Comment by pmorrill** [comment]
Table view is showing stations. I include the latest deployment information where available.

The sort and filter options are next phase once everything is functional.

**Comment by leberrigan** [comment]
**New station form:** I wonder if this could be formatted as a questionnaire of sorts. This could give us control over determining the status as I think that step may be a bit confusing for folks. Above the form would be the concept of a stations (E.g.: "A station is a location where a Motus receiver has been installed, approximated to 500m") and then the questions: 
  a. "What is the name of this location?" (text input)
  b. "Has this station already been installed?" (yes/no)
    - If no, will you be installing one soon? (approx. date/no)
  c. "Where is it located?" (Google maps)
  d. "Who is the landowner?" (select input)

If they answer "no" to question B, the station should be flagged as pending if they answer "yes" to the follow up question and prospective if they answer "no". Once a pending **or** prospective station has a deployment assigned to it, we should ask for the collaborator to verify the location is correct because its very common for the final site to change at the last minute.
 
If they answer "yes" to question B, we can force them to enter a deployment immediately upon creating the station. The station would initially be created with the status of "prospective" which would change to "active" when this initial deployment is entered. In this way, if they fail to complete that initial deployment for whatever reason (tab is closed) the station would remain as "prospective".

As for retiring a station, we could add that as a button on the form when they click on "modify this station" or something like that.
