### ISSUE TITLE
Outstanding Track Search Issues

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#894]
Interesting scenario:

Track Search for deployment 29532 reveals a detection in Colombia. - https://motus.org/data/track?tagDeploymentId=29532

Track Search for the project, or the species does not show the same ? - https://motus.org/data/tracksMap?t=24276&t=24277&t=24278&t=28724&t=28725&t=28726&t=28728&t=28729&t=28737&t=28738&t=28739&t=29517&t=29529&t=29531&t=29532&t=29533&t=29534&t=29535&t=29537&e=2013-01-01&l=2021-12-31&s=7720&p=213

URL too long? Something else I'm missing?

closed 2 issues ;)

**Comment by StuMackenzie** [comment]
Long URL issue and solution discussion here - 

https://github.com/MotusDev/Motus-TO-DO/issues/402

**Comment by StuMackenzie** [comment]
Track Search only returns 1 Kirtland's Warbler despite hundreds in the system. Are these data restricted? https://motus.org/data/tracksSelect?e=2013-01-01&l=2021-12-31&s=16770

**Comment by leberrigan** [comment]
Dashboard resolves this issue
