### ISSUE TITLE
metadata() fails on Project 213

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#897]
Calling `metadata()` on Project 213 fails due to `Error: NOT NULL constraint failed: nodeDeps.tsEnd`

```
library(motus)

m <- tagme(projRecv = 'CTT-5031194D3168', update = T, new = F, forceMeta = T, dir = 'D:/MotusData')

metadata(m, 213)

Loading complete Motus metadata
Project # 213
Error: NOT NULL constraint failed: nodeDeps.tsEnd

```

**Comment by cjardine-bsc** [comment]
@steffilazerte can you please remove the not null constraint on nodeDeps.tsEnd

Thanks!

**Comment by steffilazerte** [comment]
Okay, I'm so sorry for the delay in fixing this. I've created a  "hotfix-nodeDeps" branch which should fix this problem.  You can try it out by installing from this branch, it should automatically update your project when you try to update the data, for example:

```
> tags <- tagme(projRecv = "CTT-5031194D3168", update = TRUE, new = FALSE)
updateMotusDb started (1 version update(s))
 - Drop IS NOT NULL constraint on nodeDeps ts
Checking for new data for receiver CTT-5031194D3168 (deviceID: 1860)
Receiver CTT-5031194D3168:  got     1 batch records
batchID  1941280 (#     1 of      1): got     22 runs starting at      
```

To install: 
```
remotes::install_github("MotusWTS/motus", ref = "hotfix-nodeDeps")
```

Let me know how it goes!

**Comment by jsayers-bsc** [comment]
Actually it sometimes works, but often results in:

> Error: Server returned error 'Failed to build response vectors.'

**Comment by steffilazerte** [comment]
Hmm, at which step does this happen? @denislepage @pmorrill is this a server thing or related to this issue, do you think?

**Comment by jsayers-bsc** [comment]
When I call `metadata()` on each individual project in a loop the error will come up at different points (or not at all) so it would seem server/connection related in some sense.

**Comment by steffilazerte** [comment]
Yeah, I should probably add some metadata checks to the R package too at some point, but I do think it's a server thing... probably?

**Comment by denislepage** [comment]
Sounds likely, given the inconsistent errors. I’d probably start from the database query and try to hit it with a higher load of requests and see how quickly it responds, and whether there are alternative ways to query the info that isn’t as prone to timing out.

**Comment by jsayers-bsc** [comment]
I'll keep an eye on when I see it again. I think I've seen the error at other times as well during other calls and I think it tends to be a "restart the session" or "try again later" sort of thing. It may not be related to metadata() specifically.

**Comment by denislepage** [comment]
I haven’t seen specific error messages coming from the database, so you may be right.

**Comment by jsayers-bsc** [comment]
The initial issue with the not null constraint on nodeDeps.tsEnd is resolved and Project 213 metadata updates fine. 

The `failed to build response vectors` issue seems unrelated so I'll open a new issue and let @steffilazerte close this one when the hotfix is merged in.
