### ISSUE TITLE
Attachment type is required even for Test tag deployments 

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#899]
![image](https://user-images.githubusercontent.com/55001144/104472983-8333f400-558a-11eb-912b-9552fd641486.png)

The attachment field shouldn't be required for Test Tags as many (all?) won't actually be attached to an animal.

**Comment by cjardine-bsc** [comment]
@pmorrill

**Comment by pmorrill** [comment]
Fix in beta9 and master
