### ISSUE TITLE
tag page cache refreshment

### ISSUE THREAD

**Issue by zcrysler** [MotusDev/Motus-TO-DO#90]
Tags page: cache is being refreshed when paginated but it's not refreshing the cache when all records are on one page.  See https://motus.org/data/project/tags?projectID=173, there were 2 deployments for each tag, I deleted the duplicates, these changes are apparent when paginated, but when I click "view all records on one page" both deployments for each tag appears

**Comment by pmorrill** [comment]
I tried to reproduce this Zoe but could not. In sandbox, I set up a tag wit 2 deployments, then removed one and all my lists-views seemed to update ok. I'll try again, but let me know if there is some particular sequence that you might have followed to get this problem to appear.
