### ISSUE TITLE
Improvements to sqlite tag database download

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#901]
A few suggested improvements to the download tag database file (the .sqlite file that can be copied onto an SG to allow for local tag identification).

- Provide a .sqqlite for **all** currently registered tags to a project. Currently the .sqlite files are generated only for date_bins when tags were registered, and contain only the tags registered in that date_bin. Since the SG can only handle one tag database at a time, this requires users to download and merge desired databases in R before copying over to the SG. Having access to a complete and up-to-date sqlite file would simplify the process for users.
- Give the sqlite files meaningful and unique names. On motus.org/Manage Tags they have neither date nor extension in the name; all are simply called "tagdb". However, on [sgdata.motus.org](ProjectX_tagdatabase_DATE.sqlite) they are given meaningful names with extensions (e.g. ProjectX_tagdatabase_DATE.sqlite). This format would be helpful to have when downloading from motus.org as well.

(This is an update to #673)

**Comment by j-sayers** [comment]
As an addendum, tag database is only generated for the project that initially registered the tags.

For instance Project 125 has a few dozen tags currently active. But they were apparently all transferred from various other projects so there are actually no sqlite tag database available for this project.

**Comment by leberrigan** [comment]
Closing and referencing the issue in Future Developments project

**Comment by denislepage** [comment]
OK, I added a feature in the API that allows downloading the sqlite data, either as a csv file or an sqlite file. I haven't linked this from the download pages yet, but the links below will work.

The default returns all tags currently in a project. Optionally, it'll support a feature to only get tags between a range of dateBins. I tried to replicate the format as closely as possible to the original generated by sgdata.  One field that we don't seem to have in the tags table is dfreq.sd (the SD of the delta frequency measure), so I set this to 0.0 for all records.

I also left out potentially useful fields, especially the dateBin. We'd need to test how SG behaves when adding unsupported fields to the sqlite file. To test this, I have created an option that will generate the file with a couple added fields (dateBin, model and lifespan). If those aren't causing any problems, we can just include them by default in all calls.

SQLite format:
https://sandbox.motus.org/data/downloads/api-proxy/tags/sqlite?fmt=sqlite&projectID=45

CSV format:
https://sandbox.motus.org/data/downloads/api-proxy/tags/sqlite?fmt=csv&projectID=45

SQLite format (from 2016-1 onwards):
https://sandbox.motus.org/data/downloads/api-proxy/tags/sqlite?fmt=sqlite&projectID=45&dateBinStart=2016-1

SQLite format (from 2014-1 to 2014-4):
https://sandbox.motus.org/data/downloads/api-proxy/tags/sqlite?fmt=sqlite&projectID=45&dateBinStart=2014-1&dateBinEnd=2014-4

SQLite format (with additional fields included)
https://sandbox.motus.org/data/downloads/api-proxy/tags/sqlite?fmt=sqlite&projectID=45&allFields=yes

Can we find someone to test those files in a SensorGnome?

**Comment by denislepage** [comment]
A few more upgrades.

In Download project data (https://sandbox.motus.org/data/downloads?projectID=45), I added a link to the sqlite download page.

![image](https://user-images.githubusercontent.com/21110542/177701190-a03ad746-135c-44f1-aae3-8042745f7f6b.png)

Eventually, we may simply replace that page with a simple link above, but for now, I have added the full download option. I am not convinced with need to expose the ability to filter by dateBin. I also added a note saying that the links to the single files from sgdata are deprecated and only apply to manual tag registrations.

![image](https://user-images.githubusercontent.com/21110542/177701069-2f0869c2-29a8-4978-bc69-5f53d5e97f8e.png)

The button to download the tag database from the tags page remains unchanged for now and still links to the above, so there are now 2 ways to access the data (3 if you count sgdata).

Finally, we'll need to also modify the language on the sgdata page. I'd be in favor of no longer offering the download from that page at all, and telling people to go to the Motus page.

@j-sayers  and/or @eageldart  can you review the language and functionalities? We should also test to make sure that people without tag permissions cannot access sqlite data from other projects. That will be important.

**Comment by j-sayers** [comment]
> In Download project data (https://sandbox.motus.org/data/downloads?projectID=45), I added a link to the sqlite download page.

Makes a lot more sense to have it here anyway

> Eventually, we may simply replace that page with a simple link above, but for now, I have added the full download option. I am not convinced with need to expose the ability to filter by dateBin. I also added a note saying that the links to the single files from sgdata are deprecated and only apply to manual tag registrations.
> 
Yeah not sure if we need to do more than offer the ability to download all tags currently registered to a project. Unless the sg-based tagfinder has diminished performance with 100 vs 10 tags (unlikely it seems) I can't think of why people wouldn't just want the complete list. 
> 
> The button to download the tag database from the tags page remains unchanged for now and still links to the above, so there are now 2 ways to access the data (3 if you count sgdata).
> 
> Finally, we'll need to also modify the language on the sgdata page. I'd be in favor of no longer offering the download from that page at all, and telling people to go to the Motus page.

Definitely worth just doing this properly and only on motus.org. And once we have [filterable and searchable job logs on motus.org](#1036) there really won't be any reason to send them to sgdata for anything and keep it simple.

> @j-sayers and/or @eageldart can you review the language and functionalities? We should also test to make sure that people without tag permissions cannot access sqlite data from other projects. That will be important.

I'll use this one on the couple tests SG's here.

A comment regarding format, I think that maybe we leave the csv option off the table. This is really just for getting the tag db on the SG and there already is a csv option used for uploading changes to tag deployments in bulk. Doing both in csv may add unnecessary confusion. So for that purpose maybe it's not even worth including dateBin, even though it's admittedly useful in other contexts. 

The local tagfinder should really just be used to assist with deployment --- confirming that the tag is active and detected while in the process of deploying, rather than trying to infer from pulses. But it also has limitations. Mainly that it does not account for BI. So it's one of those potentially very useful tools that will (and probably should) only be used in certain cases.

**Comment by denislepage** [comment]
The main reason not to want to have the full list is to avoid looking for expired tags. Multi-year projects would then need to truncate the data, and having the dateBin field in the table itself would be more important. There could be value in adding an option to generate a file for a range of dates only.

The API can support additional features that we don’t immediately or ever expose, such as CSV download. I agree that it really only makes sense to offer the sqlite option.

**Comment by j-sayers** [comment]
Maybe then the default "complete" version should refer to the active tags for that particular project. That way at least expired, deprecated tags are omitted. Though maybe that was already the behaviour...

**Comment by StuMackenzie** [comment]
This looks great, but we need to remove 'Atlantic Offshore Wind' from the Fee drop down.

Needs to be pushed to live.

**Comment by denislepage** [comment]
I have changed the file name to the date/time of the download.

tagfile_project_10_2022-07-12-23-48-01.sqlite

Jeremy @hussell, can you merge those changes into beta? I may still need to make some adjustments in the main database though. Can’t remember for sure.

**Comment by denislepage** [comment]
This should now all be in live.
