### ISSUE TITLE
Omni antenna shape where no omni exist - Deployment 7512

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#903]
Project- 213 Deployment - 7512

omni antenna shape appearing even though no omni exists?

![image](https://user-images.githubusercontent.com/21124211/105560156-11be1900-5ce1-11eb-8a5e-3785758e41f3.png)

**Comment by Hussell** [comment]
This deployment has 3 antennas with no bearing. When the bearing is missing, it defaults to a 15km circle.

Documented here: https://github.com/MotusDev/Motus-TO-DO/issues/666#issuecomment-720609998

**Comment by StuMackenzie** [comment]
Right - thanks - i noticed that but didn't close the loop.
