### ISSUE TITLE
Deployment name of Networked receiver reverted to very outdated one

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#906]
The Motus Ontario receiver Koffler is a networked which has been reliably connecting for months. Today I noticed the receiver is still on the networked gnomes page, but instead of being called Koffler as it usually is, the name has reverted to the deployment Nelles (last active in 2015). A cursory look suggests it's just the deployment  name displayed on sensorgnome.org that is incorrect so it doesn't seem to be of critical importance, and I'm not sure how long it's been like this (maybe weeks).

![image](https://user-images.githubusercontent.com/55001144/106311045-812c8f00-6232-11eb-9f3d-f6555ad5f87d.png)

![image](https://user-images.githubusercontent.com/55001144/106311094-92759b80-6232-11eb-8aeb-f7c3267c7c5c.png)

**Comment by jsayers-bsc** [comment]
That's not the only one actually. OldCut has reverted to a test deployment from 2014. Again, at a glance looks likes data is all being uploaded just fine, but just that somehow the first deployment name associated with the receiver is being displayed

![image](https://user-images.githubusercontent.com/55001144/106312028-0ebcae80-6234-11eb-873d-a0918c6abee9.png)

**Comment by dfloer** [comment]
I'll take a look at this. My understanding is that this data is coming from SGdata via an API call, but I'll see if there's something else going on here.

**Comment by dfloer** [comment]
That data is definitely coming from the API call, so it's (probably) a sensorgome.org issue.

**Comment by leberrigan** [comment]
It's weird bug that's to do with the datapacket that is first send from the SG when it first connects via a given network.
