### ISSUE TITLE
Truncated Deployment Timelines

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#909]
Deployment timelines no longer show all detections of tags. Is it possible to make the entire timeline visible? These timelines are very useful for identifying false positives.

**Example:**
Deployment starts in 09-2015, but detections only appear in timeline on 09-2020.
https://motus.org/data/receiver/deployment/plot/SG%2D1614BBBK1899-2015%20Quebec%2C%20Tadoussac.png?id=3146&n=100&firstTag=0
Table of detections show annual detections since 09-2015
https://motus.org/data/receiverDeploymentDetections?q=&id=3146&f=1&n=100&o=0a1a2a3a4a5a

**Comment by jsayers-bsc** [comment]
Commenting for reference: on the call the other day, Jeremy mentioned the parameters for number of tags to display are in the URL. Modifying the "n=100" value allows more tags to be displayed (at the expense of longer load time).
