### ISSUE TITLE
Aliasing occurring on one receiver, but not (as much) on another nearby receiver

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#912]
Testing some of the new Lotek 6M codeset tags at and two nearby receivers are showing very different tag "detections".

There are 4 tags all with BI 4.9 active in the workshop, next to a test receiver [Deployment 7524](https://motus.org/data/receiverDeployment?id=7524). About 25m away is the permanent BSC HQ Deployment.

The new tags are all showing up basically as expected on the Test-4656 deployment since they were turned on. One obvious aliased false positive on BI 4.9 is also seen "detected" today (18th).

https://motus.org/data/receiver/deployment/plot/?id=7524

However on the BSC HQ receiver, none of the actual tag IDs shows up even once. Instead are a couple dozen aliased false positives, all on BI 4.9. Aside from there being only aliased tags present on this receiver, it's also interesting that no "detections" of any kind show up for the first couple days, and then only a couple aliased tags, until the 17th and 18th, where most appear. 

https://motus.org/data/receiver/deployment/plot/?id=2146

**Comment by StuMackenzie** [comment]
For the next 'round' I'd suggest that we:

1) Tag two tags to old cut and see how they perform - So leave 2 at old cut and 2 at BSC until next week. Take the BSC tags out side and separate them a bit. Attach an omni to the test SG, and place that outside as well somehow. At Old Cut we can place the tags apart from one another.

**Comment by denislepage** [comment]
With 4 tags at 4.9 seconds, you have roughly a 30% chance that at least 2 tags will overlap (based on the average burst length of around .25 seconds, each tag pair has about a 5% change of overlapping or .25 / 4.9, times 6 possible combinations of tag pairs), so conditions that can create aliasing are relatively easy to replicate with a small number of tags.

From the receiver that didn’t create aliases, can you tell if the hits from the 4 tags are spaced in time in a non-overlapping way? IE, are they potentially synchronized in a way that can create aliasing?

One thing I mentioned after you left the call would be to look at the pulse data files (the gz files) for a short section of data, and see how they differ among the 2 receivers. If one of the receiver is missing occasional pulses, or has variation in signal strength, this could potentially create conditions that are more favorable to aliasing.

What I would want to see is a list of all the pulses side-by-side, with the timestamps, the signal strength, the noise and frequency (for a period where aliasing is happening). This is all tag finder has to work from, so I would expect that we should see some differences on at least one aspect (missing pulses, variation in strength or background noise or frequency)..

One test would be to only have one active tag at a time, and see if you are still seeing problems.

**Comment by cjardine-bsc** [comment]
Sassy Edit: 

_One thing Catherine discussed in detail with you on the call when Denis clearly wasn't paying attention_.....would be to look at the pulse data files (the gz files) for a short section of data, and see how they differ among the 2 receivers. If one of the receiver is missing occasional pulses, or has variation in signal strength, this could potentially create conditions that are more favorable to aliasing.

What I would want to see is a list of all the pulses side-by-side, with the timestamps, the signal strength, the noise and frequency (for a period where aliasing is happening). This is all tag finder has to work from, so I would expect that we should see some differences on at least one aspect (missing pulses, variation in strength or background noise or frequency).

_hehehe :-P Thanks for documenting Denis. Great minds. Josh, please also remember to put the gz files on the I drive for me to access. Thanks!_

**Comment by denislepage** [comment]
¯\_(ツ)_/¯

**Comment by jsayers-bsc** [comment]
Ok...

So around 15:00 UTC today I turned off all but 1 tag (mfg_id 700).

The BSC deployment hasn't yet correctly identified any of the test tags even once. All radio data coming from these tags has resulted in aliased tags. Though even these aliased "detections" aren't regular, but sporadic -- despite the close proximity. With only one tag active, aliasing shouldn't happen. The question is whether this one tag will be detected at all at the BSC station.

I also set up another antenna on the roof -- a 3-element basically pointing right at the window of the workshop. So if there are any antenna related issues with the main BSC station, that won't be a factor here. 

I was going to attach the new antenna to the same receiver, but thought that might complicate things at this stage. Instead I set up another temporary station on the roof attached to the singular "optimal" antenna. 

There are 3 receiver deployments:

- Test SG https://motus.org/data/receiverDeployment?id=7524 Is beside the tag(s) and has been identifying them correctly
- BSC HQ https://motus.org/data/receiverDeployment?id=2146 Is on the BSC roof with 4 9-element antennas (somewhat crowded) and each pointing off into the distance
- Temporary SG on the roof https://motus.org/data/receiverDeployment?id=7528 Is also on the BSC roof and has only 1 antenna: a 3-elelement pointing toward the workshop window (where the tag is).

I did downloaded data from the BSC and Test Pi stations today. 
 
Test Pi: https://1drv.ms/u/s!AuV8pnhpZa-m7c8Y-nM9ftTTJ06i9A?e=NA6Ebn
BSC: https://1drv.ms/u/s!AuV8pnhpZa-m7c8aL8ieyHdfli2P-w?e=qpEPcP

**Comment by jsayers-bsc** [comment]
Checking now, it doesn't look like the BSC station is syncing properly. No new data in the last few hours....

**Comment by jsayers-bsc** [comment]
Over the weekend it was detecting the one real 6M tag just fine. As was the Test Pi and the Temp Pi (as expected on both accounts).

Yesterday I turned on a 2nd tag. So far the 2nd tag is also being detected on each station. I'll let this go for a couple days before turning on the 3rd tag and see if aliasing starts to occur at that point on the BSC station.

**Comment by denislepage** [comment]
Did you ever resolve whether the previous instance were actually overlapping?

**Comment by jsayers-bsc** [comment]
Some further developments...

I just checked the detections summary on the BSC station and everything now looks the same as the nearby receiver. In the screenshot, you can see where I turned all the tags on Feb 13, then when I turned all but one off on the Feb 21st. **Previously there were no detections of these tags on this receiver during this period** -- just dozens of false detections of tags not present. There are still a couple false detections, but only a couple, and consistent with what the nearby receiver was picking up.

![image](https://user-images.githubusercontent.com/55001144/115051731-23135d80-9eab-11eb-8351-60caee0ce17d.png)

So what happened?! The receiver was re-run since then (including twice on the same day?) but I'm not sure how that would have affected things so dramatically. It's possible some deployment metadata for some tags was updated, and deployments ended. But I still don't see how that changes this much, and given below that doesn't seem likely...

Below is a screenshot from a [BB I had on a few days](https://motus.org/data/receiverDeployment?id=7625) to test dual-mode recording (it has just one FCD attached, and **there is just _one_ Lotek tag active**). I just looked at the detections and it's the same as originally noticed on the BSC station: lots of false detections yet the only actual tag present isn't even detected once. Meanwhile on the BSC station 25m away, this single tag is being detected regularly (see first screenshot).

![image](https://user-images.githubusercontent.com/55001144/115054930-d467c280-9eae-11eb-8e86-d0f05cfe327d.png)

**Comment by leberrigan** [comment]
@Hussell, can you try re-running deployment #7625 to see if this fixes the issue? It only has a few days of data so should be quick.

**Comment by j-sayers** [comment]
Re-running the receivers addressed the incorrect detections, but there is still a bit of a mystery what happened.
