### ISSUE TITLE
Add list of 'local tag deployments' to stations table

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#917]
Let's find all the tags that were deployed within a 'reasonable' range of each station and designate it as '**local**' (proximal is just not a cool word) to that station. This will allow me to create nifty visualisations among other things. 

Let's say all tags deployed within 10 KM are to be considered **local**. Why this large of an area? I'm thinking of study sites where tags are not necessarily deployed near a station. This happens fairly often.

**Comment by cjardine-bsc** [comment]
Do you care about whether the tag and sensor deployments overlap in time?

**Comment by cjardine-bsc** [comment]
Okay. Here is the query I'm using to create the table: 

;WITH CTE AS (
Select a.id as tagDeploy, b.id as station, dbo.distance(a.latitude, a.longitude, b.latitude, b.longitude ) as dist
from tags_deployments a cross join sensor_stations b)

Select * from CTE where dist < 10000

It's slow, so we're going to need to look at how to keep it up to date, but I'll email you the initial spreadsheet results so you can play with them in your dashboards.

**Comment by cjardine-bsc** [comment]
Okay, I've created a new table in sandbox called tags_local_stations, which I've populated. 

I'm not sure how we want to keep this up to date. We could run a periodic wipe and replace of the whole table (prUpdateTagsLocal takes 7min), or set up triggers for when the lat/lon of a station or tag_deployment is edited or created. I believe we already have a process that updates a few places when that happens.

**Comment by cjardine-bsc** [comment]
Now that this is live @denislepage and I should discuss how to best keep it up to date. I re-ran it now but we should talk about it at the next meeting.

**Comment by denislepage** [comment]
This alternative takes about 1 second:

```
select id, geography::Point(latitude, longitude, 4326) as pt
into #temp1 from tags_deployments  where latitude between -90 and 90 and longitude between -180 and 180

select id, geography::Point(latitude, longitude, 4326) as pt
into #temp2 from sensor_stations  where latitude between -90 and 90 and longitude between -180 and 180

ALTER TABLE #temp1 add primary key (id)
CREATE SPATIAL INDEX __temp1 ON #temp1(pt) 
   
select count(*) from #temp1 a cross join #temp2 b where a.pt.STDistance(b.pt) < 10000

```

**Comment by cjardine-bsc** [comment]
So speedy!!! 

I updated the proc and included it in the recur table for the procs queue.
