### ISSUE TITLE
Differences between maps on View Tracks and Tag Deployment (including flagged "detections" still present)

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#919]
I think this is a question for @Hussell.

There are at least two different ways of viewing tracks/detections for a particular tag deployment

1) Accessed from the "tag deployment" overview page.
2) Accessed from the Explore Data > View Tracks

I had assumed that they represented the same data, but that's not entirely the case. It seems that tags that have been manually flagged as suspect are removed from the first map, but are still visible in the second map. An example is below 

Tag Deployment 5668, a NSWO was "detected" on Baffin Island. These were identified and flagged (see [here](https://github.com/MotusDev/Motus-TO-DO/issues/853#issuecomment-773515076)).

When the [map on the Tag Deployment page](https://motus.org/data/track?tagDeploymentId=5668) is viewed, the tag/receiver combo has been removed (as with the summary table).

However when the same tag deployment is accessed [via the View Tracks map](https://motus.org/data/tracksMap?t=5668), the flagged tag/receiver combo is still present. These locations are also present in the _det_taghits_tracks_ table.

![image](https://user-images.githubusercontent.com/55001144/110352172-98b22100-8003-11eb-82f4-ae496953f470.png)

So there are a couple things:

- Since the public do view tag deployments on the View Tracks maps, we want the flagged detections to be removed from there as well. I'm hoping that this will involve updating det_taghits_tracks to remove points associated with flagged tag/receiver combos since I currently use that table for station summary maps. But maybe they will have to be filtered out some other way.

- What exactly are the differences between these two maps anyway? Do they actually pull from different sources, and if so, where do the detections and tracks for the Tag Deployment map come from? Are the extrapolated paths calculated differently than for the View Tracks map? (This is a general, documentation question)

**Comment by Hussell** [comment]
This was a bug, the maps were supposed to be pulling from the same source but weren't. I think it's fixed now on beta and live (I haven't merged the fix into sandbox yet). One remaining difference between these maps is that the map on the tag deployment page will show non-public information if you're logged in and have permission to see it.

**Comment by jsayers-bsc** [comment]
The owl that was still being shown on Baffin Island is now absent entirely -- the [link ](https://motus.org/data/tracksMap?t=5668)I screenshot earlier no longer leads anywhere and there is no longer a tagDeployID 5668 in det_taghits_tracks.

I tried to do a summary earlier of a station with several hundred tags detected (likely quite a lot of aliased ones, but still). The list of tags with runLen < 3 was over 600, yet only 5 of those tag_deploy_id are present in det_taghits_tracks. Some of the absent ones are are in det_runs_filters_manual, but none at this particular deployment.

Something odd is happening where tag deployments once present are now absent from the det_taghits_tracks. Sort of like that time [everyone started vanishing around Dr Crusher](https://en.wikipedia.org/wiki/Remember_Me_(Star_Trek:_The_Next_Generation)).

Quite possibly the same thing going on in #924

**Comment by Hussell** [comment]
Alright, I think I got it this time.

**Comment by jsayers-bsc** [comment]
Appears to be resolved. Closing and will re-open if that turns out not to be.

**Comment by j-sayers** [comment]
Whatever the latest occurrence was, it's not an issue anymore.
