### ISSUE TITLE
make maps scrollable again with mouse wheel

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#92]
Adding this option in the map makes the scroll wheel behaviour the same as it was a few months ago.

gestureHandling: 'greedy' 

We'd have to see the impact on a mobile device, but our site really isn't well optimized for that in any case, I think.

**Comment by Hussell** [comment]
- [ ] [receivers map](https://beta.motus.org/data/receiversMap)
- [ ] [receiver deployment map](https://beta.motus.org/data/receiverMap?receiverDeploymentId=645)
- [ ] [tag tracks map](https://beta.motus.org/data/track?tagDeploymentId=1949)
- [ ] [tags tracks map](https://beta.motus.org/data/tracksMap?stp=10&e=2014-11-01&l=2014-12-31&f=0&c=s&cs4670=%23ff0000&s=4670&t=402&t=980&t=995&t=1012&t=1060&t=1063&t=1067&t=1068&t=1069&t=1070&t=1071&t=1072&t=1073&t=1075&t=1077&t=1078&t=1080&t=1081&t=1082&t=1083&t=1084&t=1085&t=1086&t=1088&t=1090&t=1091&t=1092&t=1949&cs5280=%230080ff&s=5280&t=5893&t=5897&t=5900&t=5905&t=5907&t=5910&t=5913&t=5946&t=5947&t=5957&cs4820=%23ffff00&s=4820&t=405&t=406&t=409&t=415&cp47=%23ff0000&p=47&cp21=%230080ff&p=21&cp15=%23ffff00&p=15&ln=50.19114&ls=38.13850&lw=-80.72810&le=-60.02285&x=n)
- [ ] [tag deployment management](https://beta.motus.org/data/tag/deployment/edit?projectID=24&id=4510)
- [ ] [receiver deployment management](https://beta.motus.org/data/receiver/deployment/edit?projectID=24&id=2305)
- [ ] [site management](https://beta.motus.org/data/project/sites?projectID=24)

**Comment by denislepage** [comment]
It seems to be working in beta, but on the main site (suggesting the default still is forcing the use of CTRL).
