### ISSUE TITLE
Expired certificate on SensorGnome.org

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#920]
![image](https://user-images.githubusercontent.com/55001144/110369451-6a8b0c00-8018-11eb-9982-cb19c3056339.png)

**Comment by jsayers-bsc** [comment]
@denislepage @dfloer

**Comment by denislepage** [comment]
@dfloer can you either look after this or get in touch with Compudata. I thought we had dealt with this just a few months ago. We should get a longer certificate, if that's the issue.

**Comment by dfloer** [comment]
I have contacted compudata (and cc'd both of you on the email).

**Comment by dfloer** [comment]
It's working again. Compudata has graciously provided a new certificate, good until March 8th, 2022.
