### ISSUE TITLE
SensorGnome WiFi connection on Network with spaces in name

### ISSUE THREAD

**Issue by adamdsmith** [MotusDev/Motus-TO-DO#921]
@dfloer @leberrigan @jsayers-bsc 

Looking for some quick syntax help for the `network.txt` file when connecting an SG to a WiFi network.

Currently, the file says:

```
# 2. What is WiFi network name? (must be a WPA/WPA2-protected network)

NetworkName
```

What would the syntax look like for a network name that included spaces, e.g., `Network Name`?

I'd poke around if it was local, but this is for a remote partner assist.

Thanks!

**Comment by dfloer** [comment]
I haven't tested this, but does enclosing it in double quotes work? `"Network Name"` for example.

**Comment by adamdsmith** [comment]
Not sure. I'll try to test this locally in the near future...

**Comment by adamdsmith** [comment]
An update:

Unsuccessful with both `"Network name"` and `'Network name'`...

So, I said, guess I'll give it a shot with the default, unquoted `Network name`, knowing full well it was in vain...

And, of course, it works fine as-is... with no quotes...

I'm sorry for wasting people's time. Close away.

**Comment by jsayers-bsc** [comment]
> 
> 
> An update:
> 
> Unsuccessful with both `"Network name"` and `'Network name'`...
> 
> So, I said, guess I'll give it a shot with the default, unquoted `Network name`, knowing full well it was in vain...
> 
> And, of course, it works fine as-is... with no quotes...
> 
> I'm sorry for wasting people's time. Close away.

Thanks @adamdsmith , I'm sending out a pre-configured Pi to a northern station and their WiFi has a space. I'll go with plain unquoted text though I agree it sounds like it shouldn't work!
