### ISSUE TITLE
Tracks are visible, but nothing in table or timelines

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#923]
https://motus.org/data/track?tagDeploymentId=21366

Is this related to project permissions?

**Comment by Hussell** [comment]
Probably fixed by #919. Testing needed.

**Comment by StuMackenzie** [comment]
@leberrigan can you test?

**Comment by leberrigan** [comment]
Nope. Still not fixed.

**Comment by Hussell** [comment]
... that's weird. I would've sworn I looked at this example earlier and the tracks were gone.

**Comment by leberrigan** [comment]
No tracks now! I think we're good
