### ISSUE TITLE
How exactly is hourBin calculated?

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#925]
### Main question 
Why would the hourBin in the activity table appear be incrementing mid-hour instead of on the hour? It also doesn't seem to be consistent when its incrementing. I can account for the all the hits in the activity table by looking at the alltags table, but their hour bins seem to be offset.

---

### Description

I'm trying to match the activity table with the alltags table using data from **SG-3214BBBK5757** ("Tadoussac - André") and the only way I'm aware is by first calculating the hourBin using timestamps in the alltags table, but it doesn't seem like it's matching up as expected, and it's not a timezone problem. 

According to the 'activity' table, the first hour bin has 109 hits, but if I group the 'alltags' table by hour I get 5 hits in the first hour bin. 

If I sort the 'alltags' table by timestamp, the 1st hit is at **2016-09-12 14:58:45** and the 109th hit is at **2016-09-12 15:06:04**. The 110th hit (where the next 'hourBin' supposedly starts in the activity table) is at **2016-09-12 15:06:05**, only 1 second later.

Similarly, if I look at the 578th hit (the last hit of hourBin 409426) it occurs at **2016-09-15 11:50:27** and the next hit (the first hit of hourBin 409427) occurs at **2016-09-15 11:50:38**. This time the hourBin seems to increment at a different time. What's going on here???

### activity.df

hourBin | numHits | numRuns | numTags
-- | -- | -- | --
409358 | 109 | 3 | 2
409359 | 193 | 5 | 3
409426 | 276 | 4 | 1
409427 | 53 | 2 | 2
409428 | 471 | 12 | 2

### alltags.df (grouped by hour)

hourBin | nHits | numRuns | numTags | time.start | time.end
-- | -- | -- | -- | -- | --
409358 | 5 | 3 | 2 | 2016-09-12 14:58:45 | 2016-09-12 14:59:59
409359 | 297 | 6 | 4 | 2016-09-12 15:00:00 | 2016-09-12 15:18:32
409426 | 44 | 4 | 1 | 2016-09-15 10:51:59 | 2016-09-15 10:59:49
409427 | 262 | 3 | 2 | 2016-09-15 11:00:00 | 2016-09-15 11:59:54
409428 | 403 | 13 | 2 | 2016-09-15 12:00:05 | 2016-09-15 12:59:52
409429 | 95 | 2 | 2 | 2016-09-15 13:00:03 | 2016-09-15 13:16:27

### The code

```
library(tidyverse)
library(lubridate)
library(motus)

data.dir <- "E:/Data"

recv <- "SG-3214BBBK5757"

Sys.setenv(TZ = "UTC")

motus.sql <- tagme(recv, new = T, update = T, forceMeta = T, dir = data.dir)

# Load in activity tables and remove bad clock times.
activity.df <- motus.sql %>% tbl('activity') %>% collect() %>% as.data.frame() %>%
  filter(hourBin > 10000)

# Load in alltags and fix vars
alltags.df <- motus.sql %>% tbl('alltags') %>% collect() %>% as.data.frame() %>%
  mutate(ts = as.POSIXct(ts, origin = '1970-01-01'),
         date = as.Date(ts),
         tagDeployID = as.character(tagDeployID),
         tsCorrected = as.POSIXct(tsCorrected, origin = '1970-01-01'),
         hourBin = as.integer(difftime(tsCorrected, as.POSIXct("1970-01-01 00:00:00"), units = 'hours')))


# Join activity.df and alltags.df by hourBin
alltags.activity.df <- alltags.df %>% 
  mutate(valid.proj = !is.na(tagProjID) & (tagProjID %in% valid_projs),
         tsCorrected = as.POSIXct(tsCorrected, origin = '1970-01-01'),
         hourBin = as.integer(difftime(tsCorrected, as.POSIXct("1970-01-01 00:00:00"), units = 'hours'))) %>%
  left_join(activity.df %>% select(hourBin, numTags, pulseCount = count, numRuns, run2, run3, propRunLong))

# See if the hourBin matches up
allTags.test <- alltags.df %>% 
  group_by(hourBin) %>% 
  summarise(nHits = length(unique(hitID)), 
            numRuns = length(unique(runID)), 
            numTags = length(unique(motusTagID)),
            hour.start = min(ts),
            hour.end = max(ts))
```

**Comment by cjardine-bsc** [comment]
I've not looked at this in depth. 

The hourbin is calculated by taking the ts value and dividing by

**Comment by leberrigan** [comment]
Thanks Catherine!

**Comment by cjardine-bsc** [comment]
This probably needs documentation in the R book. 

Also worth re-thinking those decisions if this is going to be used for more than just run filtering.

**Comment by denislepage** [comment]
![image](https://user-images.githubusercontent.com/21110542/110998113-56167e80-834c-11eb-98f6-71729cb23b99.png)

**Comment by leberrigan** [comment]
I'm not trying to stir the pot!

Hour bin is still accurate - now that I know how it's calculated I think it'll be fine.

But yes, documentation would be handy. And methods on how to calculate the hourBin the _other_ way could be added if we think it's useful too:
```
alltags.df %>%
  group_by(hourBin) %>% 
  summarise(nHits = length(unique(hitID)), 
            numRuns = length(unique(runID)), 
            numTags = length(unique(motusTagID)),
            hour.start = min(ts),
            hour.end = max(ts))
```

**Comment by denislepage** [comment]
In theory, there isn’t much value in looking at the activity data across hour bins. The hour bin should be calculated on the tsBegin field of the run, not the ts of the hits.

Long runs that span across multiple hourBins are probably mostly fine, anyway, unless they happen to be short ones that are right at the boundary of an hourBin, but then, the activity count in the first hour bin is just as good a metric as the second one.

To be more precise, someone could calculate shorter bins and look at the activity around the time of each hit, but we’re not dealing with hits individually anyway, so it’s really the activity over the whole run that matters, and particularly when a run is first initiated. While there may be rarely incorrect false hits in the middle of a valid run (a tag was not within range in a middle of a run, but noise created a false signal), it should be extremely rare and also shouldn’t matter. We always qualify the whole run as valid or not as a single unit, and not parse out valid hits within a run, so the only possible refinement that could help would be to calculate the pulse activity specific to that period, but that would be intensive, and probably not all that valuable, as the impact of noise is, well, noisy.

**Comment by cjardine-bsc** [comment]
The benefit would be combining information from runs, pulse counts and GPS all in one place to help determine when a station is active. But that should be done separately from the process that identifies noisy time periods and suspicious runs. 

Can I close this?

**Comment by jsayers-bsc** [comment]
> The benefit would be combining information from runs, pulse counts and GPS all in one place to help determine when a station is active. But that should be done separately from the process that identifies noisy time periods and suspicious runs.
> 
Providing this information across the entire period (and not just when detections occur) would definitely be  very helpful (e.g. #842)
