### ISSUE TITLE
Change Birds Canada and Lotek logos on partners page

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#928]
https://motus.org/data/partners

Old Birds Canada and Lotek logos need to be replaced. I'm not able to change them myself. Attached logos can be used:
![BirdsCan_SQ_2col](https://user-images.githubusercontent.com/35931796/111469536-30e39080-86fd-11eb-8a3a-2e15c14fd34f.png)
![Lotek](https://user-images.githubusercontent.com/35931796/111469538-317c2700-86fd-11eb-9b20-74091bd5c430.png)

**Comment by cjardine-bsc** [comment]
@Hussell This .jsp isn't where I was expecting to find it.  Perhaps it's been moved while you were organizing?

**Comment by Hussell** [comment]
https://beta.motus.org/data/partners

**Comment by StuMackenzie** [comment]
Thanks! If anyone notices the relics anywhere please let us know.
