### ISSUE TITLE
Error: Failed to build response vectors

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#929]
This came up [recently ](https://github.com/MotusDev/Motus-TO-DO/issues/897#issuecomment-790748337) while trying to use the `metadata()` function. 

I feel like I've seen it at other times as well, when not trying to call metadata() but perhaps it's always been while using the same function. Either way, the solution is "Keep trying again until it works". That doesn't help identify the issue, but does suggest something connection or server related. Below are a few attempts to call this this morning, all in succession.

It keeps failing, at different times, and then suddenly succeeds.

```
Loading complete Motus metadata
Error: Server returned error 'Failed to build response vectors.'
Timing stopped at: 0 0.01 1.5
> system.time({
+   metadata(m)
+ })
Loading complete Motus metadata
Error: Server returned error 'Failed to build response vectors.'
Timing stopped at: 0 0 0.28
> system.time({
+   metadata(m)
+ })
Loading complete Motus metadata
Error: Server returned error 'Failed to build response vectors.'
Timing stopped at: 0 0 1.89
> system.time({
+   metadata(m)
+ })
Loading complete Motus metadata
Done
   user  system elapsed 
   2.20    0.18   14.40 
```

And then later... It succeeds twice, then fails, then succeeds again. 

```
>       metadata(recv_data)
Loading complete Motus metadata
Done
>       metadata(recv_data)
Loading complete Motus metadata
Done
>       metadata(recv_data)
Loading complete Motus metadata
Error: Server returned error 'Failed to build response vectors.'
>       metadata(recv_data)
Loading complete Motus metadata
Done
```

I don't have much more to add then that; it's really just hit or miss from my vantage point. By the way, I've been using metadata() exclusively lately since[ `forceMeta = TRUE`  occasionally does not work as expected](https://github.com/MotusDev/Motus-TO-DO/issues/879), and results in a .motus file that lacks tagDeps and a number of other essential metadata tables.

**Comment by jsayers-bsc** [comment]
A traceback from one of these:

> Error: Server returned error 'Failed to build response vectors.'
> 4. stop("Server returned error '", er, "'", call. = FALSE)
> 3. srvQuery(API = motus_vars$API_TAG_METADATA_FOR_PROJECTS, params = list(projectIDs = projectIDs), verbose = verbose)
> 2. srvTagMetadataForProjects(projectIDs = projectIDs)
> 1. metadata(sql.motus)

**Comment by steffilazerte** [comment]
Hmm, there's a very good chance this is related to #955, as the problem was that the R package was sending incorrectly formatted data to the API which could very well trigger this error. `srvTagMetadataForProjects` was one of the functions affected too.

*Hopefully* the fix in #955 will also address this, fingers crossed!

**Comment by jsayers-bsc** [comment]
After the recent changes the following message is displayed:

> metadata(m)
Loading complete Motus metadata
Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.Done

**Comment by steffilazerte** [comment]
Argh, I *think* the metadata should have downloaded regardless, but it's fixed in `hotfix-metadata` anyway.

Test for me?  🙏🏼  😁 

```
remotes::install_github("MotusWTS/motus", ref = "hotfix-metadata")
tags <- tagme(176)
metadata(tags)
```
There should be complete metadata and no warnings!

**Comment by steffilazerte** [comment]
Hi @jsayers-bsc, have you had a chance to test yet? 😁  Thanks!

**Comment by jsayers-bsc** [comment]
I  usually call this after running `tagme()` and since the fix I have since seen the error once, but otherwise it seems to be working. So that's not entirely helpful since the error should be gone entirely!

**Comment by steffilazerte** [comment]
Hmm, I guess something for me to look into then.

**Comment by jsayers-bsc** [comment]
Just had this again today. First two attempts to call `metadata(m)` resulted in the error, and the 3rd time worked. Whatever the cause it's not consistent. Nor is it the highest priority actually since "try again" works most of the time.

**Comment by steffilazerte** [comment]
I've merged in the hotfix and I think I'll close this issue for now. Let me know if it becomes problematic, or if you have any more specifics. Thanks!
