### ISSUE TITLE
adding a link to view individual tag track from the tag deployment page

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#93]
I don't see a link to the view track page from here. We should add it.

https://motus.org/data/tagDeployment?id=12046

**Comment by denislepage** [comment]
I guess I was looking at tags that didn't have tracks. Not having the same options visible makes things very confusing though, if there are no track to display, we should have a line that says that there are no detection in place of the line that offers to see them in a table, a timeline or a map.

**Comment by Hussell** [comment]
https://beta.motus.org/data/tagDeployment?id=12045
