### ISSUE TITLE
Sometimes Web Interface can be accessed through sg.org/status; often it cannot

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#931]
Often when clicking the serial number of of a networked SG, you can access the Web Interface remotely. But just as often, there is either nothing there or an error. The SG may still be syncing properly with no issue so it doesn't seem to indicate any larger problem, just that the Web Interface can't be accessed. Anyone know why this might be? @dfloer perhaps? 

![sgstatus](https://user-images.githubusercontent.com/55001144/111877094-04877880-8978-11eb-9ea7-098ab50dc069.jpg)

**Comment by dfloer** [comment]
I've noticed this as well, and I'm not sure what causing it. There's nothing helpful hitting the logs on sg.org, and restarting the server does not seem to clear the issue up.

I spot checked about 15, and I was only able to connect to half of those. I'll look into this more.

**Comment by StuMackenzie** [comment]
This must have been brought up before - can we integrate into another git, or an ongoing list of sensorgnome issues to resolve? Just want to cleanup git.

**Comment by j-sayers** [comment]
This may be related to a missing patch. There was a patch in 2019-04 that addressed "problems with connecting to the new sensorgnome.org server". This is often not re-installed along with fresh software. Closing for now.
