### ISSUE TITLE
Lotek Automated Registration email notifications

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#932]
Forgive me if I didn't follow along well enough when we discussed this.

I think we've already resolved this?, but another example of a researcher that received an email (apparently to you guys as well) from us confirming lotek registration.

I think we've fixed this, but is it possible to figure out who received these notifications? I just want to make sure we close all the loops. I caught this one by luck.

Thanks

-----Original Message-----
From: Lucy Mitchell [mailto:Lucy.Mitchell@hull.ac.uk] 
Sent: Monday, March 22, 2021 4:52 AM
To: Stuart Mackenzie <smackenzie@birdscanada.org>
Subject: FW: Motus Tag Registration Report: null

Hi Stu,
This is the email I got - it is from Birds Canada rather than Lotek, I couldn't remember... 

So I will follow the 'normal' registration procedure then - I haven't done it before but I'm hopeful I'll be able to navigate the Motus instructions!

Will certainly keep you in the loop re funding, and you're right, the education info on the Motus website is really useful. Perhaps we can work together to create a European focused example or something? T 

Best wishes,
Lucy

Dr Lucy Mitchell
Postdoctoral Research Assistant Ornithological Migration Department of Biological and Marine Sciences University of Hull
HU6 7RX

https://www.researchgate.net/profile/Lucy_Mitchell11
https://www.linkedin.com/in/lucy-mitchell-2b979955/
@lucyjayneryan
https://univhullornithgroup.wixsite.com/horc

-----Original Message-----
From: no-reply@birdscanada.org <no-reply@birdscanada.org>
Sent: 25 February 2021 14:04
To: Lucy Mitchell <Lucy.Mitchell@hull.ac.uk>; paul@ravenforge.ca; dlepage@birdscanada.org; cjardine@birdscanada.org
Subject: Motus Tag Registration Report: null

The Motus toolkit is acknowledging successful Lotek tag registrations.

Tag ID: 22
	Success

Tag ID: 44
	Success

Tag ID: 23
	Success

Tag ID: 45
	Success

Tag ID: 24
	Success

Tag ID: 46
	Success

Tag ID: 25
	Success

Tag ID: 47
	Success

Tag ID: 26
	Success

Tag ID: 27
	Success

Tag ID: 28
	Success

Tag ID: 29
	Success

Tag ID: 30
	Success

Tag ID: 31
	Success

Tag ID: 32
	Success

Tag ID: 33
	Success

Tag ID: 34
	Success

Tag ID: 35
	Success

Tag ID: 36
	Success

Tag ID: 37
	Success

Tag ID: 38
	Success

Tag ID: 39
	Success

Tag ID: 40
	Success

Tag ID: 41
	Success

Tag ID: 42
	Success

Tag ID: 21
	Success

Tag ID: 43
	Success

**Comment by pmorrill** [comment]
We did fix this, yes. The change went in on Feb 25th late afternoon, and would have been built into the sandbox the next day - most likely.

**Comment by cjardine-bsc** [comment]
@StuMackenzie I sent you the list of emails.

**Comment by StuMackenzie** [comment]
beauty - thanks all
