### ISSUE TITLE
Small Web Tweaks

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#933]
Apparently Zoe still works for us :-) She just sent me the below notes on the Motus Website. @leberrigan I'm just going to leave these here.....

* [x] Clicking the resources tab brings you here(https://motus.org/guides/)  which doesn’t have a link to the swanky new sensorgnome guide(https://docs.motus.org/sensorgnome/) , to get the guide you have to select Motus Guides from the Resources drop down menu
* [x] On the Receiver Deployment (https://motus.org/receiver-deployment/) page, the link for “Download Data from SensorGnome” takes you here (https://archived.sensorgnome.org/Download_data_from_a_SensorGnome/), I was originally reviewing this before I stumbled on the new updated guide
* [x] On the troubleshooting guide page, when following the selection Receivers > Equipment > Sensorgnome (also should be SensorGnome), the link for sensorgnome.org takes you to an error page (https://motus.org/troubleshooting-guide/archived.sensorgnome.org/) 
* [x] The receiver Equipment (https://motus.org/equipment/)  page has a broken link for the “Motus currently supports SensorGnome…(https://archived.sensorgnome.org/t_blank)”

**Comment by leberrigan** [comment]
Thanks Zoe! I'll get on those
