### ISSUE TITLE
Display Band Number, not Marker Number on Tag deployment page.

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#934]
eg. https://motus.org/data/tags/edit?projectID=231&id=43395

![image](https://user-images.githubusercontent.com/21124211/112399557-d2aa4500-8cdc-11eb-91f1-0dbe14c1953c.png)

The summary box at the bottom - marker type and number should just be replaced with band number. I think this is a @pmorrill ?

Thanks

**Comment by pmorrill** [comment]
Stu: take a look at the new version of this page. EG:

https://sandbox.motus.org/data/project/tags?projectID=3

The new table is simplified. But, the headings are up for discussion. Band could be added below the species?

**Comment by StuMackenzie** [comment]
Thanks Paul, that's great! Sorry I should have checked sandbox first. Band number isn't necessary in these summaries.
