### ISSUE TITLE
Software Reuse

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#936]
Any edits to the following statement on how Motus: Promote re-use of previously developed tools to minimize the costs of software development prior to the start of research.

We have extensively relied on existing software and   standards to enable our platform.    
      
1.       Debian Linux operating system, on both the   SensorGnome.org server and on the beaglebone computer in each   SensorGnome.  We use the operating   system itself, as well as some of the scripting and development tools (GNU   G++, bash, python) that are bundled with it.    http://debian.org   

2.        nodejs javascript engine for overall control of SG, web   interface etc.  https://nodejs.org  

3.       VAMP audio processing plugin framework www.vamp-plugins.org/develop.html.   This is the framework for building our signal processing plugin, which runs   in either audacity (below) or our own custom realtime host (vamp-alsa-host),   below. We have a custom plugin for detecting pulses from telemetry tags.  
 
4.       vamp-alsa-host - custom host for VAMP plugins; runs on   beaglebone, and processes signal on all attached usb audio devices by   applying plugins to input streams; low latency.   

5.       Audacity - audio editing/processing program http://www.audacityteam.org/, for   end-user tag registration, and in-house development and testing of signal   processing plugins.  

6.       find_tags / filter_tags: custom code for processing   output of either SensorGnome signal processing or Lotek receiver data.  The basic logic in both cases is to find   "convincing" runs of detections of tags registered with us.   

7.       chrony - high precision clock-synchronization software http://chrony.tuxfamily.org/; maintains   system clock sync with GPS time to the extent permitted by choice of GPS (USB   or cape with PPS).  

8.       gpsd - talks to the GPS and serves fixes; http://www.catb.org/gpsd/   

9.       sqlite: database for organizing server-side data in   single files http://sqlite.org   

10.    mysql: database for hosting tables of data at Acadia   University http://www.mysql.com   

11.    Microsoft SQL Server, currently supporting BSC’s National   Data Center   

12.    R: most server-side data processing is done by scripts or   packaged functions in R; we make significant use of the packages RSQLite,   dplyr, lubridate, lattice. http://r-project.org
--

**Comment by dfloer** [comment]
13. Hugo: Static website generator used to generate the sensorgnome website. https://gohugo.io/
14. Nginx: Webserver, used to server the sensorgnome website. https://www.nginx.com/
15. OpenSSH: Secure, remote access for sensorgnomes. https://www.openssh.com/
16. hostapd: Software to use wireless hardware as an access point for connecting directly to a sensorgnome. https://w1.fi/hostapd/

**Comment by leberrigan** [comment]
18. D3: a JavaScript library for manipulating documents based on data: https://d3js.org/
19. Leaflet: the leading open-source JavaScript library for mobile-friendly interactive maps: https://leafletjs.com/
20. JQuery: a JavaScript library designed to simplify HTML DOM tree traversal and manipulation, as well as event handling, CSS animation, and Ajax: https://jquery.com/
22. PDFKit: A JavaScript PDF generation library for Node and the browser: https://pdfkit.org/

**Comment by StuMackenzie** [comment]
Should we list gitbook?

**Comment by denislepage** [comment]
gitbook is not quite a software, but @steffilazerte  may have some additions to the list of software tools that she uses to create the builds. Here's a list that are connected to our github account. Not sure there's anything else on her end. Steffi, if you are able to provide a short 1-line description of what each of them does, that would be helpful.

Travis CI for Open Source
AppVeyor CI
AppVeyor
Trello GitHub Integration
FastHub 

Oh, and I guess we never included Java stuff!

Java JDK
Apache Commons Libraries: codec, compress, fileupload, io, lang, logging, math, httpcomponents
Apache Tomcat Server
mssql-jdbc: A java JDBC driver
aws-java-sdk: Java client tools for Amazon Web Services integration
Windows Server
Windows Internet Information Services (IIS)

**Comment by steffilazerte** [comment]
I'm not sure it's useful to have Travis (I'll probably be removing it soon) and I don't use Trello or FastHub. In general we use "Continuous integration for automated package tests (AppVeyor and soon, GitHub Actions)"
