### ISSUE TITLE
Adding NTP-1 (NanoPin) to tag model list

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#939]
Project 113 is planning on deploying [NanoPins (the .13 g Lotek on bumblebees)](https://www.lotek.com/wp-content/uploads/2020/11/NanoPin-Spec-Sheet.pdf). However this tag model is not yet in the list.

**Comment by Hussell** [comment]
The new model number is "NTP-1". The battery is new as well, I'm calling it "NanoPin" for now. I've updated sgdata. lk_tag_models needs a new row, and that should be all.

**Comment by cjardine-bsc** [comment]
done.

**Comment by Hussell** [comment]
lifespan_buffer probably needs to be 1.50.

**Comment by cjardine-bsc** [comment]
Done.
