### ISSUE TITLE
Motus R Book: Explaining signal strength vs. time plots

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#940]
While quite useful, we don't actually explain anything about the Signal Strength vs. Time plots in the R book. Instead, they are introduced abruptly in [Chapter 5.7](https://motus.org/MotusRBook/dataCleaning.html#ambigs) for identifying ambig tags. 

I have had to explain the utility of these plots a few times now and to me it seems like it should part of Chapter 3 or even a chapter of its own.

Use cases (those in bold are already included in R book):
- Differentiating between false short runs and fly-bys 
- Identifying flights
- Characterizing active and rest periods
- **Identifying the direction of flight**
- **Identifying ambiguous detections**

**Comment by StuMackenzie** [comment]
Why don't you add this to #900 and integrate #918. We need to identify a champion to start making these changes.

**Comment by leberrigan** [comment]
Closed in deference to #941
