### ISSUE TITLE
Long term solution for Western Hemisphere birds on European receivers

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#942]
The problem of Western Hemisphere tags being "detected" on European receivers comes up often, and it's an ongoing issue. Again today Project 113 reached out with [another case of this happening](https://motus.org/data/receiverDeploymentDetections?id=7612). This can be avoided if all relevant metadata is updated and fully propagated through the database prior to any receiver data being uploaded. But in reality there are going to be many cases where the European receivers still default to the Western Hemisphere frequencies, especially for projects like 113 which have scores of internet connected receivers, which are often being moved around with new deployments being created.

If we can't prevent it from happening entirely, is there any long-term solution we can implement that will at least resolve this shortly after it occurs -- before it's noticed by the collaborators and has to be brought to our attention? I think Jeremy already has a white-list of projects but the process of fixing or screening these receivers doesn't seem to fire all the time, or frequently enough. Is it practical to use something like a database trigger that fires whenever tag in say, taghits_runs with a nominal frequency of 166.38 is associated with a sensor from a project_id in the whitelist? Maybe that's not practical, but it seems like we should tweak something in how these are being dealt with.

**Comment by Hussell** [comment]
#784

**Comment by jsayers-bsc** [comment]
Is there a way we can at least deal with this retroactively on a more regular basis? Looking for sensors belonging to whitelist projects that have detected 166 tags seems like it would give a list of receivers to be addressed. That only happens _after_ the receiver has detections incorrectly assumed to be 166 MHz, but if we could look for this say daily, we could at least resolve it prior to it being noticed by project collaborators. Is something like that easy to do? 

select distinct(sensor_id) from det_taghits_runs a
left join tags b on b.id = a.tag_id
left join sensors c on c.id	= a.sensor_id
where c.project_id = 113 and nom_freq = 166.38

**Comment by jsayers-bsc** [comment]
Closing to keep the discussion in #784
