### ISSUE TITLE
Add Bombus terrestris to Species List

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#943]
That's right, a new species tagged and tracked in the Motus system!

**Comment by cjardine-bsc** [comment]
What common name would you like? buff-tailed bumblebee or large earth bumblebee

**Comment by jsayers-bsc** [comment]
Funny, "large earth bumblebee" sounds like a bad translation error. But apparently that is one of common names! I'm not sure what the most commonly used name is but for what it's worth, it was referred to as "buff-tailed" by the project tagging it.

**Comment by cjardine-bsc** [comment]
It sounds like a video game baddie. 

added.
