### ISSUE TITLE
Tags detected locally on receiver, but not on website or in R

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#946]
Project 113 recently deployed about 10 of the new NTP-1 tags on bumblebees next to a receiver. These are showing up locally on the receiver, but there are no detections in Motus.org or in the data in R. It doesn't appear to be a default frequency issue as there are no receivers in this project at the moment with detections of 166 tags. Is there any reason to expect these tags to be identified locally but not on the server? Even though they have short battery life, that all still looks good...

The tags in question: https://motus.org/data/projectTagDeployments?q=bomb&f=1&n=100&o=0a1a2a3a4a5a6a&id=113

The receiver in question: https://motus.org/data/receiverDeployment?id=5464

Screenshot of them seeing the tags locally on the receiver:

![df](https://user-images.githubusercontent.com/55001144/114042312-5161bf00-9853-11eb-9d19-3a411f5b9ae6.jpg)

**Comment by jsayers-bsc** [comment]
... Maybe this is default frequency thing actually since tags that don't have a corresponding 166 MHz counterpart currently active wont' show up anyway. @Hussell can you check the frequency of this receiver? **SG-0733RPI37C19**

**Comment by Hussell** [comment]
The frequency of the receiver is and has been correct for a long time. The bumblebee detections showed up when I reran the receiver. Possibly related to the tag registrations and adding the NTP-1 tag model?

**Comment by jsayers-bsc** [comment]
> 
> 
> The frequency of the receiver is and has been correct for a long time. The bumblebee detections showed up when I reran the receiver. Possibly related to the tag registrations and adding the NTP-1 tag model?

Yes and the receiver deployment has been active for a while and has already been detecting European tags. Wouldn't the proper tags show up a few days later though at least? Even if data from the first day of deployment needed to be reprocessed, data coming in a few days later should have been processed with all the correct metadata...?
