### ISSUE TITLE
create a map of tag deployment locations

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#95]
Having a map showing the location of tag deployments by project would be helpful to help clean the metadata. There seems to be more errors slipping in for tag than receiver deployments.

Here's one example where a map would highlight obvious problems where only some of the coordinates are being inverted.

select * from tags a inner join tags_deployments b on a.id = b.tag_id
where project_id = 57 and CAST(dt_start as date) = '2017-04-27'

**Comment by Hussell** [comment]
#86
