### ISSUE TITLE
missing text frag

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#950]
https://motus.org/data/tag/deployment/edit?projectID=1&id=27476

![image](https://user-images.githubusercontent.com/22172758/114771068-03e8c480-9d21-11eb-9e31-036139d09705.png)

@jsayers-bsc @pmorrill @leberrigan 

Can you sort out what information is supposed to be in this fragment and create it? Thanks!

**Comment by cjardine-bsc** [comment]
Another: 
![image](https://user-images.githubusercontent.com/22172758/114771550-8e312880-9d21-11eb-9b67-fa0d6c87a1d1.png)
https://motus.org/data/receiverDeployment?id=3454

**Comment by pmorrill** [comment]
> 
> 
> https://motus.org/data/tag/deployment/edit?projectID=1&id=27476
> 
> ![image](https://user-images.githubusercontent.com/22172758/114771068-03e8c480-9d21-11eb-9e31-036139d09705.png)
> 
> @jsayers-bsc @pmorrill @leberrigan
> 
> Can you sort out what information is supposed to be in this fragment and create it? Thanks!

I have added the fragment with simple text - but someone should re-wrod to reflect what it is really for. Go here to do that

https://motus.org/data/admin/tx_keys

**Comment by jsayers-bsc** [comment]
For the deployment summary and map popup there was nothing additional there previously, so I'm not sure what's missing.

![image](https://user-images.githubusercontent.com/55001144/114864697-4c56bf80-9dbf-11eb-93b8-39032ea2d012.png)

I updated the lifespan with "Estimate of battery life remaining for this tag"

**Comment by StuMackenzie** [comment]
Fixed? Close?

**Comment by leberrigan** [comment]
I have fixed the text fragments. Reopen if more are found,

> 
> 
> > https://motus.org/data/tag/deployment/edit?projectID=1&id=27476
> > ![image](https://user-images.githubusercontent.com/22172758/114771068-03e8c480-9d21-11eb-9e31-036139d09705.png)
> > @jsayers-bsc @pmorrill @leberrigan
> > Can you sort out what information is supposed to be in this fragment and create it? Thanks!
> 
> I have added the fragment with simple text - but someone should re-word to reflect what it is really for. Go here to do that
> 
> https://motus.org/data/admin/tx_keys
