### ISSUE TITLE
Increase character limit for Project names

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#951]
Currently there is a 50 character limit on project names. This is somewhat restrictive when it comes to descriptive names of projects, leading to AOU bird codes and other acronyms. We should increase this limit to allow projects to improve their names when it comes to citation (#910)

**Comment by cjardine-bsc** [comment]
I've given you 255 characters in Sandbox. Give it a test and if all looks good I can do the same in live.

**Comment by denislepage** [comment]
Are you nvarcharing this poodle (aka field)? We should probably anticipate some international collaborators requiring UTF-8 chars in things like project names, etc.

**Comment by cjardine-bsc** [comment]
nYou nBetter nBelieve nI nAm nvarcharing nIt.

**Comment by denislepage** [comment]
どうもありがとうございます

**Comment by cjardine-bsc** [comment]
どういたしまして

**Comment by jsayers-bsc** [comment]
Seems to work fine in Sandbox. In addition to accommodating our international collaborators, frazzled grad students can now include "¯\_(ツ)_/¯" in their project names if they so choose. Of course, we hope no one chooses to exercise this new power in that way.

I guess this is one of those areas where sandbox and live are not in sync. The test project I created is **Project 384 in Sandbox**, but in Live, project 384 is a legitimate project.

**Comment by cjardine-bsc** [comment]
Done in live. 

And yes, only tag_ids and device_ids are synced between the two databi.
