### ISSUE TITLE
Harmonize time zones in public detection outputs

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#953]
Sometimes the dates displayed in the public detection summaries aren't consistent between the different views (Table, Timeline, Map) are offset by 1, as if the Timeline view is using local time zone whereas the two other views are using UTC which sometimes bumps the date. 

![image](https://user-images.githubusercontent.com/55001144/115074497-c4a8a800-9ec7-11eb-984e-315d3ff5a655.png)

![image](https://user-images.githubusercontent.com/55001144/115074524-cf633d00-9ec7-11eb-9d23-969be06a3c5e.png)

**Comment by leberrigan** [comment]
I think this is probably because the Javascript code used to print the times on the map are using the `new Date()` function which defaults to the client's time zone instead of UTC. This is going to be resolved with the explore dashboards anyways.
