### ISSUE TITLE
R package / API to catch incorrectly formated JSON values

### ISSUE THREAD

**Issue by steffilazerte** [MotusDev/Motus-TO-DO#955]
In exploring issues (e.g., #954), I've realized that the change in API to make JSON formatting more strict is now on beta  (and live?).  I think this is creating problems that I'm rushing to fix.

This change results in some calls returning errors (often the permissions error, like in #905) and some silently returning zero data (when they should return something).  I've gone through and changed parameters to stay boxed where errors or missing data were returned, but my approach is slightly half-hazard. I'm not sure which JSON values need to be unboxed, and which should be left alone. Are numeric values unboxed, but strings boxed? 

I'm implementing more API entrypoint tests in the package which should also help, but I'm not sure it's enough. Is there a way for the API to return a warning/error if it receives an invalid value? That would help prevent things like this happening quietly in the future!

**Comment by cjardine-bsc** [comment]
Tagging @pmorrill 

We can also revert the live build if needed.

**Comment by steffilazerte** [comment]
@cjardine-bsc, for testing purposes, do you know of a projectID that would return data from "custom/project_ambiguities_for_tag_project"? This is the only remaining API point for which I can't see to get data. Thanks!

**Comment by pmorrill** [comment]
I have no idea what changes in the api you are referencing..... Not even sure what the 'boxing' vs unboxing terms are referring to in this instance.

Do the issues originate with how the API parses your request objects? Can you give me a specific example?

**Comment by cjardine-bsc** [comment]
These projects should have data in vwR_Tags_for_ambiguities (there are 120 f you need more, I just grabbed the first few). 

1
3
4
9
11
14
19
20
21
22
25
27
29
32
35
37
38
40

**Comment by steffilazerte** [comment]
Hi @pmorrill sorry for the ambiguity!

The changes are ones we talked about in #905 (specifically in your comment [here](https://github.com/MotusDev/Motus-TO-DO/issues/905#issuecomment-773389835)) making the JSON requirements more strict?

Unboxing/boxing is a term used by the packages I use in R for converting to/from JSON, it essentially means putting [ ] (boxing) around parameter values. 

#905 is a specific example a error message (originally not very helpful, but it made sure I tracked it down!) 

A specific example of a silent problem on beta for `/api/sgdata/custom/metadata_for_tags` is:

**Good:** (returns data)
`{"authToken":"XXXXX","dataVersion":2,"motusTagIDs":[29876]}`

**Bad:** (silently returns empty data)
`{"authToken":"XXXXX","dataVersion":2,"motusTagIDs":29876}`

If it isn't possible to return errors, I definitely understand, but it'd be so nice if the API actually errored in the second case as I'm not always sure when data is supposed to be returned or not.

I *think* I've got tests set up which all return data, so I should be able to see if things change in the future, but I'd feel better if I knew I'd get an error message if the package sent the wrong data.

**Comment by steffilazerte** [comment]
Alternatively, it just occurred that this might be something I can deal with completely on R side. If an API query is successful but returns zero data, will it return empty but named lists/arrays? 

In that case I can just test for named returns, even if they're empty and that would solve a lot of the problems.

**Comment by pmorrill** [comment]
The example mentioned above should be returning an empty object if the motusTagIDs param is not boxed as a json array. There are no attributes on the returned object.

IN another case, the call to 'deviceID_for_receiver' will actually return an error if the serno parameter is not a json array. But I see that actual error code is no in the live system. I will add the error return for this specific case.

It may be a little tricky to treat them all the same way at the moment (ie: throwing an error). But it could be done.

Here is a list of the calls that expect a 'boxed' parameter:

- deviceID_for_receiver => 'serno'
- metadata_for_receivers => 'deviceIDs'
- metadata_for_tags => 'motusTagIDs'
- recv_metadata_for_projects => 'projectIDs'
- tag_metadata_for_projects => 'projectIDs'

**Comment by steffilazerte** [comment]
That's enormously helpful, thanks @pmorrill! I will use the lack of attributes as another indicator, that will definitely help. 

@cjardine-bsc I don't think that's what I'm looking for (although having this is helfpul for other things, so thanks!).

Specifically, however, there's an API point called `custom/project_ambiguities_for_tag_project` that takes the project ID that you're currently working with and is supposed to return any existing projectIDs that are "ambiguous detection projects" (stored in the SQLite table `projAmbig`), this is used in the tag database update, although I don't think I've really seen it in use. Does that make sense?

**Comment by steffilazerte** [comment]
@pmorrill Turns out that I really needed your list of calls that expected boxed parameters, `recv_metadata_for_projects` and `tag_metadata_for_projects` both return all data when the parameter is unboxed (i.e. interpreted as blank), so I wouldn't have been able to detect it.

Anyway, my server tests are set up and all functioning and I've fixed all the problematic calls. I'm feeling good about being able to catch problems in the future. I'll push this to a hotfix branch so we can test and get it out there.

**Comment by cjardine-bsc** [comment]
> 
> 
> That's enormously helpful, thanks @pmorrill! I will use the lack of attributes as another indicator, that will definitely help.
> 
> @cjardine-bsc I don't think that's what I'm looking for (although having this is helfpul for other things, so thanks!).
> 
> Specifically, however, there's an API point called `custom/project_ambiguities_for_tag_project` that takes the project ID that you're currently working with and is supposed to return any existing projectIDs that are "ambiguous detection projects" (stored in the SQLite table `projAmbig`), this is used in the tag database update, although I don't think I've really seen it in use. Does that make sense?

huh....That makes sense, I'm not 100% sure which view that is using, but I can give you an example that should return a record. 
Project 74 should have ambiguous detections shared with project 262. (TagIDs 26751, 35365)

**Comment by pmorrill** [comment]
> Specifically, however, there's an API point called `custom/project_ambiguities_for_tag_project` that takes the project ID that you're currently working with and is supposed to return any existing projectIDs that are "ambiguous detection projects" (stored in the SQLite table `projAmbig`), this is used in the tag database update, although I don't think I've really seen it in use. Does that make sense?

This entrypoint always returns a set of empty project arrays. I am not sure why we support it at all, but we do...

**Comment by steffilazerte** [comment]
Hmm, well I guess I don't need to test that then!

**Comment by steffilazerte** [comment]
Fix pushed to master v.4.0.6
