### ISSUE TITLE
Switch database connection from dbplyr::src_dbi() to DBI::dbConnect()

### ISSUE THREAD

**Issue by steffilazerte** [MotusDev/Motus-TO-DO#957]
`tagme()` currently uses `dbplyr::src_dbi()`, but I think we should switch to `DBI::dbConnect()` fir several reasons:

1. `dbplyr::src_dbi()` is [no longer recommended ](https://dbplyr.tidyverse.org/reference/src_dbi.html)
2. `DBI::dbConnect()` is the standard way of working with databases in R, but has different behaviour from `dbplyr::src_dbi()` which may cause confusion and makes coding more complicated

For example, to work with a database loaded with `tagme()` using DBI, we need to use the `$con` part:
```
> tags <- tagme(176, update = FALSE, new = FALSE, dir = "..")

> dbListTables(tags)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbListTables’ for signature ‘"src_SQLiteConnection"’

> dbListTables(tags$con)
 [1] "activity"    "activityAll" "admInfo"     "allambigs"   "allruns"     "allrunsGPS"  "alltags"     "alltagsGPS" 
 [9] "antDeps"     "batchRuns"   "batches"     "clarified"   "filters"     "gps"         "gpsAll"      "hits"       
[17] "meta"        "nodeData"    "nodeDeps"    "projAmbig"   "projBatch"   "projs"       "recvDeps"    "recvs"      
[25] "runs"        "runsFilters" "species"     "tagAmbig"    "tagDeps"     "tagProps"    "tags"       
```

On the other hand, if we connect to the data base with DBI, we don't need to use the `$con` (but we get an error if we do)
```
> tags <- dbConnect(RSQLite::SQLite(), "../project-176.motus")

> dbListTables(tags)
 [1] "activity"    "activityAll" "admInfo"     "allambigs"   "allruns"     "allrunsGPS"  "alltags"     "alltagsGPS" 
 [9] "antDeps"     "batchRuns"   "batches"     "clarified"   "filters"     "gps"         "gpsAll"      "hits"       
[17] "meta"        "nodeData"    "nodeDeps"    "projAmbig"   "projBatch"   "projs"       "recvDeps"    "recvs"      
[25] "runs"        "runsFilters" "species"     "tagAmbig"    "tagDeps"     "tagProps"    "tags"       

> dbListTables(tags$con)
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'conn' in selecting a method for function 'dbListTables': $ operator not defined for this S4 class

```

I think it would be best if the connections returned by `DBI::dbConnect()` and `tagme()` were the same so users could work with what ever made sense and didn't have to do anything special to use other DBI functions.

Further, right now if users less familiar with R are trying to look at their motus data base using DBI, any instructions they find specific to DBI won't work, which could be really confusing and frustrating. 

Although switching to `DBI::dbConnect()` internally may result in breaking some users existing code (e.g. the 2nd example above, with `dbListTables(tags$con)`), I still think it's a better solution in the long run.

@denislepage, @StuMackenzie, @leberrigan and whomever else... what do you think?

**Comment by denislepage** [comment]
Keeping the packages up to date generally makes sense. I’d be useful for me to understand better the implications and how to could potentially impact people’s code.

Can’t tagme return the connection object ($con) in place of its container?

**Comment by jsayers-bsc** [comment]
Yes the difference can be confusing and it would be nice if they were both the same, without the need to use a different method depending on how the database is loaded.

The R Book already provides the `dbConnect()` and a SQLite connection to the local database as the example for listing tables.

> specify the filepath where your .motus file is saved, and the file name.
> file.name <- dbConnect(SQLite(), "./data/project-176.motus") 
> 
> get a list of tables in the .motus file specified above.
> dbListTables(file.name) 

Hard to say how many people are using `tagme()` and then specifying $con to list the tables, but most of them will have arrived at that on their own and should be able to negotiate the change without too much difficulty.

And scripts that use `tbl()` shouldn't be affected anyway since that works the same with both methods of connecting to the database. So the impact of the change on people's scripts might not be that significant.

**Comment by steffilazerte** [comment]
Thanks @jsayers-bsc, that's exactly it! :grin:

@denislepage 
> Can’t tagme return the connection object ($con) in place of its container?
It could but this would result in the exact change I want to make but would use the workflow similar to dbConnect -> src_dbi -> dbConnect, so it's easier to just use dbConnect in the first place. 

- I don't think there's any benefit to using `src_dbi()`
- This will only affect existing code if people use DBI functions. AND, as @jsayers-bsc said, if they do, they've already figured out how to make it work with our non-standard method, so my proposed change (going back to a standard method), shouldn't be too difficult to navigate.

Currently, if you want to use `DBI::dbListTables()`, you either have to use `DBI::dbConnect()` first, or you need to use `$con`
```
tags <- tagme(...)
dbListTables(tags$con)
```
I propose changing things internally so this would work:

```
tags <- tagme(...)
dbListTables(tags)
```

This means that existing code (`dbListTables(tags$con)`) would result in an error, but one that is easily fixed by removing `$con`. 

I could also create a package loading message alerting users to this change, but I think that might just confuse people (because I doubt this will affect too many people).

**Comment by leberrigan** [comment]
@j-sayers can we re-evaluate? Should this be re-opened?

**Comment by steffilazerte** [comment]
This is still something I think should be done, should I move it to the motus package repo issues? Once agreed that it should be done, (have we?) It's only really relevant to me...?

**Comment by steffilazerte** [comment]
Okay, I want to make this change, @denislepage, @j-sayers, @leberrigan any objections to me going ahead with this? The above points for why this is a good idea still stand, but since it is a reasonable large change, I want to confirm before I get started.

Okay to go ahead?

**Comment by steffilazerte** [comment]
Awesome, I'll get started on a new branch based on master (using the current API as this only affects the package). For my benefit (and others), this is the to do list:

**Package changes**
- [ ] Update `motus` to use `DBI::dbConnect()` instead of `dbplyr::src_dbi()`
- [ ] Find and remove all references to `dbplyr` (shouldn't be required any more)
- [ ] Update all references to `XXX$con` to simply `XXX` in `motus` package
- [ ] Make sure all tests work
- [ ] Ask for team testing

**Documentation**
- [ ] Update all references to `XXX$con` to simply `XXX` in documentation
- [ ] Add note to docs referencing this change, why and what it means
- [ ] Review docs (perhaps with input from @ajmacdonald3?)

**Dissemination**
- [ ] Email Motus list about changes (probably minor part of a larger update email)
- [ ] Consider adding temporary note to motus package notifying users of the change (as a rule, best to try and avoid start up messages but it's not too bad and can be useful in these situations):

```
> library(motus)
motus v6.0.0
Database connections have been updated.
If you use `XXX$con` notation, note that the `$con` is no longer required.
Release notes: https://motuswts.github.io/motus/news
```

**Comment by steffilazerte** [comment]
Hi @denislepage, @j-sayers, @ajmacdonald3 (ping others if you think they should check this too)

I've made the changes to the package to use the standard `DBI::dbConnect()`, as well as some other best practices and code clean up changes: https://github.com/MotusWTS/motus/pull/18

To a general user, there should be no difference. To users who used DBI functions on tagme objects, they will get an error if they try to use `X$con` to reference the connection (it should be just `X` now). 

In the documentation, the NEWs will have this change, but we never use the `X$con` notation in the articles, so there was nothing to change. 

I'm away until September, but if possible could you install and check the following:

`remotes::install_github("motusWTS/motus", ref = "dev-dbConnect")`

1. Do you run into any problems with using the package?
2. Do you think we need a startup message warning users (e.g., [bottom of the above comment](https://github.com/MotusDev/Motus-TO-DO/issues/957#issuecomment-1176658062))
3. Can I merge when I get back? 
4. Does someone need to add details to an email for users so they know?

I'll nudge you all when I get back :wink:, thanks!

**Comment by leberrigan** [comment]
Thanks Steffi! I've assigned three of us to this task - if any of us have time to test this in the next couple weeks it would be good to provide some feedback here so Steffi has an update to work off of upon returning.

**Comment by j-sayers** [comment]
I've spent just a bit of time with this but so far it's working well. I do like being able to quickly access without adding the `$con` portion, or even when viewing table structure with `DBI::dbListFields`.

**Comment by steffilazerte** [comment]
Okay, sounds good, unless I hear otherwise I'll release the new version of motus on Friday and start working on the next round of items to address.

**Comment by steffilazerte** [comment]
This release also includes the hot fix for #1233

**Comment by denislepage** [comment]
We can discuss on our weekly call tomorrow. The only outstanding question is whether/how we should also people that the way to access the connection object has changed. Has the book been updated accordingly? If so, we may need just a post on the motus group.

**Comment by steffilazerte** [comment]
There was nothing to update in the book as we don't teach the use of the `DBI` package (which is the only thing that would have changed)

**Comment by denislepage** [comment]
Sounds good. I think we’re ready then, whenever you are.

The connection change should only affect a few people, and is easily resolvable.

If you are able to do the release note as suggested above, that would be great.

motus v6.0.0
Database connections have been updated.
If you use `XXX$con` notation, note that `$con` is no longer required.
Release notes: https://motuswts.github.io/motus/news

It says no longer required, but that makes it sounds like it will still work. Perhaps something like this instead:

motus v6.0.0
Database connections have been updated.
If you use `XXX$con` notation, note that `$con` should no longer be used.
Release notes: https://motuswts.github.io/motus/news


We can also circulate a note to the listserv. Are there other new features worth highlighting in that note?

**Comment by steffilazerte** [comment]
Good idea, just to be clear, you mean as a release note that would go [on the website](https://motuswts.github.io/motus/news/index.html) and in the [NEWS.md](https://github.com/MotusWTS/motus/blob/master/NEWS.md) file, not a note that would pop up in R ever time a user loads the package, right?

As for other things to highlight, I've standardized the documentation a bit and the messages, fixed a bug, and made some internal changes (see the [complete list](https://github.com/MotusWTS/motus/pull/18/files#diff-51920e95310ebfbc1ae31709f3b95f89afffbf4f1a6e38e8b2b406e2fb6197ea)), but nothing crazy or really note worthy.

**Comment by denislepage** [comment]
I was thinking a note that would come up during the install or update. Not every session, correct.

If that’s not possible, we can do without.

I am assuming that the new dependent library will automatically be installed as needed and that there is nothing different they should have to do.

Let me know once you have deployed, I can send a quick note to the group about the $con change

**Comment by steffilazerte** [comment]
Done! Merged to master and created the release, the website is compiling now (which can take a while), but the package is ready to go.

**Comment by cjardine-bsc** [comment]
@steffilazerte  I'm closing, feel free to re-open if there are still outstanding items here.
