### ISSUE TITLE
Networked SG not syncing data; likely has SD card from another SG in it

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#959]
Project 113 has a networked that is not syncing properly. The status page shows connected status as "No", though it appears to be regularly connecting based on the up-to-date time. However the last data sync is over a month ago.

![image](https://user-images.githubusercontent.com/55001144/116692176-f6227880-a989-11eb-8807-d64cf8314323.png)

They are fairly certain that the used an SD card that contained data from another SG, so this is possibly similar to #812. The obvious solution is to create a fresh software card and reconnect, but this is a remote station that is not easy to get to. It sounds like previously John reset the key-pair in a similar situation, though I'm not sure if that's an option here. @dfloer is this something you can look into from the sg.org side?

**Comment by dfloer** [comment]
I did not change anything on this. Part of the cause seems to be a mismatch on sgdata.
