### ISSUE TITLE
Increasing frequency that tag database is provided to tag finder

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#961]
Just wanted to make a specific issue related to our call yesterday so it doesn't get lost. Specifically modifying the frequency at which tag deployment metadata is passed to tag finder. 

- How long does the process take, and does it lock the database for any significant period of time?
- If the procedure is speedy, how frequently can we set this process to run? -- hourly, every 15 minutes?

This will help circumvent issues where researchers update their tag deployments on or around the time they are actually deployed and then miss early detections on the first pass (e.g. Project 113). But once Lotek tags are all automatically registered, "anticipated deployment dates" will likely be a thing of the past. We may end up relying exclusively on deployment dates, and will want tag finder to have the most up-to-date list possible

**Comment by Hussell** [comment]
Testing with hourly updates has had a few minor hiccups, but nothing that looks like it could prevent hourly updates from continuing indefinitely.
