### ISSUE TITLE
Setup test user

### ISSUE THREAD

**Issue by steffilazerte** [MotusDev/Motus-TO-DO#963]
@denislepage, @cjardine-bsc 

I've migrated `motus` to GitHub actions for remote testing, which makes it really easy for me to supply secrets (encrypted credentials).

Therefore I'd like to add the tests I run only locally (because they require my username and password) to these remote CI tests. 

To do that I want to set up a separate user (called `testuser`) with more privileges than `motus.sample` but fewer than mine. 

Should I create the user and then get you to add the permissions? Or how do I do this?

To work with the tests I have this user needs access to (let me know if that seems like too much and I can see if I can't pare it down):

- SG-1116BBBK0C40
- SG-3115BBBK0782
- SG-3115BBBK1127
- CTT-5031194D3168
- CTT-18BC3777F716
- CTT-867762040710391
- SG-BC3FRPI35A70
- 204
- 4
- 207
- 213
- 25

**Comment by denislepage** [comment]
If you want to create a new login on each sandbox and the main server and let us know, we can add the permissions. Permissions are assigned by project, so for receivers, it’d be better to select receivers in a couple projects to which we can give you full access. One of the motus projects, for instance.

**Comment by steffilazerte** [comment]
Okay, I created `testuser` on regular/beta (?) and sandbox

Can this user get access to these projects?
- 1
- 4
- 25
- 123
- 204
- 207
- 213
- 350

**Comment by steffilazerte** [comment]
Okay, I think I need some admin help (@cjardine-bsc, @denislepage), my sandbox `testuser` was never full activated because the link went to regular motus.org, not sandbox.motus.org. And now the link is expired and there's no way to re-initiate the email confirmation process. 

Can someone
- activate `testuser` on sandbox for me? 
- delete `testuser_sandbox` :grin:
- make sure that `testuser` main/beta and `testuser` sandbox have access to the above projects?

Thanks!

**Comment by cjardine-bsc** [comment]
Hey Steffi, Sorry I left you to languish, I was out of the office. 

Can you try to login as testuser on sandbox for me? 

For permissions, I noticed you're not currently on 350 , 204, 123 or 25 and these (to my limited knowledge) are not Birds Canada projects. Have we talked to the PIs about this? I don't want to add you to their projects in live without their knowledge (they will see this when viewing their collaborators list). I have added you there in sandbox though.

**Comment by steffilazerte** [comment]
Okay, thanks I can login!

As for permissions, I have no idea what project is Birds Canada and which is not. I generally choose projects based on the type of data they have so I can make sure that the R package works for all types of data. 

Can I get a list of which projects are Birds Canada ones? Then I can see which of those would be good for testing the project and then you can give the 'testuser' access to those.

Sound good?

**Comment by cjardine-bsc** [comment]
@StuMackenzie can you delegate someone to help Steffi sort out a list of projects I can add her to for this? Either by identifying projects that we already have relationships with or giving PIs a headsup that their project has been chosen for this purpose and they will see a "testuser" account registered to their projects?

**Comment by StuMackenzie** [comment]
I’d prefer just giving her access to all projects. Can we label the account Motus Test or Motus Admin, etc.,?

____________________

**Comment by cjardine-bsc** [comment]
She already has that with her own account. My understanding of this is based on Steffi's request below: 

I've migrated motus to GitHub actions for remote testing, which makes it really easy for me to supply secrets (encrypted credentials).

Therefore I'd like to add the tests I run only locally (because they require my username and password) to these remote CI tests.

To do that I want to set up a separate user (called testuser) with more privileges than motus.sample but fewer than mine.

**Comment by StuMackenzie** [comment]
Point being I think we can add / remove her to any project as we like/need. No need for correspondence with PIs.

Steffi - you should be able to add this account to any project you need from the manage projects pages/mange users. If you have any trouble let us know.



____________________

**Comment by steffilazerte** [comment]
Okay, I'll look into it and get back to you if I have problems. 

Is 'testuser' an acceptable name for this account? Or would you prefer 'motus_testing' or something similar?

**Comment by StuMackenzie** [comment]
We’re probably over thinking it - if test is in the title people will know it’s us. motus_testuser or motus_testing might remove any questions.

Thanks

S

____________________
