### ISSUE TITLE
Prevent end dates in the future (tag deployments)

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#964]
We've found more cases of people still entering an enddate for tag deployments. Even now that they get this nice little warning:

"You have entered an end date for this deployment. End dates should only be entered for tags that have been removed from the animal, otherwise please leave the end date blank. This tag has a remaining estimated lifespan of 0 days, If you have recovered this tag and do not intend to use the tag again please mark it as deprecated."

@pmorrill On the tag deployment management page (https://motus.org/data/tag/deployment/edit?projectID=1&id=27476) can we add a check that prevents people from entering an end date in the future? I'll do the same in the bulk tag deployment upload tool.

**Comment by jsayers-bsc** [comment]
#947 is related to this. Seeing a question mark as the end date for every deployment -- even those from many years ago -- may suggest to some users that proper metadata upkeep requires them to always populate end dates (even anticipated end dates apparently)

**Comment by pmorrill** [comment]
We do post an error when someone tries to enter a future deployment end-date. This is verified in the server side, and the data should not make it into the database. Is it possible these future end dates are all coming from the tag-deployment template upload?

I will add a client side check to the deployment mgmt page, to give them a more clear message when a future end date is attempted.

**Comment by leberrigan** [comment]
@cjardine-bsc I'm closing this because I'm under the impression that this has been resolved based on today's conversation - feel free to re-open if you think otherwise.

**Comment by cjardine-bsc** [comment]
Okay, yes. there should be a check in there that prevents tag end dates in the future. 

INSERT INTO api_errors (apiBatchID,rowNum,error_code,field_name)
SELECT @apiBatchID,rowNum,'api_value_dt',field_name
FROM #temp_ts
WHERE tsEnd > @dt 

Tested. 

![image](https://user-images.githubusercontent.com/22172758/167041609-743737e6-8524-4bac-951d-a128f2233afb.png)
