### ISSUE TITLE
Partial backlog of SensorStation data in Motus db

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#968]
A few projects, including us in Ontario, have noticed an apparent backlog of SS data coming into Motus. Many have no batches more recent than the 12th of May, though the most recent dates are spread over several days (the most recent for us is the 16th). However on the CTT portal these all seem to be connecting regularly. Other connected SS have up to date data. May be the same issue as #938 but in that I don't think there was any recent data for any SS, hence the new issue.

Most recent batch for active SS deployments. Not all are actually connected but most probably are.

receiverID | project_id | name | status | most_recent_batch
-- | -- | -- | -- | --
CTT-867459049219710 | 48 | LUZE04 | 2 | 2019-11-24 12:45:57
CTT-867459049274566 | 48 | Scott B. Rice | 2 | 2020-03-01 21:26:58
CTT-867459049265267 | 48 | SGL 037 | 2 | 2020-03-11 18:28:58
CTT-867459049297419 | 350 | Cheyenne Bottoms KWEC | 2 | 2020-05-05 18:26:59
CTT-141CD838369F | 48 | Cate's Hill | 2 | 2020-06-17 18:54:53
CTT-0F0EBA48F078 | 48 | Fields Pond Audubon Center | 2 | 2020-08-06 16:42:06
CTT-867459049219876 | 293 | South Cape May TNC Meadows | 2 | 2020-09-05 11:39:53
CTT-867762040731017 | 316 | Duke Farms | 2 | 2020-09-22 10:27:36
CTT-6359CF8E5007 | 210 | MO_MDCHUNNEWELL | 2 | 2021-01-27 15:41:48
CTT-233B3EC847A7 | 48 | Nassawango | 2 | 2021-02-23 13:39:18
CTT-B5A78CE7F3B3 | 213 | Rock Creek-IWC-MT | 2 | 2021-03-23 19:45:47
CTT-D6C8B82DD197 | 129 | Mirage | 2 | 2021-03-27 22:41:21
CTT-4BAEE4CF4A24 | 129 | ResearchPlot | 2 | 2021-03-27 22:41:56
CTT-867459049273626 | 292 | Bean House | 2 | 2021-04-02 17:30:21
CTT-6089B00BB4F3 | 129 | Felt | 2 | 2021-04-09 14:32:31
CTT-792C1C06A0AF | 48 | Princeton | 2 | 2021-04-16 17:52:13
CTT-309B92F8EB05 | 48 | Stutchbury | 2 | 2021-04-18 22:44:10
CTT-A8D3250A4A97 | 1 | Little McCoy | 2 | 2021-04-18 23:44:11
CTT-56EEA786B090 | 48 | Lake Shore Marshes WMA | 2 | 2021-04-27 18:42:11
CTT-51F5127F9A6E | 210 | MO_MDCPURDIN | 2 | 2021-04-28 05:50:31
CTT-7B06CF6C2AC8 | 210 | MO_MDCCOLLEGEMOUND | 2 | 2021-04-28 09:42:25
CTT-35055E7B4490 | 210 | MO_MDCHARTELL | 2 | 2021-04-28 09:43:39
CTT-40F188AEB096 | 213 | Fort Boise WMA-ID | 2 | 2021-05-03 00:04:49
CTT-090A15C0E6EB | 213 | APR - Dry Fork East -MT | 2 | 2021-05-03 06:17:48
CTT-7CD0F69282C9 | 48 | LACK04 | 2 | 2021-05-06 13:31:13
CTT-2512EF9F55F4 | 48 | Lambs Knoll | 2 | 2021-05-07 19:31:50
CTT-AD44FC306242 | 210 | MO_MDCANDERSON | 2 | 2021-05-12 01:36:54
CTT-63AF982C66EA | 336 | WilsonCreek | 2 | 2021-05-12 02:35:34
CTT-B7ADF108B991 | 48 | Ned Smith Center | 2 | 2021-05-12 12:42:56
CTT-9981E16B984D | 397 | Sublette Fence 4 - WY | 2 | 2021-05-12 12:53:23
CTT-42446DCD0910 | 1 | Shawanaga First Nation | 2 | 2021-05-12 14:29:54
CTT-F555703457AC | 48 | SGL 44 | 2 | 2021-05-12 14:33:53
CTT-6C563B01FF62 | 129 | Ice Cream | 2 | 2021-05-12 14:33:54
CTT-62543351AA11 | 129 | Redwing | 2 | 2021-05-12 14:33:55
CTT-6525AB2CE7B1 | 129 | O.R.B. | 2 | 2021-05-12 14:33:55
CTT-90E0546D9B4B | 129 | Blowdart | 2 | 2021-05-12 14:33:55
CTT-F21E1A341DB5 | 129 | Tumbleweed | 2 | 2021-05-12 14:33:55
CTT-74EC1C68761C | 129 | Nosebleed | 2 | 2021-05-12 14:33:58
CTT-97FB9AB20E31 | 1 | Thomson Reserve | 2 | 2021-05-12 14:34:05
CTT-CDE43745B223 | 1 | Grimsby Wetland | 2 | 2021-05-12 14:34:07
CTT-46E6DED067EE | 368 | Cypress Grove | 2 | 2021-05-12 14:34:09
CTT-37B65B47070F | 213 | McCauley Butte-Missoula-MT | 2 | 2021-05-12 14:34:11
CTT-E91F83776412 | 213 | Vesper Meadow-OR | 2 | 2021-05-12 14:34:14
CTT-5539D79D65BB | 336 | SydnTaraRule | 2 | 2021-05-12 14:34:16
CTT-7645B4C32B21 | 213 | Camas NWR 2-ID-IWC | 2 | 2021-05-12 14:34:16
CTT-EE2B5751C976 | 48 | Greenwoods Conservancy | 2 | 2021-05-12 14:34:16
CTT-D7D11D3641CD | 213 | Apricot Lane Farms-CA | 2 | 2021-05-12 14:34:17
CTT-E95B6FDAC170 | 48 | Wills Mountain | 2 | 2021-05-12 14:34:17
CTT-EBCAAFB4E66F | 48 | Fassler | 2 | 2021-05-12 14:34:17
CTT-462A274E4E94 | 281 | GPCD FCMoD | 2 | 2021-05-12 14:34:18
CTT-50C18EBCC29A | 336 | ProtectionIsland | 2 | 2021-05-12 14:34:18
CTT-96ADB4231B06 | 48 | Nahant | 2 | 2021-05-12 14:34:18
CTT-D631101D6DBD | 48 | Mount'n'Meadow | 2 | 2021-05-12 14:34:18
CTT-DB820D086E1C | 210 | MO_MDCCOLOMA | 2 | 2021-05-12 14:34:18
CTT-F193D3E840E8 | 48 | Pymatuning - Ford Island | 2 | 2021-05-12 14:34:18
CTT-A4EFE1E51B38 | 48 | Norman G. Wilder WMA | 2 | 2021-05-12 14:34:19
CTT-595E0609FDED | 48 | Town Hill | 2 | 2021-05-12 14:34:20
CTT-54AD06283ACC | 213 | Cold Water ITD- IWC-ID | 2 | 2021-05-12 14:34:21
CTT-91E34B0531B9 | 336 | SalmonRiverEstuary | 2 | 2021-05-12 14:34:21
CTT-E48EE7BAD584 | 48 | Arms 01 | 2 | 2021-05-12 14:34:21
CTT-29ABC1F8E4DA | 336 | EnglishmanEstuary | 2 | 2021-05-12 14:34:22
CTT-9BCCCC789422 | 48 | Thayerville | 2 | 2021-05-12 14:34:23
CTT-B050EC6F7787 | 48 | DWL Great Cypress Swamp | 2 | 2021-05-12 14:34:23
CTT-750514A28BD0 | 324 | EBF 2a | 2 | 2021-05-12 14:34:24
CTT-CEE71D75130F | 48 | Bear's Head | 2 | 2021-05-12 14:34:24
CTT-AC1278718014 | 48 | Phillips Exeter Academy | 2 | 2021-05-12 14:34:28
CTT-1B51CADBC2EF | 213 | WorldCenterForBirdsOfPrey3-Boise-ID | 2 | 2021-05-12 14:34:30
CTT-25E69BBEA4AD | 48 | Granite Lake Headwaters | 2 | 2021-05-12 14:34:32
CTT-DA63C3392B44 | 290 | Jennings Knob 2 | 2 | 2021-05-12 14:44:28
CTT-8279D1996694 | 48 | Franklin Parker | 2 | 2021-05-12 14:53:42
CTT-957865AC5BF7 | 247 | RTH SensorStation 1 | 2 | 2021-05-12 15:16:28
CTT-4CEC55B23E67 | 1 | Otter Lake | 2 | 2021-05-12 21:07:38
CTT-44223248A956 | 48 | Black Log | 2 | 2021-05-12 21:48:45
CTT-AF48CD0E4805 | 210 | MO_MDCPIGEONHILL | 2 | 2021-05-12 22:17:53
CTT-A794E5CA2CE4 | 48 | Utica Zoo | 2 | 2021-05-12 22:29:15
CTT-AE44767B1CC3 | 213 | Warm Springs ARCO-MT | 2 | 2021-05-12 23:15:55
CTT-2C7E930A32CA | 290 | Chestnut Mountain | 2 | 2021-05-13 01:43:20
CTT-CC506A073F27 | 213 | Kuna HighSchool 2-ID | 2 | 2021-05-13 04:23:10
CTT-5665244BE876 | 1 | Mallett | 2 | 2021-05-13 06:03:47
CTT-914C9A32A38E | 48 | Blue Marsh | 2 | 2021-05-13 08:06:23
CTT-D53C7198C4F0 | 213 | DeerFlatNWR-ID | 2 | 2021-05-13 08:27:29
CTT-C27A17D75091 | 129 | Ravensnest | 2 | 2021-05-13 10:57:23
CTT-C11B8A2EC307 | 48 | Plumer Fire tower | 2 | 2021-05-13 11:58:23
CTT-B4A6D702A864 | 48 | Buntings | 2 | 2021-05-13 13:46:04
CTT-B06D27D7B6D1 | 48 | Lupine Field | 2 | 2021-05-13 15:08:53
CTT-A325453C4420 | 48 | Poplar Island | 2 | 2021-05-13 15:27:33
CTT-72A787D1C983 | 1 | Test-C983 | 2 | 2021-05-13 16:11:35
CTT-3BA69B707BD2 | 1 | North East | 2 | 2021-05-13 16:35:15
CTT-C7CD0E6F7D6F | 48 | Upper &amp; Lower Lakes WMA | 2 | 2021-05-13 18:02:44
CTT-1F37905AE0DB | 290 | Bellamy 1 | 2 | 2021-05-13 21:45:56
CTT-E7BE27B8582A | 48 | Derby Hill Bird Observatory | 2 | 2021-05-14 11:04:49
CTT-115C42D7D4B2 | 368 | Toms Point | 2 | 2021-05-14 13:10:07
CTT-999F324263A2 | 1 | Sandy Island | 2 | 2021-05-14 16:44:45
CTT-3EBEF28F64C0 | 48 | Wellington | 2 | 2021-05-14 18:05:16
CTT-106A02AABC63 | 273 | Anderson Elementary Tower | 2 | 2021-05-14 19:04:01
CTT-F7A8ECC7315C | 397 | Sublette Fence 3 - WY | 2 | 2021-05-14 19:43:49
CTT-4EEED8B2208E | 48 | Big Pocono | 2 | 2021-05-14 19:56:25
CTT-19DD237FF696 | 48 | SGL 74 | 2 | 2021-05-14 19:57:46
CTT-E8E27D671819 | 332 | CTT AHATS #1 | 2 | 2021-05-14 22:41:44
CTT-065C1853163C | 1 | North Gwillimbury Forest | 2 | 2021-05-15 00:55:07
CTT-E9DCC146EC35 | 357 | Estero Punta Banda | 2 | 2021-05-15 01:21:19
CTT-95D88F378352 | 191 | Breckenridge Bluff 3.0 | 2 | 2021-05-15 01:48:34
CTT-18BC3777F716 | 1 | The Tip | 2 | 2021-05-15 03:10:00
CTT-9F2FC71DC4C8 | 336 | CluxeweEstuary | 2 | 2021-05-15 05:46:52
CTT-3C9873F4B04E | 213 | Billingsley Creek WMA-ID | 2 | 2021-05-15 08:55:15
CTT-0EF9486EFBD4 | 48 | Three Rivers WMA | 2 | 2021-05-15 15:22:37
CTT-217D5BD5F79E | 48 | Assateague State Park | 2 | 2021-05-15 16:08:37
CTT-9946FC619AAD | 48 | Middle Creek | 2 | 2021-05-15 18:15:48
CTT-CD5BCE070809 | 367 | Massengale Mtn. | 2 | 2021-05-15 19:49:31
CTT-24B59029A7E3 | 48 | Rushton Farm | 2 | 2021-05-15 20:00:00
CTT-6B066B3E7BAD | 48 | Knobs | 2 | 2021-05-15 21:40:51
CTT-867459049274186 | 292 | Bernheim Education Center | 2 | 2021-05-15 23:26:25
CTT-54A61DB0C752 | 303 | Meeman Biological Station Receiver | 2 | 2021-05-16 00:13:11
CTT-17E5AD66A11A | 336 | CowichanEstuary | 2 | 2021-05-16 01:49:36
CTT-0AD80DAFAB6B | 336 | DelkatlaWildlifeSanctuary | 2 | 2021-05-16 02:08:25
CTT-DC088622B691 | 48 | Perch River WMA | 2 | 2021-05-16 02:35:05
CTT-1D74C0AC2D91 | 129 | Ying-Yang | 2 | 2021-05-16 03:04:16
CTT-9E17E78B04AE | 337 | Nahcotta Motus Tower | 2 | 2021-05-16 03:21:14
CTT-E590CFC9F356 | 48 | Rome WMA | 2 | 2021-05-16 04:24:47
CTT-E76F6F633718 | 336 | Bayview | 2 | 2021-05-16 05:08:59
CTT-BDBE9C27FA02 | 48 | SUNY Potsdam - Bowman Hall | 2 | 2021-05-16 07:04:04
CTT-F5FA9A2D5D83 | 213 | Sterling WMA | 2 | 2021-05-16 10:08:32
CTT-9879DF3C9241 | 273 | Boundary Bay Field | 2 | 2021-05-16 14:14:39
CTT-6047CC0B70A3 | 48 | Redden SF | 2 | 2021-05-16 14:20:48
CTT-F0C333DDFB45 | 273 | Blackie Spit | 2 | 2021-05-16 14:33:02
CTT-F2C6EECBB135 | 1 | Killbear | 2 | 2021-05-16 14:34:04
CTT-76136C5CBCAC | 35 | Honey Hut | 2 | 2021-05-16 14:56:11
CTT-B0343AB7C77C | 48 | Hickory Ridge | 2 | 2021-05-16 15:57:13
CTT-E0AEB7A1CE3A | 48 | Strawberry Fields | 2 | 2021-05-16 16:18:09
CTT-CED23BFBD64F | 48 | High Rock | 2 | 2021-05-16 17:27:27
CTT-BE154D94151F | 48 | Restore Native Plants | 2 | 2021-05-16 17:56:08
CTT-F2B981B73FE3 | 213 | Niagara Springs WMA-ID | 2 | 2021-05-16 19:10:01
CTT-CA0B1F13DDC3 | 377 | Corn Creek | 2 | 2021-05-16 20:26:55
CTT-0E4303B1248F | 129 | New Playa | 2 | 2021-05-16 22:03:49
CTT-7AF99B215BEB | 48 | Butler03 | 2 | 2021-05-16 22:07:47
CTT-39B99EDBFFFC | 213 | LuckyPeak-BoiseRiverWMA-Boise-ID | 2 | 2021-05-16 22:24:27
CTT-22739D6E1278 | 48 | Wild Beach | 2 | 2021-05-17 01:18:41
CTT-8844392FDE05 | 213 | Rogue River KBO- OR | 2 | 2021-05-17 01:30:35
CTT-BDF39CFA4488 | 172 | Patuxent Research Refuge-NWR | 2 | 2021-05-17 01:32:37
CTT-65F59C21C2F8 | 48 | Lakeview Landfill | 2 | 2021-05-17 02:35:06
CTT-E4921F5C7E7D | 290 | Whitfield Hamilton Grain Elevator | 2 | 2021-05-17 02:50:51
CTT-C0612F7F986B | 247 | LC 4 | 2 | 2021-05-17 04:49:15
CTT-26E533CA5563 | 213 | Minidoka HQ NWR-ID | 2 | 2021-05-17 08:12:17
CTT-4DBB0227D3C4 | 48 | Marienville Firetower | 2 | 2021-05-17 09:51:12
CTT-FAFFF864EC3E | 48 | Mauch Chunk | 2 | 2021-05-17 10:06:11
CTT-C550369A27A5 | 48 | Penn DRL | 2 | 2021-05-17 10:29:20
CTT-3AE092B9FC1C | 129 | Windblown | 2 | 2021-05-17 13:10:19
CTT-59665269D53D | 390 | Black_Rock_434 | 2 | 2021-05-17 13:38:21
CTT-1BCD07237B49 | 48 | Blackwater | 2 | 2021-05-17 15:32:53
CTT-BB0BF3253D55 | 390 | SE_Light_434 | 2 | 2021-05-17 15:47:50
CTT-278BD46E158D | 357 | Golfo de Santa Clara - RV parl | 2 | 2021-05-17 16:16:43
CTT-DC15EBA4B31E | 48 | Interstate | 2 | 2021-05-17 16:22:11
CTT-F830004E08C9 | 48 | Westtown School Observatory | 2 | 2021-05-17 17:51:22
CTT-C03610761B38 | 48 | DEEC | 2 | 2021-05-17 17:51:47
CTT-86BC6CD43E43 | 48 | Buck Run | 2 | 2021-05-17 17:51:57
CTT-908421D382C8 | 310 | Longwood Gardens | 2 | 2021-05-17 18:06:06
CTT-F39C813B3D1A | 59 | East Point - 2 | 2 | 2021-05-17 18:25:49
CTT-1E45B4CB7F46 | 310 | London Grove 4 | 2 | 2021-05-17 18:51:21
CTT-02F54E43C375 | 310 | DMNH1 | 2 | 2021-05-17 18:51:31
CTT-A7D266DAB7A8 | 290 | WPNC Bird Banding Station V2 | 2 | 2021-05-17 18:51:45
CTT-4146B772AF7D | 48 | Bucktoe Preserve | 2 | 2021-05-17 18:51:48
CTT-867459049274871 | 313 | Tulsa Zoo Motus | 2 | 2021-05-17 20:25:22
CTT-867459049273493 | 292 | Bernheim Fire Tower | 2 | 2021-05-17 21:30:20
CTT-69EE80C6236A | 183 | Albany Pine Bush Preserve Discovery Center | 2 | 2021-05-18 11:20:19
CTT-3AC0EAE93AAF | 48 | Poplar Cell 2 Spillway | 2 | 2021-05-18 11:33:19
CTT-867762040710391 | 350 | Cheyenne Bottoms TNC | 2 | 2021-05-18 11:36:02
CTT-D7F2B2270735 | 48 | Marshlands | 2 | 2021-05-18 11:50:44
CTT-2EE41E27E49C | 213 | The Roost -MPG-MT | 2 | 2021-05-18 11:51:17
CTT-6CA25D375881 | 293 | CTT Meadows V2 | 2 | 2021-05-18 11:51:55
CTT-CB9A196520E9 | 35 | PARC Banding | 2 | 2021-05-18 11:52:08
CTT-5031194D3168 | 213 | IndianRidge3-MPG-MT | 2 | 2021-05-18 11:52:19
CTT-867459049297757 | 152 | Iroquois HQ | 2 | 2021-05-18 12:26:40
CTT-867459049295843 | 387 | Finca Cántaros | 2 | 2021-05-18 12:27:14
CTT-867459049276348 | 172 | Trunk Island Bermuda | 2 | 2021-05-18 12:27:15
CTT-867459049276363 | 6 | Galeta | 2 | 2021-05-18 12:27:21
CTT-867762040716224 | 281 | GPCD Rocky Mountain Arsenal | 2 | 2021-05-18 12:27:21
CTT-867459049220262 | 293 | Cape May Point State Park | 2 | 2021-05-18 12:27:35
CTT-867459049297880 | 6 | Panama Sewage Plant | 2 | 2021-05-18 12:27:36
CTT-867459049219850 | 6 | Canopy Tower | 2 | 2021-05-18 12:27:37
CTT-867459049297468 | 281 | GPCD Soapstone | 2 | 2021-05-18 12:27:37
CTT-867459049275027 | 48 | High Knob | 2 | 2021-05-18 12:27:38
CTT-867762040726462 | 325 | Zoo New England | 2 | 2021-05-18 12:27:39
CTT-87C77C759BBF | 213 | SouthBaldyRidge2-MPG-MT | 2 | 2021-07-20 22:25:50

**Comment by denislepage** [comment]
Do you have specific examples of those that you think are behind? Any of the ones last updated on 12 May? I spot checked a few and I am not seeing any problem at our end other than no data coming (e.g. CTT-D7D11D3641CD), I will need to pass this to CTT, but I'd like to give them a specific list with a few serial numbers at least.

**Comment by jsayers-bsc** [comment]
Yes, most of those registered to project 1 are still checking in regularly on the CTT portal. A couple examples are CTT-97FB9AB20E31, CTT-42446DCD0910, CTT-CDE43745B223, CTT-999F324263A2,
CTT-5665244BE876






________________________________

**Comment by denislepage** [comment]
CTT said they had a glitch, which is now fixed, and data should be moving again. We should double check again tomorrow. I haven't looked yet, but they may already be there.
