### ISSUE TITLE
Instructions or fields to mark permanently incomplete data

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#97]
From Denis:

Need instructions or ways for people to identify cases where the metadata doesn’t and/or will never exist - i.e. antenna bearings, etc.

Maybe a comment or flag in the deployment record about missing data, or something. I don’t think people currently see comments, so maybe a “complete” flag indicating that whatever data is there is all there is (e.g. 0 = waiting for more data, 1 = complete, 2 = incomplete). We could assign 0 or 1 based on minimum requirements that we want (e.g. position and/or mobile flag, antenna bearings, start date, etc.), but 2 would be set by the users or us when we know there is no more data to be had.

Needs some thought. (stu)

**Comment by StuMackenzie** [comment]
From Tara:

Message center - so when people log in, they will get a series of messages/warnings. I just looked at the site Stu sent around, and for each error, I'm given an option to edit or ignore.  If the error is ignored, does that error never show up again in the message center?  Maybe this is where there could be an option for "data not available" or something? 

And when people enter their metadata, could there be an option for 'not collected' or 'NA', which would differ from an empty field (which implies data is missing but potentially available).  This could be instead of (or in addition to) having a separate flag column?  I suppose a flag column alone might do, but waiting on more data might mean they have lat and lon to enter, but they still might never have antenna bearings, for example.  Complicated. I agree, though, that there should be a way to tell whether that metadata is missing permanently, or whether it just hasn't been entered. There's no point hassling people for information that is never going to be available.

If we are going to have an external page for error reporting, we should really get that set up asap, so that we can link to it in the book.  Then if multiple people have issues with the same project's receivers, the PI isn't getting multiple inquiries, and if the issues are solved, this could also be noted.... Presumably people would be able to search the listed issues to see if their issues match previously reported issues, and also be able to tell whether those issues were resolved -- or will never be resolved (data not available)? If there is a way to tell in the database that data are complete as is, then there should be fewer and fewer errors of this type being recorded over time.

What were the details on how this error reporting should/could be set up?

**Comment by Hussell** [comment]
The metadata issues page is a prototype which is still under development. In particular, the "ignore" function isn't working yet. The intent is that ignored errors will be moved to a separate table on the same page, where they can be reviewed and "un-ignored" if necessary. Users won't get messages or notifications about ignored errors which are re-generated when we re-run the metadata validation process.

Comments really should be visible and editable by users who are registered with a project. This has been on the list for a long time. See #31, for example.
