### ISSUE TITLE
Station summaries only showing data from most recent deployment, not entire station history.

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#971]
Via table view - eg. The Tip station - https://motus.org/data/receiverDeployment?id=7697

Only showing data since most recent deployment and nothing before.

And via the map.

The Tip station has been active since 2014. BSC HQ 2014/2015, yet only the most recent data is being displayed.

**Comment by Hussell** [comment]
That is not a station summary. It is a deployment summary.

**Comment by StuMackenzie** [comment]
Should be a station summary no? Or at least have the option.

I vote station summary.

S
