### ISSUE TITLE
Add S8 receivers to data flow and receiver registration/deployment options

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#973]
Two receiver models:

1) SigmaEight – Orion
2) SigmaEight – Ares

Serial numbers will be in the format - SEI-A123456789 (for Ares) or SEI-O123456789 (for Orion)

10 digits alphanumeric following the 'SEI-' prefix

Need to know anything else?

**Comment by cjardine-bsc** [comment]
My take-away from today's meeting is that we need to wait to confirm the serial number format before I add to the DB right?

**Comment by Hussell** [comment]
I've changed the serial number regex on sgdata to SEI-[0-9A-Z]{10}.

**Comment by denislepage** [comment]
It’s fine to have a less restrictive regex in motusServer, but we should try to have the more accurate regex for the metadata page. I asked SEI to confirm. I indicated to them that the pattern we agreed to earlier was with an underscore, not a dash. Now that we’ve advocated for both, we may need to support both options.

"SEI_[AO]_[0-9]{2}(0[0-9]|1[0-2])([0-2][0-9]|3[0-1])[0-9]{3}"

Your regex wouldn’t work based on previous recommendation. It’d need to be:

"SEI_[AO]_[0-9A-Z]{9}"

Let’s get it right once, rather than bouncing back and forth.

**Comment by Hussell** [comment]
Alright, changed to "SEI_[A-Z]_[0-9AZ]{9}" on sgdata.

**Comment by denislepage** [comment]
Sounds good. I have also added this regex in the sandbox table. It is more stringent, but this is important to get right. I haven't done this yet on live, as I wasn't sure we were ready to make this option available to everyone. The instructions will also need some adjustments on the receiver page.

SEI_[AO]_[0-9]{2}(?:0[1-9]|1[0-2])(?:[0-2][0-9]|3[0-1])[0-9]{3}

I also just heard that SEI will be asking the users to manually enter the serial number during the file extraction process. I wasn't clear if this is when extracting the data from their units or their servers. I've made some suggestions to try and reduce the risk of errors, though it's not ideal. One of them would be to validate their entry against the same regex above.

**Comment by StuMackenzie** [comment]
Outstanding task is to add this Sigma Eight model numbers into the metadata deployment mgmt templates.

**Comment by StuMackenzie** [comment]
- [ ] Update user instructions, eg. serial number, etc.

**Comment by StuMackenzie** [comment]
Elevating this issue here. Most of the discussion to date has been offline. 

Data from S8 receivers is not appear to be processing correctly. It uploads, but does not return known detections.

Need to investigate further. We'll expand documentation as I digest previous correspondence and known information from the project. 

@Hussell might be able to summarize what's working/not working, or the current status.

**Comment by Hussell** [comment]
https://motus.org/data/receiver/deployment/plot?id=7879

**Comment by Hussell** [comment]
Denis correctly identified the issue: pulse frequencies were being reported as absolute numbers in MHz, instead of offsets from the receiver listening frequency in kHz.

**Comment by StuMackenzie** [comment]
Wahooo! 

____________________

**Comment by leberrigan** [comment]
@StuMackenzie Reopen if you think it still needs attention.
