### ISSUE TITLE
Include nodeNum and motusFilter in alltags and allruns by default

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#975]
Can these two fields be added to the `allruns` and `alltags` views?

**Comment by denislepage** [comment]
@steffilazerte  I have added the 2 fields (both come from the runs table) in the R/makeAlltagsView.R and R/ makeAlltagsGPSView.R , but I feel this is no longer how you set things up. This would only work for new db files also, presumably, and I can find any trace of allruns. help?

**Comment by steffilazerte** [comment]
Hi @denislepage 

1. The `makeAlltagsView.R` etc. files are indeed how the views are created
2. This applies to **all** data bases (not just new ones) as the `ensureDBTables()` function [recreates the views](https://github.com/MotusWTS/motus/blob/3a9e5cf24a00c690014435ef94b1aa990c2c83b3/R/ensureDBTables.R#L513) and this function is [run every time `tagme()` is called](https://github.com/MotusWTS/motus/blob/3a9e5cf24a00c690014435ef94b1aa990c2c83b3/R/tagme.R#L127)
3. [`makeAllRunsView.R`](https://github.com/MotusWTS/motus/blob/78b3eefd92bc61252608766231c058f7e6199b4e/R/makeAllrunsView.R) and [`makeAllRunsGPSView.R`](https://github.com/MotusWTS/motus/blob/78b3eefd92bc61252608766231c058f7e6199b4e/R/makeAllrunsGPSView.R) only exist on Sandbox

To help preserve my sanity, I think changes to master should include a [version bump (i.e. v4.0.7)](https://github.com/MotusWTS/motus/blob/3a9e5cf24a00c690014435ef94b1aa990c2c83b3/DESCRIPTION#L3) and an addition to the [NEWS.md](https://github.com/MotusWTS/motus/blob/3a9e5cf24a00c690014435ef94b1aa990c2c83b3/NEWS.md) file. 

Perhaps I could also be an 'owner' of the motus repository so I get the GitHub Actions reports too?

**Comment by steffilazerte** [comment]
Actually I don't think the owner matters, I think the emailed reports go to whomever made the change

**Comment by denislepage** [comment]
Thanks.

Just to clarify, can you replicate my recent changes from master into sandbox, and also add the same 2 fields in the 2 runs views?

I should have made the changes in sandbox first, sorry.

**Comment by steffilazerte** [comment]
No problem! I also added it to `alltags` on beta4, so now it's consistent. This will also make some examples in the motus book that I've been working on, easier :grin:

**Comment by steffilazerte** [comment]
And I lied about the views being recreated, only the ambigtags view was actually deleted and THEN recreated. The others were only recreated if they didn't exist (this is now fixed).

**Comment by j-sayers** [comment]
Closing as it appears these fields are both present.

Re-open if there are still loose ends...
