### ISSUE TITLE
 Europe receiver - SG-50D6RPI38864 - rerun

### ISSUE THREAD

**Issue by StuMackenzie** [MotusDev/Motus-TO-DO#976]
Noort - European receiver. Either the 'bug', or I hope it's another issue. Suggest testing elsewhere before rerunning if it'll make the data worse.  This is a hot potato, so please handle gently.

Thanks

Hi Lucas,

Receiver SG-50D6RPI38864 has loads of detections in the raw data, however none show up in Motus.
Several questions:

•	How is it possible that stations keep “moving” to the US?
•	Is there a way to check for me where they are located according to Motus? / which frequency is being checked by Motus?
•	Could you please rerun this one?

Met vriendelijke groet,

Bart Noort
Researcher

**Comment by jsayers-bsc** [comment]
This receiver has[ European detections](https://motus.org/data/receiverDeploymentDetections?id=6163) already so appears not to be case of the wrong default frequency. It may be that this is a case of the recent issue seen at Old Cut where new detections just aren't showing up.

**Comment by StuMackenzie** [comment]
I worried that this was the case. Will wait for JH to confirm before we respond to them.

**Comment by Hussell** [comment]
This receiver is on the list Catherine's query produced yesterday. I reran the boot number that was already missing detections, and it still has zero detections.

P.S.: would someone please get it through to Bart that missing detections ≠ wrong frequency? His entire project has been on the correct frequency for years now. Looking at the job reports on sgdata he should be able to see the line "Got parameter overrides: --default_freq 150.096" on every single batch. That line is equivalent to "This receiver is located in Europe or Africa."

**Comment by StuMackenzie** [comment]
Closed in deference to #970
