### ISSUE TITLE
Duplicate Species

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#979]
We currently have multiple species IDs and English names for the same scientific name. This is problematic for summaries, but is an easy fix if we can just merge species IDs based on the scientific name, but the English name and 'Group' differs so we have to decide what to do there.
![image](https://user-images.githubusercontent.com/35931796/120340195-c71e6000-c2c3-11eb-96b4-e554b7259dc1.png)

We may want to consider making it possible to have multiple names for the same species, not just for other languages. For instance, we are expecting a large number of bird names to change fairly soon (this year, the next?) and it would be helpful if we could allow old names to be searchable during that transition.

Looking through the master list of species, I have found 32 duplicated species:
```
spp.df <- read.csv("E:/Data/species.csv")

spp.df[which(duplicated(spp.df$scientific)),]
```

It seems like majority of these are Bats with two (mostly) similar names. The exceptions are wild vs. domestic cats and dogs. 

id | english | french | scientific | group | sort
-- | -- | -- | -- | -- | --
129560 | Gray Wolf | ? | Canis lupus | MAMMALS | 129560
129600 | domestic dog (feral) | ? | Canis lupus | MAMMALS | 129600
100020 | Mexican Long-tongued Bat | ? | Choeronycteris mexicana | BATS | 100020
122010 | Mexican Long-nosed Bat | ? | Choeronycteris mexicana | MAMMALS | 122010
100210 | Spotted Bat | ? | Euderma maculatum | BATS | 100210
123740 | Spotted Bat | ? | Euderma maculatum | MAMMALS | 123740
100640 | Underwood's Bonneted Bat | ? | Eumops underwoodi | BATS | 100640
126500 | Underwood's Mastiff Bat | ? | Eumops underwoodi | MAMMALS | 126500
129940 | Common Wild Cat | ? | Felis silvestris | MAMMALS | 129940
129950 | domestic cat (feral) | ? | Felis silvestris | MAMMALS | 129950
100220 | Allen's Big-eared Bat | ? | Idionycteris phyllotis | BATS | 100220
123890 | Allen's Big-eared (Lappet-browed) Bat | ? | Idionycteris phyllotis | MAMMALS | 123890
100230 | Silver-haired Bat | chauve-souris argentÃ©e | Lasionycteris noctivagans | BATS | 100230
123940 | Silver-haired Bat | chauve-souris argentÃ©e | Lasionycteris noctivagans | MAMMALS | 123940
100240 | Western Red Bat | ? | Lasiurus blossevillii | BATS | 100240
123952 | Red Bat | ? | Lasiurus blossevillii | MAMMALS | 123952
100300 | Southern Yellow Bat | ? | Lasiurus ega | BATS | 100300
123980 | Southern Yellow Bat | ? | Lasiurus ega | MAMMALS | 123980
100310 | Northern Yellow Bat | ? | Lasiurus intermedius | BATS | 100310
124000 | Northern Yellow Bat | ? | Lasiurus intermedius | MAMMALS | 124000
100320 | Seminole Bat | ? | Lasiurus seminolus | BATS | 100320
124010 | Seminole Bat | ? | Lasiurus seminolus | MAMMALS | 124010
100030 | Mexican Long-nosed Bat | ? | Leptonycteris nivalis | BATS | 100030
122090 | Big Long-nosed Bat | ? | Leptonycteris nivalis | MAMMALS | 122090
100050 | California Leaf-nosed Bat | ? | Macrotus californicus | BATS | 100050
121490 | California Leaf-nosed Bat | ? | Macrotus californicus | MAMMALS | 121490
100650 | Pallas's Mastiff Bat | ? | Molossus molossus | BATS | 100650
126600 | Velvety Free-tailed Bat | ? | Molossus molossus | MAMMALS | 126600
100010 | Peters's Ghost-faced Bat | ? | Mormoops megalophylla | BATS | 100010
121350 | Leaf-chinned (Ghost-faced) Bat | ? | Mormoops megalophylla | MAMMALS | 121350
100350 | Southwestern Bat | ? | Myotis auriculus | BATS | 100350
124110 | Southwestern Myotis | ? | Myotis auriculus | MAMMALS | 124110
100360 | Southeastern Bat | ? | Myotis austroriparius | BATS | 100360
124130 | Southeastern Myotis | ? | Myotis austroriparius | MAMMALS | 124130
100370 | Californian Bat | ? | Myotis californicus | BATS | 100370
124190 | California Myotis Bat | ? | Myotis californicus | MAMMALS | 124190
100380 | Western Small-footed Bat | ? | Myotis ciliolabrum | BATS | 100380
124432 | Western Small-footed Myotis | ? | Myotis ciliolabrum | MAMMALS | 124432
100390 | Long-eared Bat | ? | Myotis evotis | BATS | 100390
124290 | Long-eared Myotis Bat | ? | Myotis evotis | MAMMALS | 124290
100400 | Gray Bat | ? | Myotis grisescens | BATS | 100400
124350 | Gray Myotis | ? | Myotis grisescens | MAMMALS | 124350
100410 | Keen's Bat | ? | Myotis keenii | BATS | 100410
124420 | Keen's Myotis | ? | Myotis keenii | MAMMALS | 124420
100420 | Eastern Small-footed Bat | chauve-souris pygmÃ©e | Myotis leibii | BATS | 100420
124430 | Small-footed Myotis | chauve-souris pygmÃ©e | Myotis leibii | MAMMALS | 124430
100430 | Little Brown Bat | petite chauve-souris brune | Myotis lucifugus | BATS | 100430
124470 | Little Brown Bat (Myotis) | petite chauve-souris brune | Myotis lucifugus | MAMMALS | 124470
100450 | Northern Long-eared Bat | vespertilion nordique | Myotis septentrionalis | BATS | 100450
124422 | Northern Long-eared Myotis | vespertilion nordique | Myotis septentrionalis | MAMMALS | 124422
100460 | Indiana Bat | ? | Myotis sodalis | BATS | 100460
124780 | Indiana Bat | ? | Myotis sodalis | MAMMALS | 124780
100520 | Long-legged Bat | chauve-souris Ã&nbsp; longues pattes | Myotis volans | BATS | 100520
124840 | Long-legged Myotis | chauve-souris Ã&nbsp; longues pattes | Myotis volans | MAMMALS | 124840
100560 | Evening Bat | ? | Nycticeius humeralis | BATS | 100560
124990 | Evening (Black-shouldered) Bat | ? | Nycticeius humeralis | MAMMALS | 124990
100660 | Pocketed Free-tailed Bat | ? | Nyctinomops femorosaccus | BATS | 100660
126910 | Pocketed Free-tailed Bat | ? | Nyctinomops femorosaccus | MAMMALS | 126910
100670 | Big Free-tailed Bat | ? | Nyctinomops macrotis | BATS | 100670
126930 | Big Free-tailed Bat | ? | Nyctinomops macrotis | MAMMALS | 126930
100570 | Western Pipistrelle | ? | Pipistrellus hesperus | BATS | 100570
125320 | Western Pipistrelle | ? | Pipistrellus hesperus | MAMMALS | 125320
100680 | Brazilian Free-tailed Bat | ? | Tadarida brasiliensis | BATS | 100680
127040 | Brazilian Free-tailed Bat | ? | Tadarida brasiliensis | MAMMALS | 127040

**Comment by denislepage** [comment]
Bats are a bit of an exception and were imported for 2 different purposes at different times. We should merge them, yes.

I’d advocate removing the species listed as “BATS” in favour of those in the “MAMMALS” group, but I’ll wait for Catherine to see which way we go, as it will likely have implications on the birds and bats database that she manages.  Right now, we have deployments with names from both lists in roughly equal numbers in Motus (700 and 1100).

We never really delete deprecated species_id, but we change their status so they become unavailable, but that’s internal db stuff.

Adding alternative names for searching should be doable without too much complications. I have a table called lk_species_synonyms that we can use for that purpose. For birds, we could potentially add IOC names at the very least (our main list is based on Clements/eBird), and keep old names moving forward.

I have modified the names of the domestic cats and dogs to include their respective subspecies in my master. Those can be synced a bit later with the rest.

There’s an upcoming bird taxonomy update also coming this summer, so we should be able to deal with this all at the same time.

**Comment by cjardine-bsc** [comment]
Yes, I'd agree. The species_ids used for the Bird and Bat Wind Database are kept in a separate table, so merging these shouldn't have an impact 

Denis, would you like me to generate a paired list of species_id that need to be merged?

**Comment by denislepage** [comment]
Sure.

You will likely need to update your own wind tables to match?

It’d rather keep the id’s associated with the MAMMALS group, rather than BATS.

**Comment by cjardine-bsc** [comment]
yes, that's fine with me.

**Comment by denislepage** [comment]
Door number 2, keep the species_id’s from BATS and then change the group to MAMMALS.

Not sure it really matters either way. We shouldn’t have a lot of records overall.

the documentation I keep for the various steps that I need to do with the taxonomy updates are in t:\metadata. The SQL file is just a guide, not something that I can run unattended. The 2019 version has a bunch of updates for the various tables, so if you know of specific tables you would like me to include in these updates, you can potentially add new rows in that section of updates that start around row #371.

I am working on the newest Clements 2021 now, which isn’t quite finalized yet.
