### ISSUE TITLE
Docs: Review of "In-depth detections filtering"

### ISSUE THREAD

**Issue by steffilazerte** [MotusDev/Motus-TO-DO#981]
Clairfies filters (manual vs. noise and motusFilter() vs. filterByActivity() (cf #944)

I've updated the motus documentation (previously the motus R book) to separate out the filtering aspects into a stand-alone, advanced article. This new "In-depth detections filtering" article should clarify `motusFilter`/`filterByActivity()`.

**Requirements**
- Correct assessment of filtering?
- General editorial review

**Resources**
- [Compiled HTML Article](https://motuswts.github.io/motus/articles/filtering.html)
- [Rmd files on book-overhaul branch](https://github.com/MotusWTS/motus/tree/book-overhaul/vignettes/articles) (`filtering.Rmd`)

**How to review:**
- Make git changes directly to "[book-overhaul](https://github.com/MotusWTS/motus/tree/book-overhaul)" branch
- "Review changes" on the [pull request](https://github.com/MotusWTS/motus/pull/12/files) (See [GitHub docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request)). You can make suggestions directly there. 
- Send me a modified Rmd file and I'll incorporate your changes

**Comment by cjardine-bsc** [comment]
Hey Steffi, How would you like me to provide feedback/wordsmithing?

**Comment by steffilazerte** [comment]
Perhaps via pull request on the book-overhaul branch? https://github.com/MotusWTS/motus/tree/book-overhaul

**Comment by ajmacdonald3** [comment]
Assigning myself to this review.

**Comment by ajmacdonald3** [comment]
@steffilazerte, are we able to push any of the fixes in the beta4 branch to the master branch? The `filterByActivity()` function isn't working properly, but I think you had already fixed it in beta4 (https://github.com/MotusDev/Motus-TO-DO/issues/871).

**Comment by steffilazerte** [comment]
I'll see about that, sometimes the beta branch changes relate to the beta version of the API as well, so it's not always straightforward. I think that's something I need to think about going forward, i.e. making small changes separate from the API easier to implement. 

I'll look into getting this all merged and working this week.
