### ISSUE TITLE
Beta10 bugs, issues, and requests

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#982]
Going to leave a running list of items here

- [x] clicking on the "tabs" (all, undeployed, etc) or on field heads throws an error 

- [x] Manage Tags link from Manage Data dropdown throws an exception

- [x] Manage Receivers link still present in Manage Data (and leads to 404)

- [x] Manage Sites and Landowners link doesn't work (404 page)

- [ ] Not so much a bug as an issue. Sorting by tag label sorts by digit instead of the entire number. Just this field; BI sorts properly. Likely because the tag label is stored as string, but it does make sorting less useful.
  - Maybe it's treating it as a character string, not an integer

  - [ ] Retain "last modified" timestamp on Manage Tags. This helps identify when deployments were only recently created and can help explain why detections may  be missing from outputs. Last modified userID would be handy too (I don't think that was on the previous version)
  - [ ] Add tool for adding institutions
    - [ ] Add notice emails as verification step
  - [ ] Institutions list:
    - [ ] 'Move up the list' button may be better placed next to ranking field (within same cell is fine)
    - [ ] No numbers appear in the ranking box. Perhaps these should be populated automatically?
    - [ ] 'Remove' button may be better placed at the end as the last cell.

**Comment by jsayers-bsc** [comment]
Just recently I'm getting a "Developer Error!" while trying to access Manage Tags. (This wasn't happening earlier)

I don't know how much detail of the error messages you need; I assume that they are being sent to Paul/Jeremy/Denis?

**Comment by jsayers-bsc** [comment]
Oh, and Paul, I see what you mean now regarding tags with multiple deployments. Previously multiple deployments for a particular tag were all shown in the same table (what I was referring to when I said they were presented by deployment, even though just the tag_id is displayed). Now in beta each tag just gets its own line, and multiple deployments are broken down in the right-hand panel. It's a bit of a change to get used to, but I think it will make management easier.

**Comment by pmorrill** [comment]
The wordpress dropdowns need updating to reflect the new mgmt model. 

- Manage Users => change to Manage Collaborators
- Manage Tags - still OK
- Manage Sites and Landowners => Change to just 'Manage Landowners' and url is now **/data/project/landowners**
- Manage Receivers => change to 'Manage Stations' and the url is now **/data/project/stations**

**Comment by pmorrill** [comment]
The issue with pagination links always using project 1 will be fixed on next build (beta10 / master)

**Comment by jsayers-bsc** [comment]
Updated the title to reflect that not every item here is a "bug". Some are less serious issues, and some are requests to retain useful features.

**Comment by leberrigan** [comment]
- [ ] Add tool for adding institutions
  - [ ] Add notice emails as verification step
- [ ] Institutions list:
  - [ ] 'Move up the list' button may be better placed next to ranking field (within same cell is fine)
  - [ ] No numbers appear in the ranking box. Perhaps these should be populated automatically?
  - [ ] 'Remove' button may be better placed at the end as the last cell.

**Comment by jsayers-bsc** [comment]
I've taken out the items specific to Manage Stations and put them in their own issues page #994. I'll do the same with Manage Tags...

**Comment by jsayers-bsc** [comment]
This has mostly been superseded by other issues so am closing...
