### ISSUE TITLE
Detections no longer visible on summary pages

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#989]
A receiver in the Panama array (https://motus.org/data/receiverDeployment?id=7664) had several detections which are now missing. 

This is a screenshot sent from earlier:

![IMG-20210628-WA0013](https://user-images.githubusercontent.com/55001144/123717181-529afa80-d84a-11eb-8857-745fc1ac9157.jpg)

It's just the Nanotag detections that are now absent; the LifeTag detection is still there.

The "missing" detections are actually still present in the data though -- definitely in the data downloaded via the R package today. And they don't appear to have been flagged, either automatically or manually.

**Comment by leberrigan** [comment]
I don't see this issue any more - close?

**Comment by jsayers-bsc** [comment]
Yeah the detections are back. Whatever happened here I wonder?! Anyway, yeah guess it's to be closed...
