### ISSUE TITLE
Add geographic regions to tag deployment bulk upload

### ISSUE THREAD

**Issue by cjardine-bsc** [MotusDev/Motus-TO-DO#99]
If we are only showing them a list of warnings and errors, then maybe we should give them a 
unique list of geographic areas where their various deployments fall. Ideally, something like this, 
or whatever we can fit within our existing framework that looks like that:
  
The location of your deployments fall within the following geographic areas. If you see any areas 
that are incorrect, please check all your coordinates for typos, also making sure that you have 
not inverted the latitude and longitude, or used positive values where negative values were 
expected.

 Ontario (Canada) - 5 deployments
 Québec (Canada) - 15 deployments
 New York (USA) - 2 deployments

I´ve added a new field called region to api_tag_deployments. The field is populated through the 
prAPIValidateTagDeploy procedure.
   
 I´ve made a new view called vwAPI_tag_deploy_region which will give the 
 regions in the upload, as outlined above

You´ll just need to call the below from the database:

 Select * from vwAPI_tag_deploy_region where apiBatchID= ?

 I´ve also added a new text fragment for the description of this section: api_tag_deploy_region_check which we can use to preface the table of counts.

 Paul this is low priority, so we can implement this after the R client is all set up.

**Comment by denislepage** [comment]
Sounds good. We should be doing this for both tags and receivers.

**Comment by Hussell** [comment]
Closely related to #96. Not sure if this is a duplicate or not.
