### ISSUE TITLE
Calculated End Dates being displayed in some places they shouldn't be

### ISSUE THREAD

**Issue by j-sayers** [MotusDev/Motus-TO-DO#993]
**In the R package**

I recently noticed that the calculated end date is provided in the tsEnd field of the tagDeps tables when downloading in the R package (for deployments without user entered end dates).

We can distinguish between these two in the web page by using font styles, but in the R data it seems like we should probably leave tsEnd blank unless actually entered by the user, and provide the calculated end date as its own clearly marked field.

![image](https://user-images.githubusercontent.com/55001144/125845695-96a5c3c1-da8e-4c21-9443-d77185aa55ce.png)

**In the Data Issues page**

![image](https://user-images.githubusercontent.com/55001144/126804601-80c92c63-df99-4a61-aff4-7c36d5e2342f.png)

**Comment by leberrigan** [comment]
@j-sayers Can you confirm whether this is still an issue?
