### ISSUE TITLE
missed batches during sg import

### ISSUE THREAD

**Issue by denislepage** [MotusDev/Motus-TO-DO#995]
We ran into some import issues when pulling data from sgdata into motus today. The server was not always responding, and that still seems to be happening sporadically, so it is possible that this is what caused the problem initially.

Some earlier batches seemed to have been missed during the import, and newer runs are now referencing these older batches (batchIDBegin in the runs table) and failing to insert.

I checked, and there was about 1,600 missing batches, most of them without any detections. I added a loop that allowed me to go back in time (not in a DeLorean though) and reimport the missing batch records, and that seems to have pull them correctly in this instance. 

My understanding of my import script is that new batch ID’s won’t be imported until the earlier batch is fully imported, but I guess there’s a gap somewhere. Perhaps if the resume loop also fail, and the import proceeds ahead anyway, this could happen.

This is the first instance of this that I am aware of, but we could have missed earlier ones. We only found it because of the missing batches matching the batchIDBegin value. Another problem is that restoring the earlier batches will have the same problem for users trying to pull their data. Batches are only pulled incrementally based on the highest previous batchID value fully imported, and for users, the only option will be to delete the entire database, or at the very least the batches records back to the point where they are missing some of them.

I am only done fixing the import to the sg_* tables. Interestingly, the same problem seems to have happened on the det tables, on the same batch ID, suggesting that some of the missing batches were missed earlier on different processes. This would indicate that the error was not happening during the import, but that these batches were not available at a certain point, and they now seem to be. The only way by which I can see this happening is that the API filters out some of the batches until they are completed. Batch records on the sgdata side are added to MariaDB in the batchID order, but they may not terminate in the same order, so there may be some batches that are being missed when we try to import.

A few possible solutions: 
 - do not allow the API to return the most recent batches until all previous batches (with a lower batchID) are completed. That is risky because it assumes that all batches always complete at some point.
 - add a delay so the API never return batches that are more recent than a certain period. Not ideal because it means more delays for users when there are often no issues warranting this.
 - have a separate loop that runs every few days and try to look for possible missing batches. That may be my preferred approach, but it does create the same problem for users as well in the R package. 
 - patch the problem for now by importing missing data and see how long before it happens again.
 
A question for @Hussell is how long can it take between the time a batch is inserted in the maria DB database and it being "ready" for import through the API. The API likely filters based on a field in batches (perhaps ts), which may only be set at the very last step when tag finder insert into MariaDB.

This seems to be relatively rare, but not exceptional. There were a few large-ish batches missed because of this, including one with over 100,000 hits and a few in the 10,000-100,000 range.

From the sequence of event, the missed batches where all created today, and they all seem to be in a consecutive sequence from 2020642 to 2021820.

**Comment by denislepage** [comment]
I now have a script that will run and go back to import missed detections. I ran it thrice (sg table and both det's), and the error from yesterday went away. I'll try to hook it up so this can be added manually as an option to the procs queue calls. It will simply need the start batchID. Because we are clearing the maria DB tables, there would be no point in ever going back to the very first batches. There is likely still a batch record in MariaDB, but many of the associated tables are cleared.

**Comment by denislepage** [comment]
```
-----Original Message-----
From: Cron Daemon [mailto:root@sgdata.motus.org] 
Sent: 26-Jul-21 10:15
To: sg@sgdata.motus.org
Subject: Cron <sg@sgdata> /sgm/bin/cleanTransferTables.R

Error: found batch with smaller batchID but larger ts than batch 2020630
Execution halted
```

@Hussell  I'm getting those regularly, but I'm not sure what they mean. I know they are related to the cleaning task, but is that an error suggesting a problem, or simply that the processes aren't completed and need more time? Presumably, this process only cleans older batches, but batch 2020630 was imported only 4 days ago when I went back and looked for missed batches, even though it was processed back in March.

Is there a clue here about why some of these batches were missed in the first pass? Batch 2020630 is one of the several who was missed on the first attempt. Re-running my import process going back to before that one worked fine, which suggested that the sgdata API filters batches based on one of the fields, and they aren't being released in a chronological batchID sequence.

**Comment by Hussell** [comment]
Batches get assigned an ID before processing is complete, so before 'ts' is set. Since processing takes a variable amount of time and processing is done in parallel, batches with smaller IDs often finish processing after batches with larger IDs. Usually this discrepancy is small, on the order of seconds or minutes, but occasionally it can take hours for a single batch to finish processing. In addition, I occasionally manually rerun a batch to fix certain transient errors. This updates ts to the time of the second attempt, which is often days, or occasionally months after the original attempt.

The tables in the transfer DB are indexed by batchID, but not by ts, so cleaning the transfer tables is done by finding the largest batchID with ts more than a month old, then deleting data from batches with smaller IDs. Currently, batches with smaller IDs but data up to 10 minutes younger will be deleted without a message, but if the sanity-check finds a batch with data younger than that, it generates the error message above and aborts. So far, every time that has happened it has turned out to be safe to delete the younger data. I'm considering raising the limit from 10 minutes to a day, or a week, which should still be safe. (Transfer of data is done once every 20 minutes, cleaning only deletes data that has been in the database for 1 month - 10 minutes, changing it to 1 month - 1 week = ~3 weeks should still be safe, and reduce the number of error messages substantially. Alternately, delete everything older than 1 month + 1 week, occasionally delete some things that are only 1 month old, and abort if anything younger than 1 month would be deleted.)

As for the batches which failed to transfer, possibly due to rerun batches? I'm not sure, because I don't know the algorithm the import process is using. I know the import process has been interrupted many times. Possibly that can result in some batches being missed?

**Comment by denislepage** [comment]
The way the import works is that it simply loops through batches starting with the highest batchID last imported.

The batch import process simply grabs up to 10,000 rows from the batches table at a time, in sequential batchID order. Then the import script proceeds to import all the related records associated, one batchID at a time. IE, the grabs all the runs records for batch XXX, then all the GPS and hits records for batchXXX, etc. When all the records are imported for a batch, it sets the tsMotus value to the current time, and moves on to the next batchID. When all the batches are imported for the page of 10,000 records, it goes back and look for more batch records and continues until no more are returned.

I’ve made the script in a way that it can resume pretty much from any point following an interruption (e.g. server restart). The script will first look whether there are any batches on the motus end that do not yet have a tsMotus value, and for each table, look at the last value previously imported, so it can only ask for new records.

Batch reruns from that perspective are assigned a different batchID, so they are simply treated as distinct.

I think what is happening is that some batches in Maria DB are skipped because they are still being process, and I do not have a mechanism to go back earlier batches. The API only allows me to grab batches with batchID > X. What I did last week was to create a separate process that allows me to pull all the batches going back in time, but only reinsert those that I do not have in the database. Say, out of 10,000 batch records, there may be 100 that were somehow missed. Only those get inserted into the batches table (det_batches or sg_batches), and the rest of the import process is the same as above for pulling the data from the associated table, one batch at a time.

I see 2 possible solutions. One is that I automated the process (adding an item in the procs queue) that allows going back in time and look for missed batches over say the past week and once per day. That would likely be the simplest option, and would not be overly burdensome, since it is only duplicating data import for 1 of the tables (batches). Maybe we can start with this.

The other, perhaps slightly more involved, would be to allow requesting batches from the API in the ts order, rather than batchID. This would ensure that all batches are made available in the order in which they are finalized on the sgdata end, and none would ever be missed This would at the very least require adding an index on both ends to allow efficiently sorting the records on that ts field, and modifying the API to sort such option. I’d have to think whether there would be other implications in term of receiving batchID’s that are potentially out of sequence, but I can’t think of any for now. It still is slightly more risky to create new issues, so I will more likely leave that option off the table for now.

I don’t think we need to be too aggressive on deleting older batches from sgdata, especially until we have sorted out a way to go back and retrieve missed batches. I mostly just need to connect my new script to the procs queue to make that work now, and move this to the beta10 branch, too.

**Comment by denislepage** [comment]
I have just added a new procs_queue_recur item in sandbox with /patch:5 as parameter, which means that it will go back and try to look at any potentially missed batches over the previous 5 days. The process will be run once per day.

I have posted the Java updates to sandbox, and pushed the changes to beta10 too, but I haven't yet deployed them there. Once I have confirmation that this is working, we can then add the queue items in the main db too. We'll need 2 new items there, one for SGDataImport (SG tables) and one for SGDataImport2 (DET tables), both using the /patch parameter. At the moment, the patch parameter will simply do nothing on beta.

**Comment by denislepage** [comment]
Sorry, I misread your notes, and you are saying that when you rerun a batch, a new batchID is *not* created. For those batches, was a ts value assigned on the first failed attempt? If not, my new process will allow recovering them, as long as they are within the window I set (currently 5 days).

If you are re-running batches in the scenario that are older than 5 days old, we’ll need to decide whether those cases should be handled individually (e.g. we could set a proc that you could run with a different number of days to generate procs queue items, or one that identifies specific batchID’s to recover), or whether I should extend my period. I could for instance only run this process once a week, and try to go back 2 weeks. That approach however would increase the risk that the end users will not see their data (as I said, the R package has exactly the same problem for dealing with batches that were made available out of sequence).

If on the other hand a ts value were set on the failed first attempt, there is also a workaround to set the tsMotus field to null on the motus end to force reloading the missing child records, but I suspect the first option applies.

**Comment by leberrigan** [comment]
@denislepage has this been resolved?

**Comment by denislepage** [comment]
As far as I know, the patch option is working as intended in sandbox, but had not yet been implemented in the main db. Done now. Ideally, we'd need a way to go hunt for older missing batches, but we'd then run into the run of bringing batches that would have since been deprecated, so it could get messy. Maria DB also only has a short period of data available. I think we should close this and reevaluate if the problem resurfaces.
