### ISSUE TITLE
Include full log details in Processing Complete email

### ISSUE THREAD

**Issue by jsayers-bsc** [MotusDev/Motus-TO-DO#996]
The "processing complete" email includes a link to the job log on sgdata as well as a summary of some of the key details. Problem is that few people actually bother to look at the log and miss important information -- especially tag registration failures.

I know that eventually tag registration for Nanotags will happen automatically, but that might still be a while.

@Hussell how simple is it for you to just include the log itself in the registration notification email? If it's not a quick thing it's probably not worth doing but if it's one of those "snap your fingers and it's done" sort of things, it would be helpful.

**Comment by Hussell** [comment]
The system is designed in such a way as to make this surprisingly difficult. I've wanted to do this for a long time, but I don't see a way that doesn't involve a shocking amount of work.

**Comment by denislepage** [comment]
A good idea, but seems out of reach for now.
