### ISSUE TITLE
Receiver Rerun - SG-23C5RPI33D16 (7846)

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#997]
[Tag 495 ](https://motus.org/data/tags/edit?projectID=250&id=53728) was deployed here on 12-Jul-21 and detections were confirmed on a Lotek receiver. The tag was later found 4 KM away over a week later, so the bird was active and flying with the tag on. 

The [local receiver deployment plot](https://motus.org/data/receiver/deployment/plot/SG%2D23C5RPI33D16-2021%20Sask%20Passerine%2C%20Bridgeman.png?id=7846&n=100&firstTag=0) appears to include a tag with a metadata mismatch (label 'NOPRO#999999 M.0') that appears to match the expected detections timeline of this tag.

**Comment by Hussell** [comment]
It's ambiguous with a tag registered in 2018 but only deployed this May: https://motus.org/data/tags/edit?projectID=232&id=30996

**Comment by leberrigan** [comment]
Thanks Jeremy. The ambiguous tag is unlikely to interfere with their analysis. I'll let them know what's up.
