### ISSUE TITLE
Missing Data from 2 SensorStations

### ISSUE THREAD

**Issue by leberrigan** [MotusDev/Motus-TO-DO#998]
Today I have identified **two** instances where data appears to be missing from CTT SensorStations. In both cases, only GPS records exist, reboot odometer and antenna pulses (including detections) are missing. 

 **CTT-867459049297757, Project 152**
This SensorStations has stopped receiving radio data since 2021-07-27, however GPS hits are up to date as of 2021-08-04. In addition, the reboot odometer has not indicated the device has reboot as scheduled on 2021-07-31. This station has been operational for a year and has ~20 Purple Martens nearby which were being detected continuously before the antennas drop off.

The fact that all antennas AND the reboot odometer are no longer being updated suggests to me there is a data issue, but there are still GPS hits which is weird. I'm not sure how to approach this problem.

[Deployment plot (#7338)](https://motus.org/data/receiver/deployment/plot/CTT-867459049297757-2020%20NY_LAKE_PLAINS%2C%20Iroquois%20HQ.png?id=7338&n=100&firstTag=0):
![image](https://user-images.githubusercontent.com/35931796/128171163-653b693b-49e3-474c-8699-c228ff6e29d4.png)

**CTT-CD5BCE070809, Project 367**
Similar to above, but beginning over a week earlier, we don't have any data for this receiver since 2021-07-18. They registered a new deployment on 2021-07-27 after swapping antenna ports and that one also only has GPS hits.

[Deployment plot (#7620)](https://motus.org/data/receiver/deployment/plot/CTT%2DCD5BCE070809-2021%20Tennessee%20Warblers%2C%20Massengale%20Mtn%2E%2C%204%5F8%5F21.png?id=7620&n=100&firstTag=0)

[Deployment plot (#7995)](https://motus.org/data/receiver/deployment/plot/CTT%2DCD5BCE070809-2021%20Tennessee%20Warblers%2C%20Massengale%20Mtn%2E%2C%204%5F8%5F21.png?id=7995&n=100&firstTag=0)

**Comment by leberrigan** [comment]
I just got confirmation from the researcher that the CTT website indicates this receiver rebooted on: Jul 31 2021 03:25:32 UTC

**Comment by Hussell** [comment]
We're having a general problem affecting data transfer from all CTT receivers to us. There's apparently a bottleneck in the AWS file transfer that CTT is using to send us the data, so there are 77,000+ files which haven't yet been transferred. @denislepage is working on it.

**Comment by denislepage** [comment]
We had about a week of files to catch up on, and the the script is still zipping up files. We're down to about 15,000 out of 90,000. They should be pushed for processing on sgdata later today, and then it'll likely take another while to get through the backlog. Despite my changes to the script, it seems to have pulled all the pending files on AWS as of yesterday, so we should be caught up to about yesterday after that. The AWS import process is perhaps as much an issue as I thought. The zipping process is also somewhat slow, as each file isn't this big.

**Comment by denislepage** [comment]
Actually, it just started pushing files for processing. The remaining files will only be dealt with next time we run the script. Paul had put a limit of 5,000 zipped files per receiver in a single run (10 x 500), so many files were left behind. I have a change pending that will increase that limit on the sandbox, but that's a minor change. I have increased the frequency of the script to 4 times per day, but @pmorrill should look at ensuring that only one copy can run concurrently, so we don't have multiple instances trying to pull files from AWS at the same time.

**Comment by denislepage** [comment]
The receiver that Bob had reported to us missing CTT data was CTT-867459049219710. There are still some unprocessed files to come for that receiver, but I can see a bunch of new data associated with that receiver in motus.  There are now also 2 new batches of data for CTT-867459049297757 with 1.6 million hits covering the period from 27 Jul to 3 Aug. I think we can close for now.
